In [1]:
import sys
from pathlib import Path
from pyprojroot import here

sys.path.append(str(here()))

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from src.processing import BaselineTransformer, build_pipeline
from sklearn.model_selection import RepeatedStratifiedKFold
from lightgbm import LGBMRegressor
from src.train import cv_result
from sklearn.base import BaseEstimator, TransformerMixin
from scipy.stats import skew
from src.config import cfg
from src.utils import set_seed, load_data
from typing import ClassVar
import warnings
import numpy as np
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
from sklearn.base import BaseEstimator, TransformerMixin

from src.processing import MemoryOptimizer, ToCategory
from src.train import cv_result

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
gseed = cfg.general.seed
set_seed(gseed)

In [5]:
train_path = Path(cfg.paths.train)
test_path = Path(cfg.paths.test)

df_train = pd.read_csv(train_path)
df_test = pd.read_csv(test_path)

In [6]:
X_train, y_train_raw, X_test, test_ids = load_data(cfg, False)

y_train = np.log1p(y_train_raw)

y_binned = pd.qcut(y_train, q=10, labels=False)

rskf = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=gseed)

In [7]:
class FinalTransformer(BaseEstimator, TransformerMixin):
    NONE_COLS: ClassVar[list[str]] = [
        "PoolQC",
        "MiscFeature",
        "Alley",
        "Fence",
        "FireplaceQu",
        "MasVnrType",
        "GarageQual",
        "GarageFinish",
        "GarageType",
        "GarageCond",
        "BsmtQual",
        "BsmtCond",
        "BsmtExposure",
        "BsmtFinType1",
        "BsmtFinType2",
    ]

    ZERO_COLS: ClassVar[list[str]] = [
        "MasVnrArea",
        "GarageYrBlt",
        "GarageArea",
        "GarageCars",
        "BsmtFinSF1",
        "BsmtFinSF2",
        "BsmtUnfSF",
        "TotalBsmtSF",
        "BsmtFullBath",
        "BsmtHalfBath",
    ]

    MODE_COLS: ClassVar[list[str]] = [
        "Electrical",
        "MSZoning",
        "Exterior1st",
        "Exterior2nd",
        "SaleType",
        "KitchenQual",
    ]

    CONTINUOUS_CANDIDATES: ClassVar[list[str]] = [
        "LotFrontage",
        "LotArea",
        "OverallQual",
        "OverallCond",
        "MasVnrArea",
        "BsmtFinSF1",
        "BsmtFinSF2",
        "BsmtUnfSF",
        "TotalBsmtSF",
        "1stFlrSF",
        "2ndFlrSF",
        "GrLivArea",
        "BsmtFullBath",
        "FullBath",
        "HalfBath",
        "BedroomAbvGr",
        "KitchenAbvGr",
        "TotRmsAbvGrd",
        "Fireplaces",
        "GarageCars",
        "GarageArea",
        "WoodDeckSF",
        "OpenPorchSF",
        "EnclosedPorch",
        "ScreenPorch",
        "PoolArea",
        "MoSold",
        "YrSold",
        "HouseAge",
        "RemodAge",
        "GarageAge",
        "TotalSF",
        "TotalBathrooms",
        "TotalPorchSF",
        "AreaPerRoom",
        "LivingAreaRatio",
    ]

    def _fill_none_and_zero(self, X):
        X = X.copy()

        for col in self.NONE_COLS:
            X[col] = X[col].fillna("None")

        for col in self.ZERO_COLS:
            X[col] = X[col].fillna(0)

        return X

    def _engineer_features(self, X):
        X = X.copy()

        X["MoSold_sin"] = np.sin(2 * np.pi * X["MoSold"] / 12)
        X["MoSold_cos"] = np.cos(2 * np.pi * X["MoSold"] / 12)

        X["HouseAge"] = X["YrSold"] - X["YearBuilt"]
        X["RemodAge"] = X["YrSold"] - X["YearRemodAdd"]
        X["GarageAge"] = X["YrSold"] - X["GarageYrBlt"]

        X.loc[X["GarageType"] == "None", "GarageAge"] = 0

        X["IsRemodeled"] = (X["YearBuilt"] != X["YearRemodAdd"]).astype(int)

        X["TotalSF"] = X["TotalBsmtSF"] + X["1stFlrSF"] + X["2ndFlrSF"]
        X["TotalPorchSF"] = (
            X["OpenPorchSF"] + X["EnclosedPorch"] + X["3SsnPorch"] + X["ScreenPorch"]
        )
        X["TotalBathrooms"] = (
            X["FullBath"]
            + 0.5 * X["HalfBath"]
            + X["BsmtFullBath"]
            + 0.5 * X["BsmtHalfBath"]
        )

        X["AreaPerRoom"] = X["GrLivArea"] / X["TotRmsAbvGrd"].replace(0, np.nan)
        X["LivingAreaRatio"] = X["GrLivArea"] / X["LotArea"].replace(0, np.nan)

        return X

    def fit(self, X_original, y=None):
        X = X_original.copy()

        self.lotfrontage_medians2_ = X.groupby(by=["Neighborhood", "LotConfig"])[
            "LotFrontage"
        ].median()

        self.lotfrontage_medians1_ = X.groupby(by=["Neighborhood"])[
            "LotFrontage"
        ].median()

        self.lotfrontage_global_median_ = X["LotFrontage"].median()

        self.modes_ = {col: X[col].mode()[0] for col in self.MODE_COLS}

        X = self._fill_none_and_zero(X)
        X = self._engineer_features(X)

        skewed = X[self.CONTINUOUS_CANDIDATES].apply(lambda x: skew(x.dropna()))
        self.skewed_cols_ = skewed[abs(skewed) > 0.85].index.tolist()

        return self

    def transform(self, X_original):
        X = X_original.copy()

        X = self._fill_none_and_zero(X)

        keys2 = list(zip(X["Neighborhood"], X["LotConfig"]))
        filled_2 = pd.Series(keys2, index=X.index).map(self.lotfrontage_medians2_)
        X["LotFrontage"] = X["LotFrontage"].fillna(filled_2)

        filled_1 = X["Neighborhood"].map(self.lotfrontage_medians1_)
        X["LotFrontage"] = X["LotFrontage"].fillna(filled_1)

        X["LotFrontage"] = X["LotFrontage"].fillna(self.lotfrontage_global_median_)

        for col, mode_value in self.modes_.items():
            X[col] = X[col].fillna(mode_value)

        X["Functional"] = X["Functional"].fillna("Typ")

        if "MSSubClass" in X.columns:
            X["MSSubClass"] = X["MSSubClass"].astype(str)

        X = self._engineer_features(X)

        for col in [
            "Id",
            "Utilities",
            "3SsnPorch",
            "BsmtHalfBath",
            "Condition2",
            "GarageYrBlt",
            "Heating",
            "LowQualFinSF",
            "MiscVal",
            "PoolQC",
            "RoofMatl",
            "Street",
            "YearBuilt",
            "YearRemodAdd",
        ]:
            if col in X.columns:
                X = X.drop(columns=col)

        for col in self.skewed_cols_:
            if col in X.columns:
                X[col] = np.log1p(X[col])

        return X

In [8]:
num_columns = [
    "LotFrontage",
    "LotArea",
    "OverallQual",
    "OverallCond",
    # "YearBuilt",        # удалено -> заменено на HouseAge
    # "YearRemodAdd",     # удалено -> заменено на RemodAge
    "MasVnrArea",
    "BsmtFinSF1",
    "BsmtFinSF2",
    "BsmtUnfSF",
    "TotalBsmtSF",
    "1stFlrSF",
    "2ndFlrSF",
    # "LowQualFinSF",   # исключено - useless_features (permutation importance)
    "GrLivArea",
    "BsmtFullBath",
    # "BsmtHalfBath",   # исключено - useless_features (permutation importance)
    "FullBath",
    "HalfBath",
    "BedroomAbvGr",
    "KitchenAbvGr",
    "TotRmsAbvGrd",
    "Fireplaces",
    # "GarageYrBlt",      # удалено -> заменено на GarageAge
    "GarageCars",
    "GarageArea",
    "WoodDeckSF",
    "OpenPorchSF",
    "EnclosedPorch",
    # "3SsnPorch",      # исключено - useless_features (permutation importance)
    "ScreenPorch",
    "PoolArea",  # лучше пусть останется упоминание о бассейне
    # "MiscVal",        # исключено - useless_features (permutation importance)
    "MoSold",
    "YrSold",
    # --- новые непрерывные/счётные признаки ---
    "HouseAge",
    "RemodAge",
    "GarageAge",
    "TotalSF",
    "TotalBathrooms",
    "TotalPorchSF",
    "AreaPerRoom",
    "LivingAreaRatio",
    "MoSold_sin",
    "MoSold_cos",
    # --- бинарные флаги (0/1) ---
    "IsRemodeled",
    # "IsNewHouse",   # исключено - useless_features
    # "HasPool",      # исключено - useless_features
    # "HasGarage",    # исключено - useless_features
    # "HasBsmt",      # исключено - useless_features
    # "HasFireplace", # исключено - useless_features
    # "Has2ndFloor",  # исключено - useless_features
]

ordinal_columns = [
    "LotShape",
    "LandSlope",
    "ExterQual",
    "ExterCond",
    "BsmtQual",
    "BsmtCond",
    "BsmtExposure",
    "BsmtFinType1",
    "BsmtFinType2",
    "HeatingQC",
    "KitchenQual",
    "Functional",
    "FireplaceQu",
    "GarageFinish",
    "GarageQual",
    "GarageCond",
    "PavedDrive",
    # "PoolQC",   # исключено - useless_features
    "CentralAir",
]

ordinal_categories = [
    # порядок соответствует ordinal_columns выше (PoolQC и его категория удалены)
    ["IR3", "IR2", "IR1", "Reg"],
    ["Sev", "Mod", "Gtl"],
    ["Po", "Fa", "TA", "Gd", "Ex"],
    ["Po", "Fa", "TA", "Gd", "Ex"],
    ["None", "Po", "Fa", "TA", "Gd", "Ex"],
    ["None", "Po", "Fa", "TA", "Gd", "Ex"],
    ["None", "No", "Mn", "Av", "Gd"],
    ["None", "Unf", "LwQ", "Rec", "BLQ", "ALQ", "GLQ"],
    ["None", "Unf", "LwQ", "Rec", "BLQ", "ALQ", "GLQ"],
    ["Po", "Fa", "TA", "Gd", "Ex"],
    ["Po", "Fa", "TA", "Gd", "Ex"],
    ["Sal", "Sev", "Maj2", "Maj1", "Mod", "Min2", "Min1", "Typ"],
    ["None", "Po", "Fa", "TA", "Gd", "Ex"],
    ["None", "Unf", "RFn", "Fin"],
    ["None", "Po", "Fa", "TA", "Gd", "Ex"],
    ["None", "Po", "Fa", "TA", "Gd", "Ex"],
    ["N", "P", "Y"],
    # ["None", "Fa", "TA", "Gd", "Ex"],  # было для PoolQC - удалено
    ["N", "Y"],
]

ohe_columns = [
    "Fence",
    "Electrical",
    "MSSubClass",
    "MSZoning",
    # "Street",        # исключено - useless_features
    "Alley",
    "LandContour",
    "LotConfig",
    "Neighborhood",
    "Condition1",
    # "Condition2",    # исключено - useless_features
    "BldgType",
    "HouseStyle",
    "RoofStyle",
    # "RoofMatl",      # исключено - useless_features
    "Exterior1st",
    "Exterior2nd",
    "MasVnrType",
    "Foundation",
    # "Heating",       # исключено - useless_features
    "GarageType",
    "MiscFeature",
    "SaleType",
    "SaleCondition",
]
tree_pipe = Pipeline(
    [
        ("processor", FinalTransformer()),
        ("memory_optimizer", MemoryOptimizer()),
        (
            "column_transformer",
            ColumnTransformer(
                transformers=[
                    ("num_features", "passthrough", num_columns),
                    (
                        "cat_features_oe",
                        OrdinalEncoder(
                            categories=ordinal_categories,
                            handle_unknown="use_encoded_value",
                            unknown_value=-1,
                        ),
                        ordinal_columns,
                    ),
                    (
                        "cat_features_ohe",
                        "passthrough",
                        ohe_columns,
                    ),
                ],
                verbose_feature_names_out=False,
            ).set_output(transform="pandas"),
        ),
        ("to_category", ToCategory(ohe_columns)),
    ]
)

from sklearn.preprocessing import StandardScaler

lin_pipe = Pipeline(
    [
        ("processor", FinalTransformer()),
        ("memory_optimizer", MemoryOptimizer()),
        (
            "column_transformer",
            ColumnTransformer(
                transformers=[
                    (
                        "num_features",
                        StandardScaler(),
                        num_columns,
                    ),
                    (
                        "cat_features_oe",
                        Pipeline(
                            [
                                (
                                    "encode",
                                    OrdinalEncoder(
                                        categories=ordinal_categories,
                                        handle_unknown="use_encoded_value",
                                        unknown_value=-1,
                                    ),
                                ),
                                ("scale", StandardScaler()),
                            ]
                        ),
                        ordinal_columns,
                    ),
                    (
                        "cat_features_ohe",
                        OneHotEncoder(
                            drop="first",
                            handle_unknown="infrequent_if_exist",
                            min_frequency=10,
                            sparse_output=False,
                        ),
                        ohe_columns,
                    ),
                ],
                verbose_feature_names_out=False,
            ).set_output(transform="pandas"),
        ),
    ]
)

assert len(ordinal_columns) == len(ordinal_categories), (
    "Рассинхрон между колонками и категориями!"
)

### baseline

In [9]:
from lightgbm import LGBMRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor,
    HistGradientBoostingRegressor,
)
from catboost import CatBoostRegressor

In [19]:
fitted_models, oof_preds, metrics, val_scores = cv_result(
    LGBMRegressor(random_state=gseed, verbosity=-1),
    X_train,
    y_train,
    y_binned,
    rskf,
    tree_pipe,
    "baseline_model",
)
metrics

baseline_model:   0%|          | 0/50 [00:00<?, ?fold/s]

,model,TRAIN_rmsle_MEAN,TRAIN_rmsle_STD,VAL_rmsle_MEAN,VAL_rmsle_STD,OOF_rmsle
0,baseline_model,0.03689,0.000739,0.123829,0.012789,0.120986

In [35]:
fitted_models, oof_preds, metrics, val_scores = cv_result(
    LinearRegression(), X_train, y_train, y_binned, rskf, lin_pipe, "lin_reg"
)
metrics

lin_reg:   0%|          | 0/50 [00:00<?, ?fold/s]

,model,TRAIN_rmsle_MEAN,TRAIN_rmsle_STD,VAL_rmsle_MEAN,VAL_rmsle_STD,OOF_rmsle
0,lin_reg,0.093288,0.00143,0.11321,0.013364,0.112858

In [73]:
fitted_models, oof_preds, metrics, val_scores = cv_result(
    Ridge(), X_train, y_train, y_binned, rskf, lin_pipe, "ridge_reg"
)
metrics

,model,TRAIN_rmsle_MEAN,TRAIN_rmsle_STD,VAL_rmsle_MEAN,VAL_rmsle_STD,OOF_rmsle
0,ridge_reg,0.0938,0.001435,0.110749,0.013143,0.110652

In [ ]:
fitted_models, oof_preds, metrics, val_scores = cv_result(
    Lasso(alpha=0.01), X_train, y_train, y_binned, rskf, lin_pipe, "lasso_reg"
)
metrics

lasso_reg:   0%|          | 0/50 [00:00<?, ?fold/s]

,model,TRAIN_rmsle_MEAN,TRAIN_rmsle_STD,VAL_rmsle_MEAN,VAL_rmsle_STD,OOF_rmsle
0,lasso_reg,0.119912,0.001395,0.122319,0.012302,0.122706

In [ ]:
fitted_models, oof_preds, metrics, val_scores = cv_result(
    ElasticNet(alpha=0.01), X_train, y_train, y_binned, rskf, lin_pipe, "elastic_net"
)
metrics

elastic_net:   0%|          | 0/50 [00:00<?, ?fold/s]

,model,TRAIN_rmsle_MEAN,TRAIN_rmsle_STD,VAL_rmsle_MEAN,VAL_rmsle_STD,OOF_rmsle
0,elastic_net,0.116877,0.001417,0.120102,0.012315,0.120561

In [88]:
fitted_models, oof_preds, metrics, val_scores = cv_result(
    KNeighborsRegressor(), X_train, y_train, y_binned, rskf, lin_pipe, "knn_regressor"
)
metrics

,model,TRAIN_rmsle_MEAN,TRAIN_rmsle_STD,VAL_rmsle_MEAN,VAL_rmsle_STD,OOF_rmsle
0,knn_regressor,0.128849,0.001532,0.158134,0.01347,0.156096

In [89]:
fitted_models, oof_preds, metrics, val_scores = cv_result(
    SVR(C=0.5), X_train, y_train, y_binned, rskf, lin_pipe, "svr"
)
metrics

svr:   0%|          | 0/50 [00:00<?, ?fold/s]

,model,TRAIN_rmsle_MEAN,TRAIN_rmsle_STD,VAL_rmsle_MEAN,VAL_rmsle_STD,OOF_rmsle
0,svr,0.088035,0.001245,0.140214,0.01796,0.140826

In [ ]:
fitted_models, oof_preds, metrics, val_scores = cv_result(
    RandomForestRegressor(random_state=gseed),
    X_train,
    y_train,
    y_binned,
    rskf,
    lin_pipe,
    "random_forest",
)
metrics

random_forest:   0%|          | 0/50 [00:00<?, ?fold/s]

,model,TRAIN_rmsle_MEAN,TRAIN_rmsle_STD,VAL_rmsle_MEAN,VAL_rmsle_STD,OOF_rmsle
0,random_forest,0.051303,0.000824,0.136488,0.012877,0.135401

In [ ]:
fitted_models, oof_preds, metrics, val_scores = cv_result(
    GradientBoostingRegressor(),
    X_train,
    y_train,
    y_binned,
    rskf,
    lin_pipe,
    "sklearn_gbdt",
)
metrics

,model,TRAIN_rmsle_MEAN,TRAIN_rmsle_STD,VAL_rmsle_MEAN,VAL_rmsle_STD,OOF_rmsle
0,sklearn_gbdt,0.077669,0.001202,0.120881,0.013783,0.119422

In [ ]:
fitted_models, oof_preds, metrics, val_scores = cv_result(
    HistGradientBoostingRegressor(),
    X_train,
    y_train,
    y_binned,
    rskf,
    lin_pipe,
    "sklearn_hist_gbdt",
)
metrics

,model,TRAIN_rmsle_MEAN,TRAIN_rmsle_STD,VAL_rmsle_MEAN,VAL_rmsle_STD,OOF_rmsle
0,sklearn_hist_gbdt,0.039042,0.000877,0.125394,0.012208,0.122598

In [ ]:
fitted_models, oof_preds, metrics, val_scores = cv_result(
    HistGradientBoostingRegressor(),
    X_train,
    y_train,
    y_binned,
    rskf,
    lin_pipe,
    "sklearn_hist_gbdt",
)
metrics

,model,TRAIN_rmsle_MEAN,TRAIN_rmsle_STD,VAL_rmsle_MEAN,VAL_rmsle_STD,OOF_rmsle
0,sklearn_hist_gbdt,0.039042,0.000877,0.125394,0.012208,0.122598

In [25]:
fitted_models, oof_preds, metrics, val_scores = cv_result(
    CatBoostRegressor(random_state=gseed, loss_function="RMSE"),
    X_train,
    y_train,
    y_binned,
    rskf,
    tree_pipe,
    fit_params={"model__cat_features": list(ohe_columns)},
)
metrics

CV folds:   0%|          | 0/50 [00:00<?, ?fold/s]

Learning rate set to 0.042738
0:	learn: 0.3875577	total: 22.6ms	remaining: 22.6s
1:	learn: 0.3769581	total: 48.9ms	remaining: 24.4s
2:	learn: 0.3666456	total: 82.4ms	remaining: 27.4s
3:	learn: 0.3570172	total: 122ms	remaining: 30.3s
4:	learn: 0.3474048	total: 149ms	remaining: 29.6s
5:	learn: 0.3383886	total: 173ms	remaining: 28.7s
6:	learn: 0.3297794	total: 197ms	remaining: 27.9s
7:	learn: 0.3211660	total: 224ms	remaining: 27.8s
8:	learn: 0.3131202	total: 250ms	remaining: 27.6s
9:	learn: 0.3049609	total: 274ms	remaining: 27.1s
10:	learn: 0.2970141	total: 299ms	remaining: 26.9s
11:	learn: 0.2893075	total: 325ms	remaining: 26.7s
12:	learn: 0.2829105	total: 352ms	remaining: 26.7s
13:	learn: 0.2767194	total: 380ms	remaining: 26.7s
14:	learn: 0.2700917	total: 404ms	remaining: 26.6s
15:	learn: 0.2642530	total: 430ms	remaining: 26.4s
16:	learn: 0.2583854	total: 455ms	remaining: 26.3s
17:	learn: 0.2524203	total: 483ms	remaining: 26.3s
18:	learn: 0.2471084	total: 510ms	remaining: 26.4s
19:	learn: 0.2418435	total: 536ms	remaining: 26.3s
20:	learn: 0.2372376	total: 561ms	remaining: 26.1s
21:	learn: 0.2322764	total: 585ms	remaining: 26s
22:	learn: 0.2271714	total: 611ms	remaining: 25.9s
23:	learn: 0.2230845	total: 638ms	remaining: 25.9s
24:	learn: 0.2189527	total: 662ms	remaining: 25.8s
25:	learn: 0.2148166	total: 691ms	remaining: 25.9s
26:	learn: 0.2107725	total: 721ms	remaining: 26s
27:	learn: 0.2068013	total: 749ms	remaining: 26s
28:	learn: 0.2030296	total: 779ms	remaining: 26.1s
29:	learn: 0.1992838	total: 804ms	remaining: 26s
30:	learn: 0.1956463	total: 830ms	remaining: 26s
31:	learn: 0.1927314	total: 856ms	remaining: 25.9s
32:	learn: 0.1896269	total: 883ms	remaining: 25.9s
33:	learn: 0.1865820	total: 911ms	remaining: 25.9s
34:	learn: 0.1837030	total: 941ms	remaining: 25.9s
35:	learn: 0.1812249	total: 968ms	remaining: 25.9s
36:	learn: 0.1785143	total: 999ms	remaining: 26s
37:	learn: 0.1759630	total: 1.03s	remaining: 26.1s
38:	learn: 0.1735731	total: 1.06s	remaining: 26.2s
39:	learn: 0.1709274	total: 1.09s	remaining: 26.2s
40:	learn: 0.1685282	total: 1.14s	remaining: 26.7s
41:	learn: 0.1664887	total: 1.17s	remaining: 26.8s
42:	learn: 0.1640952	total: 1.2s	remaining: 26.7s
43:	learn: 0.1619321	total: 1.23s	remaining: 26.7s
44:	learn: 0.1601927	total: 1.26s	remaining: 26.7s
45:	learn: 0.1581161	total: 1.29s	remaining: 26.7s
46:	learn: 0.1562169	total: 1.32s	remaining: 26.7s
47:	learn: 0.1545586	total: 1.35s	remaining: 26.8s
48:	learn: 0.1529728	total: 1.38s	remaining: 26.8s
49:	learn: 0.1511615	total: 1.41s	remaining: 26.8s
50:	learn: 0.1497267	total: 1.44s	remaining: 26.8s
51:	learn: 0.1481954	total: 1.47s	remaining: 26.8s
52:	learn: 0.1467744	total: 1.5s	remaining: 26.7s
53:	learn: 0.1455140	total: 1.52s	remaining: 26.7s
54:	learn: 0.1441518	total: 1.55s	remaining: 26.6s
55:	learn: 0.1427782	total: 1.58s	remaining: 26.6s
56:	learn: 0.1413391	total: 1.6s	remaining: 26.5s
57:	learn: 0.1400651	total: 1.64s	remaining: 26.6s
58:	learn: 0.1388118	total: 1.67s	remaining: 26.6s
59:	learn: 0.1375674	total: 1.7s	remaining: 26.6s
60:	learn: 0.1364669	total: 1.72s	remaining: 26.5s
61:	learn: 0.1354237	total: 1.75s	remaining: 26.5s
62:	learn: 0.1343551	total: 1.78s	remaining: 26.5s
63:	learn: 0.1332984	total: 1.81s	remaining: 26.5s
64:	learn: 0.1324839	total: 1.84s	remaining: 26.5s
65:	learn: 0.1316010	total: 1.87s	remaining: 26.5s
66:	learn: 0.1308574	total: 1.9s	remaining: 26.5s
67:	learn: 0.1299891	total: 1.93s	remaining: 26.5s
68:	learn: 0.1290442	total: 1.96s	remaining: 26.5s
69:	learn: 0.1283411	total: 1.99s	remaining: 26.4s
70:	learn: 0.1275888	total: 2.02s	remaining: 26.4s
71:	learn: 0.1268635	total: 2.05s	remaining: 26.5s
72:	learn: 0.1261023	total: 2.08s	remaining: 26.5s
73:	learn: 0.1254348	total: 2.12s	remaining: 26.5s
74:	learn: 0.1247148	total: 2.15s	remaining: 26.5s
75:	learn: 0.1239481	total: 2.18s	remaining: 26.5s
76:	learn: 0.1233873	total: 2.21s	remaining: 26.5s
77:	learn: 0.1227596	total: 2.25s	remaining: 26.5s
78:	learn: 0.1221567	total: 2.28s	remaining: 26.5s
79:	learn: 0.1214316	total: 2.31s	remaining: 26.5s
80:	learn: 0.1208292	total: 2.34s	remaining: 26.6s
81:	learn: 0.1203558	total: 2.37s	remaining: 26.6s
82:	learn: 0.1199376	total: 2.4s	remaining: 26.6s
83:	learn: 0.1195124	total: 2.44s	remaining: 26.6s
84:	learn: 0.1189492	total: 2.47s	remaining: 26.6s
85:	learn: 0.1184269	total: 2.49s	remaining: 26.5s
86:	learn: 0.1179859	total: 2.52s	remaining: 26.5s
87:	learn: 0.1175740	total: 2.56s	remaining: 26.5s
88:	learn: 0.1170478	total: 2.59s	remaining: 26.5s
89:	learn: 0.1165519	total: 2.62s	remaining: 26.5s
90:	learn: 0.1161165	total: 2.65s	remaining: 26.5s
91:	learn: 0.1156440	total: 2.68s	remaining: 26.4s
92:	learn: 0.1152532	total: 2.71s	remaining: 26.5s
93:	learn: 0.1148830	total: 2.75s	remaining: 26.5s
94:	learn: 0.1144785	total: 2.78s	remaining: 26.5s
95:	learn: 0.1141722	total: 2.81s	remaining: 26.4s
96:	learn: 0.1137071	total: 2.84s	remaining: 26.4s
97:	learn: 0.1132172	total: 2.87s	remaining: 26.4s
98:	learn: 0.1129275	total: 2.9s	remaining: 26.4s
99:	learn: 0.1125192	total: 2.93s	remaining: 26.4s
100:	learn: 0.1121245	total: 2.96s	remaining: 26.4s
101:	learn: 0.1117408	total: 2.99s	remaining: 26.4s
102:	learn: 0.1113035	total: 3.02s	remaining: 26.3s
103:	learn: 0.1109708	total: 3.05s	remaining: 26.3s
104:	learn: 0.1105513	total: 3.08s	remaining: 26.3s
105:	learn: 0.1102620	total: 3.12s	remaining: 26.3s
106:	learn: 0.1099274	total: 3.15s	remaining: 26.3s
107:	learn: 0.1095433	total: 3.19s	remaining: 26.3s
108:	learn: 0.1092492	total: 3.22s	remaining: 26.3s
109:	learn: 0.1089419	total: 3.26s	remaining: 26.4s
110:	learn: 0.1086357	total: 3.31s	remaining: 26.5s
111:	learn: 0.1082710	total: 3.33s	remaining: 26.4s
112:	learn: 0.1079971	total: 3.37s	remaining: 26.4s
113:	learn: 0.1076427	total: 3.4s	remaining: 26.5s
114:	learn: 0.1073541	total: 3.44s	remaining: 26.4s
115:	learn: 0.1071184	total: 3.46s	remaining: 26.4s
116:	learn: 0.1068045	total: 3.5s	remaining: 26.4s
117:	learn: 0.1065250	total: 3.53s	remaining: 26.4s
118:	learn: 0.1062187	total: 3.56s	remaining: 26.3s
119:	learn: 0.1059748	total: 3.59s	remaining: 26.3s
120:	learn: 0.1056973	total: 3.62s	remaining: 26.3s
121:	learn: 0.1053444	total: 3.65s	remaining: 26.3s
122:	learn: 0.1051288	total: 3.68s	remaining: 26.2s
123:	learn: 0.1048959	total: 3.71s	remaining: 26.2s
124:	learn: 0.1046383	total: 3.74s	remaining: 26.2s
125:	learn: 0.1043832	total: 3.77s	remaining: 26.1s
126:	learn: 0.1041502	total: 3.8s	remaining: 26.1s
127:	learn: 0.1038728	total: 3.83s	remaining: 26.1s
128:	learn: 0.1035718	total: 3.86s	remaining: 26.1s
129:	learn: 0.1033536	total: 3.89s	remaining: 26s
130:	learn: 0.1032007	total: 3.91s	remaining: 26s
131:	learn: 0.1028562	total: 3.94s	remaining: 25.9s
132:	learn: 0.1025964	total: 3.97s	remaining: 25.9s
133:	learn: 0.1023019	total: 4.01s	remaining: 25.9s
134:	learn: 0.1021125	total: 4.04s	remaining: 25.9s
135:	learn: 0.1018070	total: 4.07s	remaining: 25.9s
136:	learn: 0.1015554	total: 4.1s	remaining: 25.8s
137:	learn: 0.1014224	total: 4.12s	remaining: 25.8s
138:	learn: 0.1013513	total: 4.15s	remaining: 25.7s
139:	learn: 0.1011317	total: 4.18s	remaining: 25.7s
140:	learn: 0.1008832	total: 4.21s	remaining: 25.7s
141:	learn: 0.1006612	total: 4.25s	remaining: 25.7s
142:	learn: 0.1004810	total: 4.28s	remaining: 25.6s
143:	learn: 0.1002757	total: 4.3s	remaining: 25.6s
144:	learn: 0.1000542	total: 4.34s	remaining: 25.6s
145:	learn: 0.0997767	total: 4.37s	remaining: 25.6s
146:	learn: 0.0995698	total: 4.4s	remaining: 25.5s
147:	learn: 0.0994034	total: 4.43s	remaining: 25.5s
148:	learn: 0.0992333	total: 4.46s	remaining: 25.5s
149:	learn: 0.0989453	total: 4.5s	remaining: 25.5s
150:	learn: 0.0987172	total: 4.53s	remaining: 25.5s
151:	learn: 0.0985072	total: 4.56s	remaining: 25.4s
152:	learn: 0.0983011	total: 4.59s	remaining: 25.4s
153:	learn: 0.0980987	total: 4.62s	remaining: 25.4s
154:	learn: 0.0979955	total: 4.64s	remaining: 25.3s
155:	learn: 0.0978934	total: 4.68s	remaining: 25.3s
156:	learn: 0.0977149	total: 4.71s	remaining: 25.3s
157:	learn: 0.0975716	total: 4.74s	remaining: 25.2s
158:	learn: 0.0973360	total: 4.76s	remaining: 25.2s
159:	learn: 0.0972125	total: 4.79s	remaining: 25.2s
160:	learn: 0.0970564	total: 4.82s	remaining: 25.1s
161:	learn: 0.0968222	total: 4.85s	remaining: 25.1s
162:	learn: 0.0966153	total: 4.89s	remaining: 25.1s
163:	learn: 0.0964536	total: 4.92s	remaining: 25.1s
164:	learn: 0.0963753	total: 4.94s	remaining: 25s
165:	learn: 0.0962474	total: 4.97s	remaining: 25s
166:	learn: 0.0961440	total: 5s	remaining: 24.9s
167:	learn: 0.0959900	total: 5.03s	remaining: 24.9s
168:	learn: 0.0958349	total: 5.06s	remaining: 24.9s
169:	learn: 0.0956980	total: 5.09s	remaining: 24.8s
170:	learn: 0.0955137	total: 5.12s	remaining: 24.8s
171:	learn: 0.0953131	total: 5.15s	remaining: 24.8s
172:	learn: 0.0950397	total: 5.18s	remaining: 24.8s
173:	learn: 0.0949057	total: 5.21s	remaining: 24.7s
174:	learn: 0.0947856	total: 5.24s	remaining: 24.7s
175:	learn: 0.0945480	total: 5.27s	remaining: 24.7s
176:	learn: 0.0944023	total: 5.3s	remaining: 24.6s
177:	learn: 0.0942278	total: 5.33s	remaining: 24.6s
178:	learn: 0.0940636	total: 5.36s	remaining: 24.6s
179:	learn: 0.0939445	total: 5.39s	remaining: 24.6s
180:	learn: 0.0937922	total: 5.42s	remaining: 24.5s
181:	learn: 0.0937116	total: 5.46s	remaining: 24.5s
182:	learn: 0.0935693	total: 5.49s	remaining: 24.5s
183:	learn: 0.0934329	total: 5.52s	remaining: 24.5s
184:	learn: 0.0933796	total: 5.54s	remaining: 24.4s
185:	learn: 0.0931989	total: 5.58s	remaining: 24.4s
186:	learn: 0.0930364	total: 5.61s	remaining: 24.4s
187:	learn: 0.0929406	total: 5.64s	remaining: 24.4s
188:	learn: 0.0927898	total: 5.67s	remaining: 24.3s
189:	learn: 0.0926760	total: 5.7s	remaining: 24.3s
190:	learn: 0.0925713	total: 5.73s	remaining: 24.3s
191:	learn: 0.0923292	total: 5.76s	remaining: 24.2s
192:	learn: 0.0922405	total: 5.79s	remaining: 24.2s
193:	learn: 0.0920263	total: 5.82s	remaining: 24.2s
194:	learn: 0.0919914	total: 5.85s	remaining: 24.1s
195:	learn: 0.0918532	total: 5.88s	remaining: 24.1s
196:	learn: 0.0916780	total: 5.9s	remaining: 24.1s
197:	learn: 0.0916249	total: 5.93s	remaining: 24s
198:	learn: 0.0914181	total: 5.96s	remaining: 24s
199:	learn: 0.0913176	total: 6s	remaining: 24s
200:	learn: 0.0911541	total: 6.03s	remaining: 24s
201:	learn: 0.0911075	total: 6.05s	remaining: 23.9s
202:	learn: 0.0909529	total: 6.08s	remaining: 23.9s
203:	learn: 0.0908769	total: 6.11s	remaining: 23.9s
204:	learn: 0.0908346	total: 6.14s	remaining: 23.8s
205:	learn: 0.0906411	total: 6.17s	remaining: 23.8s
206:	learn: 0.0905608	total: 6.21s	remaining: 23.8s
207:	learn: 0.0904156	total: 6.24s	remaining: 23.7s
208:	learn: 0.0903352	total: 6.26s	remaining: 23.7s
209:	learn: 0.0901635	total: 6.29s	remaining: 23.7s
210:	learn: 0.0899646	total: 6.32s	remaining: 23.6s
211:	learn: 0.0898262	total: 6.35s	remaining: 23.6s
212:	learn: 0.0897609	total: 6.38s	remaining: 23.6s
213:	learn: 0.0897178	total: 6.41s	remaining: 23.5s
214:	learn: 0.0895420	total: 6.44s	remaining: 23.5s
215:	learn: 0.0894415	total: 6.47s	remaining: 23.5s
216:	learn: 0.0892564	total: 6.5s	remaining: 23.5s
217:	learn: 0.0892070	total: 6.53s	remaining: 23.4s
218:	learn: 0.0890087	total: 6.56s	remaining: 23.4s
219:	learn: 0.0889249	total: 6.59s	remaining: 23.4s
220:	learn: 0.0888833	total: 6.62s	remaining: 23.3s
221:	learn: 0.0887703	total: 6.64s	remaining: 23.3s
222:	learn: 0.0886821	total: 6.68s	remaining: 23.3s
223:	learn: 0.0886230	total: 6.71s	remaining: 23.3s
224:	learn: 0.0885296	total: 6.75s	remaining: 23.2s
225:	learn: 0.0884440	total: 6.78s	remaining: 23.2s
226:	learn: 0.0883545	total: 6.8s	remaining: 23.2s
227:	learn: 0.0882977	total: 6.84s	remaining: 23.1s
228:	learn: 0.0881740	total: 6.87s	remaining: 23.1s
229:	learn: 0.0881423	total: 6.9s	remaining: 23.1s
230:	learn: 0.0878983	total: 6.93s	remaining: 23.1s
231:	learn: 0.0878747	total: 6.97s	remaining: 23.1s
232:	learn: 0.0877703	total: 7s	remaining: 23.1s
233:	learn: 0.0876061	total: 7.03s	remaining: 23s
234:	learn: 0.0875394	total: 7.06s	remaining: 23s
235:	learn: 0.0874428	total: 7.09s	remaining: 22.9s
236:	learn: 0.0874082	total: 7.12s	remaining: 22.9s
237:	learn: 0.0872998	total: 7.15s	remaining: 22.9s
238:	learn: 0.0871842	total: 7.18s	remaining: 22.9s
239:	learn: 0.0870701	total: 7.21s	remaining: 22.8s
240:	learn: 0.0869802	total: 7.24s	remaining: 22.8s
241:	learn: 0.0868516	total: 7.27s	remaining: 22.8s
242:	learn: 0.0868171	total: 7.3s	remaining: 22.8s
243:	learn: 0.0866864	total: 7.34s	remaining: 22.7s
244:	learn: 0.0865842	total: 7.37s	remaining: 22.7s
245:	learn: 0.0865418	total: 7.4s	remaining: 22.7s
246:	learn: 0.0865126	total: 7.43s	remaining: 22.6s
247:	learn: 0.0864341	total: 7.45s	remaining: 22.6s
248:	learn: 0.0862585	total: 7.48s	remaining: 22.6s
249:	learn: 0.0861705	total: 7.51s	remaining: 22.5s
250:	learn: 0.0859945	total: 7.55s	remaining: 22.5s
251:	learn: 0.0858876	total: 7.58s	remaining: 22.5s
252:	learn: 0.0857458	total: 7.63s	remaining: 22.5s
253:	learn: 0.0857025	total: 7.66s	remaining: 22.5s
254:	learn: 0.0855235	total: 7.68s	remaining: 22.4s
255:	learn: 0.0854270	total: 7.71s	remaining: 22.4s
256:	learn: 0.0853073	total: 7.75s	remaining: 22.4s
257:	learn: 0.0850341	total: 7.77s	remaining: 22.4s
258:	learn: 0.0849071	total: 7.8s	remaining: 22.3s
259:	learn: 0.0848129	total: 7.83s	remaining: 22.3s
260:	learn: 0.0847899	total: 7.86s	remaining: 22.3s
261:	learn: 0.0846322	total: 7.89s	remaining: 22.2s
262:	learn: 0.0844965	total: 7.92s	remaining: 22.2s
263:	learn: 0.0844688	total: 7.95s	remaining: 22.2s
264:	learn: 0.0843887	total: 7.98s	remaining: 22.1s
265:	learn: 0.0842691	total: 8.01s	remaining: 22.1s
266:	learn: 0.0840767	total: 8.04s	remaining: 22.1s
267:	learn: 0.0840545	total: 8.07s	remaining: 22s
268:	learn: 0.0840373	total: 8.1s	remaining: 22s
269:	learn: 0.0839649	total: 8.13s	remaining: 22s
270:	learn: 0.0839073	total: 8.16s	remaining: 21.9s
271:	learn: 0.0838115	total: 8.19s	remaining: 21.9s
272:	learn: 0.0837835	total: 8.22s	remaining: 21.9s
273:	learn: 0.0836711	total: 8.25s	remaining: 21.9s
274:	learn: 0.0836465	total: 8.28s	remaining: 21.8s
275:	learn: 0.0835947	total: 8.3s	remaining: 21.8s
276:	learn: 0.0835196	total: 8.33s	remaining: 21.8s
277:	learn: 0.0834146	total: 8.36s	remaining: 21.7s
278:	learn: 0.0832340	total: 8.39s	remaining: 21.7s
279:	learn: 0.0831390	total: 8.42s	remaining: 21.7s
280:	learn: 0.0830396	total: 8.45s	remaining: 21.6s
281:	learn: 0.0830243	total: 8.48s	remaining: 21.6s
282:	learn: 0.0830016	total: 8.53s	remaining: 21.6s
283:	learn: 0.0829697	total: 8.56s	remaining: 21.6s
284:	learn: 0.0828988	total: 8.59s	remaining: 21.6s
285:	learn: 0.0828478	total: 8.62s	remaining: 21.5s
286:	learn: 0.0828206	total: 8.65s	remaining: 21.5s
287:	learn: 0.0827990	total: 8.68s	remaining: 21.5s
288:	learn: 0.0827638	total: 8.71s	remaining: 21.4s
289:	learn: 0.0826964	total: 8.74s	remaining: 21.4s
290:	learn: 0.0824928	total: 8.77s	remaining: 21.4s
291:	learn: 0.0824773	total: 8.8s	remaining: 21.3s
292:	learn: 0.0823861	total: 8.83s	remaining: 21.3s
293:	learn: 0.0822902	total: 8.86s	remaining: 21.3s
294:	learn: 0.0821485	total: 8.89s	remaining: 21.3s
295:	learn: 0.0819672	total: 8.92s	remaining: 21.2s
296:	learn: 0.0819007	total: 8.96s	remaining: 21.2s
297:	learn: 0.0817780	total: 8.99s	remaining: 21.2s
298:	learn: 0.0816863	total: 9.02s	remaining: 21.1s
299:	learn: 0.0816453	total: 9.04s	remaining: 21.1s
300:	learn: 0.0815336	total: 9.07s	remaining: 21.1s
301:	learn: 0.0815167	total: 9.1s	remaining: 21s
302:	learn: 0.0814517	total: 9.13s	remaining: 21s
303:	learn: 0.0814105	total: 9.16s	remaining: 21s
304:	learn: 0.0813909	total: 9.19s	remaining: 20.9s
305:	learn: 0.0813746	total: 9.22s	remaining: 20.9s
306:	learn: 0.0812596	total: 9.25s	remaining: 20.9s
307:	learn: 0.0811430	total: 9.28s	remaining: 20.8s
308:	learn: 0.0810538	total: 9.31s	remaining: 20.8s
309:	learn: 0.0810348	total: 9.34s	remaining: 20.8s
310:	learn: 0.0809723	total: 9.37s	remaining: 20.8s
311:	learn: 0.0809091	total: 9.39s	remaining: 20.7s
312:	learn: 0.0808887	total: 9.43s	remaining: 20.7s
313:	learn: 0.0808738	total: 9.46s	remaining: 20.7s
314:	learn: 0.0806655	total: 9.48s	remaining: 20.6s
315:	learn: 0.0805956	total: 9.51s	remaining: 20.6s
316:	learn: 0.0805132	total: 9.54s	remaining: 20.6s
317:	learn: 0.0804684	total: 9.59s	remaining: 20.6s
318:	learn: 0.0804091	total: 9.62s	remaining: 20.5s
319:	learn: 0.0802894	total: 9.65s	remaining: 20.5s
320:	learn: 0.0802608	total: 9.68s	remaining: 20.5s
321:	learn: 0.0801653	total: 9.71s	remaining: 20.4s
322:	learn: 0.0800649	total: 9.74s	remaining: 20.4s
323:	learn: 0.0799570	total: 9.79s	remaining: 20.4s
324:	learn: 0.0798687	total: 9.82s	remaining: 20.4s
325:	learn: 0.0798451	total: 9.85s	remaining: 20.4s
326:	learn: 0.0798246	total: 9.88s	remaining: 20.3s
327:	learn: 0.0797649	total: 9.91s	remaining: 20.3s
328:	learn: 0.0796618	total: 9.94s	remaining: 20.3s
329:	learn: 0.0795365	total: 9.97s	remaining: 20.2s
330:	learn: 0.0794062	total: 10s	remaining: 20.2s
331:	learn: 0.0793184	total: 10s	remaining: 20.2s
332:	learn: 0.0793012	total: 10.1s	remaining: 20.1s
333:	learn: 0.0792470	total: 10.1s	remaining: 20.1s
334:	learn: 0.0792047	total: 10.1s	remaining: 20.1s
335:	learn: 0.0791694	total: 10.2s	remaining: 20.1s
336:	learn: 0.0790062	total: 10.2s	remaining: 20s
337:	learn: 0.0789937	total: 10.2s	remaining: 20s
338:	learn: 0.0788481	total: 10.2s	remaining: 20s
339:	learn: 0.0787856	total: 10.3s	remaining: 19.9s
340:	learn: 0.0787488	total: 10.3s	remaining: 19.9s
341:	learn: 0.0786153	total: 10.3s	remaining: 19.9s
342:	learn: 0.0785792	total: 10.4s	remaining: 19.8s
343:	learn: 0.0785319	total: 10.4s	remaining: 19.8s
344:	learn: 0.0784472	total: 10.4s	remaining: 19.8s
345:	learn: 0.0784355	total: 10.4s	remaining: 19.7s
346:	learn: 0.0784105	total: 10.5s	remaining: 19.7s
347:	learn: 0.0782664	total: 10.5s	remaining: 19.7s
348:	learn: 0.0781814	total: 10.5s	remaining: 19.6s
349:	learn: 0.0780579	total: 10.6s	remaining: 19.6s
350:	learn: 0.0779910	total: 10.6s	remaining: 19.6s
351:	learn: 0.0778995	total: 10.6s	remaining: 19.6s
352:	learn: 0.0777900	total: 10.6s	remaining: 19.5s
353:	learn: 0.0777727	total: 10.7s	remaining: 19.5s
354:	learn: 0.0776371	total: 10.7s	remaining: 19.4s
355:	learn: 0.0775197	total: 10.7s	remaining: 19.4s
356:	learn: 0.0775074	total: 10.8s	remaining: 19.4s
357:	learn: 0.0774667	total: 10.8s	remaining: 19.4s
358:	learn: 0.0773210	total: 10.8s	remaining: 19.3s
359:	learn: 0.0771546	total: 10.8s	remaining: 19.3s
360:	learn: 0.0771186	total: 10.9s	remaining: 19.3s
361:	learn: 0.0769758	total: 10.9s	remaining: 19.2s
362:	learn: 0.0768402	total: 10.9s	remaining: 19.2s
363:	learn: 0.0767459	total: 11s	remaining: 19.2s
364:	learn: 0.0766221	total: 11s	remaining: 19.1s
365:	learn: 0.0764456	total: 11s	remaining: 19.1s
366:	learn: 0.0763916	total: 11s	remaining: 19.1s
367:	learn: 0.0763797	total: 11.1s	remaining: 19s
368:	learn: 0.0762711	total: 11.1s	remaining: 19s
369:	learn: 0.0761625	total: 11.1s	remaining: 19s
370:	learn: 0.0760501	total: 11.2s	remaining: 18.9s
371:	learn: 0.0760174	total: 11.2s	remaining: 18.9s
372:	learn: 0.0759660	total: 11.2s	remaining: 18.9s
373:	learn: 0.0759506	total: 11.3s	remaining: 18.9s
374:	learn: 0.0759318	total: 11.3s	remaining: 18.8s
375:	learn: 0.0759040	total: 11.3s	remaining: 18.8s
376:	learn: 0.0757663	total: 11.3s	remaining: 18.8s
377:	learn: 0.0757192	total: 11.4s	remaining: 18.7s
378:	learn: 0.0756688	total: 11.4s	remaining: 18.7s
379:	learn: 0.0755960	total: 11.5s	remaining: 18.7s
380:	learn: 0.0755101	total: 11.5s	remaining: 18.7s
381:	learn: 0.0754797	total: 11.5s	remaining: 18.6s
382:	learn: 0.0754294	total: 11.5s	remaining: 18.6s
383:	learn: 0.0753811	total: 11.6s	remaining: 18.6s
384:	learn: 0.0753059	total: 11.6s	remaining: 18.5s
385:	learn: 0.0751863	total: 11.6s	remaining: 18.5s
386:	learn: 0.0750775	total: 11.7s	remaining: 18.5s
387:	learn: 0.0750342	total: 11.7s	remaining: 18.4s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior1st': 1 unseen categories converted to Unseen on transform.

CV folds:   2%|▏         | 1/50 [00:30<25:01, 30.64s/fold]

Learning rate set to 0.042738
0:	learn: 0.3869299	total: 25.5ms	remaining: 25.4s
1:	learn: 0.3764993	total: 55.2ms	remaining: 27.5s
2:	learn: 0.3658834	total: 84.1ms	remaining: 27.9s
3:	learn: 0.3554544	total: 113ms	remaining: 28.1s
4:	learn: 0.3468280	total: 140ms	remaining: 27.8s
5:	learn: 0.3371119	total: 167ms	remaining: 27.7s
6:	learn: 0.3281173	total: 200ms	remaining: 28.3s
7:	learn: 0.3194937	total: 230ms	remaining: 28.6s
8:	learn: 0.3110526	total: 264ms	remaining: 29s
9:	learn: 0.3030352	total: 295ms	remaining: 29.2s
10:	learn: 0.2960080	total: 324ms	remaining: 29.1s
11:	learn: 0.2889917	total: 354ms	remaining: 29.2s
12:	learn: 0.2825443	total: 384ms	remaining: 29.2s
13:	learn: 0.2756549	total: 412ms	remaining: 29s
14:	learn: 0.2689565	total: 441ms	remaining: 29s
15:	learn: 0.2632580	total: 472ms	remaining: 29s
16:	learn: 0.2572140	total: 503ms	remaining: 29.1s
17:	learn: 0.2517081	total: 532ms	remaining: 29s
18:	learn: 0.2459517	total: 564ms	remaining: 29.1s
19:	learn: 0.2409301	total: 598ms	remaining: 29.3s
20:	learn: 0.2358413	total: 632ms	remaining: 29.5s
21:	learn: 0.2309951	total: 665ms	remaining: 29.6s
22:	learn: 0.2264846	total: 697ms	remaining: 29.6s
23:	learn: 0.2219716	total: 725ms	remaining: 29.5s
24:	learn: 0.2179513	total: 756ms	remaining: 29.5s
25:	learn: 0.2142384	total: 787ms	remaining: 29.5s
26:	learn: 0.2102981	total: 817ms	remaining: 29.4s
27:	learn: 0.2066724	total: 846ms	remaining: 29.4s
28:	learn: 0.2029990	total: 880ms	remaining: 29.5s
29:	learn: 0.1998308	total: 933ms	remaining: 30.2s
30:	learn: 0.1964323	total: 963ms	remaining: 30.1s
31:	learn: 0.1935610	total: 992ms	remaining: 30s
32:	learn: 0.1903817	total: 1.02s	remaining: 30s
33:	learn: 0.1872325	total: 1.05s	remaining: 29.9s
34:	learn: 0.1845171	total: 1.08s	remaining: 29.9s
35:	learn: 0.1815522	total: 1.12s	remaining: 29.9s
36:	learn: 0.1789361	total: 1.15s	remaining: 29.8s
37:	learn: 0.1764280	total: 1.18s	remaining: 29.8s
38:	learn: 0.1739039	total: 1.21s	remaining: 29.7s
39:	learn: 0.1714182	total: 1.24s	remaining: 29.7s
40:	learn: 0.1692554	total: 1.27s	remaining: 29.6s
41:	learn: 0.1670369	total: 1.29s	remaining: 29.6s
42:	learn: 0.1649712	total: 1.33s	remaining: 29.5s
43:	learn: 0.1630162	total: 1.36s	remaining: 29.5s
44:	learn: 0.1611093	total: 1.39s	remaining: 29.4s
45:	learn: 0.1591091	total: 1.42s	remaining: 29.4s
46:	learn: 0.1574029	total: 1.44s	remaining: 29.3s
47:	learn: 0.1556095	total: 1.47s	remaining: 29.2s
48:	learn: 0.1538405	total: 1.5s	remaining: 29.1s
49:	learn: 0.1522763	total: 1.53s	remaining: 29.1s
50:	learn: 0.1508481	total: 1.56s	remaining: 29s
51:	learn: 0.1495969	total: 1.59s	remaining: 29.1s
52:	learn: 0.1481000	total: 1.63s	remaining: 29s
53:	learn: 0.1467708	total: 1.66s	remaining: 29s
54:	learn: 0.1456853	total: 1.68s	remaining: 28.9s
55:	learn: 0.1444085	total: 1.71s	remaining: 28.9s
56:	learn: 0.1432808	total: 1.75s	remaining: 28.9s
57:	learn: 0.1420099	total: 1.77s	remaining: 28.8s
58:	learn: 0.1408255	total: 1.8s	remaining: 28.8s
59:	learn: 0.1396541	total: 1.83s	remaining: 28.7s
60:	learn: 0.1384983	total: 1.86s	remaining: 28.7s
61:	learn: 0.1375233	total: 1.89s	remaining: 28.6s
62:	learn: 0.1362786	total: 1.92s	remaining: 28.5s
63:	learn: 0.1351622	total: 1.95s	remaining: 28.5s
64:	learn: 0.1342227	total: 1.98s	remaining: 28.5s
65:	learn: 0.1334413	total: 2.01s	remaining: 28.4s
66:	learn: 0.1326053	total: 2.04s	remaining: 28.4s
67:	learn: 0.1317721	total: 2.07s	remaining: 28.4s
68:	learn: 0.1309528	total: 2.1s	remaining: 28.3s
69:	learn: 0.1302205	total: 2.13s	remaining: 28.2s
70:	learn: 0.1293709	total: 2.16s	remaining: 28.2s
71:	learn: 0.1286343	total: 2.19s	remaining: 28.2s
72:	learn: 0.1279504	total: 2.22s	remaining: 28.1s
73:	learn: 0.1272654	total: 2.25s	remaining: 28.1s
74:	learn: 0.1261983	total: 2.28s	remaining: 28.1s
75:	learn: 0.1255304	total: 2.33s	remaining: 28.3s
76:	learn: 0.1248513	total: 2.36s	remaining: 28.3s
77:	learn: 0.1242604	total: 2.39s	remaining: 28.2s
78:	learn: 0.1235930	total: 2.42s	remaining: 28.2s
79:	learn: 0.1230353	total: 2.44s	remaining: 28.1s
80:	learn: 0.1223942	total: 2.48s	remaining: 28.1s
81:	learn: 0.1219176	total: 2.5s	remaining: 28s
82:	learn: 0.1213095	total: 2.53s	remaining: 28s
83:	learn: 0.1208474	total: 2.56s	remaining: 28s
84:	learn: 0.1202190	total: 2.59s	remaining: 27.9s
85:	learn: 0.1196833	total: 2.62s	remaining: 27.9s
86:	learn: 0.1191919	total: 2.65s	remaining: 27.8s
87:	learn: 0.1186909	total: 2.69s	remaining: 27.9s
88:	learn: 0.1182256	total: 2.72s	remaining: 27.8s
89:	learn: 0.1177339	total: 2.75s	remaining: 27.8s
90:	learn: 0.1171652	total: 2.78s	remaining: 27.7s
91:	learn: 0.1165373	total: 2.8s	remaining: 27.7s
92:	learn: 0.1160296	total: 2.83s	remaining: 27.6s
93:	learn: 0.1156156	total: 2.86s	remaining: 27.6s
94:	learn: 0.1152009	total: 2.89s	remaining: 27.6s
95:	learn: 0.1147740	total: 2.92s	remaining: 27.5s
96:	learn: 0.1144000	total: 2.95s	remaining: 27.5s
97:	learn: 0.1140018	total: 2.98s	remaining: 27.5s
98:	learn: 0.1135899	total: 3.01s	remaining: 27.4s
99:	learn: 0.1132219	total: 3.04s	remaining: 27.4s
100:	learn: 0.1127744	total: 3.08s	remaining: 27.4s
101:	learn: 0.1123598	total: 3.11s	remaining: 27.4s
102:	learn: 0.1120649	total: 3.14s	remaining: 27.3s
103:	learn: 0.1117236	total: 3.17s	remaining: 27.3s
104:	learn: 0.1111791	total: 3.2s	remaining: 27.3s
105:	learn: 0.1106709	total: 3.23s	remaining: 27.3s
106:	learn: 0.1102020	total: 3.26s	remaining: 27.2s
107:	learn: 0.1099065	total: 3.29s	remaining: 27.2s
108:	learn: 0.1095506	total: 3.32s	remaining: 27.2s
109:	learn: 0.1090996	total: 3.35s	remaining: 27.1s
110:	learn: 0.1088911	total: 3.39s	remaining: 27.1s
111:	learn: 0.1085912	total: 3.41s	remaining: 27.1s
112:	learn: 0.1082200	total: 3.45s	remaining: 27.1s
113:	learn: 0.1078804	total: 3.48s	remaining: 27.1s
114:	learn: 0.1076068	total: 3.51s	remaining: 27s
115:	learn: 0.1073606	total: 3.54s	remaining: 27s
116:	learn: 0.1070894	total: 3.57s	remaining: 27s
117:	learn: 0.1068753	total: 3.6s	remaining: 27s
118:	learn: 0.1066802	total: 3.65s	remaining: 27s
119:	learn: 0.1063912	total: 3.68s	remaining: 27s
120:	learn: 0.1060888	total: 3.71s	remaining: 27s
121:	learn: 0.1058442	total: 3.74s	remaining: 26.9s
122:	learn: 0.1055936	total: 3.77s	remaining: 26.9s
123:	learn: 0.1053118	total: 3.8s	remaining: 26.9s
124:	learn: 0.1049593	total: 3.83s	remaining: 26.8s
125:	learn: 0.1046450	total: 3.86s	remaining: 26.8s
126:	learn: 0.1043929	total: 3.89s	remaining: 26.8s
127:	learn: 0.1041172	total: 3.92s	remaining: 26.7s
128:	learn: 0.1038941	total: 3.96s	remaining: 26.7s
129:	learn: 0.1036916	total: 3.99s	remaining: 26.7s
130:	learn: 0.1035799	total: 4.02s	remaining: 26.7s
131:	learn: 0.1034095	total: 4.05s	remaining: 26.7s
132:	learn: 0.1031947	total: 4.08s	remaining: 26.6s
133:	learn: 0.1030020	total: 4.12s	remaining: 26.6s
134:	learn: 0.1028222	total: 4.15s	remaining: 26.6s
135:	learn: 0.1025546	total: 4.18s	remaining: 26.6s
136:	learn: 0.1023232	total: 4.22s	remaining: 26.6s
137:	learn: 0.1020515	total: 4.25s	remaining: 26.6s
138:	learn: 0.1018711	total: 4.28s	remaining: 26.5s
139:	learn: 0.1016632	total: 4.32s	remaining: 26.5s
140:	learn: 0.1014351	total: 4.35s	remaining: 26.5s
141:	learn: 0.1012207	total: 4.39s	remaining: 26.5s
142:	learn: 0.1009325	total: 4.42s	remaining: 26.5s
143:	learn: 0.1007639	total: 4.45s	remaining: 26.4s
144:	learn: 0.1005767	total: 4.48s	remaining: 26.4s
145:	learn: 0.1003954	total: 4.51s	remaining: 26.4s
146:	learn: 0.1001874	total: 4.54s	remaining: 26.3s
147:	learn: 0.0999323	total: 4.57s	remaining: 26.3s
148:	learn: 0.0996983	total: 4.6s	remaining: 26.3s
149:	learn: 0.0994636	total: 4.63s	remaining: 26.3s
150:	learn: 0.0992821	total: 4.66s	remaining: 26.2s
151:	learn: 0.0991838	total: 4.69s	remaining: 26.2s
152:	learn: 0.0990838	total: 4.72s	remaining: 26.1s
153:	learn: 0.0989268	total: 4.74s	remaining: 26.1s
154:	learn: 0.0987513	total: 4.78s	remaining: 26s
155:	learn: 0.0985221	total: 4.8s	remaining: 26s
156:	learn: 0.0983942	total: 4.83s	remaining: 26s
157:	learn: 0.0982474	total: 4.87s	remaining: 25.9s
158:	learn: 0.0980243	total: 4.89s	remaining: 25.9s
159:	learn: 0.0978516	total: 4.92s	remaining: 25.8s
160:	learn: 0.0977073	total: 4.96s	remaining: 25.8s
161:	learn: 0.0975139	total: 4.99s	remaining: 25.8s
162:	learn: 0.0972429	total: 5.02s	remaining: 25.8s
163:	learn: 0.0970878	total: 5.05s	remaining: 25.8s
164:	learn: 0.0968570	total: 5.08s	remaining: 25.7s
165:	learn: 0.0967463	total: 5.11s	remaining: 25.7s
166:	learn: 0.0965842	total: 5.14s	remaining: 25.7s
167:	learn: 0.0964702	total: 5.18s	remaining: 25.6s
168:	learn: 0.0962808	total: 5.22s	remaining: 25.7s
169:	learn: 0.0961557	total: 5.25s	remaining: 25.7s
170:	learn: 0.0960359	total: 5.28s	remaining: 25.6s
171:	learn: 0.0958797	total: 5.31s	remaining: 25.6s
172:	learn: 0.0955831	total: 5.34s	remaining: 25.5s
173:	learn: 0.0953798	total: 5.37s	remaining: 25.5s
174:	learn: 0.0953223	total: 5.41s	remaining: 25.5s
175:	learn: 0.0951459	total: 5.44s	remaining: 25.5s
176:	learn: 0.0950524	total: 5.47s	remaining: 25.4s
177:	learn: 0.0948737	total: 5.5s	remaining: 25.4s
178:	learn: 0.0946602	total: 5.53s	remaining: 25.4s
179:	learn: 0.0945346	total: 5.56s	remaining: 25.3s
180:	learn: 0.0943745	total: 5.59s	remaining: 25.3s
181:	learn: 0.0942717	total: 5.62s	remaining: 25.3s
182:	learn: 0.0941642	total: 5.65s	remaining: 25.2s
183:	learn: 0.0939195	total: 5.68s	remaining: 25.2s
184:	learn: 0.0937179	total: 5.71s	remaining: 25.2s
185:	learn: 0.0935936	total: 5.74s	remaining: 25.1s
186:	learn: 0.0933525	total: 5.77s	remaining: 25.1s
187:	learn: 0.0931634	total: 5.8s	remaining: 25.1s
188:	learn: 0.0930636	total: 5.84s	remaining: 25.1s
189:	learn: 0.0929362	total: 5.87s	remaining: 25s
190:	learn: 0.0928422	total: 5.9s	remaining: 25s
191:	learn: 0.0927136	total: 5.93s	remaining: 25s
192:	learn: 0.0925681	total: 5.96s	remaining: 24.9s
193:	learn: 0.0923178	total: 5.99s	remaining: 24.9s
194:	learn: 0.0921481	total: 6.02s	remaining: 24.9s
195:	learn: 0.0920277	total: 6.05s	remaining: 24.8s
196:	learn: 0.0918693	total: 6.09s	remaining: 24.8s
197:	learn: 0.0916451	total: 6.12s	remaining: 24.8s
198:	learn: 0.0915299	total: 6.15s	remaining: 24.7s
199:	learn: 0.0913969	total: 6.17s	remaining: 24.7s
200:	learn: 0.0912524	total: 6.21s	remaining: 24.7s
201:	learn: 0.0911907	total: 6.23s	remaining: 24.6s
202:	learn: 0.0909956	total: 6.26s	remaining: 24.6s
203:	learn: 0.0909118	total: 6.29s	remaining: 24.5s
204:	learn: 0.0907130	total: 6.32s	remaining: 24.5s
205:	learn: 0.0906559	total: 6.35s	remaining: 24.5s
206:	learn: 0.0905255	total: 6.38s	remaining: 24.4s
207:	learn: 0.0904389	total: 6.41s	remaining: 24.4s
208:	learn: 0.0903529	total: 6.44s	remaining: 24.4s
209:	learn: 0.0902314	total: 6.47s	remaining: 24.3s
210:	learn: 0.0901439	total: 6.5s	remaining: 24.3s
211:	learn: 0.0899655	total: 6.53s	remaining: 24.3s
212:	learn: 0.0897983	total: 6.56s	remaining: 24.2s
213:	learn: 0.0897342	total: 6.59s	remaining: 24.2s
214:	learn: 0.0896298	total: 6.62s	remaining: 24.2s
215:	learn: 0.0895541	total: 6.65s	remaining: 24.1s
216:	learn: 0.0894927	total: 6.68s	remaining: 24.1s
217:	learn: 0.0893636	total: 6.73s	remaining: 24.1s
218:	learn: 0.0892161	total: 6.76s	remaining: 24.1s
219:	learn: 0.0890321	total: 6.79s	remaining: 24.1s
220:	learn: 0.0889637	total: 6.82s	remaining: 24s
221:	learn: 0.0888651	total: 6.85s	remaining: 24s
222:	learn: 0.0887407	total: 6.88s	remaining: 24s
223:	learn: 0.0886370	total: 6.91s	remaining: 23.9s
224:	learn: 0.0885606	total: 6.94s	remaining: 23.9s
225:	learn: 0.0884228	total: 6.97s	remaining: 23.9s
226:	learn: 0.0883414	total: 7s	remaining: 23.8s
227:	learn: 0.0882622	total: 7.03s	remaining: 23.8s
228:	learn: 0.0882109	total: 7.06s	remaining: 23.8s
229:	learn: 0.0881404	total: 7.09s	remaining: 23.7s
230:	learn: 0.0881139	total: 7.12s	remaining: 23.7s
231:	learn: 0.0879821	total: 7.15s	remaining: 23.7s
232:	learn: 0.0878284	total: 7.18s	remaining: 23.6s
233:	learn: 0.0876458	total: 7.21s	remaining: 23.6s
234:	learn: 0.0874236	total: 7.24s	remaining: 23.6s
235:	learn: 0.0872783	total: 7.27s	remaining: 23.5s
236:	learn: 0.0871951	total: 7.3s	remaining: 23.5s
237:	learn: 0.0870795	total: 7.33s	remaining: 23.5s
238:	learn: 0.0869800	total: 7.38s	remaining: 23.5s
239:	learn: 0.0869183	total: 7.41s	remaining: 23.5s
240:	learn: 0.0868796	total: 7.44s	remaining: 23.4s
241:	learn: 0.0868332	total: 7.47s	remaining: 23.4s
242:	learn: 0.0867933	total: 7.5s	remaining: 23.4s
243:	learn: 0.0866294	total: 7.53s	remaining: 23.3s
244:	learn: 0.0865966	total: 7.56s	remaining: 23.3s
245:	learn: 0.0865261	total: 7.59s	remaining: 23.3s
246:	learn: 0.0864202	total: 7.62s	remaining: 23.2s
247:	learn: 0.0863552	total: 7.65s	remaining: 23.2s
248:	learn: 0.0862238	total: 7.68s	remaining: 23.2s
249:	learn: 0.0861323	total: 7.71s	remaining: 23.1s
250:	learn: 0.0860077	total: 7.75s	remaining: 23.1s
251:	learn: 0.0859567	total: 7.78s	remaining: 23.1s
252:	learn: 0.0859474	total: 7.81s	remaining: 23.1s
253:	learn: 0.0857937	total: 7.83s	remaining: 23s
254:	learn: 0.0856908	total: 7.87s	remaining: 23s
255:	learn: 0.0856786	total: 7.9s	remaining: 22.9s
256:	learn: 0.0856365	total: 7.92s	remaining: 22.9s
257:	learn: 0.0855589	total: 7.96s	remaining: 22.9s
258:	learn: 0.0853236	total: 7.99s	remaining: 22.9s
259:	learn: 0.0852257	total: 8.02s	remaining: 22.8s
260:	learn: 0.0851657	total: 8.05s	remaining: 22.8s
261:	learn: 0.0850489	total: 8.08s	remaining: 22.8s
262:	learn: 0.0849315	total: 8.11s	remaining: 22.7s
263:	learn: 0.0847722	total: 8.13s	remaining: 22.7s
264:	learn: 0.0845903	total: 8.16s	remaining: 22.6s
265:	learn: 0.0844922	total: 8.2s	remaining: 22.6s
266:	learn: 0.0844583	total: 8.23s	remaining: 22.6s
267:	learn: 0.0843309	total: 8.28s	remaining: 22.6s
268:	learn: 0.0842253	total: 8.31s	remaining: 22.6s
269:	learn: 0.0841272	total: 8.34s	remaining: 22.6s
270:	learn: 0.0840141	total: 8.38s	remaining: 22.5s
271:	learn: 0.0839465	total: 8.4s	remaining: 22.5s
272:	learn: 0.0838066	total: 8.44s	remaining: 22.5s
273:	learn: 0.0837181	total: 8.47s	remaining: 22.4s
274:	learn: 0.0836924	total: 8.5s	remaining: 22.4s
275:	learn: 0.0835892	total: 8.53s	remaining: 22.4s
276:	learn: 0.0834143	total: 8.56s	remaining: 22.4s
277:	learn: 0.0833738	total: 8.6s	remaining: 22.3s
278:	learn: 0.0832646	total: 8.63s	remaining: 22.3s
279:	learn: 0.0831437	total: 8.67s	remaining: 22.3s
280:	learn: 0.0830903	total: 8.7s	remaining: 22.3s
281:	learn: 0.0830671	total: 8.73s	remaining: 22.2s
282:	learn: 0.0830537	total: 8.76s	remaining: 22.2s
283:	learn: 0.0828954	total: 8.79s	remaining: 22.2s
284:	learn: 0.0828651	total: 8.82s	remaining: 22.1s
285:	learn: 0.0828004	total: 8.85s	remaining: 22.1s
286:	learn: 0.0826804	total: 8.88s	remaining: 22.1s
287:	learn: 0.0826637	total: 8.92s	remaining: 22s
288:	learn: 0.0825953	total: 8.95s	remaining: 22s
289:	learn: 0.0825115	total: 8.98s	remaining: 22s
290:	learn: 0.0824591	total: 9.01s	remaining: 22s
291:	learn: 0.0824127	total: 9.04s	remaining: 21.9s
292:	learn: 0.0823899	total: 9.07s	remaining: 21.9s
293:	learn: 0.0822433	total: 9.1s	remaining: 21.9s
294:	learn: 0.0822214	total: 9.14s	remaining: 21.8s
295:	learn: 0.0820932	total: 9.17s	remaining: 21.8s
296:	learn: 0.0819664	total: 9.2s	remaining: 21.8s
297:	learn: 0.0818870	total: 9.23s	remaining: 21.7s
298:	learn: 0.0818644	total: 9.26s	remaining: 21.7s
299:	learn: 0.0817467	total: 9.29s	remaining: 21.7s
300:	learn: 0.0816875	total: 9.32s	remaining: 21.6s
301:	learn: 0.0816696	total: 9.35s	remaining: 21.6s
302:	learn: 0.0816068	total: 9.38s	remaining: 21.6s
303:	learn: 0.0814771	total: 9.41s	remaining: 21.6s
304:	learn: 0.0814588	total: 9.44s	remaining: 21.5s
305:	learn: 0.0814310	total: 9.47s	remaining: 21.5s
306:	learn: 0.0814234	total: 9.51s	remaining: 21.5s
307:	learn: 0.0812280	total: 9.56s	remaining: 21.5s
308:	learn: 0.0810508	total: 9.59s	remaining: 21.4s
309:	learn: 0.0810221	total: 9.62s	remaining: 21.4s
310:	learn: 0.0809081	total: 9.65s	remaining: 21.4s
311:	learn: 0.0807651	total: 9.68s	remaining: 21.3s
312:	learn: 0.0807039	total: 9.71s	remaining: 21.3s
313:	learn: 0.0805729	total: 9.74s	remaining: 21.3s
314:	learn: 0.0805178	total: 9.77s	remaining: 21.2s
315:	learn: 0.0804743	total: 9.8s	remaining: 21.2s
316:	learn: 0.0804448	total: 9.84s	remaining: 21.2s
317:	learn: 0.0803206	total: 9.86s	remaining: 21.2s
318:	learn: 0.0802927	total: 9.89s	remaining: 21.1s
319:	learn: 0.0802518	total: 9.93s	remaining: 21.1s
320:	learn: 0.0800946	total: 9.96s	remaining: 21.1s
321:	learn: 0.0800882	total: 9.99s	remaining: 21s
322:	learn: 0.0800615	total: 10s	remaining: 21s
323:	learn: 0.0800014	total: 10.1s	remaining: 21s
324:	learn: 0.0798853	total: 10.1s	remaining: 20.9s
325:	learn: 0.0798299	total: 10.1s	remaining: 20.9s
326:	learn: 0.0798154	total: 10.1s	remaining: 20.9s
327:	learn: 0.0797220	total: 10.2s	remaining: 20.9s
328:	learn: 0.0796068	total: 10.2s	remaining: 20.8s
329:	learn: 0.0795457	total: 10.2s	remaining: 20.8s
330:	learn: 0.0794950	total: 10.3s	remaining: 20.8s
331:	learn: 0.0793776	total: 10.3s	remaining: 20.7s
332:	learn: 0.0792995	total: 10.3s	remaining: 20.7s
333:	learn: 0.0792409	total: 10.4s	remaining: 20.7s
334:	learn: 0.0792327	total: 10.4s	remaining: 20.6s
335:	learn: 0.0791658	total: 10.4s	remaining: 20.6s
336:	learn: 0.0791079	total: 10.5s	remaining: 20.6s
337:	learn: 0.0790839	total: 10.5s	remaining: 20.5s
338:	learn: 0.0790008	total: 10.5s	remaining: 20.5s
339:	learn: 0.0789143	total: 10.5s	remaining: 20.5s
340:	learn: 0.0788620	total: 10.6s	remaining: 20.4s
341:	learn: 0.0788219	total: 10.6s	remaining: 20.4s
342:	learn: 0.0787451	total: 10.6s	remaining: 20.4s
343:	learn: 0.0786507	total: 10.7s	remaining: 20.4s
344:	learn: 0.0785388	total: 10.7s	remaining: 20.3s
345:	learn: 0.0784757	total: 10.7s	remaining: 20.3s
346:	learn: 0.0783730	total: 10.8s	remaining: 20.3s
347:	learn: 0.0783653	total: 10.8s	remaining: 20.3s
348:	learn: 0.0781565	total: 10.8s	remaining: 20.2s
349:	learn: 0.0781069	total: 10.9s	remaining: 20.2s
350:	learn: 0.0781009	total: 10.9s	remaining: 20.2s
351:	learn: 0.0779358	total: 10.9s	remaining: 20.1s
352:	learn: 0.0779224	total: 11s	remaining: 20.1s
353:	learn: 0.0779143	total: 11s	remaining: 20.1s
354:	learn: 0.0777543	total: 11s	remaining: 20s
355:	learn: 0.0777100	total: 11.1s	remaining: 20s
356:	learn: 0.0776923	total: 11.1s	remaining: 20s
357:	learn: 0.0776818	total: 11.1s	remaining: 20s
358:	learn: 0.0776739	total: 11.2s	remaining: 19.9s
359:	learn: 0.0776456	total: 11.2s	remaining: 19.9s
360:	learn: 0.0774771	total: 11.2s	remaining: 19.9s
361:	learn: 0.0773228	total: 11.3s	remaining: 19.8s
362:	learn: 0.0772084	total: 11.3s	remaining: 19.8s
363:	learn: 0.0771115	total: 11.3s	remaining: 19.8s
364:	learn: 0.0770720	total: 11.3s	remaining: 19.7s
365:	learn: 0.0770164	total: 11.4s	remaining: 19.7s
366:	learn: 0.0769721	total: 11.4s	remaining: 19.7s
367:	learn: 0.0768582	total: 11.4s	remaining: 19.7s
368:	learn: 0.0767716	total: 11.5s	remaining: 19.6s
369:	learn: 0.0767655	total: 11.5s	remaining: 19.6s
370:	learn: 0.0767601	total: 11.5s	remaining: 19.6s
371:	learn: 0.0767237	total: 11.6s	remaining: 19.5s
372:	learn: 0.0767080	total: 11.6s	remaining: 19.5s
373:	learn: 0.0766194	total: 11.6s	remaining: 19.5s
374:	learn: 0.0766028	total: 11.7s	remaining: 19.4s
375:	learn: 0.0765275	total: 11.7s	remaining: 19.4s
376:	learn: 0.0764625	total: 11.7s	remaining: 19.4s
377:	learn: 0.0764258	total: 11.8s	remaining: 19.4s
378:	learn: 0.0764200	total: 11.8s	remaining: 19.3s
379:	learn: 0.0763620	total: 11.8s	remaining: 19.3s
380:	learn: 0.0761694	total: 11.9s	remaining: 19.3s
381:	learn: 0.0760679	total: 11.9s	remaining: 19.2s
382:	learn: 0.0760570	total: 11.9s	remaining: 19.2s
383:	learn: 0.0760399	total: 11.9s	remaining: 19.2s
384:	learn: 0.0759322	total: 12s	remaining: 19.1s
385:	learn: 0.0758444	total: 12s	remaining: 19.1s
386:	learn: 0.0758341	total: 12s	remaining: 19.1s
387:	learn: 0.0757924	total: 12.1s	remaining: 19s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Neighborhood': 2 unseen categories converted to Unseen on transform.

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior1st': 1 unseen categories converted to Unseen on transform.

CV folds:   4%|▍         | 2/50 [01:02<25:00, 31.26s/fold]

999:	learn: 0.0448766	total: 31.2s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3878376	total: 14.6ms	remaining: 14.6s
1:	learn: 0.3768563	total: 38ms	remaining: 19s
2:	learn: 0.3665984	total: 64.1ms	remaining: 21.3s
3:	learn: 0.3568898	total: 95.3ms	remaining: 23.7s
4:	learn: 0.3475270	total: 122ms	remaining: 24.3s
5:	learn: 0.3386006	total: 150ms	remaining: 24.9s
6:	learn: 0.3300248	total: 177ms	remaining: 25.1s
7:	learn: 0.3214474	total: 204ms	remaining: 25.3s
8:	learn: 0.3134061	total: 234ms	remaining: 25.7s
9:	learn: 0.3062131	total: 265ms	remaining: 26.2s
10:	learn: 0.2988467	total: 294ms	remaining: 26.5s
11:	learn: 0.2914752	total: 323ms	remaining: 26.6s
12:	learn: 0.2841940	total: 350ms	remaining: 26.6s
13:	learn: 0.2771196	total: 382ms	remaining: 26.9s
14:	learn: 0.2709161	total: 410ms	remaining: 26.9s
15:	learn: 0.2652778	total: 441ms	remaining: 27.1s
16:	learn: 0.2594450	total: 468ms	remaining: 27.1s
17:	learn: 0.2541299	total: 499ms	remaining: 27.2s
18:	learn: 0.2487227	total: 529ms	remaining: 27.3s
19:	learn: 0.2433479	total: 559ms	remaining: 27.4s
20:	learn: 0.2377803	total: 589ms	remaining: 27.4s
21:	learn: 0.2329603	total: 617ms	remaining: 27.4s
22:	learn: 0.2283124	total: 646ms	remaining: 27.4s
23:	learn: 0.2239534	total: 677ms	remaining: 27.5s
24:	learn: 0.2201565	total: 709ms	remaining: 27.6s
25:	learn: 0.2162744	total: 742ms	remaining: 27.8s
26:	learn: 0.2119909	total: 770ms	remaining: 27.8s
27:	learn: 0.2083164	total: 800ms	remaining: 27.8s
28:	learn: 0.2044762	total: 831ms	remaining: 27.8s
29:	learn: 0.2011035	total: 861ms	remaining: 27.8s
30:	learn: 0.1973023	total: 891ms	remaining: 27.8s
31:	learn: 0.1941243	total: 923ms	remaining: 27.9s
32:	learn: 0.1909946	total: 957ms	remaining: 28s
33:	learn: 0.1878877	total: 985ms	remaining: 28s
34:	learn: 0.1853019	total: 1.01s	remaining: 27.8s
35:	learn: 0.1823041	total: 1.04s	remaining: 27.9s
36:	learn: 0.1795889	total: 1.07s	remaining: 27.9s
37:	learn: 0.1770685	total: 1.1s	remaining: 28s
38:	learn: 0.1746398	total: 1.13s	remaining: 28s
39:	learn: 0.1722048	total: 1.16s	remaining: 27.9s
40:	learn: 0.1697499	total: 1.19s	remaining: 27.8s
41:	learn: 0.1676326	total: 1.22s	remaining: 27.8s
42:	learn: 0.1652782	total: 1.25s	remaining: 27.8s
43:	learn: 0.1633000	total: 1.28s	remaining: 27.8s
44:	learn: 0.1613529	total: 1.31s	remaining: 27.8s
45:	learn: 0.1595045	total: 1.34s	remaining: 27.8s
46:	learn: 0.1576920	total: 1.37s	remaining: 27.7s
47:	learn: 0.1561345	total: 1.4s	remaining: 27.7s
48:	learn: 0.1545460	total: 1.43s	remaining: 27.7s
49:	learn: 0.1529418	total: 1.46s	remaining: 27.7s
50:	learn: 0.1515788	total: 1.49s	remaining: 27.7s
51:	learn: 0.1501577	total: 1.52s	remaining: 27.7s
52:	learn: 0.1485970	total: 1.55s	remaining: 27.7s
53:	learn: 0.1470191	total: 1.58s	remaining: 27.7s
54:	learn: 0.1456102	total: 1.61s	remaining: 27.7s
55:	learn: 0.1443618	total: 1.65s	remaining: 27.7s
56:	learn: 0.1431453	total: 1.68s	remaining: 27.7s
57:	learn: 0.1421410	total: 1.71s	remaining: 27.7s
58:	learn: 0.1410988	total: 1.75s	remaining: 27.9s
59:	learn: 0.1398387	total: 1.78s	remaining: 27.9s
60:	learn: 0.1386900	total: 1.81s	remaining: 27.9s
61:	learn: 0.1375894	total: 1.84s	remaining: 27.8s
62:	learn: 0.1366964	total: 1.87s	remaining: 27.8s
63:	learn: 0.1357605	total: 1.9s	remaining: 27.8s
64:	learn: 0.1347042	total: 1.93s	remaining: 27.8s
65:	learn: 0.1339435	total: 1.96s	remaining: 27.7s
66:	learn: 0.1331992	total: 1.99s	remaining: 27.7s
67:	learn: 0.1323508	total: 2.02s	remaining: 27.7s
68:	learn: 0.1315051	total: 2.05s	remaining: 27.6s
69:	learn: 0.1307440	total: 2.08s	remaining: 27.6s
70:	learn: 0.1299056	total: 2.11s	remaining: 27.6s
71:	learn: 0.1292405	total: 2.14s	remaining: 27.6s
72:	learn: 0.1284079	total: 2.17s	remaining: 27.6s
73:	learn: 0.1276406	total: 2.2s	remaining: 27.5s
74:	learn: 0.1270068	total: 2.22s	remaining: 27.4s
75:	learn: 0.1260352	total: 2.25s	remaining: 27.4s
76:	learn: 0.1253442	total: 2.28s	remaining: 27.3s
77:	learn: 0.1246484	total: 2.31s	remaining: 27.3s
78:	learn: 0.1240475	total: 2.34s	remaining: 27.3s
79:	learn: 0.1233625	total: 2.37s	remaining: 27.3s
80:	learn: 0.1226710	total: 2.4s	remaining: 27.2s
81:	learn: 0.1221778	total: 2.43s	remaining: 27.2s
82:	learn: 0.1216894	total: 2.46s	remaining: 27.2s
83:	learn: 0.1211086	total: 2.49s	remaining: 27.2s
84:	learn: 0.1207159	total: 2.52s	remaining: 27.1s
85:	learn: 0.1202101	total: 2.55s	remaining: 27.1s
86:	learn: 0.1195787	total: 2.58s	remaining: 27s
87:	learn: 0.1191502	total: 2.6s	remaining: 27s
88:	learn: 0.1185884	total: 2.64s	remaining: 27s
89:	learn: 0.1178925	total: 2.67s	remaining: 27s
90:	learn: 0.1174957	total: 2.7s	remaining: 27s
91:	learn: 0.1170281	total: 2.73s	remaining: 27s
92:	learn: 0.1165893	total: 2.76s	remaining: 26.9s
93:	learn: 0.1161988	total: 2.79s	remaining: 26.9s
94:	learn: 0.1156667	total: 2.82s	remaining: 26.9s
95:	learn: 0.1151558	total: 2.85s	remaining: 26.8s
96:	learn: 0.1147483	total: 2.88s	remaining: 26.8s
97:	learn: 0.1142822	total: 2.91s	remaining: 26.8s
98:	learn: 0.1138634	total: 2.95s	remaining: 26.9s
99:	learn: 0.1134743	total: 2.98s	remaining: 26.9s
100:	learn: 0.1130362	total: 3.02s	remaining: 26.8s
101:	learn: 0.1127035	total: 3.05s	remaining: 26.8s
102:	learn: 0.1123327	total: 3.08s	remaining: 26.8s
103:	learn: 0.1119966	total: 3.11s	remaining: 26.8s
104:	learn: 0.1114992	total: 3.14s	remaining: 26.8s
105:	learn: 0.1112079	total: 3.17s	remaining: 26.7s
106:	learn: 0.1106973	total: 3.2s	remaining: 26.7s
107:	learn: 0.1103992	total: 3.23s	remaining: 26.7s
108:	learn: 0.1100835	total: 3.26s	remaining: 26.6s
109:	learn: 0.1098129	total: 3.29s	remaining: 26.6s
110:	learn: 0.1093763	total: 3.32s	remaining: 26.6s
111:	learn: 0.1090119	total: 3.35s	remaining: 26.5s
112:	learn: 0.1087768	total: 3.38s	remaining: 26.5s
113:	learn: 0.1084307	total: 3.41s	remaining: 26.5s
114:	learn: 0.1081517	total: 3.44s	remaining: 26.5s
115:	learn: 0.1079018	total: 3.47s	remaining: 26.4s
116:	learn: 0.1076030	total: 3.5s	remaining: 26.4s
117:	learn: 0.1073080	total: 3.53s	remaining: 26.4s
118:	learn: 0.1070681	total: 3.56s	remaining: 26.4s
119:	learn: 0.1067412	total: 3.59s	remaining: 26.3s
120:	learn: 0.1064952	total: 3.62s	remaining: 26.3s
121:	learn: 0.1063134	total: 3.65s	remaining: 26.3s
122:	learn: 0.1060392	total: 3.68s	remaining: 26.2s
123:	learn: 0.1056942	total: 3.71s	remaining: 26.2s
124:	learn: 0.1054860	total: 3.74s	remaining: 26.2s
125:	learn: 0.1052938	total: 3.78s	remaining: 26.2s
126:	learn: 0.1049705	total: 3.81s	remaining: 26.2s
127:	learn: 0.1047488	total: 3.84s	remaining: 26.2s
128:	learn: 0.1045116	total: 3.88s	remaining: 26.2s
129:	learn: 0.1043649	total: 3.91s	remaining: 26.2s
130:	learn: 0.1040511	total: 3.94s	remaining: 26.2s
131:	learn: 0.1039099	total: 3.97s	remaining: 26.1s
132:	learn: 0.1036514	total: 4s	remaining: 26.1s
133:	learn: 0.1034311	total: 4.04s	remaining: 26.1s
134:	learn: 0.1032326	total: 4.07s	remaining: 26.1s
135:	learn: 0.1030309	total: 4.1s	remaining: 26s
136:	learn: 0.1027462	total: 4.13s	remaining: 26s
137:	learn: 0.1025872	total: 4.16s	remaining: 26s
138:	learn: 0.1023939	total: 4.19s	remaining: 25.9s
139:	learn: 0.1021659	total: 4.23s	remaining: 26s
140:	learn: 0.1019415	total: 4.26s	remaining: 26s
141:	learn: 0.1018040	total: 4.29s	remaining: 25.9s
142:	learn: 0.1016411	total: 4.32s	remaining: 25.9s
143:	learn: 0.1014919	total: 4.35s	remaining: 25.8s
144:	learn: 0.1012218	total: 4.37s	remaining: 25.8s
145:	learn: 0.1010690	total: 4.43s	remaining: 25.9s
146:	learn: 0.1009076	total: 4.46s	remaining: 25.9s
147:	learn: 0.1007843	total: 4.49s	remaining: 25.8s
148:	learn: 0.1006447	total: 4.52s	remaining: 25.8s
149:	learn: 0.1003573	total: 4.55s	remaining: 25.8s
150:	learn: 0.1000323	total: 4.58s	remaining: 25.8s
151:	learn: 0.0997930	total: 4.61s	remaining: 25.7s
152:	learn: 0.0995125	total: 4.64s	remaining: 25.7s
153:	learn: 0.0992442	total: 4.67s	remaining: 25.7s
154:	learn: 0.0990918	total: 4.71s	remaining: 25.7s
155:	learn: 0.0988219	total: 4.75s	remaining: 25.7s
156:	learn: 0.0986730	total: 4.77s	remaining: 25.6s
157:	learn: 0.0984012	total: 4.8s	remaining: 25.6s
158:	learn: 0.0982977	total: 4.83s	remaining: 25.6s
159:	learn: 0.0980778	total: 4.86s	remaining: 25.5s
160:	learn: 0.0979061	total: 4.9s	remaining: 25.5s
161:	learn: 0.0976951	total: 4.93s	remaining: 25.5s
162:	learn: 0.0975519	total: 4.96s	remaining: 25.5s
163:	learn: 0.0972980	total: 4.99s	remaining: 25.4s
164:	learn: 0.0971305	total: 5.02s	remaining: 25.4s
165:	learn: 0.0969035	total: 5.05s	remaining: 25.4s
166:	learn: 0.0966559	total: 5.08s	remaining: 25.3s
167:	learn: 0.0965135	total: 5.11s	remaining: 25.3s
168:	learn: 0.0963285	total: 5.14s	remaining: 25.3s
169:	learn: 0.0960422	total: 5.17s	remaining: 25.3s
170:	learn: 0.0959450	total: 5.2s	remaining: 25.2s
171:	learn: 0.0957682	total: 5.23s	remaining: 25.2s
172:	learn: 0.0956429	total: 5.26s	remaining: 25.1s
173:	learn: 0.0955276	total: 5.29s	remaining: 25.1s
174:	learn: 0.0953938	total: 5.32s	remaining: 25.1s
175:	learn: 0.0953123	total: 5.35s	remaining: 25s
176:	learn: 0.0950734	total: 5.38s	remaining: 25s
177:	learn: 0.0948521	total: 5.41s	remaining: 25s
178:	learn: 0.0946321	total: 5.44s	remaining: 25s
179:	learn: 0.0943776	total: 5.47s	remaining: 24.9s
180:	learn: 0.0941362	total: 5.5s	remaining: 24.9s
181:	learn: 0.0940292	total: 5.53s	remaining: 24.9s
182:	learn: 0.0938864	total: 5.56s	remaining: 24.8s
183:	learn: 0.0936086	total: 5.59s	remaining: 24.8s
184:	learn: 0.0935455	total: 5.62s	remaining: 24.8s
185:	learn: 0.0934376	total: 5.66s	remaining: 24.7s
186:	learn: 0.0932628	total: 5.69s	remaining: 24.7s
187:	learn: 0.0931617	total: 5.72s	remaining: 24.7s
188:	learn: 0.0930203	total: 5.75s	remaining: 24.7s
189:	learn: 0.0929792	total: 5.78s	remaining: 24.6s
190:	learn: 0.0929213	total: 5.81s	remaining: 24.6s
191:	learn: 0.0927005	total: 5.84s	remaining: 24.6s
192:	learn: 0.0926756	total: 5.87s	remaining: 24.5s
193:	learn: 0.0925443	total: 5.9s	remaining: 24.5s
194:	learn: 0.0924319	total: 5.93s	remaining: 24.5s
195:	learn: 0.0924103	total: 5.96s	remaining: 24.5s
196:	learn: 0.0923879	total: 5.99s	remaining: 24.4s
197:	learn: 0.0922655	total: 6.04s	remaining: 24.5s
198:	learn: 0.0922159	total: 6.08s	remaining: 24.5s
199:	learn: 0.0921806	total: 6.11s	remaining: 24.4s
200:	learn: 0.0920606	total: 6.14s	remaining: 24.4s
201:	learn: 0.0918228	total: 6.17s	remaining: 24.4s
202:	learn: 0.0916964	total: 6.21s	remaining: 24.4s
203:	learn: 0.0916213	total: 6.23s	remaining: 24.3s
204:	learn: 0.0915086	total: 6.27s	remaining: 24.3s
205:	learn: 0.0914734	total: 6.3s	remaining: 24.3s
206:	learn: 0.0913509	total: 6.33s	remaining: 24.2s
207:	learn: 0.0912906	total: 6.36s	remaining: 24.2s
208:	learn: 0.0912638	total: 6.39s	remaining: 24.2s
209:	learn: 0.0911959	total: 6.42s	remaining: 24.1s
210:	learn: 0.0909998	total: 6.45s	remaining: 24.1s
211:	learn: 0.0908510	total: 6.47s	remaining: 24.1s
212:	learn: 0.0906472	total: 6.5s	remaining: 24s
213:	learn: 0.0905532	total: 6.54s	remaining: 24s
214:	learn: 0.0903826	total: 6.57s	remaining: 24s
215:	learn: 0.0903488	total: 6.6s	remaining: 24s
216:	learn: 0.0903299	total: 6.63s	remaining: 23.9s
217:	learn: 0.0902173	total: 6.66s	remaining: 23.9s
218:	learn: 0.0901386	total: 6.69s	remaining: 23.9s
219:	learn: 0.0900323	total: 6.72s	remaining: 23.8s
220:	learn: 0.0898338	total: 6.75s	remaining: 23.8s
221:	learn: 0.0898099	total: 6.78s	remaining: 23.8s
222:	learn: 0.0897312	total: 6.81s	remaining: 23.7s
223:	learn: 0.0894520	total: 6.84s	remaining: 23.7s
224:	learn: 0.0892281	total: 6.87s	remaining: 23.7s
225:	learn: 0.0891010	total: 6.9s	remaining: 23.6s
226:	learn: 0.0890265	total: 6.93s	remaining: 23.6s
227:	learn: 0.0888282	total: 6.96s	remaining: 23.6s
228:	learn: 0.0886486	total: 7s	remaining: 23.6s
229:	learn: 0.0884863	total: 7.03s	remaining: 23.5s
230:	learn: 0.0884269	total: 7.07s	remaining: 23.5s
231:	learn: 0.0884064	total: 7.1s	remaining: 23.5s
232:	learn: 0.0883575	total: 7.13s	remaining: 23.5s
233:	learn: 0.0881448	total: 7.16s	remaining: 23.4s
234:	learn: 0.0879617	total: 7.19s	remaining: 23.4s
235:	learn: 0.0878531	total: 7.22s	remaining: 23.4s
236:	learn: 0.0876689	total: 7.25s	remaining: 23.4s
237:	learn: 0.0874698	total: 7.29s	remaining: 23.3s
238:	learn: 0.0874276	total: 7.32s	remaining: 23.3s
239:	learn: 0.0873966	total: 7.35s	remaining: 23.3s
240:	learn: 0.0872431	total: 7.38s	remaining: 23.2s
241:	learn: 0.0872051	total: 7.4s	remaining: 23.2s
242:	learn: 0.0869915	total: 7.44s	remaining: 23.2s
243:	learn: 0.0869057	total: 7.47s	remaining: 23.1s
244:	learn: 0.0868108	total: 7.5s	remaining: 23.1s
245:	learn: 0.0867347	total: 7.53s	remaining: 23.1s
246:	learn: 0.0866841	total: 7.56s	remaining: 23s
247:	learn: 0.0865838	total: 7.59s	remaining: 23s
248:	learn: 0.0865292	total: 7.62s	remaining: 23s
249:	learn: 0.0865120	total: 7.65s	remaining: 23s
250:	learn: 0.0863346	total: 7.68s	remaining: 22.9s
251:	learn: 0.0862369	total: 7.71s	remaining: 22.9s
252:	learn: 0.0860826	total: 7.74s	remaining: 22.8s
253:	learn: 0.0860297	total: 7.77s	remaining: 22.8s
254:	learn: 0.0859046	total: 7.8s	remaining: 22.8s
255:	learn: 0.0858106	total: 7.83s	remaining: 22.8s
256:	learn: 0.0856962	total: 7.86s	remaining: 22.7s
257:	learn: 0.0856608	total: 7.89s	remaining: 22.7s
258:	learn: 0.0855721	total: 7.92s	remaining: 22.7s
259:	learn: 0.0854474	total: 7.95s	remaining: 22.6s
260:	learn: 0.0853603	total: 7.98s	remaining: 22.6s
261:	learn: 0.0853381	total: 8.01s	remaining: 22.6s
262:	learn: 0.0853179	total: 8.04s	remaining: 22.5s
263:	learn: 0.0850187	total: 8.07s	remaining: 22.5s
264:	learn: 0.0848229	total: 8.1s	remaining: 22.5s
265:	learn: 0.0846578	total: 8.13s	remaining: 22.4s
266:	learn: 0.0846286	total: 8.16s	remaining: 22.4s
267:	learn: 0.0844284	total: 8.21s	remaining: 22.4s
268:	learn: 0.0842748	total: 8.24s	remaining: 22.4s
269:	learn: 0.0841788	total: 8.27s	remaining: 22.4s
270:	learn: 0.0841195	total: 8.29s	remaining: 22.3s
271:	learn: 0.0840115	total: 8.32s	remaining: 22.3s
272:	learn: 0.0838766	total: 8.36s	remaining: 22.3s
273:	learn: 0.0838566	total: 8.38s	remaining: 22.2s
274:	learn: 0.0838363	total: 8.42s	remaining: 22.2s
275:	learn: 0.0838122	total: 8.45s	remaining: 22.2s
276:	learn: 0.0836988	total: 8.48s	remaining: 22.1s
277:	learn: 0.0836405	total: 8.51s	remaining: 22.1s
278:	learn: 0.0834831	total: 8.54s	remaining: 22.1s
279:	learn: 0.0833605	total: 8.57s	remaining: 22s
280:	learn: 0.0833303	total: 8.6s	remaining: 22s
281:	learn: 0.0831902	total: 8.63s	remaining: 22s
282:	learn: 0.0829827	total: 8.66s	remaining: 21.9s
283:	learn: 0.0828779	total: 8.69s	remaining: 21.9s
284:	learn: 0.0828656	total: 8.72s	remaining: 21.9s
285:	learn: 0.0825794	total: 8.76s	remaining: 21.9s
286:	learn: 0.0825620	total: 8.79s	remaining: 21.8s
287:	learn: 0.0823967	total: 8.82s	remaining: 21.8s
288:	learn: 0.0823664	total: 8.85s	remaining: 21.8s
289:	learn: 0.0823499	total: 8.88s	remaining: 21.7s
290:	learn: 0.0823132	total: 8.91s	remaining: 21.7s
291:	learn: 0.0822663	total: 8.94s	remaining: 21.7s
292:	learn: 0.0820987	total: 8.99s	remaining: 21.7s
293:	learn: 0.0819407	total: 9.02s	remaining: 21.7s
294:	learn: 0.0818544	total: 9.05s	remaining: 21.6s
295:	learn: 0.0818475	total: 9.08s	remaining: 21.6s
296:	learn: 0.0817482	total: 9.11s	remaining: 21.6s
297:	learn: 0.0817367	total: 9.14s	remaining: 21.5s
298:	learn: 0.0816259	total: 9.17s	remaining: 21.5s
299:	learn: 0.0814883	total: 9.2s	remaining: 21.5s
300:	learn: 0.0813758	total: 9.23s	remaining: 21.4s
301:	learn: 0.0811955	total: 9.26s	remaining: 21.4s
302:	learn: 0.0810327	total: 9.29s	remaining: 21.4s
303:	learn: 0.0809275	total: 9.32s	remaining: 21.3s
304:	learn: 0.0808412	total: 9.36s	remaining: 21.3s
305:	learn: 0.0807509	total: 9.39s	remaining: 21.3s
306:	learn: 0.0806312	total: 9.42s	remaining: 21.3s
307:	learn: 0.0805767	total: 9.45s	remaining: 21.2s
308:	learn: 0.0804830	total: 9.48s	remaining: 21.2s
309:	learn: 0.0804739	total: 9.51s	remaining: 21.2s
310:	learn: 0.0803299	total: 9.54s	remaining: 21.1s
311:	learn: 0.0802960	total: 9.57s	remaining: 21.1s
312:	learn: 0.0802481	total: 9.6s	remaining: 21.1s
313:	learn: 0.0802333	total: 9.63s	remaining: 21s
314:	learn: 0.0800949	total: 9.67s	remaining: 21s
315:	learn: 0.0799709	total: 9.7s	remaining: 21s
316:	learn: 0.0799184	total: 9.73s	remaining: 21s
317:	learn: 0.0799011	total: 9.76s	remaining: 20.9s
318:	learn: 0.0798798	total: 9.79s	remaining: 20.9s
319:	learn: 0.0798414	total: 9.82s	remaining: 20.9s
320:	learn: 0.0798215	total: 9.85s	remaining: 20.8s
321:	learn: 0.0797800	total: 9.88s	remaining: 20.8s
322:	learn: 0.0797622	total: 9.95s	remaining: 20.9s
323:	learn: 0.0797538	total: 9.98s	remaining: 20.8s
324:	learn: 0.0796723	total: 10s	remaining: 20.8s
325:	learn: 0.0794664	total: 10s	remaining: 20.8s
326:	learn: 0.0792573	total: 10.1s	remaining: 20.7s
327:	learn: 0.0791869	total: 10.1s	remaining: 20.7s
328:	learn: 0.0790826	total: 10.1s	remaining: 20.7s
329:	learn: 0.0790252	total: 10.2s	remaining: 20.6s
330:	learn: 0.0789379	total: 10.2s	remaining: 20.6s
331:	learn: 0.0788747	total: 10.2s	remaining: 20.6s
332:	learn: 0.0786865	total: 10.3s	remaining: 20.5s
333:	learn: 0.0785852	total: 10.3s	remaining: 20.5s
334:	learn: 0.0784980	total: 10.3s	remaining: 20.5s
335:	learn: 0.0783896	total: 10.4s	remaining: 20.5s
336:	learn: 0.0782568	total: 10.4s	remaining: 20.5s
337:	learn: 0.0782170	total: 10.4s	remaining: 20.4s
338:	learn: 0.0782057	total: 10.5s	remaining: 20.4s
339:	learn: 0.0781454	total: 10.5s	remaining: 20.4s
340:	learn: 0.0780320	total: 10.5s	remaining: 20.3s
341:	learn: 0.0779540	total: 10.6s	remaining: 20.3s
342:	learn: 0.0779271	total: 10.6s	remaining: 20.3s
343:	learn: 0.0778022	total: 10.6s	remaining: 20.2s
344:	learn: 0.0777362	total: 10.6s	remaining: 20.2s
345:	learn: 0.0776317	total: 10.7s	remaining: 20.2s
346:	learn: 0.0775467	total: 10.7s	remaining: 20.1s
347:	learn: 0.0774626	total: 10.7s	remaining: 20.1s
348:	learn: 0.0774361	total: 10.8s	remaining: 20.1s
349:	learn: 0.0773313	total: 10.8s	remaining: 20.1s
350:	learn: 0.0772267	total: 10.8s	remaining: 20s
351:	learn: 0.0771123	total: 10.9s	remaining: 20s
352:	learn: 0.0770302	total: 10.9s	remaining: 20s
353:	learn: 0.0769883	total: 10.9s	remaining: 19.9s
354:	learn: 0.0767926	total: 11s	remaining: 19.9s
355:	learn: 0.0767202	total: 11s	remaining: 19.9s
356:	learn: 0.0765880	total: 11s	remaining: 19.8s
357:	learn: 0.0764700	total: 11s	remaining: 19.8s
358:	learn: 0.0763662	total: 11.1s	remaining: 19.8s
359:	learn: 0.0762961	total: 11.1s	remaining: 19.7s
360:	learn: 0.0762735	total: 11.1s	remaining: 19.7s
361:	learn: 0.0761051	total: 11.2s	remaining: 19.7s
362:	learn: 0.0759768	total: 11.2s	remaining: 19.7s
363:	learn: 0.0759688	total: 11.2s	remaining: 19.6s
364:	learn: 0.0759538	total: 11.3s	remaining: 19.6s
365:	learn: 0.0758243	total: 11.3s	remaining: 19.6s
366:	learn: 0.0757354	total: 11.3s	remaining: 19.5s
367:	learn: 0.0757231	total: 11.4s	remaining: 19.5s
368:	learn: 0.0756622	total: 11.4s	remaining: 19.5s
369:	learn: 0.0756504	total: 11.4s	remaining: 19.4s
370:	learn: 0.0755506	total: 11.5s	remaining: 19.4s
371:	learn: 0.0754809	total: 11.5s	remaining: 19.4s
372:	learn: 0.0754374	total: 11.5s	remaining: 19.4s
373:	learn: 0.0753296	total: 11.5s	remaining: 19.3s
374:	learn: 0.0752147	total: 11.6s	remaining: 19.3s
375:	learn: 0.0751272	total: 11.6s	remaining: 19.3s
376:	learn: 0.0749847	total: 11.6s	remaining: 19.2s
377:	learn: 0.0749537	total: 11.7s	remaining: 19.2s
378:	learn: 0.0747885	total: 11.7s	remaining: 19.2s
379:	learn: 0.0746898	total: 11.7s	remaining: 19.1s
380:	learn: 0.0746530	total: 11.8s	remaining: 19.1s
381:	learn: 0.0746341	total: 11.8s	remaining: 19.1s
382:	learn: 0.0745201	total: 11.8s	remaining: 19s
383:	learn: 0.0744584	total: 11.8s	remaining: 19s
384:	learn: 0.0744271	total: 11.9s	remaining: 19s
385:	learn: 0.0743028	total: 11.9s	remaining: 18.9s
386:	learn: 0.0741758	total: 11.9s	remaining: 18.9s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'ExterCond': 1 unseen categories converted to Unseen on transform.

CV folds:   6%|▌         | 3/50 [01:33<24:33, 31.34s/fold]

998:	learn: 0.0434005	total: 30.9s	remaining: 30.9ms
999:	learn: 0.0433505	total: 30.9s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3864961	total: 24ms	remaining: 23.9s
1:	learn: 0.3760828	total: 56.5ms	remaining: 28.2s
2:	learn: 0.3655773	total: 86.4ms	remaining: 28.7s
3:	learn: 0.3563677	total: 130ms	remaining: 32.5s
4:	learn: 0.3465996	total: 162ms	remaining: 32.2s
5:	learn: 0.3375009	total: 192ms	remaining: 31.9s
6:	learn: 0.3291555	total: 219ms	remaining: 31.1s
7:	learn: 0.3207580	total: 251ms	remaining: 31.1s
8:	learn: 0.3129233	total: 284ms	remaining: 31.3s
9:	learn: 0.3056494	total: 314ms	remaining: 31.1s
10:	learn: 0.2976771	total: 351ms	remaining: 31.6s
11:	learn: 0.2906192	total: 382ms	remaining: 31.5s
12:	learn: 0.2831717	total: 409ms	remaining: 31.1s
13:	learn: 0.2756628	total: 438ms	remaining: 30.9s
14:	learn: 0.2690726	total: 472ms	remaining: 31s
15:	learn: 0.2634729	total: 503ms	remaining: 30.9s
16:	learn: 0.2574669	total: 535ms	remaining: 30.9s
17:	learn: 0.2516224	total: 582ms	remaining: 31.7s
18:	learn: 0.2460411	total: 612ms	remaining: 31.6s
19:	learn: 0.2409841	total: 658ms	remaining: 32.2s
20:	learn: 0.2360940	total: 686ms	remaining: 32s
21:	learn: 0.2311639	total: 718ms	remaining: 31.9s
22:	learn: 0.2267420	total: 749ms	remaining: 31.8s
23:	learn: 0.2225861	total: 780ms	remaining: 31.7s
24:	learn: 0.2187090	total: 812ms	remaining: 31.7s
25:	learn: 0.2145067	total: 839ms	remaining: 31.4s
26:	learn: 0.2107622	total: 867ms	remaining: 31.2s
27:	learn: 0.2067144	total: 900ms	remaining: 31.2s
28:	learn: 0.2029746	total: 933ms	remaining: 31.2s
29:	learn: 0.1998151	total: 963ms	remaining: 31.1s
30:	learn: 0.1964430	total: 998ms	remaining: 31.2s
31:	learn: 0.1931788	total: 1.03s	remaining: 31.2s
32:	learn: 0.1898224	total: 1.06s	remaining: 31s
33:	learn: 0.1872363	total: 1.09s	remaining: 31s
34:	learn: 0.1846781	total: 1.12s	remaining: 31s
35:	learn: 0.1820265	total: 1.15s	remaining: 30.8s
36:	learn: 0.1793184	total: 1.18s	remaining: 30.7s
37:	learn: 0.1765211	total: 1.21s	remaining: 30.7s
38:	learn: 0.1738808	total: 1.24s	remaining: 30.7s
39:	learn: 0.1716353	total: 1.28s	remaining: 30.7s
40:	learn: 0.1694221	total: 1.31s	remaining: 30.6s
41:	learn: 0.1671697	total: 1.34s	remaining: 30.6s
42:	learn: 0.1650514	total: 1.37s	remaining: 30.4s
43:	learn: 0.1631159	total: 1.4s	remaining: 30.3s
44:	learn: 0.1611727	total: 1.43s	remaining: 30.3s
45:	learn: 0.1591461	total: 1.46s	remaining: 30.2s
46:	learn: 0.1573486	total: 1.49s	remaining: 30.1s
47:	learn: 0.1555623	total: 1.52s	remaining: 30.1s
48:	learn: 0.1540216	total: 1.55s	remaining: 30.1s
49:	learn: 0.1525934	total: 1.58s	remaining: 30s
50:	learn: 0.1509977	total: 1.61s	remaining: 30s
51:	learn: 0.1494009	total: 1.64s	remaining: 30s
52:	learn: 0.1478421	total: 1.67s	remaining: 29.9s
53:	learn: 0.1464807	total: 1.7s	remaining: 29.8s
54:	learn: 0.1451565	total: 1.73s	remaining: 29.7s
55:	learn: 0.1439467	total: 1.76s	remaining: 29.6s
56:	learn: 0.1426095	total: 1.79s	remaining: 29.6s
57:	learn: 0.1413581	total: 1.82s	remaining: 29.5s
58:	learn: 0.1401884	total: 1.85s	remaining: 29.5s
59:	learn: 0.1390738	total: 1.88s	remaining: 29.4s
60:	learn: 0.1380694	total: 1.91s	remaining: 29.3s
61:	learn: 0.1371050	total: 1.94s	remaining: 29.3s
62:	learn: 0.1362604	total: 1.97s	remaining: 29.2s
63:	learn: 0.1351994	total: 1.99s	remaining: 29.2s
64:	learn: 0.1342609	total: 2.02s	remaining: 29.1s
65:	learn: 0.1333158	total: 2.05s	remaining: 29.1s
66:	learn: 0.1325448	total: 2.08s	remaining: 29s
67:	learn: 0.1316310	total: 2.11s	remaining: 28.9s
68:	learn: 0.1305961	total: 2.14s	remaining: 28.9s
69:	learn: 0.1298343	total: 2.18s	remaining: 28.9s
70:	learn: 0.1290143	total: 2.21s	remaining: 28.9s
71:	learn: 0.1280938	total: 2.24s	remaining: 28.9s
72:	learn: 0.1273539	total: 2.27s	remaining: 28.8s
73:	learn: 0.1265642	total: 2.3s	remaining: 28.8s
74:	learn: 0.1257786	total: 2.33s	remaining: 28.7s
75:	learn: 0.1252281	total: 2.36s	remaining: 28.7s
76:	learn: 0.1246590	total: 2.39s	remaining: 28.6s
77:	learn: 0.1239703	total: 2.42s	remaining: 28.6s
78:	learn: 0.1231692	total: 2.45s	remaining: 28.6s
79:	learn: 0.1225792	total: 2.48s	remaining: 28.6s
80:	learn: 0.1221255	total: 2.52s	remaining: 28.5s
81:	learn: 0.1215537	total: 2.54s	remaining: 28.5s
82:	learn: 0.1208508	total: 2.57s	remaining: 28.4s
83:	learn: 0.1203449	total: 2.6s	remaining: 28.4s
84:	learn: 0.1198426	total: 2.63s	remaining: 28.3s
85:	learn: 0.1193888	total: 2.66s	remaining: 28.3s
86:	learn: 0.1189507	total: 2.69s	remaining: 28.2s
87:	learn: 0.1184932	total: 2.72s	remaining: 28.2s
88:	learn: 0.1178983	total: 2.75s	remaining: 28.1s
89:	learn: 0.1173406	total: 2.79s	remaining: 28.2s
90:	learn: 0.1169082	total: 2.82s	remaining: 28.2s
91:	learn: 0.1163990	total: 2.85s	remaining: 28.1s
92:	learn: 0.1160535	total: 2.88s	remaining: 28.1s
93:	learn: 0.1156357	total: 2.91s	remaining: 28s
94:	learn: 0.1151376	total: 2.93s	remaining: 28s
95:	learn: 0.1148641	total: 2.95s	remaining: 27.8s
96:	learn: 0.1144100	total: 2.97s	remaining: 27.7s
97:	learn: 0.1140678	total: 3s	remaining: 27.6s
98:	learn: 0.1137271	total: 3.03s	remaining: 27.6s
99:	learn: 0.1133244	total: 3.06s	remaining: 27.6s
100:	learn: 0.1130771	total: 3.09s	remaining: 27.5s
101:	learn: 0.1128242	total: 3.12s	remaining: 27.4s
102:	learn: 0.1124301	total: 3.15s	remaining: 27.4s
103:	learn: 0.1120648	total: 3.18s	remaining: 27.4s
104:	learn: 0.1116889	total: 3.21s	remaining: 27.3s
105:	learn: 0.1113923	total: 3.23s	remaining: 27.3s
106:	learn: 0.1108641	total: 3.27s	remaining: 27.3s
107:	learn: 0.1106053	total: 3.31s	remaining: 27.3s
108:	learn: 0.1102180	total: 3.34s	remaining: 27.3s
109:	learn: 0.1097824	total: 3.37s	remaining: 27.3s
110:	learn: 0.1092569	total: 3.41s	remaining: 27.3s
111:	learn: 0.1089944	total: 3.44s	remaining: 27.3s
112:	learn: 0.1086759	total: 3.47s	remaining: 27.3s
113:	learn: 0.1083526	total: 3.5s	remaining: 27.2s
114:	learn: 0.1081304	total: 3.53s	remaining: 27.2s
115:	learn: 0.1077640	total: 3.56s	remaining: 27.1s
116:	learn: 0.1072913	total: 3.59s	remaining: 27.1s
117:	learn: 0.1069441	total: 3.62s	remaining: 27.1s
118:	learn: 0.1065359	total: 3.65s	remaining: 27s
119:	learn: 0.1061874	total: 3.68s	remaining: 27s
120:	learn: 0.1059421	total: 3.71s	remaining: 27s
121:	learn: 0.1058392	total: 3.74s	remaining: 26.9s
122:	learn: 0.1055051	total: 3.77s	remaining: 26.9s
123:	learn: 0.1051529	total: 3.8s	remaining: 26.8s
124:	learn: 0.1049481	total: 3.83s	remaining: 26.8s
125:	learn: 0.1047664	total: 3.86s	remaining: 26.8s
126:	learn: 0.1045434	total: 3.89s	remaining: 26.7s
127:	learn: 0.1043014	total: 3.92s	remaining: 26.7s
128:	learn: 0.1041555	total: 3.94s	remaining: 26.6s
129:	learn: 0.1039831	total: 3.98s	remaining: 26.6s
130:	learn: 0.1038269	total: 4.01s	remaining: 26.6s
131:	learn: 0.1035735	total: 4.04s	remaining: 26.5s
132:	learn: 0.1033927	total: 4.07s	remaining: 26.5s
133:	learn: 0.1031709	total: 4.09s	remaining: 26.5s
134:	learn: 0.1029419	total: 4.12s	remaining: 26.4s
135:	learn: 0.1027600	total: 4.16s	remaining: 26.4s
136:	learn: 0.1026108	total: 4.19s	remaining: 26.4s
137:	learn: 0.1024080	total: 4.22s	remaining: 26.4s
138:	learn: 0.1020602	total: 4.25s	remaining: 26.3s
139:	learn: 0.1018404	total: 4.28s	remaining: 26.3s
140:	learn: 0.1016624	total: 4.31s	remaining: 26.3s
141:	learn: 0.1015180	total: 4.34s	remaining: 26.2s
142:	learn: 0.1014280	total: 4.37s	remaining: 26.2s
143:	learn: 0.1011937	total: 4.41s	remaining: 26.2s
144:	learn: 0.1008462	total: 4.43s	remaining: 26.2s
145:	learn: 0.1006679	total: 4.46s	remaining: 26.1s
146:	learn: 0.1004277	total: 4.49s	remaining: 26.1s
147:	learn: 0.1002552	total: 4.53s	remaining: 26.1s
148:	learn: 0.1000324	total: 4.56s	remaining: 26s
149:	learn: 0.0997878	total: 4.59s	remaining: 26s
150:	learn: 0.0995154	total: 4.62s	remaining: 26s
151:	learn: 0.0992781	total: 4.65s	remaining: 25.9s
152:	learn: 0.0989571	total: 4.68s	remaining: 25.9s
153:	learn: 0.0987954	total: 4.71s	remaining: 25.9s
154:	learn: 0.0987150	total: 4.74s	remaining: 25.8s
155:	learn: 0.0985255	total: 4.77s	remaining: 25.8s
156:	learn: 0.0983883	total: 4.8s	remaining: 25.8s
157:	learn: 0.0981810	total: 4.85s	remaining: 25.9s
158:	learn: 0.0980121	total: 4.88s	remaining: 25.8s
159:	learn: 0.0979125	total: 4.91s	remaining: 25.8s
160:	learn: 0.0977617	total: 4.96s	remaining: 25.8s
161:	learn: 0.0975885	total: 5s	remaining: 25.9s
162:	learn: 0.0974690	total: 5.03s	remaining: 25.8s
163:	learn: 0.0972704	total: 5.06s	remaining: 25.8s
164:	learn: 0.0969925	total: 5.1s	remaining: 25.8s
165:	learn: 0.0967763	total: 5.13s	remaining: 25.8s
166:	learn: 0.0966415	total: 5.17s	remaining: 25.8s
167:	learn: 0.0963843	total: 5.2s	remaining: 25.8s
168:	learn: 0.0962671	total: 5.24s	remaining: 25.8s
169:	learn: 0.0960635	total: 5.28s	remaining: 25.8s
170:	learn: 0.0958573	total: 5.32s	remaining: 25.8s
171:	learn: 0.0957531	total: 5.35s	remaining: 25.7s
172:	learn: 0.0955643	total: 5.38s	remaining: 25.7s
173:	learn: 0.0953167	total: 5.41s	remaining: 25.7s
174:	learn: 0.0951316	total: 5.45s	remaining: 25.7s
175:	learn: 0.0949908	total: 5.48s	remaining: 25.7s
176:	learn: 0.0947763	total: 5.52s	remaining: 25.7s
177:	learn: 0.0946399	total: 5.55s	remaining: 25.6s
178:	learn: 0.0945505	total: 5.59s	remaining: 25.7s
179:	learn: 0.0943693	total: 5.63s	remaining: 25.7s
180:	learn: 0.0941777	total: 5.66s	remaining: 25.6s
181:	learn: 0.0940814	total: 5.7s	remaining: 25.6s
182:	learn: 0.0939333	total: 5.73s	remaining: 25.6s
183:	learn: 0.0938046	total: 5.76s	remaining: 25.6s
184:	learn: 0.0935357	total: 5.8s	remaining: 25.6s
185:	learn: 0.0933809	total: 5.83s	remaining: 25.5s
186:	learn: 0.0932666	total: 5.86s	remaining: 25.5s
187:	learn: 0.0930108	total: 5.89s	remaining: 25.5s
188:	learn: 0.0928441	total: 5.93s	remaining: 25.4s
189:	learn: 0.0927340	total: 5.96s	remaining: 25.4s
190:	learn: 0.0925703	total: 5.99s	remaining: 25.4s
191:	learn: 0.0923760	total: 6.02s	remaining: 25.3s
192:	learn: 0.0922350	total: 6.05s	remaining: 25.3s
193:	learn: 0.0921211	total: 6.08s	remaining: 25.2s
194:	learn: 0.0919259	total: 6.11s	remaining: 25.2s
195:	learn: 0.0917703	total: 6.13s	remaining: 25.2s
196:	learn: 0.0916156	total: 6.16s	remaining: 25.1s
197:	learn: 0.0915337	total: 6.19s	remaining: 25.1s
198:	learn: 0.0914164	total: 6.23s	remaining: 25.1s
199:	learn: 0.0913584	total: 6.26s	remaining: 25.1s
200:	learn: 0.0911781	total: 6.29s	remaining: 25s
201:	learn: 0.0909571	total: 6.34s	remaining: 25.1s
202:	learn: 0.0908854	total: 6.37s	remaining: 25s
203:	learn: 0.0907573	total: 6.4s	remaining: 25s
204:	learn: 0.0905890	total: 6.44s	remaining: 25s
205:	learn: 0.0905166	total: 6.47s	remaining: 24.9s
206:	learn: 0.0903534	total: 6.5s	remaining: 24.9s
207:	learn: 0.0902107	total: 6.54s	remaining: 24.9s
208:	learn: 0.0900931	total: 6.56s	remaining: 24.8s
209:	learn: 0.0899799	total: 6.59s	remaining: 24.8s
210:	learn: 0.0898094	total: 6.62s	remaining: 24.8s
211:	learn: 0.0897073	total: 6.66s	remaining: 24.7s
212:	learn: 0.0895338	total: 6.69s	remaining: 24.7s
213:	learn: 0.0893069	total: 6.71s	remaining: 24.7s
214:	learn: 0.0892637	total: 6.74s	remaining: 24.6s
215:	learn: 0.0892114	total: 6.77s	remaining: 24.6s
216:	learn: 0.0890351	total: 6.81s	remaining: 24.6s
217:	learn: 0.0888717	total: 6.84s	remaining: 24.5s
218:	learn: 0.0886347	total: 6.87s	remaining: 24.5s
219:	learn: 0.0884507	total: 6.9s	remaining: 24.5s
220:	learn: 0.0883671	total: 6.94s	remaining: 24.5s
221:	learn: 0.0882401	total: 6.97s	remaining: 24.4s
222:	learn: 0.0880946	total: 7s	remaining: 24.4s
223:	learn: 0.0879926	total: 7.03s	remaining: 24.4s
224:	learn: 0.0877934	total: 7.06s	remaining: 24.3s
225:	learn: 0.0876657	total: 7.11s	remaining: 24.3s
226:	learn: 0.0875874	total: 7.14s	remaining: 24.3s
227:	learn: 0.0875324	total: 7.17s	remaining: 24.3s
228:	learn: 0.0873980	total: 7.2s	remaining: 24.2s
229:	learn: 0.0872522	total: 7.23s	remaining: 24.2s
230:	learn: 0.0871977	total: 7.26s	remaining: 24.2s
231:	learn: 0.0870917	total: 7.29s	remaining: 24.1s
232:	learn: 0.0870317	total: 7.32s	remaining: 24.1s
233:	learn: 0.0868507	total: 7.36s	remaining: 24.1s
234:	learn: 0.0867486	total: 7.39s	remaining: 24.1s
235:	learn: 0.0866305	total: 7.42s	remaining: 24s
236:	learn: 0.0865149	total: 7.46s	remaining: 24s
237:	learn: 0.0863919	total: 7.49s	remaining: 24s
238:	learn: 0.0863405	total: 7.52s	remaining: 24s
239:	learn: 0.0863175	total: 7.55s	remaining: 23.9s
240:	learn: 0.0862901	total: 7.58s	remaining: 23.9s
241:	learn: 0.0862643	total: 7.61s	remaining: 23.8s
242:	learn: 0.0861574	total: 7.64s	remaining: 23.8s
243:	learn: 0.0861223	total: 7.67s	remaining: 23.8s
244:	learn: 0.0860143	total: 7.7s	remaining: 23.7s
245:	learn: 0.0859893	total: 7.72s	remaining: 23.7s
246:	learn: 0.0858995	total: 7.75s	remaining: 23.6s
247:	learn: 0.0856836	total: 7.78s	remaining: 23.6s
248:	learn: 0.0855174	total: 7.81s	remaining: 23.5s
249:	learn: 0.0854875	total: 7.83s	remaining: 23.5s
250:	learn: 0.0853807	total: 7.86s	remaining: 23.5s
251:	learn: 0.0852108	total: 7.89s	remaining: 23.4s
252:	learn: 0.0850180	total: 7.92s	remaining: 23.4s
253:	learn: 0.0849978	total: 7.96s	remaining: 23.4s
254:	learn: 0.0848375	total: 8s	remaining: 23.4s
255:	learn: 0.0847427	total: 8.03s	remaining: 23.3s
256:	learn: 0.0846462	total: 8.06s	remaining: 23.3s
257:	learn: 0.0846367	total: 8.1s	remaining: 23.3s
258:	learn: 0.0846245	total: 8.14s	remaining: 23.3s
259:	learn: 0.0844908	total: 8.17s	remaining: 23.3s
260:	learn: 0.0843590	total: 8.23s	remaining: 23.3s
261:	learn: 0.0843457	total: 8.27s	remaining: 23.3s
262:	learn: 0.0842065	total: 8.29s	remaining: 23.2s
263:	learn: 0.0841784	total: 8.32s	remaining: 23.2s
264:	learn: 0.0840903	total: 8.35s	remaining: 23.2s
265:	learn: 0.0839216	total: 8.38s	remaining: 23.1s
266:	learn: 0.0836563	total: 8.41s	remaining: 23.1s
267:	learn: 0.0835388	total: 8.44s	remaining: 23.1s
268:	learn: 0.0835178	total: 8.47s	remaining: 23s
269:	learn: 0.0834922	total: 8.51s	remaining: 23s
270:	learn: 0.0833622	total: 8.54s	remaining: 23s
271:	learn: 0.0832036	total: 8.58s	remaining: 23s
272:	learn: 0.0830623	total: 8.61s	remaining: 22.9s
273:	learn: 0.0829014	total: 8.65s	remaining: 22.9s
274:	learn: 0.0827900	total: 8.68s	remaining: 22.9s
275:	learn: 0.0827758	total: 8.71s	remaining: 22.8s
276:	learn: 0.0826310	total: 8.74s	remaining: 22.8s
277:	learn: 0.0823992	total: 8.77s	remaining: 22.8s
278:	learn: 0.0823025	total: 8.81s	remaining: 22.8s
279:	learn: 0.0822126	total: 8.84s	remaining: 22.7s
280:	learn: 0.0821419	total: 8.87s	remaining: 22.7s
281:	learn: 0.0819849	total: 8.92s	remaining: 22.7s
282:	learn: 0.0819674	total: 8.96s	remaining: 22.7s
283:	learn: 0.0818319	total: 8.99s	remaining: 22.7s
284:	learn: 0.0817107	total: 9.02s	remaining: 22.6s
285:	learn: 0.0815335	total: 9.05s	remaining: 22.6s
286:	learn: 0.0813407	total: 9.08s	remaining: 22.6s
287:	learn: 0.0813240	total: 9.12s	remaining: 22.5s
288:	learn: 0.0811886	total: 9.14s	remaining: 22.5s
289:	learn: 0.0811788	total: 9.18s	remaining: 22.5s
290:	learn: 0.0811649	total: 9.2s	remaining: 22.4s
291:	learn: 0.0811307	total: 9.24s	remaining: 22.4s
292:	learn: 0.0809700	total: 9.28s	remaining: 22.4s
293:	learn: 0.0807893	total: 9.31s	remaining: 22.4s
294:	learn: 0.0806679	total: 9.34s	remaining: 22.3s
295:	learn: 0.0806135	total: 9.37s	remaining: 22.3s
296:	learn: 0.0805255	total: 9.4s	remaining: 22.2s
297:	learn: 0.0804073	total: 9.43s	remaining: 22.2s
298:	learn: 0.0803882	total: 9.45s	remaining: 22.2s
299:	learn: 0.0803703	total: 9.48s	remaining: 22.1s
300:	learn: 0.0802669	total: 9.51s	remaining: 22.1s
301:	learn: 0.0802585	total: 9.54s	remaining: 22.1s
302:	learn: 0.0801176	total: 9.57s	remaining: 22s
303:	learn: 0.0799894	total: 9.61s	remaining: 22s
304:	learn: 0.0798981	total: 9.65s	remaining: 22s
305:	learn: 0.0797613	total: 9.68s	remaining: 21.9s
306:	learn: 0.0796856	total: 9.71s	remaining: 21.9s
307:	learn: 0.0796771	total: 9.74s	remaining: 21.9s
308:	learn: 0.0795847	total: 9.78s	remaining: 21.9s
309:	learn: 0.0795563	total: 9.81s	remaining: 21.8s
310:	learn: 0.0793661	total: 9.84s	remaining: 21.8s
311:	learn: 0.0793319	total: 9.87s	remaining: 21.8s
312:	learn: 0.0792487	total: 9.9s	remaining: 21.7s
313:	learn: 0.0791214	total: 9.94s	remaining: 21.7s
314:	learn: 0.0791068	total: 9.97s	remaining: 21.7s
315:	learn: 0.0790111	total: 10s	remaining: 21.6s
316:	learn: 0.0788387	total: 10s	remaining: 21.6s
317:	learn: 0.0787459	total: 10.1s	remaining: 21.6s
318:	learn: 0.0786384	total: 10.1s	remaining: 21.5s
319:	learn: 0.0785316	total: 10.1s	remaining: 21.5s
320:	learn: 0.0785209	total: 10.2s	remaining: 21.5s
321:	learn: 0.0784126	total: 10.2s	remaining: 21.5s
322:	learn: 0.0783388	total: 10.2s	remaining: 21.4s
323:	learn: 0.0782833	total: 10.3s	remaining: 21.4s
324:	learn: 0.0782080	total: 10.3s	remaining: 21.4s
325:	learn: 0.0780916	total: 10.3s	remaining: 21.3s
326:	learn: 0.0780076	total: 10.3s	remaining: 21.3s
327:	learn: 0.0779667	total: 10.4s	remaining: 21.3s
328:	learn: 0.0779152	total: 10.4s	remaining: 21.2s
329:	learn: 0.0778786	total: 10.4s	remaining: 21.2s
330:	learn: 0.0777461	total: 10.5s	remaining: 21.2s
331:	learn: 0.0776389	total: 10.5s	remaining: 21.2s
332:	learn: 0.0774527	total: 10.5s	remaining: 21.1s
333:	learn: 0.0772842	total: 10.6s	remaining: 21.1s
334:	learn: 0.0772239	total: 10.6s	remaining: 21.1s
335:	learn: 0.0771606	total: 10.6s	remaining: 21s
336:	learn: 0.0770466	total: 10.7s	remaining: 21s
337:	learn: 0.0769246	total: 10.8s	remaining: 21.1s
338:	learn: 0.0768375	total: 10.8s	remaining: 21s
339:	learn: 0.0768045	total: 10.8s	remaining: 21s
340:	learn: 0.0767168	total: 10.8s	remaining: 21s
341:	learn: 0.0766093	total: 10.9s	remaining: 20.9s
342:	learn: 0.0765298	total: 10.9s	remaining: 20.9s
343:	learn: 0.0764928	total: 10.9s	remaining: 20.9s
344:	learn: 0.0764132	total: 11s	remaining: 20.8s
345:	learn: 0.0763297	total: 11s	remaining: 20.8s
346:	learn: 0.0762375	total: 11s	remaining: 20.8s
347:	learn: 0.0761025	total: 11.1s	remaining: 20.7s
348:	learn: 0.0760154	total: 11.1s	remaining: 20.7s
349:	learn: 0.0758811	total: 11.1s	remaining: 20.6s
350:	learn: 0.0757367	total: 11.1s	remaining: 20.6s
351:	learn: 0.0756262	total: 11.2s	remaining: 20.6s
352:	learn: 0.0755467	total: 11.2s	remaining: 20.5s
353:	learn: 0.0754866	total: 11.2s	remaining: 20.5s
354:	learn: 0.0754534	total: 11.3s	remaining: 20.5s
355:	learn: 0.0753040	total: 11.3s	remaining: 20.4s
356:	learn: 0.0752625	total: 11.3s	remaining: 20.4s
357:	learn: 0.0751913	total: 11.4s	remaining: 20.4s
358:	learn: 0.0751372	total: 11.4s	remaining: 20.4s
359:	learn: 0.0750209	total: 11.5s	remaining: 20.4s
360:	learn: 0.0748857	total: 11.5s	remaining: 20.3s
361:	learn: 0.0748725	total: 11.5s	remaining: 20.3s
362:	learn: 0.0748525	total: 11.6s	remaining: 20.3s
363:	learn: 0.0748235	total: 11.6s	remaining: 20.3s
364:	learn: 0.0747642	total: 11.6s	remaining: 20.2s
365:	learn: 0.0746147	total: 11.7s	remaining: 20.2s
366:	learn: 0.0745007	total: 11.7s	remaining: 20.2s
367:	learn: 0.0743766	total: 11.7s	remaining: 20.1s
368:	learn: 0.0742730	total: 11.8s	remaining: 20.1s
369:	learn: 0.0741621	total: 11.8s	remaining: 20.1s
370:	learn: 0.0740882	total: 11.8s	remaining: 20s
371:	learn: 0.0739673	total: 11.9s	remaining: 20s
372:	learn: 0.0738398	total: 11.9s	remaining: 20s
373:	learn: 0.0737819	total: 11.9s	remaining: 20s
374:	learn: 0.0736950	total: 12s	remaining: 20s
375:	learn: 0.0736203	total: 12s	remaining: 19.9s
376:	learn: 0.0734211	total: 12s	remaining: 19.9s
377:	learn: 0.0733833	total: 12.1s	remaining: 19.9s
378:	learn: 0.0732504	total: 12.1s	remaining: 19.8s
379:	learn: 0.0731751	total: 12.1s	remaining: 19.8s
380:	learn: 0.0730757	total: 12.2s	remaining: 19.8s
381:	learn: 0.0729562	total: 12.2s	remaining: 19.8s
382:	learn: 0.0728130	total: 12.2s	remaining: 19.7s
383:	learn: 0.0726602	total: 12.3s	remaining: 19.7s
384:	learn: 0.0725521	total: 12.3s	remaining: 19.7s
385:	learn: 0.0724974	total: 12.3s	remaining: 19.6s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Electrical': 1 unseen categories converted to Unseen on transform.

CV folds:   8%|▊         | 4/50 [02:05<24:16, 31.67s/fold]

998:	learn: 0.0398789	total: 31.6s	remaining: 31.7ms
999:	learn: 0.0398291	total: 31.7s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3911046	total: 24.2ms	remaining: 24.2s
1:	learn: 0.3804020	total: 58.1ms	remaining: 29s
2:	learn: 0.3695294	total: 94.6ms	remaining: 31.4s
3:	learn: 0.3597389	total: 143ms	remaining: 35.5s
4:	learn: 0.3501897	total: 181ms	remaining: 36s
5:	learn: 0.3410115	total: 233ms	remaining: 38.7s
6:	learn: 0.3322122	total: 278ms	remaining: 39.4s
7:	learn: 0.3239329	total: 326ms	remaining: 40.4s
8:	learn: 0.3161522	total: 353ms	remaining: 38.9s
9:	learn: 0.3088010	total: 381ms	remaining: 37.7s
10:	learn: 0.3009188	total: 405ms	remaining: 36.4s
11:	learn: 0.2937571	total: 432ms	remaining: 35.6s
12:	learn: 0.2867883	total: 463ms	remaining: 35.1s
13:	learn: 0.2797678	total: 495ms	remaining: 34.9s
14:	learn: 0.2740344	total: 524ms	remaining: 34.4s
15:	learn: 0.2676045	total: 550ms	remaining: 33.9s
16:	learn: 0.2619592	total: 578ms	remaining: 33.4s
17:	learn: 0.2560494	total: 606ms	remaining: 33.1s
18:	learn: 0.2506007	total: 634ms	remaining: 32.8s
19:	learn: 0.2458738	total: 658ms	remaining: 32.2s
20:	learn: 0.2409918	total: 689ms	remaining: 32.1s
21:	learn: 0.2359941	total: 718ms	remaining: 31.9s
22:	learn: 0.2312594	total: 749ms	remaining: 31.8s
23:	learn: 0.2268997	total: 780ms	remaining: 31.7s
24:	learn: 0.2224233	total: 813ms	remaining: 31.7s
25:	learn: 0.2181944	total: 842ms	remaining: 31.6s
26:	learn: 0.2145146	total: 874ms	remaining: 31.5s
27:	learn: 0.2107208	total: 903ms	remaining: 31.4s
28:	learn: 0.2068951	total: 937ms	remaining: 31.4s
29:	learn: 0.2033987	total: 998ms	remaining: 32.3s
30:	learn: 0.2000563	total: 1.03s	remaining: 32.1s
31:	learn: 0.1977258	total: 1.07s	remaining: 32.4s
32:	learn: 0.1945274	total: 1.1s	remaining: 32.2s
33:	learn: 0.1917278	total: 1.13s	remaining: 32s
34:	learn: 0.1886835	total: 1.16s	remaining: 31.9s
35:	learn: 0.1862416	total: 1.19s	remaining: 31.8s
36:	learn: 0.1833501	total: 1.22s	remaining: 31.6s
37:	learn: 0.1806088	total: 1.24s	remaining: 31.5s
38:	learn: 0.1782721	total: 1.27s	remaining: 31.4s
39:	learn: 0.1755424	total: 1.3s	remaining: 31.3s
40:	learn: 0.1731810	total: 1.34s	remaining: 31.4s
41:	learn: 0.1707311	total: 1.37s	remaining: 31.3s
42:	learn: 0.1684491	total: 1.41s	remaining: 31.3s
43:	learn: 0.1662132	total: 1.43s	remaining: 31.2s
44:	learn: 0.1644053	total: 1.47s	remaining: 31.1s
45:	learn: 0.1624828	total: 1.5s	remaining: 31s
46:	learn: 0.1605808	total: 1.52s	remaining: 30.9s
47:	learn: 0.1590270	total: 1.55s	remaining: 30.8s
48:	learn: 0.1573444	total: 1.58s	remaining: 30.8s
49:	learn: 0.1559875	total: 1.61s	remaining: 30.6s
50:	learn: 0.1542560	total: 1.64s	remaining: 30.6s
51:	learn: 0.1526390	total: 1.67s	remaining: 30.5s
52:	learn: 0.1512594	total: 1.71s	remaining: 30.5s
53:	learn: 0.1499599	total: 1.74s	remaining: 30.4s
54:	learn: 0.1483603	total: 1.77s	remaining: 30.4s
55:	learn: 0.1471687	total: 1.8s	remaining: 30.3s
56:	learn: 0.1457297	total: 1.83s	remaining: 30.3s
57:	learn: 0.1445119	total: 1.86s	remaining: 30.2s
58:	learn: 0.1433439	total: 1.89s	remaining: 30.1s
59:	learn: 0.1421654	total: 1.92s	remaining: 30s
60:	learn: 0.1409641	total: 1.95s	remaining: 30s
61:	learn: 0.1399975	total: 1.98s	remaining: 29.9s
62:	learn: 0.1388880	total: 2.02s	remaining: 30s
63:	learn: 0.1380055	total: 2.05s	remaining: 29.9s
64:	learn: 0.1370232	total: 2.07s	remaining: 29.8s
65:	learn: 0.1359704	total: 2.1s	remaining: 29.8s
66:	learn: 0.1351271	total: 2.13s	remaining: 29.7s
67:	learn: 0.1341049	total: 2.16s	remaining: 29.6s
68:	learn: 0.1332036	total: 2.19s	remaining: 29.6s
69:	learn: 0.1325122	total: 2.22s	remaining: 29.5s
70:	learn: 0.1318389	total: 2.25s	remaining: 29.5s
71:	learn: 0.1310801	total: 2.28s	remaining: 29.4s
72:	learn: 0.1303650	total: 2.31s	remaining: 29.4s
73:	learn: 0.1295986	total: 2.35s	remaining: 29.3s
74:	learn: 0.1288475	total: 2.38s	remaining: 29.3s
75:	learn: 0.1282434	total: 2.4s	remaining: 29.2s
76:	learn: 0.1274105	total: 2.44s	remaining: 29.2s
77:	learn: 0.1266646	total: 2.47s	remaining: 29.1s
78:	learn: 0.1262133	total: 2.5s	remaining: 29.1s
79:	learn: 0.1256671	total: 2.53s	remaining: 29.1s
80:	learn: 0.1250719	total: 2.56s	remaining: 29s
81:	learn: 0.1245310	total: 2.59s	remaining: 29s
82:	learn: 0.1240137	total: 2.62s	remaining: 28.9s
83:	learn: 0.1234584	total: 2.65s	remaining: 28.9s
84:	learn: 0.1227848	total: 2.68s	remaining: 28.9s
85:	learn: 0.1222272	total: 2.71s	remaining: 28.8s
86:	learn: 0.1216458	total: 2.74s	remaining: 28.7s
87:	learn: 0.1211581	total: 2.77s	remaining: 28.7s
88:	learn: 0.1207075	total: 2.8s	remaining: 28.6s
89:	learn: 0.1201530	total: 2.83s	remaining: 28.6s
90:	learn: 0.1197804	total: 2.85s	remaining: 28.5s
91:	learn: 0.1192341	total: 2.89s	remaining: 28.5s
92:	learn: 0.1187718	total: 2.91s	remaining: 28.4s
93:	learn: 0.1184812	total: 2.95s	remaining: 28.4s
94:	learn: 0.1180106	total: 2.98s	remaining: 28.4s
95:	learn: 0.1175568	total: 3s	remaining: 28.3s
96:	learn: 0.1171078	total: 3.03s	remaining: 28.2s
97:	learn: 0.1167660	total: 3.06s	remaining: 28.2s
98:	learn: 0.1163939	total: 3.09s	remaining: 28.1s
99:	learn: 0.1161406	total: 3.12s	remaining: 28.1s
100:	learn: 0.1156225	total: 3.15s	remaining: 28.1s
101:	learn: 0.1150775	total: 3.19s	remaining: 28.1s
102:	learn: 0.1145747	total: 3.23s	remaining: 28.1s
103:	learn: 0.1141689	total: 3.26s	remaining: 28.1s
104:	learn: 0.1137137	total: 3.29s	remaining: 28s
105:	learn: 0.1131613	total: 3.32s	remaining: 28s
106:	learn: 0.1127638	total: 3.35s	remaining: 28s
107:	learn: 0.1124951	total: 3.38s	remaining: 27.9s
108:	learn: 0.1122061	total: 3.41s	remaining: 27.9s
109:	learn: 0.1119291	total: 3.44s	remaining: 27.9s
110:	learn: 0.1116009	total: 3.48s	remaining: 27.9s
111:	learn: 0.1112729	total: 3.51s	remaining: 27.8s
112:	learn: 0.1108534	total: 3.54s	remaining: 27.8s
113:	learn: 0.1106590	total: 3.57s	remaining: 27.7s
114:	learn: 0.1105104	total: 3.6s	remaining: 27.7s
115:	learn: 0.1100948	total: 3.63s	remaining: 27.6s
116:	learn: 0.1098033	total: 3.66s	remaining: 27.6s
117:	learn: 0.1095084	total: 3.69s	remaining: 27.6s
118:	learn: 0.1091634	total: 3.72s	remaining: 27.6s
119:	learn: 0.1089532	total: 3.75s	remaining: 27.5s
120:	learn: 0.1086508	total: 3.79s	remaining: 27.5s
121:	learn: 0.1083173	total: 3.82s	remaining: 27.5s
122:	learn: 0.1082896	total: 3.83s	remaining: 27.3s
123:	learn: 0.1080311	total: 3.85s	remaining: 27.2s
124:	learn: 0.1077052	total: 3.88s	remaining: 27.2s
125:	learn: 0.1074668	total: 3.91s	remaining: 27.1s
126:	learn: 0.1071360	total: 3.94s	remaining: 27.1s
127:	learn: 0.1068018	total: 3.97s	remaining: 27.1s
128:	learn: 0.1065791	total: 4s	remaining: 27s
129:	learn: 0.1062319	total: 4.03s	remaining: 27s
130:	learn: 0.1060267	total: 4.06s	remaining: 27s
131:	learn: 0.1057848	total: 4.09s	remaining: 26.9s
132:	learn: 0.1055405	total: 4.12s	remaining: 26.9s
133:	learn: 0.1052954	total: 4.15s	remaining: 26.8s
134:	learn: 0.1050651	total: 4.18s	remaining: 26.8s
135:	learn: 0.1047567	total: 4.21s	remaining: 26.8s
136:	learn: 0.1045960	total: 4.25s	remaining: 26.8s
137:	learn: 0.1044676	total: 4.28s	remaining: 26.7s
138:	learn: 0.1043226	total: 4.31s	remaining: 26.7s
139:	learn: 0.1040276	total: 4.34s	remaining: 26.7s
140:	learn: 0.1036728	total: 4.37s	remaining: 26.6s
141:	learn: 0.1033713	total: 4.4s	remaining: 26.6s
142:	learn: 0.1031733	total: 4.43s	remaining: 26.6s
143:	learn: 0.1029439	total: 4.46s	remaining: 26.5s
144:	learn: 0.1027363	total: 4.49s	remaining: 26.5s
145:	learn: 0.1025175	total: 4.53s	remaining: 26.5s
146:	learn: 0.1022776	total: 4.55s	remaining: 26.4s
147:	learn: 0.1021016	total: 4.58s	remaining: 26.4s
148:	learn: 0.1018335	total: 4.61s	remaining: 26.4s
149:	learn: 0.1016514	total: 4.64s	remaining: 26.3s
150:	learn: 0.1014901	total: 4.68s	remaining: 26.3s
151:	learn: 0.1012374	total: 4.7s	remaining: 26.2s
152:	learn: 0.1010639	total: 4.74s	remaining: 26.2s
153:	learn: 0.1009133	total: 4.76s	remaining: 26.2s
154:	learn: 0.1007346	total: 4.79s	remaining: 26.1s
155:	learn: 0.1005413	total: 4.82s	remaining: 26.1s
156:	learn: 0.1002974	total: 4.85s	remaining: 26.1s
157:	learn: 0.1001571	total: 4.88s	remaining: 26s
158:	learn: 0.0999484	total: 4.92s	remaining: 26s
159:	learn: 0.0997901	total: 4.95s	remaining: 26s
160:	learn: 0.0995255	total: 4.98s	remaining: 25.9s
161:	learn: 0.0993672	total: 5.01s	remaining: 25.9s
162:	learn: 0.0991970	total: 5.03s	remaining: 25.9s
163:	learn: 0.0989568	total: 5.07s	remaining: 25.8s
164:	learn: 0.0987936	total: 5.09s	remaining: 25.8s
165:	learn: 0.0986603	total: 5.13s	remaining: 25.8s
166:	learn: 0.0983824	total: 5.16s	remaining: 25.7s
167:	learn: 0.0981299	total: 5.19s	remaining: 25.7s
168:	learn: 0.0978953	total: 5.22s	remaining: 25.7s
169:	learn: 0.0977129	total: 5.25s	remaining: 25.6s
170:	learn: 0.0975703	total: 5.28s	remaining: 25.6s
171:	learn: 0.0973159	total: 5.33s	remaining: 25.7s
172:	learn: 0.0972230	total: 5.39s	remaining: 25.8s
173:	learn: 0.0971097	total: 5.41s	remaining: 25.7s
174:	learn: 0.0969980	total: 5.44s	remaining: 25.7s
175:	learn: 0.0968431	total: 5.47s	remaining: 25.6s
176:	learn: 0.0967298	total: 5.5s	remaining: 25.6s
177:	learn: 0.0966254	total: 5.53s	remaining: 25.6s
178:	learn: 0.0964047	total: 5.57s	remaining: 25.5s
179:	learn: 0.0961715	total: 5.59s	remaining: 25.5s
180:	learn: 0.0959559	total: 5.62s	remaining: 25.4s
181:	learn: 0.0958473	total: 5.66s	remaining: 25.4s
182:	learn: 0.0956845	total: 5.68s	remaining: 25.4s
183:	learn: 0.0955247	total: 5.71s	remaining: 25.3s
184:	learn: 0.0953691	total: 5.75s	remaining: 25.3s
185:	learn: 0.0951993	total: 5.78s	remaining: 25.3s
186:	learn: 0.0950111	total: 5.81s	remaining: 25.3s
187:	learn: 0.0948559	total: 5.84s	remaining: 25.2s
188:	learn: 0.0947367	total: 5.87s	remaining: 25.2s
189:	learn: 0.0946093	total: 5.9s	remaining: 25.2s
190:	learn: 0.0944302	total: 5.93s	remaining: 25.1s
191:	learn: 0.0943507	total: 5.96s	remaining: 25.1s
192:	learn: 0.0941192	total: 5.99s	remaining: 25s
193:	learn: 0.0940267	total: 6.02s	remaining: 25s
194:	learn: 0.0938259	total: 6.05s	remaining: 25s
195:	learn: 0.0937298	total: 6.08s	remaining: 24.9s
196:	learn: 0.0935380	total: 6.11s	remaining: 24.9s
197:	learn: 0.0933787	total: 6.14s	remaining: 24.9s
198:	learn: 0.0932858	total: 6.17s	remaining: 24.8s
199:	learn: 0.0930505	total: 6.2s	remaining: 24.8s
200:	learn: 0.0929382	total: 6.23s	remaining: 24.8s
201:	learn: 0.0927201	total: 6.27s	remaining: 24.8s
202:	learn: 0.0925371	total: 6.29s	remaining: 24.7s
203:	learn: 0.0924856	total: 6.33s	remaining: 24.7s
204:	learn: 0.0923015	total: 6.36s	remaining: 24.7s
205:	learn: 0.0921068	total: 6.39s	remaining: 24.6s
206:	learn: 0.0918780	total: 6.42s	remaining: 24.6s
207:	learn: 0.0917238	total: 6.45s	remaining: 24.6s
208:	learn: 0.0916452	total: 6.48s	remaining: 24.5s
209:	learn: 0.0915250	total: 6.51s	remaining: 24.5s
210:	learn: 0.0913498	total: 6.54s	remaining: 24.5s
211:	learn: 0.0913084	total: 6.57s	remaining: 24.4s
212:	learn: 0.0912033	total: 6.61s	remaining: 24.4s
213:	learn: 0.0910819	total: 6.64s	remaining: 24.4s
214:	learn: 0.0910223	total: 6.67s	remaining: 24.4s
215:	learn: 0.0908098	total: 6.7s	remaining: 24.3s
216:	learn: 0.0907291	total: 6.73s	remaining: 24.3s
217:	learn: 0.0904911	total: 6.76s	remaining: 24.3s
218:	learn: 0.0903715	total: 6.79s	remaining: 24.2s
219:	learn: 0.0901523	total: 6.82s	remaining: 24.2s
220:	learn: 0.0900371	total: 6.85s	remaining: 24.2s
221:	learn: 0.0899898	total: 6.89s	remaining: 24.1s
222:	learn: 0.0898674	total: 6.92s	remaining: 24.1s
223:	learn: 0.0898302	total: 6.95s	remaining: 24.1s
224:	learn: 0.0896389	total: 6.97s	remaining: 24s
225:	learn: 0.0895264	total: 7s	remaining: 24s
226:	learn: 0.0894538	total: 7.03s	remaining: 23.9s
227:	learn: 0.0894194	total: 7.06s	remaining: 23.9s
228:	learn: 0.0893842	total: 7.09s	remaining: 23.9s
229:	learn: 0.0892137	total: 7.12s	remaining: 23.9s
230:	learn: 0.0891697	total: 7.15s	remaining: 23.8s
231:	learn: 0.0891383	total: 7.18s	remaining: 23.8s
232:	learn: 0.0889511	total: 7.21s	remaining: 23.7s
233:	learn: 0.0889103	total: 7.24s	remaining: 23.7s
234:	learn: 0.0888860	total: 7.28s	remaining: 23.7s
235:	learn: 0.0888575	total: 7.31s	remaining: 23.7s
236:	learn: 0.0887762	total: 7.34s	remaining: 23.6s
237:	learn: 0.0886394	total: 7.38s	remaining: 23.6s
238:	learn: 0.0885639	total: 7.41s	remaining: 23.6s
239:	learn: 0.0884910	total: 7.43s	remaining: 23.5s
240:	learn: 0.0884393	total: 7.46s	remaining: 23.5s
241:	learn: 0.0882756	total: 7.5s	remaining: 23.5s
242:	learn: 0.0882457	total: 7.54s	remaining: 23.5s
243:	learn: 0.0880974	total: 7.57s	remaining: 23.5s
244:	learn: 0.0880653	total: 7.6s	remaining: 23.4s
245:	learn: 0.0879705	total: 7.63s	remaining: 23.4s
246:	learn: 0.0877650	total: 7.67s	remaining: 23.4s
247:	learn: 0.0876969	total: 7.71s	remaining: 23.4s
248:	learn: 0.0874904	total: 7.75s	remaining: 23.4s
249:	learn: 0.0874552	total: 7.78s	remaining: 23.3s
250:	learn: 0.0874179	total: 7.81s	remaining: 23.3s
251:	learn: 0.0873843	total: 7.84s	remaining: 23.3s
252:	learn: 0.0872486	total: 7.87s	remaining: 23.2s
253:	learn: 0.0872160	total: 7.9s	remaining: 23.2s
254:	learn: 0.0869782	total: 7.93s	remaining: 23.2s
255:	learn: 0.0868253	total: 7.97s	remaining: 23.2s
256:	learn: 0.0866839	total: 8s	remaining: 23.1s
257:	learn: 0.0865460	total: 8.03s	remaining: 23.1s
258:	learn: 0.0865098	total: 8.06s	remaining: 23.1s
259:	learn: 0.0864198	total: 8.09s	remaining: 23s
260:	learn: 0.0863023	total: 8.12s	remaining: 23s
261:	learn: 0.0862706	total: 8.15s	remaining: 22.9s
262:	learn: 0.0861881	total: 8.18s	remaining: 22.9s
263:	learn: 0.0860925	total: 8.21s	remaining: 22.9s
264:	learn: 0.0860484	total: 8.24s	remaining: 22.9s
265:	learn: 0.0860316	total: 8.27s	remaining: 22.8s
266:	learn: 0.0858597	total: 8.3s	remaining: 22.8s
267:	learn: 0.0858298	total: 8.33s	remaining: 22.8s
268:	learn: 0.0856710	total: 8.36s	remaining: 22.7s
269:	learn: 0.0856390	total: 8.4s	remaining: 22.7s
270:	learn: 0.0856104	total: 8.43s	remaining: 22.7s
271:	learn: 0.0855014	total: 8.46s	remaining: 22.6s
272:	learn: 0.0853651	total: 8.49s	remaining: 22.6s
273:	learn: 0.0853060	total: 8.52s	remaining: 22.6s
274:	learn: 0.0852950	total: 8.55s	remaining: 22.5s
275:	learn: 0.0851917	total: 8.58s	remaining: 22.5s
276:	learn: 0.0851617	total: 8.61s	remaining: 22.5s
277:	learn: 0.0850840	total: 8.64s	remaining: 22.4s
278:	learn: 0.0850562	total: 8.67s	remaining: 22.4s
279:	learn: 0.0849902	total: 8.7s	remaining: 22.4s
280:	learn: 0.0848514	total: 8.73s	remaining: 22.3s
281:	learn: 0.0846794	total: 8.76s	remaining: 22.3s
282:	learn: 0.0846337	total: 8.79s	remaining: 22.3s
283:	learn: 0.0845537	total: 8.82s	remaining: 22.2s
284:	learn: 0.0844353	total: 8.85s	remaining: 22.2s
285:	learn: 0.0843682	total: 8.88s	remaining: 22.2s
286:	learn: 0.0843565	total: 8.91s	remaining: 22.1s
287:	learn: 0.0843489	total: 8.94s	remaining: 22.1s
288:	learn: 0.0842422	total: 8.97s	remaining: 22.1s
289:	learn: 0.0842017	total: 9s	remaining: 22s
290:	learn: 0.0840557	total: 9.03s	remaining: 22s
291:	learn: 0.0840475	total: 9.06s	remaining: 22s
292:	learn: 0.0839596	total: 9.09s	remaining: 21.9s
293:	learn: 0.0839294	total: 9.13s	remaining: 21.9s
294:	learn: 0.0837653	total: 9.15s	remaining: 21.9s
295:	learn: 0.0836143	total: 9.19s	remaining: 21.8s
296:	learn: 0.0834793	total: 9.21s	remaining: 21.8s
297:	learn: 0.0834540	total: 9.24s	remaining: 21.8s
298:	learn: 0.0833461	total: 9.28s	remaining: 21.8s
299:	learn: 0.0832345	total: 9.31s	remaining: 21.7s
300:	learn: 0.0832285	total: 9.34s	remaining: 21.7s
301:	learn: 0.0832080	total: 9.37s	remaining: 21.7s
302:	learn: 0.0831352	total: 9.4s	remaining: 21.6s
303:	learn: 0.0831180	total: 9.44s	remaining: 21.6s
304:	learn: 0.0830867	total: 9.47s	remaining: 21.6s
305:	learn: 0.0829007	total: 9.5s	remaining: 21.6s
306:	learn: 0.0827846	total: 9.53s	remaining: 21.5s
307:	learn: 0.0826120	total: 9.56s	remaining: 21.5s
308:	learn: 0.0825385	total: 9.6s	remaining: 21.5s
309:	learn: 0.0824152	total: 9.63s	remaining: 21.4s
310:	learn: 0.0823010	total: 9.67s	remaining: 21.4s
311:	learn: 0.0821462	total: 9.7s	remaining: 21.4s
312:	learn: 0.0820061	total: 9.73s	remaining: 21.3s
313:	learn: 0.0819984	total: 9.76s	remaining: 21.3s
314:	learn: 0.0819923	total: 9.79s	remaining: 21.3s
315:	learn: 0.0818765	total: 9.82s	remaining: 21.3s
316:	learn: 0.0818215	total: 9.85s	remaining: 21.2s
317:	learn: 0.0816954	total: 9.88s	remaining: 21.2s
318:	learn: 0.0816860	total: 9.91s	remaining: 21.2s
319:	learn: 0.0815635	total: 9.94s	remaining: 21.1s
320:	learn: 0.0815563	total: 9.98s	remaining: 21.1s
321:	learn: 0.0814247	total: 10s	remaining: 21.1s
322:	learn: 0.0814158	total: 10s	remaining: 21s
323:	learn: 0.0813210	total: 10.1s	remaining: 21s
324:	learn: 0.0812306	total: 10.1s	remaining: 21s
325:	learn: 0.0810944	total: 10.1s	remaining: 20.9s
326:	learn: 0.0809234	total: 10.2s	remaining: 20.9s
327:	learn: 0.0807305	total: 10.2s	remaining: 20.9s
328:	learn: 0.0805277	total: 10.2s	remaining: 20.8s
329:	learn: 0.0805191	total: 10.2s	remaining: 20.8s
330:	learn: 0.0804761	total: 10.3s	remaining: 20.8s
331:	learn: 0.0803221	total: 10.3s	remaining: 20.7s
332:	learn: 0.0802350	total: 10.3s	remaining: 20.7s
333:	learn: 0.0802100	total: 10.4s	remaining: 20.7s
334:	learn: 0.0801671	total: 10.4s	remaining: 20.6s
335:	learn: 0.0801587	total: 10.4s	remaining: 20.6s
336:	learn: 0.0800807	total: 10.5s	remaining: 20.6s
337:	learn: 0.0800546	total: 10.5s	remaining: 20.5s
338:	learn: 0.0799170	total: 10.5s	remaining: 20.5s
339:	learn: 0.0797850	total: 10.5s	remaining: 20.5s
340:	learn: 0.0797672	total: 10.6s	remaining: 20.4s
341:	learn: 0.0796623	total: 10.6s	remaining: 20.4s
342:	learn: 0.0794961	total: 10.6s	remaining: 20.4s
343:	learn: 0.0794740	total: 10.7s	remaining: 20.3s
344:	learn: 0.0793610	total: 10.7s	remaining: 20.3s
345:	learn: 0.0792249	total: 10.7s	remaining: 20.3s
346:	learn: 0.0790913	total: 10.8s	remaining: 20.2s
347:	learn: 0.0789498	total: 10.8s	remaining: 20.2s
348:	learn: 0.0787304	total: 10.8s	remaining: 20.2s
349:	learn: 0.0784393	total: 10.8s	remaining: 20.1s
350:	learn: 0.0783690	total: 10.9s	remaining: 20.1s
351:	learn: 0.0782958	total: 10.9s	remaining: 20.1s
352:	learn: 0.0782881	total: 10.9s	remaining: 20.1s
353:	learn: 0.0781840	total: 11s	remaining: 20s
354:	learn: 0.0781599	total: 11s	remaining: 20s
355:	learn: 0.0780963	total: 11s	remaining: 20s
356:	learn: 0.0780502	total: 11.1s	remaining: 19.9s
357:	learn: 0.0780069	total: 11.1s	remaining: 19.9s
358:	learn: 0.0779939	total: 11.1s	remaining: 19.9s
359:	learn: 0.0779863	total: 11.2s	remaining: 19.9s
360:	learn: 0.0779423	total: 11.2s	remaining: 19.8s
361:	learn: 0.0779168	total: 11.2s	remaining: 19.8s
362:	learn: 0.0778244	total: 11.3s	remaining: 19.8s
363:	learn: 0.0777479	total: 11.3s	remaining: 19.8s
364:	learn: 0.0775435	total: 11.3s	remaining: 19.7s
365:	learn: 0.0775309	total: 11.4s	remaining: 19.7s
366:	learn: 0.0775114	total: 11.4s	remaining: 19.7s
367:	learn: 0.0773174	total: 11.4s	remaining: 19.6s
368:	learn: 0.0772799	total: 11.5s	remaining: 19.6s
369:	learn: 0.0771200	total: 11.5s	remaining: 19.6s
370:	learn: 0.0770221	total: 11.5s	remaining: 19.6s
371:	learn: 0.0769846	total: 11.6s	remaining: 19.5s
372:	learn: 0.0768754	total: 11.6s	remaining: 19.5s
373:	learn: 0.0768139	total: 11.6s	remaining: 19.5s
374:	learn: 0.0766264	total: 11.7s	remaining: 19.4s
375:	learn: 0.0765036	total: 11.7s	remaining: 19.4s
376:	learn: 0.0764058	total: 11.7s	remaining: 19.4s
377:	learn: 0.0763833	total: 11.8s	remaining: 19.3s
378:	learn: 0.0762459	total: 11.8s	remaining: 19.3s
379:	learn: 0.0761349	total: 11.8s	remaining: 19.3s
380:	learn: 0.0760312	total: 11.9s	remaining: 19.3s
381:	learn: 0.0760109	total: 11.9s	remaining: 19.3s
382:	learn: 0.0759678	total: 12s	remaining: 19.3s
383:	learn: 0.0759482	total: 12s	remaining: 19.2s
384:	learn: 0.0758696	total: 12s	remaining: 19.2s
385:	learn: 0.0758532	total: 12.1s	remaining: 19.2s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior1st': 1 unseen categories converted to Unseen on transform.

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior2nd': 1 unseen categories converted to Unseen on transform.

CV folds:  10%|█         | 5/50 [02:37<23:42, 31.62s/fold]

Learning rate set to 0.042738
0:	learn: 0.3881124	total: 31.6ms	remaining: 31.6s
1:	learn: 0.3775947	total: 65.7ms	remaining: 32.8s
2:	learn: 0.3671104	total: 96.6ms	remaining: 32.1s
3:	learn: 0.3578181	total: 127ms	remaining: 31.5s
4:	learn: 0.3485012	total: 162ms	remaining: 32.3s
5:	learn: 0.3394908	total: 195ms	remaining: 32.3s
6:	learn: 0.3311827	total: 225ms	remaining: 31.9s
7:	learn: 0.3226602	total: 255ms	remaining: 31.6s
8:	learn: 0.3141675	total: 288ms	remaining: 31.7s
9:	learn: 0.3067742	total: 314ms	remaining: 31.1s
10:	learn: 0.2992200	total: 344ms	remaining: 30.9s
11:	learn: 0.2923372	total: 373ms	remaining: 30.7s
12:	learn: 0.2848114	total: 402ms	remaining: 30.5s
13:	learn: 0.2781845	total: 431ms	remaining: 30.4s
14:	learn: 0.2725557	total: 451ms	remaining: 29.6s
15:	learn: 0.2660581	total: 481ms	remaining: 29.6s
16:	learn: 0.2601968	total: 511ms	remaining: 29.5s
17:	learn: 0.2551112	total: 542ms	remaining: 29.6s
18:	learn: 0.2494604	total: 571ms	remaining: 29.5s
19:	learn: 0.2436706	total: 599ms	remaining: 29.4s
20:	learn: 0.2386154	total: 625ms	remaining: 29.2s
21:	learn: 0.2336920	total: 654ms	remaining: 29.1s
22:	learn: 0.2291191	total: 683ms	remaining: 29s
23:	learn: 0.2250172	total: 715ms	remaining: 29.1s
24:	learn: 0.2207834	total: 745ms	remaining: 29.1s
25:	learn: 0.2164454	total: 772ms	remaining: 28.9s
26:	learn: 0.2121785	total: 801ms	remaining: 28.9s
27:	learn: 0.2085772	total: 828ms	remaining: 28.7s
28:	learn: 0.2051087	total: 855ms	remaining: 28.6s
29:	learn: 0.2019169	total: 884ms	remaining: 28.6s
30:	learn: 0.1989011	total: 911ms	remaining: 28.5s
31:	learn: 0.1954671	total: 941ms	remaining: 28.5s
32:	learn: 0.1922404	total: 971ms	remaining: 28.5s
33:	learn: 0.1894443	total: 1000ms	remaining: 28.4s
34:	learn: 0.1862324	total: 1.03s	remaining: 28.4s
35:	learn: 0.1835405	total: 1.05s	remaining: 28.3s
36:	learn: 0.1805075	total: 1.08s	remaining: 28.2s
37:	learn: 0.1780298	total: 1.11s	remaining: 28.2s
38:	learn: 0.1755376	total: 1.14s	remaining: 28.1s
39:	learn: 0.1730604	total: 1.17s	remaining: 28.1s
40:	learn: 0.1706669	total: 1.2s	remaining: 28.1s
41:	learn: 0.1686901	total: 1.23s	remaining: 28s
42:	learn: 0.1665885	total: 1.26s	remaining: 28s
43:	learn: 0.1646111	total: 1.29s	remaining: 28s
44:	learn: 0.1625948	total: 1.31s	remaining: 27.9s
45:	learn: 0.1605144	total: 1.34s	remaining: 27.8s
46:	learn: 0.1588937	total: 1.37s	remaining: 27.8s
47:	learn: 0.1571132	total: 1.4s	remaining: 27.8s
48:	learn: 0.1552194	total: 1.43s	remaining: 27.8s
49:	learn: 0.1536318	total: 1.46s	remaining: 27.7s
50:	learn: 0.1520327	total: 1.49s	remaining: 27.7s
51:	learn: 0.1506687	total: 1.52s	remaining: 27.7s
52:	learn: 0.1491188	total: 1.55s	remaining: 27.6s
53:	learn: 0.1476156	total: 1.58s	remaining: 27.6s
54:	learn: 0.1462659	total: 1.61s	remaining: 27.6s
55:	learn: 0.1450915	total: 1.64s	remaining: 27.6s
56:	learn: 0.1438290	total: 1.67s	remaining: 27.6s
57:	learn: 0.1426292	total: 1.7s	remaining: 27.5s
58:	learn: 0.1413973	total: 1.73s	remaining: 27.5s
59:	learn: 0.1402537	total: 1.76s	remaining: 27.5s
60:	learn: 0.1391954	total: 1.78s	remaining: 27.5s
61:	learn: 0.1383613	total: 1.8s	remaining: 27.3s
62:	learn: 0.1373307	total: 1.83s	remaining: 27.3s
63:	learn: 0.1363588	total: 1.86s	remaining: 27.3s
64:	learn: 0.1352885	total: 1.89s	remaining: 27.2s
65:	learn: 0.1342206	total: 1.92s	remaining: 27.2s
66:	learn: 0.1333259	total: 1.95s	remaining: 27.2s
67:	learn: 0.1325175	total: 1.99s	remaining: 27.2s
68:	learn: 0.1317870	total: 2.03s	remaining: 27.4s
69:	learn: 0.1309420	total: 2.07s	remaining: 27.4s
70:	learn: 0.1300894	total: 2.1s	remaining: 27.4s
71:	learn: 0.1293492	total: 2.13s	remaining: 27.4s
72:	learn: 0.1284338	total: 2.16s	remaining: 27.4s
73:	learn: 0.1277460	total: 2.19s	remaining: 27.4s
74:	learn: 0.1270833	total: 2.22s	remaining: 27.4s
75:	learn: 0.1263869	total: 2.25s	remaining: 27.3s
76:	learn: 0.1257375	total: 2.28s	remaining: 27.3s
77:	learn: 0.1250522	total: 2.3s	remaining: 27.2s
78:	learn: 0.1244791	total: 2.33s	remaining: 27.2s
79:	learn: 0.1238563	total: 2.36s	remaining: 27.2s
80:	learn: 0.1232768	total: 2.4s	remaining: 27.2s
81:	learn: 0.1227522	total: 2.42s	remaining: 27.1s
82:	learn: 0.1222398	total: 2.45s	remaining: 27.1s
83:	learn: 0.1216877	total: 2.48s	remaining: 27.1s
84:	learn: 0.1212248	total: 2.52s	remaining: 27.1s
85:	learn: 0.1207459	total: 2.55s	remaining: 27.1s
86:	learn: 0.1203318	total: 2.58s	remaining: 27.1s
87:	learn: 0.1198067	total: 2.62s	remaining: 27.1s
88:	learn: 0.1192264	total: 2.65s	remaining: 27.1s
89:	learn: 0.1186894	total: 2.68s	remaining: 27.1s
90:	learn: 0.1181380	total: 2.71s	remaining: 27.1s
91:	learn: 0.1175986	total: 2.74s	remaining: 27.1s
92:	learn: 0.1171141	total: 2.77s	remaining: 27.1s
93:	learn: 0.1167594	total: 2.8s	remaining: 27s
94:	learn: 0.1164260	total: 2.83s	remaining: 27s
95:	learn: 0.1160500	total: 2.87s	remaining: 27s
96:	learn: 0.1157222	total: 2.9s	remaining: 27s
97:	learn: 0.1153399	total: 2.94s	remaining: 27s
98:	learn: 0.1147529	total: 2.97s	remaining: 27.1s
99:	learn: 0.1141311	total: 3s	remaining: 27s
100:	learn: 0.1137636	total: 3.04s	remaining: 27s
101:	learn: 0.1134549	total: 3.07s	remaining: 27s
102:	learn: 0.1129273	total: 3.1s	remaining: 27s
103:	learn: 0.1124811	total: 3.13s	remaining: 27s
104:	learn: 0.1120709	total: 3.17s	remaining: 27s
105:	learn: 0.1117222	total: 3.2s	remaining: 27s
106:	learn: 0.1114700	total: 3.23s	remaining: 26.9s
107:	learn: 0.1111500	total: 3.25s	remaining: 26.9s
108:	learn: 0.1108545	total: 3.29s	remaining: 26.9s
109:	learn: 0.1105758	total: 3.31s	remaining: 26.8s
110:	learn: 0.1103673	total: 3.35s	remaining: 26.8s
111:	learn: 0.1100949	total: 3.38s	remaining: 26.8s
112:	learn: 0.1097039	total: 3.41s	remaining: 26.8s
113:	learn: 0.1094036	total: 3.44s	remaining: 26.8s
114:	learn: 0.1090815	total: 3.47s	remaining: 26.7s
115:	learn: 0.1087533	total: 3.5s	remaining: 26.7s
116:	learn: 0.1085251	total: 3.53s	remaining: 26.7s
117:	learn: 0.1081343	total: 3.57s	remaining: 26.7s
118:	learn: 0.1078227	total: 3.6s	remaining: 26.6s
119:	learn: 0.1075034	total: 3.63s	remaining: 26.6s
120:	learn: 0.1072399	total: 3.67s	remaining: 26.6s
121:	learn: 0.1070541	total: 3.7s	remaining: 26.6s
122:	learn: 0.1068842	total: 3.73s	remaining: 26.6s
123:	learn: 0.1066561	total: 3.76s	remaining: 26.5s
124:	learn: 0.1065050	total: 3.78s	remaining: 26.5s
125:	learn: 0.1062078	total: 3.81s	remaining: 26.5s
126:	learn: 0.1059300	total: 3.84s	remaining: 26.4s
127:	learn: 0.1057245	total: 3.87s	remaining: 26.4s
128:	learn: 0.1054731	total: 3.9s	remaining: 26.3s
129:	learn: 0.1051637	total: 3.93s	remaining: 26.3s
130:	learn: 0.1049345	total: 3.97s	remaining: 26.3s
131:	learn: 0.1047598	total: 4s	remaining: 26.3s
132:	learn: 0.1045065	total: 4.03s	remaining: 26.2s
133:	learn: 0.1043238	total: 4.05s	remaining: 26.2s
134:	learn: 0.1039041	total: 4.09s	remaining: 26.2s
135:	learn: 0.1036821	total: 4.12s	remaining: 26.2s
136:	learn: 0.1034976	total: 4.15s	remaining: 26.1s
137:	learn: 0.1033089	total: 4.18s	remaining: 26.1s
138:	learn: 0.1030875	total: 4.24s	remaining: 26.3s
139:	learn: 0.1028560	total: 4.27s	remaining: 26.3s
140:	learn: 0.1026469	total: 4.3s	remaining: 26.2s
141:	learn: 0.1025338	total: 4.33s	remaining: 26.2s
142:	learn: 0.1024055	total: 4.37s	remaining: 26.2s
143:	learn: 0.1021324	total: 4.4s	remaining: 26.2s
144:	learn: 0.1019623	total: 4.43s	remaining: 26.1s
145:	learn: 0.1018092	total: 4.46s	remaining: 26.1s
146:	learn: 0.1016760	total: 4.49s	remaining: 26.1s
147:	learn: 0.1015713	total: 4.52s	remaining: 26s
148:	learn: 0.1012878	total: 4.55s	remaining: 26s
149:	learn: 0.1011540	total: 4.58s	remaining: 26s
150:	learn: 0.1009768	total: 4.61s	remaining: 25.9s
151:	learn: 0.1008376	total: 4.64s	remaining: 25.9s
152:	learn: 0.1007093	total: 4.67s	remaining: 25.8s
153:	learn: 0.1003572	total: 4.7s	remaining: 25.8s
154:	learn: 0.1001951	total: 4.73s	remaining: 25.8s
155:	learn: 0.1000593	total: 4.76s	remaining: 25.7s
156:	learn: 0.0998424	total: 4.79s	remaining: 25.7s
157:	learn: 0.0996432	total: 4.82s	remaining: 25.7s
158:	learn: 0.0993936	total: 4.85s	remaining: 25.6s
159:	learn: 0.0992220	total: 4.88s	remaining: 25.6s
160:	learn: 0.0990319	total: 4.91s	remaining: 25.6s
161:	learn: 0.0987665	total: 4.94s	remaining: 25.5s
162:	learn: 0.0986358	total: 4.97s	remaining: 25.5s
163:	learn: 0.0985004	total: 5s	remaining: 25.5s
164:	learn: 0.0984086	total: 5.03s	remaining: 25.5s
165:	learn: 0.0982685	total: 5.06s	remaining: 25.4s
166:	learn: 0.0980309	total: 5.09s	remaining: 25.4s
167:	learn: 0.0978469	total: 5.12s	remaining: 25.4s
168:	learn: 0.0977333	total: 5.16s	remaining: 25.4s
169:	learn: 0.0974297	total: 5.19s	remaining: 25.3s
170:	learn: 0.0972822	total: 5.22s	remaining: 25.3s
171:	learn: 0.0971425	total: 5.25s	remaining: 25.3s
172:	learn: 0.0969281	total: 5.28s	remaining: 25.3s
173:	learn: 0.0967696	total: 5.31s	remaining: 25.2s
174:	learn: 0.0966911	total: 5.34s	remaining: 25.2s
175:	learn: 0.0965125	total: 5.37s	remaining: 25.1s
176:	learn: 0.0961843	total: 5.4s	remaining: 25.1s
177:	learn: 0.0960004	total: 5.43s	remaining: 25.1s
178:	learn: 0.0956890	total: 5.46s	remaining: 25s
179:	learn: 0.0956026	total: 5.49s	remaining: 25s
180:	learn: 0.0954749	total: 5.52s	remaining: 25s
181:	learn: 0.0953707	total: 5.55s	remaining: 24.9s
182:	learn: 0.0951676	total: 5.58s	remaining: 24.9s
183:	learn: 0.0950056	total: 5.61s	remaining: 24.9s
184:	learn: 0.0948250	total: 5.63s	remaining: 24.8s
185:	learn: 0.0946840	total: 5.67s	remaining: 24.8s
186:	learn: 0.0945808	total: 5.7s	remaining: 24.8s
187:	learn: 0.0943893	total: 5.73s	remaining: 24.8s
188:	learn: 0.0942251	total: 5.76s	remaining: 24.7s
189:	learn: 0.0940436	total: 5.79s	remaining: 24.7s
190:	learn: 0.0939744	total: 5.82s	remaining: 24.7s
191:	learn: 0.0938773	total: 5.85s	remaining: 24.6s
192:	learn: 0.0937270	total: 5.88s	remaining: 24.6s
193:	learn: 0.0935032	total: 5.91s	remaining: 24.6s
194:	learn: 0.0933736	total: 5.94s	remaining: 24.5s
195:	learn: 0.0932026	total: 5.97s	remaining: 24.5s
196:	learn: 0.0929899	total: 6s	remaining: 24.5s
197:	learn: 0.0928338	total: 6.03s	remaining: 24.4s
198:	learn: 0.0926972	total: 6.07s	remaining: 24.4s
199:	learn: 0.0925472	total: 6.1s	remaining: 24.4s
200:	learn: 0.0924535	total: 6.13s	remaining: 24.4s
201:	learn: 0.0922819	total: 6.16s	remaining: 24.3s
202:	learn: 0.0921323	total: 6.19s	remaining: 24.3s
203:	learn: 0.0919638	total: 6.22s	remaining: 24.3s
204:	learn: 0.0918642	total: 6.25s	remaining: 24.2s
205:	learn: 0.0917635	total: 6.28s	remaining: 24.2s
206:	learn: 0.0916755	total: 6.32s	remaining: 24.2s
207:	learn: 0.0915063	total: 6.36s	remaining: 24.2s
208:	learn: 0.0912986	total: 6.4s	remaining: 24.2s
209:	learn: 0.0910828	total: 6.43s	remaining: 24.2s
210:	learn: 0.0909425	total: 6.46s	remaining: 24.2s
211:	learn: 0.0908123	total: 6.49s	remaining: 24.1s
212:	learn: 0.0906563	total: 6.52s	remaining: 24.1s
213:	learn: 0.0905267	total: 6.55s	remaining: 24.1s
214:	learn: 0.0903553	total: 6.58s	remaining: 24s
215:	learn: 0.0903186	total: 6.61s	remaining: 24s
216:	learn: 0.0901459	total: 6.64s	remaining: 23.9s
217:	learn: 0.0899957	total: 6.67s	remaining: 23.9s
218:	learn: 0.0899500	total: 6.7s	remaining: 23.9s
219:	learn: 0.0898473	total: 6.73s	remaining: 23.9s
220:	learn: 0.0896447	total: 6.76s	remaining: 23.8s
221:	learn: 0.0895112	total: 6.79s	remaining: 23.8s
222:	learn: 0.0894260	total: 6.82s	remaining: 23.8s
223:	learn: 0.0893126	total: 6.85s	remaining: 23.7s
224:	learn: 0.0892651	total: 6.88s	remaining: 23.7s
225:	learn: 0.0892249	total: 6.91s	remaining: 23.7s
226:	learn: 0.0890897	total: 6.94s	remaining: 23.6s
227:	learn: 0.0890401	total: 6.97s	remaining: 23.6s
228:	learn: 0.0888966	total: 7s	remaining: 23.6s
229:	learn: 0.0887502	total: 7.03s	remaining: 23.5s
230:	learn: 0.0886474	total: 7.06s	remaining: 23.5s
231:	learn: 0.0885891	total: 7.09s	remaining: 23.5s
232:	learn: 0.0884886	total: 7.12s	remaining: 23.4s
233:	learn: 0.0884303	total: 7.14s	remaining: 23.4s
234:	learn: 0.0882664	total: 7.17s	remaining: 23.4s
235:	learn: 0.0881264	total: 7.2s	remaining: 23.3s
236:	learn: 0.0880859	total: 7.24s	remaining: 23.3s
237:	learn: 0.0878611	total: 7.26s	remaining: 23.3s
238:	learn: 0.0877990	total: 7.3s	remaining: 23.2s
239:	learn: 0.0877354	total: 7.33s	remaining: 23.2s
240:	learn: 0.0875244	total: 7.35s	remaining: 23.2s
241:	learn: 0.0874008	total: 7.38s	remaining: 23.1s
242:	learn: 0.0873046	total: 7.42s	remaining: 23.1s
243:	learn: 0.0872780	total: 7.44s	remaining: 23.1s
244:	learn: 0.0872508	total: 7.47s	remaining: 23s
245:	learn: 0.0871895	total: 7.5s	remaining: 23s
246:	learn: 0.0871663	total: 7.53s	remaining: 23s
247:	learn: 0.0870737	total: 7.56s	remaining: 22.9s
248:	learn: 0.0869268	total: 7.59s	remaining: 22.9s
249:	learn: 0.0868360	total: 7.62s	remaining: 22.9s
250:	learn: 0.0867347	total: 7.66s	remaining: 22.8s
251:	learn: 0.0867044	total: 7.68s	remaining: 22.8s
252:	learn: 0.0866391	total: 7.72s	remaining: 22.8s
253:	learn: 0.0865423	total: 7.75s	remaining: 22.8s
254:	learn: 0.0864019	total: 7.78s	remaining: 22.7s
255:	learn: 0.0862257	total: 7.81s	remaining: 22.7s
256:	learn: 0.0861586	total: 7.84s	remaining: 22.7s
257:	learn: 0.0860901	total: 7.87s	remaining: 22.6s
258:	learn: 0.0859161	total: 7.9s	remaining: 22.6s
259:	learn: 0.0858890	total: 7.93s	remaining: 22.6s
260:	learn: 0.0857717	total: 7.96s	remaining: 22.5s
261:	learn: 0.0857507	total: 8s	remaining: 22.5s
262:	learn: 0.0856085	total: 8.03s	remaining: 22.5s
263:	learn: 0.0854756	total: 8.06s	remaining: 22.5s
264:	learn: 0.0853242	total: 8.09s	remaining: 22.4s
265:	learn: 0.0852767	total: 8.12s	remaining: 22.4s
266:	learn: 0.0852499	total: 8.15s	remaining: 22.4s
267:	learn: 0.0851310	total: 8.18s	remaining: 22.3s
268:	learn: 0.0849999	total: 8.21s	remaining: 22.3s
269:	learn: 0.0849492	total: 8.26s	remaining: 22.3s
270:	learn: 0.0848937	total: 8.29s	remaining: 22.3s
271:	learn: 0.0847735	total: 8.33s	remaining: 22.3s
272:	learn: 0.0846890	total: 8.36s	remaining: 22.3s
273:	learn: 0.0845930	total: 8.39s	remaining: 22.2s
274:	learn: 0.0845338	total: 8.42s	remaining: 22.2s
275:	learn: 0.0843946	total: 8.45s	remaining: 22.2s
276:	learn: 0.0842523	total: 8.48s	remaining: 22.1s
277:	learn: 0.0841395	total: 8.51s	remaining: 22.1s
278:	learn: 0.0840918	total: 8.57s	remaining: 22.1s
279:	learn: 0.0839692	total: 8.6s	remaining: 22.1s
280:	learn: 0.0839018	total: 8.63s	remaining: 22.1s
281:	learn: 0.0837444	total: 8.66s	remaining: 22s
282:	learn: 0.0836642	total: 8.69s	remaining: 22s
283:	learn: 0.0836470	total: 8.72s	remaining: 22s
284:	learn: 0.0835581	total: 8.75s	remaining: 22s
285:	learn: 0.0834201	total: 8.78s	remaining: 21.9s
286:	learn: 0.0833588	total: 8.81s	remaining: 21.9s
287:	learn: 0.0832717	total: 8.84s	remaining: 21.9s
288:	learn: 0.0831969	total: 8.88s	remaining: 21.8s
289:	learn: 0.0830637	total: 8.91s	remaining: 21.8s
290:	learn: 0.0829812	total: 8.94s	remaining: 21.8s
291:	learn: 0.0829632	total: 8.97s	remaining: 21.7s
292:	learn: 0.0829032	total: 9s	remaining: 21.7s
293:	learn: 0.0828109	total: 9.04s	remaining: 21.7s
294:	learn: 0.0826445	total: 9.07s	remaining: 21.7s
295:	learn: 0.0825975	total: 9.1s	remaining: 21.6s
296:	learn: 0.0825792	total: 9.13s	remaining: 21.6s
297:	learn: 0.0825340	total: 9.16s	remaining: 21.6s
298:	learn: 0.0824031	total: 9.19s	remaining: 21.5s
299:	learn: 0.0823345	total: 9.22s	remaining: 21.5s
300:	learn: 0.0823178	total: 9.26s	remaining: 21.5s
301:	learn: 0.0821974	total: 9.29s	remaining: 21.5s
302:	learn: 0.0821599	total: 9.32s	remaining: 21.4s
303:	learn: 0.0820547	total: 9.35s	remaining: 21.4s
304:	learn: 0.0819818	total: 9.38s	remaining: 21.4s
305:	learn: 0.0818466	total: 9.41s	remaining: 21.3s
306:	learn: 0.0816999	total: 9.44s	remaining: 21.3s
307:	learn: 0.0816730	total: 9.48s	remaining: 21.3s
308:	learn: 0.0815933	total: 9.51s	remaining: 21.3s
309:	learn: 0.0815166	total: 9.54s	remaining: 21.2s
310:	learn: 0.0814628	total: 9.57s	remaining: 21.2s
311:	learn: 0.0813775	total: 9.6s	remaining: 21.2s
312:	learn: 0.0813132	total: 9.63s	remaining: 21.1s
313:	learn: 0.0811441	total: 9.66s	remaining: 21.1s
314:	learn: 0.0810755	total: 9.69s	remaining: 21.1s
315:	learn: 0.0810625	total: 9.72s	remaining: 21s
316:	learn: 0.0809100	total: 9.74s	remaining: 21s
317:	learn: 0.0808255	total: 9.78s	remaining: 21s
318:	learn: 0.0808069	total: 9.81s	remaining: 20.9s
319:	learn: 0.0806904	total: 9.84s	remaining: 20.9s
320:	learn: 0.0806785	total: 9.87s	remaining: 20.9s
321:	learn: 0.0806623	total: 9.9s	remaining: 20.9s
322:	learn: 0.0805172	total: 9.93s	remaining: 20.8s
323:	learn: 0.0804436	total: 9.97s	remaining: 20.8s
324:	learn: 0.0803532	total: 10s	remaining: 20.8s
325:	learn: 0.0803155	total: 10s	remaining: 20.7s
326:	learn: 0.0802594	total: 10.1s	remaining: 20.7s
327:	learn: 0.0802129	total: 10.1s	remaining: 20.7s
328:	learn: 0.0801554	total: 10.1s	remaining: 20.6s
329:	learn: 0.0801229	total: 10.2s	remaining: 20.6s
330:	learn: 0.0801067	total: 10.2s	remaining: 20.6s
331:	learn: 0.0799764	total: 10.2s	remaining: 20.6s
332:	learn: 0.0799657	total: 10.3s	remaining: 20.5s
333:	learn: 0.0798406	total: 10.3s	remaining: 20.5s
334:	learn: 0.0797643	total: 10.3s	remaining: 20.5s
335:	learn: 0.0796097	total: 10.3s	remaining: 20.4s
336:	learn: 0.0795640	total: 10.4s	remaining: 20.4s
337:	learn: 0.0795337	total: 10.4s	remaining: 20.4s
338:	learn: 0.0794089	total: 10.4s	remaining: 20.3s
339:	learn: 0.0793232	total: 10.5s	remaining: 20.3s
340:	learn: 0.0792508	total: 10.5s	remaining: 20.3s
341:	learn: 0.0792206	total: 10.5s	remaining: 20.2s
342:	learn: 0.0791208	total: 10.5s	remaining: 20.2s
343:	learn: 0.0790649	total: 10.6s	remaining: 20.2s
344:	learn: 0.0790330	total: 10.6s	remaining: 20.1s
345:	learn: 0.0788899	total: 10.6s	remaining: 20.1s
346:	learn: 0.0788315	total: 10.7s	remaining: 20.1s
347:	learn: 0.0787924	total: 10.7s	remaining: 20.1s
348:	learn: 0.0787184	total: 10.8s	remaining: 20.1s
349:	learn: 0.0786210	total: 10.8s	remaining: 20s
350:	learn: 0.0785309	total: 10.8s	remaining: 20s
351:	learn: 0.0784842	total: 10.9s	remaining: 20s
352:	learn: 0.0784597	total: 10.9s	remaining: 19.9s
353:	learn: 0.0783638	total: 10.9s	remaining: 19.9s
354:	learn: 0.0783513	total: 10.9s	remaining: 19.9s
355:	learn: 0.0782730	total: 11s	remaining: 19.8s
356:	learn: 0.0781866	total: 11s	remaining: 19.8s
357:	learn: 0.0780384	total: 11s	remaining: 19.8s
358:	learn: 0.0779456	total: 11.1s	remaining: 19.8s
359:	learn: 0.0777720	total: 11.1s	remaining: 19.7s
360:	learn: 0.0777609	total: 11.1s	remaining: 19.7s
361:	learn: 0.0777382	total: 11.2s	remaining: 19.7s
362:	learn: 0.0776887	total: 11.2s	remaining: 19.6s
363:	learn: 0.0776306	total: 11.2s	remaining: 19.6s
364:	learn: 0.0775950	total: 11.2s	remaining: 19.6s
365:	learn: 0.0774992	total: 11.3s	remaining: 19.5s
366:	learn: 0.0774243	total: 11.3s	remaining: 19.5s
367:	learn: 0.0772956	total: 11.3s	remaining: 19.5s
368:	learn: 0.0771886	total: 11.4s	remaining: 19.4s
369:	learn: 0.0770386	total: 11.4s	remaining: 19.4s
370:	learn: 0.0769507	total: 11.4s	remaining: 19.4s
371:	learn: 0.0768372	total: 11.5s	remaining: 19.3s
372:	learn: 0.0767580	total: 11.5s	remaining: 19.3s
373:	learn: 0.0767147	total: 11.5s	remaining: 19.3s
374:	learn: 0.0766952	total: 11.5s	remaining: 19.2s
375:	learn: 0.0766141	total: 11.6s	remaining: 19.2s
376:	learn: 0.0765309	total: 11.6s	remaining: 19.2s
377:	learn: 0.0764983	total: 11.6s	remaining: 19.1s
378:	learn: 0.0764194	total: 11.7s	remaining: 19.1s
379:	learn: 0.0763672	total: 11.7s	remaining: 19.1s
380:	learn: 0.0762364	total: 11.7s	remaining: 19s
381:	learn: 0.0761658	total: 11.8s	remaining: 19s
382:	learn: 0.0761244	total: 11.8s	remaining: 19s
383:	learn: 0.0760470	total: 11.8s	remaining: 19s
384:	learn: 0.0759550	total: 11.8s	remaining: 18.9s
385:	learn: 0.0759374	total: 11.9s	remaining: 18.9s
386:	learn: 0.0758842	total: 11.9s	remaining: 18.9s
387:	learn: 0.0758210	total: 12s	remaining: 18.9s

CV folds:  12%|█▏        | 6/50 [03:09<23:10, 31.60s/fold]

997:	learn: 0.0472183	total: 31s	remaining: 62.1ms
998:	learn: 0.0471714	total: 31s	remaining: 31.1ms
999:	learn: 0.0471609	total: 31.1s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3889042	total: 25.5ms	remaining: 25.5s
1:	learn: 0.3783876	total: 55.2ms	remaining: 27.5s
2:	learn: 0.3673768	total: 85.3ms	remaining: 28.4s
3:	learn: 0.3577057	total: 113ms	remaining: 28.3s
4:	learn: 0.3492716	total: 143ms	remaining: 28.5s
5:	learn: 0.3411566	total: 162ms	remaining: 26.9s
6:	learn: 0.3326316	total: 190ms	remaining: 27s
7:	learn: 0.3237658	total: 222ms	remaining: 27.5s
8:	learn: 0.3155293	total: 253ms	remaining: 27.9s
9:	learn: 0.3077455	total: 287ms	remaining: 28.4s
10:	learn: 0.2996311	total: 316ms	remaining: 28.4s
11:	learn: 0.2918957	total: 347ms	remaining: 28.6s
12:	learn: 0.2851277	total: 377ms	remaining: 28.6s
13:	learn: 0.2788377	total: 407ms	remaining: 28.6s
14:	learn: 0.2722833	total: 437ms	remaining: 28.7s
15:	learn: 0.2663676	total: 467ms	remaining: 28.7s
16:	learn: 0.2606936	total: 499ms	remaining: 28.9s
17:	learn: 0.2548249	total: 530ms	remaining: 28.9s
18:	learn: 0.2491370	total: 560ms	remaining: 28.9s
19:	learn: 0.2437351	total: 588ms	remaining: 28.8s
20:	learn: 0.2389237	total: 617ms	remaining: 28.8s
21:	learn: 0.2341585	total: 646ms	remaining: 28.7s
22:	learn: 0.2292468	total: 675ms	remaining: 28.7s
23:	learn: 0.2248730	total: 710ms	remaining: 28.9s
24:	learn: 0.2206716	total: 745ms	remaining: 29.1s
25:	learn: 0.2167231	total: 772ms	remaining: 28.9s
26:	learn: 0.2129024	total: 803ms	remaining: 28.9s
27:	learn: 0.2092119	total: 833ms	remaining: 28.9s
28:	learn: 0.2058844	total: 864ms	remaining: 28.9s
29:	learn: 0.2021314	total: 916ms	remaining: 29.6s
30:	learn: 0.1988674	total: 943ms	remaining: 29.5s
31:	learn: 0.1954116	total: 971ms	remaining: 29.4s
32:	learn: 0.1922110	total: 999ms	remaining: 29.3s
33:	learn: 0.1891461	total: 1.04s	remaining: 29.7s
34:	learn: 0.1863038	total: 1.08s	remaining: 29.8s
35:	learn: 0.1835324	total: 1.11s	remaining: 29.7s
36:	learn: 0.1807315	total: 1.14s	remaining: 29.7s
37:	learn: 0.1780882	total: 1.17s	remaining: 29.6s
38:	learn: 0.1757432	total: 1.2s	remaining: 29.6s
39:	learn: 0.1735703	total: 1.23s	remaining: 29.5s
40:	learn: 0.1715147	total: 1.26s	remaining: 29.6s
41:	learn: 0.1690377	total: 1.29s	remaining: 29.6s
42:	learn: 0.1670481	total: 1.33s	remaining: 29.5s
43:	learn: 0.1649065	total: 1.36s	remaining: 29.6s
44:	learn: 0.1631192	total: 1.39s	remaining: 29.6s
45:	learn: 0.1612765	total: 1.42s	remaining: 29.5s
46:	learn: 0.1592008	total: 1.45s	remaining: 29.4s
47:	learn: 0.1574056	total: 1.48s	remaining: 29.4s
48:	learn: 0.1555621	total: 1.51s	remaining: 29.3s
49:	learn: 0.1540260	total: 1.54s	remaining: 29.2s
50:	learn: 0.1525488	total: 1.57s	remaining: 29.2s
51:	learn: 0.1510421	total: 1.6s	remaining: 29.1s
52:	learn: 0.1496476	total: 1.63s	remaining: 29.1s
53:	learn: 0.1483290	total: 1.65s	remaining: 29s
54:	learn: 0.1470009	total: 1.68s	remaining: 28.9s
55:	learn: 0.1456655	total: 1.71s	remaining: 28.8s
56:	learn: 0.1442912	total: 1.74s	remaining: 28.8s
57:	learn: 0.1430000	total: 1.76s	remaining: 28.7s
58:	learn: 0.1418463	total: 1.79s	remaining: 28.6s
59:	learn: 0.1408065	total: 1.82s	remaining: 28.6s
60:	learn: 0.1398131	total: 1.85s	remaining: 28.5s
61:	learn: 0.1388795	total: 1.89s	remaining: 28.5s
62:	learn: 0.1377104	total: 1.91s	remaining: 28.5s
63:	learn: 0.1367505	total: 1.95s	remaining: 28.4s
64:	learn: 0.1358323	total: 1.98s	remaining: 28.5s
65:	learn: 0.1347084	total: 2.01s	remaining: 28.4s
66:	learn: 0.1338339	total: 2.04s	remaining: 28.4s
67:	learn: 0.1330729	total: 2.07s	remaining: 28.4s
68:	learn: 0.1325327	total: 2.1s	remaining: 28.3s
69:	learn: 0.1316828	total: 2.13s	remaining: 28.3s
70:	learn: 0.1307628	total: 2.16s	remaining: 28.3s
71:	learn: 0.1299679	total: 2.19s	remaining: 28.2s
72:	learn: 0.1291744	total: 2.22s	remaining: 28.2s
73:	learn: 0.1284890	total: 2.25s	remaining: 28.2s
74:	learn: 0.1276987	total: 2.28s	remaining: 28.2s
75:	learn: 0.1270232	total: 2.32s	remaining: 28.2s
76:	learn: 0.1264018	total: 2.35s	remaining: 28.2s
77:	learn: 0.1257827	total: 2.38s	remaining: 28.1s
78:	learn: 0.1251252	total: 2.41s	remaining: 28.1s
79:	learn: 0.1245550	total: 2.44s	remaining: 28.1s
80:	learn: 0.1239627	total: 2.47s	remaining: 28s
81:	learn: 0.1235458	total: 2.5s	remaining: 28s
82:	learn: 0.1229194	total: 2.53s	remaining: 27.9s
83:	learn: 0.1223973	total: 2.56s	remaining: 27.9s
84:	learn: 0.1219293	total: 2.59s	remaining: 27.9s
85:	learn: 0.1213283	total: 2.62s	remaining: 27.8s
86:	learn: 0.1206997	total: 2.65s	remaining: 27.8s
87:	learn: 0.1202429	total: 2.68s	remaining: 27.8s
88:	learn: 0.1197730	total: 2.71s	remaining: 27.8s
89:	learn: 0.1193815	total: 2.74s	remaining: 27.7s
90:	learn: 0.1189719	total: 2.77s	remaining: 27.7s
91:	learn: 0.1186337	total: 2.8s	remaining: 27.6s
92:	learn: 0.1178459	total: 2.83s	remaining: 27.6s
93:	learn: 0.1173592	total: 2.86s	remaining: 27.6s
94:	learn: 0.1167825	total: 2.89s	remaining: 27.6s
95:	learn: 0.1163168	total: 2.92s	remaining: 27.5s
96:	learn: 0.1159792	total: 2.95s	remaining: 27.5s
97:	learn: 0.1157293	total: 2.97s	remaining: 27.4s
98:	learn: 0.1152102	total: 3.02s	remaining: 27.5s
99:	learn: 0.1148908	total: 3.07s	remaining: 27.6s
100:	learn: 0.1144755	total: 3.1s	remaining: 27.6s
101:	learn: 0.1141390	total: 3.13s	remaining: 27.5s
102:	learn: 0.1137134	total: 3.16s	remaining: 27.5s
103:	learn: 0.1133155	total: 3.19s	remaining: 27.5s
104:	learn: 0.1129555	total: 3.22s	remaining: 27.4s
105:	learn: 0.1125603	total: 3.25s	remaining: 27.4s
106:	learn: 0.1122884	total: 3.28s	remaining: 27.4s
107:	learn: 0.1118851	total: 3.31s	remaining: 27.3s
108:	learn: 0.1116275	total: 3.34s	remaining: 27.3s
109:	learn: 0.1113733	total: 3.37s	remaining: 27.3s
110:	learn: 0.1111106	total: 3.4s	remaining: 27.2s
111:	learn: 0.1108628	total: 3.44s	remaining: 27.2s
112:	learn: 0.1106252	total: 3.47s	remaining: 27.2s
113:	learn: 0.1103410	total: 3.5s	remaining: 27.2s
114:	learn: 0.1100644	total: 3.53s	remaining: 27.2s
115:	learn: 0.1098410	total: 3.56s	remaining: 27.1s
116:	learn: 0.1096778	total: 3.59s	remaining: 27.1s
117:	learn: 0.1093606	total: 3.63s	remaining: 27.1s
118:	learn: 0.1089885	total: 3.66s	remaining: 27.1s
119:	learn: 0.1087467	total: 3.69s	remaining: 27s
120:	learn: 0.1084718	total: 3.72s	remaining: 27s
121:	learn: 0.1080604	total: 3.75s	remaining: 27s
122:	learn: 0.1078022	total: 3.78s	remaining: 26.9s
123:	learn: 0.1075718	total: 3.81s	remaining: 26.9s
124:	learn: 0.1073261	total: 3.84s	remaining: 26.9s
125:	learn: 0.1070622	total: 3.87s	remaining: 26.9s
126:	learn: 0.1068343	total: 3.9s	remaining: 26.8s
127:	learn: 0.1065975	total: 3.93s	remaining: 26.8s
128:	learn: 0.1063856	total: 3.96s	remaining: 26.8s
129:	learn: 0.1062473	total: 3.99s	remaining: 26.7s
130:	learn: 0.1060508	total: 4.02s	remaining: 26.7s
131:	learn: 0.1057808	total: 4.05s	remaining: 26.6s
132:	learn: 0.1055277	total: 4.08s	remaining: 26.6s
133:	learn: 0.1053250	total: 4.11s	remaining: 26.6s
134:	learn: 0.1050813	total: 4.14s	remaining: 26.5s
135:	learn: 0.1048108	total: 4.17s	remaining: 26.5s
136:	learn: 0.1045995	total: 4.21s	remaining: 26.5s
137:	learn: 0.1042840	total: 4.24s	remaining: 26.5s
138:	learn: 0.1040549	total: 4.27s	remaining: 26.4s
139:	learn: 0.1038234	total: 4.3s	remaining: 26.4s
140:	learn: 0.1036384	total: 4.33s	remaining: 26.4s
141:	learn: 0.1034684	total: 4.36s	remaining: 26.4s
142:	learn: 0.1032624	total: 4.39s	remaining: 26.3s
143:	learn: 0.1030027	total: 4.42s	remaining: 26.3s
144:	learn: 0.1027869	total: 4.45s	remaining: 26.2s
145:	learn: 0.1025985	total: 4.48s	remaining: 26.2s
146:	learn: 0.1024695	total: 4.51s	remaining: 26.2s
147:	learn: 0.1023075	total: 4.54s	remaining: 26.1s
148:	learn: 0.1020759	total: 4.57s	remaining: 26.1s
149:	learn: 0.1019539	total: 4.6s	remaining: 26.1s
150:	learn: 0.1016091	total: 4.63s	remaining: 26.1s
151:	learn: 0.1014869	total: 4.67s	remaining: 26s
152:	learn: 0.1011923	total: 4.7s	remaining: 26s
153:	learn: 0.1010389	total: 4.73s	remaining: 26s
154:	learn: 0.1009149	total: 4.76s	remaining: 26s
155:	learn: 0.1007237	total: 4.79s	remaining: 25.9s
156:	learn: 0.1004913	total: 4.82s	remaining: 25.9s
157:	learn: 0.1002543	total: 4.85s	remaining: 25.9s
158:	learn: 0.1000187	total: 4.88s	remaining: 25.8s
159:	learn: 0.0998710	total: 4.92s	remaining: 25.8s
160:	learn: 0.0996188	total: 4.95s	remaining: 25.8s
161:	learn: 0.0995225	total: 4.97s	remaining: 25.7s
162:	learn: 0.0993618	total: 5.01s	remaining: 25.7s
163:	learn: 0.0991335	total: 5.04s	remaining: 25.7s
164:	learn: 0.0989732	total: 5.07s	remaining: 25.7s
165:	learn: 0.0988636	total: 5.1s	remaining: 25.6s
166:	learn: 0.0986192	total: 5.13s	remaining: 25.6s
167:	learn: 0.0984342	total: 5.16s	remaining: 25.5s
168:	learn: 0.0982377	total: 5.2s	remaining: 25.5s
169:	learn: 0.0979730	total: 5.25s	remaining: 25.6s
170:	learn: 0.0977829	total: 5.28s	remaining: 25.6s
171:	learn: 0.0975736	total: 5.31s	remaining: 25.5s
172:	learn: 0.0974451	total: 5.34s	remaining: 25.5s
173:	learn: 0.0972165	total: 5.37s	remaining: 25.5s
174:	learn: 0.0970908	total: 5.4s	remaining: 25.5s
175:	learn: 0.0968397	total: 5.43s	remaining: 25.4s
176:	learn: 0.0966934	total: 5.46s	remaining: 25.4s
177:	learn: 0.0965540	total: 5.49s	remaining: 25.4s
178:	learn: 0.0964438	total: 5.52s	remaining: 25.3s
179:	learn: 0.0962136	total: 5.55s	remaining: 25.3s
180:	learn: 0.0959969	total: 5.58s	remaining: 25.3s
181:	learn: 0.0958936	total: 5.61s	remaining: 25.2s
182:	learn: 0.0956487	total: 5.64s	remaining: 25.2s
183:	learn: 0.0954051	total: 5.67s	remaining: 25.1s
184:	learn: 0.0952085	total: 5.7s	remaining: 25.1s
185:	learn: 0.0950967	total: 5.74s	remaining: 25.1s
186:	learn: 0.0949499	total: 5.76s	remaining: 25.1s
187:	learn: 0.0947508	total: 5.8s	remaining: 25s
188:	learn: 0.0946543	total: 5.83s	remaining: 25s
189:	learn: 0.0944830	total: 5.86s	remaining: 25s
190:	learn: 0.0943802	total: 5.89s	remaining: 24.9s
191:	learn: 0.0942491	total: 5.92s	remaining: 24.9s
192:	learn: 0.0941462	total: 5.95s	remaining: 24.9s
193:	learn: 0.0939986	total: 5.98s	remaining: 24.8s
194:	learn: 0.0938469	total: 6.01s	remaining: 24.8s
195:	learn: 0.0937030	total: 6.04s	remaining: 24.8s
196:	learn: 0.0935996	total: 6.07s	remaining: 24.7s
197:	learn: 0.0934268	total: 6.09s	remaining: 24.7s
198:	learn: 0.0933144	total: 6.12s	remaining: 24.7s
199:	learn: 0.0931444	total: 6.16s	remaining: 24.6s
200:	learn: 0.0931126	total: 6.19s	remaining: 24.6s
201:	learn: 0.0930538	total: 6.22s	remaining: 24.6s
202:	learn: 0.0928907	total: 6.25s	remaining: 24.5s
203:	learn: 0.0926759	total: 6.28s	remaining: 24.5s
204:	learn: 0.0925291	total: 6.31s	remaining: 24.5s
205:	learn: 0.0924162	total: 6.34s	remaining: 24.4s
206:	learn: 0.0922642	total: 6.37s	remaining: 24.4s
207:	learn: 0.0921759	total: 6.41s	remaining: 24.4s
208:	learn: 0.0920546	total: 6.43s	remaining: 24.4s
209:	learn: 0.0918239	total: 6.46s	remaining: 24.3s
210:	learn: 0.0917380	total: 6.5s	remaining: 24.3s
211:	learn: 0.0916722	total: 6.52s	remaining: 24.3s
212:	learn: 0.0916176	total: 6.55s	remaining: 24.2s
213:	learn: 0.0914908	total: 6.58s	remaining: 24.2s
214:	learn: 0.0914698	total: 6.61s	remaining: 24.2s
215:	learn: 0.0913652	total: 6.64s	remaining: 24.1s
216:	learn: 0.0913426	total: 6.67s	remaining: 24.1s
217:	learn: 0.0912275	total: 6.71s	remaining: 24.1s
218:	learn: 0.0911766	total: 6.73s	remaining: 24s
219:	learn: 0.0910251	total: 6.76s	remaining: 24s
220:	learn: 0.0908675	total: 6.79s	remaining: 23.9s
221:	learn: 0.0907144	total: 6.82s	remaining: 23.9s
222:	learn: 0.0906922	total: 6.85s	remaining: 23.9s
223:	learn: 0.0906606	total: 6.88s	remaining: 23.8s
224:	learn: 0.0905938	total: 6.91s	remaining: 23.8s
225:	learn: 0.0905578	total: 6.94s	remaining: 23.8s
226:	learn: 0.0905059	total: 6.97s	remaining: 23.7s
227:	learn: 0.0904666	total: 7s	remaining: 23.7s
228:	learn: 0.0903229	total: 7.03s	remaining: 23.7s
229:	learn: 0.0902445	total: 7.06s	remaining: 23.6s
230:	learn: 0.0902273	total: 7.09s	remaining: 23.6s
231:	learn: 0.0901994	total: 7.13s	remaining: 23.6s
232:	learn: 0.0899833	total: 7.16s	remaining: 23.6s
233:	learn: 0.0899584	total: 7.19s	remaining: 23.5s
234:	learn: 0.0898408	total: 7.22s	remaining: 23.5s
235:	learn: 0.0898224	total: 7.25s	remaining: 23.5s
236:	learn: 0.0895180	total: 7.28s	remaining: 23.4s
237:	learn: 0.0893554	total: 7.31s	remaining: 23.4s
238:	learn: 0.0891815	total: 7.34s	remaining: 23.4s
239:	learn: 0.0890483	total: 7.38s	remaining: 23.4s
240:	learn: 0.0888958	total: 7.41s	remaining: 23.3s
241:	learn: 0.0888096	total: 7.44s	remaining: 23.3s
242:	learn: 0.0886875	total: 7.47s	remaining: 23.3s
243:	learn: 0.0885549	total: 7.5s	remaining: 23.2s
244:	learn: 0.0883902	total: 7.53s	remaining: 23.2s
245:	learn: 0.0882371	total: 7.56s	remaining: 23.2s
246:	learn: 0.0880584	total: 7.59s	remaining: 23.1s
247:	learn: 0.0880433	total: 7.62s	remaining: 23.1s
248:	learn: 0.0879149	total: 7.65s	remaining: 23.1s
249:	learn: 0.0877751	total: 7.68s	remaining: 23s
250:	learn: 0.0877077	total: 7.71s	remaining: 23s
251:	learn: 0.0876885	total: 7.74s	remaining: 23s
252:	learn: 0.0876044	total: 7.77s	remaining: 22.9s
253:	learn: 0.0874651	total: 7.8s	remaining: 22.9s
254:	learn: 0.0872569	total: 7.83s	remaining: 22.9s
255:	learn: 0.0870262	total: 7.86s	remaining: 22.9s
256:	learn: 0.0869954	total: 7.9s	remaining: 22.8s
257:	learn: 0.0869414	total: 7.93s	remaining: 22.8s
258:	learn: 0.0868387	total: 7.96s	remaining: 22.8s
259:	learn: 0.0867132	total: 7.99s	remaining: 22.8s
260:	learn: 0.0866099	total: 8.02s	remaining: 22.7s
261:	learn: 0.0865701	total: 8.05s	remaining: 22.7s
262:	learn: 0.0864798	total: 8.09s	remaining: 22.7s
263:	learn: 0.0863301	total: 8.12s	remaining: 22.6s
264:	learn: 0.0863018	total: 8.15s	remaining: 22.6s
265:	learn: 0.0861831	total: 8.18s	remaining: 22.6s
266:	learn: 0.0860711	total: 8.21s	remaining: 22.6s
267:	learn: 0.0860348	total: 8.25s	remaining: 22.5s
268:	learn: 0.0859957	total: 8.28s	remaining: 22.5s
269:	learn: 0.0858867	total: 8.31s	remaining: 22.5s
270:	learn: 0.0858561	total: 8.34s	remaining: 22.4s
271:	learn: 0.0858025	total: 8.37s	remaining: 22.4s
272:	learn: 0.0857899	total: 8.4s	remaining: 22.4s
273:	learn: 0.0856758	total: 8.43s	remaining: 22.3s
274:	learn: 0.0854952	total: 8.46s	remaining: 22.3s
275:	learn: 0.0854139	total: 8.49s	remaining: 22.3s
276:	learn: 0.0853751	total: 8.52s	remaining: 22.2s
277:	learn: 0.0852578	total: 8.54s	remaining: 22.2s
278:	learn: 0.0851654	total: 8.58s	remaining: 22.2s
279:	learn: 0.0850158	total: 8.61s	remaining: 22.1s
280:	learn: 0.0849669	total: 8.64s	remaining: 22.1s
281:	learn: 0.0847684	total: 8.67s	remaining: 22.1s
282:	learn: 0.0846669	total: 8.7s	remaining: 22s
283:	learn: 0.0845492	total: 8.74s	remaining: 22s
284:	learn: 0.0844847	total: 8.77s	remaining: 22s
285:	learn: 0.0843285	total: 8.81s	remaining: 22s
286:	learn: 0.0841787	total: 8.85s	remaining: 22s
287:	learn: 0.0840387	total: 8.88s	remaining: 22s
288:	learn: 0.0838289	total: 8.91s	remaining: 21.9s
289:	learn: 0.0836696	total: 8.95s	remaining: 21.9s
290:	learn: 0.0836593	total: 8.98s	remaining: 21.9s
291:	learn: 0.0836256	total: 9.02s	remaining: 21.9s
292:	learn: 0.0834384	total: 9.05s	remaining: 21.8s
293:	learn: 0.0834100	total: 9.08s	remaining: 21.8s
294:	learn: 0.0833364	total: 9.11s	remaining: 21.8s
295:	learn: 0.0832511	total: 9.15s	remaining: 21.8s
296:	learn: 0.0831396	total: 9.18s	remaining: 21.7s
297:	learn: 0.0831269	total: 9.21s	remaining: 21.7s
298:	learn: 0.0829363	total: 9.25s	remaining: 21.7s
299:	learn: 0.0829071	total: 9.28s	remaining: 21.7s
300:	learn: 0.0827658	total: 9.32s	remaining: 21.6s
301:	learn: 0.0827549	total: 9.35s	remaining: 21.6s
302:	learn: 0.0827390	total: 9.39s	remaining: 21.6s
303:	learn: 0.0827323	total: 9.42s	remaining: 21.6s
304:	learn: 0.0826319	total: 9.46s	remaining: 21.6s
305:	learn: 0.0825087	total: 9.51s	remaining: 21.6s
306:	learn: 0.0824046	total: 9.56s	remaining: 21.6s
307:	learn: 0.0823097	total: 9.59s	remaining: 21.5s
308:	learn: 0.0823050	total: 9.62s	remaining: 21.5s
309:	learn: 0.0821993	total: 9.66s	remaining: 21.5s
310:	learn: 0.0820561	total: 9.69s	remaining: 21.5s
311:	learn: 0.0819930	total: 9.72s	remaining: 21.4s
312:	learn: 0.0819403	total: 9.76s	remaining: 21.4s
313:	learn: 0.0818397	total: 9.79s	remaining: 21.4s
314:	learn: 0.0816702	total: 9.82s	remaining: 21.3s
315:	learn: 0.0814729	total: 9.85s	remaining: 21.3s
316:	learn: 0.0813463	total: 9.88s	remaining: 21.3s
317:	learn: 0.0812681	total: 9.91s	remaining: 21.3s
318:	learn: 0.0812310	total: 9.95s	remaining: 21.2s
319:	learn: 0.0811232	total: 9.98s	remaining: 21.2s
320:	learn: 0.0809153	total: 10s	remaining: 21.2s
321:	learn: 0.0808739	total: 10s	remaining: 21.2s
322:	learn: 0.0808643	total: 10.1s	remaining: 21.1s
323:	learn: 0.0808035	total: 10.1s	remaining: 21.1s
324:	learn: 0.0806704	total: 10.1s	remaining: 21.1s
325:	learn: 0.0805901	total: 10.2s	remaining: 21.1s
326:	learn: 0.0804507	total: 10.2s	remaining: 21s
327:	learn: 0.0802442	total: 10.3s	remaining: 21s
328:	learn: 0.0800945	total: 10.3s	remaining: 21s
329:	learn: 0.0799779	total: 10.3s	remaining: 20.9s
330:	learn: 0.0798755	total: 10.3s	remaining: 20.9s
331:	learn: 0.0797960	total: 10.4s	remaining: 20.9s
332:	learn: 0.0796640	total: 10.4s	remaining: 20.8s
333:	learn: 0.0795911	total: 10.4s	remaining: 20.8s
334:	learn: 0.0795053	total: 10.5s	remaining: 20.8s
335:	learn: 0.0794773	total: 10.5s	remaining: 20.7s
336:	learn: 0.0794643	total: 10.5s	remaining: 20.7s
337:	learn: 0.0794441	total: 10.6s	remaining: 20.7s
338:	learn: 0.0793009	total: 10.6s	remaining: 20.6s
339:	learn: 0.0792856	total: 10.6s	remaining: 20.6s
340:	learn: 0.0792644	total: 10.7s	remaining: 20.6s
341:	learn: 0.0791904	total: 10.7s	remaining: 20.6s
342:	learn: 0.0791629	total: 10.7s	remaining: 20.5s
343:	learn: 0.0790842	total: 10.7s	remaining: 20.5s
344:	learn: 0.0789171	total: 10.8s	remaining: 20.4s
345:	learn: 0.0787880	total: 10.8s	remaining: 20.4s
346:	learn: 0.0786917	total: 10.8s	remaining: 20.4s
347:	learn: 0.0785762	total: 10.8s	remaining: 20.3s
348:	learn: 0.0785380	total: 10.9s	remaining: 20.3s
349:	learn: 0.0784609	total: 10.9s	remaining: 20.3s
350:	learn: 0.0784558	total: 10.9s	remaining: 20.2s
351:	learn: 0.0784401	total: 11s	remaining: 20.2s
352:	learn: 0.0784353	total: 11s	remaining: 20.2s
353:	learn: 0.0783623	total: 11s	remaining: 20.2s
354:	learn: 0.0781950	total: 11.1s	remaining: 20.1s
355:	learn: 0.0780791	total: 11.1s	remaining: 20.1s
356:	learn: 0.0780547	total: 11.1s	remaining: 20.1s
357:	learn: 0.0780217	total: 11.2s	remaining: 20s
358:	learn: 0.0779444	total: 11.2s	remaining: 20s
359:	learn: 0.0778739	total: 11.2s	remaining: 20s
360:	learn: 0.0778093	total: 11.3s	remaining: 20s
361:	learn: 0.0776391	total: 11.3s	remaining: 19.9s
362:	learn: 0.0775646	total: 11.3s	remaining: 19.9s
363:	learn: 0.0775307	total: 11.4s	remaining: 19.9s
364:	learn: 0.0773647	total: 11.4s	remaining: 19.8s
365:	learn: 0.0773423	total: 11.5s	remaining: 19.8s
366:	learn: 0.0772007	total: 11.5s	remaining: 19.8s
367:	learn: 0.0770587	total: 11.5s	remaining: 19.8s
368:	learn: 0.0770289	total: 11.6s	remaining: 19.8s
369:	learn: 0.0769326	total: 11.6s	remaining: 19.7s
370:	learn: 0.0769022	total: 11.6s	remaining: 19.7s
371:	learn: 0.0767968	total: 11.7s	remaining: 19.7s
372:	learn: 0.0766804	total: 11.7s	remaining: 19.7s
373:	learn: 0.0765776	total: 11.7s	remaining: 19.7s
374:	learn: 0.0764074	total: 11.8s	remaining: 19.6s
375:	learn: 0.0762918	total: 11.8s	remaining: 19.6s
376:	learn: 0.0762629	total: 11.8s	remaining: 19.6s
377:	learn: 0.0762585	total: 11.9s	remaining: 19.5s
378:	learn: 0.0761221	total: 11.9s	remaining: 19.5s
379:	learn: 0.0759568	total: 11.9s	remaining: 19.5s
380:	learn: 0.0758656	total: 12s	remaining: 19.5s
381:	learn: 0.0757119	total: 12s	remaining: 19.4s
382:	learn: 0.0756209	total: 12s	remaining: 19.4s
383:	learn: 0.0754560	total: 12.1s	remaining: 19.4s
384:	learn: 0.0754126	total: 12.1s	remaining: 19.3s

CV folds:  14%|█▍        | 7/50 [03:40<22:38, 31.59s/fold]

Learning rate set to 0.042738
0:	learn: 0.3877350	total: 25.1ms	remaining: 25.1s
1:	learn: 0.3766451	total: 57.6ms	remaining: 28.8s
2:	learn: 0.3667336	total: 105ms	remaining: 34.8s
3:	learn: 0.3569796	total: 133ms	remaining: 33s
4:	learn: 0.3475508	total: 161ms	remaining: 32s
5:	learn: 0.3385212	total: 209ms	remaining: 34.7s
6:	learn: 0.3298358	total: 261ms	remaining: 37s
7:	learn: 0.3214600	total: 302ms	remaining: 37.4s
8:	learn: 0.3135513	total: 330ms	remaining: 36.4s
9:	learn: 0.3053740	total: 362ms	remaining: 35.8s
10:	learn: 0.2974188	total: 394ms	remaining: 35.4s
11:	learn: 0.2898744	total: 424ms	remaining: 34.9s
12:	learn: 0.2833442	total: 457ms	remaining: 34.7s
13:	learn: 0.2764291	total: 488ms	remaining: 34.4s
14:	learn: 0.2701734	total: 518ms	remaining: 34s
15:	learn: 0.2638477	total: 548ms	remaining: 33.7s
16:	learn: 0.2581808	total: 579ms	remaining: 33.5s
17:	learn: 0.2525963	total: 610ms	remaining: 33.3s
18:	learn: 0.2476827	total: 640ms	remaining: 33.1s
19:	learn: 0.2423431	total: 679ms	remaining: 33.3s
20:	learn: 0.2372939	total: 711ms	remaining: 33.1s
21:	learn: 0.2326129	total: 742ms	remaining: 33s
22:	learn: 0.2280005	total: 774ms	remaining: 32.9s
23:	learn: 0.2234388	total: 802ms	remaining: 32.6s
24:	learn: 0.2190546	total: 830ms	remaining: 32.4s
25:	learn: 0.2147774	total: 858ms	remaining: 32.1s
26:	learn: 0.2112413	total: 888ms	remaining: 32s
27:	learn: 0.2072942	total: 920ms	remaining: 31.9s
28:	learn: 0.2042706	total: 951ms	remaining: 31.8s
29:	learn: 0.2008392	total: 980ms	remaining: 31.7s
30:	learn: 0.1977902	total: 1.01s	remaining: 31.5s
31:	learn: 0.1943638	total: 1.04s	remaining: 31.4s
32:	learn: 0.1915962	total: 1.07s	remaining: 31.3s
33:	learn: 0.1884234	total: 1.1s	remaining: 31.3s
34:	learn: 0.1856158	total: 1.13s	remaining: 31.2s
35:	learn: 0.1829699	total: 1.16s	remaining: 31.1s
36:	learn: 0.1802955	total: 1.2s	remaining: 31.2s
37:	learn: 0.1779793	total: 1.22s	remaining: 30.9s
38:	learn: 0.1757954	total: 1.25s	remaining: 30.7s
39:	learn: 0.1736832	total: 1.27s	remaining: 30.6s
40:	learn: 0.1712948	total: 1.3s	remaining: 30.5s
41:	learn: 0.1690796	total: 1.33s	remaining: 30.4s
42:	learn: 0.1671242	total: 1.36s	remaining: 30.3s
43:	learn: 0.1652104	total: 1.39s	remaining: 30.3s
44:	learn: 0.1630749	total: 1.42s	remaining: 30.2s
45:	learn: 0.1612342	total: 1.45s	remaining: 30.1s
46:	learn: 0.1595049	total: 1.48s	remaining: 30.1s
47:	learn: 0.1577746	total: 1.51s	remaining: 30s
48:	learn: 0.1560310	total: 1.54s	remaining: 29.9s
49:	learn: 0.1544440	total: 1.57s	remaining: 29.8s
50:	learn: 0.1531001	total: 1.6s	remaining: 29.8s
51:	learn: 0.1516528	total: 1.63s	remaining: 29.7s
52:	learn: 0.1501137	total: 1.66s	remaining: 29.7s
53:	learn: 0.1486540	total: 1.69s	remaining: 29.6s
54:	learn: 0.1474431	total: 1.71s	remaining: 29.4s
55:	learn: 0.1462424	total: 1.74s	remaining: 29.3s
56:	learn: 0.1450351	total: 1.77s	remaining: 29.3s
57:	learn: 0.1439104	total: 1.8s	remaining: 29.3s
58:	learn: 0.1429124	total: 1.83s	remaining: 29.3s
59:	learn: 0.1417246	total: 1.86s	remaining: 29.2s
60:	learn: 0.1407059	total: 1.89s	remaining: 29.1s
61:	learn: 0.1395445	total: 1.93s	remaining: 29.2s
62:	learn: 0.1385551	total: 1.97s	remaining: 29.2s
63:	learn: 0.1375060	total: 1.99s	remaining: 29.2s
64:	learn: 0.1365512	total: 2.02s	remaining: 29.1s
65:	learn: 0.1356386	total: 2.05s	remaining: 29.1s
66:	learn: 0.1347835	total: 2.08s	remaining: 29s
67:	learn: 0.1339477	total: 2.11s	remaining: 29s
68:	learn: 0.1330975	total: 2.14s	remaining: 28.9s
69:	learn: 0.1322835	total: 2.17s	remaining: 28.9s
70:	learn: 0.1314994	total: 2.2s	remaining: 28.8s
71:	learn: 0.1307519	total: 2.23s	remaining: 28.7s
72:	learn: 0.1300973	total: 2.26s	remaining: 28.7s
73:	learn: 0.1292973	total: 2.29s	remaining: 28.6s
74:	learn: 0.1284348	total: 2.32s	remaining: 28.6s
75:	learn: 0.1276714	total: 2.35s	remaining: 28.5s
76:	learn: 0.1268708	total: 2.38s	remaining: 28.5s
77:	learn: 0.1262303	total: 2.41s	remaining: 28.5s
78:	learn: 0.1256080	total: 2.44s	remaining: 28.4s
79:	learn: 0.1249388	total: 2.46s	remaining: 28.4s
80:	learn: 0.1244320	total: 2.49s	remaining: 28.3s
81:	learn: 0.1237551	total: 2.52s	remaining: 28.3s
82:	learn: 0.1231350	total: 2.55s	remaining: 28.2s
83:	learn: 0.1225019	total: 2.58s	remaining: 28.2s
84:	learn: 0.1220581	total: 2.61s	remaining: 28.1s
85:	learn: 0.1215036	total: 2.64s	remaining: 28.1s
86:	learn: 0.1209442	total: 2.67s	remaining: 28s
87:	learn: 0.1203398	total: 2.7s	remaining: 28s
88:	learn: 0.1197480	total: 2.73s	remaining: 27.9s
89:	learn: 0.1194250	total: 2.75s	remaining: 27.8s
90:	learn: 0.1188839	total: 2.78s	remaining: 27.8s
91:	learn: 0.1182391	total: 2.81s	remaining: 27.7s
92:	learn: 0.1177976	total: 2.84s	remaining: 27.7s
93:	learn: 0.1173209	total: 2.87s	remaining: 27.6s
94:	learn: 0.1168407	total: 2.9s	remaining: 27.6s
95:	learn: 0.1165431	total: 2.92s	remaining: 27.6s
96:	learn: 0.1160755	total: 2.96s	remaining: 27.5s
97:	learn: 0.1156484	total: 2.98s	remaining: 27.5s
98:	learn: 0.1152897	total: 3.02s	remaining: 27.5s
99:	learn: 0.1150268	total: 3.04s	remaining: 27.4s
100:	learn: 0.1147284	total: 3.07s	remaining: 27.4s
101:	learn: 0.1144823	total: 3.1s	remaining: 27.3s
102:	learn: 0.1141094	total: 3.13s	remaining: 27.3s
103:	learn: 0.1136757	total: 3.16s	remaining: 27.3s
104:	learn: 0.1133308	total: 3.19s	remaining: 27.2s
105:	learn: 0.1130841	total: 3.22s	remaining: 27.2s
106:	learn: 0.1128246	total: 3.25s	remaining: 27.2s
107:	learn: 0.1124596	total: 3.29s	remaining: 27.1s
108:	learn: 0.1121576	total: 3.31s	remaining: 27.1s
109:	learn: 0.1117652	total: 3.35s	remaining: 27.1s
110:	learn: 0.1113923	total: 3.38s	remaining: 27s
111:	learn: 0.1110786	total: 3.4s	remaining: 27s
112:	learn: 0.1107478	total: 3.43s	remaining: 26.9s
113:	learn: 0.1104124	total: 3.46s	remaining: 26.9s
114:	learn: 0.1101048	total: 3.5s	remaining: 26.9s
115:	learn: 0.1098366	total: 3.52s	remaining: 26.8s
116:	learn: 0.1095221	total: 3.55s	remaining: 26.8s
117:	learn: 0.1092078	total: 3.58s	remaining: 26.8s
118:	learn: 0.1090104	total: 3.61s	remaining: 26.7s
119:	learn: 0.1087979	total: 3.65s	remaining: 26.7s
120:	learn: 0.1084673	total: 3.68s	remaining: 26.7s
121:	learn: 0.1081624	total: 3.71s	remaining: 26.7s
122:	learn: 0.1078759	total: 3.74s	remaining: 26.7s
123:	learn: 0.1076719	total: 3.78s	remaining: 26.7s
124:	learn: 0.1073124	total: 3.81s	remaining: 26.6s
125:	learn: 0.1070317	total: 3.83s	remaining: 26.6s
126:	learn: 0.1068609	total: 3.86s	remaining: 26.6s
127:	learn: 0.1066415	total: 3.89s	remaining: 26.5s
128:	learn: 0.1063160	total: 3.92s	remaining: 26.5s
129:	learn: 0.1060870	total: 3.95s	remaining: 26.5s
130:	learn: 0.1058595	total: 3.98s	remaining: 26.4s
131:	learn: 0.1055892	total: 4.01s	remaining: 26.4s
132:	learn: 0.1053479	total: 4.04s	remaining: 26.4s
133:	learn: 0.1050206	total: 4.08s	remaining: 26.4s
134:	learn: 0.1047508	total: 4.12s	remaining: 26.4s
135:	learn: 0.1045082	total: 4.14s	remaining: 26.3s
136:	learn: 0.1042177	total: 4.18s	remaining: 26.3s
137:	learn: 0.1040139	total: 4.22s	remaining: 26.4s
138:	learn: 0.1039446	total: 4.24s	remaining: 26.3s
139:	learn: 0.1037637	total: 4.26s	remaining: 26.2s
140:	learn: 0.1035777	total: 4.29s	remaining: 26.2s
141:	learn: 0.1033537	total: 4.33s	remaining: 26.1s
142:	learn: 0.1030550	total: 4.36s	remaining: 26.1s
143:	learn: 0.1028003	total: 4.38s	remaining: 26.1s
144:	learn: 0.1025060	total: 4.42s	remaining: 26s
145:	learn: 0.1022085	total: 4.45s	remaining: 26s
146:	learn: 0.1020883	total: 4.48s	remaining: 26s
147:	learn: 0.1018615	total: 4.51s	remaining: 26s
148:	learn: 0.1016917	total: 4.54s	remaining: 26s
149:	learn: 0.1015885	total: 4.58s	remaining: 25.9s
150:	learn: 0.1014773	total: 4.61s	remaining: 25.9s
151:	learn: 0.1012763	total: 4.63s	remaining: 25.9s
152:	learn: 0.1011576	total: 4.66s	remaining: 25.8s
153:	learn: 0.1009990	total: 4.69s	remaining: 25.8s
154:	learn: 0.1007652	total: 4.73s	remaining: 25.8s
155:	learn: 0.1005775	total: 4.76s	remaining: 25.8s
156:	learn: 0.1003789	total: 4.79s	remaining: 25.7s
157:	learn: 0.1001963	total: 4.83s	remaining: 25.7s
158:	learn: 0.1000303	total: 4.86s	remaining: 25.7s
159:	learn: 0.0998030	total: 4.89s	remaining: 25.7s
160:	learn: 0.0996401	total: 4.92s	remaining: 25.6s
161:	learn: 0.0994384	total: 4.95s	remaining: 25.6s
162:	learn: 0.0992181	total: 4.98s	remaining: 25.6s
163:	learn: 0.0989894	total: 5.01s	remaining: 25.5s
164:	learn: 0.0986743	total: 5.04s	remaining: 25.5s
165:	learn: 0.0985641	total: 5.07s	remaining: 25.5s
166:	learn: 0.0983375	total: 5.1s	remaining: 25.4s
167:	learn: 0.0981724	total: 5.13s	remaining: 25.4s
168:	learn: 0.0979793	total: 5.17s	remaining: 25.4s
169:	learn: 0.0978578	total: 5.21s	remaining: 25.4s
170:	learn: 0.0976105	total: 5.24s	remaining: 25.4s
171:	learn: 0.0973880	total: 5.28s	remaining: 25.4s
172:	learn: 0.0972775	total: 5.31s	remaining: 25.4s
173:	learn: 0.0969854	total: 5.34s	remaining: 25.3s
174:	learn: 0.0968429	total: 5.37s	remaining: 25.3s
175:	learn: 0.0967381	total: 5.4s	remaining: 25.3s
176:	learn: 0.0966109	total: 5.43s	remaining: 25.3s
177:	learn: 0.0962288	total: 5.46s	remaining: 25.2s
178:	learn: 0.0959755	total: 5.5s	remaining: 25.2s
179:	learn: 0.0956392	total: 5.52s	remaining: 25.2s
180:	learn: 0.0953942	total: 5.55s	remaining: 25.1s
181:	learn: 0.0951885	total: 5.58s	remaining: 25.1s
182:	learn: 0.0950168	total: 5.61s	remaining: 25.1s
183:	learn: 0.0948410	total: 5.64s	remaining: 25s
184:	learn: 0.0946710	total: 5.67s	remaining: 25s
185:	learn: 0.0945183	total: 5.71s	remaining: 25s
186:	learn: 0.0944102	total: 5.74s	remaining: 24.9s
187:	learn: 0.0941954	total: 5.76s	remaining: 24.9s
188:	learn: 0.0941190	total: 5.8s	remaining: 24.9s
189:	learn: 0.0939396	total: 5.83s	remaining: 24.8s
190:	learn: 0.0938826	total: 5.86s	remaining: 24.8s
191:	learn: 0.0937925	total: 5.89s	remaining: 24.8s
192:	learn: 0.0936233	total: 5.92s	remaining: 24.8s
193:	learn: 0.0934739	total: 5.95s	remaining: 24.7s
194:	learn: 0.0932721	total: 5.98s	remaining: 24.7s
195:	learn: 0.0930816	total: 6.01s	remaining: 24.7s
196:	learn: 0.0929703	total: 6.04s	remaining: 24.6s
197:	learn: 0.0927319	total: 6.07s	remaining: 24.6s
198:	learn: 0.0924354	total: 6.11s	remaining: 24.6s
199:	learn: 0.0922388	total: 6.14s	remaining: 24.5s
200:	learn: 0.0921618	total: 6.17s	remaining: 24.5s
201:	learn: 0.0919576	total: 6.2s	remaining: 24.5s
202:	learn: 0.0918682	total: 6.24s	remaining: 24.5s
203:	learn: 0.0916518	total: 6.27s	remaining: 24.5s
204:	learn: 0.0915681	total: 6.3s	remaining: 24.4s
205:	learn: 0.0914035	total: 6.33s	remaining: 24.4s
206:	learn: 0.0912401	total: 6.36s	remaining: 24.4s
207:	learn: 0.0911689	total: 6.39s	remaining: 24.4s
208:	learn: 0.0910343	total: 6.42s	remaining: 24.3s
209:	learn: 0.0908808	total: 6.46s	remaining: 24.3s
210:	learn: 0.0907054	total: 6.49s	remaining: 24.3s
211:	learn: 0.0906583	total: 6.52s	remaining: 24.2s
212:	learn: 0.0905141	total: 6.55s	remaining: 24.2s
213:	learn: 0.0904199	total: 6.58s	remaining: 24.2s
214:	learn: 0.0901977	total: 6.61s	remaining: 24.1s
215:	learn: 0.0900794	total: 6.64s	remaining: 24.1s
216:	learn: 0.0900387	total: 6.67s	remaining: 24.1s
217:	learn: 0.0898940	total: 6.7s	remaining: 24s
218:	learn: 0.0898200	total: 6.73s	remaining: 24s
219:	learn: 0.0897231	total: 6.79s	remaining: 24.1s
220:	learn: 0.0896020	total: 6.82s	remaining: 24s
221:	learn: 0.0895751	total: 6.85s	remaining: 24s
222:	learn: 0.0894741	total: 6.88s	remaining: 24s
223:	learn: 0.0893454	total: 6.91s	remaining: 23.9s
224:	learn: 0.0892848	total: 6.93s	remaining: 23.9s
225:	learn: 0.0891624	total: 6.97s	remaining: 23.9s
226:	learn: 0.0890127	total: 7s	remaining: 23.8s
227:	learn: 0.0889513	total: 7.03s	remaining: 23.8s
228:	learn: 0.0889164	total: 7.06s	remaining: 23.8s
229:	learn: 0.0887637	total: 7.09s	remaining: 23.7s
230:	learn: 0.0886197	total: 7.12s	remaining: 23.7s
231:	learn: 0.0884727	total: 7.15s	remaining: 23.7s
232:	learn: 0.0882417	total: 7.18s	remaining: 23.6s
233:	learn: 0.0881447	total: 7.21s	remaining: 23.6s
234:	learn: 0.0881010	total: 7.24s	remaining: 23.6s
235:	learn: 0.0878576	total: 7.27s	remaining: 23.5s
236:	learn: 0.0878150	total: 7.3s	remaining: 23.5s
237:	learn: 0.0876426	total: 7.33s	remaining: 23.5s
238:	learn: 0.0875218	total: 7.36s	remaining: 23.4s
239:	learn: 0.0874703	total: 7.39s	remaining: 23.4s
240:	learn: 0.0874320	total: 7.42s	remaining: 23.4s
241:	learn: 0.0872596	total: 7.45s	remaining: 23.3s
242:	learn: 0.0872316	total: 7.48s	remaining: 23.3s
243:	learn: 0.0871976	total: 7.51s	remaining: 23.3s
244:	learn: 0.0870242	total: 7.54s	remaining: 23.2s
245:	learn: 0.0868670	total: 7.57s	remaining: 23.2s
246:	learn: 0.0866907	total: 7.61s	remaining: 23.2s
247:	learn: 0.0864942	total: 7.64s	remaining: 23.2s
248:	learn: 0.0864660	total: 7.67s	remaining: 23.1s
249:	learn: 0.0864236	total: 7.7s	remaining: 23.1s
250:	learn: 0.0863127	total: 7.73s	remaining: 23.1s
251:	learn: 0.0862173	total: 7.77s	remaining: 23.1s
252:	learn: 0.0861444	total: 7.8s	remaining: 23s
253:	learn: 0.0860458	total: 7.83s	remaining: 23s
254:	learn: 0.0860083	total: 7.85s	remaining: 22.9s
255:	learn: 0.0859058	total: 7.88s	remaining: 22.9s
256:	learn: 0.0858473	total: 7.91s	remaining: 22.9s
257:	learn: 0.0858118	total: 7.94s	remaining: 22.8s
258:	learn: 0.0857665	total: 7.97s	remaining: 22.8s
259:	learn: 0.0857051	total: 8s	remaining: 22.8s
260:	learn: 0.0856595	total: 8.03s	remaining: 22.7s
261:	learn: 0.0855864	total: 8.06s	remaining: 22.7s
262:	learn: 0.0854556	total: 8.09s	remaining: 22.7s
263:	learn: 0.0853582	total: 8.12s	remaining: 22.6s
264:	learn: 0.0853420	total: 8.15s	remaining: 22.6s
265:	learn: 0.0853120	total: 8.18s	remaining: 22.6s
266:	learn: 0.0852064	total: 8.21s	remaining: 22.5s
267:	learn: 0.0850381	total: 8.24s	remaining: 22.5s
268:	learn: 0.0850020	total: 8.27s	remaining: 22.5s
269:	learn: 0.0849499	total: 8.3s	remaining: 22.5s
270:	learn: 0.0848395	total: 8.34s	remaining: 22.4s
271:	learn: 0.0846541	total: 8.37s	remaining: 22.4s
272:	learn: 0.0845910	total: 8.42s	remaining: 22.4s
273:	learn: 0.0844984	total: 8.45s	remaining: 22.4s
274:	learn: 0.0843852	total: 8.48s	remaining: 22.4s
275:	learn: 0.0843584	total: 8.52s	remaining: 22.4s
276:	learn: 0.0842009	total: 8.55s	remaining: 22.3s
277:	learn: 0.0840875	total: 8.58s	remaining: 22.3s
278:	learn: 0.0840601	total: 8.61s	remaining: 22.3s
279:	learn: 0.0839268	total: 8.64s	remaining: 22.2s
280:	learn: 0.0838961	total: 8.67s	remaining: 22.2s
281:	learn: 0.0838298	total: 8.71s	remaining: 22.2s
282:	learn: 0.0837856	total: 8.74s	remaining: 22.2s
283:	learn: 0.0837705	total: 8.77s	remaining: 22.1s
284:	learn: 0.0837143	total: 8.8s	remaining: 22.1s
285:	learn: 0.0836855	total: 8.83s	remaining: 22.1s
286:	learn: 0.0836392	total: 8.87s	remaining: 22s
287:	learn: 0.0836087	total: 8.9s	remaining: 22s
288:	learn: 0.0835882	total: 8.93s	remaining: 22s
289:	learn: 0.0834411	total: 8.96s	remaining: 21.9s
290:	learn: 0.0832659	total: 8.99s	remaining: 21.9s
291:	learn: 0.0832413	total: 9.02s	remaining: 21.9s
292:	learn: 0.0831986	total: 9.05s	remaining: 21.8s
293:	learn: 0.0830764	total: 9.08s	remaining: 21.8s
294:	learn: 0.0830426	total: 9.11s	remaining: 21.8s
295:	learn: 0.0828918	total: 9.14s	remaining: 21.8s
296:	learn: 0.0828465	total: 9.18s	remaining: 21.7s
297:	learn: 0.0828187	total: 9.21s	remaining: 21.7s
298:	learn: 0.0826614	total: 9.24s	remaining: 21.7s
299:	learn: 0.0825549	total: 9.27s	remaining: 21.6s
300:	learn: 0.0824380	total: 9.3s	remaining: 21.6s
301:	learn: 0.0823152	total: 9.33s	remaining: 21.6s
302:	learn: 0.0822674	total: 9.36s	remaining: 21.5s
303:	learn: 0.0822408	total: 9.4s	remaining: 21.5s
304:	learn: 0.0821312	total: 9.43s	remaining: 21.5s
305:	learn: 0.0820102	total: 9.46s	remaining: 21.5s
306:	learn: 0.0819294	total: 9.49s	remaining: 21.4s
307:	learn: 0.0818255	total: 9.52s	remaining: 21.4s
308:	learn: 0.0816666	total: 9.55s	remaining: 21.4s
309:	learn: 0.0815808	total: 9.58s	remaining: 21.3s
310:	learn: 0.0814006	total: 9.61s	remaining: 21.3s
311:	learn: 0.0813564	total: 9.64s	remaining: 21.3s
312:	learn: 0.0811655	total: 9.67s	remaining: 21.2s
313:	learn: 0.0810777	total: 9.7s	remaining: 21.2s
314:	learn: 0.0809465	total: 9.73s	remaining: 21.2s
315:	learn: 0.0809019	total: 9.76s	remaining: 21.1s
316:	learn: 0.0808734	total: 9.79s	remaining: 21.1s
317:	learn: 0.0807068	total: 9.83s	remaining: 21.1s
318:	learn: 0.0806893	total: 9.86s	remaining: 21s
319:	learn: 0.0806175	total: 9.89s	remaining: 21s
320:	learn: 0.0805174	total: 9.92s	remaining: 21s
321:	learn: 0.0804295	total: 9.95s	remaining: 21s
322:	learn: 0.0803664	total: 9.98s	remaining: 20.9s
323:	learn: 0.0802683	total: 10s	remaining: 20.9s
324:	learn: 0.0801841	total: 10.1s	remaining: 20.9s
325:	learn: 0.0801506	total: 10.1s	remaining: 20.8s
326:	learn: 0.0800556	total: 10.1s	remaining: 20.8s
327:	learn: 0.0800345	total: 10.1s	remaining: 20.8s
328:	learn: 0.0800208	total: 10.2s	remaining: 20.7s
329:	learn: 0.0800001	total: 10.2s	remaining: 20.7s
330:	learn: 0.0799734	total: 10.2s	remaining: 20.7s
331:	learn: 0.0799555	total: 10.3s	remaining: 20.7s
332:	learn: 0.0798615	total: 10.3s	remaining: 20.6s
333:	learn: 0.0797134	total: 10.3s	remaining: 20.6s
334:	learn: 0.0796678	total: 10.4s	remaining: 20.6s
335:	learn: 0.0796539	total: 10.4s	remaining: 20.5s
336:	learn: 0.0795925	total: 10.4s	remaining: 20.5s
337:	learn: 0.0794442	total: 10.5s	remaining: 20.5s
338:	learn: 0.0793234	total: 10.5s	remaining: 20.5s
339:	learn: 0.0792101	total: 10.5s	remaining: 20.4s
340:	learn: 0.0791745	total: 10.6s	remaining: 20.4s
341:	learn: 0.0791019	total: 10.6s	remaining: 20.4s
342:	learn: 0.0790240	total: 10.6s	remaining: 20.3s
343:	learn: 0.0789798	total: 10.6s	remaining: 20.3s
344:	learn: 0.0789311	total: 10.7s	remaining: 20.3s
345:	learn: 0.0788610	total: 10.7s	remaining: 20.3s
346:	learn: 0.0788436	total: 10.7s	remaining: 20.2s
347:	learn: 0.0788207	total: 10.8s	remaining: 20.2s
348:	learn: 0.0786796	total: 10.8s	remaining: 20.2s
349:	learn: 0.0786688	total: 10.8s	remaining: 20.1s
350:	learn: 0.0786565	total: 10.9s	remaining: 20.1s
351:	learn: 0.0786214	total: 10.9s	remaining: 20.1s
352:	learn: 0.0786094	total: 10.9s	remaining: 20s
353:	learn: 0.0785413	total: 11s	remaining: 20s
354:	learn: 0.0785282	total: 11s	remaining: 20s
355:	learn: 0.0784439	total: 11s	remaining: 19.9s
356:	learn: 0.0784067	total: 11s	remaining: 19.9s
357:	learn: 0.0783368	total: 11.1s	remaining: 19.9s
358:	learn: 0.0783211	total: 11.1s	remaining: 19.8s
359:	learn: 0.0782261	total: 11.1s	remaining: 19.8s
360:	learn: 0.0781710	total: 11.2s	remaining: 19.8s
361:	learn: 0.0781277	total: 11.2s	remaining: 19.7s
362:	learn: 0.0780519	total: 11.2s	remaining: 19.7s
363:	learn: 0.0779673	total: 11.3s	remaining: 19.7s
364:	learn: 0.0777694	total: 11.3s	remaining: 19.6s
365:	learn: 0.0776975	total: 11.3s	remaining: 19.6s
366:	learn: 0.0775507	total: 11.3s	remaining: 19.6s
367:	learn: 0.0775236	total: 11.4s	remaining: 19.5s
368:	learn: 0.0774152	total: 11.4s	remaining: 19.5s
369:	learn: 0.0773621	total: 11.4s	remaining: 19.5s
370:	learn: 0.0773496	total: 11.5s	remaining: 19.5s
371:	learn: 0.0772363	total: 11.5s	remaining: 19.4s
372:	learn: 0.0772245	total: 11.5s	remaining: 19.4s
373:	learn: 0.0771184	total: 11.6s	remaining: 19.4s
374:	learn: 0.0770440	total: 11.6s	remaining: 19.3s
375:	learn: 0.0769905	total: 11.6s	remaining: 19.3s
376:	learn: 0.0769348	total: 11.7s	remaining: 19.3s
377:	learn: 0.0768907	total: 11.7s	remaining: 19.2s
378:	learn: 0.0767928	total: 11.7s	remaining: 19.2s
379:	learn: 0.0767273	total: 11.7s	remaining: 19.2s
380:	learn: 0.0766668	total: 11.8s	remaining: 19.1s
381:	learn: 0.0766560	total: 11.8s	remaining: 19.1s
382:	learn: 0.0765601	total: 11.8s	remaining: 19.1s
383:	learn: 0.0763891	total: 11.9s	remaining: 19s
384:	learn: 0.0763130	total: 11.9s	remaining: 19s
385:	learn: 0.0762110	total: 11.9s	remaining: 19s
386:	learn: 0.0760920	total: 12s	remaining: 19s
387:	learn: 0.0758957	total: 12s	remaining: 18.9s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior1st': 2 unseen categories converted to Unseen on transform.

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'HeatingQC': 1 unseen categories converted to Unseen on transform.

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Functional': 1 unseen categories converted to Unseen on transform.

CV folds:  16%|█▌        | 8/50 [04:11<22:03, 31.51s/fold]

Learning rate set to 0.042743
0:	learn: 0.3875194	total: 25.2ms	remaining: 25.2s
1:	learn: 0.3768927	total: 55.4ms	remaining: 27.7s
2:	learn: 0.3663587	total: 88.1ms	remaining: 29.3s
3:	learn: 0.3567867	total: 116ms	remaining: 28.9s
4:	learn: 0.3476866	total: 147ms	remaining: 29.2s
5:	learn: 0.3383215	total: 174ms	remaining: 28.9s
6:	learn: 0.3292701	total: 202ms	remaining: 28.7s
7:	learn: 0.3212381	total: 236ms	remaining: 29.2s
8:	learn: 0.3135465	total: 284ms	remaining: 31.2s
9:	learn: 0.3053239	total: 311ms	remaining: 30.8s
10:	learn: 0.2975988	total: 339ms	remaining: 30.4s
11:	learn: 0.2895972	total: 367ms	remaining: 30.2s
12:	learn: 0.2832325	total: 395ms	remaining: 30s
13:	learn: 0.2764084	total: 425ms	remaining: 29.9s
14:	learn: 0.2700306	total: 457ms	remaining: 30s
15:	learn: 0.2639065	total: 491ms	remaining: 30.2s
16:	learn: 0.2581528	total: 521ms	remaining: 30.1s
17:	learn: 0.2524269	total: 551ms	remaining: 30.1s
18:	learn: 0.2467067	total: 582ms	remaining: 30s
19:	learn: 0.2418899	total: 611ms	remaining: 30s
20:	learn: 0.2370131	total: 639ms	remaining: 29.8s
21:	learn: 0.2328391	total: 670ms	remaining: 29.8s
22:	learn: 0.2283139	total: 703ms	remaining: 29.9s
23:	learn: 0.2239236	total: 736ms	remaining: 29.9s
24:	learn: 0.2200798	total: 768ms	remaining: 30s
25:	learn: 0.2162249	total: 797ms	remaining: 29.9s
26:	learn: 0.2119695	total: 827ms	remaining: 29.8s
27:	learn: 0.2087500	total: 856ms	remaining: 29.7s
28:	learn: 0.2052926	total: 887ms	remaining: 29.7s
29:	learn: 0.2018950	total: 922ms	remaining: 29.8s
30:	learn: 0.1984464	total: 956ms	remaining: 29.9s
31:	learn: 0.1954862	total: 986ms	remaining: 29.8s
32:	learn: 0.1926160	total: 1.01s	remaining: 29.7s
33:	learn: 0.1895849	total: 1.04s	remaining: 29.6s
34:	learn: 0.1864219	total: 1.07s	remaining: 29.6s
35:	learn: 0.1833644	total: 1.1s	remaining: 29.6s
36:	learn: 0.1808665	total: 1.14s	remaining: 29.6s
37:	learn: 0.1785025	total: 1.17s	remaining: 29.6s
38:	learn: 0.1760849	total: 1.2s	remaining: 29.6s
39:	learn: 0.1737474	total: 1.23s	remaining: 29.6s
40:	learn: 0.1716127	total: 1.26s	remaining: 29.4s
41:	learn: 0.1695199	total: 1.29s	remaining: 29.4s
42:	learn: 0.1673757	total: 1.32s	remaining: 29.3s
43:	learn: 0.1653923	total: 1.35s	remaining: 29.3s
44:	learn: 0.1634418	total: 1.37s	remaining: 29.2s
45:	learn: 0.1616100	total: 1.4s	remaining: 29.1s
46:	learn: 0.1596950	total: 1.44s	remaining: 29.1s
47:	learn: 0.1576791	total: 1.47s	remaining: 29.1s
48:	learn: 0.1562758	total: 1.5s	remaining: 29s
49:	learn: 0.1545928	total: 1.53s	remaining: 29.2s
50:	learn: 0.1531164	total: 1.57s	remaining: 29.2s
51:	learn: 0.1515203	total: 1.6s	remaining: 29.1s
52:	learn: 0.1500526	total: 1.63s	remaining: 29.1s
53:	learn: 0.1485415	total: 1.66s	remaining: 29s
54:	learn: 0.1471602	total: 1.69s	remaining: 29s
55:	learn: 0.1460234	total: 1.72s	remaining: 29s
56:	learn: 0.1447617	total: 1.75s	remaining: 28.9s
57:	learn: 0.1434978	total: 1.78s	remaining: 28.9s
58:	learn: 0.1423780	total: 1.81s	remaining: 28.9s
59:	learn: 0.1413449	total: 1.84s	remaining: 28.9s
60:	learn: 0.1403138	total: 1.87s	remaining: 28.8s
61:	learn: 0.1392101	total: 1.9s	remaining: 28.8s
62:	learn: 0.1381808	total: 1.93s	remaining: 28.8s
63:	learn: 0.1372312	total: 1.97s	remaining: 28.8s
64:	learn: 0.1362462	total: 2s	remaining: 28.8s
65:	learn: 0.1355240	total: 2.03s	remaining: 28.8s
66:	learn: 0.1347849	total: 2.06s	remaining: 28.7s
67:	learn: 0.1339057	total: 2.11s	remaining: 28.9s
68:	learn: 0.1330105	total: 2.14s	remaining: 28.8s
69:	learn: 0.1322744	total: 2.17s	remaining: 28.8s
70:	learn: 0.1314651	total: 2.2s	remaining: 28.8s
71:	learn: 0.1306517	total: 2.23s	remaining: 28.7s
72:	learn: 0.1300353	total: 2.26s	remaining: 28.7s
73:	learn: 0.1293997	total: 2.29s	remaining: 28.7s
74:	learn: 0.1287415	total: 2.33s	remaining: 28.7s
75:	learn: 0.1281646	total: 2.36s	remaining: 28.7s
76:	learn: 0.1276826	total: 2.39s	remaining: 28.7s
77:	learn: 0.1270006	total: 2.42s	remaining: 28.6s
78:	learn: 0.1265014	total: 2.46s	remaining: 28.6s
79:	learn: 0.1258692	total: 2.49s	remaining: 28.6s
80:	learn: 0.1253166	total: 2.52s	remaining: 28.6s
81:	learn: 0.1247147	total: 2.55s	remaining: 28.6s
82:	learn: 0.1238645	total: 2.58s	remaining: 28.5s
83:	learn: 0.1232686	total: 2.61s	remaining: 28.5s
84:	learn: 0.1226428	total: 2.65s	remaining: 28.5s
85:	learn: 0.1222942	total: 2.66s	remaining: 28.3s
86:	learn: 0.1216609	total: 2.69s	remaining: 28.3s
87:	learn: 0.1210074	total: 2.72s	remaining: 28.2s
88:	learn: 0.1203841	total: 2.75s	remaining: 28.2s
89:	learn: 0.1198795	total: 2.8s	remaining: 28.3s
90:	learn: 0.1194753	total: 2.83s	remaining: 28.3s
91:	learn: 0.1188365	total: 2.87s	remaining: 28.3s
92:	learn: 0.1184115	total: 2.9s	remaining: 28.2s
93:	learn: 0.1180723	total: 2.92s	remaining: 28.2s
94:	learn: 0.1177011	total: 2.96s	remaining: 28.2s
95:	learn: 0.1172241	total: 2.98s	remaining: 28.1s
96:	learn: 0.1168056	total: 3.01s	remaining: 28s
97:	learn: 0.1164186	total: 3.04s	remaining: 28s
98:	learn: 0.1158636	total: 3.08s	remaining: 28s
99:	learn: 0.1155150	total: 3.11s	remaining: 28s
100:	learn: 0.1152303	total: 3.14s	remaining: 28s
101:	learn: 0.1149163	total: 3.18s	remaining: 28s
102:	learn: 0.1145828	total: 3.21s	remaining: 27.9s
103:	learn: 0.1142332	total: 3.24s	remaining: 27.9s
104:	learn: 0.1139668	total: 3.27s	remaining: 27.9s
105:	learn: 0.1135642	total: 3.3s	remaining: 27.9s
106:	learn: 0.1133192	total: 3.33s	remaining: 27.8s
107:	learn: 0.1129036	total: 3.36s	remaining: 27.8s
108:	learn: 0.1125896	total: 3.41s	remaining: 27.9s
109:	learn: 0.1122574	total: 3.44s	remaining: 27.8s
110:	learn: 0.1120096	total: 3.47s	remaining: 27.8s
111:	learn: 0.1117437	total: 3.49s	remaining: 27.7s
112:	learn: 0.1114827	total: 3.52s	remaining: 27.7s
113:	learn: 0.1111412	total: 3.56s	remaining: 27.6s
114:	learn: 0.1109322	total: 3.59s	remaining: 27.6s
115:	learn: 0.1106996	total: 3.62s	remaining: 27.6s
116:	learn: 0.1103880	total: 3.65s	remaining: 27.6s
117:	learn: 0.1100364	total: 3.68s	remaining: 27.5s
118:	learn: 0.1096819	total: 3.71s	remaining: 27.5s
119:	learn: 0.1094331	total: 3.74s	remaining: 27.4s
120:	learn: 0.1091213	total: 3.77s	remaining: 27.4s
121:	learn: 0.1089940	total: 3.8s	remaining: 27.4s
122:	learn: 0.1087581	total: 3.83s	remaining: 27.3s
123:	learn: 0.1085306	total: 3.87s	remaining: 27.3s
124:	learn: 0.1081882	total: 3.9s	remaining: 27.3s
125:	learn: 0.1080197	total: 3.93s	remaining: 27.2s
126:	learn: 0.1077987	total: 3.96s	remaining: 27.2s
127:	learn: 0.1075552	total: 3.99s	remaining: 27.2s
128:	learn: 0.1074081	total: 4.02s	remaining: 27.1s
129:	learn: 0.1072458	total: 4.05s	remaining: 27.1s
130:	learn: 0.1070207	total: 4.08s	remaining: 27.1s
131:	learn: 0.1067930	total: 4.11s	remaining: 27s
132:	learn: 0.1065258	total: 4.14s	remaining: 27s
133:	learn: 0.1063020	total: 4.17s	remaining: 27s
134:	learn: 0.1060460	total: 4.21s	remaining: 27s
135:	learn: 0.1059329	total: 4.25s	remaining: 27s
136:	learn: 0.1056165	total: 4.27s	remaining: 26.9s
137:	learn: 0.1054488	total: 4.3s	remaining: 26.9s
138:	learn: 0.1052063	total: 4.33s	remaining: 26.9s
139:	learn: 0.1050026	total: 4.36s	remaining: 26.8s
140:	learn: 0.1048592	total: 4.39s	remaining: 26.8s
141:	learn: 0.1047294	total: 4.44s	remaining: 26.8s
142:	learn: 0.1045715	total: 4.47s	remaining: 26.8s
143:	learn: 0.1043678	total: 4.5s	remaining: 26.8s
144:	learn: 0.1042256	total: 4.53s	remaining: 26.7s
145:	learn: 0.1039467	total: 4.56s	remaining: 26.7s
146:	learn: 0.1037911	total: 4.59s	remaining: 26.6s
147:	learn: 0.1036682	total: 4.62s	remaining: 26.6s
148:	learn: 0.1034568	total: 4.65s	remaining: 26.6s
149:	learn: 0.1031523	total: 4.68s	remaining: 26.5s
150:	learn: 0.1030062	total: 4.71s	remaining: 26.5s
151:	learn: 0.1027012	total: 4.74s	remaining: 26.4s
152:	learn: 0.1025824	total: 4.77s	remaining: 26.4s
153:	learn: 0.1023620	total: 4.8s	remaining: 26.4s
154:	learn: 0.1021362	total: 4.83s	remaining: 26.3s
155:	learn: 0.1020423	total: 4.86s	remaining: 26.3s
156:	learn: 0.1019698	total: 4.89s	remaining: 26.3s
157:	learn: 0.1018116	total: 4.92s	remaining: 26.2s
158:	learn: 0.1016708	total: 4.95s	remaining: 26.2s
159:	learn: 0.1015911	total: 4.98s	remaining: 26.2s
160:	learn: 0.1014011	total: 5.01s	remaining: 26.1s
161:	learn: 0.1012601	total: 5.04s	remaining: 26.1s
162:	learn: 0.1010200	total: 5.07s	remaining: 26s
163:	learn: 0.1007680	total: 5.1s	remaining: 26s
164:	learn: 0.1006610	total: 5.13s	remaining: 26s
165:	learn: 0.1005056	total: 5.16s	remaining: 25.9s
166:	learn: 0.1003785	total: 5.19s	remaining: 25.9s
167:	learn: 0.1002407	total: 5.24s	remaining: 25.9s
168:	learn: 0.0999988	total: 5.27s	remaining: 25.9s
169:	learn: 0.0999612	total: 5.28s	remaining: 25.8s
170:	learn: 0.0997444	total: 5.31s	remaining: 25.8s
171:	learn: 0.0996357	total: 5.35s	remaining: 25.7s
172:	learn: 0.0994596	total: 5.38s	remaining: 25.7s
173:	learn: 0.0994017	total: 5.41s	remaining: 25.7s
174:	learn: 0.0992221	total: 5.45s	remaining: 25.7s
175:	learn: 0.0989660	total: 5.48s	remaining: 25.6s
176:	learn: 0.0988215	total: 5.51s	remaining: 25.6s
177:	learn: 0.0986175	total: 5.54s	remaining: 25.6s
178:	learn: 0.0985284	total: 5.57s	remaining: 25.5s
179:	learn: 0.0984293	total: 5.6s	remaining: 25.5s
180:	learn: 0.0982967	total: 5.63s	remaining: 25.5s
181:	learn: 0.0980418	total: 5.66s	remaining: 25.4s
182:	learn: 0.0978577	total: 5.69s	remaining: 25.4s
183:	learn: 0.0976193	total: 5.72s	remaining: 25.4s
184:	learn: 0.0974874	total: 5.75s	remaining: 25.4s
185:	learn: 0.0973951	total: 5.78s	remaining: 25.3s
186:	learn: 0.0973047	total: 5.81s	remaining: 25.3s
187:	learn: 0.0971491	total: 5.84s	remaining: 25.2s
188:	learn: 0.0970097	total: 5.87s	remaining: 25.2s
189:	learn: 0.0968325	total: 5.9s	remaining: 25.2s
190:	learn: 0.0965455	total: 5.93s	remaining: 25.1s
191:	learn: 0.0964279	total: 5.96s	remaining: 25.1s
192:	learn: 0.0963020	total: 6s	remaining: 25.1s
193:	learn: 0.0961655	total: 6.03s	remaining: 25s
194:	learn: 0.0961297	total: 6.06s	remaining: 25s
195:	learn: 0.0960276	total: 6.09s	remaining: 25s
196:	learn: 0.0959906	total: 6.12s	remaining: 24.9s
197:	learn: 0.0957797	total: 6.15s	remaining: 24.9s
198:	learn: 0.0956572	total: 6.18s	remaining: 24.9s
199:	learn: 0.0955552	total: 6.21s	remaining: 24.9s
200:	learn: 0.0953461	total: 6.25s	remaining: 24.8s
201:	learn: 0.0953136	total: 6.28s	remaining: 24.8s
202:	learn: 0.0951864	total: 6.31s	remaining: 24.8s
203:	learn: 0.0949942	total: 6.34s	remaining: 24.7s
204:	learn: 0.0949241	total: 6.37s	remaining: 24.7s
205:	learn: 0.0947699	total: 6.4s	remaining: 24.7s
206:	learn: 0.0946647	total: 6.43s	remaining: 24.6s
207:	learn: 0.0945800	total: 6.46s	remaining: 24.6s
208:	learn: 0.0944348	total: 6.5s	remaining: 24.6s
209:	learn: 0.0941312	total: 6.53s	remaining: 24.5s
210:	learn: 0.0939987	total: 6.55s	remaining: 24.5s
211:	learn: 0.0937939	total: 6.58s	remaining: 24.5s
212:	learn: 0.0935786	total: 6.62s	remaining: 24.4s
213:	learn: 0.0935225	total: 6.65s	remaining: 24.4s
214:	learn: 0.0934006	total: 6.68s	remaining: 24.4s
215:	learn: 0.0932692	total: 6.71s	remaining: 24.4s
216:	learn: 0.0931597	total: 6.74s	remaining: 24.3s
217:	learn: 0.0931180	total: 6.77s	remaining: 24.3s
218:	learn: 0.0929870	total: 6.8s	remaining: 24.2s
219:	learn: 0.0928930	total: 6.83s	remaining: 24.2s
220:	learn: 0.0928647	total: 6.86s	remaining: 24.2s
221:	learn: 0.0926047	total: 6.89s	remaining: 24.1s
222:	learn: 0.0925023	total: 6.92s	remaining: 24.1s
223:	learn: 0.0922775	total: 6.95s	remaining: 24.1s
224:	learn: 0.0920513	total: 6.98s	remaining: 24s
225:	learn: 0.0918900	total: 7.01s	remaining: 24s
226:	learn: 0.0918006	total: 7.04s	remaining: 24s
227:	learn: 0.0917430	total: 7.07s	remaining: 23.9s
228:	learn: 0.0916776	total: 7.1s	remaining: 23.9s
229:	learn: 0.0916169	total: 7.13s	remaining: 23.9s
230:	learn: 0.0915179	total: 7.16s	remaining: 23.9s
231:	learn: 0.0913572	total: 7.2s	remaining: 23.8s
232:	learn: 0.0912668	total: 7.23s	remaining: 23.8s
233:	learn: 0.0911607	total: 7.26s	remaining: 23.8s
234:	learn: 0.0910177	total: 7.29s	remaining: 23.7s
235:	learn: 0.0909664	total: 7.33s	remaining: 23.7s
236:	learn: 0.0908654	total: 7.36s	remaining: 23.7s
237:	learn: 0.0907573	total: 7.4s	remaining: 23.7s
238:	learn: 0.0906251	total: 7.43s	remaining: 23.7s
239:	learn: 0.0904709	total: 7.46s	remaining: 23.6s
240:	learn: 0.0903951	total: 7.49s	remaining: 23.6s
241:	learn: 0.0902390	total: 7.52s	remaining: 23.6s
242:	learn: 0.0900354	total: 7.55s	remaining: 23.5s
243:	learn: 0.0899241	total: 7.58s	remaining: 23.5s
244:	learn: 0.0897033	total: 7.61s	remaining: 23.5s
245:	learn: 0.0896355	total: 7.64s	remaining: 23.4s
246:	learn: 0.0895811	total: 7.67s	remaining: 23.4s
247:	learn: 0.0894610	total: 7.7s	remaining: 23.4s
248:	learn: 0.0893476	total: 7.73s	remaining: 23.3s
249:	learn: 0.0893063	total: 7.76s	remaining: 23.3s
250:	learn: 0.0892716	total: 7.79s	remaining: 23.3s
251:	learn: 0.0892222	total: 7.83s	remaining: 23.2s
252:	learn: 0.0891502	total: 7.87s	remaining: 23.2s
253:	learn: 0.0890766	total: 7.9s	remaining: 23.2s
254:	learn: 0.0889997	total: 7.93s	remaining: 23.2s
255:	learn: 0.0889570	total: 7.96s	remaining: 23.1s
256:	learn: 0.0888930	total: 7.99s	remaining: 23.1s
257:	learn: 0.0888527	total: 8.02s	remaining: 23.1s
258:	learn: 0.0887931	total: 8.05s	remaining: 23s
259:	learn: 0.0886943	total: 8.08s	remaining: 23s
260:	learn: 0.0886073	total: 8.11s	remaining: 23s
261:	learn: 0.0885681	total: 8.14s	remaining: 22.9s
262:	learn: 0.0884110	total: 8.17s	remaining: 22.9s
263:	learn: 0.0883523	total: 8.2s	remaining: 22.9s
264:	learn: 0.0882753	total: 8.23s	remaining: 22.8s
265:	learn: 0.0880973	total: 8.26s	remaining: 22.8s
266:	learn: 0.0880337	total: 8.3s	remaining: 22.8s
267:	learn: 0.0880154	total: 8.33s	remaining: 22.7s
268:	learn: 0.0880087	total: 8.36s	remaining: 22.7s
269:	learn: 0.0878378	total: 8.39s	remaining: 22.7s
270:	learn: 0.0877941	total: 8.42s	remaining: 22.7s
271:	learn: 0.0877599	total: 8.46s	remaining: 22.6s
272:	learn: 0.0877368	total: 8.49s	remaining: 22.6s
273:	learn: 0.0875231	total: 8.52s	remaining: 22.6s
274:	learn: 0.0875109	total: 8.55s	remaining: 22.5s
275:	learn: 0.0875047	total: 8.58s	remaining: 22.5s
276:	learn: 0.0874170	total: 8.61s	remaining: 22.5s
277:	learn: 0.0871872	total: 8.66s	remaining: 22.5s
278:	learn: 0.0870085	total: 8.69s	remaining: 22.5s
279:	learn: 0.0869953	total: 8.72s	remaining: 22.4s
280:	learn: 0.0868730	total: 8.75s	remaining: 22.4s
281:	learn: 0.0867051	total: 8.79s	remaining: 22.4s
282:	learn: 0.0866624	total: 8.82s	remaining: 22.3s
283:	learn: 0.0866147	total: 8.85s	remaining: 22.3s
284:	learn: 0.0864417	total: 8.88s	remaining: 22.3s
285:	learn: 0.0864324	total: 8.91s	remaining: 22.3s
286:	learn: 0.0864012	total: 8.94s	remaining: 22.2s
287:	learn: 0.0863837	total: 8.98s	remaining: 22.2s
288:	learn: 0.0863461	total: 9.01s	remaining: 22.2s
289:	learn: 0.0862774	total: 9.04s	remaining: 22.1s
290:	learn: 0.0862180	total: 9.07s	remaining: 22.1s
291:	learn: 0.0861947	total: 9.1s	remaining: 22.1s
292:	learn: 0.0861218	total: 9.13s	remaining: 22s
293:	learn: 0.0860652	total: 9.16s	remaining: 22s
294:	learn: 0.0860486	total: 9.19s	remaining: 22s
295:	learn: 0.0860255	total: 9.22s	remaining: 21.9s
296:	learn: 0.0859626	total: 9.26s	remaining: 21.9s
297:	learn: 0.0858543	total: 9.28s	remaining: 21.9s
298:	learn: 0.0857402	total: 9.31s	remaining: 21.8s
299:	learn: 0.0856755	total: 9.35s	remaining: 21.8s
300:	learn: 0.0856537	total: 9.38s	remaining: 21.8s
301:	learn: 0.0855944	total: 9.41s	remaining: 21.8s
302:	learn: 0.0855519	total: 9.44s	remaining: 21.7s
303:	learn: 0.0854315	total: 9.47s	remaining: 21.7s
304:	learn: 0.0853967	total: 9.51s	remaining: 21.7s
305:	learn: 0.0852758	total: 9.56s	remaining: 21.7s
306:	learn: 0.0852314	total: 9.59s	remaining: 21.6s
307:	learn: 0.0851615	total: 9.62s	remaining: 21.6s
308:	learn: 0.0850533	total: 9.65s	remaining: 21.6s
309:	learn: 0.0849108	total: 9.68s	remaining: 21.5s
310:	learn: 0.0849016	total: 9.71s	remaining: 21.5s
311:	learn: 0.0848056	total: 9.74s	remaining: 21.5s
312:	learn: 0.0846970	total: 9.78s	remaining: 21.5s
313:	learn: 0.0845933	total: 9.8s	remaining: 21.4s
314:	learn: 0.0845294	total: 9.84s	remaining: 21.4s
315:	learn: 0.0844756	total: 9.87s	remaining: 21.4s
316:	learn: 0.0844689	total: 9.9s	remaining: 21.3s
317:	learn: 0.0843382	total: 9.93s	remaining: 21.3s
318:	learn: 0.0843051	total: 9.96s	remaining: 21.3s
319:	learn: 0.0842495	total: 9.99s	remaining: 21.2s
320:	learn: 0.0841299	total: 10s	remaining: 21.2s
321:	learn: 0.0840177	total: 10.1s	remaining: 21.2s
322:	learn: 0.0840041	total: 10.1s	remaining: 21.1s
323:	learn: 0.0839657	total: 10.1s	remaining: 21.1s
324:	learn: 0.0839196	total: 10.1s	remaining: 21.1s
325:	learn: 0.0837341	total: 10.2s	remaining: 21s
326:	learn: 0.0836824	total: 10.2s	remaining: 21s
327:	learn: 0.0836131	total: 10.2s	remaining: 21s
328:	learn: 0.0835047	total: 10.3s	remaining: 20.9s
329:	learn: 0.0834883	total: 10.3s	remaining: 20.9s
330:	learn: 0.0834403	total: 10.3s	remaining: 20.9s
331:	learn: 0.0834343	total: 10.4s	remaining: 20.8s
332:	learn: 0.0834193	total: 10.4s	remaining: 20.8s
333:	learn: 0.0833964	total: 10.4s	remaining: 20.8s
334:	learn: 0.0833768	total: 10.5s	remaining: 20.8s
335:	learn: 0.0831918	total: 10.5s	remaining: 20.7s
336:	learn: 0.0831805	total: 10.5s	remaining: 20.7s
337:	learn: 0.0831710	total: 10.5s	remaining: 20.7s
338:	learn: 0.0830451	total: 10.6s	remaining: 20.6s
339:	learn: 0.0829074	total: 10.6s	remaining: 20.6s
340:	learn: 0.0827376	total: 10.6s	remaining: 20.5s
341:	learn: 0.0826338	total: 10.7s	remaining: 20.5s
342:	learn: 0.0825213	total: 10.7s	remaining: 20.5s
343:	learn: 0.0824938	total: 10.7s	remaining: 20.4s
344:	learn: 0.0823961	total: 10.8s	remaining: 20.4s
345:	learn: 0.0822936	total: 10.8s	remaining: 20.4s
346:	learn: 0.0821538	total: 10.8s	remaining: 20.4s
347:	learn: 0.0821012	total: 10.8s	remaining: 20.3s
348:	learn: 0.0819458	total: 10.9s	remaining: 20.3s
349:	learn: 0.0819084	total: 10.9s	remaining: 20.2s
350:	learn: 0.0817973	total: 10.9s	remaining: 20.2s
351:	learn: 0.0817350	total: 11s	remaining: 20.2s
352:	learn: 0.0817214	total: 11s	remaining: 20.2s
353:	learn: 0.0816843	total: 11s	remaining: 20.1s
354:	learn: 0.0815899	total: 11.1s	remaining: 20.1s
355:	learn: 0.0814546	total: 11.1s	remaining: 20.1s
356:	learn: 0.0813154	total: 11.1s	remaining: 20s
357:	learn: 0.0812106	total: 11.1s	remaining: 20s
358:	learn: 0.0811257	total: 11.2s	remaining: 19.9s
359:	learn: 0.0810664	total: 11.2s	remaining: 19.9s
360:	learn: 0.0810092	total: 11.2s	remaining: 19.9s
361:	learn: 0.0809316	total: 11.3s	remaining: 19.9s
362:	learn: 0.0808702	total: 11.3s	remaining: 19.8s
363:	learn: 0.0808361	total: 11.3s	remaining: 19.8s
364:	learn: 0.0807619	total: 11.4s	remaining: 19.8s
365:	learn: 0.0805670	total: 11.4s	remaining: 19.7s
366:	learn: 0.0805043	total: 11.4s	remaining: 19.7s
367:	learn: 0.0804991	total: 11.4s	remaining: 19.7s
368:	learn: 0.0804807	total: 11.5s	remaining: 19.6s
369:	learn: 0.0803771	total: 11.5s	remaining: 19.6s
370:	learn: 0.0802601	total: 11.5s	remaining: 19.6s
371:	learn: 0.0801779	total: 11.6s	remaining: 19.5s
372:	learn: 0.0799682	total: 11.6s	remaining: 19.5s
373:	learn: 0.0799117	total: 11.6s	remaining: 19.5s
374:	learn: 0.0798282	total: 11.7s	remaining: 19.4s
375:	learn: 0.0796731	total: 11.7s	remaining: 19.4s
376:	learn: 0.0795502	total: 11.7s	remaining: 19.4s
377:	learn: 0.0794061	total: 11.8s	remaining: 19.4s
378:	learn: 0.0793272	total: 11.8s	remaining: 19.3s
379:	learn: 0.0792773	total: 11.8s	remaining: 19.3s
380:	learn: 0.0790948	total: 11.9s	remaining: 19.3s
381:	learn: 0.0790906	total: 11.9s	remaining: 19.2s
382:	learn: 0.0790846	total: 11.9s	remaining: 19.2s
383:	learn: 0.0790478	total: 12s	remaining: 19.2s
384:	learn: 0.0790343	total: 12s	remaining: 19.1s
385:	learn: 0.0788901	total: 12s	remaining: 19.1s
386:	learn: 0.0788408	total: 12s	remaining: 19.1s
387:	learn: 0.0788013	total: 12.1s	remaining: 19s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior2nd': 1 unseen categories converted to Unseen on transform.

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'MiscFeature': 1 unseen categories converted to Unseen on transform.

CV folds:  18%|█▊        | 9/50 [04:43<21:32, 31.53s/fold]

Learning rate set to 0.042743
0:	learn: 0.3881160	total: 25ms	remaining: 25s
1:	learn: 0.3777069	total: 54.1ms	remaining: 27s
2:	learn: 0.3675025	total: 85.2ms	remaining: 28.3s
3:	learn: 0.3577198	total: 113ms	remaining: 28.2s
4:	learn: 0.3480339	total: 145ms	remaining: 28.8s
5:	learn: 0.3396906	total: 174ms	remaining: 28.8s
6:	learn: 0.3303161	total: 204ms	remaining: 28.9s
7:	learn: 0.3228061	total: 238ms	remaining: 29.6s
8:	learn: 0.3144618	total: 270ms	remaining: 29.7s
9:	learn: 0.3070263	total: 302ms	remaining: 29.9s
10:	learn: 0.3002651	total: 332ms	remaining: 29.9s
11:	learn: 0.2931900	total: 363ms	remaining: 29.9s
12:	learn: 0.2863803	total: 392ms	remaining: 29.8s
13:	learn: 0.2802717	total: 422ms	remaining: 29.7s
14:	learn: 0.2731964	total: 459ms	remaining: 30.1s
15:	learn: 0.2668950	total: 488ms	remaining: 30s
16:	learn: 0.2610822	total: 520ms	remaining: 30.1s
17:	learn: 0.2554568	total: 550ms	remaining: 30s
18:	learn: 0.2500355	total: 580ms	remaining: 29.9s
19:	learn: 0.2448698	total: 609ms	remaining: 29.8s
20:	learn: 0.2399712	total: 641ms	remaining: 29.9s
21:	learn: 0.2353785	total: 674ms	remaining: 30s
22:	learn: 0.2304848	total: 707ms	remaining: 30s
23:	learn: 0.2258765	total: 735ms	remaining: 29.9s
24:	learn: 0.2214435	total: 766ms	remaining: 29.9s
25:	learn: 0.2171239	total: 795ms	remaining: 29.8s
26:	learn: 0.2130050	total: 825ms	remaining: 29.7s
27:	learn: 0.2092598	total: 856ms	remaining: 29.7s
28:	learn: 0.2055170	total: 888ms	remaining: 29.7s
29:	learn: 0.2018591	total: 921ms	remaining: 29.8s
30:	learn: 0.1984553	total: 954ms	remaining: 29.8s
31:	learn: 0.1952158	total: 983ms	remaining: 29.7s
32:	learn: 0.1918158	total: 1.01s	remaining: 29.7s
33:	learn: 0.1891918	total: 1.04s	remaining: 29.7s
34:	learn: 0.1861900	total: 1.07s	remaining: 29.6s
35:	learn: 0.1834042	total: 1.11s	remaining: 29.6s
36:	learn: 0.1808326	total: 1.14s	remaining: 29.7s
37:	learn: 0.1780737	total: 1.17s	remaining: 29.6s
38:	learn: 0.1755960	total: 1.2s	remaining: 29.6s
39:	learn: 0.1731126	total: 1.23s	remaining: 29.5s
40:	learn: 0.1708469	total: 1.26s	remaining: 29.4s
41:	learn: 0.1686654	total: 1.29s	remaining: 29.4s
42:	learn: 0.1665831	total: 1.32s	remaining: 29.4s
43:	learn: 0.1645705	total: 1.35s	remaining: 29.3s
44:	learn: 0.1625829	total: 1.38s	remaining: 29.2s
45:	learn: 0.1608843	total: 1.41s	remaining: 29.1s
46:	learn: 0.1592819	total: 1.43s	remaining: 29.1s
47:	learn: 0.1575950	total: 1.46s	remaining: 29s
48:	learn: 0.1559037	total: 1.5s	remaining: 29s
49:	learn: 0.1542703	total: 1.52s	remaining: 29s
50:	learn: 0.1526132	total: 1.55s	remaining: 28.9s
51:	learn: 0.1511898	total: 1.59s	remaining: 28.9s
52:	learn: 0.1497489	total: 1.62s	remaining: 28.9s
53:	learn: 0.1486772	total: 1.64s	remaining: 28.7s
54:	learn: 0.1474123	total: 1.67s	remaining: 28.6s
55:	learn: 0.1461916	total: 1.7s	remaining: 28.6s
56:	learn: 0.1450878	total: 1.73s	remaining: 28.6s
57:	learn: 0.1438104	total: 1.76s	remaining: 28.6s
58:	learn: 0.1424363	total: 1.79s	remaining: 28.5s
59:	learn: 0.1410952	total: 1.82s	remaining: 28.5s
60:	learn: 0.1399507	total: 1.85s	remaining: 28.5s
61:	learn: 0.1389234	total: 1.89s	remaining: 28.5s
62:	learn: 0.1378486	total: 1.92s	remaining: 28.5s
63:	learn: 0.1367323	total: 1.95s	remaining: 28.4s
64:	learn: 0.1356929	total: 1.97s	remaining: 28.4s
65:	learn: 0.1346987	total: 2s	remaining: 28.4s
66:	learn: 0.1339195	total: 2.03s	remaining: 28.3s
67:	learn: 0.1329551	total: 2.06s	remaining: 28.3s
68:	learn: 0.1323131	total: 2.09s	remaining: 28.2s
69:	learn: 0.1315526	total: 2.12s	remaining: 28.2s
70:	learn: 0.1304905	total: 2.15s	remaining: 28.1s
71:	learn: 0.1297116	total: 2.18s	remaining: 28.1s
72:	learn: 0.1289535	total: 2.21s	remaining: 28.1s
73:	learn: 0.1282229	total: 2.26s	remaining: 28.3s
74:	learn: 0.1274325	total: 2.3s	remaining: 28.4s
75:	learn: 0.1267814	total: 2.34s	remaining: 28.4s
76:	learn: 0.1262053	total: 2.37s	remaining: 28.4s
77:	learn: 0.1255518	total: 2.4s	remaining: 28.4s
78:	learn: 0.1248791	total: 2.43s	remaining: 28.3s
79:	learn: 0.1243459	total: 2.46s	remaining: 28.3s
80:	learn: 0.1237579	total: 2.49s	remaining: 28.2s
81:	learn: 0.1231256	total: 2.52s	remaining: 28.2s
82:	learn: 0.1226861	total: 2.55s	remaining: 28.1s
83:	learn: 0.1222421	total: 2.58s	remaining: 28.1s
84:	learn: 0.1215753	total: 2.61s	remaining: 28.1s
85:	learn: 0.1207336	total: 2.64s	remaining: 28s
86:	learn: 0.1201007	total: 2.67s	remaining: 28s
87:	learn: 0.1196045	total: 2.7s	remaining: 28s
88:	learn: 0.1192393	total: 2.72s	remaining: 27.8s
89:	learn: 0.1187804	total: 2.75s	remaining: 27.8s
90:	learn: 0.1182429	total: 2.77s	remaining: 27.7s
91:	learn: 0.1176033	total: 2.8s	remaining: 27.7s
92:	learn: 0.1172266	total: 2.83s	remaining: 27.6s
93:	learn: 0.1167287	total: 2.87s	remaining: 27.6s
94:	learn: 0.1162176	total: 2.9s	remaining: 27.6s
95:	learn: 0.1156727	total: 2.93s	remaining: 27.6s
96:	learn: 0.1153433	total: 2.96s	remaining: 27.5s
97:	learn: 0.1148553	total: 2.99s	remaining: 27.5s
98:	learn: 0.1143107	total: 3.02s	remaining: 27.5s
99:	learn: 0.1138068	total: 3.05s	remaining: 27.4s
100:	learn: 0.1134018	total: 3.08s	remaining: 27.4s
101:	learn: 0.1130617	total: 3.11s	remaining: 27.4s
102:	learn: 0.1127241	total: 3.15s	remaining: 27.4s
103:	learn: 0.1123400	total: 3.18s	remaining: 27.4s
104:	learn: 0.1120071	total: 3.21s	remaining: 27.4s
105:	learn: 0.1116670	total: 3.24s	remaining: 27.3s
106:	learn: 0.1112905	total: 3.27s	remaining: 27.3s
107:	learn: 0.1108851	total: 3.3s	remaining: 27.3s
108:	learn: 0.1105789	total: 3.33s	remaining: 27.3s
109:	learn: 0.1103054	total: 3.36s	remaining: 27.2s
110:	learn: 0.1100044	total: 3.39s	remaining: 27.2s
111:	learn: 0.1096226	total: 3.42s	remaining: 27.1s
112:	learn: 0.1092462	total: 3.44s	remaining: 27s
113:	learn: 0.1088881	total: 3.48s	remaining: 27s
114:	learn: 0.1086571	total: 3.5s	remaining: 27s
115:	learn: 0.1083310	total: 3.53s	remaining: 26.9s
116:	learn: 0.1080091	total: 3.56s	remaining: 26.9s
117:	learn: 0.1075893	total: 3.59s	remaining: 26.9s
118:	learn: 0.1073542	total: 3.62s	remaining: 26.8s
119:	learn: 0.1070612	total: 3.65s	remaining: 26.8s
120:	learn: 0.1067518	total: 3.68s	remaining: 26.8s
121:	learn: 0.1065750	total: 3.71s	remaining: 26.7s
122:	learn: 0.1063565	total: 3.74s	remaining: 26.7s
123:	learn: 0.1061536	total: 3.77s	remaining: 26.6s
124:	learn: 0.1058229	total: 3.8s	remaining: 26.6s
125:	learn: 0.1056410	total: 3.83s	remaining: 26.6s
126:	learn: 0.1053639	total: 3.86s	remaining: 26.5s
127:	learn: 0.1051946	total: 3.89s	remaining: 26.5s
128:	learn: 0.1049537	total: 3.92s	remaining: 26.5s
129:	learn: 0.1047138	total: 3.95s	remaining: 26.4s
130:	learn: 0.1044460	total: 3.98s	remaining: 26.4s
131:	learn: 0.1042968	total: 4.03s	remaining: 26.5s
132:	learn: 0.1040485	total: 4.06s	remaining: 26.5s
133:	learn: 0.1037045	total: 4.09s	remaining: 26.5s
134:	learn: 0.1034705	total: 4.12s	remaining: 26.4s
135:	learn: 0.1032445	total: 4.16s	remaining: 26.4s
136:	learn: 0.1029661	total: 4.21s	remaining: 26.5s
137:	learn: 0.1026264	total: 4.24s	remaining: 26.5s
138:	learn: 0.1024260	total: 4.27s	remaining: 26.5s
139:	learn: 0.1022226	total: 4.3s	remaining: 26.4s
140:	learn: 0.1020597	total: 4.33s	remaining: 26.4s
141:	learn: 0.1018239	total: 4.36s	remaining: 26.4s
142:	learn: 0.1015805	total: 4.39s	remaining: 26.3s
143:	learn: 0.1014181	total: 4.42s	remaining: 26.3s
144:	learn: 0.1012725	total: 4.45s	remaining: 26.3s
145:	learn: 0.1010632	total: 4.48s	remaining: 26.2s
146:	learn: 0.1008184	total: 4.51s	remaining: 26.2s
147:	learn: 0.1005560	total: 4.54s	remaining: 26.1s
148:	learn: 0.1003462	total: 4.57s	remaining: 26.1s
149:	learn: 0.1001874	total: 4.6s	remaining: 26.1s
150:	learn: 0.1000722	total: 4.63s	remaining: 26s
151:	learn: 0.0999237	total: 4.66s	remaining: 26s
152:	learn: 0.0996931	total: 4.69s	remaining: 26s
153:	learn: 0.0994461	total: 4.72s	remaining: 25.9s
154:	learn: 0.0992881	total: 4.75s	remaining: 25.9s
155:	learn: 0.0991550	total: 4.78s	remaining: 25.9s
156:	learn: 0.0989914	total: 4.81s	remaining: 25.8s
157:	learn: 0.0988486	total: 4.84s	remaining: 25.8s
158:	learn: 0.0986977	total: 4.87s	remaining: 25.8s
159:	learn: 0.0985435	total: 4.91s	remaining: 25.8s
160:	learn: 0.0984120	total: 4.93s	remaining: 25.7s
161:	learn: 0.0981171	total: 4.96s	remaining: 25.7s
162:	learn: 0.0977968	total: 4.99s	remaining: 25.6s
163:	learn: 0.0976984	total: 5.02s	remaining: 25.6s
164:	learn: 0.0975747	total: 5.05s	remaining: 25.6s
165:	learn: 0.0974650	total: 5.08s	remaining: 25.5s
166:	learn: 0.0972142	total: 5.11s	remaining: 25.5s
167:	learn: 0.0969212	total: 5.14s	remaining: 25.5s
168:	learn: 0.0967577	total: 5.17s	remaining: 25.4s
169:	learn: 0.0966751	total: 5.2s	remaining: 25.4s
170:	learn: 0.0964926	total: 5.23s	remaining: 25.4s
171:	learn: 0.0963214	total: 5.26s	remaining: 25.3s
172:	learn: 0.0962434	total: 5.29s	remaining: 25.3s
173:	learn: 0.0960111	total: 5.32s	remaining: 25.3s
174:	learn: 0.0958442	total: 5.35s	remaining: 25.2s
175:	learn: 0.0956877	total: 5.38s	remaining: 25.2s
176:	learn: 0.0955419	total: 5.41s	remaining: 25.2s
177:	learn: 0.0953443	total: 5.44s	remaining: 25.1s
178:	learn: 0.0952098	total: 5.47s	remaining: 25.1s
179:	learn: 0.0950171	total: 5.5s	remaining: 25.1s
180:	learn: 0.0948594	total: 5.53s	remaining: 25s
181:	learn: 0.0947932	total: 5.56s	remaining: 25s
182:	learn: 0.0945181	total: 5.6s	remaining: 25s
183:	learn: 0.0943785	total: 5.63s	remaining: 24.9s
184:	learn: 0.0942130	total: 5.66s	remaining: 24.9s
185:	learn: 0.0941846	total: 5.69s	remaining: 24.9s
186:	learn: 0.0939893	total: 5.72s	remaining: 24.9s
187:	learn: 0.0938823	total: 5.75s	remaining: 24.8s
188:	learn: 0.0937813	total: 5.78s	remaining: 24.8s
189:	learn: 0.0935388	total: 5.81s	remaining: 24.8s
190:	learn: 0.0934743	total: 5.84s	remaining: 24.7s
191:	learn: 0.0933876	total: 5.87s	remaining: 24.7s
192:	learn: 0.0932259	total: 5.91s	remaining: 24.7s
193:	learn: 0.0930966	total: 5.93s	remaining: 24.7s
194:	learn: 0.0928996	total: 5.97s	remaining: 24.6s
195:	learn: 0.0926515	total: 6s	remaining: 24.6s
196:	learn: 0.0924926	total: 6.03s	remaining: 24.6s
197:	learn: 0.0922833	total: 6.06s	remaining: 24.5s
198:	learn: 0.0921373	total: 6.08s	remaining: 24.5s
199:	learn: 0.0920884	total: 6.12s	remaining: 24.5s
200:	learn: 0.0919004	total: 6.14s	remaining: 24.4s
201:	learn: 0.0917806	total: 6.18s	remaining: 24.4s
202:	learn: 0.0916396	total: 6.21s	remaining: 24.4s
203:	learn: 0.0915307	total: 6.25s	remaining: 24.4s
204:	learn: 0.0914663	total: 6.28s	remaining: 24.3s
205:	learn: 0.0913797	total: 6.31s	remaining: 24.3s
206:	learn: 0.0912320	total: 6.34s	remaining: 24.3s
207:	learn: 0.0911803	total: 6.37s	remaining: 24.3s
208:	learn: 0.0911011	total: 6.4s	remaining: 24.2s
209:	learn: 0.0909386	total: 6.43s	remaining: 24.2s
210:	learn: 0.0908092	total: 6.46s	remaining: 24.2s
211:	learn: 0.0906717	total: 6.49s	remaining: 24.1s
212:	learn: 0.0905970	total: 6.52s	remaining: 24.1s
213:	learn: 0.0904893	total: 6.56s	remaining: 24.1s
214:	learn: 0.0903721	total: 6.58s	remaining: 24s
215:	learn: 0.0903203	total: 6.62s	remaining: 24s
216:	learn: 0.0902871	total: 6.64s	remaining: 24s
217:	learn: 0.0901559	total: 6.67s	remaining: 23.9s
218:	learn: 0.0899323	total: 6.71s	remaining: 23.9s
219:	learn: 0.0898693	total: 6.74s	remaining: 23.9s
220:	learn: 0.0897745	total: 6.77s	remaining: 23.9s
221:	learn: 0.0896760	total: 6.8s	remaining: 23.8s
222:	learn: 0.0895488	total: 6.83s	remaining: 23.8s
223:	learn: 0.0894426	total: 6.86s	remaining: 23.8s
224:	learn: 0.0892979	total: 6.89s	remaining: 23.7s
225:	learn: 0.0891432	total: 6.92s	remaining: 23.7s
226:	learn: 0.0889931	total: 6.95s	remaining: 23.7s
227:	learn: 0.0889046	total: 6.98s	remaining: 23.6s
228:	learn: 0.0888526	total: 7.01s	remaining: 23.6s
229:	learn: 0.0887509	total: 7.04s	remaining: 23.6s
230:	learn: 0.0887230	total: 7.07s	remaining: 23.5s
231:	learn: 0.0887100	total: 7.1s	remaining: 23.5s
232:	learn: 0.0886100	total: 7.13s	remaining: 23.5s
233:	learn: 0.0885132	total: 7.16s	remaining: 23.5s
234:	learn: 0.0884350	total: 7.19s	remaining: 23.4s
235:	learn: 0.0883706	total: 7.22s	remaining: 23.4s
236:	learn: 0.0883139	total: 7.25s	remaining: 23.4s
237:	learn: 0.0881586	total: 7.28s	remaining: 23.3s
238:	learn: 0.0880604	total: 7.31s	remaining: 23.3s
239:	learn: 0.0880467	total: 7.34s	remaining: 23.3s
240:	learn: 0.0878886	total: 7.37s	remaining: 23.2s
241:	learn: 0.0877334	total: 7.4s	remaining: 23.2s
242:	learn: 0.0876501	total: 7.43s	remaining: 23.1s
243:	learn: 0.0876279	total: 7.46s	remaining: 23.1s
244:	learn: 0.0875056	total: 7.49s	remaining: 23.1s
245:	learn: 0.0874053	total: 7.52s	remaining: 23.1s
246:	learn: 0.0872202	total: 7.55s	remaining: 23s
247:	learn: 0.0871579	total: 7.58s	remaining: 23s
248:	learn: 0.0870890	total: 7.62s	remaining: 23s
249:	learn: 0.0870435	total: 7.65s	remaining: 22.9s
250:	learn: 0.0869119	total: 7.68s	remaining: 22.9s
251:	learn: 0.0867564	total: 7.71s	remaining: 22.9s
252:	learn: 0.0865861	total: 7.74s	remaining: 22.8s
253:	learn: 0.0865257	total: 7.77s	remaining: 22.8s
254:	learn: 0.0864408	total: 7.8s	remaining: 22.8s
255:	learn: 0.0863676	total: 7.83s	remaining: 22.8s
256:	learn: 0.0863268	total: 7.86s	remaining: 22.7s
257:	learn: 0.0861849	total: 7.89s	remaining: 22.7s
258:	learn: 0.0859929	total: 7.92s	remaining: 22.7s
259:	learn: 0.0858766	total: 7.95s	remaining: 22.6s
260:	learn: 0.0857948	total: 7.98s	remaining: 22.6s
261:	learn: 0.0856754	total: 8.01s	remaining: 22.6s
262:	learn: 0.0855366	total: 8.04s	remaining: 22.5s
263:	learn: 0.0854620	total: 8.07s	remaining: 22.5s
264:	learn: 0.0853584	total: 8.1s	remaining: 22.5s
265:	learn: 0.0851602	total: 8.13s	remaining: 22.4s
266:	learn: 0.0850079	total: 8.16s	remaining: 22.4s
267:	learn: 0.0849146	total: 8.19s	remaining: 22.4s
268:	learn: 0.0847761	total: 8.22s	remaining: 22.3s
269:	learn: 0.0846902	total: 8.25s	remaining: 22.3s
270:	learn: 0.0845470	total: 8.28s	remaining: 22.3s
271:	learn: 0.0845077	total: 8.32s	remaining: 22.3s
272:	learn: 0.0842799	total: 8.35s	remaining: 22.2s
273:	learn: 0.0842432	total: 8.38s	remaining: 22.2s
274:	learn: 0.0841193	total: 8.41s	remaining: 22.2s
275:	learn: 0.0840470	total: 8.45s	remaining: 22.2s
276:	learn: 0.0840103	total: 8.48s	remaining: 22.1s
277:	learn: 0.0837852	total: 8.51s	remaining: 22.1s
278:	learn: 0.0836999	total: 8.54s	remaining: 22.1s
279:	learn: 0.0836633	total: 8.56s	remaining: 22s
280:	learn: 0.0834970	total: 8.6s	remaining: 22s
281:	learn: 0.0833616	total: 8.63s	remaining: 22s
282:	learn: 0.0831871	total: 8.66s	remaining: 21.9s
283:	learn: 0.0829560	total: 8.7s	remaining: 21.9s
284:	learn: 0.0828643	total: 8.74s	remaining: 21.9s
285:	learn: 0.0827296	total: 8.77s	remaining: 21.9s
286:	learn: 0.0826171	total: 8.8s	remaining: 21.9s
287:	learn: 0.0825299	total: 8.83s	remaining: 21.8s
288:	learn: 0.0824452	total: 8.86s	remaining: 21.8s
289:	learn: 0.0824164	total: 8.89s	remaining: 21.8s
290:	learn: 0.0822543	total: 8.92s	remaining: 21.7s
291:	learn: 0.0821816	total: 8.95s	remaining: 21.7s
292:	learn: 0.0820293	total: 8.98s	remaining: 21.7s
293:	learn: 0.0819596	total: 9.01s	remaining: 21.6s
294:	learn: 0.0818845	total: 9.04s	remaining: 21.6s
295:	learn: 0.0818267	total: 9.08s	remaining: 21.6s
296:	learn: 0.0817462	total: 9.11s	remaining: 21.6s
297:	learn: 0.0815933	total: 9.14s	remaining: 21.5s
298:	learn: 0.0815373	total: 9.17s	remaining: 21.5s
299:	learn: 0.0815055	total: 9.2s	remaining: 21.5s
300:	learn: 0.0814200	total: 9.23s	remaining: 21.4s
301:	learn: 0.0812939	total: 9.27s	remaining: 21.4s
302:	learn: 0.0811736	total: 9.3s	remaining: 21.4s
303:	learn: 0.0811341	total: 9.34s	remaining: 21.4s
304:	learn: 0.0810157	total: 9.37s	remaining: 21.4s
305:	learn: 0.0809001	total: 9.4s	remaining: 21.3s
306:	learn: 0.0807244	total: 9.44s	remaining: 21.3s
307:	learn: 0.0805862	total: 9.48s	remaining: 21.3s
308:	learn: 0.0805625	total: 9.51s	remaining: 21.3s
309:	learn: 0.0804190	total: 9.54s	remaining: 21.2s
310:	learn: 0.0803738	total: 9.57s	remaining: 21.2s
311:	learn: 0.0802667	total: 9.6s	remaining: 21.2s
312:	learn: 0.0801622	total: 9.63s	remaining: 21.1s
313:	learn: 0.0799448	total: 9.66s	remaining: 21.1s
314:	learn: 0.0799001	total: 9.69s	remaining: 21.1s
315:	learn: 0.0798759	total: 9.72s	remaining: 21s
316:	learn: 0.0798042	total: 9.75s	remaining: 21s
317:	learn: 0.0797311	total: 9.79s	remaining: 21s
318:	learn: 0.0796247	total: 9.82s	remaining: 21s
319:	learn: 0.0795866	total: 9.85s	remaining: 20.9s
320:	learn: 0.0795438	total: 9.88s	remaining: 20.9s
321:	learn: 0.0794115	total: 9.91s	remaining: 20.9s
322:	learn: 0.0792521	total: 9.95s	remaining: 20.9s
323:	learn: 0.0791469	total: 9.98s	remaining: 20.8s
324:	learn: 0.0791337	total: 10s	remaining: 20.8s
325:	learn: 0.0791203	total: 10s	remaining: 20.8s
326:	learn: 0.0790418	total: 10.1s	remaining: 20.7s
327:	learn: 0.0789033	total: 10.1s	remaining: 20.7s
328:	learn: 0.0788898	total: 10.1s	remaining: 20.7s
329:	learn: 0.0788825	total: 10.2s	remaining: 20.6s
330:	learn: 0.0788155	total: 10.2s	remaining: 20.6s
331:	learn: 0.0787501	total: 10.2s	remaining: 20.6s
332:	learn: 0.0786360	total: 10.3s	remaining: 20.5s
333:	learn: 0.0786184	total: 10.3s	remaining: 20.5s
334:	learn: 0.0786034	total: 10.3s	remaining: 20.5s
335:	learn: 0.0785055	total: 10.3s	remaining: 20.4s
336:	learn: 0.0783961	total: 10.4s	remaining: 20.4s
337:	learn: 0.0783837	total: 10.4s	remaining: 20.4s
338:	learn: 0.0782819	total: 10.4s	remaining: 20.4s
339:	learn: 0.0781932	total: 10.5s	remaining: 20.4s
340:	learn: 0.0780147	total: 10.5s	remaining: 20.3s
341:	learn: 0.0778529	total: 10.5s	remaining: 20.3s
342:	learn: 0.0777173	total: 10.6s	remaining: 20.3s
343:	learn: 0.0777051	total: 10.6s	remaining: 20.2s
344:	learn: 0.0775930	total: 10.6s	remaining: 20.2s
345:	learn: 0.0774741	total: 10.7s	remaining: 20.2s
346:	learn: 0.0772828	total: 10.7s	remaining: 20.1s
347:	learn: 0.0771848	total: 10.7s	remaining: 20.1s
348:	learn: 0.0770813	total: 10.8s	remaining: 20.1s
349:	learn: 0.0769220	total: 10.8s	remaining: 20s
350:	learn: 0.0767782	total: 10.8s	remaining: 20s
351:	learn: 0.0767258	total: 10.8s	remaining: 20s
352:	learn: 0.0766030	total: 10.9s	remaining: 19.9s
353:	learn: 0.0765763	total: 10.9s	remaining: 19.9s
354:	learn: 0.0765533	total: 10.9s	remaining: 19.9s
355:	learn: 0.0764018	total: 11s	remaining: 19.8s
356:	learn: 0.0763198	total: 11s	remaining: 19.8s
357:	learn: 0.0762488	total: 11s	remaining: 19.8s
358:	learn: 0.0760658	total: 11.1s	remaining: 19.8s
359:	learn: 0.0759681	total: 11.1s	remaining: 19.7s
360:	learn: 0.0758916	total: 11.1s	remaining: 19.7s
361:	learn: 0.0758716	total: 11.2s	remaining: 19.7s
362:	learn: 0.0758017	total: 11.2s	remaining: 19.6s
363:	learn: 0.0756925	total: 11.2s	remaining: 19.6s
364:	learn: 0.0756003	total: 11.2s	remaining: 19.6s
365:	learn: 0.0755231	total: 11.3s	remaining: 19.5s
366:	learn: 0.0753821	total: 11.3s	remaining: 19.5s
367:	learn: 0.0753585	total: 11.3s	remaining: 19.5s
368:	learn: 0.0752575	total: 11.4s	remaining: 19.4s
369:	learn: 0.0751420	total: 11.4s	remaining: 19.4s
370:	learn: 0.0750772	total: 11.4s	remaining: 19.4s
371:	learn: 0.0750317	total: 11.5s	remaining: 19.3s
372:	learn: 0.0749416	total: 11.5s	remaining: 19.3s
373:	learn: 0.0749247	total: 11.5s	remaining: 19.3s
374:	learn: 0.0747710	total: 11.5s	remaining: 19.2s
375:	learn: 0.0747435	total: 11.6s	remaining: 19.2s
376:	learn: 0.0746185	total: 11.6s	remaining: 19.2s
377:	learn: 0.0745062	total: 11.6s	remaining: 19.1s
378:	learn: 0.0744469	total: 11.7s	remaining: 19.1s
379:	learn: 0.0743497	total: 11.7s	remaining: 19.1s
380:	learn: 0.0743292	total: 11.7s	remaining: 19s
381:	learn: 0.0743234	total: 11.8s	remaining: 19s
382:	learn: 0.0743178	total: 11.8s	remaining: 19s
383:	learn: 0.0742716	total: 11.8s	remaining: 18.9s
384:	learn: 0.0741742	total: 11.8s	remaining: 18.9s
385:	learn: 0.0740731	total: 11.9s	remaining: 18.9s
386:	learn: 0.0739572	total: 11.9s	remaining: 18.9s
387:	learn: 0.0739510	total: 11.9s	remaining: 18.8s

CV folds:  20%|██        | 10/50 [05:15<21:01, 31.54s/fold]

Learning rate set to 0.042738
0:	learn: 0.3903608	total: 27.8ms	remaining: 27.7s
1:	learn: 0.3795824	total: 56.8ms	remaining: 28.3s
2:	learn: 0.3698669	total: 90.8ms	remaining: 30.2s
3:	learn: 0.3598273	total: 125ms	remaining: 31.1s
4:	learn: 0.3496541	total: 153ms	remaining: 30.4s
5:	learn: 0.3402995	total: 181ms	remaining: 30s
6:	learn: 0.3311913	total: 215ms	remaining: 30.5s
7:	learn: 0.3223086	total: 250ms	remaining: 31s
8:	learn: 0.3145748	total: 282ms	remaining: 31s
9:	learn: 0.3065491	total: 314ms	remaining: 31.1s
10:	learn: 0.2993430	total: 344ms	remaining: 30.9s
11:	learn: 0.2924352	total: 375ms	remaining: 30.9s
12:	learn: 0.2852017	total: 406ms	remaining: 30.8s
13:	learn: 0.2781911	total: 438ms	remaining: 30.8s
14:	learn: 0.2712003	total: 471ms	remaining: 30.9s
15:	learn: 0.2647497	total: 506ms	remaining: 31.1s
16:	learn: 0.2588841	total: 538ms	remaining: 31.1s
17:	learn: 0.2533810	total: 570ms	remaining: 31.1s
18:	learn: 0.2479216	total: 598ms	remaining: 30.9s
19:	learn: 0.2428872	total: 633ms	remaining: 31s
20:	learn: 0.2377692	total: 672ms	remaining: 31.3s
21:	learn: 0.2333570	total: 704ms	remaining: 31.3s
22:	learn: 0.2286153	total: 736ms	remaining: 31.3s
23:	learn: 0.2240006	total: 765ms	remaining: 31.1s
24:	learn: 0.2194733	total: 797ms	remaining: 31.1s
25:	learn: 0.2151963	total: 843ms	remaining: 31.6s
26:	learn: 0.2111414	total: 874ms	remaining: 31.5s
27:	learn: 0.2072219	total: 903ms	remaining: 31.3s
28:	learn: 0.2032972	total: 935ms	remaining: 31.3s
29:	learn: 0.1999947	total: 969ms	remaining: 31.3s
30:	learn: 0.1965959	total: 998ms	remaining: 31.2s
31:	learn: 0.1934639	total: 1.02s	remaining: 31s
32:	learn: 0.1908023	total: 1.05s	remaining: 30.9s
33:	learn: 0.1874974	total: 1.08s	remaining: 30.9s
34:	learn: 0.1847049	total: 1.11s	remaining: 30.7s
35:	learn: 0.1816830	total: 1.15s	remaining: 30.7s
36:	learn: 0.1792571	total: 1.18s	remaining: 30.7s
37:	learn: 0.1767733	total: 1.21s	remaining: 30.7s
38:	learn: 0.1741592	total: 1.25s	remaining: 30.7s
39:	learn: 0.1717867	total: 1.28s	remaining: 30.6s
40:	learn: 0.1694283	total: 1.3s	remaining: 30.5s
41:	learn: 0.1672397	total: 1.33s	remaining: 30.5s
42:	learn: 0.1650214	total: 1.37s	remaining: 30.4s
43:	learn: 0.1629407	total: 1.4s	remaining: 30.4s
44:	learn: 0.1611003	total: 1.43s	remaining: 30.3s
45:	learn: 0.1591040	total: 1.46s	remaining: 30.2s
46:	learn: 0.1571628	total: 1.49s	remaining: 30.2s
47:	learn: 0.1552968	total: 1.52s	remaining: 30.1s
48:	learn: 0.1535276	total: 1.55s	remaining: 30.1s
49:	learn: 0.1519028	total: 1.58s	remaining: 30s
50:	learn: 0.1502662	total: 1.61s	remaining: 29.9s
51:	learn: 0.1485971	total: 1.64s	remaining: 29.8s
52:	learn: 0.1470370	total: 1.67s	remaining: 29.8s
53:	learn: 0.1454043	total: 1.7s	remaining: 29.7s
54:	learn: 0.1441318	total: 1.73s	remaining: 29.7s
55:	learn: 0.1427427	total: 1.76s	remaining: 29.6s
56:	learn: 0.1416252	total: 1.79s	remaining: 29.6s
57:	learn: 0.1403681	total: 1.82s	remaining: 29.5s
58:	learn: 0.1391584	total: 1.84s	remaining: 29.4s
59:	learn: 0.1379632	total: 1.87s	remaining: 29.4s
60:	learn: 0.1368686	total: 1.9s	remaining: 29.3s
61:	learn: 0.1357841	total: 1.93s	remaining: 29.3s
62:	learn: 0.1347433	total: 1.97s	remaining: 29.2s
63:	learn: 0.1336843	total: 2s	remaining: 29.2s
64:	learn: 0.1328383	total: 2.03s	remaining: 29.2s
65:	learn: 0.1320562	total: 2.06s	remaining: 29.1s
66:	learn: 0.1311705	total: 2.09s	remaining: 29.1s
67:	learn: 0.1301627	total: 2.12s	remaining: 29s
68:	learn: 0.1293560	total: 2.15s	remaining: 28.9s
69:	learn: 0.1284618	total: 2.18s	remaining: 28.9s
70:	learn: 0.1277290	total: 2.22s	remaining: 29s
71:	learn: 0.1270416	total: 2.25s	remaining: 29s
72:	learn: 0.1263008	total: 2.28s	remaining: 28.9s
73:	learn: 0.1256406	total: 2.31s	remaining: 28.9s
74:	learn: 0.1248845	total: 2.34s	remaining: 28.9s
75:	learn: 0.1239249	total: 2.37s	remaining: 28.8s
76:	learn: 0.1229254	total: 2.4s	remaining: 28.8s
77:	learn: 0.1221088	total: 2.43s	remaining: 28.8s
78:	learn: 0.1214360	total: 2.46s	remaining: 28.7s
79:	learn: 0.1206882	total: 2.49s	remaining: 28.6s
80:	learn: 0.1201924	total: 2.52s	remaining: 28.6s
81:	learn: 0.1195585	total: 2.55s	remaining: 28.6s
82:	learn: 0.1189381	total: 2.58s	remaining: 28.5s
83:	learn: 0.1183733	total: 2.61s	remaining: 28.5s
84:	learn: 0.1176776	total: 2.64s	remaining: 28.4s
85:	learn: 0.1170804	total: 2.67s	remaining: 28.4s
86:	learn: 0.1164842	total: 2.71s	remaining: 28.4s
87:	learn: 0.1159909	total: 2.74s	remaining: 28.4s
88:	learn: 0.1155569	total: 2.77s	remaining: 28.4s
89:	learn: 0.1149531	total: 2.81s	remaining: 28.4s
90:	learn: 0.1145564	total: 2.84s	remaining: 28.4s
91:	learn: 0.1140887	total: 2.87s	remaining: 28.4s
92:	learn: 0.1135964	total: 2.9s	remaining: 28.3s
93:	learn: 0.1132409	total: 2.94s	remaining: 28.3s
94:	learn: 0.1127925	total: 2.97s	remaining: 28.3s
95:	learn: 0.1123777	total: 3s	remaining: 28.2s
96:	learn: 0.1119309	total: 3.03s	remaining: 28.2s
97:	learn: 0.1114332	total: 3.06s	remaining: 28.2s
98:	learn: 0.1109342	total: 3.09s	remaining: 28.1s
99:	learn: 0.1105070	total: 3.12s	remaining: 28.1s
100:	learn: 0.1101370	total: 3.15s	remaining: 28s
101:	learn: 0.1098051	total: 3.18s	remaining: 28s
102:	learn: 0.1093766	total: 3.21s	remaining: 27.9s
103:	learn: 0.1090328	total: 3.24s	remaining: 27.9s
104:	learn: 0.1086342	total: 3.27s	remaining: 27.9s
105:	learn: 0.1081957	total: 3.3s	remaining: 27.8s
106:	learn: 0.1077677	total: 3.33s	remaining: 27.8s
107:	learn: 0.1075331	total: 3.37s	remaining: 27.8s
108:	learn: 0.1072398	total: 3.4s	remaining: 27.8s
109:	learn: 0.1069188	total: 3.43s	remaining: 27.8s
110:	learn: 0.1066265	total: 3.46s	remaining: 27.7s
111:	learn: 0.1062088	total: 3.49s	remaining: 27.7s
112:	learn: 0.1058881	total: 3.52s	remaining: 27.7s
113:	learn: 0.1056111	total: 3.57s	remaining: 27.8s
114:	learn: 0.1053328	total: 3.6s	remaining: 27.7s
115:	learn: 0.1050752	total: 3.63s	remaining: 27.7s
116:	learn: 0.1048131	total: 3.66s	remaining: 27.7s
117:	learn: 0.1044692	total: 3.69s	remaining: 27.6s
118:	learn: 0.1041563	total: 3.72s	remaining: 27.6s
119:	learn: 0.1038677	total: 3.75s	remaining: 27.5s
120:	learn: 0.1035126	total: 3.79s	remaining: 27.5s
121:	learn: 0.1032117	total: 3.81s	remaining: 27.5s
122:	learn: 0.1028799	total: 3.85s	remaining: 27.4s
123:	learn: 0.1026832	total: 3.88s	remaining: 27.4s
124:	learn: 0.1023360	total: 3.9s	remaining: 27.3s
125:	learn: 0.1020456	total: 3.93s	remaining: 27.3s
126:	learn: 0.1017442	total: 3.96s	remaining: 27.3s
127:	learn: 0.1016564	total: 3.97s	remaining: 27.1s
128:	learn: 0.1014299	total: 4s	remaining: 27s
129:	learn: 0.1012658	total: 4.03s	remaining: 27s
130:	learn: 0.1009920	total: 4.07s	remaining: 27s
131:	learn: 0.1006782	total: 4.1s	remaining: 26.9s
132:	learn: 0.1004067	total: 4.13s	remaining: 26.9s
133:	learn: 0.1002069	total: 4.16s	remaining: 26.9s
134:	learn: 0.1001767	total: 4.18s	remaining: 26.8s
135:	learn: 0.0999159	total: 4.21s	remaining: 26.7s
136:	learn: 0.0997312	total: 4.24s	remaining: 26.7s
137:	learn: 0.0994151	total: 4.27s	remaining: 26.7s
138:	learn: 0.0991940	total: 4.3s	remaining: 26.6s
139:	learn: 0.0990788	total: 4.33s	remaining: 26.6s
140:	learn: 0.0987668	total: 4.36s	remaining: 26.6s
141:	learn: 0.0985072	total: 4.39s	remaining: 26.5s
142:	learn: 0.0982287	total: 4.42s	remaining: 26.5s
143:	learn: 0.0979652	total: 4.45s	remaining: 26.4s
144:	learn: 0.0977934	total: 4.48s	remaining: 26.4s
145:	learn: 0.0975348	total: 4.51s	remaining: 26.4s
146:	learn: 0.0973541	total: 4.54s	remaining: 26.4s
147:	learn: 0.0970889	total: 4.57s	remaining: 26.3s
148:	learn: 0.0968150	total: 4.6s	remaining: 26.3s
149:	learn: 0.0966302	total: 4.63s	remaining: 26.2s
150:	learn: 0.0964856	total: 4.66s	remaining: 26.2s
151:	learn: 0.0963647	total: 4.69s	remaining: 26.2s
152:	learn: 0.0961520	total: 4.73s	remaining: 26.2s
153:	learn: 0.0960159	total: 4.76s	remaining: 26.1s
154:	learn: 0.0958641	total: 4.79s	remaining: 26.1s
155:	learn: 0.0956773	total: 4.82s	remaining: 26.1s
156:	learn: 0.0954392	total: 4.85s	remaining: 26.1s
157:	learn: 0.0952940	total: 4.88s	remaining: 26s
158:	learn: 0.0951985	total: 4.91s	remaining: 26s
159:	learn: 0.0950240	total: 4.95s	remaining: 26s
160:	learn: 0.0948360	total: 4.99s	remaining: 26s
161:	learn: 0.0946572	total: 5.01s	remaining: 25.9s
162:	learn: 0.0943947	total: 5.04s	remaining: 25.9s
163:	learn: 0.0942325	total: 5.07s	remaining: 25.9s
164:	learn: 0.0940235	total: 5.1s	remaining: 25.8s
165:	learn: 0.0939030	total: 5.15s	remaining: 25.9s
166:	learn: 0.0936536	total: 5.18s	remaining: 25.8s
167:	learn: 0.0934953	total: 5.21s	remaining: 25.8s
168:	learn: 0.0933387	total: 5.24s	remaining: 25.7s
169:	learn: 0.0932411	total: 5.27s	remaining: 25.7s
170:	learn: 0.0930762	total: 5.29s	remaining: 25.7s
171:	learn: 0.0928644	total: 5.33s	remaining: 25.7s
172:	learn: 0.0926987	total: 5.36s	remaining: 25.6s
173:	learn: 0.0925792	total: 5.39s	remaining: 25.6s
174:	learn: 0.0924679	total: 5.42s	remaining: 25.6s
175:	learn: 0.0922110	total: 5.45s	remaining: 25.5s
176:	learn: 0.0920743	total: 5.48s	remaining: 25.5s
177:	learn: 0.0919717	total: 5.51s	remaining: 25.4s
178:	learn: 0.0918307	total: 5.54s	remaining: 25.4s
179:	learn: 0.0917216	total: 5.57s	remaining: 25.4s
180:	learn: 0.0915674	total: 5.61s	remaining: 25.4s
181:	learn: 0.0913352	total: 5.64s	remaining: 25.3s
182:	learn: 0.0911444	total: 5.67s	remaining: 25.3s
183:	learn: 0.0909893	total: 5.71s	remaining: 25.3s
184:	learn: 0.0908856	total: 5.73s	remaining: 25.3s
185:	learn: 0.0907305	total: 5.76s	remaining: 25.2s
186:	learn: 0.0905458	total: 5.79s	remaining: 25.2s
187:	learn: 0.0903366	total: 5.82s	remaining: 25.1s
188:	learn: 0.0902800	total: 5.85s	remaining: 25.1s
189:	learn: 0.0901611	total: 5.88s	remaining: 25.1s
190:	learn: 0.0900772	total: 5.91s	remaining: 25s
191:	learn: 0.0899689	total: 5.94s	remaining: 25s
192:	learn: 0.0898225	total: 5.97s	remaining: 25s
193:	learn: 0.0897096	total: 6.02s	remaining: 25s
194:	learn: 0.0894997	total: 6.05s	remaining: 25s
195:	learn: 0.0893966	total: 6.08s	remaining: 24.9s
196:	learn: 0.0892872	total: 6.11s	remaining: 24.9s
197:	learn: 0.0890791	total: 6.14s	remaining: 24.9s
198:	learn: 0.0889460	total: 6.17s	remaining: 24.8s
199:	learn: 0.0887581	total: 6.2s	remaining: 24.8s
200:	learn: 0.0885622	total: 6.23s	remaining: 24.8s
201:	learn: 0.0884619	total: 6.26s	remaining: 24.7s
202:	learn: 0.0883963	total: 6.29s	remaining: 24.7s
203:	learn: 0.0883206	total: 6.32s	remaining: 24.7s
204:	learn: 0.0881716	total: 6.35s	remaining: 24.6s
205:	learn: 0.0880545	total: 6.38s	remaining: 24.6s
206:	learn: 0.0878661	total: 6.41s	remaining: 24.6s
207:	learn: 0.0877621	total: 6.44s	remaining: 24.5s
208:	learn: 0.0877000	total: 6.47s	remaining: 24.5s
209:	learn: 0.0875997	total: 6.5s	remaining: 24.5s
210:	learn: 0.0875273	total: 6.54s	remaining: 24.4s
211:	learn: 0.0873321	total: 6.56s	remaining: 24.4s
212:	learn: 0.0872844	total: 6.59s	remaining: 24.4s
213:	learn: 0.0871787	total: 6.62s	remaining: 24.3s
214:	learn: 0.0871256	total: 6.66s	remaining: 24.3s
215:	learn: 0.0870901	total: 6.69s	remaining: 24.3s
216:	learn: 0.0869462	total: 6.72s	remaining: 24.2s
217:	learn: 0.0868938	total: 6.75s	remaining: 24.2s
218:	learn: 0.0867753	total: 6.78s	remaining: 24.2s
219:	learn: 0.0865750	total: 6.81s	remaining: 24.1s
220:	learn: 0.0863840	total: 6.84s	remaining: 24.1s
221:	learn: 0.0863582	total: 6.87s	remaining: 24.1s
222:	learn: 0.0861982	total: 6.9s	remaining: 24.1s
223:	learn: 0.0860658	total: 6.93s	remaining: 24s
224:	learn: 0.0859728	total: 6.96s	remaining: 24s
225:	learn: 0.0858663	total: 6.99s	remaining: 23.9s
226:	learn: 0.0856852	total: 7.02s	remaining: 23.9s
227:	learn: 0.0855270	total: 7.05s	remaining: 23.9s
228:	learn: 0.0854775	total: 7.09s	remaining: 23.9s
229:	learn: 0.0854373	total: 7.13s	remaining: 23.9s
230:	learn: 0.0852891	total: 7.16s	remaining: 23.8s
231:	learn: 0.0851821	total: 7.18s	remaining: 23.8s
232:	learn: 0.0850324	total: 7.21s	remaining: 23.8s
233:	learn: 0.0848806	total: 7.25s	remaining: 23.7s
234:	learn: 0.0847748	total: 7.28s	remaining: 23.7s
235:	learn: 0.0845982	total: 7.31s	remaining: 23.7s
236:	learn: 0.0844960	total: 7.34s	remaining: 23.6s
237:	learn: 0.0844310	total: 7.37s	remaining: 23.6s
238:	learn: 0.0843858	total: 7.41s	remaining: 23.6s
239:	learn: 0.0842008	total: 7.44s	remaining: 23.6s
240:	learn: 0.0841803	total: 7.47s	remaining: 23.5s
241:	learn: 0.0840498	total: 7.5s	remaining: 23.5s
242:	learn: 0.0839046	total: 7.53s	remaining: 23.5s
243:	learn: 0.0838203	total: 7.56s	remaining: 23.4s
244:	learn: 0.0837878	total: 7.59s	remaining: 23.4s
245:	learn: 0.0836748	total: 7.62s	remaining: 23.4s
246:	learn: 0.0836417	total: 7.65s	remaining: 23.3s
247:	learn: 0.0834974	total: 7.68s	remaining: 23.3s
248:	learn: 0.0833742	total: 7.71s	remaining: 23.3s
249:	learn: 0.0833043	total: 7.74s	remaining: 23.2s
250:	learn: 0.0831910	total: 7.77s	remaining: 23.2s
251:	learn: 0.0830929	total: 7.8s	remaining: 23.2s
252:	learn: 0.0828755	total: 7.83s	remaining: 23.1s
253:	learn: 0.0827902	total: 7.87s	remaining: 23.1s
254:	learn: 0.0826165	total: 7.9s	remaining: 23.1s
255:	learn: 0.0825685	total: 7.93s	remaining: 23s
256:	learn: 0.0824467	total: 7.96s	remaining: 23s
257:	learn: 0.0824276	total: 7.99s	remaining: 23s
258:	learn: 0.0823962	total: 8.02s	remaining: 23s
259:	learn: 0.0822430	total: 8.05s	remaining: 22.9s
260:	learn: 0.0821162	total: 8.08s	remaining: 22.9s
261:	learn: 0.0820060	total: 8.11s	remaining: 22.9s
262:	learn: 0.0818808	total: 8.14s	remaining: 22.8s
263:	learn: 0.0817158	total: 8.17s	remaining: 22.8s
264:	learn: 0.0816165	total: 8.2s	remaining: 22.8s
265:	learn: 0.0814432	total: 8.23s	remaining: 22.7s
266:	learn: 0.0813824	total: 8.26s	remaining: 22.7s
267:	learn: 0.0813373	total: 8.29s	remaining: 22.7s
268:	learn: 0.0811856	total: 8.32s	remaining: 22.6s
269:	learn: 0.0810550	total: 8.36s	remaining: 22.6s
270:	learn: 0.0809435	total: 8.39s	remaining: 22.6s
271:	learn: 0.0809159	total: 8.42s	remaining: 22.5s
272:	learn: 0.0808366	total: 8.45s	remaining: 22.5s
273:	learn: 0.0808244	total: 8.48s	remaining: 22.5s
274:	learn: 0.0806349	total: 8.51s	remaining: 22.4s
275:	learn: 0.0805003	total: 8.54s	remaining: 22.4s
276:	learn: 0.0804037	total: 8.57s	remaining: 22.4s
277:	learn: 0.0803013	total: 8.61s	remaining: 22.4s
278:	learn: 0.0801103	total: 8.64s	remaining: 22.3s
279:	learn: 0.0800411	total: 8.67s	remaining: 22.3s
280:	learn: 0.0800136	total: 8.7s	remaining: 22.3s
281:	learn: 0.0799226	total: 8.73s	remaining: 22.2s
282:	learn: 0.0798947	total: 8.76s	remaining: 22.2s
283:	learn: 0.0798013	total: 8.79s	remaining: 22.2s
284:	learn: 0.0797047	total: 8.82s	remaining: 22.1s
285:	learn: 0.0796855	total: 8.85s	remaining: 22.1s
286:	learn: 0.0795951	total: 8.88s	remaining: 22.1s
287:	learn: 0.0794054	total: 8.91s	remaining: 22s
288:	learn: 0.0793891	total: 8.94s	remaining: 22s
289:	learn: 0.0793728	total: 8.97s	remaining: 22s
290:	learn: 0.0792292	total: 9s	remaining: 21.9s
291:	learn: 0.0791659	total: 9.03s	remaining: 21.9s
292:	learn: 0.0791551	total: 9.06s	remaining: 21.9s
293:	learn: 0.0790091	total: 9.09s	remaining: 21.8s
294:	learn: 0.0789203	total: 9.12s	remaining: 21.8s
295:	learn: 0.0788932	total: 9.15s	remaining: 21.8s
296:	learn: 0.0788051	total: 9.18s	remaining: 21.7s
297:	learn: 0.0786708	total: 9.21s	remaining: 21.7s
298:	learn: 0.0785162	total: 9.26s	remaining: 21.7s
299:	learn: 0.0784987	total: 9.29s	remaining: 21.7s
300:	learn: 0.0784084	total: 9.32s	remaining: 21.6s
301:	learn: 0.0782799	total: 9.35s	remaining: 21.6s
302:	learn: 0.0782194	total: 9.39s	remaining: 21.6s
303:	learn: 0.0781353	total: 9.41s	remaining: 21.6s
304:	learn: 0.0780105	total: 9.45s	remaining: 21.5s
305:	learn: 0.0779571	total: 9.47s	remaining: 21.5s
306:	learn: 0.0778040	total: 9.53s	remaining: 21.5s
307:	learn: 0.0777623	total: 9.56s	remaining: 21.5s
308:	learn: 0.0776639	total: 9.59s	remaining: 21.4s
309:	learn: 0.0775956	total: 9.62s	remaining: 21.4s
310:	learn: 0.0774938	total: 9.65s	remaining: 21.4s
311:	learn: 0.0774051	total: 9.68s	remaining: 21.4s
312:	learn: 0.0772488	total: 9.72s	remaining: 21.3s
313:	learn: 0.0771685	total: 9.74s	remaining: 21.3s
314:	learn: 0.0771516	total: 9.78s	remaining: 21.3s
315:	learn: 0.0771343	total: 9.81s	remaining: 21.2s
316:	learn: 0.0768973	total: 9.84s	remaining: 21.2s
317:	learn: 0.0767789	total: 9.87s	remaining: 21.2s
318:	learn: 0.0766014	total: 9.9s	remaining: 21.1s
319:	learn: 0.0764465	total: 9.93s	remaining: 21.1s
320:	learn: 0.0763308	total: 9.96s	remaining: 21.1s
321:	learn: 0.0762954	total: 9.99s	remaining: 21s
322:	learn: 0.0762100	total: 10s	remaining: 21s
323:	learn: 0.0760673	total: 10.1s	remaining: 21s
324:	learn: 0.0760290	total: 10.1s	remaining: 20.9s
325:	learn: 0.0760171	total: 10.1s	remaining: 20.9s
326:	learn: 0.0759990	total: 10.1s	remaining: 20.9s
327:	learn: 0.0759334	total: 10.2s	remaining: 20.8s
328:	learn: 0.0758741	total: 10.2s	remaining: 20.8s
329:	learn: 0.0757950	total: 10.2s	remaining: 20.8s
330:	learn: 0.0756547	total: 10.3s	remaining: 20.7s
331:	learn: 0.0756241	total: 10.3s	remaining: 20.7s
332:	learn: 0.0755390	total: 10.3s	remaining: 20.7s
333:	learn: 0.0755304	total: 10.4s	remaining: 20.6s
334:	learn: 0.0754406	total: 10.4s	remaining: 20.6s
335:	learn: 0.0753772	total: 10.4s	remaining: 20.6s
336:	learn: 0.0753654	total: 10.4s	remaining: 20.5s
337:	learn: 0.0752536	total: 10.5s	remaining: 20.5s
338:	learn: 0.0752400	total: 10.5s	remaining: 20.5s
339:	learn: 0.0751013	total: 10.5s	remaining: 20.4s
340:	learn: 0.0750574	total: 10.6s	remaining: 20.4s
341:	learn: 0.0749695	total: 10.6s	remaining: 20.4s
342:	learn: 0.0749567	total: 10.6s	remaining: 20.3s
343:	learn: 0.0749397	total: 10.6s	remaining: 20.3s
344:	learn: 0.0749124	total: 10.7s	remaining: 20.3s
345:	learn: 0.0748058	total: 10.7s	remaining: 20.2s
346:	learn: 0.0746992	total: 10.7s	remaining: 20.2s
347:	learn: 0.0746319	total: 10.8s	remaining: 20.2s
348:	learn: 0.0744829	total: 10.8s	remaining: 20.1s
349:	learn: 0.0744729	total: 10.8s	remaining: 20.1s
350:	learn: 0.0744092	total: 10.9s	remaining: 20.1s
351:	learn: 0.0743052	total: 10.9s	remaining: 20s
352:	learn: 0.0742204	total: 10.9s	remaining: 20s
353:	learn: 0.0741653	total: 11s	remaining: 20s
354:	learn: 0.0741160	total: 11s	remaining: 20s
355:	learn: 0.0738168	total: 11s	remaining: 19.9s
356:	learn: 0.0735822	total: 11s	remaining: 19.9s
357:	learn: 0.0733257	total: 11.1s	remaining: 19.9s
358:	learn: 0.0730505	total: 11.1s	remaining: 19.8s
359:	learn: 0.0729047	total: 11.1s	remaining: 19.8s
360:	learn: 0.0726275	total: 11.2s	remaining: 19.8s
361:	learn: 0.0724488	total: 11.2s	remaining: 19.7s
362:	learn: 0.0723984	total: 11.2s	remaining: 19.7s
363:	learn: 0.0722862	total: 11.3s	remaining: 19.7s
364:	learn: 0.0722756	total: 11.3s	remaining: 19.6s
365:	learn: 0.0721520	total: 11.3s	remaining: 19.6s
366:	learn: 0.0720204	total: 11.4s	remaining: 19.6s
367:	learn: 0.0720001	total: 11.4s	remaining: 19.6s
368:	learn: 0.0719551	total: 11.4s	remaining: 19.5s
369:	learn: 0.0718575	total: 11.5s	remaining: 19.5s
370:	learn: 0.0715912	total: 11.5s	remaining: 19.5s
371:	learn: 0.0715826	total: 11.5s	remaining: 19.4s
372:	learn: 0.0714771	total: 11.5s	remaining: 19.4s
373:	learn: 0.0713680	total: 11.6s	remaining: 19.4s
374:	learn: 0.0711782	total: 11.6s	remaining: 19.3s
375:	learn: 0.0710888	total: 11.6s	remaining: 19.3s
376:	learn: 0.0710138	total: 11.7s	remaining: 19.3s
377:	learn: 0.0708700	total: 11.7s	remaining: 19.2s
378:	learn: 0.0707689	total: 11.7s	remaining: 19.2s
379:	learn: 0.0705374	total: 11.8s	remaining: 19.2s
380:	learn: 0.0705172	total: 11.8s	remaining: 19.2s
381:	learn: 0.0704346	total: 11.8s	remaining: 19.1s
382:	learn: 0.0703336	total: 11.8s	remaining: 19.1s
383:	learn: 0.0702457	total: 11.9s	remaining: 19.1s
384:	learn: 0.0701558	total: 11.9s	remaining: 19s
385:	learn: 0.0700093	total: 11.9s	remaining: 19s
386:	learn: 0.0698248	total: 12s	remaining: 19s
387:	learn: 0.0697336	total: 12s	remaining: 18.9s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior1st': 1 unseen categories converted to Unseen on transform.

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior2nd': 1 unseen categories converted to Unseen on transform.

CV folds:  22%|██▏       | 11/50 [05:46<20:32, 31.61s/fold]

Learning rate set to 0.042738
0:	learn: 0.3849784	total: 28.1ms	remaining: 28.1s
1:	learn: 0.3741948	total: 58.6ms	remaining: 29.3s
2:	learn: 0.3644696	total: 89.6ms	remaining: 29.8s
3:	learn: 0.3548345	total: 120ms	remaining: 29.8s
4:	learn: 0.3451172	total: 151ms	remaining: 30.1s
5:	learn: 0.3358710	total: 181ms	remaining: 29.9s
6:	learn: 0.3267138	total: 210ms	remaining: 29.8s
7:	learn: 0.3181835	total: 246ms	remaining: 30.5s
8:	learn: 0.3107479	total: 278ms	remaining: 30.6s
9:	learn: 0.3030248	total: 308ms	remaining: 30.5s
10:	learn: 0.2955000	total: 336ms	remaining: 30.2s
11:	learn: 0.2877168	total: 367ms	remaining: 30.2s
12:	learn: 0.2810138	total: 395ms	remaining: 30s
13:	learn: 0.2743509	total: 426ms	remaining: 30s
14:	learn: 0.2684212	total: 459ms	remaining: 30.1s
15:	learn: 0.2621859	total: 490ms	remaining: 30.1s
16:	learn: 0.2567465	total: 520ms	remaining: 30.1s
17:	learn: 0.2507451	total: 554ms	remaining: 30.2s
18:	learn: 0.2456028	total: 584ms	remaining: 30.1s
19:	learn: 0.2403684	total: 615ms	remaining: 30.1s
20:	learn: 0.2353672	total: 644ms	remaining: 30s
21:	learn: 0.2305299	total: 677ms	remaining: 30.1s
22:	learn: 0.2261870	total: 709ms	remaining: 30.1s
23:	learn: 0.2220079	total: 740ms	remaining: 30.1s
24:	learn: 0.2177912	total: 771ms	remaining: 30.1s
25:	learn: 0.2132210	total: 801ms	remaining: 30s
26:	learn: 0.2089836	total: 831ms	remaining: 29.9s
27:	learn: 0.2050404	total: 863ms	remaining: 30s
28:	learn: 0.2013121	total: 894ms	remaining: 29.9s
29:	learn: 0.1979414	total: 927ms	remaining: 30s
30:	learn: 0.1947180	total: 979ms	remaining: 30.6s
31:	learn: 0.1915287	total: 1.01s	remaining: 30.7s
32:	learn: 0.1883866	total: 1.04s	remaining: 30.6s
33:	learn: 0.1855347	total: 1.07s	remaining: 30.4s
34:	learn: 0.1828196	total: 1.1s	remaining: 30.4s
35:	learn: 0.1806592	total: 1.14s	remaining: 30.4s
36:	learn: 0.1776317	total: 1.16s	remaining: 30.3s
37:	learn: 0.1752957	total: 1.19s	remaining: 30.2s
38:	learn: 0.1727328	total: 1.23s	remaining: 30.2s
39:	learn: 0.1704587	total: 1.26s	remaining: 30.2s
40:	learn: 0.1685325	total: 1.28s	remaining: 30.1s
41:	learn: 0.1663717	total: 1.31s	remaining: 30s
42:	learn: 0.1644731	total: 1.34s	remaining: 29.9s
43:	learn: 0.1626929	total: 1.39s	remaining: 30.2s
44:	learn: 0.1606339	total: 1.42s	remaining: 30.2s
45:	learn: 0.1586794	total: 1.46s	remaining: 30.3s
46:	learn: 0.1573334	total: 1.48s	remaining: 30s
47:	learn: 0.1554422	total: 1.51s	remaining: 29.9s
48:	learn: 0.1535303	total: 1.54s	remaining: 30s
49:	learn: 0.1519371	total: 1.58s	remaining: 30s
50:	learn: 0.1501026	total: 1.61s	remaining: 30s
51:	learn: 0.1486369	total: 1.64s	remaining: 29.9s
52:	learn: 0.1470691	total: 1.67s	remaining: 29.9s
53:	learn: 0.1456323	total: 1.7s	remaining: 29.8s
54:	learn: 0.1442311	total: 1.73s	remaining: 29.7s
55:	learn: 0.1427038	total: 1.76s	remaining: 29.7s
56:	learn: 0.1414115	total: 1.79s	remaining: 29.7s
57:	learn: 0.1402546	total: 1.82s	remaining: 29.6s
58:	learn: 0.1390938	total: 1.85s	remaining: 29.6s
59:	learn: 0.1379190	total: 1.88s	remaining: 29.5s
60:	learn: 0.1367512	total: 1.91s	remaining: 29.5s
61:	learn: 0.1355004	total: 1.98s	remaining: 30s
62:	learn: 0.1342626	total: 2.02s	remaining: 30s
63:	learn: 0.1332870	total: 2.05s	remaining: 30s
64:	learn: 0.1323867	total: 2.08s	remaining: 29.9s
65:	learn: 0.1315676	total: 2.11s	remaining: 29.9s
66:	learn: 0.1307980	total: 2.14s	remaining: 29.8s
67:	learn: 0.1298743	total: 2.17s	remaining: 29.7s
68:	learn: 0.1289600	total: 2.2s	remaining: 29.7s
69:	learn: 0.1282248	total: 2.23s	remaining: 29.6s
70:	learn: 0.1274048	total: 2.26s	remaining: 29.6s
71:	learn: 0.1265270	total: 2.29s	remaining: 29.6s
72:	learn: 0.1256836	total: 2.32s	remaining: 29.5s
73:	learn: 0.1249035	total: 2.35s	remaining: 29.5s
74:	learn: 0.1242481	total: 2.38s	remaining: 29.4s
75:	learn: 0.1235549	total: 2.41s	remaining: 29.3s
76:	learn: 0.1229783	total: 2.44s	remaining: 29.3s
77:	learn: 0.1222594	total: 2.47s	remaining: 29.2s
78:	learn: 0.1216340	total: 2.5s	remaining: 29.2s
79:	learn: 0.1208614	total: 2.54s	remaining: 29.2s
80:	learn: 0.1202045	total: 2.57s	remaining: 29.1s
81:	learn: 0.1196546	total: 2.6s	remaining: 29.1s
82:	learn: 0.1191665	total: 2.63s	remaining: 29s
83:	learn: 0.1186319	total: 2.66s	remaining: 29s
84:	learn: 0.1181052	total: 2.69s	remaining: 29s
85:	learn: 0.1176175	total: 2.72s	remaining: 28.9s
86:	learn: 0.1170347	total: 2.75s	remaining: 28.9s
87:	learn: 0.1165683	total: 2.78s	remaining: 28.8s
88:	learn: 0.1162107	total: 2.81s	remaining: 28.7s
89:	learn: 0.1158628	total: 2.84s	remaining: 28.7s
90:	learn: 0.1153506	total: 2.87s	remaining: 28.7s
91:	learn: 0.1148534	total: 2.9s	remaining: 28.7s
92:	learn: 0.1143347	total: 2.93s	remaining: 28.6s
93:	learn: 0.1138885	total: 2.96s	remaining: 28.6s
94:	learn: 0.1133353	total: 2.99s	remaining: 28.5s
95:	learn: 0.1129046	total: 3.03s	remaining: 28.5s
96:	learn: 0.1126462	total: 3.06s	remaining: 28.5s
97:	learn: 0.1122585	total: 3.09s	remaining: 28.5s
98:	learn: 0.1119015	total: 3.12s	remaining: 28.4s
99:	learn: 0.1114757	total: 3.15s	remaining: 28.4s
100:	learn: 0.1110458	total: 3.18s	remaining: 28.3s
101:	learn: 0.1106757	total: 3.21s	remaining: 28.3s
102:	learn: 0.1102746	total: 3.24s	remaining: 28.2s
103:	learn: 0.1098493	total: 3.27s	remaining: 28.2s
104:	learn: 0.1091789	total: 3.31s	remaining: 28.2s
105:	learn: 0.1088124	total: 3.34s	remaining: 28.2s
106:	learn: 0.1084523	total: 3.37s	remaining: 28.1s
107:	learn: 0.1081213	total: 3.4s	remaining: 28.1s
108:	learn: 0.1077156	total: 3.43s	remaining: 28.1s
109:	learn: 0.1072183	total: 3.46s	remaining: 28s
110:	learn: 0.1068610	total: 3.49s	remaining: 28s
111:	learn: 0.1066178	total: 3.53s	remaining: 28s
112:	learn: 0.1062908	total: 3.57s	remaining: 28s
113:	learn: 0.1060585	total: 3.6s	remaining: 28s
114:	learn: 0.1057244	total: 3.63s	remaining: 27.9s
115:	learn: 0.1053944	total: 3.66s	remaining: 27.9s
116:	learn: 0.1049731	total: 3.69s	remaining: 27.9s
117:	learn: 0.1046537	total: 3.73s	remaining: 27.9s
118:	learn: 0.1043989	total: 3.76s	remaining: 27.8s
119:	learn: 0.1040396	total: 3.79s	remaining: 27.8s
120:	learn: 0.1037967	total: 3.82s	remaining: 27.7s
121:	learn: 0.1033804	total: 3.85s	remaining: 27.7s
122:	learn: 0.1030537	total: 3.88s	remaining: 27.7s
123:	learn: 0.1028097	total: 3.91s	remaining: 27.6s
124:	learn: 0.1024755	total: 3.94s	remaining: 27.6s
125:	learn: 0.1022799	total: 3.97s	remaining: 27.6s
126:	learn: 0.1018674	total: 4s	remaining: 27.5s
127:	learn: 0.1015653	total: 4.04s	remaining: 27.5s
128:	learn: 0.1013658	total: 4.07s	remaining: 27.5s
129:	learn: 0.1011398	total: 4.1s	remaining: 27.4s
130:	learn: 0.1008275	total: 4.13s	remaining: 27.4s
131:	learn: 0.1005458	total: 4.16s	remaining: 27.4s
132:	learn: 0.1003274	total: 4.19s	remaining: 27.3s
133:	learn: 0.1000930	total: 4.23s	remaining: 27.3s
134:	learn: 0.0998712	total: 4.26s	remaining: 27.3s
135:	learn: 0.0995936	total: 4.29s	remaining: 27.3s
136:	learn: 0.0993981	total: 4.32s	remaining: 27.2s
137:	learn: 0.0993576	total: 4.33s	remaining: 27s
138:	learn: 0.0992087	total: 4.36s	remaining: 27s
139:	learn: 0.0990017	total: 4.39s	remaining: 27s
140:	learn: 0.0987878	total: 4.42s	remaining: 27s
141:	learn: 0.0986587	total: 4.46s	remaining: 26.9s
142:	learn: 0.0985294	total: 4.48s	remaining: 26.9s
143:	learn: 0.0983422	total: 4.51s	remaining: 26.8s
144:	learn: 0.0981334	total: 4.55s	remaining: 26.8s
145:	learn: 0.0979054	total: 4.58s	remaining: 26.8s
146:	learn: 0.0977055	total: 4.61s	remaining: 26.8s
147:	learn: 0.0975786	total: 4.64s	remaining: 26.7s
148:	learn: 0.0974597	total: 4.68s	remaining: 26.7s
149:	learn: 0.0972827	total: 4.71s	remaining: 26.7s
150:	learn: 0.0971285	total: 4.74s	remaining: 26.6s
151:	learn: 0.0969996	total: 4.76s	remaining: 26.6s
152:	learn: 0.0968229	total: 4.79s	remaining: 26.5s
153:	learn: 0.0965738	total: 4.82s	remaining: 26.5s
154:	learn: 0.0964148	total: 4.85s	remaining: 26.4s
155:	learn: 0.0962783	total: 4.88s	remaining: 26.4s
156:	learn: 0.0960666	total: 4.91s	remaining: 26.4s
157:	learn: 0.0959107	total: 4.94s	remaining: 26.3s
158:	learn: 0.0957975	total: 4.98s	remaining: 26.3s
159:	learn: 0.0955757	total: 5.01s	remaining: 26.3s
160:	learn: 0.0954631	total: 5.04s	remaining: 26.3s
161:	learn: 0.0952021	total: 5.07s	remaining: 26.2s
162:	learn: 0.0950608	total: 5.1s	remaining: 26.2s
163:	learn: 0.0949065	total: 5.13s	remaining: 26.1s
164:	learn: 0.0947324	total: 5.16s	remaining: 26.1s
165:	learn: 0.0946591	total: 5.19s	remaining: 26.1s
166:	learn: 0.0945370	total: 5.22s	remaining: 26.1s
167:	learn: 0.0944169	total: 5.25s	remaining: 26s
168:	learn: 0.0942051	total: 5.28s	remaining: 26s
169:	learn: 0.0939190	total: 5.32s	remaining: 26s
170:	learn: 0.0937876	total: 5.35s	remaining: 25.9s
171:	learn: 0.0937024	total: 5.4s	remaining: 26s
172:	learn: 0.0935221	total: 5.43s	remaining: 26s
173:	learn: 0.0934349	total: 5.46s	remaining: 25.9s
174:	learn: 0.0932749	total: 5.49s	remaining: 25.9s
175:	learn: 0.0931454	total: 5.52s	remaining: 25.9s
176:	learn: 0.0930674	total: 5.55s	remaining: 25.8s
177:	learn: 0.0928550	total: 5.59s	remaining: 25.8s
178:	learn: 0.0926688	total: 5.62s	remaining: 25.8s
179:	learn: 0.0924474	total: 5.64s	remaining: 25.7s
180:	learn: 0.0923775	total: 5.69s	remaining: 25.8s
181:	learn: 0.0921109	total: 5.73s	remaining: 25.8s
182:	learn: 0.0919512	total: 5.76s	remaining: 25.7s
183:	learn: 0.0918033	total: 5.79s	remaining: 25.7s
184:	learn: 0.0916231	total: 5.82s	remaining: 25.7s
185:	learn: 0.0914497	total: 5.85s	remaining: 25.6s
186:	learn: 0.0913539	total: 5.88s	remaining: 25.6s
187:	learn: 0.0911778	total: 5.92s	remaining: 25.6s
188:	learn: 0.0909052	total: 5.95s	remaining: 25.5s
189:	learn: 0.0908018	total: 5.98s	remaining: 25.5s
190:	learn: 0.0906367	total: 6.01s	remaining: 25.5s
191:	learn: 0.0905698	total: 6.04s	remaining: 25.4s
192:	learn: 0.0903358	total: 6.07s	remaining: 25.4s
193:	learn: 0.0901538	total: 6.1s	remaining: 25.3s
194:	learn: 0.0900542	total: 6.13s	remaining: 25.3s
195:	learn: 0.0899627	total: 6.16s	remaining: 25.3s
196:	learn: 0.0898597	total: 6.19s	remaining: 25.2s
197:	learn: 0.0897088	total: 6.22s	remaining: 25.2s
198:	learn: 0.0895861	total: 6.25s	remaining: 25.2s
199:	learn: 0.0893939	total: 6.28s	remaining: 25.1s
200:	learn: 0.0892251	total: 6.31s	remaining: 25.1s
201:	learn: 0.0890868	total: 6.34s	remaining: 25s
202:	learn: 0.0889198	total: 6.37s	remaining: 25s
203:	learn: 0.0888054	total: 6.4s	remaining: 25s
204:	learn: 0.0886275	total: 6.44s	remaining: 25s
205:	learn: 0.0884701	total: 6.47s	remaining: 25s
206:	learn: 0.0883398	total: 6.51s	remaining: 24.9s
207:	learn: 0.0881437	total: 6.54s	remaining: 24.9s
208:	learn: 0.0879921	total: 6.58s	remaining: 24.9s
209:	learn: 0.0878846	total: 6.61s	remaining: 24.9s
210:	learn: 0.0877014	total: 6.64s	remaining: 24.8s
211:	learn: 0.0875451	total: 6.67s	remaining: 24.8s
212:	learn: 0.0874780	total: 6.7s	remaining: 24.8s
213:	learn: 0.0873738	total: 6.73s	remaining: 24.7s
214:	learn: 0.0872527	total: 6.76s	remaining: 24.7s
215:	learn: 0.0871540	total: 6.79s	remaining: 24.7s
216:	learn: 0.0869505	total: 6.83s	remaining: 24.6s
217:	learn: 0.0868056	total: 6.86s	remaining: 24.6s
218:	learn: 0.0867292	total: 6.89s	remaining: 24.6s
219:	learn: 0.0866172	total: 6.92s	remaining: 24.5s
220:	learn: 0.0864918	total: 6.95s	remaining: 24.5s
221:	learn: 0.0863035	total: 6.98s	remaining: 24.5s
222:	learn: 0.0861003	total: 7.01s	remaining: 24.4s
223:	learn: 0.0858938	total: 7.04s	remaining: 24.4s
224:	learn: 0.0857229	total: 7.07s	remaining: 24.4s
225:	learn: 0.0856272	total: 7.1s	remaining: 24.3s
226:	learn: 0.0854962	total: 7.13s	remaining: 24.3s
227:	learn: 0.0853588	total: 7.17s	remaining: 24.3s
228:	learn: 0.0852723	total: 7.2s	remaining: 24.2s
229:	learn: 0.0851618	total: 7.22s	remaining: 24.2s
230:	learn: 0.0850220	total: 7.26s	remaining: 24.2s
231:	learn: 0.0849954	total: 7.29s	remaining: 24.1s
232:	learn: 0.0848819	total: 7.32s	remaining: 24.1s
233:	learn: 0.0847281	total: 7.35s	remaining: 24.1s
234:	learn: 0.0846043	total: 7.38s	remaining: 24s
235:	learn: 0.0845662	total: 7.41s	remaining: 24s
236:	learn: 0.0844285	total: 7.44s	remaining: 24s
237:	learn: 0.0842653	total: 7.47s	remaining: 23.9s
238:	learn: 0.0841309	total: 7.51s	remaining: 23.9s
239:	learn: 0.0840735	total: 7.54s	remaining: 23.9s
240:	learn: 0.0839569	total: 7.58s	remaining: 23.9s
241:	learn: 0.0837623	total: 7.61s	remaining: 23.8s
242:	learn: 0.0836980	total: 7.64s	remaining: 23.8s
243:	learn: 0.0835350	total: 7.67s	remaining: 23.8s
244:	learn: 0.0834669	total: 7.7s	remaining: 23.7s
245:	learn: 0.0833245	total: 7.73s	remaining: 23.7s
246:	learn: 0.0832438	total: 7.76s	remaining: 23.7s
247:	learn: 0.0830162	total: 7.79s	remaining: 23.6s
248:	learn: 0.0828883	total: 7.83s	remaining: 23.6s
249:	learn: 0.0828449	total: 7.87s	remaining: 23.6s
250:	learn: 0.0827251	total: 7.9s	remaining: 23.6s
251:	learn: 0.0825332	total: 7.92s	remaining: 23.5s
252:	learn: 0.0824863	total: 7.95s	remaining: 23.5s
253:	learn: 0.0823161	total: 7.98s	remaining: 23.4s
254:	learn: 0.0821999	total: 8.02s	remaining: 23.4s
255:	learn: 0.0821437	total: 8.04s	remaining: 23.4s
256:	learn: 0.0820329	total: 8.07s	remaining: 23.3s
257:	learn: 0.0819180	total: 8.1s	remaining: 23.3s
258:	learn: 0.0818701	total: 8.13s	remaining: 23.3s
259:	learn: 0.0816891	total: 8.17s	remaining: 23.2s
260:	learn: 0.0816187	total: 8.2s	remaining: 23.2s
261:	learn: 0.0815485	total: 8.23s	remaining: 23.2s
262:	learn: 0.0813818	total: 8.26s	remaining: 23.1s
263:	learn: 0.0812336	total: 8.29s	remaining: 23.1s
264:	learn: 0.0811690	total: 8.33s	remaining: 23.1s
265:	learn: 0.0810681	total: 8.36s	remaining: 23.1s
266:	learn: 0.0808829	total: 8.39s	remaining: 23s
267:	learn: 0.0807382	total: 8.42s	remaining: 23s
268:	learn: 0.0805836	total: 8.46s	remaining: 23s
269:	learn: 0.0804766	total: 8.49s	remaining: 22.9s
270:	learn: 0.0803821	total: 8.52s	remaining: 22.9s
271:	learn: 0.0803443	total: 8.55s	remaining: 22.9s
272:	learn: 0.0803162	total: 8.58s	remaining: 22.9s
273:	learn: 0.0802878	total: 8.61s	remaining: 22.8s
274:	learn: 0.0801461	total: 8.65s	remaining: 22.8s
275:	learn: 0.0800032	total: 8.68s	remaining: 22.8s
276:	learn: 0.0799601	total: 8.71s	remaining: 22.7s
277:	learn: 0.0798476	total: 8.74s	remaining: 22.7s
278:	learn: 0.0797747	total: 8.77s	remaining: 22.7s
279:	learn: 0.0796664	total: 8.8s	remaining: 22.6s
280:	learn: 0.0796185	total: 8.84s	remaining: 22.6s
281:	learn: 0.0795176	total: 8.87s	remaining: 22.6s
282:	learn: 0.0793338	total: 8.9s	remaining: 22.5s
283:	learn: 0.0792831	total: 8.93s	remaining: 22.5s
284:	learn: 0.0792116	total: 8.96s	remaining: 22.5s
285:	learn: 0.0790993	total: 8.99s	remaining: 22.4s
286:	learn: 0.0790308	total: 9.02s	remaining: 22.4s
287:	learn: 0.0789292	total: 9.05s	remaining: 22.4s
288:	learn: 0.0788384	total: 9.08s	remaining: 22.3s
289:	learn: 0.0786699	total: 9.11s	remaining: 22.3s
290:	learn: 0.0785386	total: 9.14s	remaining: 22.3s
291:	learn: 0.0784491	total: 9.17s	remaining: 22.2s
292:	learn: 0.0783560	total: 9.2s	remaining: 22.2s
293:	learn: 0.0782621	total: 9.23s	remaining: 22.2s
294:	learn: 0.0782010	total: 9.26s	remaining: 22.1s
295:	learn: 0.0781177	total: 9.29s	remaining: 22.1s
296:	learn: 0.0779460	total: 9.32s	remaining: 22.1s
297:	learn: 0.0779201	total: 9.35s	remaining: 22s
298:	learn: 0.0778401	total: 9.39s	remaining: 22s
299:	learn: 0.0777117	total: 9.42s	remaining: 22s
300:	learn: 0.0776658	total: 9.45s	remaining: 21.9s
301:	learn: 0.0776260	total: 9.48s	remaining: 21.9s
302:	learn: 0.0776074	total: 9.51s	remaining: 21.9s
303:	learn: 0.0773626	total: 9.54s	remaining: 21.8s
304:	learn: 0.0772587	total: 9.57s	remaining: 21.8s
305:	learn: 0.0771179	total: 9.6s	remaining: 21.8s
306:	learn: 0.0770041	total: 9.63s	remaining: 21.7s
307:	learn: 0.0769326	total: 9.66s	remaining: 21.7s
308:	learn: 0.0768800	total: 9.7s	remaining: 21.7s
309:	learn: 0.0768357	total: 9.73s	remaining: 21.6s
310:	learn: 0.0767534	total: 9.76s	remaining: 21.6s
311:	learn: 0.0765552	total: 9.79s	remaining: 21.6s
312:	learn: 0.0764175	total: 9.83s	remaining: 21.6s
313:	learn: 0.0763294	total: 9.86s	remaining: 21.6s
314:	learn: 0.0762049	total: 9.89s	remaining: 21.5s
315:	learn: 0.0761145	total: 9.93s	remaining: 21.5s
316:	learn: 0.0760593	total: 9.96s	remaining: 21.5s
317:	learn: 0.0760137	total: 10s	remaining: 21.5s
318:	learn: 0.0759239	total: 10s	remaining: 21.4s
319:	learn: 0.0759027	total: 10.1s	remaining: 21.4s
320:	learn: 0.0758582	total: 10.1s	remaining: 21.4s
321:	learn: 0.0757446	total: 10.1s	remaining: 21.4s
322:	learn: 0.0756401	total: 10.2s	remaining: 21.3s
323:	learn: 0.0756029	total: 10.2s	remaining: 21.3s
324:	learn: 0.0755015	total: 10.2s	remaining: 21.3s
325:	learn: 0.0752923	total: 10.3s	remaining: 21.2s
326:	learn: 0.0751864	total: 10.3s	remaining: 21.2s
327:	learn: 0.0751681	total: 10.3s	remaining: 21.2s
328:	learn: 0.0750765	total: 10.4s	remaining: 21.1s
329:	learn: 0.0750468	total: 10.4s	remaining: 21.1s
330:	learn: 0.0749348	total: 10.4s	remaining: 21.1s
331:	learn: 0.0748601	total: 10.5s	remaining: 21s
332:	learn: 0.0747451	total: 10.5s	remaining: 21s
333:	learn: 0.0746837	total: 10.5s	remaining: 21s
334:	learn: 0.0745605	total: 10.5s	remaining: 20.9s
335:	learn: 0.0745438	total: 10.6s	remaining: 20.9s
336:	learn: 0.0744936	total: 10.6s	remaining: 20.9s
337:	learn: 0.0744691	total: 10.6s	remaining: 20.8s
338:	learn: 0.0743309	total: 10.7s	remaining: 20.8s
339:	learn: 0.0742929	total: 10.7s	remaining: 20.8s
340:	learn: 0.0742717	total: 10.7s	remaining: 20.7s
341:	learn: 0.0741409	total: 10.8s	remaining: 20.7s
342:	learn: 0.0740992	total: 10.8s	remaining: 20.7s
343:	learn: 0.0740775	total: 10.8s	remaining: 20.6s
344:	learn: 0.0739998	total: 10.9s	remaining: 20.6s
345:	learn: 0.0739107	total: 10.9s	remaining: 20.6s
346:	learn: 0.0738422	total: 10.9s	remaining: 20.5s
347:	learn: 0.0738017	total: 10.9s	remaining: 20.5s
348:	learn: 0.0736778	total: 11s	remaining: 20.5s
349:	learn: 0.0735668	total: 11s	remaining: 20.5s
350:	learn: 0.0734112	total: 11s	remaining: 20.4s
351:	learn: 0.0732972	total: 11.1s	remaining: 20.4s
352:	learn: 0.0732736	total: 11.1s	remaining: 20.4s
353:	learn: 0.0732124	total: 11.1s	remaining: 20.3s
354:	learn: 0.0731025	total: 11.2s	remaining: 20.3s
355:	learn: 0.0730500	total: 11.2s	remaining: 20.3s
356:	learn: 0.0730372	total: 11.2s	remaining: 20.2s
357:	learn: 0.0730215	total: 11.3s	remaining: 20.2s
358:	learn: 0.0729658	total: 11.3s	remaining: 20.2s
359:	learn: 0.0728489	total: 11.3s	remaining: 20.2s
360:	learn: 0.0727042	total: 11.4s	remaining: 20.1s
361:	learn: 0.0726700	total: 11.4s	remaining: 20.1s
362:	learn: 0.0726265	total: 11.4s	remaining: 20.1s
363:	learn: 0.0725109	total: 11.5s	remaining: 20.1s
364:	learn: 0.0724509	total: 11.5s	remaining: 20s
365:	learn: 0.0723908	total: 11.5s	remaining: 20s
366:	learn: 0.0723635	total: 11.6s	remaining: 19.9s
367:	learn: 0.0723261	total: 11.6s	remaining: 19.9s
368:	learn: 0.0722178	total: 11.6s	remaining: 19.9s
369:	learn: 0.0721169	total: 11.7s	remaining: 19.9s
370:	learn: 0.0720037	total: 11.7s	remaining: 19.8s
371:	learn: 0.0718785	total: 11.7s	remaining: 19.8s
372:	learn: 0.0718585	total: 11.8s	remaining: 19.8s
373:	learn: 0.0718367	total: 11.8s	remaining: 19.7s
374:	learn: 0.0717912	total: 11.8s	remaining: 19.7s
375:	learn: 0.0716833	total: 11.8s	remaining: 19.7s
376:	learn: 0.0715684	total: 11.9s	remaining: 19.6s
377:	learn: 0.0715092	total: 11.9s	remaining: 19.6s
378:	learn: 0.0713624	total: 12s	remaining: 19.6s
379:	learn: 0.0712833	total: 12s	remaining: 19.5s
380:	learn: 0.0712681	total: 12s	remaining: 19.5s
381:	learn: 0.0711704	total: 12s	remaining: 19.5s
382:	learn: 0.0710755	total: 12.1s	remaining: 19.4s
383:	learn: 0.0709792	total: 12.1s	remaining: 19.4s
384:	learn: 0.0708649	total: 12.1s	remaining: 19.4s
385:	learn: 0.0708368	total: 12.2s	remaining: 19.3s
386:	learn: 0.0708164	total: 12.2s	remaining: 19.3s
387:	learn: 0.0707020	total: 12.2s	remaining: 19.3s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'MiscFeature': 1 unseen categories converted to Unseen on transform.

CV folds:  24%|██▍       | 12/50 [06:18<20:00, 31.59s/fold]

997:	learn: 0.0436299	total: 31s	remaining: 62.1ms
998:	learn: 0.0436159	total: 31s	remaining: 31.1ms
999:	learn: 0.0435747	total: 31.1s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3855061	total: 29.6ms	remaining: 29.6s
1:	learn: 0.3744956	total: 61.3ms	remaining: 30.6s
2:	learn: 0.3639033	total: 90.2ms	remaining: 30s
3:	learn: 0.3539859	total: 139ms	remaining: 34.5s
4:	learn: 0.3446968	total: 165ms	remaining: 32.9s
5:	learn: 0.3360228	total: 229ms	remaining: 37.9s
6:	learn: 0.3272414	total: 264ms	remaining: 37.5s
7:	learn: 0.3193929	total: 291ms	remaining: 36.1s
8:	learn: 0.3111670	total: 317ms	remaining: 34.9s
9:	learn: 0.3033829	total: 344ms	remaining: 34s
10:	learn: 0.2955578	total: 368ms	remaining: 33.1s
11:	learn: 0.2890354	total: 393ms	remaining: 32.4s
12:	learn: 0.2821145	total: 420ms	remaining: 31.9s
13:	learn: 0.2760866	total: 444ms	remaining: 31.3s
14:	learn: 0.2698973	total: 473ms	remaining: 31.1s
15:	learn: 0.2639786	total: 502ms	remaining: 30.9s
16:	learn: 0.2581932	total: 531ms	remaining: 30.7s
17:	learn: 0.2525185	total: 560ms	remaining: 30.6s
18:	learn: 0.2466716	total: 585ms	remaining: 30.2s
19:	learn: 0.2417187	total: 609ms	remaining: 29.8s
20:	learn: 0.2366119	total: 633ms	remaining: 29.5s
21:	learn: 0.2317105	total: 659ms	remaining: 29.3s
22:	learn: 0.2269363	total: 685ms	remaining: 29.1s
23:	learn: 0.2224407	total: 712ms	remaining: 28.9s
24:	learn: 0.2184816	total: 738ms	remaining: 28.8s
25:	learn: 0.2144760	total: 764ms	remaining: 28.6s
26:	learn: 0.2107546	total: 791ms	remaining: 28.5s
27:	learn: 0.2075720	total: 817ms	remaining: 28.3s
28:	learn: 0.2040108	total: 842ms	remaining: 28.2s
29:	learn: 0.2006538	total: 877ms	remaining: 28.3s
30:	learn: 0.1975453	total: 907ms	remaining: 28.3s
31:	learn: 0.1942041	total: 936ms	remaining: 28.3s
32:	learn: 0.1910541	total: 971ms	remaining: 28.4s
33:	learn: 0.1878846	total: 1.01s	remaining: 28.7s
34:	learn: 0.1850961	total: 1.04s	remaining: 28.7s
35:	learn: 0.1825578	total: 1.07s	remaining: 28.8s
36:	learn: 0.1799151	total: 1.1s	remaining: 28.8s
37:	learn: 0.1773040	total: 1.14s	remaining: 28.9s
38:	learn: 0.1750137	total: 1.17s	remaining: 28.8s
39:	learn: 0.1728271	total: 1.2s	remaining: 28.8s
40:	learn: 0.1704543	total: 1.23s	remaining: 28.7s
41:	learn: 0.1680561	total: 1.26s	remaining: 28.7s
42:	learn: 0.1662157	total: 1.28s	remaining: 28.6s
43:	learn: 0.1642379	total: 1.31s	remaining: 28.6s
44:	learn: 0.1622808	total: 1.35s	remaining: 28.6s
45:	learn: 0.1606159	total: 1.38s	remaining: 28.6s
46:	learn: 0.1587547	total: 1.41s	remaining: 28.5s
47:	learn: 0.1568265	total: 1.43s	remaining: 28.4s
48:	learn: 0.1550404	total: 1.47s	remaining: 28.5s
49:	learn: 0.1535153	total: 1.5s	remaining: 28.4s
50:	learn: 0.1520574	total: 1.53s	remaining: 28.4s
51:	learn: 0.1506077	total: 1.56s	remaining: 28.4s
52:	learn: 0.1493712	total: 1.59s	remaining: 28.4s
53:	learn: 0.1481406	total: 1.62s	remaining: 28.4s
54:	learn: 0.1467600	total: 1.65s	remaining: 28.4s
55:	learn: 0.1454723	total: 1.68s	remaining: 28.4s
56:	learn: 0.1441373	total: 1.71s	remaining: 28.4s
57:	learn: 0.1429203	total: 1.74s	remaining: 28.3s
58:	learn: 0.1417365	total: 1.78s	remaining: 28.3s
59:	learn: 0.1406133	total: 1.81s	remaining: 28.3s
60:	learn: 0.1395235	total: 1.84s	remaining: 28.3s
61:	learn: 0.1383775	total: 1.87s	remaining: 28.3s
62:	learn: 0.1373554	total: 1.9s	remaining: 28.2s
63:	learn: 0.1365559	total: 1.93s	remaining: 28.2s
64:	learn: 0.1354584	total: 1.95s	remaining: 28.1s
65:	learn: 0.1345709	total: 1.98s	remaining: 28s
66:	learn: 0.1335642	total: 2.01s	remaining: 28s
67:	learn: 0.1326682	total: 2.04s	remaining: 27.9s
68:	learn: 0.1318301	total: 2.06s	remaining: 27.8s
69:	learn: 0.1309200	total: 2.09s	remaining: 27.8s
70:	learn: 0.1300894	total: 2.14s	remaining: 28s
71:	learn: 0.1293286	total: 2.17s	remaining: 27.9s
72:	learn: 0.1286330	total: 2.2s	remaining: 27.9s
73:	learn: 0.1278847	total: 2.23s	remaining: 27.9s
74:	learn: 0.1271315	total: 2.26s	remaining: 27.9s
75:	learn: 0.1265353	total: 2.29s	remaining: 27.8s
76:	learn: 0.1259302	total: 2.32s	remaining: 27.8s
77:	learn: 0.1252853	total: 2.35s	remaining: 27.8s
78:	learn: 0.1247301	total: 2.39s	remaining: 27.9s
79:	learn: 0.1241299	total: 2.42s	remaining: 27.8s
80:	learn: 0.1235080	total: 2.45s	remaining: 27.8s
81:	learn: 0.1229855	total: 2.48s	remaining: 27.8s
82:	learn: 0.1224992	total: 2.51s	remaining: 27.8s
83:	learn: 0.1220154	total: 2.55s	remaining: 27.8s
84:	learn: 0.1215547	total: 2.58s	remaining: 27.8s
85:	learn: 0.1208911	total: 2.6s	remaining: 27.7s
86:	learn: 0.1203678	total: 2.63s	remaining: 27.6s
87:	learn: 0.1199170	total: 2.66s	remaining: 27.6s
88:	learn: 0.1194230	total: 2.69s	remaining: 27.6s
89:	learn: 0.1189256	total: 2.72s	remaining: 27.5s
90:	learn: 0.1183313	total: 2.75s	remaining: 27.5s
91:	learn: 0.1179042	total: 2.78s	remaining: 27.4s
92:	learn: 0.1175216	total: 2.8s	remaining: 27.3s
93:	learn: 0.1171563	total: 2.83s	remaining: 27.3s
94:	learn: 0.1167850	total: 2.86s	remaining: 27.2s
95:	learn: 0.1163762	total: 2.89s	remaining: 27.2s
96:	learn: 0.1158374	total: 2.92s	remaining: 27.2s
97:	learn: 0.1155495	total: 2.96s	remaining: 27.2s
98:	learn: 0.1151335	total: 2.98s	remaining: 27.1s
99:	learn: 0.1147961	total: 3.01s	remaining: 27.1s
100:	learn: 0.1144293	total: 3.03s	remaining: 27s
101:	learn: 0.1140860	total: 3.06s	remaining: 26.9s
102:	learn: 0.1138238	total: 3.09s	remaining: 26.9s
103:	learn: 0.1135839	total: 3.11s	remaining: 26.8s
104:	learn: 0.1132783	total: 3.14s	remaining: 26.8s
105:	learn: 0.1129320	total: 3.18s	remaining: 26.8s
106:	learn: 0.1125950	total: 3.21s	remaining: 26.8s
107:	learn: 0.1122400	total: 3.25s	remaining: 26.8s
108:	learn: 0.1119314	total: 3.28s	remaining: 26.8s
109:	learn: 0.1116627	total: 3.31s	remaining: 26.8s
110:	learn: 0.1113971	total: 3.35s	remaining: 26.8s
111:	learn: 0.1111787	total: 3.38s	remaining: 26.8s
112:	learn: 0.1109954	total: 3.42s	remaining: 26.8s
113:	learn: 0.1107060	total: 3.45s	remaining: 26.8s
114:	learn: 0.1103561	total: 3.48s	remaining: 26.8s
115:	learn: 0.1100785	total: 3.51s	remaining: 26.7s
116:	learn: 0.1098722	total: 3.54s	remaining: 26.7s
117:	learn: 0.1095678	total: 3.57s	remaining: 26.7s
118:	learn: 0.1092893	total: 3.6s	remaining: 26.6s
119:	learn: 0.1089420	total: 3.63s	remaining: 26.6s
120:	learn: 0.1086392	total: 3.66s	remaining: 26.6s
121:	learn: 0.1083910	total: 3.68s	remaining: 26.5s
122:	learn: 0.1079913	total: 3.71s	remaining: 26.5s
123:	learn: 0.1077361	total: 3.74s	remaining: 26.4s
124:	learn: 0.1073611	total: 3.77s	remaining: 26.4s
125:	learn: 0.1071327	total: 3.8s	remaining: 26.4s
126:	learn: 0.1067287	total: 3.84s	remaining: 26.4s
127:	learn: 0.1064286	total: 3.87s	remaining: 26.4s
128:	learn: 0.1061486	total: 3.9s	remaining: 26.4s
129:	learn: 0.1058911	total: 3.94s	remaining: 26.4s
130:	learn: 0.1055343	total: 3.97s	remaining: 26.3s
131:	learn: 0.1052274	total: 4s	remaining: 26.3s
132:	learn: 0.1048615	total: 4.04s	remaining: 26.3s
133:	learn: 0.1046566	total: 4.07s	remaining: 26.3s
134:	learn: 0.1045226	total: 4.1s	remaining: 26.3s
135:	learn: 0.1043662	total: 4.13s	remaining: 26.3s
136:	learn: 0.1041820	total: 4.18s	remaining: 26.4s
137:	learn: 0.1039381	total: 4.23s	remaining: 26.4s
138:	learn: 0.1036843	total: 4.26s	remaining: 26.4s
139:	learn: 0.1034882	total: 4.29s	remaining: 26.4s
140:	learn: 0.1033769	total: 4.32s	remaining: 26.3s
141:	learn: 0.1031190	total: 4.35s	remaining: 26.3s
142:	learn: 0.1028342	total: 4.38s	remaining: 26.2s
143:	learn: 0.1027392	total: 4.41s	remaining: 26.2s
144:	learn: 0.1025598	total: 4.43s	remaining: 26.2s
145:	learn: 0.1024262	total: 4.46s	remaining: 26.1s
146:	learn: 0.1023144	total: 4.5s	remaining: 26.1s
147:	learn: 0.1020796	total: 4.55s	remaining: 26.2s
148:	learn: 0.1018417	total: 4.58s	remaining: 26.2s
149:	learn: 0.1016733	total: 4.61s	remaining: 26.1s
150:	learn: 0.1014643	total: 4.65s	remaining: 26.1s
151:	learn: 0.1013222	total: 4.68s	remaining: 26.1s
152:	learn: 0.1010881	total: 4.72s	remaining: 26.1s
153:	learn: 0.1007909	total: 4.75s	remaining: 26.1s
154:	learn: 0.1006999	total: 4.79s	remaining: 26.1s
155:	learn: 0.1004767	total: 4.82s	remaining: 26.1s
156:	learn: 0.1003056	total: 4.86s	remaining: 26.1s
157:	learn: 0.1001874	total: 4.89s	remaining: 26.1s
158:	learn: 0.0999467	total: 4.92s	remaining: 26s
159:	learn: 0.0997843	total: 4.95s	remaining: 26s
160:	learn: 0.0995631	total: 4.99s	remaining: 26s
161:	learn: 0.0993820	total: 5.01s	remaining: 25.9s
162:	learn: 0.0990859	total: 5.04s	remaining: 25.9s
163:	learn: 0.0988853	total: 5.08s	remaining: 25.9s
164:	learn: 0.0987765	total: 5.11s	remaining: 25.9s
165:	learn: 0.0983995	total: 5.14s	remaining: 25.8s
166:	learn: 0.0981893	total: 5.18s	remaining: 25.8s
167:	learn: 0.0980211	total: 5.21s	remaining: 25.8s
168:	learn: 0.0977121	total: 5.24s	remaining: 25.8s
169:	learn: 0.0974550	total: 5.27s	remaining: 25.7s
170:	learn: 0.0973340	total: 5.31s	remaining: 25.7s
171:	learn: 0.0971951	total: 5.34s	remaining: 25.7s
172:	learn: 0.0969023	total: 5.38s	remaining: 25.7s
173:	learn: 0.0967616	total: 5.41s	remaining: 25.7s
174:	learn: 0.0964696	total: 5.44s	remaining: 25.6s
175:	learn: 0.0963255	total: 5.47s	remaining: 25.6s
176:	learn: 0.0960410	total: 5.5s	remaining: 25.6s
177:	learn: 0.0957863	total: 5.53s	remaining: 25.5s
178:	learn: 0.0955902	total: 5.56s	remaining: 25.5s
179:	learn: 0.0953444	total: 5.58s	remaining: 25.4s
180:	learn: 0.0952434	total: 5.61s	remaining: 25.4s
181:	learn: 0.0951263	total: 5.64s	remaining: 25.4s
182:	learn: 0.0949214	total: 5.67s	remaining: 25.3s
183:	learn: 0.0947146	total: 5.71s	remaining: 25.3s
184:	learn: 0.0944284	total: 5.74s	remaining: 25.3s
185:	learn: 0.0942516	total: 5.78s	remaining: 25.3s
186:	learn: 0.0941663	total: 5.81s	remaining: 25.3s
187:	learn: 0.0940026	total: 5.85s	remaining: 25.3s
188:	learn: 0.0938744	total: 5.89s	remaining: 25.3s
189:	learn: 0.0937164	total: 5.92s	remaining: 25.2s
190:	learn: 0.0934338	total: 5.95s	remaining: 25.2s
191:	learn: 0.0933137	total: 5.98s	remaining: 25.2s
192:	learn: 0.0932411	total: 6.01s	remaining: 25.1s
193:	learn: 0.0930587	total: 6.04s	remaining: 25.1s
194:	learn: 0.0929603	total: 6.07s	remaining: 25s
195:	learn: 0.0927793	total: 6.1s	remaining: 25s
196:	learn: 0.0925496	total: 6.13s	remaining: 25s
197:	learn: 0.0923995	total: 6.16s	remaining: 25s
198:	learn: 0.0922316	total: 6.2s	remaining: 25s
199:	learn: 0.0920932	total: 6.23s	remaining: 24.9s
200:	learn: 0.0919574	total: 6.27s	remaining: 24.9s
201:	learn: 0.0917235	total: 6.3s	remaining: 24.9s
202:	learn: 0.0916594	total: 6.33s	remaining: 24.9s
203:	learn: 0.0915430	total: 6.36s	remaining: 24.8s
204:	learn: 0.0914280	total: 6.39s	remaining: 24.8s
205:	learn: 0.0912640	total: 6.42s	remaining: 24.8s
206:	learn: 0.0911633	total: 6.45s	remaining: 24.7s
207:	learn: 0.0911078	total: 6.49s	remaining: 24.7s
208:	learn: 0.0910289	total: 6.52s	remaining: 24.7s
209:	learn: 0.0907847	total: 6.56s	remaining: 24.7s
210:	learn: 0.0907269	total: 6.59s	remaining: 24.6s
211:	learn: 0.0904958	total: 6.62s	remaining: 24.6s
212:	learn: 0.0904626	total: 6.65s	remaining: 24.6s
213:	learn: 0.0902750	total: 6.68s	remaining: 24.6s
214:	learn: 0.0902270	total: 6.72s	remaining: 24.5s
215:	learn: 0.0901458	total: 6.75s	remaining: 24.5s
216:	learn: 0.0900416	total: 6.78s	remaining: 24.5s
217:	learn: 0.0900031	total: 6.82s	remaining: 24.5s
218:	learn: 0.0898979	total: 6.85s	remaining: 24.4s
219:	learn: 0.0897067	total: 6.88s	remaining: 24.4s
220:	learn: 0.0895963	total: 6.92s	remaining: 24.4s
221:	learn: 0.0894814	total: 6.95s	remaining: 24.4s
222:	learn: 0.0893741	total: 6.98s	remaining: 24.3s
223:	learn: 0.0892634	total: 7.01s	remaining: 24.3s
224:	learn: 0.0891634	total: 7.04s	remaining: 24.3s
225:	learn: 0.0890139	total: 7.07s	remaining: 24.2s
226:	learn: 0.0888384	total: 7.1s	remaining: 24.2s
227:	learn: 0.0887145	total: 7.13s	remaining: 24.1s
228:	learn: 0.0886428	total: 7.17s	remaining: 24.1s
229:	learn: 0.0885049	total: 7.2s	remaining: 24.1s
230:	learn: 0.0884549	total: 7.23s	remaining: 24.1s
231:	learn: 0.0882953	total: 7.26s	remaining: 24s
232:	learn: 0.0882429	total: 7.3s	remaining: 24s
233:	learn: 0.0881959	total: 7.33s	remaining: 24s
234:	learn: 0.0881072	total: 7.36s	remaining: 24s
235:	learn: 0.0879505	total: 7.39s	remaining: 23.9s
236:	learn: 0.0876783	total: 7.42s	remaining: 23.9s
237:	learn: 0.0876451	total: 7.45s	remaining: 23.9s
238:	learn: 0.0873798	total: 7.48s	remaining: 23.8s
239:	learn: 0.0871974	total: 7.51s	remaining: 23.8s
240:	learn: 0.0869677	total: 7.55s	remaining: 23.8s
241:	learn: 0.0868330	total: 7.59s	remaining: 23.8s
242:	learn: 0.0867319	total: 7.62s	remaining: 23.7s
243:	learn: 0.0866332	total: 7.65s	remaining: 23.7s
244:	learn: 0.0863233	total: 7.69s	remaining: 23.7s
245:	learn: 0.0859774	total: 7.73s	remaining: 23.7s
246:	learn: 0.0859313	total: 7.76s	remaining: 23.7s
247:	learn: 0.0856698	total: 7.79s	remaining: 23.6s
248:	learn: 0.0853577	total: 7.83s	remaining: 23.6s
249:	learn: 0.0853157	total: 7.86s	remaining: 23.6s
250:	learn: 0.0851072	total: 7.89s	remaining: 23.5s
251:	learn: 0.0850203	total: 7.92s	remaining: 23.5s
252:	learn: 0.0849877	total: 7.95s	remaining: 23.5s
253:	learn: 0.0848373	total: 7.99s	remaining: 23.5s
254:	learn: 0.0846530	total: 8.02s	remaining: 23.4s
255:	learn: 0.0845205	total: 8.05s	remaining: 23.4s
256:	learn: 0.0843357	total: 8.09s	remaining: 23.4s
257:	learn: 0.0843002	total: 8.12s	remaining: 23.4s
258:	learn: 0.0842366	total: 8.15s	remaining: 23.3s
259:	learn: 0.0841594	total: 8.19s	remaining: 23.3s
260:	learn: 0.0839514	total: 8.22s	remaining: 23.3s
261:	learn: 0.0838962	total: 8.25s	remaining: 23.2s
262:	learn: 0.0838689	total: 8.29s	remaining: 23.2s
263:	learn: 0.0837939	total: 8.32s	remaining: 23.2s
264:	learn: 0.0837655	total: 8.35s	remaining: 23.2s
265:	learn: 0.0837240	total: 8.38s	remaining: 23.1s
266:	learn: 0.0835497	total: 8.41s	remaining: 23.1s
267:	learn: 0.0835073	total: 8.43s	remaining: 23s
268:	learn: 0.0834787	total: 8.46s	remaining: 23s
269:	learn: 0.0834438	total: 8.49s	remaining: 23s
270:	learn: 0.0834010	total: 8.52s	remaining: 22.9s
271:	learn: 0.0832930	total: 8.55s	remaining: 22.9s
272:	learn: 0.0832550	total: 8.59s	remaining: 22.9s
273:	learn: 0.0832284	total: 8.62s	remaining: 22.8s
274:	learn: 0.0830429	total: 8.65s	remaining: 22.8s
275:	learn: 0.0829481	total: 8.68s	remaining: 22.8s
276:	learn: 0.0828157	total: 8.71s	remaining: 22.7s
277:	learn: 0.0826035	total: 8.74s	remaining: 22.7s
278:	learn: 0.0825677	total: 8.77s	remaining: 22.7s
279:	learn: 0.0825022	total: 8.8s	remaining: 22.6s
280:	learn: 0.0824128	total: 8.84s	remaining: 22.6s
281:	learn: 0.0821296	total: 8.87s	remaining: 22.6s
282:	learn: 0.0819418	total: 8.89s	remaining: 22.5s
283:	learn: 0.0817576	total: 8.92s	remaining: 22.5s
284:	learn: 0.0816711	total: 8.95s	remaining: 22.5s
285:	learn: 0.0816130	total: 8.98s	remaining: 22.4s
286:	learn: 0.0814991	total: 9.02s	remaining: 22.4s
287:	learn: 0.0814828	total: 9.05s	remaining: 22.4s
288:	learn: 0.0814631	total: 9.07s	remaining: 22.3s
289:	learn: 0.0812491	total: 9.1s	remaining: 22.3s
290:	learn: 0.0812282	total: 9.13s	remaining: 22.3s
291:	learn: 0.0812061	total: 9.16s	remaining: 22.2s
292:	learn: 0.0811373	total: 9.2s	remaining: 22.2s
293:	learn: 0.0810628	total: 9.22s	remaining: 22.1s
294:	learn: 0.0808875	total: 9.25s	remaining: 22.1s
295:	learn: 0.0808642	total: 9.28s	remaining: 22.1s
296:	learn: 0.0807843	total: 9.32s	remaining: 22.1s
297:	learn: 0.0805809	total: 9.35s	remaining: 22s
298:	learn: 0.0805004	total: 9.38s	remaining: 22s
299:	learn: 0.0803851	total: 9.41s	remaining: 22s
300:	learn: 0.0803586	total: 9.44s	remaining: 21.9s
301:	learn: 0.0803243	total: 9.47s	remaining: 21.9s
302:	learn: 0.0802148	total: 9.51s	remaining: 21.9s
303:	learn: 0.0802021	total: 9.54s	remaining: 21.8s
304:	learn: 0.0801858	total: 9.58s	remaining: 21.8s
305:	learn: 0.0799789	total: 9.62s	remaining: 21.8s
306:	learn: 0.0799107	total: 9.65s	remaining: 21.8s
307:	learn: 0.0798615	total: 9.68s	remaining: 21.8s
308:	learn: 0.0797884	total: 9.72s	remaining: 21.7s
309:	learn: 0.0796887	total: 9.75s	remaining: 21.7s
310:	learn: 0.0796558	total: 9.79s	remaining: 21.7s
311:	learn: 0.0796210	total: 9.82s	remaining: 21.7s
312:	learn: 0.0795825	total: 9.86s	remaining: 21.6s
313:	learn: 0.0795381	total: 9.9s	remaining: 21.6s
314:	learn: 0.0794080	total: 9.93s	remaining: 21.6s
315:	learn: 0.0792439	total: 9.97s	remaining: 21.6s
316:	learn: 0.0792245	total: 10s	remaining: 21.5s
317:	learn: 0.0790531	total: 10s	remaining: 21.5s
318:	learn: 0.0789873	total: 10.1s	remaining: 21.5s
319:	learn: 0.0789483	total: 10.1s	remaining: 21.5s
320:	learn: 0.0787636	total: 10.1s	remaining: 21.4s
321:	learn: 0.0787433	total: 10.2s	remaining: 21.4s
322:	learn: 0.0786581	total: 10.2s	remaining: 21.4s
323:	learn: 0.0785576	total: 10.2s	remaining: 21.3s
324:	learn: 0.0784523	total: 10.3s	remaining: 21.3s
325:	learn: 0.0782798	total: 10.3s	remaining: 21.3s
326:	learn: 0.0782648	total: 10.3s	remaining: 21.2s
327:	learn: 0.0781456	total: 10.3s	remaining: 21.2s
328:	learn: 0.0780591	total: 10.4s	remaining: 21.2s
329:	learn: 0.0778764	total: 10.4s	remaining: 21.1s
330:	learn: 0.0776522	total: 10.4s	remaining: 21.1s
331:	learn: 0.0776483	total: 10.5s	remaining: 21.1s
332:	learn: 0.0775099	total: 10.5s	remaining: 21s
333:	learn: 0.0773344	total: 10.5s	remaining: 21s
334:	learn: 0.0773229	total: 10.6s	remaining: 21s
335:	learn: 0.0772176	total: 10.6s	remaining: 20.9s
336:	learn: 0.0770893	total: 10.6s	remaining: 20.9s
337:	learn: 0.0770575	total: 10.7s	remaining: 20.9s
338:	learn: 0.0769440	total: 10.7s	remaining: 20.9s
339:	learn: 0.0769295	total: 10.7s	remaining: 20.8s
340:	learn: 0.0768394	total: 10.8s	remaining: 20.8s
341:	learn: 0.0767936	total: 10.8s	remaining: 20.8s
342:	learn: 0.0767747	total: 10.8s	remaining: 20.7s
343:	learn: 0.0766396	total: 10.8s	remaining: 20.7s
344:	learn: 0.0765341	total: 10.9s	remaining: 20.7s
345:	learn: 0.0764119	total: 10.9s	remaining: 20.6s
346:	learn: 0.0762763	total: 10.9s	remaining: 20.6s
347:	learn: 0.0761952	total: 11s	remaining: 20.6s
348:	learn: 0.0761443	total: 11s	remaining: 20.6s
349:	learn: 0.0761310	total: 11.1s	remaining: 20.5s
350:	learn: 0.0761252	total: 11.1s	remaining: 20.5s
351:	learn: 0.0760373	total: 11.1s	remaining: 20.5s
352:	learn: 0.0760163	total: 11.1s	remaining: 20.4s
353:	learn: 0.0759749	total: 11.2s	remaining: 20.4s
354:	learn: 0.0759047	total: 11.2s	remaining: 20.3s
355:	learn: 0.0757650	total: 11.2s	remaining: 20.3s
356:	learn: 0.0757627	total: 11.3s	remaining: 20.3s
357:	learn: 0.0757455	total: 11.3s	remaining: 20.3s
358:	learn: 0.0756591	total: 11.3s	remaining: 20.2s
359:	learn: 0.0755875	total: 11.4s	remaining: 20.2s
360:	learn: 0.0755118	total: 11.4s	remaining: 20.2s
361:	learn: 0.0754897	total: 11.4s	remaining: 20.1s
362:	learn: 0.0754779	total: 11.5s	remaining: 20.1s
363:	learn: 0.0754691	total: 11.5s	remaining: 20.1s
364:	learn: 0.0754189	total: 11.5s	remaining: 20.1s
365:	learn: 0.0752729	total: 11.6s	remaining: 20s
366:	learn: 0.0751668	total: 11.6s	remaining: 20s
367:	learn: 0.0750752	total: 11.6s	remaining: 20s
368:	learn: 0.0749840	total: 11.7s	remaining: 19.9s
369:	learn: 0.0748408	total: 11.7s	remaining: 19.9s
370:	learn: 0.0748141	total: 11.7s	remaining: 19.9s
371:	learn: 0.0748010	total: 11.8s	remaining: 19.9s
372:	learn: 0.0747090	total: 11.8s	remaining: 19.8s
373:	learn: 0.0746957	total: 11.8s	remaining: 19.8s
374:	learn: 0.0746884	total: 11.9s	remaining: 19.8s
375:	learn: 0.0745154	total: 11.9s	remaining: 19.7s
376:	learn: 0.0744835	total: 11.9s	remaining: 19.7s
377:	learn: 0.0743811	total: 12s	remaining: 19.7s
378:	learn: 0.0742816	total: 12s	remaining: 19.7s
379:	learn: 0.0742185	total: 12s	remaining: 19.6s
380:	learn: 0.0740432	total: 12.1s	remaining: 19.6s
381:	learn: 0.0739638	total: 12.1s	remaining: 19.6s
382:	learn: 0.0739571	total: 12.1s	remaining: 19.5s
383:	learn: 0.0737649	total: 12.2s	remaining: 19.5s
384:	learn: 0.0737504	total: 12.2s	remaining: 19.5s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'ExterCond': 1 unseen categories converted to Unseen on transform.

CV folds:  26%|██▌       | 13/50 [06:49<19:25, 31.49s/fold]

999:	learn: 0.0413426	total: 30.8s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3884551	total: 27.2ms	remaining: 27.2s
1:	learn: 0.3779774	total: 59.9ms	remaining: 29.9s
2:	learn: 0.3674172	total: 91.1ms	remaining: 30.3s
3:	learn: 0.3575046	total: 125ms	remaining: 31.1s
4:	learn: 0.3478280	total: 158ms	remaining: 31.4s
5:	learn: 0.3390928	total: 190ms	remaining: 31.4s
6:	learn: 0.3295733	total: 219ms	remaining: 31.1s
7:	learn: 0.3216468	total: 254ms	remaining: 31.5s
8:	learn: 0.3133915	total: 288ms	remaining: 31.7s
9:	learn: 0.3056862	total: 319ms	remaining: 31.6s
10:	learn: 0.2977632	total: 348ms	remaining: 31.3s
11:	learn: 0.2911727	total: 381ms	remaining: 31.4s
12:	learn: 0.2846263	total: 413ms	remaining: 31.4s
13:	learn: 0.2775957	total: 447ms	remaining: 31.4s
14:	learn: 0.2711763	total: 480ms	remaining: 31.5s
15:	learn: 0.2647699	total: 511ms	remaining: 31.4s
16:	learn: 0.2588031	total: 541ms	remaining: 31.3s
17:	learn: 0.2532642	total: 573ms	remaining: 31.3s
18:	learn: 0.2479260	total: 605ms	remaining: 31.2s
19:	learn: 0.2429456	total: 636ms	remaining: 31.2s
20:	learn: 0.2380506	total: 667ms	remaining: 31.1s
21:	learn: 0.2335136	total: 704ms	remaining: 31.3s
22:	learn: 0.2288717	total: 736ms	remaining: 31.3s
23:	learn: 0.2246506	total: 767ms	remaining: 31.2s
24:	learn: 0.2206158	total: 797ms	remaining: 31.1s
25:	learn: 0.2164922	total: 828ms	remaining: 31s
26:	learn: 0.2128940	total: 856ms	remaining: 30.9s
27:	learn: 0.2091023	total: 888ms	remaining: 30.8s
28:	learn: 0.2049953	total: 923ms	remaining: 30.9s
29:	learn: 0.2014785	total: 955ms	remaining: 30.9s
30:	learn: 0.1979067	total: 988ms	remaining: 30.9s
31:	learn: 0.1948544	total: 1.02s	remaining: 30.9s
32:	learn: 0.1919804	total: 1.05s	remaining: 30.8s
33:	learn: 0.1896751	total: 1.07s	remaining: 30.6s
34:	learn: 0.1868280	total: 1.1s	remaining: 30.5s
35:	learn: 0.1841848	total: 1.14s	remaining: 30.4s
36:	learn: 0.1814450	total: 1.17s	remaining: 30.4s
37:	learn: 0.1789014	total: 1.2s	remaining: 30.4s
38:	learn: 0.1764106	total: 1.23s	remaining: 30.3s
39:	learn: 0.1740738	total: 1.26s	remaining: 30.3s
40:	learn: 0.1719474	total: 1.3s	remaining: 30.4s
41:	learn: 0.1694986	total: 1.33s	remaining: 30.4s
42:	learn: 0.1670215	total: 1.37s	remaining: 30.4s
43:	learn: 0.1649628	total: 1.4s	remaining: 30.4s
44:	learn: 0.1629144	total: 1.43s	remaining: 30.4s
45:	learn: 0.1613542	total: 1.48s	remaining: 30.8s
46:	learn: 0.1595382	total: 1.51s	remaining: 30.7s
47:	learn: 0.1579610	total: 1.54s	remaining: 30.7s
48:	learn: 0.1560343	total: 1.58s	remaining: 30.6s
49:	learn: 0.1542406	total: 1.61s	remaining: 30.6s
50:	learn: 0.1529296	total: 1.64s	remaining: 30.5s
51:	learn: 0.1515087	total: 1.67s	remaining: 30.5s
52:	learn: 0.1501785	total: 1.7s	remaining: 30.4s
53:	learn: 0.1488488	total: 1.73s	remaining: 30.3s
54:	learn: 0.1475196	total: 1.76s	remaining: 30.3s
55:	learn: 0.1462181	total: 1.79s	remaining: 30.2s
56:	learn: 0.1448986	total: 1.82s	remaining: 30.2s
57:	learn: 0.1435344	total: 1.85s	remaining: 30.1s
58:	learn: 0.1424642	total: 1.88s	remaining: 30s
59:	learn: 0.1413917	total: 1.91s	remaining: 29.9s
60:	learn: 0.1401237	total: 1.94s	remaining: 29.9s
61:	learn: 0.1389166	total: 1.98s	remaining: 29.9s
62:	learn: 0.1377418	total: 2.02s	remaining: 30s
63:	learn: 0.1367495	total: 2.05s	remaining: 29.9s
64:	learn: 0.1359534	total: 2.08s	remaining: 29.9s
65:	learn: 0.1348942	total: 2.12s	remaining: 29.9s
66:	learn: 0.1342296	total: 2.15s	remaining: 29.9s
67:	learn: 0.1332468	total: 2.18s	remaining: 29.9s
68:	learn: 0.1323256	total: 2.21s	remaining: 29.9s
69:	learn: 0.1314512	total: 2.24s	remaining: 29.8s
70:	learn: 0.1306878	total: 2.28s	remaining: 29.8s
71:	learn: 0.1299278	total: 2.31s	remaining: 29.8s
72:	learn: 0.1291420	total: 2.35s	remaining: 29.8s
73:	learn: 0.1282845	total: 2.38s	remaining: 29.8s
74:	learn: 0.1276854	total: 2.41s	remaining: 29.7s
75:	learn: 0.1270172	total: 2.44s	remaining: 29.7s
76:	learn: 0.1262921	total: 2.48s	remaining: 29.7s
77:	learn: 0.1256932	total: 2.51s	remaining: 29.7s
78:	learn: 0.1250222	total: 2.54s	remaining: 29.7s
79:	learn: 0.1245541	total: 2.57s	remaining: 29.6s
80:	learn: 0.1240019	total: 2.6s	remaining: 29.6s
81:	learn: 0.1234153	total: 2.64s	remaining: 29.5s
82:	learn: 0.1228482	total: 2.67s	remaining: 29.5s
83:	learn: 0.1222887	total: 2.7s	remaining: 29.5s
84:	learn: 0.1218026	total: 2.73s	remaining: 29.4s
85:	learn: 0.1213816	total: 2.77s	remaining: 29.4s
86:	learn: 0.1208767	total: 2.8s	remaining: 29.4s
87:	learn: 0.1204856	total: 2.83s	remaining: 29.4s
88:	learn: 0.1199634	total: 2.87s	remaining: 29.3s
89:	learn: 0.1194886	total: 2.9s	remaining: 29.3s
90:	learn: 0.1189987	total: 2.93s	remaining: 29.3s
91:	learn: 0.1186284	total: 2.96s	remaining: 29.2s
92:	learn: 0.1181997	total: 2.99s	remaining: 29.2s
93:	learn: 0.1177003	total: 3.03s	remaining: 29.2s
94:	learn: 0.1173816	total: 3.06s	remaining: 29.1s
95:	learn: 0.1169505	total: 3.1s	remaining: 29.2s
96:	learn: 0.1165071	total: 3.13s	remaining: 29.1s
97:	learn: 0.1162269	total: 3.16s	remaining: 29.1s
98:	learn: 0.1159459	total: 3.19s	remaining: 29s
99:	learn: 0.1155929	total: 3.22s	remaining: 29s
100:	learn: 0.1150932	total: 3.25s	remaining: 29s
101:	learn: 0.1146700	total: 3.28s	remaining: 28.9s
102:	learn: 0.1144250	total: 3.32s	remaining: 28.9s
103:	learn: 0.1140805	total: 3.35s	remaining: 28.9s
104:	learn: 0.1137324	total: 3.38s	remaining: 28.9s
105:	learn: 0.1132700	total: 3.42s	remaining: 28.8s
106:	learn: 0.1130735	total: 3.45s	remaining: 28.8s
107:	learn: 0.1127025	total: 3.48s	remaining: 28.8s
108:	learn: 0.1124611	total: 3.52s	remaining: 28.7s
109:	learn: 0.1122682	total: 3.55s	remaining: 28.7s
110:	learn: 0.1119840	total: 3.58s	remaining: 28.7s
111:	learn: 0.1116390	total: 3.63s	remaining: 28.8s
112:	learn: 0.1113851	total: 3.68s	remaining: 28.9s
113:	learn: 0.1110763	total: 3.72s	remaining: 28.9s
114:	learn: 0.1106546	total: 3.75s	remaining: 28.9s
115:	learn: 0.1103351	total: 3.79s	remaining: 28.9s
116:	learn: 0.1101466	total: 3.82s	remaining: 28.8s
117:	learn: 0.1097667	total: 3.85s	remaining: 28.8s
118:	learn: 0.1094002	total: 3.88s	remaining: 28.8s
119:	learn: 0.1088508	total: 3.92s	remaining: 28.7s
120:	learn: 0.1085160	total: 3.95s	remaining: 28.7s
121:	learn: 0.1081172	total: 3.98s	remaining: 28.6s
122:	learn: 0.1078778	total: 4.01s	remaining: 28.6s
123:	learn: 0.1075671	total: 4.04s	remaining: 28.6s
124:	learn: 0.1072307	total: 4.08s	remaining: 28.6s
125:	learn: 0.1070449	total: 4.11s	remaining: 28.5s
126:	learn: 0.1068120	total: 4.15s	remaining: 28.5s
127:	learn: 0.1066800	total: 4.18s	remaining: 28.5s
128:	learn: 0.1063837	total: 4.22s	remaining: 28.5s
129:	learn: 0.1061487	total: 4.25s	remaining: 28.5s
130:	learn: 0.1059538	total: 4.29s	remaining: 28.5s
131:	learn: 0.1057406	total: 4.32s	remaining: 28.4s
132:	learn: 0.1053762	total: 4.36s	remaining: 28.4s
133:	learn: 0.1051929	total: 4.39s	remaining: 28.4s
134:	learn: 0.1049798	total: 4.42s	remaining: 28.4s
135:	learn: 0.1047874	total: 4.46s	remaining: 28.3s
136:	learn: 0.1043906	total: 4.49s	remaining: 28.3s
137:	learn: 0.1041679	total: 4.52s	remaining: 28.2s
138:	learn: 0.1039389	total: 4.55s	remaining: 28.2s
139:	learn: 0.1036931	total: 4.58s	remaining: 28.2s
140:	learn: 0.1034138	total: 4.61s	remaining: 28.1s
141:	learn: 0.1031780	total: 4.65s	remaining: 28.1s
142:	learn: 0.1029014	total: 4.68s	remaining: 28s
143:	learn: 0.1026052	total: 4.71s	remaining: 28s
144:	learn: 0.1023632	total: 4.75s	remaining: 28s
145:	learn: 0.1021875	total: 4.78s	remaining: 27.9s
146:	learn: 0.1018567	total: 4.81s	remaining: 27.9s
147:	learn: 0.1016047	total: 4.84s	remaining: 27.9s
148:	learn: 0.1015306	total: 4.88s	remaining: 27.9s
149:	learn: 0.1012889	total: 4.91s	remaining: 27.8s
150:	learn: 0.1010311	total: 4.95s	remaining: 27.8s
151:	learn: 0.1007362	total: 4.99s	remaining: 27.8s
152:	learn: 0.1005882	total: 5.02s	remaining: 27.8s
153:	learn: 0.1003676	total: 5.06s	remaining: 27.8s
154:	learn: 0.1002570	total: 5.09s	remaining: 27.8s
155:	learn: 0.1000934	total: 5.13s	remaining: 27.7s
156:	learn: 0.0998177	total: 5.16s	remaining: 27.7s
157:	learn: 0.0996971	total: 5.19s	remaining: 27.7s
158:	learn: 0.0995404	total: 5.22s	remaining: 27.6s
159:	learn: 0.0993035	total: 5.26s	remaining: 27.6s
160:	learn: 0.0991574	total: 5.29s	remaining: 27.6s
161:	learn: 0.0989544	total: 5.32s	remaining: 27.5s
162:	learn: 0.0988669	total: 5.35s	remaining: 27.5s
163:	learn: 0.0986463	total: 5.38s	remaining: 27.4s
164:	learn: 0.0984843	total: 5.42s	remaining: 27.4s
165:	learn: 0.0982630	total: 5.45s	remaining: 27.4s
166:	learn: 0.0981405	total: 5.48s	remaining: 27.3s
167:	learn: 0.0979549	total: 5.51s	remaining: 27.3s
168:	learn: 0.0976912	total: 5.54s	remaining: 27.3s
169:	learn: 0.0975588	total: 5.57s	remaining: 27.2s
170:	learn: 0.0975171	total: 5.61s	remaining: 27.2s
171:	learn: 0.0973602	total: 5.64s	remaining: 27.1s
172:	learn: 0.0972780	total: 5.67s	remaining: 27.1s
173:	learn: 0.0970515	total: 5.7s	remaining: 27.1s
174:	learn: 0.0968579	total: 5.73s	remaining: 27s
175:	learn: 0.0967823	total: 5.78s	remaining: 27.1s
176:	learn: 0.0964533	total: 5.81s	remaining: 27s
177:	learn: 0.0963620	total: 5.84s	remaining: 27s
178:	learn: 0.0961697	total: 5.87s	remaining: 26.9s
179:	learn: 0.0959366	total: 5.9s	remaining: 26.9s
180:	learn: 0.0957084	total: 5.94s	remaining: 26.9s
181:	learn: 0.0955375	total: 5.97s	remaining: 26.8s
182:	learn: 0.0952939	total: 6s	remaining: 26.8s
183:	learn: 0.0952555	total: 6.03s	remaining: 26.7s
184:	learn: 0.0950604	total: 6.06s	remaining: 26.7s
185:	learn: 0.0949130	total: 6.09s	remaining: 26.7s
186:	learn: 0.0948367	total: 6.14s	remaining: 26.7s
187:	learn: 0.0947384	total: 6.17s	remaining: 26.7s
188:	learn: 0.0946037	total: 6.2s	remaining: 26.6s
189:	learn: 0.0944300	total: 6.23s	remaining: 26.6s
190:	learn: 0.0943238	total: 6.26s	remaining: 26.5s
191:	learn: 0.0941692	total: 6.29s	remaining: 26.5s
192:	learn: 0.0940028	total: 6.33s	remaining: 26.4s
193:	learn: 0.0937513	total: 6.36s	remaining: 26.4s
194:	learn: 0.0935330	total: 6.38s	remaining: 26.4s
195:	learn: 0.0933444	total: 6.41s	remaining: 26.3s
196:	learn: 0.0931325	total: 6.45s	remaining: 26.3s
197:	learn: 0.0929740	total: 6.47s	remaining: 26.2s
198:	learn: 0.0928610	total: 6.5s	remaining: 26.2s
199:	learn: 0.0926724	total: 6.53s	remaining: 26.1s
200:	learn: 0.0924850	total: 6.56s	remaining: 26.1s
201:	learn: 0.0922692	total: 6.59s	remaining: 26s
202:	learn: 0.0920501	total: 6.62s	remaining: 26s
203:	learn: 0.0918472	total: 6.64s	remaining: 25.9s
204:	learn: 0.0916269	total: 6.67s	remaining: 25.9s
205:	learn: 0.0914758	total: 6.7s	remaining: 25.8s
206:	learn: 0.0914105	total: 6.73s	remaining: 25.8s
207:	learn: 0.0913272	total: 6.76s	remaining: 25.7s
208:	learn: 0.0912160	total: 6.79s	remaining: 25.7s
209:	learn: 0.0911059	total: 6.82s	remaining: 25.7s
210:	learn: 0.0909806	total: 6.85s	remaining: 25.6s
211:	learn: 0.0908766	total: 6.88s	remaining: 25.6s
212:	learn: 0.0907296	total: 6.91s	remaining: 25.5s
213:	learn: 0.0905623	total: 6.93s	remaining: 25.5s
214:	learn: 0.0903618	total: 6.96s	remaining: 25.4s
215:	learn: 0.0901791	total: 6.99s	remaining: 25.4s
216:	learn: 0.0901082	total: 7.02s	remaining: 25.3s
217:	learn: 0.0899064	total: 7.05s	remaining: 25.3s
218:	learn: 0.0898845	total: 7.08s	remaining: 25.3s
219:	learn: 0.0898080	total: 7.11s	remaining: 25.2s
220:	learn: 0.0895963	total: 7.14s	remaining: 25.2s
221:	learn: 0.0894885	total: 7.17s	remaining: 25.1s
222:	learn: 0.0893476	total: 7.2s	remaining: 25.1s
223:	learn: 0.0893176	total: 7.22s	remaining: 25s
224:	learn: 0.0892099	total: 7.25s	remaining: 25s
225:	learn: 0.0891144	total: 7.28s	remaining: 24.9s
226:	learn: 0.0890470	total: 7.31s	remaining: 24.9s
227:	learn: 0.0888846	total: 7.33s	remaining: 24.8s
228:	learn: 0.0888334	total: 7.36s	remaining: 24.8s
229:	learn: 0.0887087	total: 7.39s	remaining: 24.7s
230:	learn: 0.0886200	total: 7.42s	remaining: 24.7s
231:	learn: 0.0885213	total: 7.47s	remaining: 24.7s
232:	learn: 0.0884030	total: 7.5s	remaining: 24.7s
233:	learn: 0.0883160	total: 7.54s	remaining: 24.7s
234:	learn: 0.0881638	total: 7.57s	remaining: 24.6s
235:	learn: 0.0880100	total: 7.6s	remaining: 24.6s
236:	learn: 0.0877998	total: 7.63s	remaining: 24.6s
237:	learn: 0.0876804	total: 7.66s	remaining: 24.5s
238:	learn: 0.0875471	total: 7.69s	remaining: 24.5s
239:	learn: 0.0873843	total: 7.72s	remaining: 24.5s
240:	learn: 0.0873452	total: 7.75s	remaining: 24.4s
241:	learn: 0.0871911	total: 7.79s	remaining: 24.4s
242:	learn: 0.0870508	total: 7.82s	remaining: 24.4s
243:	learn: 0.0869410	total: 7.85s	remaining: 24.3s
244:	learn: 0.0868849	total: 7.88s	remaining: 24.3s
245:	learn: 0.0867075	total: 7.94s	remaining: 24.3s
246:	learn: 0.0866549	total: 7.97s	remaining: 24.3s
247:	learn: 0.0865156	total: 8s	remaining: 24.2s
248:	learn: 0.0862811	total: 8.03s	remaining: 24.2s
249:	learn: 0.0860909	total: 8.06s	remaining: 24.2s
250:	learn: 0.0859983	total: 8.09s	remaining: 24.1s
251:	learn: 0.0858646	total: 8.12s	remaining: 24.1s
252:	learn: 0.0857252	total: 8.15s	remaining: 24.1s
253:	learn: 0.0855347	total: 8.18s	remaining: 24s
254:	learn: 0.0853691	total: 8.21s	remaining: 24s
255:	learn: 0.0852485	total: 8.24s	remaining: 24s
256:	learn: 0.0851878	total: 8.27s	remaining: 23.9s
257:	learn: 0.0851717	total: 8.3s	remaining: 23.9s
258:	learn: 0.0851492	total: 8.33s	remaining: 23.8s
259:	learn: 0.0850054	total: 8.36s	remaining: 23.8s
260:	learn: 0.0848309	total: 8.39s	remaining: 23.8s
261:	learn: 0.0846907	total: 8.42s	remaining: 23.7s
262:	learn: 0.0845345	total: 8.47s	remaining: 23.7s
263:	learn: 0.0844269	total: 8.51s	remaining: 23.7s
264:	learn: 0.0842497	total: 8.53s	remaining: 23.7s
265:	learn: 0.0841520	total: 8.56s	remaining: 23.6s
266:	learn: 0.0839887	total: 8.59s	remaining: 23.6s
267:	learn: 0.0838960	total: 8.62s	remaining: 23.5s
268:	learn: 0.0838013	total: 8.65s	remaining: 23.5s
269:	learn: 0.0837742	total: 8.69s	remaining: 23.5s
270:	learn: 0.0837178	total: 8.73s	remaining: 23.5s
271:	learn: 0.0836539	total: 8.77s	remaining: 23.5s
272:	learn: 0.0834786	total: 8.8s	remaining: 23.4s
273:	learn: 0.0834416	total: 8.83s	remaining: 23.4s
274:	learn: 0.0833669	total: 8.87s	remaining: 23.4s
275:	learn: 0.0833357	total: 8.91s	remaining: 23.4s
276:	learn: 0.0831753	total: 8.95s	remaining: 23.4s
277:	learn: 0.0831581	total: 8.98s	remaining: 23.3s
278:	learn: 0.0830654	total: 9.01s	remaining: 23.3s
279:	learn: 0.0829706	total: 9.04s	remaining: 23.3s
280:	learn: 0.0828552	total: 9.08s	remaining: 23.2s
281:	learn: 0.0828226	total: 9.12s	remaining: 23.2s
282:	learn: 0.0827634	total: 9.15s	remaining: 23.2s
283:	learn: 0.0826974	total: 9.19s	remaining: 23.2s
284:	learn: 0.0826131	total: 9.22s	remaining: 23.1s
285:	learn: 0.0825737	total: 9.25s	remaining: 23.1s
286:	learn: 0.0824552	total: 9.28s	remaining: 23s
287:	learn: 0.0822984	total: 9.3s	remaining: 23s
288:	learn: 0.0822089	total: 9.33s	remaining: 23s
289:	learn: 0.0821416	total: 9.36s	remaining: 22.9s
290:	learn: 0.0820760	total: 9.38s	remaining: 22.9s
291:	learn: 0.0819543	total: 9.41s	remaining: 22.8s
292:	learn: 0.0818896	total: 9.44s	remaining: 22.8s
293:	learn: 0.0817017	total: 9.47s	remaining: 22.7s
294:	learn: 0.0816293	total: 9.5s	remaining: 22.7s
295:	learn: 0.0815057	total: 9.53s	remaining: 22.7s
296:	learn: 0.0813909	total: 9.56s	remaining: 22.6s
297:	learn: 0.0812251	total: 9.59s	remaining: 22.6s
298:	learn: 0.0811192	total: 9.62s	remaining: 22.5s
299:	learn: 0.0810385	total: 9.64s	remaining: 22.5s
300:	learn: 0.0809584	total: 9.67s	remaining: 22.5s
301:	learn: 0.0809264	total: 9.71s	remaining: 22.4s
302:	learn: 0.0808591	total: 9.74s	remaining: 22.4s
303:	learn: 0.0808283	total: 9.77s	remaining: 22.4s
304:	learn: 0.0806408	total: 9.81s	remaining: 22.3s
305:	learn: 0.0805402	total: 9.84s	remaining: 22.3s
306:	learn: 0.0804675	total: 9.87s	remaining: 22.3s
307:	learn: 0.0804045	total: 9.89s	remaining: 22.2s
308:	learn: 0.0803090	total: 9.92s	remaining: 22.2s
309:	learn: 0.0802082	total: 9.95s	remaining: 22.2s
310:	learn: 0.0801823	total: 9.99s	remaining: 22.1s
311:	learn: 0.0800360	total: 10s	remaining: 22.1s
312:	learn: 0.0798647	total: 10.1s	remaining: 22.1s
313:	learn: 0.0798425	total: 10.1s	remaining: 22.1s
314:	learn: 0.0797428	total: 10.1s	remaining: 22s
315:	learn: 0.0796740	total: 10.2s	remaining: 22s
316:	learn: 0.0796170	total: 10.2s	remaining: 22s
317:	learn: 0.0795601	total: 10.2s	remaining: 21.9s
318:	learn: 0.0794940	total: 10.3s	remaining: 21.9s
319:	learn: 0.0793522	total: 10.3s	remaining: 21.9s
320:	learn: 0.0792721	total: 10.3s	remaining: 21.8s
321:	learn: 0.0791528	total: 10.4s	remaining: 21.8s
322:	learn: 0.0790782	total: 10.4s	remaining: 21.8s
323:	learn: 0.0790145	total: 10.4s	remaining: 21.7s
324:	learn: 0.0789650	total: 10.5s	remaining: 21.7s
325:	learn: 0.0788205	total: 10.5s	remaining: 21.7s
326:	learn: 0.0787468	total: 10.5s	remaining: 21.6s
327:	learn: 0.0786527	total: 10.6s	remaining: 21.6s
328:	learn: 0.0785863	total: 10.6s	remaining: 21.6s
329:	learn: 0.0784688	total: 10.6s	remaining: 21.5s
330:	learn: 0.0783873	total: 10.6s	remaining: 21.5s
331:	learn: 0.0782382	total: 10.7s	remaining: 21.5s
332:	learn: 0.0781629	total: 10.7s	remaining: 21.4s
333:	learn: 0.0780930	total: 10.7s	remaining: 21.4s
334:	learn: 0.0779426	total: 10.8s	remaining: 21.4s
335:	learn: 0.0779300	total: 10.8s	remaining: 21.3s
336:	learn: 0.0779049	total: 10.8s	remaining: 21.3s
337:	learn: 0.0778724	total: 10.9s	remaining: 21.3s
338:	learn: 0.0777529	total: 10.9s	remaining: 21.3s
339:	learn: 0.0777209	total: 10.9s	remaining: 21.2s
340:	learn: 0.0776726	total: 11s	remaining: 21.2s
341:	learn: 0.0775751	total: 11s	remaining: 21.2s
342:	learn: 0.0774532	total: 11s	remaining: 21.1s
343:	learn: 0.0772856	total: 11.1s	remaining: 21.1s
344:	learn: 0.0771391	total: 11.1s	remaining: 21.1s
345:	learn: 0.0770162	total: 11.1s	remaining: 21s
346:	learn: 0.0769093	total: 11.2s	remaining: 21s
347:	learn: 0.0768938	total: 11.2s	remaining: 21s
348:	learn: 0.0767988	total: 11.2s	remaining: 20.9s
349:	learn: 0.0767487	total: 11.3s	remaining: 20.9s
350:	learn: 0.0766195	total: 11.3s	remaining: 20.9s
351:	learn: 0.0766076	total: 11.3s	remaining: 20.9s
352:	learn: 0.0765463	total: 11.4s	remaining: 20.8s
353:	learn: 0.0765267	total: 11.4s	remaining: 20.8s
354:	learn: 0.0763976	total: 11.4s	remaining: 20.8s
355:	learn: 0.0763224	total: 11.5s	remaining: 20.7s
356:	learn: 0.0761655	total: 11.5s	remaining: 20.7s
357:	learn: 0.0761014	total: 11.5s	remaining: 20.6s
358:	learn: 0.0759682	total: 11.5s	remaining: 20.6s
359:	learn: 0.0759461	total: 11.6s	remaining: 20.6s
360:	learn: 0.0759250	total: 11.6s	remaining: 20.5s
361:	learn: 0.0758646	total: 11.6s	remaining: 20.5s
362:	learn: 0.0758313	total: 11.7s	remaining: 20.5s
363:	learn: 0.0757896	total: 11.7s	remaining: 20.5s
364:	learn: 0.0757060	total: 11.7s	remaining: 20.4s
365:	learn: 0.0756903	total: 11.8s	remaining: 20.4s
366:	learn: 0.0755687	total: 11.8s	remaining: 20.4s
367:	learn: 0.0755453	total: 11.8s	remaining: 20.3s
368:	learn: 0.0754381	total: 11.9s	remaining: 20.3s
369:	learn: 0.0753644	total: 11.9s	remaining: 20.3s
370:	learn: 0.0753507	total: 11.9s	remaining: 20.3s
371:	learn: 0.0753126	total: 12s	remaining: 20.2s
372:	learn: 0.0752195	total: 12s	remaining: 20.2s
373:	learn: 0.0751872	total: 12.1s	remaining: 20.2s
374:	learn: 0.0751067	total: 12.1s	remaining: 20.1s
375:	learn: 0.0750388	total: 12.1s	remaining: 20.1s
376:	learn: 0.0749694	total: 12.1s	remaining: 20.1s
377:	learn: 0.0749450	total: 12.2s	remaining: 20s
378:	learn: 0.0748152	total: 12.2s	remaining: 20s
379:	learn: 0.0747062	total: 12.3s	remaining: 20s
380:	learn: 0.0746574	total: 12.3s	remaining: 20s
381:	learn: 0.0746312	total: 12.3s	remaining: 19.9s
382:	learn: 0.0745948	total: 12.4s	remaining: 19.9s
383:	learn: 0.0745054	total: 12.4s	remaining: 19.9s
384:	learn: 0.0743994	total: 12.4s	remaining: 19.8s
385:	learn: 0.0742894	total: 12.4s	remaining: 19.8s
386:	learn: 0.0742462	total: 12.5s	remaining: 19.8s

CV folds:  28%|██▊       | 14/50 [07:22<19:09, 31.92s/fold]

Learning rate set to 0.042738
0:	learn: 0.3887625	total: 24.5ms	remaining: 24.5s
1:	learn: 0.3782752	total: 57.1ms	remaining: 28.5s
2:	learn: 0.3682950	total: 86.8ms	remaining: 28.8s
3:	learn: 0.3587888	total: 120ms	remaining: 30s
4:	learn: 0.3494829	total: 149ms	remaining: 29.6s
5:	learn: 0.3404283	total: 180ms	remaining: 29.8s
6:	learn: 0.3317691	total: 211ms	remaining: 30s
7:	learn: 0.3232485	total: 250ms	remaining: 31s
8:	learn: 0.3146667	total: 281ms	remaining: 30.9s
9:	learn: 0.3070224	total: 311ms	remaining: 30.8s
10:	learn: 0.2997729	total: 338ms	remaining: 30.4s
11:	learn: 0.2928300	total: 365ms	remaining: 30s
12:	learn: 0.2859522	total: 394ms	remaining: 29.9s
13:	learn: 0.2791420	total: 426ms	remaining: 30s
14:	learn: 0.2725067	total: 457ms	remaining: 30s
15:	learn: 0.2663379	total: 488ms	remaining: 30s
16:	learn: 0.2602429	total: 519ms	remaining: 30s
17:	learn: 0.2545395	total: 550ms	remaining: 30s
18:	learn: 0.2492069	total: 581ms	remaining: 30s
19:	learn: 0.2443174	total: 608ms	remaining: 29.8s
20:	learn: 0.2391415	total: 636ms	remaining: 29.6s
21:	learn: 0.2339806	total: 666ms	remaining: 29.6s
22:	learn: 0.2291989	total: 697ms	remaining: 29.6s
23:	learn: 0.2242826	total: 726ms	remaining: 29.5s
24:	learn: 0.2204892	total: 755ms	remaining: 29.5s
25:	learn: 0.2164192	total: 784ms	remaining: 29.4s
26:	learn: 0.2119709	total: 813ms	remaining: 29.3s
27:	learn: 0.2081914	total: 844ms	remaining: 29.3s
28:	learn: 0.2046171	total: 874ms	remaining: 29.3s
29:	learn: 0.2010472	total: 906ms	remaining: 29.3s
30:	learn: 0.1979633	total: 927ms	remaining: 29s
31:	learn: 0.1947227	total: 973ms	remaining: 29.4s
32:	learn: 0.1914299	total: 1s	remaining: 29.4s
33:	learn: 0.1881857	total: 1.03s	remaining: 29.4s
34:	learn: 0.1854869	total: 1.06s	remaining: 29.3s
35:	learn: 0.1824556	total: 1.1s	remaining: 29.6s
36:	learn: 0.1797790	total: 1.15s	remaining: 30s
37:	learn: 0.1773284	total: 1.18s	remaining: 30s
38:	learn: 0.1749862	total: 1.21s	remaining: 29.9s
39:	learn: 0.1723742	total: 1.24s	remaining: 29.8s
40:	learn: 0.1701136	total: 1.27s	remaining: 29.8s
41:	learn: 0.1679109	total: 1.3s	remaining: 29.7s
42:	learn: 0.1656160	total: 1.33s	remaining: 29.7s
43:	learn: 0.1633915	total: 1.36s	remaining: 29.6s
44:	learn: 0.1614005	total: 1.39s	remaining: 29.6s
45:	learn: 0.1594263	total: 1.42s	remaining: 29.5s
46:	learn: 0.1577095	total: 1.45s	remaining: 29.4s
47:	learn: 0.1559568	total: 1.48s	remaining: 29.4s
48:	learn: 0.1542479	total: 1.51s	remaining: 29.4s
49:	learn: 0.1527487	total: 1.55s	remaining: 29.4s
50:	learn: 0.1512923	total: 1.58s	remaining: 29.4s
51:	learn: 0.1497392	total: 1.61s	remaining: 29.3s
52:	learn: 0.1482293	total: 1.64s	remaining: 29.3s
53:	learn: 0.1467729	total: 1.67s	remaining: 29.3s
54:	learn: 0.1455905	total: 1.7s	remaining: 29.2s
55:	learn: 0.1444278	total: 1.73s	remaining: 29.1s
56:	learn: 0.1431543	total: 1.76s	remaining: 29.1s
57:	learn: 0.1420037	total: 1.79s	remaining: 29s
58:	learn: 0.1409491	total: 1.82s	remaining: 29s
59:	learn: 0.1398182	total: 1.84s	remaining: 28.9s
60:	learn: 0.1386379	total: 1.88s	remaining: 28.9s
61:	learn: 0.1376253	total: 1.91s	remaining: 28.8s
62:	learn: 0.1366708	total: 1.94s	remaining: 28.8s
63:	learn: 0.1357316	total: 1.97s	remaining: 28.8s
64:	learn: 0.1347276	total: 2s	remaining: 28.8s
65:	learn: 0.1337278	total: 2.03s	remaining: 28.7s
66:	learn: 0.1328111	total: 2.06s	remaining: 28.7s
67:	learn: 0.1318590	total: 2.09s	remaining: 28.6s
68:	learn: 0.1310366	total: 2.12s	remaining: 28.6s
69:	learn: 0.1301535	total: 2.15s	remaining: 28.6s
70:	learn: 0.1295158	total: 2.19s	remaining: 28.6s
71:	learn: 0.1286041	total: 2.23s	remaining: 28.7s
72:	learn: 0.1277645	total: 2.26s	remaining: 28.7s
73:	learn: 0.1270632	total: 2.29s	remaining: 28.6s
74:	learn: 0.1265067	total: 2.32s	remaining: 28.6s
75:	learn: 0.1257636	total: 2.35s	remaining: 28.6s
76:	learn: 0.1251160	total: 2.38s	remaining: 28.5s
77:	learn: 0.1244503	total: 2.41s	remaining: 28.5s
78:	learn: 0.1237488	total: 2.44s	remaining: 28.5s
79:	learn: 0.1229087	total: 2.48s	remaining: 28.5s
80:	learn: 0.1221747	total: 2.51s	remaining: 28.5s
81:	learn: 0.1215017	total: 2.54s	remaining: 28.5s
82:	learn: 0.1208024	total: 2.57s	remaining: 28.4s
83:	learn: 0.1201709	total: 2.6s	remaining: 28.4s
84:	learn: 0.1194648	total: 2.63s	remaining: 28.3s
85:	learn: 0.1189233	total: 2.66s	remaining: 28.3s
86:	learn: 0.1182584	total: 2.69s	remaining: 28.3s
87:	learn: 0.1176500	total: 2.73s	remaining: 28.3s
88:	learn: 0.1170244	total: 2.76s	remaining: 28.3s
89:	learn: 0.1164668	total: 2.79s	remaining: 28.2s
90:	learn: 0.1159279	total: 2.82s	remaining: 28.2s
91:	learn: 0.1155617	total: 2.85s	remaining: 28.1s
92:	learn: 0.1151242	total: 2.88s	remaining: 28.1s
93:	learn: 0.1147989	total: 2.91s	remaining: 28s
94:	learn: 0.1143814	total: 2.94s	remaining: 28s
95:	learn: 0.1139403	total: 2.97s	remaining: 28s
96:	learn: 0.1135417	total: 3s	remaining: 28s
97:	learn: 0.1132262	total: 3.03s	remaining: 27.9s
98:	learn: 0.1129509	total: 3.06s	remaining: 27.9s
99:	learn: 0.1125813	total: 3.1s	remaining: 27.9s
100:	learn: 0.1122353	total: 3.13s	remaining: 27.9s
101:	learn: 0.1118489	total: 3.16s	remaining: 27.8s
102:	learn: 0.1115608	total: 3.19s	remaining: 27.8s
103:	learn: 0.1112311	total: 3.22s	remaining: 27.8s
104:	learn: 0.1107804	total: 3.26s	remaining: 27.8s
105:	learn: 0.1105645	total: 3.3s	remaining: 27.9s
106:	learn: 0.1102429	total: 3.33s	remaining: 27.8s
107:	learn: 0.1099826	total: 3.36s	remaining: 27.8s
108:	learn: 0.1095583	total: 3.39s	remaining: 27.7s
109:	learn: 0.1093709	total: 3.43s	remaining: 27.7s
110:	learn: 0.1091766	total: 3.46s	remaining: 27.7s
111:	learn: 0.1089391	total: 3.49s	remaining: 27.6s
112:	learn: 0.1087491	total: 3.52s	remaining: 27.6s
113:	learn: 0.1084552	total: 3.54s	remaining: 27.6s
114:	learn: 0.1082529	total: 3.58s	remaining: 27.5s
115:	learn: 0.1079451	total: 3.61s	remaining: 27.5s
116:	learn: 0.1077239	total: 3.64s	remaining: 27.4s
117:	learn: 0.1074446	total: 3.67s	remaining: 27.4s
118:	learn: 0.1072197	total: 3.69s	remaining: 27.4s
119:	learn: 0.1069906	total: 3.73s	remaining: 27.3s
120:	learn: 0.1066858	total: 3.75s	remaining: 27.3s
121:	learn: 0.1064540	total: 3.78s	remaining: 27.2s
122:	learn: 0.1062277	total: 3.81s	remaining: 27.2s
123:	learn: 0.1059388	total: 3.84s	remaining: 27.2s
124:	learn: 0.1057325	total: 3.87s	remaining: 27.1s
125:	learn: 0.1055335	total: 3.9s	remaining: 27.1s
126:	learn: 0.1053939	total: 3.93s	remaining: 27s
127:	learn: 0.1051439	total: 3.96s	remaining: 27s
128:	learn: 0.1048816	total: 4s	remaining: 27s
129:	learn: 0.1046314	total: 4.03s	remaining: 27s
130:	learn: 0.1044639	total: 4.06s	remaining: 26.9s
131:	learn: 0.1042231	total: 4.09s	remaining: 26.9s
132:	learn: 0.1040027	total: 4.12s	remaining: 26.9s
133:	learn: 0.1036924	total: 4.15s	remaining: 26.8s
134:	learn: 0.1034240	total: 4.18s	remaining: 26.8s
135:	learn: 0.1032347	total: 4.21s	remaining: 26.8s
136:	learn: 0.1029841	total: 4.25s	remaining: 26.8s
137:	learn: 0.1027671	total: 4.28s	remaining: 26.8s
138:	learn: 0.1025399	total: 4.33s	remaining: 26.8s
139:	learn: 0.1022835	total: 4.36s	remaining: 26.8s
140:	learn: 0.1021365	total: 4.39s	remaining: 26.8s
141:	learn: 0.1019441	total: 4.43s	remaining: 26.7s
142:	learn: 0.1016997	total: 4.46s	remaining: 26.7s
143:	learn: 0.1015840	total: 4.48s	remaining: 26.6s
144:	learn: 0.1013847	total: 4.51s	remaining: 26.6s
145:	learn: 0.1012522	total: 4.53s	remaining: 26.5s
146:	learn: 0.1011585	total: 4.56s	remaining: 26.5s
147:	learn: 0.1009918	total: 4.59s	remaining: 26.5s
148:	learn: 0.1007625	total: 4.63s	remaining: 26.4s
149:	learn: 0.1006072	total: 4.66s	remaining: 26.4s
150:	learn: 0.1002176	total: 4.69s	remaining: 26.4s
151:	learn: 0.0999794	total: 4.72s	remaining: 26.4s
152:	learn: 0.0997303	total: 4.75s	remaining: 26.3s
153:	learn: 0.0995652	total: 4.78s	remaining: 26.3s
154:	learn: 0.0993393	total: 4.82s	remaining: 26.2s
155:	learn: 0.0991987	total: 4.85s	remaining: 26.2s
156:	learn: 0.0990415	total: 4.88s	remaining: 26.2s
157:	learn: 0.0988276	total: 4.91s	remaining: 26.2s
158:	learn: 0.0986953	total: 4.94s	remaining: 26.1s
159:	learn: 0.0985540	total: 4.97s	remaining: 26.1s
160:	learn: 0.0983629	total: 5.01s	remaining: 26.1s
161:	learn: 0.0981359	total: 5.04s	remaining: 26.1s
162:	learn: 0.0980171	total: 5.06s	remaining: 26s
163:	learn: 0.0978475	total: 5.1s	remaining: 26s
164:	learn: 0.0977107	total: 5.13s	remaining: 25.9s
165:	learn: 0.0975919	total: 5.16s	remaining: 25.9s
166:	learn: 0.0974232	total: 5.2s	remaining: 25.9s
167:	learn: 0.0973565	total: 5.23s	remaining: 25.9s
168:	learn: 0.0971764	total: 5.26s	remaining: 25.9s
169:	learn: 0.0970586	total: 5.29s	remaining: 25.8s
170:	learn: 0.0968514	total: 5.32s	remaining: 25.8s
171:	learn: 0.0966075	total: 5.35s	remaining: 25.8s
172:	learn: 0.0964575	total: 5.38s	remaining: 25.7s
173:	learn: 0.0961094	total: 5.42s	remaining: 25.7s
174:	learn: 0.0958615	total: 5.46s	remaining: 25.7s
175:	learn: 0.0956946	total: 5.49s	remaining: 25.7s
176:	learn: 0.0955204	total: 5.52s	remaining: 25.7s
177:	learn: 0.0954059	total: 5.55s	remaining: 25.6s
178:	learn: 0.0951532	total: 5.61s	remaining: 25.7s
179:	learn: 0.0948719	total: 5.64s	remaining: 25.7s
180:	learn: 0.0945937	total: 5.67s	remaining: 25.7s
181:	learn: 0.0944054	total: 5.7s	remaining: 25.6s
182:	learn: 0.0942325	total: 5.73s	remaining: 25.6s
183:	learn: 0.0939228	total: 5.76s	remaining: 25.5s
184:	learn: 0.0938029	total: 5.79s	remaining: 25.5s
185:	learn: 0.0937104	total: 5.82s	remaining: 25.5s
186:	learn: 0.0936378	total: 5.85s	remaining: 25.4s
187:	learn: 0.0934741	total: 5.88s	remaining: 25.4s
188:	learn: 0.0932769	total: 5.91s	remaining: 25.3s
189:	learn: 0.0931769	total: 5.94s	remaining: 25.3s
190:	learn: 0.0930841	total: 5.97s	remaining: 25.3s
191:	learn: 0.0930167	total: 6s	remaining: 25.3s
192:	learn: 0.0929166	total: 6.03s	remaining: 25.2s
193:	learn: 0.0928614	total: 6.06s	remaining: 25.2s
194:	learn: 0.0927284	total: 6.09s	remaining: 25.1s
195:	learn: 0.0926448	total: 6.12s	remaining: 25.1s
196:	learn: 0.0925466	total: 6.16s	remaining: 25.1s
197:	learn: 0.0923935	total: 6.19s	remaining: 25.1s
198:	learn: 0.0922018	total: 6.22s	remaining: 25s
199:	learn: 0.0920926	total: 6.25s	remaining: 25s
200:	learn: 0.0920140	total: 6.29s	remaining: 25s
201:	learn: 0.0919078	total: 6.32s	remaining: 25s
202:	learn: 0.0917417	total: 6.35s	remaining: 24.9s
203:	learn: 0.0915115	total: 6.38s	remaining: 24.9s
204:	learn: 0.0914041	total: 6.41s	remaining: 24.9s
205:	learn: 0.0912813	total: 6.44s	remaining: 24.8s
206:	learn: 0.0912173	total: 6.47s	remaining: 24.8s
207:	learn: 0.0911084	total: 6.5s	remaining: 24.7s
208:	learn: 0.0910019	total: 6.53s	remaining: 24.7s
209:	learn: 0.0908188	total: 6.56s	remaining: 24.7s
210:	learn: 0.0907241	total: 6.59s	remaining: 24.7s
211:	learn: 0.0905432	total: 6.62s	remaining: 24.6s
212:	learn: 0.0904597	total: 6.65s	remaining: 24.6s
213:	learn: 0.0903487	total: 6.68s	remaining: 24.6s
214:	learn: 0.0902547	total: 6.71s	remaining: 24.5s
215:	learn: 0.0902090	total: 6.75s	remaining: 24.5s
216:	learn: 0.0900334	total: 6.78s	remaining: 24.5s
217:	learn: 0.0898891	total: 6.81s	remaining: 24.4s
218:	learn: 0.0898188	total: 6.84s	remaining: 24.4s
219:	learn: 0.0897532	total: 6.87s	remaining: 24.4s
220:	learn: 0.0896666	total: 6.9s	remaining: 24.3s
221:	learn: 0.0895488	total: 6.93s	remaining: 24.3s
222:	learn: 0.0894714	total: 6.97s	remaining: 24.3s
223:	learn: 0.0892334	total: 7s	remaining: 24.2s
224:	learn: 0.0891141	total: 7.03s	remaining: 24.2s
225:	learn: 0.0889659	total: 7.06s	remaining: 24.2s
226:	learn: 0.0888464	total: 7.09s	remaining: 24.1s
227:	learn: 0.0887139	total: 7.12s	remaining: 24.1s
228:	learn: 0.0885539	total: 7.15s	remaining: 24.1s
229:	learn: 0.0884544	total: 7.18s	remaining: 24.1s
230:	learn: 0.0883712	total: 7.21s	remaining: 24s
231:	learn: 0.0881980	total: 7.25s	remaining: 24s
232:	learn: 0.0880710	total: 7.28s	remaining: 24s
233:	learn: 0.0879955	total: 7.31s	remaining: 23.9s
234:	learn: 0.0878919	total: 7.34s	remaining: 23.9s
235:	learn: 0.0877654	total: 7.37s	remaining: 23.9s
236:	learn: 0.0877409	total: 7.4s	remaining: 23.8s
237:	learn: 0.0875770	total: 7.43s	remaining: 23.8s
238:	learn: 0.0872656	total: 7.46s	remaining: 23.8s
239:	learn: 0.0870614	total: 7.49s	remaining: 23.7s
240:	learn: 0.0869598	total: 7.52s	remaining: 23.7s
241:	learn: 0.0868639	total: 7.55s	remaining: 23.7s
242:	learn: 0.0868237	total: 7.6s	remaining: 23.7s
243:	learn: 0.0867751	total: 7.63s	remaining: 23.6s
244:	learn: 0.0866311	total: 7.66s	remaining: 23.6s
245:	learn: 0.0865903	total: 7.69s	remaining: 23.6s
246:	learn: 0.0865373	total: 7.72s	remaining: 23.5s
247:	learn: 0.0864894	total: 7.76s	remaining: 23.5s
248:	learn: 0.0864053	total: 7.79s	remaining: 23.5s
249:	learn: 0.0861811	total: 7.82s	remaining: 23.5s
250:	learn: 0.0859177	total: 7.85s	remaining: 23.4s
251:	learn: 0.0857323	total: 7.88s	remaining: 23.4s
252:	learn: 0.0855837	total: 7.91s	remaining: 23.4s
253:	learn: 0.0854804	total: 7.94s	remaining: 23.3s
254:	learn: 0.0854385	total: 7.97s	remaining: 23.3s
255:	learn: 0.0852535	total: 8s	remaining: 23.3s
256:	learn: 0.0851791	total: 8.03s	remaining: 23.2s
257:	learn: 0.0848885	total: 8.06s	remaining: 23.2s
258:	learn: 0.0847639	total: 8.09s	remaining: 23.2s
259:	learn: 0.0846548	total: 8.13s	remaining: 23.1s
260:	learn: 0.0844966	total: 8.16s	remaining: 23.1s
261:	learn: 0.0843894	total: 8.19s	remaining: 23.1s
262:	learn: 0.0842976	total: 8.22s	remaining: 23s
263:	learn: 0.0841813	total: 8.26s	remaining: 23s
264:	learn: 0.0840960	total: 8.29s	remaining: 23s
265:	learn: 0.0839387	total: 8.32s	remaining: 23s
266:	learn: 0.0837909	total: 8.35s	remaining: 22.9s
267:	learn: 0.0836525	total: 8.38s	remaining: 22.9s
268:	learn: 0.0836172	total: 8.41s	remaining: 22.8s
269:	learn: 0.0836039	total: 8.44s	remaining: 22.8s
270:	learn: 0.0835173	total: 8.47s	remaining: 22.8s
271:	learn: 0.0834851	total: 8.5s	remaining: 22.8s
272:	learn: 0.0832882	total: 8.54s	remaining: 22.7s
273:	learn: 0.0832578	total: 8.56s	remaining: 22.7s
274:	learn: 0.0830974	total: 8.59s	remaining: 22.6s
275:	learn: 0.0830641	total: 8.62s	remaining: 22.6s
276:	learn: 0.0830010	total: 8.65s	remaining: 22.6s
277:	learn: 0.0829852	total: 8.69s	remaining: 22.6s
278:	learn: 0.0827380	total: 8.72s	remaining: 22.5s
279:	learn: 0.0826450	total: 8.75s	remaining: 22.5s
280:	learn: 0.0824557	total: 8.78s	remaining: 22.5s
281:	learn: 0.0823524	total: 8.81s	remaining: 22.4s
282:	learn: 0.0822290	total: 8.84s	remaining: 22.4s
283:	learn: 0.0821522	total: 8.87s	remaining: 22.4s
284:	learn: 0.0820883	total: 8.9s	remaining: 22.3s
285:	learn: 0.0820664	total: 8.93s	remaining: 22.3s
286:	learn: 0.0819658	total: 8.97s	remaining: 22.3s
287:	learn: 0.0818768	total: 9s	remaining: 22.2s
288:	learn: 0.0817378	total: 9.03s	remaining: 22.2s
289:	learn: 0.0816278	total: 9.06s	remaining: 22.2s
290:	learn: 0.0816107	total: 9.09s	remaining: 22.2s
291:	learn: 0.0815455	total: 9.12s	remaining: 22.1s
292:	learn: 0.0814445	total: 9.15s	remaining: 22.1s
293:	learn: 0.0813256	total: 9.18s	remaining: 22.1s
294:	learn: 0.0812468	total: 9.22s	remaining: 22s
295:	learn: 0.0811505	total: 9.25s	remaining: 22s
296:	learn: 0.0811066	total: 9.28s	remaining: 22s
297:	learn: 0.0810163	total: 9.31s	remaining: 21.9s
298:	learn: 0.0809930	total: 9.34s	remaining: 21.9s
299:	learn: 0.0809009	total: 9.37s	remaining: 21.9s
300:	learn: 0.0808336	total: 9.4s	remaining: 21.8s
301:	learn: 0.0807039	total: 9.44s	remaining: 21.8s
302:	learn: 0.0806431	total: 9.47s	remaining: 21.8s
303:	learn: 0.0804651	total: 9.5s	remaining: 21.8s
304:	learn: 0.0804490	total: 9.54s	remaining: 21.7s
305:	learn: 0.0804308	total: 9.56s	remaining: 21.7s
306:	learn: 0.0803513	total: 9.6s	remaining: 21.7s
307:	learn: 0.0802848	total: 9.63s	remaining: 21.6s
308:	learn: 0.0802266	total: 9.66s	remaining: 21.6s
309:	learn: 0.0801822	total: 9.69s	remaining: 21.6s
310:	learn: 0.0800499	total: 9.73s	remaining: 21.6s
311:	learn: 0.0798706	total: 9.77s	remaining: 21.5s
312:	learn: 0.0798338	total: 9.8s	remaining: 21.5s
313:	learn: 0.0797156	total: 9.83s	remaining: 21.5s
314:	learn: 0.0796254	total: 9.86s	remaining: 21.4s
315:	learn: 0.0795156	total: 9.89s	remaining: 21.4s
316:	learn: 0.0794915	total: 9.92s	remaining: 21.4s
317:	learn: 0.0793875	total: 9.95s	remaining: 21.3s
318:	learn: 0.0793603	total: 9.98s	remaining: 21.3s
319:	learn: 0.0792776	total: 10s	remaining: 21.3s
320:	learn: 0.0792282	total: 10s	remaining: 21.3s
321:	learn: 0.0791681	total: 10.1s	remaining: 21.2s
322:	learn: 0.0791070	total: 10.1s	remaining: 21.2s
323:	learn: 0.0789027	total: 10.1s	remaining: 21.2s
324:	learn: 0.0788391	total: 10.2s	remaining: 21.1s
325:	learn: 0.0787094	total: 10.2s	remaining: 21.1s
326:	learn: 0.0786702	total: 10.2s	remaining: 21.1s
327:	learn: 0.0785523	total: 10.3s	remaining: 21s
328:	learn: 0.0784841	total: 10.3s	remaining: 21s
329:	learn: 0.0784188	total: 10.3s	remaining: 21s
330:	learn: 0.0783471	total: 10.4s	remaining: 20.9s
331:	learn: 0.0782690	total: 10.4s	remaining: 20.9s
332:	learn: 0.0781511	total: 10.4s	remaining: 20.9s
333:	learn: 0.0781239	total: 10.5s	remaining: 20.8s
334:	learn: 0.0780750	total: 10.5s	remaining: 20.8s
335:	learn: 0.0779590	total: 10.5s	remaining: 20.8s
336:	learn: 0.0777845	total: 10.5s	remaining: 20.8s
337:	learn: 0.0777583	total: 10.6s	remaining: 20.7s
338:	learn: 0.0777087	total: 10.6s	remaining: 20.7s
339:	learn: 0.0777004	total: 10.7s	remaining: 20.7s
340:	learn: 0.0775037	total: 10.7s	remaining: 20.7s
341:	learn: 0.0773748	total: 10.7s	remaining: 20.6s
342:	learn: 0.0772787	total: 10.8s	remaining: 20.6s
343:	learn: 0.0772146	total: 10.8s	remaining: 20.6s
344:	learn: 0.0770766	total: 10.8s	remaining: 20.5s
345:	learn: 0.0769485	total: 10.9s	remaining: 20.5s
346:	learn: 0.0768058	total: 10.9s	remaining: 20.5s
347:	learn: 0.0767169	total: 10.9s	remaining: 20.4s
348:	learn: 0.0766360	total: 10.9s	remaining: 20.4s
349:	learn: 0.0766251	total: 11s	remaining: 20.4s
350:	learn: 0.0765180	total: 11s	remaining: 20.4s
351:	learn: 0.0764680	total: 11s	remaining: 20.3s
352:	learn: 0.0764569	total: 11.1s	remaining: 20.3s
353:	learn: 0.0763403	total: 11.1s	remaining: 20.3s
354:	learn: 0.0762319	total: 11.1s	remaining: 20.2s
355:	learn: 0.0761699	total: 11.2s	remaining: 20.2s
356:	learn: 0.0759544	total: 11.2s	remaining: 20.2s
357:	learn: 0.0759397	total: 11.2s	remaining: 20.1s
358:	learn: 0.0759060	total: 11.3s	remaining: 20.1s
359:	learn: 0.0758931	total: 11.3s	remaining: 20.1s
360:	learn: 0.0757818	total: 11.3s	remaining: 20s
361:	learn: 0.0756987	total: 11.4s	remaining: 20s
362:	learn: 0.0756853	total: 11.4s	remaining: 20s
363:	learn: 0.0756591	total: 11.4s	remaining: 19.9s
364:	learn: 0.0755336	total: 11.4s	remaining: 19.9s
365:	learn: 0.0755210	total: 11.5s	remaining: 19.9s
366:	learn: 0.0755145	total: 11.5s	remaining: 19.8s
367:	learn: 0.0754093	total: 11.5s	remaining: 19.8s
368:	learn: 0.0752322	total: 11.6s	remaining: 19.8s
369:	learn: 0.0752114	total: 11.6s	remaining: 19.8s
370:	learn: 0.0751592	total: 11.6s	remaining: 19.7s
371:	learn: 0.0750785	total: 11.7s	remaining: 19.7s
372:	learn: 0.0750004	total: 11.7s	remaining: 19.7s
373:	learn: 0.0749875	total: 11.7s	remaining: 19.6s
374:	learn: 0.0749383	total: 11.8s	remaining: 19.6s
375:	learn: 0.0748745	total: 11.8s	remaining: 19.6s
376:	learn: 0.0747660	total: 11.8s	remaining: 19.6s
377:	learn: 0.0746816	total: 11.9s	remaining: 19.5s
378:	learn: 0.0744938	total: 11.9s	remaining: 19.5s
379:	learn: 0.0743905	total: 11.9s	remaining: 19.5s
380:	learn: 0.0742918	total: 12s	remaining: 19.5s
381:	learn: 0.0742469	total: 12s	remaining: 19.4s
382:	learn: 0.0741411	total: 12s	remaining: 19.4s
383:	learn: 0.0740660	total: 12.1s	remaining: 19.4s
384:	learn: 0.0739241	total: 12.1s	remaining: 19.3s
385:	learn: 0.0738155	total: 12.1s	remaining: 19.3s
386:	learn: 0.0738072	total: 12.2s	remaining: 19.3s
387:	learn: 0.0737958	total: 12.2s	remaining: 19.3s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Functional': 1 unseen categories converted to Unseen on transform.

CV folds:  30%|███       | 15/50 [07:55<18:43, 32.09s/fold]

997:	learn: 0.0444135	total: 31.9s	remaining: 64ms
998:	learn: 0.0443985	total: 32s	remaining: 32ms
999:	learn: 0.0443968	total: 32s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3900945	total: 29.4ms	remaining: 29.4s
1:	learn: 0.3791335	total: 62.6ms	remaining: 31.3s
2:	learn: 0.3692216	total: 93.1ms	remaining: 30.9s
3:	learn: 0.3597032	total: 123ms	remaining: 30.6s
4:	learn: 0.3504186	total: 155ms	remaining: 30.8s
5:	learn: 0.3408420	total: 187ms	remaining: 30.9s
6:	learn: 0.3316839	total: 219ms	remaining: 31s
7:	learn: 0.3235884	total: 252ms	remaining: 31.3s
8:	learn: 0.3159510	total: 284ms	remaining: 31.3s
9:	learn: 0.3080398	total: 312ms	remaining: 30.9s
10:	learn: 0.3002242	total: 354ms	remaining: 31.8s
11:	learn: 0.2926563	total: 381ms	remaining: 31.4s
12:	learn: 0.2854919	total: 415ms	remaining: 31.5s
13:	learn: 0.2793744	total: 438ms	remaining: 30.8s
14:	learn: 0.2731985	total: 467ms	remaining: 30.6s
15:	learn: 0.2669174	total: 497ms	remaining: 30.5s
16:	learn: 0.2608444	total: 524ms	remaining: 30.3s
17:	learn: 0.2553646	total: 553ms	remaining: 30.2s
18:	learn: 0.2494529	total: 584ms	remaining: 30.2s
19:	learn: 0.2443835	total: 614ms	remaining: 30.1s
20:	learn: 0.2394216	total: 645ms	remaining: 30.1s
21:	learn: 0.2344051	total: 679ms	remaining: 30.2s
22:	learn: 0.2295695	total: 709ms	remaining: 30.1s
23:	learn: 0.2246909	total: 738ms	remaining: 30s
24:	learn: 0.2201324	total: 767ms	remaining: 29.9s
25:	learn: 0.2157468	total: 797ms	remaining: 29.9s
26:	learn: 0.2119375	total: 827ms	remaining: 29.8s
27:	learn: 0.2082989	total: 849ms	remaining: 29.5s
28:	learn: 0.2045628	total: 880ms	remaining: 29.5s
29:	learn: 0.2008746	total: 911ms	remaining: 29.4s
30:	learn: 0.1972652	total: 939ms	remaining: 29.4s
31:	learn: 0.1943717	total: 972ms	remaining: 29.4s
32:	learn: 0.1910857	total: 1s	remaining: 29.4s
33:	learn: 0.1880066	total: 1.03s	remaining: 29.3s
34:	learn: 0.1849799	total: 1.06s	remaining: 29.3s
35:	learn: 0.1820468	total: 1.09s	remaining: 29.2s
36:	learn: 0.1792073	total: 1.12s	remaining: 29.3s
37:	learn: 0.1764609	total: 1.15s	remaining: 29.2s
38:	learn: 0.1737515	total: 1.19s	remaining: 29.4s
39:	learn: 0.1714302	total: 1.23s	remaining: 29.4s
40:	learn: 0.1690994	total: 1.25s	remaining: 29.4s
41:	learn: 0.1670369	total: 1.28s	remaining: 29.3s
42:	learn: 0.1647319	total: 1.31s	remaining: 29.2s
43:	learn: 0.1628612	total: 1.34s	remaining: 29.2s
44:	learn: 0.1607051	total: 1.37s	remaining: 29.1s
45:	learn: 0.1587652	total: 1.4s	remaining: 29.1s
46:	learn: 0.1570438	total: 1.43s	remaining: 29.1s
47:	learn: 0.1551951	total: 1.46s	remaining: 29s
48:	learn: 0.1535945	total: 1.49s	remaining: 29s
49:	learn: 0.1521438	total: 1.52s	remaining: 29s
50:	learn: 0.1504726	total: 1.56s	remaining: 29s
51:	learn: 0.1488485	total: 1.59s	remaining: 28.9s
52:	learn: 0.1472671	total: 1.63s	remaining: 29.1s
53:	learn: 0.1458652	total: 1.66s	remaining: 29s
54:	learn: 0.1444086	total: 1.68s	remaining: 28.9s
55:	learn: 0.1430318	total: 1.71s	remaining: 28.9s
56:	learn: 0.1416796	total: 1.74s	remaining: 28.9s
57:	learn: 0.1406790	total: 1.77s	remaining: 28.8s
58:	learn: 0.1394453	total: 1.81s	remaining: 28.8s
59:	learn: 0.1383964	total: 1.84s	remaining: 28.8s
60:	learn: 0.1372150	total: 1.86s	remaining: 28.7s
61:	learn: 0.1361572	total: 1.9s	remaining: 28.7s
62:	learn: 0.1351786	total: 1.93s	remaining: 28.7s
63:	learn: 0.1340607	total: 1.96s	remaining: 28.6s
64:	learn: 0.1331318	total: 1.99s	remaining: 28.6s
65:	learn: 0.1322082	total: 2.02s	remaining: 28.5s
66:	learn: 0.1313568	total: 2.04s	remaining: 28.5s
67:	learn: 0.1305132	total: 2.07s	remaining: 28.4s
68:	learn: 0.1297121	total: 2.1s	remaining: 28.4s
69:	learn: 0.1289505	total: 2.13s	remaining: 28.3s
70:	learn: 0.1282227	total: 2.16s	remaining: 28.3s
71:	learn: 0.1274773	total: 2.19s	remaining: 28.3s
72:	learn: 0.1266557	total: 2.22s	remaining: 28.2s
73:	learn: 0.1260510	total: 2.25s	remaining: 28.2s
74:	learn: 0.1253565	total: 2.28s	remaining: 28.2s
75:	learn: 0.1247533	total: 2.31s	remaining: 28.1s
76:	learn: 0.1238726	total: 2.34s	remaining: 28.1s
77:	learn: 0.1232802	total: 2.37s	remaining: 28s
78:	learn: 0.1226286	total: 2.4s	remaining: 28s
79:	learn: 0.1221168	total: 2.43s	remaining: 27.9s
80:	learn: 0.1214070	total: 2.46s	remaining: 27.9s
81:	learn: 0.1208296	total: 2.49s	remaining: 27.9s
82:	learn: 0.1202343	total: 2.52s	remaining: 27.9s
83:	learn: 0.1195721	total: 2.56s	remaining: 27.9s
84:	learn: 0.1188219	total: 2.59s	remaining: 27.8s
85:	learn: 0.1182145	total: 2.62s	remaining: 27.8s
86:	learn: 0.1175843	total: 2.65s	remaining: 27.8s
87:	learn: 0.1171648	total: 2.68s	remaining: 27.8s
88:	learn: 0.1166422	total: 2.71s	remaining: 27.8s
89:	learn: 0.1162775	total: 2.74s	remaining: 27.7s
90:	learn: 0.1156972	total: 2.77s	remaining: 27.7s
91:	learn: 0.1152978	total: 2.81s	remaining: 27.7s
92:	learn: 0.1148556	total: 2.84s	remaining: 27.7s
93:	learn: 0.1147560	total: 2.85s	remaining: 27.5s
94:	learn: 0.1141931	total: 2.88s	remaining: 27.5s
95:	learn: 0.1138699	total: 2.91s	remaining: 27.4s
96:	learn: 0.1134564	total: 2.94s	remaining: 27.4s
97:	learn: 0.1130010	total: 2.97s	remaining: 27.4s
98:	learn: 0.1126493	total: 3s	remaining: 27.3s
99:	learn: 0.1123160	total: 3.04s	remaining: 27.3s
100:	learn: 0.1120842	total: 3.06s	remaining: 27.3s
101:	learn: 0.1117718	total: 3.1s	remaining: 27.3s
102:	learn: 0.1113824	total: 3.13s	remaining: 27.2s
103:	learn: 0.1110877	total: 3.15s	remaining: 27.2s
104:	learn: 0.1106531	total: 3.19s	remaining: 27.2s
105:	learn: 0.1102195	total: 3.22s	remaining: 27.2s
106:	learn: 0.1097616	total: 3.25s	remaining: 27.1s
107:	learn: 0.1094180	total: 3.28s	remaining: 27.1s
108:	learn: 0.1091434	total: 3.32s	remaining: 27.2s
109:	learn: 0.1087821	total: 3.37s	remaining: 27.2s
110:	learn: 0.1084894	total: 3.4s	remaining: 27.2s
111:	learn: 0.1082338	total: 3.42s	remaining: 27.1s
112:	learn: 0.1078666	total: 3.45s	remaining: 27.1s
113:	learn: 0.1074424	total: 3.49s	remaining: 27.1s
114:	learn: 0.1072128	total: 3.52s	remaining: 27.1s
115:	learn: 0.1068838	total: 3.55s	remaining: 27s
116:	learn: 0.1066247	total: 3.58s	remaining: 27s
117:	learn: 0.1064261	total: 3.61s	remaining: 27s
118:	learn: 0.1060901	total: 3.64s	remaining: 27s
119:	learn: 0.1057086	total: 3.67s	remaining: 26.9s
120:	learn: 0.1053639	total: 3.7s	remaining: 26.9s
121:	learn: 0.1050275	total: 3.73s	remaining: 26.9s
122:	learn: 0.1046849	total: 3.76s	remaining: 26.8s
123:	learn: 0.1044792	total: 3.79s	remaining: 26.8s
124:	learn: 0.1042750	total: 3.82s	remaining: 26.8s
125:	learn: 0.1039879	total: 3.85s	remaining: 26.7s
126:	learn: 0.1037218	total: 3.88s	remaining: 26.7s
127:	learn: 0.1034968	total: 3.91s	remaining: 26.7s
128:	learn: 0.1032157	total: 3.94s	remaining: 26.6s
129:	learn: 0.1030204	total: 3.97s	remaining: 26.6s
130:	learn: 0.1028430	total: 4s	remaining: 26.6s
131:	learn: 0.1025882	total: 4.04s	remaining: 26.6s
132:	learn: 0.1023617	total: 4.07s	remaining: 26.5s
133:	learn: 0.1020816	total: 4.1s	remaining: 26.5s
134:	learn: 0.1018401	total: 4.13s	remaining: 26.4s
135:	learn: 0.1015342	total: 4.16s	remaining: 26.4s
136:	learn: 0.1013602	total: 4.19s	remaining: 26.4s
137:	learn: 0.1011872	total: 4.22s	remaining: 26.4s
138:	learn: 0.1009894	total: 4.28s	remaining: 26.5s
139:	learn: 0.1007390	total: 4.31s	remaining: 26.5s
140:	learn: 0.1005902	total: 4.34s	remaining: 26.5s
141:	learn: 0.1003022	total: 4.37s	remaining: 26.4s
142:	learn: 0.1001627	total: 4.4s	remaining: 26.4s
143:	learn: 0.1000304	total: 4.43s	remaining: 26.3s
144:	learn: 0.0997171	total: 4.46s	remaining: 26.3s
145:	learn: 0.0994890	total: 4.49s	remaining: 26.2s
146:	learn: 0.0993735	total: 4.52s	remaining: 26.2s
147:	learn: 0.0991547	total: 4.55s	remaining: 26.2s
148:	learn: 0.0989212	total: 4.58s	remaining: 26.2s
149:	learn: 0.0987591	total: 4.61s	remaining: 26.1s
150:	learn: 0.0985299	total: 4.64s	remaining: 26.1s
151:	learn: 0.0982960	total: 4.67s	remaining: 26.1s
152:	learn: 0.0982505	total: 4.69s	remaining: 26s
153:	learn: 0.0980141	total: 4.72s	remaining: 25.9s
154:	learn: 0.0978305	total: 4.75s	remaining: 25.9s
155:	learn: 0.0976620	total: 4.78s	remaining: 25.9s
156:	learn: 0.0974028	total: 4.81s	remaining: 25.9s
157:	learn: 0.0972042	total: 4.84s	remaining: 25.8s
158:	learn: 0.0969949	total: 4.88s	remaining: 25.8s
159:	learn: 0.0967537	total: 4.91s	remaining: 25.8s
160:	learn: 0.0966749	total: 4.94s	remaining: 25.8s
161:	learn: 0.0964696	total: 4.97s	remaining: 25.7s
162:	learn: 0.0962143	total: 5s	remaining: 25.7s
163:	learn: 0.0960660	total: 5.03s	remaining: 25.7s
164:	learn: 0.0958726	total: 5.07s	remaining: 25.6s
165:	learn: 0.0957006	total: 5.1s	remaining: 25.6s
166:	learn: 0.0954840	total: 5.13s	remaining: 25.6s
167:	learn: 0.0952827	total: 5.18s	remaining: 25.6s
168:	learn: 0.0950787	total: 5.21s	remaining: 25.6s
169:	learn: 0.0948308	total: 5.24s	remaining: 25.6s
170:	learn: 0.0946618	total: 5.26s	remaining: 25.5s
171:	learn: 0.0944428	total: 5.3s	remaining: 25.5s
172:	learn: 0.0943013	total: 5.33s	remaining: 25.5s
173:	learn: 0.0941060	total: 5.36s	remaining: 25.4s
174:	learn: 0.0939587	total: 5.39s	remaining: 25.4s
175:	learn: 0.0937842	total: 5.42s	remaining: 25.4s
176:	learn: 0.0936447	total: 5.45s	remaining: 25.3s
177:	learn: 0.0934685	total: 5.51s	remaining: 25.5s
178:	learn: 0.0933051	total: 5.54s	remaining: 25.4s
179:	learn: 0.0931644	total: 5.58s	remaining: 25.4s
180:	learn: 0.0930967	total: 5.61s	remaining: 25.4s
181:	learn: 0.0928822	total: 5.64s	remaining: 25.3s
182:	learn: 0.0928007	total: 5.67s	remaining: 25.3s
183:	learn: 0.0926616	total: 5.7s	remaining: 25.3s
184:	learn: 0.0924779	total: 5.73s	remaining: 25.3s
185:	learn: 0.0922669	total: 5.76s	remaining: 25.2s
186:	learn: 0.0920667	total: 5.79s	remaining: 25.2s
187:	learn: 0.0919997	total: 5.83s	remaining: 25.2s
188:	learn: 0.0918687	total: 5.86s	remaining: 25.1s
189:	learn: 0.0917193	total: 5.88s	remaining: 25.1s
190:	learn: 0.0916114	total: 5.92s	remaining: 25.1s
191:	learn: 0.0913699	total: 5.95s	remaining: 25s
192:	learn: 0.0912479	total: 5.97s	remaining: 25s
193:	learn: 0.0911525	total: 6.01s	remaining: 25s
194:	learn: 0.0910473	total: 6.04s	remaining: 24.9s
195:	learn: 0.0909828	total: 6.07s	remaining: 24.9s
196:	learn: 0.0909268	total: 6.1s	remaining: 24.9s
197:	learn: 0.0907991	total: 6.13s	remaining: 24.8s
198:	learn: 0.0906280	total: 6.16s	remaining: 24.8s
199:	learn: 0.0904349	total: 6.19s	remaining: 24.8s
200:	learn: 0.0903297	total: 6.22s	remaining: 24.7s
201:	learn: 0.0900975	total: 6.25s	remaining: 24.7s
202:	learn: 0.0899604	total: 6.28s	remaining: 24.7s
203:	learn: 0.0898315	total: 6.31s	remaining: 24.6s
204:	learn: 0.0896704	total: 6.34s	remaining: 24.6s
205:	learn: 0.0894031	total: 6.37s	remaining: 24.6s
206:	learn: 0.0893231	total: 6.4s	remaining: 24.5s
207:	learn: 0.0891650	total: 6.44s	remaining: 24.5s
208:	learn: 0.0890566	total: 6.47s	remaining: 24.5s
209:	learn: 0.0889030	total: 6.5s	remaining: 24.4s
210:	learn: 0.0888295	total: 6.53s	remaining: 24.4s
211:	learn: 0.0887168	total: 6.56s	remaining: 24.4s
212:	learn: 0.0885829	total: 6.59s	remaining: 24.3s
213:	learn: 0.0885335	total: 6.62s	remaining: 24.3s
214:	learn: 0.0883839	total: 6.65s	remaining: 24.3s
215:	learn: 0.0882890	total: 6.69s	remaining: 24.3s
216:	learn: 0.0881997	total: 6.72s	remaining: 24.2s
217:	learn: 0.0880846	total: 6.75s	remaining: 24.2s
218:	learn: 0.0879329	total: 6.78s	remaining: 24.2s
219:	learn: 0.0878338	total: 6.81s	remaining: 24.2s
220:	learn: 0.0877611	total: 6.84s	remaining: 24.1s
221:	learn: 0.0876499	total: 6.88s	remaining: 24.1s
222:	learn: 0.0875166	total: 6.91s	remaining: 24.1s
223:	learn: 0.0873843	total: 6.93s	remaining: 24s
224:	learn: 0.0873383	total: 6.96s	remaining: 24s
225:	learn: 0.0872352	total: 6.99s	remaining: 24s
226:	learn: 0.0870878	total: 7.03s	remaining: 23.9s
227:	learn: 0.0868984	total: 7.06s	remaining: 23.9s
228:	learn: 0.0868152	total: 7.09s	remaining: 23.9s
229:	learn: 0.0866759	total: 7.12s	remaining: 23.8s
230:	learn: 0.0866225	total: 7.15s	remaining: 23.8s
231:	learn: 0.0865279	total: 7.18s	remaining: 23.8s
232:	learn: 0.0864126	total: 7.21s	remaining: 23.7s
233:	learn: 0.0862440	total: 7.25s	remaining: 23.7s
234:	learn: 0.0860241	total: 7.28s	remaining: 23.7s
235:	learn: 0.0859266	total: 7.31s	remaining: 23.7s
236:	learn: 0.0858261	total: 7.34s	remaining: 23.6s
237:	learn: 0.0857795	total: 7.37s	remaining: 23.6s
238:	learn: 0.0856995	total: 7.4s	remaining: 23.6s
239:	learn: 0.0854824	total: 7.43s	remaining: 23.5s
240:	learn: 0.0853911	total: 7.46s	remaining: 23.5s
241:	learn: 0.0851787	total: 7.49s	remaining: 23.5s
242:	learn: 0.0850751	total: 7.52s	remaining: 23.4s
243:	learn: 0.0850538	total: 7.55s	remaining: 23.4s
244:	learn: 0.0849366	total: 7.58s	remaining: 23.4s
245:	learn: 0.0848107	total: 7.61s	remaining: 23.3s
246:	learn: 0.0847096	total: 7.65s	remaining: 23.3s
247:	learn: 0.0846025	total: 7.69s	remaining: 23.3s
248:	learn: 0.0845724	total: 7.72s	remaining: 23.3s
249:	learn: 0.0843906	total: 7.76s	remaining: 23.3s
250:	learn: 0.0843291	total: 7.79s	remaining: 23.3s
251:	learn: 0.0842889	total: 7.82s	remaining: 23.2s
252:	learn: 0.0841881	total: 7.85s	remaining: 23.2s
253:	learn: 0.0841420	total: 7.88s	remaining: 23.1s
254:	learn: 0.0840383	total: 7.91s	remaining: 23.1s
255:	learn: 0.0838793	total: 7.94s	remaining: 23.1s
256:	learn: 0.0837150	total: 7.97s	remaining: 23s
257:	learn: 0.0836112	total: 8s	remaining: 23s
258:	learn: 0.0835939	total: 8.03s	remaining: 23s
259:	learn: 0.0835409	total: 8.06s	remaining: 23s
260:	learn: 0.0834568	total: 8.1s	remaining: 22.9s
261:	learn: 0.0833658	total: 8.13s	remaining: 22.9s
262:	learn: 0.0832048	total: 8.16s	remaining: 22.9s
263:	learn: 0.0831887	total: 8.19s	remaining: 22.8s
264:	learn: 0.0830803	total: 8.21s	remaining: 22.8s
265:	learn: 0.0829243	total: 8.25s	remaining: 22.8s
266:	learn: 0.0828580	total: 8.27s	remaining: 22.7s
267:	learn: 0.0827193	total: 8.3s	remaining: 22.7s
268:	learn: 0.0826989	total: 8.33s	remaining: 22.6s
269:	learn: 0.0825044	total: 8.36s	remaining: 22.6s
270:	learn: 0.0824554	total: 8.4s	remaining: 22.6s
271:	learn: 0.0822710	total: 8.43s	remaining: 22.6s
272:	learn: 0.0821029	total: 8.46s	remaining: 22.5s
273:	learn: 0.0820407	total: 8.49s	remaining: 22.5s
274:	learn: 0.0819611	total: 8.52s	remaining: 22.5s
275:	learn: 0.0819188	total: 8.55s	remaining: 22.4s
276:	learn: 0.0818734	total: 8.58s	remaining: 22.4s
277:	learn: 0.0817717	total: 8.62s	remaining: 22.4s
278:	learn: 0.0816772	total: 8.65s	remaining: 22.4s
279:	learn: 0.0815875	total: 8.69s	remaining: 22.3s
280:	learn: 0.0815603	total: 8.71s	remaining: 22.3s
281:	learn: 0.0814159	total: 8.75s	remaining: 22.3s
282:	learn: 0.0813318	total: 8.79s	remaining: 22.3s
283:	learn: 0.0812348	total: 8.82s	remaining: 22.2s
284:	learn: 0.0811494	total: 8.85s	remaining: 22.2s
285:	learn: 0.0810483	total: 8.88s	remaining: 22.2s
286:	learn: 0.0809664	total: 8.91s	remaining: 22.1s
287:	learn: 0.0808221	total: 8.94s	remaining: 22.1s
288:	learn: 0.0807032	total: 8.97s	remaining: 22.1s
289:	learn: 0.0806799	total: 9s	remaining: 22s
290:	learn: 0.0806364	total: 9.03s	remaining: 22s
291:	learn: 0.0804345	total: 9.07s	remaining: 22s
292:	learn: 0.0803637	total: 9.1s	remaining: 22s
293:	learn: 0.0803324	total: 9.13s	remaining: 21.9s
294:	learn: 0.0803053	total: 9.16s	remaining: 21.9s
295:	learn: 0.0801375	total: 9.19s	remaining: 21.9s
296:	learn: 0.0801102	total: 9.22s	remaining: 21.8s
297:	learn: 0.0799829	total: 9.25s	remaining: 21.8s
298:	learn: 0.0799112	total: 9.28s	remaining: 21.8s
299:	learn: 0.0798399	total: 9.31s	remaining: 21.7s
300:	learn: 0.0798202	total: 9.34s	remaining: 21.7s
301:	learn: 0.0796824	total: 9.38s	remaining: 21.7s
302:	learn: 0.0796119	total: 9.41s	remaining: 21.6s
303:	learn: 0.0795323	total: 9.44s	remaining: 21.6s
304:	learn: 0.0794501	total: 9.47s	remaining: 21.6s
305:	learn: 0.0792079	total: 9.5s	remaining: 21.5s
306:	learn: 0.0791568	total: 9.53s	remaining: 21.5s
307:	learn: 0.0791330	total: 9.56s	remaining: 21.5s
308:	learn: 0.0789927	total: 9.59s	remaining: 21.5s
309:	learn: 0.0788531	total: 9.62s	remaining: 21.4s
310:	learn: 0.0787510	total: 9.66s	remaining: 21.4s
311:	learn: 0.0787257	total: 9.69s	remaining: 21.4s
312:	learn: 0.0786449	total: 9.73s	remaining: 21.4s
313:	learn: 0.0785757	total: 9.76s	remaining: 21.3s
314:	learn: 0.0784504	total: 9.8s	remaining: 21.3s
315:	learn: 0.0784306	total: 9.83s	remaining: 21.3s
316:	learn: 0.0783104	total: 9.86s	remaining: 21.3s
317:	learn: 0.0782913	total: 9.89s	remaining: 21.2s
318:	learn: 0.0782190	total: 9.93s	remaining: 21.2s
319:	learn: 0.0781652	total: 9.96s	remaining: 21.2s
320:	learn: 0.0781413	total: 9.99s	remaining: 21.1s
321:	learn: 0.0780066	total: 10s	remaining: 21.1s
322:	learn: 0.0779551	total: 10.1s	remaining: 21.1s
323:	learn: 0.0779363	total: 10.1s	remaining: 21.1s
324:	learn: 0.0778732	total: 10.1s	remaining: 21s
325:	learn: 0.0778511	total: 10.2s	remaining: 21s
326:	learn: 0.0777625	total: 10.2s	remaining: 21s
327:	learn: 0.0777414	total: 10.2s	remaining: 21s
328:	learn: 0.0776912	total: 10.3s	remaining: 20.9s
329:	learn: 0.0775897	total: 10.3s	remaining: 20.9s
330:	learn: 0.0775698	total: 10.3s	remaining: 20.9s
331:	learn: 0.0774360	total: 10.4s	remaining: 20.8s
332:	learn: 0.0773379	total: 10.4s	remaining: 20.8s
333:	learn: 0.0772661	total: 10.4s	remaining: 20.8s
334:	learn: 0.0771301	total: 10.5s	remaining: 20.7s
335:	learn: 0.0770150	total: 10.5s	remaining: 20.7s
336:	learn: 0.0769448	total: 10.5s	remaining: 20.7s
337:	learn: 0.0769249	total: 10.5s	remaining: 20.6s
338:	learn: 0.0767863	total: 10.6s	remaining: 20.6s
339:	learn: 0.0767577	total: 10.6s	remaining: 20.6s
340:	learn: 0.0766651	total: 10.6s	remaining: 20.5s
341:	learn: 0.0766455	total: 10.7s	remaining: 20.5s
342:	learn: 0.0766204	total: 10.7s	remaining: 20.5s
343:	learn: 0.0764591	total: 10.7s	remaining: 20.4s
344:	learn: 0.0763921	total: 10.8s	remaining: 20.4s
345:	learn: 0.0763010	total: 10.8s	remaining: 20.4s
346:	learn: 0.0762209	total: 10.8s	remaining: 20.4s
347:	learn: 0.0761353	total: 10.8s	remaining: 20.3s
348:	learn: 0.0760514	total: 10.9s	remaining: 20.3s
349:	learn: 0.0759366	total: 10.9s	remaining: 20.3s
350:	learn: 0.0759095	total: 10.9s	remaining: 20.2s
351:	learn: 0.0757998	total: 11s	remaining: 20.2s
352:	learn: 0.0757444	total: 11s	remaining: 20.2s
353:	learn: 0.0756449	total: 11s	remaining: 20.1s
354:	learn: 0.0755537	total: 11.1s	remaining: 20.1s
355:	learn: 0.0755105	total: 11.1s	remaining: 20.1s
356:	learn: 0.0753519	total: 11.1s	remaining: 20s
357:	learn: 0.0753334	total: 11.2s	remaining: 20s
358:	learn: 0.0752114	total: 11.2s	remaining: 20s
359:	learn: 0.0751398	total: 11.2s	remaining: 19.9s
360:	learn: 0.0750806	total: 11.2s	remaining: 19.9s
361:	learn: 0.0749485	total: 11.3s	remaining: 19.9s
362:	learn: 0.0749324	total: 11.3s	remaining: 19.8s
363:	learn: 0.0749166	total: 11.3s	remaining: 19.8s
364:	learn: 0.0748983	total: 11.4s	remaining: 19.8s
365:	learn: 0.0748643	total: 11.4s	remaining: 19.8s
366:	learn: 0.0748344	total: 11.4s	remaining: 19.7s
367:	learn: 0.0748114	total: 11.5s	remaining: 19.7s
368:	learn: 0.0746833	total: 11.5s	remaining: 19.6s
369:	learn: 0.0746085	total: 11.5s	remaining: 19.6s
370:	learn: 0.0745465	total: 11.6s	remaining: 19.6s
371:	learn: 0.0744976	total: 11.6s	remaining: 19.6s
372:	learn: 0.0744198	total: 11.6s	remaining: 19.5s
373:	learn: 0.0744049	total: 11.7s	remaining: 19.5s
374:	learn: 0.0743805	total: 11.7s	remaining: 19.5s
375:	learn: 0.0743325	total: 11.7s	remaining: 19.4s
376:	learn: 0.0742717	total: 11.8s	remaining: 19.4s
377:	learn: 0.0742038	total: 11.8s	remaining: 19.4s
378:	learn: 0.0740558	total: 11.8s	remaining: 19.4s
379:	learn: 0.0739597	total: 11.8s	remaining: 19.3s
380:	learn: 0.0738386	total: 11.9s	remaining: 19.3s
381:	learn: 0.0737861	total: 11.9s	remaining: 19.3s
382:	learn: 0.0737132	total: 12s	remaining: 19.3s
383:	learn: 0.0736402	total: 12s	remaining: 19.2s
384:	learn: 0.0735806	total: 12s	remaining: 19.2s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'HeatingQC': 1 unseen categories converted to Unseen on transform.

CV folds:  32%|███▏      | 16/50 [08:27<18:12, 32.12s/fold]

999:	learn: 0.0436029	total: 31.7s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3871534	total: 26.1ms	remaining: 26s
1:	learn: 0.3772227	total: 56.7ms	remaining: 28.3s
2:	learn: 0.3668409	total: 87.1ms	remaining: 28.9s
3:	learn: 0.3563959	total: 121ms	remaining: 30.2s
4:	learn: 0.3472590	total: 149ms	remaining: 29.7s
5:	learn: 0.3382318	total: 178ms	remaining: 29.4s
6:	learn: 0.3290367	total: 206ms	remaining: 29.3s
7:	learn: 0.3203771	total: 236ms	remaining: 29.3s
8:	learn: 0.3120533	total: 266ms	remaining: 29.2s
9:	learn: 0.3045890	total: 293ms	remaining: 29s
10:	learn: 0.2974156	total: 325ms	remaining: 29.2s
11:	learn: 0.2899296	total: 351ms	remaining: 28.9s
12:	learn: 0.2829148	total: 380ms	remaining: 28.8s
13:	learn: 0.2760961	total: 411ms	remaining: 28.9s
14:	learn: 0.2696535	total: 440ms	remaining: 28.9s
15:	learn: 0.2633659	total: 470ms	remaining: 28.9s
16:	learn: 0.2576489	total: 501ms	remaining: 29s
17:	learn: 0.2520097	total: 536ms	remaining: 29.2s
18:	learn: 0.2470226	total: 565ms	remaining: 29.2s
19:	learn: 0.2417392	total: 594ms	remaining: 29.1s
20:	learn: 0.2369945	total: 624ms	remaining: 29.1s
21:	learn: 0.2320417	total: 653ms	remaining: 29s
22:	learn: 0.2277122	total: 686ms	remaining: 29.1s
23:	learn: 0.2230363	total: 716ms	remaining: 29.1s
24:	learn: 0.2187517	total: 748ms	remaining: 29.2s
25:	learn: 0.2147158	total: 777ms	remaining: 29.1s
26:	learn: 0.2107002	total: 809ms	remaining: 29.1s
27:	learn: 0.2072663	total: 837ms	remaining: 29.1s
28:	learn: 0.2035830	total: 872ms	remaining: 29.2s
29:	learn: 0.2002960	total: 904ms	remaining: 29.2s
30:	learn: 0.1964739	total: 932ms	remaining: 29.1s
31:	learn: 0.1933281	total: 962ms	remaining: 29.1s
32:	learn: 0.1903934	total: 991ms	remaining: 29s
33:	learn: 0.1874238	total: 1.02s	remaining: 28.9s
34:	learn: 0.1843656	total: 1.04s	remaining: 28.8s
35:	learn: 0.1813988	total: 1.07s	remaining: 28.8s
36:	learn: 0.1788092	total: 1.1s	remaining: 28.8s
37:	learn: 0.1758229	total: 1.14s	remaining: 28.8s
38:	learn: 0.1738799	total: 1.16s	remaining: 28.6s
39:	learn: 0.1715520	total: 1.19s	remaining: 28.5s
40:	learn: 0.1691916	total: 1.22s	remaining: 28.5s
41:	learn: 0.1670908	total: 1.24s	remaining: 28.4s
42:	learn: 0.1650175	total: 1.27s	remaining: 28.4s
43:	learn: 0.1632217	total: 1.3s	remaining: 28.3s
44:	learn: 0.1612937	total: 1.33s	remaining: 28.3s
45:	learn: 0.1593547	total: 1.36s	remaining: 28.3s
46:	learn: 0.1576390	total: 1.39s	remaining: 28.2s
47:	learn: 0.1558408	total: 1.42s	remaining: 28.2s
48:	learn: 0.1541309	total: 1.45s	remaining: 28.2s
49:	learn: 0.1525367	total: 1.48s	remaining: 28.2s
50:	learn: 0.1509080	total: 1.51s	remaining: 28.2s
51:	learn: 0.1496302	total: 1.55s	remaining: 28.3s
52:	learn: 0.1481651	total: 1.6s	remaining: 28.6s
53:	learn: 0.1466493	total: 1.63s	remaining: 28.5s
54:	learn: 0.1452486	total: 1.66s	remaining: 28.5s
55:	learn: 0.1439044	total: 1.69s	remaining: 28.5s
56:	learn: 0.1428042	total: 1.72s	remaining: 28.5s
57:	learn: 0.1415592	total: 1.75s	remaining: 28.5s
58:	learn: 0.1404397	total: 1.8s	remaining: 28.7s
59:	learn: 0.1393611	total: 1.84s	remaining: 28.9s
60:	learn: 0.1383488	total: 1.87s	remaining: 28.8s
61:	learn: 0.1373308	total: 1.9s	remaining: 28.8s
62:	learn: 0.1363864	total: 1.93s	remaining: 28.7s
63:	learn: 0.1355283	total: 1.96s	remaining: 28.6s
64:	learn: 0.1345774	total: 1.98s	remaining: 28.5s
65:	learn: 0.1335031	total: 2.01s	remaining: 28.5s
66:	learn: 0.1326673	total: 2.04s	remaining: 28.5s
67:	learn: 0.1319235	total: 2.07s	remaining: 28.4s
68:	learn: 0.1312651	total: 2.1s	remaining: 28.3s
69:	learn: 0.1305640	total: 2.13s	remaining: 28.3s
70:	learn: 0.1297894	total: 2.16s	remaining: 28.2s
71:	learn: 0.1291193	total: 2.19s	remaining: 28.2s
72:	learn: 0.1283716	total: 2.21s	remaining: 28.1s
73:	learn: 0.1277047	total: 2.24s	remaining: 28s
74:	learn: 0.1269237	total: 2.27s	remaining: 28s
75:	learn: 0.1263113	total: 2.3s	remaining: 28s
76:	learn: 0.1256350	total: 2.33s	remaining: 27.9s
77:	learn: 0.1249065	total: 2.36s	remaining: 27.9s
78:	learn: 0.1241903	total: 2.39s	remaining: 27.9s
79:	learn: 0.1235850	total: 2.42s	remaining: 27.8s
80:	learn: 0.1230127	total: 2.45s	remaining: 27.8s
81:	learn: 0.1225499	total: 2.5s	remaining: 28s
82:	learn: 0.1220648	total: 2.53s	remaining: 28s
83:	learn: 0.1216128	total: 2.56s	remaining: 27.9s
84:	learn: 0.1211697	total: 2.59s	remaining: 27.9s
85:	learn: 0.1205092	total: 2.62s	remaining: 27.9s
86:	learn: 0.1198888	total: 2.65s	remaining: 27.8s
87:	learn: 0.1191931	total: 2.68s	remaining: 27.8s
88:	learn: 0.1187363	total: 2.71s	remaining: 27.8s
89:	learn: 0.1181908	total: 2.74s	remaining: 27.8s
90:	learn: 0.1177642	total: 2.77s	remaining: 27.7s
91:	learn: 0.1171803	total: 2.8s	remaining: 27.7s
92:	learn: 0.1168187	total: 2.83s	remaining: 27.6s
93:	learn: 0.1163917	total: 2.86s	remaining: 27.6s
94:	learn: 0.1157693	total: 2.89s	remaining: 27.5s
95:	learn: 0.1154403	total: 2.92s	remaining: 27.5s
96:	learn: 0.1149954	total: 2.96s	remaining: 27.6s
97:	learn: 0.1144592	total: 2.99s	remaining: 27.5s
98:	learn: 0.1139058	total: 3.02s	remaining: 27.5s
99:	learn: 0.1133665	total: 3.05s	remaining: 27.5s
100:	learn: 0.1129807	total: 3.08s	remaining: 27.4s
101:	learn: 0.1126438	total: 3.11s	remaining: 27.4s
102:	learn: 0.1121995	total: 3.14s	remaining: 27.4s
103:	learn: 0.1117303	total: 3.17s	remaining: 27.3s
104:	learn: 0.1112585	total: 3.2s	remaining: 27.3s
105:	learn: 0.1110285	total: 3.23s	remaining: 27.2s
106:	learn: 0.1105331	total: 3.26s	remaining: 27.2s
107:	learn: 0.1101185	total: 3.29s	remaining: 27.2s
108:	learn: 0.1097899	total: 3.32s	remaining: 27.1s
109:	learn: 0.1095058	total: 3.34s	remaining: 27.1s
110:	learn: 0.1093089	total: 3.38s	remaining: 27s
111:	learn: 0.1089920	total: 3.4s	remaining: 27s
112:	learn: 0.1086842	total: 3.44s	remaining: 27s
113:	learn: 0.1084444	total: 3.46s	remaining: 26.9s
114:	learn: 0.1081518	total: 3.49s	remaining: 26.9s
115:	learn: 0.1078872	total: 3.53s	remaining: 26.9s
116:	learn: 0.1075709	total: 3.56s	remaining: 26.9s
117:	learn: 0.1072107	total: 3.59s	remaining: 26.8s
118:	learn: 0.1069078	total: 3.62s	remaining: 26.8s
119:	learn: 0.1066049	total: 3.65s	remaining: 26.8s
120:	learn: 0.1063937	total: 3.68s	remaining: 26.8s
121:	learn: 0.1062606	total: 3.72s	remaining: 26.8s
122:	learn: 0.1060116	total: 3.76s	remaining: 26.8s
123:	learn: 0.1058268	total: 3.78s	remaining: 26.7s
124:	learn: 0.1055386	total: 3.81s	remaining: 26.6s
125:	learn: 0.1052809	total: 3.84s	remaining: 26.6s
126:	learn: 0.1050104	total: 3.87s	remaining: 26.6s
127:	learn: 0.1048313	total: 3.9s	remaining: 26.6s
128:	learn: 0.1045836	total: 3.93s	remaining: 26.5s
129:	learn: 0.1042739	total: 3.96s	remaining: 26.5s
130:	learn: 0.1040189	total: 4s	remaining: 26.6s
131:	learn: 0.1037782	total: 4.04s	remaining: 26.5s
132:	learn: 0.1036080	total: 4.07s	remaining: 26.5s
133:	learn: 0.1034281	total: 4.09s	remaining: 26.5s
134:	learn: 0.1031347	total: 4.12s	remaining: 26.4s
135:	learn: 0.1028845	total: 4.15s	remaining: 26.4s
136:	learn: 0.1027266	total: 4.19s	remaining: 26.4s
137:	learn: 0.1024736	total: 4.22s	remaining: 26.3s
138:	learn: 0.1022418	total: 4.25s	remaining: 26.3s
139:	learn: 0.1020554	total: 4.28s	remaining: 26.3s
140:	learn: 0.1017517	total: 4.31s	remaining: 26.2s
141:	learn: 0.1015203	total: 4.33s	remaining: 26.2s
142:	learn: 0.1013434	total: 4.36s	remaining: 26.1s
143:	learn: 0.1009699	total: 4.39s	remaining: 26.1s
144:	learn: 0.1008326	total: 4.42s	remaining: 26.1s
145:	learn: 0.1004814	total: 4.45s	remaining: 26s
146:	learn: 0.1003717	total: 4.48s	remaining: 26s
147:	learn: 0.1002149	total: 4.52s	remaining: 26s
148:	learn: 0.1001078	total: 4.55s	remaining: 26s
149:	learn: 0.0999918	total: 4.58s	remaining: 25.9s
150:	learn: 0.0998068	total: 4.61s	remaining: 25.9s
151:	learn: 0.0996448	total: 4.64s	remaining: 25.9s
152:	learn: 0.0995610	total: 4.67s	remaining: 25.8s
153:	learn: 0.0993637	total: 4.7s	remaining: 25.8s
154:	learn: 0.0991859	total: 4.73s	remaining: 25.8s
155:	learn: 0.0989569	total: 4.76s	remaining: 25.8s
156:	learn: 0.0987878	total: 4.79s	remaining: 25.7s
157:	learn: 0.0986257	total: 4.82s	remaining: 25.7s
158:	learn: 0.0983871	total: 4.85s	remaining: 25.7s
159:	learn: 0.0982137	total: 4.88s	remaining: 25.6s
160:	learn: 0.0979742	total: 4.91s	remaining: 25.6s
161:	learn: 0.0978446	total: 4.94s	remaining: 25.6s
162:	learn: 0.0976728	total: 4.97s	remaining: 25.5s
163:	learn: 0.0976379	total: 5s	remaining: 25.5s
164:	learn: 0.0975110	total: 5.03s	remaining: 25.5s
165:	learn: 0.0974199	total: 5.06s	remaining: 25.4s
166:	learn: 0.0971543	total: 5.09s	remaining: 25.4s
167:	learn: 0.0969645	total: 5.12s	remaining: 25.4s
168:	learn: 0.0968126	total: 5.15s	remaining: 25.3s
169:	learn: 0.0966061	total: 5.18s	remaining: 25.3s
170:	learn: 0.0964496	total: 5.21s	remaining: 25.3s
171:	learn: 0.0962993	total: 5.24s	remaining: 25.2s
172:	learn: 0.0961692	total: 5.27s	remaining: 25.2s
173:	learn: 0.0960167	total: 5.3s	remaining: 25.2s
174:	learn: 0.0959046	total: 5.33s	remaining: 25.1s
175:	learn: 0.0957847	total: 5.36s	remaining: 25.1s
176:	learn: 0.0956583	total: 5.4s	remaining: 25.1s
177:	learn: 0.0955188	total: 5.43s	remaining: 25.1s
178:	learn: 0.0953837	total: 5.46s	remaining: 25s
179:	learn: 0.0952876	total: 5.49s	remaining: 25s
180:	learn: 0.0951567	total: 5.52s	remaining: 25s
181:	learn: 0.0950725	total: 5.55s	remaining: 24.9s
182:	learn: 0.0950046	total: 5.58s	remaining: 24.9s
183:	learn: 0.0949862	total: 5.62s	remaining: 24.9s
184:	learn: 0.0949174	total: 5.64s	remaining: 24.9s
185:	learn: 0.0947869	total: 5.67s	remaining: 24.8s
186:	learn: 0.0946888	total: 5.7s	remaining: 24.8s
187:	learn: 0.0945953	total: 5.73s	remaining: 24.8s
188:	learn: 0.0944379	total: 5.76s	remaining: 24.7s
189:	learn: 0.0942374	total: 5.79s	remaining: 24.7s
190:	learn: 0.0940548	total: 5.82s	remaining: 24.7s
191:	learn: 0.0939564	total: 5.85s	remaining: 24.6s
192:	learn: 0.0937753	total: 5.89s	remaining: 24.6s
193:	learn: 0.0937474	total: 5.92s	remaining: 24.6s
194:	learn: 0.0936195	total: 5.95s	remaining: 24.6s
195:	learn: 0.0935553	total: 5.99s	remaining: 24.6s
196:	learn: 0.0933147	total: 6.02s	remaining: 24.5s
197:	learn: 0.0932266	total: 6.05s	remaining: 24.5s
198:	learn: 0.0930169	total: 6.08s	remaining: 24.5s
199:	learn: 0.0928445	total: 6.11s	remaining: 24.4s
200:	learn: 0.0927077	total: 6.14s	remaining: 24.4s
201:	learn: 0.0925278	total: 6.17s	remaining: 24.4s
202:	learn: 0.0923523	total: 6.2s	remaining: 24.3s
203:	learn: 0.0922091	total: 6.23s	remaining: 24.3s
204:	learn: 0.0921302	total: 6.26s	remaining: 24.3s
205:	learn: 0.0920027	total: 6.29s	remaining: 24.2s
206:	learn: 0.0919055	total: 6.32s	remaining: 24.2s
207:	learn: 0.0916950	total: 6.35s	remaining: 24.2s
208:	learn: 0.0916375	total: 6.37s	remaining: 24.1s
209:	learn: 0.0915059	total: 6.4s	remaining: 24.1s
210:	learn: 0.0913366	total: 6.43s	remaining: 24.1s
211:	learn: 0.0912063	total: 6.46s	remaining: 24s
212:	learn: 0.0910331	total: 6.5s	remaining: 24s
213:	learn: 0.0909016	total: 6.53s	remaining: 24s
214:	learn: 0.0908370	total: 6.56s	remaining: 23.9s
215:	learn: 0.0907310	total: 6.59s	remaining: 23.9s
216:	learn: 0.0905900	total: 6.62s	remaining: 23.9s
217:	learn: 0.0904804	total: 6.65s	remaining: 23.9s
218:	learn: 0.0904294	total: 6.68s	remaining: 23.8s
219:	learn: 0.0902498	total: 6.71s	remaining: 23.8s
220:	learn: 0.0901542	total: 6.75s	remaining: 23.8s
221:	learn: 0.0901049	total: 6.78s	remaining: 23.7s
222:	learn: 0.0899523	total: 6.8s	remaining: 23.7s
223:	learn: 0.0899226	total: 6.83s	remaining: 23.7s
224:	learn: 0.0898019	total: 6.86s	remaining: 23.6s
225:	learn: 0.0897557	total: 6.89s	remaining: 23.6s
226:	learn: 0.0895176	total: 6.92s	remaining: 23.6s
227:	learn: 0.0894763	total: 6.95s	remaining: 23.5s
228:	learn: 0.0893264	total: 6.98s	remaining: 23.5s
229:	learn: 0.0892885	total: 7.01s	remaining: 23.5s
230:	learn: 0.0891173	total: 7.04s	remaining: 23.4s
231:	learn: 0.0891091	total: 7.07s	remaining: 23.4s
232:	learn: 0.0890525	total: 7.1s	remaining: 23.4s
233:	learn: 0.0888884	total: 7.13s	remaining: 23.3s
234:	learn: 0.0888574	total: 7.16s	remaining: 23.3s
235:	learn: 0.0888402	total: 7.19s	remaining: 23.3s
236:	learn: 0.0887697	total: 7.22s	remaining: 23.3s
237:	learn: 0.0886073	total: 7.25s	remaining: 23.2s
238:	learn: 0.0885293	total: 7.28s	remaining: 23.2s
239:	learn: 0.0884698	total: 7.31s	remaining: 23.2s
240:	learn: 0.0884221	total: 7.34s	remaining: 23.1s
241:	learn: 0.0882053	total: 7.38s	remaining: 23.1s
242:	learn: 0.0881554	total: 7.41s	remaining: 23.1s
243:	learn: 0.0879976	total: 7.44s	remaining: 23.1s
244:	learn: 0.0879821	total: 7.47s	remaining: 23s
245:	learn: 0.0879765	total: 7.5s	remaining: 23s
246:	learn: 0.0878843	total: 7.54s	remaining: 23s
247:	learn: 0.0876652	total: 7.57s	remaining: 22.9s
248:	learn: 0.0875077	total: 7.6s	remaining: 22.9s
249:	learn: 0.0874724	total: 7.62s	remaining: 22.9s
250:	learn: 0.0874286	total: 7.66s	remaining: 22.9s
251:	learn: 0.0873893	total: 7.7s	remaining: 22.8s
252:	learn: 0.0873485	total: 7.73s	remaining: 22.8s
253:	learn: 0.0872736	total: 7.76s	remaining: 22.8s
254:	learn: 0.0870807	total: 7.79s	remaining: 22.8s
255:	learn: 0.0870367	total: 7.82s	remaining: 22.7s
256:	learn: 0.0870040	total: 7.85s	remaining: 22.7s
257:	learn: 0.0869287	total: 7.88s	remaining: 22.7s
258:	learn: 0.0869003	total: 7.91s	remaining: 22.6s
259:	learn: 0.0868813	total: 7.94s	remaining: 22.6s
260:	learn: 0.0868252	total: 7.97s	remaining: 22.6s
261:	learn: 0.0865989	total: 8s	remaining: 22.5s
262:	learn: 0.0865942	total: 8.06s	remaining: 22.6s
263:	learn: 0.0864454	total: 8.09s	remaining: 22.5s
264:	learn: 0.0862829	total: 8.13s	remaining: 22.6s
265:	learn: 0.0862633	total: 8.17s	remaining: 22.5s
266:	learn: 0.0861814	total: 8.2s	remaining: 22.5s
267:	learn: 0.0861656	total: 8.23s	remaining: 22.5s
268:	learn: 0.0861655	total: 8.27s	remaining: 22.5s
269:	learn: 0.0860713	total: 8.29s	remaining: 22.4s
270:	learn: 0.0860132	total: 8.32s	remaining: 22.4s
271:	learn: 0.0859353	total: 8.35s	remaining: 22.4s
272:	learn: 0.0858507	total: 8.38s	remaining: 22.3s
273:	learn: 0.0857820	total: 8.41s	remaining: 22.3s
274:	learn: 0.0857392	total: 8.44s	remaining: 22.3s
275:	learn: 0.0856333	total: 8.47s	remaining: 22.2s
276:	learn: 0.0855490	total: 8.51s	remaining: 22.2s
277:	learn: 0.0855396	total: 8.54s	remaining: 22.2s
278:	learn: 0.0854497	total: 8.57s	remaining: 22.1s
279:	learn: 0.0853414	total: 8.6s	remaining: 22.1s
280:	learn: 0.0852417	total: 8.63s	remaining: 22.1s
281:	learn: 0.0851570	total: 8.66s	remaining: 22.1s
282:	learn: 0.0850677	total: 8.69s	remaining: 22s
283:	learn: 0.0848869	total: 8.75s	remaining: 22.1s
284:	learn: 0.0848361	total: 8.78s	remaining: 22s
285:	learn: 0.0848285	total: 8.81s	remaining: 22s
286:	learn: 0.0847719	total: 8.84s	remaining: 22s
287:	learn: 0.0847241	total: 8.87s	remaining: 21.9s
288:	learn: 0.0847189	total: 8.9s	remaining: 21.9s
289:	learn: 0.0846531	total: 8.93s	remaining: 21.9s
290:	learn: 0.0846027	total: 8.97s	remaining: 21.8s
291:	learn: 0.0845857	total: 9s	remaining: 21.8s
292:	learn: 0.0845285	total: 9.03s	remaining: 21.8s
293:	learn: 0.0844529	total: 9.06s	remaining: 21.8s
294:	learn: 0.0844314	total: 9.09s	remaining: 21.7s
295:	learn: 0.0843748	total: 9.12s	remaining: 21.7s
296:	learn: 0.0842833	total: 9.15s	remaining: 21.6s
297:	learn: 0.0842335	total: 9.18s	remaining: 21.6s
298:	learn: 0.0841726	total: 9.21s	remaining: 21.6s
299:	learn: 0.0841582	total: 9.24s	remaining: 21.6s
300:	learn: 0.0841574	total: 9.28s	remaining: 21.5s
301:	learn: 0.0841126	total: 9.31s	remaining: 21.5s
302:	learn: 0.0838973	total: 9.34s	remaining: 21.5s
303:	learn: 0.0838023	total: 9.37s	remaining: 21.4s
304:	learn: 0.0837662	total: 9.4s	remaining: 21.4s
305:	learn: 0.0836234	total: 9.43s	remaining: 21.4s
306:	learn: 0.0835793	total: 9.46s	remaining: 21.4s
307:	learn: 0.0834728	total: 9.49s	remaining: 21.3s
308:	learn: 0.0834721	total: 9.53s	remaining: 21.3s
309:	learn: 0.0834559	total: 9.56s	remaining: 21.3s
310:	learn: 0.0832977	total: 9.59s	remaining: 21.2s
311:	learn: 0.0831948	total: 9.62s	remaining: 21.2s
312:	learn: 0.0831655	total: 9.65s	remaining: 21.2s
313:	learn: 0.0830979	total: 9.68s	remaining: 21.1s
314:	learn: 0.0830824	total: 9.71s	remaining: 21.1s
315:	learn: 0.0829196	total: 9.74s	remaining: 21.1s
316:	learn: 0.0829132	total: 9.77s	remaining: 21.1s
317:	learn: 0.0828783	total: 9.8s	remaining: 21s
318:	learn: 0.0828123	total: 9.83s	remaining: 21s
319:	learn: 0.0827707	total: 9.86s	remaining: 21s
320:	learn: 0.0826392	total: 9.89s	remaining: 20.9s
321:	learn: 0.0824622	total: 9.92s	remaining: 20.9s
322:	learn: 0.0824503	total: 9.95s	remaining: 20.9s
323:	learn: 0.0822954	total: 9.98s	remaining: 20.8s
324:	learn: 0.0822893	total: 10s	remaining: 20.8s
325:	learn: 0.0822772	total: 10s	remaining: 20.8s
326:	learn: 0.0821762	total: 10.1s	remaining: 20.7s
327:	learn: 0.0820367	total: 10.1s	remaining: 20.7s
328:	learn: 0.0819653	total: 10.1s	remaining: 20.7s
329:	learn: 0.0819577	total: 10.2s	remaining: 20.6s
330:	learn: 0.0819557	total: 10.2s	remaining: 20.6s
331:	learn: 0.0819291	total: 10.2s	remaining: 20.6s
332:	learn: 0.0818487	total: 10.3s	remaining: 20.6s
333:	learn: 0.0817626	total: 10.3s	remaining: 20.5s
334:	learn: 0.0817161	total: 10.3s	remaining: 20.5s
335:	learn: 0.0816510	total: 10.4s	remaining: 20.5s
336:	learn: 0.0816014	total: 10.4s	remaining: 20.5s
337:	learn: 0.0815161	total: 10.4s	remaining: 20.4s
338:	learn: 0.0814402	total: 10.5s	remaining: 20.4s
339:	learn: 0.0814136	total: 10.5s	remaining: 20.4s
340:	learn: 0.0814047	total: 10.5s	remaining: 20.3s
341:	learn: 0.0813911	total: 10.6s	remaining: 20.3s
342:	learn: 0.0813188	total: 10.6s	remaining: 20.3s
343:	learn: 0.0811323	total: 10.6s	remaining: 20.2s
344:	learn: 0.0811034	total: 10.6s	remaining: 20.2s
345:	learn: 0.0809519	total: 10.7s	remaining: 20.2s
346:	learn: 0.0807956	total: 10.7s	remaining: 20.1s
347:	learn: 0.0807052	total: 10.7s	remaining: 20.1s
348:	learn: 0.0805194	total: 10.8s	remaining: 20.1s
349:	learn: 0.0804390	total: 10.8s	remaining: 20s
350:	learn: 0.0804376	total: 10.8s	remaining: 20s
351:	learn: 0.0803130	total: 10.9s	remaining: 20s
352:	learn: 0.0802012	total: 10.9s	remaining: 19.9s
353:	learn: 0.0801621	total: 10.9s	remaining: 19.9s
354:	learn: 0.0800633	total: 10.9s	remaining: 19.9s
355:	learn: 0.0799354	total: 11s	remaining: 19.8s
356:	learn: 0.0797942	total: 11s	remaining: 19.8s
357:	learn: 0.0796761	total: 11s	remaining: 19.8s
358:	learn: 0.0795748	total: 11.1s	remaining: 19.8s
359:	learn: 0.0794990	total: 11.1s	remaining: 19.7s
360:	learn: 0.0794779	total: 11.1s	remaining: 19.7s
361:	learn: 0.0793453	total: 11.2s	remaining: 19.7s
362:	learn: 0.0793433	total: 11.2s	remaining: 19.6s
363:	learn: 0.0792869	total: 11.2s	remaining: 19.6s
364:	learn: 0.0792089	total: 11.2s	remaining: 19.6s
365:	learn: 0.0790817	total: 11.3s	remaining: 19.5s
366:	learn: 0.0790534	total: 11.3s	remaining: 19.5s
367:	learn: 0.0788921	total: 11.3s	remaining: 19.5s
368:	learn: 0.0788444	total: 11.4s	remaining: 19.4s
369:	learn: 0.0787329	total: 11.4s	remaining: 19.4s
370:	learn: 0.0786036	total: 11.4s	remaining: 19.4s
371:	learn: 0.0785929	total: 11.5s	remaining: 19.3s
372:	learn: 0.0785786	total: 11.5s	remaining: 19.3s
373:	learn: 0.0785748	total: 11.5s	remaining: 19.3s
374:	learn: 0.0784872	total: 11.5s	remaining: 19.2s
375:	learn: 0.0784842	total: 11.6s	remaining: 19.2s
376:	learn: 0.0784250	total: 11.6s	remaining: 19.2s
377:	learn: 0.0783279	total: 11.6s	remaining: 19.2s
378:	learn: 0.0782753	total: 11.7s	remaining: 19.1s
379:	learn: 0.0781745	total: 11.7s	remaining: 19.1s
380:	learn: 0.0780654	total: 11.7s	remaining: 19.1s
381:	learn: 0.0779726	total: 11.8s	remaining: 19s
382:	learn: 0.0779020	total: 11.8s	remaining: 19s
383:	learn: 0.0778723	total: 11.8s	remaining: 19s
384:	learn: 0.0777370	total: 11.9s	remaining: 18.9s
385:	learn: 0.0776680	total: 11.9s	remaining: 18.9s
386:	learn: 0.0775689	total: 11.9s	remaining: 18.9s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior1st': 1 unseen categories converted to Unseen on transform.

CV folds:  34%|███▍      | 17/50 [08:58<17:32, 31.91s/fold]

999:	learn: 0.0452695	total: 30.9s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3892878	total: 26.2ms	remaining: 26.2s
1:	learn: 0.3788440	total: 54.1ms	remaining: 27s
2:	learn: 0.3683530	total: 83.3ms	remaining: 27.7s
3:	learn: 0.3582107	total: 114ms	remaining: 28.3s
4:	learn: 0.3487342	total: 142ms	remaining: 28.2s
5:	learn: 0.3399634	total: 171ms	remaining: 28.4s
6:	learn: 0.3309634	total: 200ms	remaining: 28.3s
7:	learn: 0.3232311	total: 230ms	remaining: 28.5s
8:	learn: 0.3144944	total: 259ms	remaining: 28.5s
9:	learn: 0.3068705	total: 289ms	remaining: 28.6s
10:	learn: 0.2987288	total: 318ms	remaining: 28.6s
11:	learn: 0.2915242	total: 348ms	remaining: 28.6s
12:	learn: 0.2851032	total: 379ms	remaining: 28.8s
13:	learn: 0.2785269	total: 409ms	remaining: 28.8s
14:	learn: 0.2720687	total: 437ms	remaining: 28.7s
15:	learn: 0.2655462	total: 465ms	remaining: 28.6s
16:	learn: 0.2596516	total: 494ms	remaining: 28.6s
17:	learn: 0.2538238	total: 540ms	remaining: 29.5s
18:	learn: 0.2482753	total: 572ms	remaining: 29.5s
19:	learn: 0.2428082	total: 600ms	remaining: 29.4s
20:	learn: 0.2377999	total: 632ms	remaining: 29.4s
21:	learn: 0.2327938	total: 662ms	remaining: 29.4s
22:	learn: 0.2282133	total: 694ms	remaining: 29.5s
23:	learn: 0.2238519	total: 723ms	remaining: 29.4s
24:	learn: 0.2198064	total: 753ms	remaining: 29.4s
25:	learn: 0.2158288	total: 782ms	remaining: 29.3s
26:	learn: 0.2118878	total: 811ms	remaining: 29.2s
27:	learn: 0.2078374	total: 843ms	remaining: 29.2s
28:	learn: 0.2039072	total: 875ms	remaining: 29.3s
29:	learn: 0.2004942	total: 905ms	remaining: 29.2s
30:	learn: 0.1970787	total: 933ms	remaining: 29.2s
31:	learn: 0.1941138	total: 961ms	remaining: 29.1s
32:	learn: 0.1911056	total: 991ms	remaining: 29.1s
33:	learn: 0.1879978	total: 1.02s	remaining: 29s
34:	learn: 0.1851978	total: 1.05s	remaining: 28.9s
35:	learn: 0.1819910	total: 1.08s	remaining: 28.9s
36:	learn: 0.1791711	total: 1.12s	remaining: 29.1s
37:	learn: 0.1768078	total: 1.17s	remaining: 29.5s
38:	learn: 0.1744273	total: 1.2s	remaining: 29.5s
39:	learn: 0.1722039	total: 1.23s	remaining: 29.5s
40:	learn: 0.1702934	total: 1.25s	remaining: 29.3s
41:	learn: 0.1682154	total: 1.28s	remaining: 29.3s
42:	learn: 0.1659627	total: 1.31s	remaining: 29.2s
43:	learn: 0.1641265	total: 1.34s	remaining: 29.2s
44:	learn: 0.1619957	total: 1.37s	remaining: 29.1s
45:	learn: 0.1599147	total: 1.4s	remaining: 29.1s
46:	learn: 0.1581342	total: 1.43s	remaining: 29s
47:	learn: 0.1563844	total: 1.46s	remaining: 29s
48:	learn: 0.1547997	total: 1.49s	remaining: 28.9s
49:	learn: 0.1537402	total: 1.52s	remaining: 28.8s
50:	learn: 0.1521757	total: 1.55s	remaining: 28.8s
51:	learn: 0.1507818	total: 1.58s	remaining: 28.7s
52:	learn: 0.1493944	total: 1.6s	remaining: 28.7s
53:	learn: 0.1479903	total: 1.63s	remaining: 28.6s
54:	learn: 0.1467253	total: 1.66s	remaining: 28.5s
55:	learn: 0.1453645	total: 1.69s	remaining: 28.5s
56:	learn: 0.1440928	total: 1.72s	remaining: 28.5s
57:	learn: 0.1427715	total: 1.75s	remaining: 28.5s
58:	learn: 0.1417259	total: 1.78s	remaining: 28.4s
59:	learn: 0.1404907	total: 1.81s	remaining: 28.4s
60:	learn: 0.1393516	total: 1.84s	remaining: 28.4s
61:	learn: 0.1382641	total: 1.87s	remaining: 28.3s
62:	learn: 0.1372480	total: 1.9s	remaining: 28.3s
63:	learn: 0.1362796	total: 1.93s	remaining: 28.3s
64:	learn: 0.1353645	total: 1.97s	remaining: 28.3s
65:	learn: 0.1344748	total: 2s	remaining: 28.4s
66:	learn: 0.1335692	total: 2.04s	remaining: 28.4s
67:	learn: 0.1327400	total: 2.07s	remaining: 28.4s
68:	learn: 0.1318616	total: 2.1s	remaining: 28.4s
69:	learn: 0.1309745	total: 2.14s	remaining: 28.4s
70:	learn: 0.1301973	total: 2.17s	remaining: 28.4s
71:	learn: 0.1293185	total: 2.21s	remaining: 28.4s
72:	learn: 0.1287439	total: 2.24s	remaining: 28.4s
73:	learn: 0.1279806	total: 2.27s	remaining: 28.4s
74:	learn: 0.1273421	total: 2.3s	remaining: 28.4s
75:	learn: 0.1265838	total: 2.33s	remaining: 28.3s
76:	learn: 0.1259188	total: 2.36s	remaining: 28.3s
77:	learn: 0.1251593	total: 2.39s	remaining: 28.2s
78:	learn: 0.1245217	total: 2.42s	remaining: 28.2s
79:	learn: 0.1239074	total: 2.45s	remaining: 28.1s
80:	learn: 0.1233383	total: 2.48s	remaining: 28.1s
81:	learn: 0.1226569	total: 2.51s	remaining: 28.1s
82:	learn: 0.1220106	total: 2.54s	remaining: 28.1s
83:	learn: 0.1214276	total: 2.57s	remaining: 28s
84:	learn: 0.1207015	total: 2.6s	remaining: 28s
85:	learn: 0.1201824	total: 2.63s	remaining: 27.9s
86:	learn: 0.1195989	total: 2.66s	remaining: 27.9s
87:	learn: 0.1189749	total: 2.7s	remaining: 28s
88:	learn: 0.1185708	total: 2.73s	remaining: 28s
89:	learn: 0.1180258	total: 2.76s	remaining: 27.9s
90:	learn: 0.1175890	total: 2.79s	remaining: 27.9s
91:	learn: 0.1170555	total: 2.82s	remaining: 27.9s
92:	learn: 0.1166422	total: 2.85s	remaining: 27.8s
93:	learn: 0.1161576	total: 2.88s	remaining: 27.8s
94:	learn: 0.1156990	total: 2.92s	remaining: 27.8s
95:	learn: 0.1153320	total: 2.94s	remaining: 27.7s
96:	learn: 0.1149350	total: 2.98s	remaining: 27.7s
97:	learn: 0.1144887	total: 3s	remaining: 27.7s
98:	learn: 0.1140382	total: 3.04s	remaining: 27.6s
99:	learn: 0.1137149	total: 3.07s	remaining: 27.6s
100:	learn: 0.1133283	total: 3.1s	remaining: 27.6s
101:	learn: 0.1130153	total: 3.13s	remaining: 27.6s
102:	learn: 0.1126469	total: 3.17s	remaining: 27.6s
103:	learn: 0.1123882	total: 3.2s	remaining: 27.6s
104:	learn: 0.1119538	total: 3.23s	remaining: 27.5s
105:	learn: 0.1116256	total: 3.25s	remaining: 27.4s
106:	learn: 0.1114158	total: 3.28s	remaining: 27.4s
107:	learn: 0.1111433	total: 3.31s	remaining: 27.3s
108:	learn: 0.1108694	total: 3.34s	remaining: 27.3s
109:	learn: 0.1105087	total: 3.37s	remaining: 27.3s
110:	learn: 0.1101088	total: 3.4s	remaining: 27.3s
111:	learn: 0.1098439	total: 3.43s	remaining: 27.2s
112:	learn: 0.1096396	total: 3.46s	remaining: 27.1s
113:	learn: 0.1094254	total: 3.49s	remaining: 27.1s
114:	learn: 0.1091084	total: 3.52s	remaining: 27.1s
115:	learn: 0.1088083	total: 3.55s	remaining: 27.1s
116:	learn: 0.1085141	total: 3.58s	remaining: 27.1s
117:	learn: 0.1082696	total: 3.61s	remaining: 27s
118:	learn: 0.1081370	total: 3.64s	remaining: 27s
119:	learn: 0.1078756	total: 3.67s	remaining: 26.9s
120:	learn: 0.1076204	total: 3.7s	remaining: 26.9s
121:	learn: 0.1072866	total: 3.73s	remaining: 26.8s
122:	learn: 0.1070906	total: 3.76s	remaining: 26.8s
123:	learn: 0.1069100	total: 3.79s	remaining: 26.8s
124:	learn: 0.1065902	total: 3.82s	remaining: 26.7s
125:	learn: 0.1062354	total: 3.85s	remaining: 26.7s
126:	learn: 0.1060545	total: 3.88s	remaining: 26.7s
127:	learn: 0.1058075	total: 3.91s	remaining: 26.6s
128:	learn: 0.1054680	total: 3.94s	remaining: 26.6s
129:	learn: 0.1053165	total: 3.97s	remaining: 26.6s
130:	learn: 0.1051090	total: 4s	remaining: 26.5s
131:	learn: 0.1048652	total: 4.03s	remaining: 26.5s
132:	learn: 0.1044866	total: 4.06s	remaining: 26.5s
133:	learn: 0.1041800	total: 4.09s	remaining: 26.4s
134:	learn: 0.1037922	total: 4.12s	remaining: 26.4s
135:	learn: 0.1036390	total: 4.16s	remaining: 26.4s
136:	learn: 0.1035437	total: 4.17s	remaining: 26.3s
137:	learn: 0.1033712	total: 4.2s	remaining: 26.2s
138:	learn: 0.1032140	total: 4.23s	remaining: 26.2s
139:	learn: 0.1030792	total: 4.27s	remaining: 26.2s
140:	learn: 0.1029599	total: 4.3s	remaining: 26.2s
141:	learn: 0.1027456	total: 4.33s	remaining: 26.2s
142:	learn: 0.1026128	total: 4.36s	remaining: 26.1s
143:	learn: 0.1024016	total: 4.39s	remaining: 26.1s
144:	learn: 0.1022702	total: 4.42s	remaining: 26.1s
145:	learn: 0.1020905	total: 4.45s	remaining: 26s
146:	learn: 0.1018669	total: 4.48s	remaining: 26s
147:	learn: 0.1017391	total: 4.51s	remaining: 26s
148:	learn: 0.1015918	total: 4.54s	remaining: 25.9s
149:	learn: 0.1013995	total: 4.57s	remaining: 25.9s
150:	learn: 0.1011809	total: 4.6s	remaining: 25.9s
151:	learn: 0.1009595	total: 4.63s	remaining: 25.8s
152:	learn: 0.1007679	total: 4.66s	remaining: 25.8s
153:	learn: 0.1006217	total: 4.69s	remaining: 25.8s
154:	learn: 0.1003320	total: 4.72s	remaining: 25.7s
155:	learn: 0.1000513	total: 4.75s	remaining: 25.7s
156:	learn: 0.0999244	total: 4.77s	remaining: 25.6s
157:	learn: 0.0996403	total: 4.8s	remaining: 25.6s
158:	learn: 0.0994784	total: 4.84s	remaining: 25.6s
159:	learn: 0.0992417	total: 4.88s	remaining: 25.6s
160:	learn: 0.0990474	total: 4.91s	remaining: 25.6s
161:	learn: 0.0988934	total: 4.94s	remaining: 25.5s
162:	learn: 0.0986334	total: 4.97s	remaining: 25.5s
163:	learn: 0.0984048	total: 5s	remaining: 25.5s
164:	learn: 0.0982519	total: 5.03s	remaining: 25.5s
165:	learn: 0.0980849	total: 5.06s	remaining: 25.4s
166:	learn: 0.0978402	total: 5.09s	remaining: 25.4s
167:	learn: 0.0977221	total: 5.12s	remaining: 25.4s
168:	learn: 0.0974875	total: 5.16s	remaining: 25.4s
169:	learn: 0.0973702	total: 5.19s	remaining: 25.3s
170:	learn: 0.0972360	total: 5.22s	remaining: 25.3s
171:	learn: 0.0970492	total: 5.25s	remaining: 25.3s
172:	learn: 0.0968445	total: 5.28s	remaining: 25.2s
173:	learn: 0.0966345	total: 5.31s	remaining: 25.2s
174:	learn: 0.0964851	total: 5.34s	remaining: 25.2s
175:	learn: 0.0962384	total: 5.37s	remaining: 25.2s
176:	learn: 0.0961469	total: 5.4s	remaining: 25.1s
177:	learn: 0.0959836	total: 5.43s	remaining: 25.1s
178:	learn: 0.0958675	total: 5.46s	remaining: 25s
179:	learn: 0.0956861	total: 5.49s	remaining: 25s
180:	learn: 0.0955419	total: 5.52s	remaining: 25s
181:	learn: 0.0953774	total: 5.55s	remaining: 25s
182:	learn: 0.0952741	total: 5.58s	remaining: 24.9s
183:	learn: 0.0951115	total: 5.61s	remaining: 24.9s
184:	learn: 0.0950080	total: 5.64s	remaining: 24.9s
185:	learn: 0.0949155	total: 5.67s	remaining: 24.8s
186:	learn: 0.0948152	total: 5.7s	remaining: 24.8s
187:	learn: 0.0946782	total: 5.73s	remaining: 24.8s
188:	learn: 0.0944820	total: 5.77s	remaining: 24.8s
189:	learn: 0.0943376	total: 5.8s	remaining: 24.7s
190:	learn: 0.0942334	total: 5.83s	remaining: 24.7s
191:	learn: 0.0940997	total: 5.86s	remaining: 24.7s
192:	learn: 0.0939415	total: 5.89s	remaining: 24.6s
193:	learn: 0.0938110	total: 5.94s	remaining: 24.7s
194:	learn: 0.0937265	total: 5.98s	remaining: 24.7s
195:	learn: 0.0935188	total: 6s	remaining: 24.6s
196:	learn: 0.0933921	total: 6.04s	remaining: 24.6s
197:	learn: 0.0931908	total: 6.07s	remaining: 24.6s
198:	learn: 0.0929930	total: 6.1s	remaining: 24.6s
199:	learn: 0.0928284	total: 6.13s	remaining: 24.5s
200:	learn: 0.0926557	total: 6.16s	remaining: 24.5s
201:	learn: 0.0924932	total: 6.19s	remaining: 24.4s
202:	learn: 0.0923251	total: 6.22s	remaining: 24.4s
203:	learn: 0.0921229	total: 6.25s	remaining: 24.4s
204:	learn: 0.0920122	total: 6.28s	remaining: 24.4s
205:	learn: 0.0917541	total: 6.31s	remaining: 24.3s
206:	learn: 0.0916463	total: 6.34s	remaining: 24.3s
207:	learn: 0.0915447	total: 6.38s	remaining: 24.3s
208:	learn: 0.0913340	total: 6.41s	remaining: 24.2s
209:	learn: 0.0911720	total: 6.44s	remaining: 24.2s
210:	learn: 0.0909744	total: 6.47s	remaining: 24.2s
211:	learn: 0.0908805	total: 6.5s	remaining: 24.2s
212:	learn: 0.0908076	total: 6.53s	remaining: 24.1s
213:	learn: 0.0906040	total: 6.56s	remaining: 24.1s
214:	learn: 0.0904481	total: 6.58s	remaining: 24s
215:	learn: 0.0903289	total: 6.62s	remaining: 24s
216:	learn: 0.0902163	total: 6.65s	remaining: 24s
217:	learn: 0.0901048	total: 6.68s	remaining: 24s
218:	learn: 0.0900390	total: 6.71s	remaining: 23.9s
219:	learn: 0.0899433	total: 6.74s	remaining: 23.9s
220:	learn: 0.0898164	total: 6.77s	remaining: 23.9s
221:	learn: 0.0896716	total: 6.8s	remaining: 23.8s
222:	learn: 0.0895967	total: 6.83s	remaining: 23.8s
223:	learn: 0.0894619	total: 6.86s	remaining: 23.7s
224:	learn: 0.0893784	total: 6.89s	remaining: 23.7s
225:	learn: 0.0893013	total: 6.92s	remaining: 23.7s
226:	learn: 0.0892110	total: 6.95s	remaining: 23.7s
227:	learn: 0.0891168	total: 6.99s	remaining: 23.7s
228:	learn: 0.0890523	total: 7.02s	remaining: 23.6s
229:	learn: 0.0889165	total: 7.05s	remaining: 23.6s
230:	learn: 0.0888410	total: 7.08s	remaining: 23.6s
231:	learn: 0.0885991	total: 7.11s	remaining: 23.6s
232:	learn: 0.0885301	total: 7.14s	remaining: 23.5s
233:	learn: 0.0883674	total: 7.17s	remaining: 23.5s
234:	learn: 0.0882065	total: 7.2s	remaining: 23.4s
235:	learn: 0.0881304	total: 7.23s	remaining: 23.4s
236:	learn: 0.0880264	total: 7.26s	remaining: 23.4s
237:	learn: 0.0879505	total: 7.29s	remaining: 23.3s
238:	learn: 0.0878609	total: 7.32s	remaining: 23.3s
239:	learn: 0.0878314	total: 7.35s	remaining: 23.3s
240:	learn: 0.0877147	total: 7.38s	remaining: 23.2s
241:	learn: 0.0875942	total: 7.41s	remaining: 23.2s
242:	learn: 0.0875134	total: 7.44s	remaining: 23.2s
243:	learn: 0.0873703	total: 7.47s	remaining: 23.1s
244:	learn: 0.0872771	total: 7.5s	remaining: 23.1s
245:	learn: 0.0871504	total: 7.53s	remaining: 23.1s
246:	learn: 0.0870695	total: 7.56s	remaining: 23s
247:	learn: 0.0869373	total: 7.59s	remaining: 23s
248:	learn: 0.0868273	total: 7.62s	remaining: 23s
249:	learn: 0.0866829	total: 7.65s	remaining: 22.9s
250:	learn: 0.0865903	total: 7.68s	remaining: 22.9s
251:	learn: 0.0863470	total: 7.71s	remaining: 22.9s
252:	learn: 0.0863233	total: 7.74s	remaining: 22.9s
253:	learn: 0.0863124	total: 7.77s	remaining: 22.8s
254:	learn: 0.0862952	total: 7.8s	remaining: 22.8s
255:	learn: 0.0861633	total: 7.83s	remaining: 22.8s
256:	learn: 0.0860863	total: 7.86s	remaining: 22.7s
257:	learn: 0.0860650	total: 7.89s	remaining: 22.7s
258:	learn: 0.0858492	total: 7.92s	remaining: 22.7s
259:	learn: 0.0858058	total: 7.95s	remaining: 22.6s
260:	learn: 0.0856216	total: 7.98s	remaining: 22.6s
261:	learn: 0.0855698	total: 8.01s	remaining: 22.6s
262:	learn: 0.0854750	total: 8.04s	remaining: 22.5s
263:	learn: 0.0852768	total: 8.08s	remaining: 22.5s
264:	learn: 0.0851223	total: 8.11s	remaining: 22.5s
265:	learn: 0.0850284	total: 8.14s	remaining: 22.5s
266:	learn: 0.0849950	total: 8.18s	remaining: 22.4s
267:	learn: 0.0848448	total: 8.21s	remaining: 22.4s
268:	learn: 0.0846915	total: 8.24s	remaining: 22.4s
269:	learn: 0.0846755	total: 8.27s	remaining: 22.3s
270:	learn: 0.0845023	total: 8.29s	remaining: 22.3s
271:	learn: 0.0844314	total: 8.32s	remaining: 22.3s
272:	learn: 0.0843425	total: 8.35s	remaining: 22.2s
273:	learn: 0.0841834	total: 8.39s	remaining: 22.2s
274:	learn: 0.0840685	total: 8.41s	remaining: 22.2s
275:	learn: 0.0839267	total: 8.44s	remaining: 22.1s
276:	learn: 0.0839162	total: 8.47s	remaining: 22.1s
277:	learn: 0.0838820	total: 8.49s	remaining: 22.1s
278:	learn: 0.0838418	total: 8.52s	remaining: 22s
279:	learn: 0.0837450	total: 8.55s	remaining: 22s
280:	learn: 0.0836531	total: 8.58s	remaining: 22s
281:	learn: 0.0835075	total: 8.61s	remaining: 21.9s
282:	learn: 0.0833968	total: 8.64s	remaining: 21.9s
283:	learn: 0.0831871	total: 8.67s	remaining: 21.9s
284:	learn: 0.0831201	total: 8.7s	remaining: 21.8s
285:	learn: 0.0830563	total: 8.74s	remaining: 21.8s
286:	learn: 0.0829756	total: 8.77s	remaining: 21.8s
287:	learn: 0.0829390	total: 8.8s	remaining: 21.8s
288:	learn: 0.0828357	total: 8.83s	remaining: 21.7s
289:	learn: 0.0827007	total: 8.86s	remaining: 21.7s
290:	learn: 0.0826859	total: 8.89s	remaining: 21.7s
291:	learn: 0.0825575	total: 8.92s	remaining: 21.6s
292:	learn: 0.0824576	total: 8.95s	remaining: 21.6s
293:	learn: 0.0824469	total: 8.98s	remaining: 21.6s
294:	learn: 0.0823589	total: 9.01s	remaining: 21.5s
295:	learn: 0.0821893	total: 9.06s	remaining: 21.6s
296:	learn: 0.0820733	total: 9.09s	remaining: 21.5s
297:	learn: 0.0819323	total: 9.13s	remaining: 21.5s
298:	learn: 0.0817071	total: 9.17s	remaining: 21.5s
299:	learn: 0.0816636	total: 9.2s	remaining: 21.5s
300:	learn: 0.0815234	total: 9.23s	remaining: 21.4s
301:	learn: 0.0813969	total: 9.27s	remaining: 21.4s
302:	learn: 0.0813848	total: 9.3s	remaining: 21.4s
303:	learn: 0.0813721	total: 9.33s	remaining: 21.4s
304:	learn: 0.0813316	total: 9.36s	remaining: 21.3s
305:	learn: 0.0813190	total: 9.39s	remaining: 21.3s
306:	learn: 0.0811098	total: 9.43s	remaining: 21.3s
307:	learn: 0.0810690	total: 9.45s	remaining: 21.2s
308:	learn: 0.0810636	total: 9.47s	remaining: 21.2s
309:	learn: 0.0810584	total: 9.48s	remaining: 21.1s
310:	learn: 0.0809873	total: 9.51s	remaining: 21.1s
311:	learn: 0.0809823	total: 9.52s	remaining: 21s
312:	learn: 0.0808440	total: 9.55s	remaining: 21s
313:	learn: 0.0806986	total: 9.58s	remaining: 20.9s
314:	learn: 0.0805286	total: 9.63s	remaining: 20.9s
315:	learn: 0.0803916	total: 9.66s	remaining: 20.9s
316:	learn: 0.0803847	total: 9.69s	remaining: 20.9s
317:	learn: 0.0802858	total: 9.72s	remaining: 20.8s
318:	learn: 0.0801628	total: 9.75s	remaining: 20.8s
319:	learn: 0.0801323	total: 9.78s	remaining: 20.8s
320:	learn: 0.0800458	total: 9.81s	remaining: 20.8s
321:	learn: 0.0800321	total: 9.84s	remaining: 20.7s
322:	learn: 0.0799402	total: 9.88s	remaining: 20.7s
323:	learn: 0.0798659	total: 9.91s	remaining: 20.7s
324:	learn: 0.0798613	total: 9.93s	remaining: 20.6s
325:	learn: 0.0797271	total: 9.96s	remaining: 20.6s
326:	learn: 0.0796271	total: 9.99s	remaining: 20.6s
327:	learn: 0.0796141	total: 10s	remaining: 20.5s
328:	learn: 0.0796097	total: 10s	remaining: 20.5s
329:	learn: 0.0795822	total: 10.1s	remaining: 20.5s
330:	learn: 0.0794589	total: 10.1s	remaining: 20.4s
331:	learn: 0.0793609	total: 10.1s	remaining: 20.4s
332:	learn: 0.0792057	total: 10.2s	remaining: 20.4s
333:	learn: 0.0790973	total: 10.2s	remaining: 20.3s
334:	learn: 0.0790122	total: 10.2s	remaining: 20.3s
335:	learn: 0.0789058	total: 10.3s	remaining: 20.3s
336:	learn: 0.0788185	total: 10.3s	remaining: 20.2s
337:	learn: 0.0786444	total: 10.3s	remaining: 20.2s
338:	learn: 0.0785783	total: 10.4s	remaining: 20.2s
339:	learn: 0.0784099	total: 10.4s	remaining: 20.2s
340:	learn: 0.0783508	total: 10.4s	remaining: 20.1s
341:	learn: 0.0782711	total: 10.4s	remaining: 20.1s
342:	learn: 0.0781896	total: 10.5s	remaining: 20.1s
343:	learn: 0.0780469	total: 10.5s	remaining: 20s
344:	learn: 0.0780021	total: 10.5s	remaining: 20s
345:	learn: 0.0779009	total: 10.6s	remaining: 20s
346:	learn: 0.0778213	total: 10.6s	remaining: 19.9s
347:	learn: 0.0777272	total: 10.6s	remaining: 19.9s
348:	learn: 0.0776294	total: 10.7s	remaining: 19.9s
349:	learn: 0.0775396	total: 10.7s	remaining: 19.8s
350:	learn: 0.0775355	total: 10.7s	remaining: 19.8s
351:	learn: 0.0774152	total: 10.7s	remaining: 19.8s
352:	learn: 0.0773068	total: 10.8s	remaining: 19.7s
353:	learn: 0.0772788	total: 10.8s	remaining: 19.7s
354:	learn: 0.0772325	total: 10.8s	remaining: 19.7s
355:	learn: 0.0771642	total: 10.9s	remaining: 19.7s
356:	learn: 0.0770345	total: 10.9s	remaining: 19.7s
357:	learn: 0.0770288	total: 10.9s	remaining: 19.6s
358:	learn: 0.0768570	total: 11s	remaining: 19.6s
359:	learn: 0.0767745	total: 11s	remaining: 19.6s
360:	learn: 0.0766656	total: 11s	remaining: 19.5s
361:	learn: 0.0765938	total: 11.1s	remaining: 19.5s
362:	learn: 0.0765647	total: 11.1s	remaining: 19.5s
363:	learn: 0.0765287	total: 11.1s	remaining: 19.5s
364:	learn: 0.0763899	total: 11.2s	remaining: 19.4s
365:	learn: 0.0762231	total: 11.2s	remaining: 19.4s
366:	learn: 0.0760973	total: 11.2s	remaining: 19.4s
367:	learn: 0.0759787	total: 11.3s	remaining: 19.4s
368:	learn: 0.0759750	total: 11.3s	remaining: 19.3s
369:	learn: 0.0759322	total: 11.3s	remaining: 19.3s
370:	learn: 0.0758957	total: 11.4s	remaining: 19.3s
371:	learn: 0.0758810	total: 11.4s	remaining: 19.2s
372:	learn: 0.0757702	total: 11.4s	remaining: 19.2s
373:	learn: 0.0756719	total: 11.5s	remaining: 19.2s
374:	learn: 0.0755205	total: 11.5s	remaining: 19.1s
375:	learn: 0.0754405	total: 11.5s	remaining: 19.1s
376:	learn: 0.0753659	total: 11.5s	remaining: 19.1s
377:	learn: 0.0752969	total: 11.6s	remaining: 19.1s
378:	learn: 0.0752149	total: 11.6s	remaining: 19s
379:	learn: 0.0750236	total: 11.6s	remaining: 19s
380:	learn: 0.0749791	total: 11.7s	remaining: 19s
381:	learn: 0.0749147	total: 11.7s	remaining: 18.9s
382:	learn: 0.0748611	total: 11.7s	remaining: 18.9s
383:	learn: 0.0748536	total: 11.8s	remaining: 18.9s
384:	learn: 0.0747203	total: 11.8s	remaining: 18.8s
385:	learn: 0.0747155	total: 11.8s	remaining: 18.8s
386:	learn: 0.0745859	total: 11.9s	remaining: 18.8s

CV folds:  36%|███▌      | 18/50 [09:30<16:58, 31.83s/fold]

Learning rate set to 0.042743
0:	learn: 0.3887247	total: 23.6ms	remaining: 23.5s
1:	learn: 0.3782796	total: 53.6ms	remaining: 26.8s
2:	learn: 0.3671435	total: 83.1ms	remaining: 27.6s
3:	learn: 0.3580350	total: 113ms	remaining: 28.1s
4:	learn: 0.3483393	total: 142ms	remaining: 28.2s
5:	learn: 0.3391431	total: 170ms	remaining: 28.2s
6:	learn: 0.3305741	total: 203ms	remaining: 28.8s
7:	learn: 0.3221148	total: 254ms	remaining: 31.5s
8:	learn: 0.3142490	total: 288ms	remaining: 31.7s
9:	learn: 0.3071324	total: 315ms	remaining: 31.2s
10:	learn: 0.2993878	total: 341ms	remaining: 30.7s
11:	learn: 0.2919926	total: 369ms	remaining: 30.4s
12:	learn: 0.2846240	total: 395ms	remaining: 30s
13:	learn: 0.2776815	total: 424ms	remaining: 29.9s
14:	learn: 0.2715219	total: 454ms	remaining: 29.8s
15:	learn: 0.2658357	total: 501ms	remaining: 30.8s
16:	learn: 0.2602781	total: 534ms	remaining: 30.9s
17:	learn: 0.2544718	total: 564ms	remaining: 30.8s
18:	learn: 0.2489721	total: 592ms	remaining: 30.6s
19:	learn: 0.2438268	total: 620ms	remaining: 30.4s
20:	learn: 0.2390081	total: 649ms	remaining: 30.3s
21:	learn: 0.2346112	total: 683ms	remaining: 30.4s
22:	learn: 0.2301868	total: 712ms	remaining: 30.2s
23:	learn: 0.2258195	total: 740ms	remaining: 30.1s
24:	learn: 0.2215314	total: 770ms	remaining: 30s
25:	learn: 0.2174300	total: 799ms	remaining: 29.9s
26:	learn: 0.2132870	total: 828ms	remaining: 29.8s
27:	learn: 0.2097280	total: 856ms	remaining: 29.7s
28:	learn: 0.2060622	total: 887ms	remaining: 29.7s
29:	learn: 0.2023893	total: 916ms	remaining: 29.6s
30:	learn: 0.1989415	total: 950ms	remaining: 29.7s
31:	learn: 0.1962420	total: 981ms	remaining: 29.7s
32:	learn: 0.1930859	total: 1.01s	remaining: 29.6s
33:	learn: 0.1903660	total: 1.04s	remaining: 29.6s
34:	learn: 0.1872447	total: 1.07s	remaining: 29.5s
35:	learn: 0.1845655	total: 1.1s	remaining: 29.4s
36:	learn: 0.1820802	total: 1.13s	remaining: 29.4s
37:	learn: 0.1797319	total: 1.16s	remaining: 29.4s
38:	learn: 0.1771813	total: 1.19s	remaining: 29.3s
39:	learn: 0.1747104	total: 1.22s	remaining: 29.2s
40:	learn: 0.1724361	total: 1.24s	remaining: 29.1s
41:	learn: 0.1701769	total: 1.27s	remaining: 28.9s
42:	learn: 0.1679939	total: 1.3s	remaining: 28.9s
43:	learn: 0.1657359	total: 1.33s	remaining: 28.8s
44:	learn: 0.1640991	total: 1.35s	remaining: 28.8s
45:	learn: 0.1623263	total: 1.4s	remaining: 28.9s
46:	learn: 0.1606169	total: 1.43s	remaining: 29.1s
47:	learn: 0.1588254	total: 1.46s	remaining: 29s
48:	learn: 0.1569652	total: 1.49s	remaining: 29s
49:	learn: 0.1553365	total: 1.51s	remaining: 28.7s
50:	learn: 0.1535671	total: 1.54s	remaining: 28.7s
51:	learn: 0.1523874	total: 1.57s	remaining: 28.7s
52:	learn: 0.1510092	total: 1.6s	remaining: 28.6s
53:	learn: 0.1496329	total: 1.63s	remaining: 28.6s
54:	learn: 0.1484198	total: 1.66s	remaining: 28.6s
55:	learn: 0.1473452	total: 1.69s	remaining: 28.5s
56:	learn: 0.1460559	total: 1.72s	remaining: 28.5s
57:	learn: 0.1445411	total: 1.75s	remaining: 28.4s
58:	learn: 0.1434114	total: 1.78s	remaining: 28.4s
59:	learn: 0.1423704	total: 1.81s	remaining: 28.3s
60:	learn: 0.1412239	total: 1.84s	remaining: 28.3s
61:	learn: 0.1401118	total: 1.86s	remaining: 28.2s
62:	learn: 0.1391744	total: 1.89s	remaining: 28.1s
63:	learn: 0.1382259	total: 1.92s	remaining: 28.1s
64:	learn: 0.1373025	total: 1.95s	remaining: 28s
65:	learn: 0.1364124	total: 1.98s	remaining: 28s
66:	learn: 0.1353675	total: 2s	remaining: 27.9s
67:	learn: 0.1343820	total: 2.03s	remaining: 27.9s
68:	learn: 0.1336062	total: 2.06s	remaining: 27.9s
69:	learn: 0.1329163	total: 2.09s	remaining: 27.8s
70:	learn: 0.1321495	total: 2.12s	remaining: 27.7s
71:	learn: 0.1313718	total: 2.15s	remaining: 27.7s
72:	learn: 0.1306757	total: 2.17s	remaining: 27.6s
73:	learn: 0.1298495	total: 2.2s	remaining: 27.6s
74:	learn: 0.1291439	total: 2.23s	remaining: 27.5s
75:	learn: 0.1284308	total: 2.26s	remaining: 27.5s
76:	learn: 0.1276042	total: 2.29s	remaining: 27.4s
77:	learn: 0.1269193	total: 2.32s	remaining: 27.4s
78:	learn: 0.1262355	total: 2.35s	remaining: 27.4s
79:	learn: 0.1256180	total: 2.38s	remaining: 27.3s
80:	learn: 0.1249468	total: 2.41s	remaining: 27.3s
81:	learn: 0.1242571	total: 2.44s	remaining: 27.3s
82:	learn: 0.1236510	total: 2.47s	remaining: 27.2s
83:	learn: 0.1231365	total: 2.5s	remaining: 27.3s
84:	learn: 0.1226390	total: 2.53s	remaining: 27.2s
85:	learn: 0.1221609	total: 2.56s	remaining: 27.2s
86:	learn: 0.1216882	total: 2.58s	remaining: 27.1s
87:	learn: 0.1211830	total: 2.61s	remaining: 27.1s
88:	learn: 0.1205689	total: 2.64s	remaining: 27.1s
89:	learn: 0.1201279	total: 2.67s	remaining: 27s
90:	learn: 0.1195951	total: 2.7s	remaining: 27s
91:	learn: 0.1190775	total: 2.73s	remaining: 27s
92:	learn: 0.1186162	total: 2.76s	remaining: 26.9s
93:	learn: 0.1182156	total: 2.79s	remaining: 26.9s
94:	learn: 0.1178044	total: 2.82s	remaining: 26.9s
95:	learn: 0.1174270	total: 2.85s	remaining: 26.9s
96:	learn: 0.1171242	total: 2.88s	remaining: 26.9s
97:	learn: 0.1167775	total: 2.92s	remaining: 26.8s
98:	learn: 0.1164898	total: 2.95s	remaining: 26.8s
99:	learn: 0.1159726	total: 2.98s	remaining: 26.8s
100:	learn: 0.1155593	total: 3.01s	remaining: 26.8s
101:	learn: 0.1151495	total: 3.04s	remaining: 26.8s
102:	learn: 0.1147949	total: 3.07s	remaining: 26.7s
103:	learn: 0.1145237	total: 3.1s	remaining: 26.7s
104:	learn: 0.1141712	total: 3.13s	remaining: 26.7s
105:	learn: 0.1139212	total: 3.16s	remaining: 26.6s
106:	learn: 0.1134902	total: 3.19s	remaining: 26.6s
107:	learn: 0.1130828	total: 3.22s	remaining: 26.6s
108:	learn: 0.1126363	total: 3.25s	remaining: 26.6s
109:	learn: 0.1124132	total: 3.28s	remaining: 26.5s
110:	learn: 0.1122077	total: 3.31s	remaining: 26.5s
111:	learn: 0.1118814	total: 3.34s	remaining: 26.5s
112:	learn: 0.1115347	total: 3.37s	remaining: 26.5s
113:	learn: 0.1112463	total: 3.4s	remaining: 26.5s
114:	learn: 0.1110002	total: 3.43s	remaining: 26.4s
115:	learn: 0.1107831	total: 3.46s	remaining: 26.4s
116:	learn: 0.1105237	total: 3.5s	remaining: 26.5s
117:	learn: 0.1103046	total: 3.56s	remaining: 26.6s
118:	learn: 0.1100515	total: 3.59s	remaining: 26.6s
119:	learn: 0.1097838	total: 3.62s	remaining: 26.6s
120:	learn: 0.1093934	total: 3.65s	remaining: 26.5s
121:	learn: 0.1091603	total: 3.68s	remaining: 26.5s
122:	learn: 0.1089694	total: 3.71s	remaining: 26.4s
123:	learn: 0.1086963	total: 3.74s	remaining: 26.4s
124:	learn: 0.1083708	total: 3.77s	remaining: 26.4s
125:	learn: 0.1081319	total: 3.8s	remaining: 26.3s
126:	learn: 0.1079419	total: 3.83s	remaining: 26.3s
127:	learn: 0.1076976	total: 3.86s	remaining: 26.3s
128:	learn: 0.1074045	total: 3.89s	remaining: 26.3s
129:	learn: 0.1071526	total: 3.92s	remaining: 26.2s
130:	learn: 0.1069087	total: 3.95s	remaining: 26.2s
131:	learn: 0.1067291	total: 3.98s	remaining: 26.2s
132:	learn: 0.1065616	total: 4.01s	remaining: 26.1s
133:	learn: 0.1063424	total: 4.04s	remaining: 26.1s
134:	learn: 0.1061282	total: 4.07s	remaining: 26.1s
135:	learn: 0.1059512	total: 4.1s	remaining: 26.1s
136:	learn: 0.1056432	total: 4.14s	remaining: 26.1s
137:	learn: 0.1054535	total: 4.17s	remaining: 26s
138:	learn: 0.1050909	total: 4.2s	remaining: 26s
139:	learn: 0.1048815	total: 4.22s	remaining: 26s
140:	learn: 0.1046635	total: 4.25s	remaining: 25.9s
141:	learn: 0.1044287	total: 4.28s	remaining: 25.9s
142:	learn: 0.1042655	total: 4.32s	remaining: 25.9s
143:	learn: 0.1042004	total: 4.33s	remaining: 25.7s
144:	learn: 0.1040842	total: 4.36s	remaining: 25.7s
145:	learn: 0.1039729	total: 4.39s	remaining: 25.7s
146:	learn: 0.1038297	total: 4.42s	remaining: 25.7s
147:	learn: 0.1035792	total: 4.46s	remaining: 25.7s
148:	learn: 0.1033810	total: 4.5s	remaining: 25.7s
149:	learn: 0.1031164	total: 4.53s	remaining: 25.7s
150:	learn: 0.1028969	total: 4.57s	remaining: 25.7s
151:	learn: 0.1027744	total: 4.6s	remaining: 25.7s
152:	learn: 0.1025978	total: 4.63s	remaining: 25.6s
153:	learn: 0.1024716	total: 4.67s	remaining: 25.7s
154:	learn: 0.1023969	total: 4.71s	remaining: 25.7s
155:	learn: 0.1022444	total: 4.74s	remaining: 25.7s
156:	learn: 0.1021161	total: 4.77s	remaining: 25.6s
157:	learn: 0.1020285	total: 4.8s	remaining: 25.6s
158:	learn: 0.1017740	total: 4.83s	remaining: 25.6s
159:	learn: 0.1016210	total: 4.86s	remaining: 25.5s
160:	learn: 0.1015886	total: 4.88s	remaining: 25.4s
161:	learn: 0.1014050	total: 4.91s	remaining: 25.4s
162:	learn: 0.1011237	total: 4.94s	remaining: 25.4s
163:	learn: 0.1009551	total: 4.97s	remaining: 25.4s
164:	learn: 0.1007932	total: 5s	remaining: 25.3s
165:	learn: 0.1006899	total: 5.05s	remaining: 25.4s
166:	learn: 0.1005690	total: 5.09s	remaining: 25.4s
167:	learn: 0.1004333	total: 5.12s	remaining: 25.4s
168:	learn: 0.1003311	total: 5.16s	remaining: 25.4s
169:	learn: 0.1001860	total: 5.19s	remaining: 25.4s
170:	learn: 0.0999687	total: 5.23s	remaining: 25.3s
171:	learn: 0.0997919	total: 5.25s	remaining: 25.3s
172:	learn: 0.0996463	total: 5.29s	remaining: 25.3s
173:	learn: 0.0993605	total: 5.31s	remaining: 25.2s
174:	learn: 0.0991172	total: 5.34s	remaining: 25.2s
175:	learn: 0.0988655	total: 5.37s	remaining: 25.2s
176:	learn: 0.0986957	total: 5.41s	remaining: 25.1s
177:	learn: 0.0985954	total: 5.44s	remaining: 25.1s
178:	learn: 0.0983693	total: 5.46s	remaining: 25.1s
179:	learn: 0.0981248	total: 5.5s	remaining: 25s
180:	learn: 0.0979373	total: 5.53s	remaining: 25s
181:	learn: 0.0978459	total: 5.55s	remaining: 25s
182:	learn: 0.0976522	total: 5.58s	remaining: 24.9s
183:	learn: 0.0976108	total: 5.62s	remaining: 24.9s
184:	learn: 0.0975371	total: 5.64s	remaining: 24.9s
185:	learn: 0.0973262	total: 5.67s	remaining: 24.8s
186:	learn: 0.0971677	total: 5.72s	remaining: 24.9s
187:	learn: 0.0970105	total: 5.75s	remaining: 24.8s
188:	learn: 0.0969387	total: 5.78s	remaining: 24.8s
189:	learn: 0.0967510	total: 5.81s	remaining: 24.8s
190:	learn: 0.0966880	total: 5.84s	remaining: 24.7s
191:	learn: 0.0964525	total: 5.87s	remaining: 24.7s
192:	learn: 0.0962925	total: 5.89s	remaining: 24.6s
193:	learn: 0.0961266	total: 5.92s	remaining: 24.6s
194:	learn: 0.0960451	total: 5.95s	remaining: 24.6s
195:	learn: 0.0959702	total: 5.98s	remaining: 24.5s
196:	learn: 0.0958426	total: 6.01s	remaining: 24.5s
197:	learn: 0.0957508	total: 6.04s	remaining: 24.5s
198:	learn: 0.0955619	total: 6.08s	remaining: 24.5s
199:	learn: 0.0954065	total: 6.11s	remaining: 24.4s
200:	learn: 0.0953474	total: 6.14s	remaining: 24.4s
201:	learn: 0.0952371	total: 6.17s	remaining: 24.4s
202:	learn: 0.0950494	total: 6.2s	remaining: 24.3s
203:	learn: 0.0949320	total: 6.23s	remaining: 24.3s
204:	learn: 0.0948542	total: 6.26s	remaining: 24.3s
205:	learn: 0.0946808	total: 6.29s	remaining: 24.2s
206:	learn: 0.0946116	total: 6.32s	remaining: 24.2s
207:	learn: 0.0945094	total: 6.35s	remaining: 24.2s
208:	learn: 0.0943657	total: 6.38s	remaining: 24.1s
209:	learn: 0.0941795	total: 6.4s	remaining: 24.1s
210:	learn: 0.0941194	total: 6.43s	remaining: 24s
211:	learn: 0.0938646	total: 6.46s	remaining: 24s
212:	learn: 0.0937371	total: 6.49s	remaining: 24s
213:	learn: 0.0936441	total: 6.52s	remaining: 24s
214:	learn: 0.0936001	total: 6.55s	remaining: 23.9s
215:	learn: 0.0935505	total: 6.58s	remaining: 23.9s
216:	learn: 0.0934861	total: 6.61s	remaining: 23.9s
217:	learn: 0.0934012	total: 6.64s	remaining: 23.8s
218:	learn: 0.0933251	total: 6.67s	remaining: 23.8s
219:	learn: 0.0932005	total: 6.7s	remaining: 23.8s
220:	learn: 0.0931070	total: 6.74s	remaining: 23.8s
221:	learn: 0.0930552	total: 6.78s	remaining: 23.7s
222:	learn: 0.0929952	total: 6.8s	remaining: 23.7s
223:	learn: 0.0929547	total: 6.83s	remaining: 23.7s
224:	learn: 0.0929275	total: 6.86s	remaining: 23.6s
225:	learn: 0.0926242	total: 6.89s	remaining: 23.6s
226:	learn: 0.0924902	total: 6.92s	remaining: 23.6s
227:	learn: 0.0924429	total: 6.95s	remaining: 23.5s
228:	learn: 0.0923671	total: 6.98s	remaining: 23.5s
229:	learn: 0.0922022	total: 7.01s	remaining: 23.5s
230:	learn: 0.0921681	total: 7.04s	remaining: 23.4s
231:	learn: 0.0920982	total: 7.07s	remaining: 23.4s
232:	learn: 0.0919255	total: 7.1s	remaining: 23.4s
233:	learn: 0.0917343	total: 7.13s	remaining: 23.4s
234:	learn: 0.0916161	total: 7.16s	remaining: 23.3s
235:	learn: 0.0915700	total: 7.2s	remaining: 23.3s
236:	learn: 0.0913702	total: 7.22s	remaining: 23.3s
237:	learn: 0.0913008	total: 7.25s	remaining: 23.2s
238:	learn: 0.0911982	total: 7.29s	remaining: 23.2s
239:	learn: 0.0911484	total: 7.32s	remaining: 23.2s
240:	learn: 0.0908882	total: 7.34s	remaining: 23.1s
241:	learn: 0.0907280	total: 7.38s	remaining: 23.1s
242:	learn: 0.0906949	total: 7.41s	remaining: 23.1s
243:	learn: 0.0905506	total: 7.44s	remaining: 23s
244:	learn: 0.0903538	total: 7.47s	remaining: 23s
245:	learn: 0.0903295	total: 7.5s	remaining: 23s
246:	learn: 0.0901186	total: 7.53s	remaining: 22.9s
247:	learn: 0.0899629	total: 7.56s	remaining: 22.9s
248:	learn: 0.0899533	total: 7.59s	remaining: 22.9s
249:	learn: 0.0898888	total: 7.62s	remaining: 22.9s
250:	learn: 0.0898549	total: 7.65s	remaining: 22.8s
251:	learn: 0.0898154	total: 7.68s	remaining: 22.8s
252:	learn: 0.0897522	total: 7.71s	remaining: 22.8s
253:	learn: 0.0897210	total: 7.74s	remaining: 22.7s
254:	learn: 0.0895703	total: 7.77s	remaining: 22.7s
255:	learn: 0.0894901	total: 7.8s	remaining: 22.7s
256:	learn: 0.0894424	total: 7.83s	remaining: 22.6s
257:	learn: 0.0894219	total: 7.88s	remaining: 22.6s
258:	learn: 0.0893166	total: 7.91s	remaining: 22.6s
259:	learn: 0.0892193	total: 7.94s	remaining: 22.6s
260:	learn: 0.0889977	total: 7.97s	remaining: 22.6s
261:	learn: 0.0889340	total: 8s	remaining: 22.5s
262:	learn: 0.0889071	total: 8.03s	remaining: 22.5s
263:	learn: 0.0888674	total: 8.06s	remaining: 22.5s
264:	learn: 0.0888507	total: 8.09s	remaining: 22.4s
265:	learn: 0.0887727	total: 8.12s	remaining: 22.4s
266:	learn: 0.0886421	total: 8.15s	remaining: 22.4s
267:	learn: 0.0885600	total: 8.18s	remaining: 22.4s
268:	learn: 0.0884383	total: 8.23s	remaining: 22.4s
269:	learn: 0.0881921	total: 8.26s	remaining: 22.3s
270:	learn: 0.0880327	total: 8.3s	remaining: 22.3s
271:	learn: 0.0879330	total: 8.33s	remaining: 22.3s
272:	learn: 0.0878984	total: 8.36s	remaining: 22.3s
273:	learn: 0.0878896	total: 8.39s	remaining: 22.2s
274:	learn: 0.0878136	total: 8.42s	remaining: 22.2s
275:	learn: 0.0877937	total: 8.45s	remaining: 22.2s
276:	learn: 0.0876392	total: 8.48s	remaining: 22.1s
277:	learn: 0.0875594	total: 8.51s	remaining: 22.1s
278:	learn: 0.0874121	total: 8.54s	remaining: 22.1s
279:	learn: 0.0872172	total: 8.57s	remaining: 22s
280:	learn: 0.0871885	total: 8.6s	remaining: 22s
281:	learn: 0.0870320	total: 8.63s	remaining: 22s
282:	learn: 0.0869305	total: 8.66s	remaining: 21.9s
283:	learn: 0.0869109	total: 8.69s	remaining: 21.9s
284:	learn: 0.0868674	total: 8.72s	remaining: 21.9s
285:	learn: 0.0866794	total: 8.75s	remaining: 21.9s
286:	learn: 0.0865703	total: 8.78s	remaining: 21.8s
287:	learn: 0.0865080	total: 8.82s	remaining: 21.8s
288:	learn: 0.0864363	total: 8.85s	remaining: 21.8s
289:	learn: 0.0864026	total: 8.88s	remaining: 21.7s
290:	learn: 0.0861981	total: 8.91s	remaining: 21.7s
291:	learn: 0.0861799	total: 8.95s	remaining: 21.7s
292:	learn: 0.0861600	total: 8.98s	remaining: 21.7s
293:	learn: 0.0860715	total: 9.01s	remaining: 21.6s
294:	learn: 0.0860433	total: 9.04s	remaining: 21.6s
295:	learn: 0.0859257	total: 9.07s	remaining: 21.6s
296:	learn: 0.0859144	total: 9.1s	remaining: 21.5s
297:	learn: 0.0858559	total: 9.13s	remaining: 21.5s
298:	learn: 0.0856201	total: 9.16s	remaining: 21.5s
299:	learn: 0.0855280	total: 9.21s	remaining: 21.5s
300:	learn: 0.0855071	total: 9.24s	remaining: 21.5s
301:	learn: 0.0854871	total: 9.27s	remaining: 21.4s
302:	learn: 0.0854652	total: 9.3s	remaining: 21.4s
303:	learn: 0.0854336	total: 9.34s	remaining: 21.4s
304:	learn: 0.0852779	total: 9.37s	remaining: 21.3s
305:	learn: 0.0850940	total: 9.4s	remaining: 21.3s
306:	learn: 0.0849645	total: 9.43s	remaining: 21.3s
307:	learn: 0.0848807	total: 9.46s	remaining: 21.3s
308:	learn: 0.0848747	total: 9.49s	remaining: 21.2s
309:	learn: 0.0848665	total: 9.52s	remaining: 21.2s
310:	learn: 0.0846978	total: 9.55s	remaining: 21.2s
311:	learn: 0.0846817	total: 9.59s	remaining: 21.1s
312:	learn: 0.0846585	total: 9.62s	remaining: 21.1s
313:	learn: 0.0844330	total: 9.65s	remaining: 21.1s
314:	learn: 0.0843585	total: 9.68s	remaining: 21.1s
315:	learn: 0.0843486	total: 9.71s	remaining: 21s
316:	learn: 0.0841825	total: 9.74s	remaining: 21s
317:	learn: 0.0840964	total: 9.77s	remaining: 20.9s
318:	learn: 0.0840131	total: 9.8s	remaining: 20.9s
319:	learn: 0.0839159	total: 9.82s	remaining: 20.9s
320:	learn: 0.0838620	total: 9.86s	remaining: 20.9s
321:	learn: 0.0838439	total: 9.89s	remaining: 20.8s
322:	learn: 0.0837404	total: 9.92s	remaining: 20.8s
323:	learn: 0.0837168	total: 9.95s	remaining: 20.8s
324:	learn: 0.0836353	total: 9.98s	remaining: 20.7s
325:	learn: 0.0834780	total: 10s	remaining: 20.7s
326:	learn: 0.0833751	total: 10.1s	remaining: 20.7s
327:	learn: 0.0833028	total: 10.1s	remaining: 20.7s
328:	learn: 0.0832935	total: 10.1s	remaining: 20.6s
329:	learn: 0.0832847	total: 10.1s	remaining: 20.6s
330:	learn: 0.0832695	total: 10.2s	remaining: 20.6s
331:	learn: 0.0832176	total: 10.2s	remaining: 20.5s
332:	learn: 0.0832006	total: 10.2s	remaining: 20.5s
333:	learn: 0.0830420	total: 10.3s	remaining: 20.5s
334:	learn: 0.0828868	total: 10.3s	remaining: 20.4s
335:	learn: 0.0827507	total: 10.3s	remaining: 20.4s
336:	learn: 0.0826849	total: 10.4s	remaining: 20.4s
337:	learn: 0.0825562	total: 10.4s	remaining: 20.3s
338:	learn: 0.0825056	total: 10.4s	remaining: 20.3s
339:	learn: 0.0824153	total: 10.4s	remaining: 20.3s
340:	learn: 0.0823132	total: 10.5s	remaining: 20.3s
341:	learn: 0.0822924	total: 10.5s	remaining: 20.2s
342:	learn: 0.0822757	total: 10.5s	remaining: 20.2s
343:	learn: 0.0821054	total: 10.6s	remaining: 20.2s
344:	learn: 0.0820522	total: 10.6s	remaining: 20.1s
345:	learn: 0.0818830	total: 10.6s	remaining: 20.1s
346:	learn: 0.0818745	total: 10.7s	remaining: 20.1s
347:	learn: 0.0818071	total: 10.7s	remaining: 20s
348:	learn: 0.0816536	total: 10.7s	remaining: 20s
349:	learn: 0.0816281	total: 10.8s	remaining: 20s
350:	learn: 0.0815690	total: 10.8s	remaining: 19.9s
351:	learn: 0.0815278	total: 10.8s	remaining: 19.9s
352:	learn: 0.0815054	total: 10.8s	remaining: 19.9s
353:	learn: 0.0813334	total: 10.9s	remaining: 19.8s
354:	learn: 0.0812115	total: 10.9s	remaining: 19.8s
355:	learn: 0.0810450	total: 10.9s	remaining: 19.8s
356:	learn: 0.0810125	total: 11s	remaining: 19.8s
357:	learn: 0.0809925	total: 11s	remaining: 19.7s
358:	learn: 0.0808283	total: 11s	remaining: 19.7s
359:	learn: 0.0806878	total: 11.1s	remaining: 19.7s
360:	learn: 0.0806291	total: 11.1s	remaining: 19.6s
361:	learn: 0.0805704	total: 11.1s	remaining: 19.6s
362:	learn: 0.0803999	total: 11.2s	remaining: 19.6s
363:	learn: 0.0803347	total: 11.2s	remaining: 19.5s
364:	learn: 0.0803217	total: 11.2s	remaining: 19.5s
365:	learn: 0.0803131	total: 11.2s	remaining: 19.5s
366:	learn: 0.0802695	total: 11.3s	remaining: 19.5s
367:	learn: 0.0801788	total: 11.3s	remaining: 19.4s
368:	learn: 0.0800542	total: 11.4s	remaining: 19.4s
369:	learn: 0.0799486	total: 11.4s	remaining: 19.4s
370:	learn: 0.0799359	total: 11.4s	remaining: 19.4s
371:	learn: 0.0797618	total: 11.4s	remaining: 19.3s
372:	learn: 0.0796198	total: 11.5s	remaining: 19.3s
373:	learn: 0.0794531	total: 11.5s	remaining: 19.3s
374:	learn: 0.0792773	total: 11.5s	remaining: 19.2s
375:	learn: 0.0791877	total: 11.6s	remaining: 19.2s
376:	learn: 0.0790187	total: 11.6s	remaining: 19.2s
377:	learn: 0.0789597	total: 11.6s	remaining: 19.1s
378:	learn: 0.0788683	total: 11.7s	remaining: 19.1s
379:	learn: 0.0788297	total: 11.7s	remaining: 19.1s
380:	learn: 0.0787406	total: 11.7s	remaining: 19s
381:	learn: 0.0787021	total: 11.7s	remaining: 19s
382:	learn: 0.0785210	total: 11.8s	remaining: 19s
383:	learn: 0.0785095	total: 11.8s	remaining: 18.9s
384:	learn: 0.0784010	total: 11.8s	remaining: 18.9s
385:	learn: 0.0782587	total: 11.9s	remaining: 18.9s
386:	learn: 0.0781255	total: 11.9s	remaining: 18.8s
387:	learn: 0.0780542	total: 11.9s	remaining: 18.8s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior1st': 1 unseen categories converted to Unseen on transform.

CV folds:  38%|███▊      | 19/50 [10:01<16:24, 31.77s/fold]

Learning rate set to 0.042743
0:	learn: 0.3853033	total: 24.5ms	remaining: 24.5s
1:	learn: 0.3750467	total: 54.5ms	remaining: 27.2s
2:	learn: 0.3647004	total: 85ms	remaining: 28.3s
3:	learn: 0.3545314	total: 117ms	remaining: 29s
4:	learn: 0.3447019	total: 147ms	remaining: 29.3s
5:	learn: 0.3363853	total: 196ms	remaining: 32.5s
6:	learn: 0.3273014	total: 226ms	remaining: 32s
7:	learn: 0.3192368	total: 261ms	remaining: 32.3s
8:	learn: 0.3107936	total: 291ms	remaining: 32s
9:	learn: 0.3033413	total: 323ms	remaining: 32s
10:	learn: 0.2956221	total: 351ms	remaining: 31.6s
11:	learn: 0.2886197	total: 381ms	remaining: 31.3s
12:	learn: 0.2821821	total: 411ms	remaining: 31.2s
13:	learn: 0.2757743	total: 441ms	remaining: 31s
14:	learn: 0.2692883	total: 473ms	remaining: 31.1s
15:	learn: 0.2636027	total: 518ms	remaining: 31.9s
16:	learn: 0.2582068	total: 556ms	remaining: 32.1s
17:	learn: 0.2525208	total: 585ms	remaining: 31.9s
18:	learn: 0.2469201	total: 614ms	remaining: 31.7s
19:	learn: 0.2420185	total: 642ms	remaining: 31.5s
20:	learn: 0.2366161	total: 673ms	remaining: 31.4s
21:	learn: 0.2317345	total: 701ms	remaining: 31.2s
22:	learn: 0.2273560	total: 731ms	remaining: 31.1s
23:	learn: 0.2231736	total: 763ms	remaining: 31s
24:	learn: 0.2189867	total: 794ms	remaining: 31s
25:	learn: 0.2149933	total: 823ms	remaining: 30.8s
26:	learn: 0.2110633	total: 851ms	remaining: 30.7s
27:	learn: 0.2073193	total: 879ms	remaining: 30.5s
28:	learn: 0.2036629	total: 913ms	remaining: 30.6s
29:	learn: 0.2004050	total: 942ms	remaining: 30.5s
30:	learn: 0.1973387	total: 973ms	remaining: 30.4s
31:	learn: 0.1942578	total: 1s	remaining: 30.3s
32:	learn: 0.1913370	total: 1.03s	remaining: 30.3s
33:	learn: 0.1882735	total: 1.06s	remaining: 30.2s
34:	learn: 0.1854430	total: 1.09s	remaining: 30.1s
35:	learn: 0.1828830	total: 1.12s	remaining: 30.1s
36:	learn: 0.1800708	total: 1.15s	remaining: 30.1s
37:	learn: 0.1775228	total: 1.19s	remaining: 30s
38:	learn: 0.1751860	total: 1.21s	remaining: 29.9s
39:	learn: 0.1726798	total: 1.24s	remaining: 29.8s
40:	learn: 0.1702936	total: 1.27s	remaining: 29.7s
41:	learn: 0.1681457	total: 1.3s	remaining: 29.6s
42:	learn: 0.1662107	total: 1.32s	remaining: 29.4s
43:	learn: 0.1642306	total: 1.35s	remaining: 29.4s
44:	learn: 0.1622875	total: 1.38s	remaining: 29.3s
45:	learn: 0.1604033	total: 1.41s	remaining: 29.3s
46:	learn: 0.1586353	total: 1.44s	remaining: 29.3s
47:	learn: 0.1571619	total: 1.47s	remaining: 29.2s
48:	learn: 0.1556282	total: 1.5s	remaining: 29.1s
49:	learn: 0.1540969	total: 1.53s	remaining: 29.1s
50:	learn: 0.1527089	total: 1.56s	remaining: 29s
51:	learn: 0.1511798	total: 1.59s	remaining: 29s
52:	learn: 0.1498054	total: 1.62s	remaining: 28.9s
53:	learn: 0.1483776	total: 1.65s	remaining: 28.9s
54:	learn: 0.1470146	total: 1.68s	remaining: 28.9s
55:	learn: 0.1458180	total: 1.71s	remaining: 28.8s
56:	learn: 0.1445792	total: 1.74s	remaining: 28.7s
57:	learn: 0.1433245	total: 1.77s	remaining: 28.7s
58:	learn: 0.1422496	total: 1.8s	remaining: 28.7s
59:	learn: 0.1411688	total: 1.83s	remaining: 28.7s
60:	learn: 0.1401372	total: 1.86s	remaining: 28.6s
61:	learn: 0.1389217	total: 1.89s	remaining: 28.5s
62:	learn: 0.1378557	total: 1.92s	remaining: 28.5s
63:	learn: 0.1371223	total: 1.95s	remaining: 28.5s
64:	learn: 0.1363127	total: 1.98s	remaining: 28.4s
65:	learn: 0.1351916	total: 2s	remaining: 28.4s
66:	learn: 0.1343548	total: 2.03s	remaining: 28.3s
67:	learn: 0.1336475	total: 2.06s	remaining: 28.3s
68:	learn: 0.1328220	total: 2.09s	remaining: 28.2s
69:	learn: 0.1320578	total: 2.12s	remaining: 28.2s
70:	learn: 0.1312338	total: 2.15s	remaining: 28.1s
71:	learn: 0.1305093	total: 2.18s	remaining: 28.1s
72:	learn: 0.1299021	total: 2.22s	remaining: 28.2s
73:	learn: 0.1293597	total: 2.25s	remaining: 28.2s
74:	learn: 0.1289161	total: 2.28s	remaining: 28.2s
75:	learn: 0.1283704	total: 2.33s	remaining: 28.3s
76:	learn: 0.1277936	total: 2.36s	remaining: 28.3s
77:	learn: 0.1270680	total: 2.39s	remaining: 28.3s
78:	learn: 0.1265056	total: 2.42s	remaining: 28.2s
79:	learn: 0.1259174	total: 2.45s	remaining: 28.2s
80:	learn: 0.1252781	total: 2.48s	remaining: 28.2s
81:	learn: 0.1247230	total: 2.52s	remaining: 28.2s
82:	learn: 0.1242023	total: 2.54s	remaining: 28.1s
83:	learn: 0.1237829	total: 2.57s	remaining: 28.1s
84:	learn: 0.1233265	total: 2.6s	remaining: 28s
85:	learn: 0.1225516	total: 2.63s	remaining: 28s
86:	learn: 0.1219009	total: 2.66s	remaining: 27.9s
87:	learn: 0.1213190	total: 2.69s	remaining: 27.9s
88:	learn: 0.1208776	total: 2.72s	remaining: 27.9s
89:	learn: 0.1204830	total: 2.76s	remaining: 27.9s
90:	learn: 0.1200852	total: 2.78s	remaining: 27.8s
91:	learn: 0.1194571	total: 2.81s	remaining: 27.8s
92:	learn: 0.1188340	total: 2.84s	remaining: 27.7s
93:	learn: 0.1183019	total: 2.88s	remaining: 27.7s
94:	learn: 0.1178873	total: 2.91s	remaining: 27.7s
95:	learn: 0.1173759	total: 2.94s	remaining: 27.7s
96:	learn: 0.1169344	total: 2.97s	remaining: 27.7s
97:	learn: 0.1164226	total: 3s	remaining: 27.6s
98:	learn: 0.1160660	total: 3.03s	remaining: 27.6s
99:	learn: 0.1157025	total: 3.06s	remaining: 27.6s
100:	learn: 0.1152565	total: 3.09s	remaining: 27.5s
101:	learn: 0.1147975	total: 3.12s	remaining: 27.5s
102:	learn: 0.1144067	total: 3.15s	remaining: 27.5s
103:	learn: 0.1141590	total: 3.18s	remaining: 27.4s
104:	learn: 0.1138412	total: 3.21s	remaining: 27.4s
105:	learn: 0.1135912	total: 3.24s	remaining: 27.3s
106:	learn: 0.1132982	total: 3.27s	remaining: 27.3s
107:	learn: 0.1130483	total: 3.3s	remaining: 27.2s
108:	learn: 0.1128185	total: 3.33s	remaining: 27.2s
109:	learn: 0.1124974	total: 3.37s	remaining: 27.3s
110:	learn: 0.1120143	total: 3.4s	remaining: 27.3s
111:	learn: 0.1117642	total: 3.43s	remaining: 27.2s
112:	learn: 0.1114916	total: 3.46s	remaining: 27.2s
113:	learn: 0.1112141	total: 3.49s	remaining: 27.1s
114:	learn: 0.1107390	total: 3.52s	remaining: 27.1s
115:	learn: 0.1103928	total: 3.54s	remaining: 27s
116:	learn: 0.1101236	total: 3.57s	remaining: 27s
117:	learn: 0.1099046	total: 3.6s	remaining: 26.9s
118:	learn: 0.1095163	total: 3.63s	remaining: 26.9s
119:	learn: 0.1092257	total: 3.67s	remaining: 26.9s
120:	learn: 0.1088968	total: 3.69s	remaining: 26.8s
121:	learn: 0.1085875	total: 3.72s	remaining: 26.8s
122:	learn: 0.1083444	total: 3.75s	remaining: 26.8s
123:	learn: 0.1080826	total: 3.79s	remaining: 26.8s
124:	learn: 0.1077434	total: 3.82s	remaining: 26.7s
125:	learn: 0.1074904	total: 3.85s	remaining: 26.7s
126:	learn: 0.1073168	total: 3.88s	remaining: 26.6s
127:	learn: 0.1070532	total: 3.91s	remaining: 26.6s
128:	learn: 0.1069835	total: 3.92s	remaining: 26.5s
129:	learn: 0.1066429	total: 3.94s	remaining: 26.4s
130:	learn: 0.1064360	total: 3.97s	remaining: 26.4s
131:	learn: 0.1062085	total: 4s	remaining: 26.3s
132:	learn: 0.1059863	total: 4.03s	remaining: 26.3s
133:	learn: 0.1056177	total: 4.06s	remaining: 26.2s
134:	learn: 0.1054554	total: 4.09s	remaining: 26.2s
135:	learn: 0.1052023	total: 4.12s	remaining: 26.2s
136:	learn: 0.1049367	total: 4.15s	remaining: 26.1s
137:	learn: 0.1048171	total: 4.18s	remaining: 26.1s
138:	learn: 0.1046737	total: 4.21s	remaining: 26.1s
139:	learn: 0.1044280	total: 4.24s	remaining: 26.1s
140:	learn: 0.1043798	total: 4.27s	remaining: 26s
141:	learn: 0.1042123	total: 4.31s	remaining: 26s
142:	learn: 0.1040464	total: 4.34s	remaining: 26s
143:	learn: 0.1039031	total: 4.37s	remaining: 26s
144:	learn: 0.1037002	total: 4.4s	remaining: 25.9s
145:	learn: 0.1035277	total: 4.43s	remaining: 25.9s
146:	learn: 0.1033747	total: 4.47s	remaining: 25.9s
147:	learn: 0.1031598	total: 4.5s	remaining: 25.9s
148:	learn: 0.1030991	total: 4.53s	remaining: 25.9s
149:	learn: 0.1028383	total: 4.56s	remaining: 25.8s
150:	learn: 0.1027727	total: 4.59s	remaining: 25.8s
151:	learn: 0.1024955	total: 4.62s	remaining: 25.8s
152:	learn: 0.1023894	total: 4.65s	remaining: 25.7s
153:	learn: 0.1021480	total: 4.68s	remaining: 25.7s
154:	learn: 0.1019161	total: 4.71s	remaining: 25.7s
155:	learn: 0.1018093	total: 4.74s	remaining: 25.6s
156:	learn: 0.1016517	total: 4.77s	remaining: 25.6s
157:	learn: 0.1014792	total: 4.8s	remaining: 25.6s
158:	learn: 0.1013051	total: 4.83s	remaining: 25.6s
159:	learn: 0.1011945	total: 4.86s	remaining: 25.5s
160:	learn: 0.1009872	total: 4.89s	remaining: 25.5s
161:	learn: 0.1007177	total: 4.92s	remaining: 25.5s
162:	learn: 0.1005070	total: 4.96s	remaining: 25.5s
163:	learn: 0.1003715	total: 4.99s	remaining: 25.4s
164:	learn: 0.1001901	total: 5.02s	remaining: 25.4s
165:	learn: 0.1000797	total: 5.05s	remaining: 25.4s
166:	learn: 0.0998369	total: 5.08s	remaining: 25.3s
167:	learn: 0.0996459	total: 5.11s	remaining: 25.3s
168:	learn: 0.0994041	total: 5.14s	remaining: 25.3s
169:	learn: 0.0992533	total: 5.17s	remaining: 25.3s
170:	learn: 0.0990150	total: 5.2s	remaining: 25.2s
171:	learn: 0.0987901	total: 5.23s	remaining: 25.2s
172:	learn: 0.0986810	total: 5.26s	remaining: 25.1s
173:	learn: 0.0986530	total: 5.29s	remaining: 25.1s
174:	learn: 0.0984459	total: 5.32s	remaining: 25.1s
175:	learn: 0.0983371	total: 5.35s	remaining: 25s
176:	learn: 0.0982234	total: 5.38s	remaining: 25s
177:	learn: 0.0980419	total: 5.41s	remaining: 25s
178:	learn: 0.0979445	total: 5.43s	remaining: 24.9s
179:	learn: 0.0978064	total: 5.46s	remaining: 24.9s
180:	learn: 0.0977978	total: 5.49s	remaining: 24.9s
181:	learn: 0.0977117	total: 5.52s	remaining: 24.8s
182:	learn: 0.0974008	total: 5.55s	remaining: 24.8s
183:	learn: 0.0971544	total: 5.59s	remaining: 24.8s
184:	learn: 0.0969179	total: 5.62s	remaining: 24.7s
185:	learn: 0.0968393	total: 5.65s	remaining: 24.7s
186:	learn: 0.0966702	total: 5.68s	remaining: 24.7s
187:	learn: 0.0964812	total: 5.71s	remaining: 24.7s
188:	learn: 0.0963998	total: 5.74s	remaining: 24.6s
189:	learn: 0.0963694	total: 5.77s	remaining: 24.6s
190:	learn: 0.0961453	total: 5.8s	remaining: 24.6s
191:	learn: 0.0959650	total: 5.83s	remaining: 24.5s
192:	learn: 0.0958596	total: 5.86s	remaining: 24.5s
193:	learn: 0.0957748	total: 5.89s	remaining: 24.5s
194:	learn: 0.0956523	total: 5.92s	remaining: 24.5s
195:	learn: 0.0955523	total: 5.96s	remaining: 24.4s
196:	learn: 0.0955276	total: 5.99s	remaining: 24.4s
197:	learn: 0.0953069	total: 6.02s	remaining: 24.4s
198:	learn: 0.0951806	total: 6.05s	remaining: 24.4s
199:	learn: 0.0949983	total: 6.08s	remaining: 24.3s
200:	learn: 0.0949505	total: 6.12s	remaining: 24.3s
201:	learn: 0.0948403	total: 6.14s	remaining: 24.3s
202:	learn: 0.0946425	total: 6.17s	remaining: 24.2s
203:	learn: 0.0944749	total: 6.2s	remaining: 24.2s
204:	learn: 0.0943016	total: 6.23s	remaining: 24.2s
205:	learn: 0.0940225	total: 6.26s	remaining: 24.1s
206:	learn: 0.0938970	total: 6.29s	remaining: 24.1s
207:	learn: 0.0936706	total: 6.32s	remaining: 24.1s
208:	learn: 0.0935958	total: 6.35s	remaining: 24.1s
209:	learn: 0.0935623	total: 6.39s	remaining: 24s
210:	learn: 0.0934254	total: 6.42s	remaining: 24s
211:	learn: 0.0931919	total: 6.45s	remaining: 24s
212:	learn: 0.0929530	total: 6.49s	remaining: 24s
213:	learn: 0.0928886	total: 6.52s	remaining: 24s
214:	learn: 0.0928713	total: 6.55s	remaining: 23.9s
215:	learn: 0.0926130	total: 6.58s	remaining: 23.9s
216:	learn: 0.0923086	total: 6.63s	remaining: 23.9s
217:	learn: 0.0922447	total: 6.66s	remaining: 23.9s
218:	learn: 0.0921135	total: 6.69s	remaining: 23.9s
219:	learn: 0.0921051	total: 6.72s	remaining: 23.8s
220:	learn: 0.0920264	total: 6.76s	remaining: 23.8s
221:	learn: 0.0919411	total: 6.79s	remaining: 23.8s
222:	learn: 0.0918406	total: 6.82s	remaining: 23.8s
223:	learn: 0.0917721	total: 6.85s	remaining: 23.7s
224:	learn: 0.0916133	total: 6.88s	remaining: 23.7s
225:	learn: 0.0913518	total: 6.91s	remaining: 23.7s
226:	learn: 0.0911855	total: 6.94s	remaining: 23.6s
227:	learn: 0.0911026	total: 6.97s	remaining: 23.6s
228:	learn: 0.0910922	total: 7s	remaining: 23.6s
229:	learn: 0.0907745	total: 7.03s	remaining: 23.5s
230:	learn: 0.0907471	total: 7.06s	remaining: 23.5s
231:	learn: 0.0907374	total: 7.09s	remaining: 23.5s
232:	learn: 0.0905949	total: 7.12s	remaining: 23.4s
233:	learn: 0.0905033	total: 7.15s	remaining: 23.4s
234:	learn: 0.0902429	total: 7.18s	remaining: 23.4s
235:	learn: 0.0900999	total: 7.21s	remaining: 23.3s
236:	learn: 0.0899650	total: 7.24s	remaining: 23.3s
237:	learn: 0.0899494	total: 7.27s	remaining: 23.3s
238:	learn: 0.0897789	total: 7.31s	remaining: 23.3s
239:	learn: 0.0896579	total: 7.34s	remaining: 23.2s
240:	learn: 0.0896154	total: 7.37s	remaining: 23.2s
241:	learn: 0.0895325	total: 7.4s	remaining: 23.2s
242:	learn: 0.0895162	total: 7.43s	remaining: 23.1s
243:	learn: 0.0895060	total: 7.46s	remaining: 23.1s
244:	learn: 0.0893225	total: 7.49s	remaining: 23.1s
245:	learn: 0.0891471	total: 7.54s	remaining: 23.1s
246:	learn: 0.0889780	total: 7.58s	remaining: 23.1s
247:	learn: 0.0889714	total: 7.61s	remaining: 23.1s
248:	learn: 0.0888642	total: 7.64s	remaining: 23s
249:	learn: 0.0887440	total: 7.67s	remaining: 23s
250:	learn: 0.0886981	total: 7.7s	remaining: 23s
251:	learn: 0.0885399	total: 7.73s	remaining: 22.9s
252:	learn: 0.0884702	total: 7.76s	remaining: 22.9s
253:	learn: 0.0884302	total: 7.79s	remaining: 22.9s
254:	learn: 0.0883271	total: 7.82s	remaining: 22.8s
255:	learn: 0.0882511	total: 7.85s	remaining: 22.8s
256:	learn: 0.0880027	total: 7.88s	remaining: 22.8s
257:	learn: 0.0878168	total: 7.91s	remaining: 22.8s
258:	learn: 0.0877249	total: 7.94s	remaining: 22.7s
259:	learn: 0.0876114	total: 7.97s	remaining: 22.7s
260:	learn: 0.0875027	total: 8s	remaining: 22.7s
261:	learn: 0.0873335	total: 8.03s	remaining: 22.6s
262:	learn: 0.0873011	total: 8.06s	remaining: 22.6s
263:	learn: 0.0871796	total: 8.09s	remaining: 22.6s
264:	learn: 0.0871031	total: 8.13s	remaining: 22.5s
265:	learn: 0.0869548	total: 8.16s	remaining: 22.5s
266:	learn: 0.0869255	total: 8.19s	remaining: 22.5s
267:	learn: 0.0869142	total: 8.22s	remaining: 22.5s
268:	learn: 0.0867818	total: 8.25s	remaining: 22.4s
269:	learn: 0.0866358	total: 8.28s	remaining: 22.4s
270:	learn: 0.0865993	total: 8.31s	remaining: 22.4s
271:	learn: 0.0865865	total: 8.34s	remaining: 22.3s
272:	learn: 0.0865759	total: 8.38s	remaining: 22.3s
273:	learn: 0.0863961	total: 8.41s	remaining: 22.3s
274:	learn: 0.0863613	total: 8.44s	remaining: 22.2s
275:	learn: 0.0862519	total: 8.47s	remaining: 22.2s
276:	learn: 0.0861078	total: 8.5s	remaining: 22.2s
277:	learn: 0.0859701	total: 8.53s	remaining: 22.1s
278:	learn: 0.0858306	total: 8.56s	remaining: 22.1s
279:	learn: 0.0857024	total: 8.59s	remaining: 22.1s
280:	learn: 0.0855267	total: 8.62s	remaining: 22.1s
281:	learn: 0.0852947	total: 8.67s	remaining: 22.1s
282:	learn: 0.0852539	total: 8.7s	remaining: 22s
283:	learn: 0.0852143	total: 8.72s	remaining: 22s
284:	learn: 0.0851737	total: 8.76s	remaining: 22s
285:	learn: 0.0851136	total: 8.81s	remaining: 22s
286:	learn: 0.0851025	total: 8.84s	remaining: 22s
287:	learn: 0.0850467	total: 8.87s	remaining: 21.9s
288:	learn: 0.0849005	total: 8.9s	remaining: 21.9s
289:	learn: 0.0848423	total: 8.93s	remaining: 21.9s
290:	learn: 0.0846881	total: 8.96s	remaining: 21.8s
291:	learn: 0.0845513	total: 8.99s	remaining: 21.8s
292:	learn: 0.0844808	total: 9.02s	remaining: 21.8s
293:	learn: 0.0844745	total: 9.06s	remaining: 21.7s
294:	learn: 0.0843582	total: 9.09s	remaining: 21.7s
295:	learn: 0.0842787	total: 9.12s	remaining: 21.7s
296:	learn: 0.0840578	total: 9.15s	remaining: 21.7s
297:	learn: 0.0838820	total: 9.18s	remaining: 21.6s
298:	learn: 0.0838090	total: 9.21s	remaining: 21.6s
299:	learn: 0.0837828	total: 9.24s	remaining: 21.6s
300:	learn: 0.0836210	total: 9.27s	remaining: 21.5s
301:	learn: 0.0835536	total: 9.3s	remaining: 21.5s
302:	learn: 0.0834917	total: 9.34s	remaining: 21.5s
303:	learn: 0.0833207	total: 9.37s	remaining: 21.5s
304:	learn: 0.0833136	total: 9.4s	remaining: 21.4s
305:	learn: 0.0832703	total: 9.43s	remaining: 21.4s
306:	learn: 0.0831596	total: 9.46s	remaining: 21.4s
307:	learn: 0.0831473	total: 9.49s	remaining: 21.3s
308:	learn: 0.0830245	total: 9.52s	remaining: 21.3s
309:	learn: 0.0828896	total: 9.55s	remaining: 21.3s
310:	learn: 0.0827719	total: 9.58s	remaining: 21.2s
311:	learn: 0.0827577	total: 9.61s	remaining: 21.2s
312:	learn: 0.0825964	total: 9.64s	remaining: 21.2s
313:	learn: 0.0824734	total: 9.68s	remaining: 21.1s
314:	learn: 0.0824022	total: 9.71s	remaining: 21.1s
315:	learn: 0.0823113	total: 9.74s	remaining: 21.1s
316:	learn: 0.0821922	total: 9.77s	remaining: 21s
317:	learn: 0.0821800	total: 9.8s	remaining: 21s
318:	learn: 0.0821243	total: 9.83s	remaining: 21s
319:	learn: 0.0819586	total: 9.86s	remaining: 21s
320:	learn: 0.0818259	total: 9.89s	remaining: 20.9s
321:	learn: 0.0817604	total: 9.92s	remaining: 20.9s
322:	learn: 0.0815995	total: 9.95s	remaining: 20.9s
323:	learn: 0.0814708	total: 9.98s	remaining: 20.8s
324:	learn: 0.0814271	total: 10s	remaining: 20.8s
325:	learn: 0.0812743	total: 10s	remaining: 20.8s
326:	learn: 0.0811910	total: 10.1s	remaining: 20.7s
327:	learn: 0.0810465	total: 10.1s	remaining: 20.7s
328:	learn: 0.0810141	total: 10.1s	remaining: 20.7s
329:	learn: 0.0809455	total: 10.2s	remaining: 20.7s
330:	learn: 0.0807755	total: 10.2s	remaining: 20.6s
331:	learn: 0.0807678	total: 10.2s	remaining: 20.6s
332:	learn: 0.0806406	total: 10.3s	remaining: 20.6s
333:	learn: 0.0805078	total: 10.3s	remaining: 20.5s
334:	learn: 0.0804208	total: 10.3s	remaining: 20.5s
335:	learn: 0.0803409	total: 10.4s	remaining: 20.5s
336:	learn: 0.0803187	total: 10.4s	remaining: 20.4s
337:	learn: 0.0802180	total: 10.4s	remaining: 20.4s
338:	learn: 0.0800506	total: 10.5s	remaining: 20.4s
339:	learn: 0.0799620	total: 10.5s	remaining: 20.4s
340:	learn: 0.0798089	total: 10.5s	remaining: 20.3s
341:	learn: 0.0797772	total: 10.6s	remaining: 20.3s
342:	learn: 0.0796342	total: 10.6s	remaining: 20.3s
343:	learn: 0.0794855	total: 10.6s	remaining: 20.2s
344:	learn: 0.0793822	total: 10.6s	remaining: 20.2s
345:	learn: 0.0791949	total: 10.7s	remaining: 20.2s
346:	learn: 0.0790590	total: 10.7s	remaining: 20.1s
347:	learn: 0.0789554	total: 10.7s	remaining: 20.1s
348:	learn: 0.0789374	total: 10.8s	remaining: 20.1s
349:	learn: 0.0787914	total: 10.8s	remaining: 20s
350:	learn: 0.0787270	total: 10.8s	remaining: 20s
351:	learn: 0.0786111	total: 10.9s	remaining: 20s
352:	learn: 0.0785700	total: 10.9s	remaining: 19.9s
353:	learn: 0.0784591	total: 10.9s	remaining: 19.9s
354:	learn: 0.0782752	total: 11s	remaining: 19.9s
355:	learn: 0.0781507	total: 11s	remaining: 19.9s
356:	learn: 0.0780383	total: 11s	remaining: 19.9s
357:	learn: 0.0779903	total: 11.1s	remaining: 19.8s
358:	learn: 0.0779557	total: 11.1s	remaining: 19.8s
359:	learn: 0.0778856	total: 11.1s	remaining: 19.8s
360:	learn: 0.0778181	total: 11.1s	remaining: 19.7s
361:	learn: 0.0777638	total: 11.2s	remaining: 19.7s
362:	learn: 0.0776536	total: 11.2s	remaining: 19.7s
363:	learn: 0.0775791	total: 11.2s	remaining: 19.7s
364:	learn: 0.0775044	total: 11.3s	remaining: 19.6s
365:	learn: 0.0774169	total: 11.3s	remaining: 19.6s
366:	learn: 0.0773092	total: 11.3s	remaining: 19.6s
367:	learn: 0.0771863	total: 11.4s	remaining: 19.5s
368:	learn: 0.0770897	total: 11.4s	remaining: 19.5s
369:	learn: 0.0770266	total: 11.4s	remaining: 19.5s
370:	learn: 0.0769878	total: 11.5s	remaining: 19.4s
371:	learn: 0.0769281	total: 11.5s	remaining: 19.4s
372:	learn: 0.0767717	total: 11.5s	remaining: 19.4s
373:	learn: 0.0766847	total: 11.6s	remaining: 19.4s
374:	learn: 0.0766212	total: 11.6s	remaining: 19.3s
375:	learn: 0.0764751	total: 11.6s	remaining: 19.3s
376:	learn: 0.0764491	total: 11.7s	remaining: 19.3s
377:	learn: 0.0764374	total: 11.7s	remaining: 19.3s
378:	learn: 0.0763352	total: 11.7s	remaining: 19.2s
379:	learn: 0.0762867	total: 11.8s	remaining: 19.2s
380:	learn: 0.0761852	total: 11.8s	remaining: 19.2s
381:	learn: 0.0761732	total: 11.8s	remaining: 19.1s
382:	learn: 0.0760251	total: 11.9s	remaining: 19.1s
383:	learn: 0.0759862	total: 11.9s	remaining: 19.1s
384:	learn: 0.0759692	total: 11.9s	remaining: 19.1s
385:	learn: 0.0758324	total: 12s	remaining: 19s
386:	learn: 0.0758075	total: 12s	remaining: 19s
387:	learn: 0.0756585	total: 12s	remaining: 19s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior2nd': 1 unseen categories converted to Unseen on transform.

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'BsmtCond': 2 unseen categories converted to Unseen on transform.

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Electrical': 1 unseen categories converted to Unseen on transform.

CV folds:  40%|████      | 20/50 [10:33<15:52, 31.74s/fold]

997:	learn: 0.0455217	total: 31.1s	remaining: 62.3ms
998:	learn: 0.0455168	total: 31.1s	remaining: 31.2ms
999:	learn: 0.0455058	total: 31.1s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3885622	total: 23.3ms	remaining: 23.3s
1:	learn: 0.3780806	total: 51.4ms	remaining: 25.7s
2:	learn: 0.3676484	total: 80.2ms	remaining: 26.7s
3:	learn: 0.3581084	total: 110ms	remaining: 27.3s
4:	learn: 0.3485955	total: 139ms	remaining: 27.6s
5:	learn: 0.3395832	total: 168ms	remaining: 27.9s
6:	learn: 0.3309439	total: 199ms	remaining: 28.2s
7:	learn: 0.3225075	total: 233ms	remaining: 28.9s
8:	learn: 0.3146739	total: 263ms	remaining: 29s
9:	learn: 0.3067194	total: 294ms	remaining: 29.1s
10:	learn: 0.2989126	total: 323ms	remaining: 29s
11:	learn: 0.2920768	total: 352ms	remaining: 29s
12:	learn: 0.2848034	total: 382ms	remaining: 29s
13:	learn: 0.2784060	total: 411ms	remaining: 28.9s
14:	learn: 0.2717052	total: 440ms	remaining: 28.9s
15:	learn: 0.2654612	total: 468ms	remaining: 28.8s
16:	learn: 0.2594108	total: 499ms	remaining: 28.9s
17:	learn: 0.2538609	total: 530ms	remaining: 28.9s
18:	learn: 0.2481822	total: 562ms	remaining: 29s
19:	learn: 0.2430036	total: 591ms	remaining: 29s
20:	learn: 0.2380973	total: 640ms	remaining: 29.8s
21:	learn: 0.2332573	total: 670ms	remaining: 29.8s
22:	learn: 0.2287633	total: 698ms	remaining: 29.7s
23:	learn: 0.2240693	total: 728ms	remaining: 29.6s
24:	learn: 0.2197123	total: 761ms	remaining: 29.7s
25:	learn: 0.2155831	total: 788ms	remaining: 29.5s
26:	learn: 0.2117272	total: 819ms	remaining: 29.5s
27:	learn: 0.2079171	total: 846ms	remaining: 29.4s
28:	learn: 0.2045748	total: 877ms	remaining: 29.4s
29:	learn: 0.2007134	total: 906ms	remaining: 29.3s
30:	learn: 0.1973128	total: 940ms	remaining: 29.4s
31:	learn: 0.1941942	total: 972ms	remaining: 29.4s
32:	learn: 0.1914253	total: 1.01s	remaining: 29.5s
33:	learn: 0.1883297	total: 1.04s	remaining: 29.7s
34:	learn: 0.1853056	total: 1.07s	remaining: 29.6s
35:	learn: 0.1825680	total: 1.1s	remaining: 29.6s
36:	learn: 0.1799083	total: 1.13s	remaining: 29.5s
37:	learn: 0.1774444	total: 1.17s	remaining: 29.6s
38:	learn: 0.1752044	total: 1.2s	remaining: 29.7s
39:	learn: 0.1727224	total: 1.23s	remaining: 29.6s
40:	learn: 0.1701382	total: 1.26s	remaining: 29.5s
41:	learn: 0.1677444	total: 1.29s	remaining: 29.6s
42:	learn: 0.1657122	total: 1.33s	remaining: 29.6s
43:	learn: 0.1637100	total: 1.36s	remaining: 29.6s
44:	learn: 0.1617472	total: 1.39s	remaining: 29.5s
45:	learn: 0.1599451	total: 1.42s	remaining: 29.5s
46:	learn: 0.1577350	total: 1.45s	remaining: 29.4s
47:	learn: 0.1559215	total: 1.48s	remaining: 29.4s
48:	learn: 0.1542437	total: 1.51s	remaining: 29.3s
49:	learn: 0.1525950	total: 1.54s	remaining: 29.2s
50:	learn: 0.1511065	total: 1.57s	remaining: 29.2s
51:	learn: 0.1493683	total: 1.6s	remaining: 29.1s
52:	learn: 0.1478812	total: 1.63s	remaining: 29.2s
53:	learn: 0.1464219	total: 1.66s	remaining: 29.1s
54:	learn: 0.1450491	total: 1.69s	remaining: 29.1s
55:	learn: 0.1438887	total: 1.73s	remaining: 29.1s
56:	learn: 0.1427669	total: 1.75s	remaining: 29s
57:	learn: 0.1417923	total: 1.78s	remaining: 29s
58:	learn: 0.1406268	total: 1.81s	remaining: 28.9s
59:	learn: 0.1394718	total: 1.84s	remaining: 28.9s
60:	learn: 0.1383149	total: 1.87s	remaining: 28.8s
61:	learn: 0.1372317	total: 1.9s	remaining: 28.8s
62:	learn: 0.1361638	total: 1.93s	remaining: 28.7s
63:	learn: 0.1351683	total: 1.96s	remaining: 28.7s
64:	learn: 0.1342187	total: 1.99s	remaining: 28.6s
65:	learn: 0.1331885	total: 2.02s	remaining: 28.6s
66:	learn: 0.1323189	total: 2.05s	remaining: 28.6s
67:	learn: 0.1314822	total: 2.08s	remaining: 28.5s
68:	learn: 0.1307864	total: 2.11s	remaining: 28.5s
69:	learn: 0.1299919	total: 2.14s	remaining: 28.4s
70:	learn: 0.1294273	total: 2.17s	remaining: 28.4s
71:	learn: 0.1285940	total: 2.2s	remaining: 28.4s
72:	learn: 0.1279354	total: 2.23s	remaining: 28.3s
73:	learn: 0.1272118	total: 2.26s	remaining: 28.3s
74:	learn: 0.1265313	total: 2.29s	remaining: 28.3s
75:	learn: 0.1258329	total: 2.33s	remaining: 28.3s
76:	learn: 0.1252014	total: 2.36s	remaining: 28.3s
77:	learn: 0.1245554	total: 2.38s	remaining: 28.2s
78:	learn: 0.1240535	total: 2.41s	remaining: 28.1s
79:	learn: 0.1234487	total: 2.44s	remaining: 28.1s
80:	learn: 0.1227016	total: 2.47s	remaining: 28s
81:	learn: 0.1222978	total: 2.48s	remaining: 27.8s
82:	learn: 0.1216590	total: 2.51s	remaining: 27.8s
83:	learn: 0.1210391	total: 2.54s	remaining: 27.7s
84:	learn: 0.1204773	total: 2.57s	remaining: 27.7s
85:	learn: 0.1198564	total: 2.6s	remaining: 27.6s
86:	learn: 0.1193379	total: 2.63s	remaining: 27.6s
87:	learn: 0.1187579	total: 2.66s	remaining: 27.6s
88:	learn: 0.1183251	total: 2.69s	remaining: 27.5s
89:	learn: 0.1178780	total: 2.72s	remaining: 27.5s
90:	learn: 0.1173975	total: 2.75s	remaining: 27.5s
91:	learn: 0.1169391	total: 2.78s	remaining: 27.4s
92:	learn: 0.1164839	total: 2.81s	remaining: 27.4s
93:	learn: 0.1159979	total: 2.84s	remaining: 27.3s
94:	learn: 0.1156407	total: 2.87s	remaining: 27.3s
95:	learn: 0.1153273	total: 2.9s	remaining: 27.3s
96:	learn: 0.1147742	total: 2.92s	remaining: 27.2s
97:	learn: 0.1140052	total: 2.95s	remaining: 27.2s
98:	learn: 0.1134562	total: 2.99s	remaining: 27.2s
99:	learn: 0.1128491	total: 3.02s	remaining: 27.2s
100:	learn: 0.1123084	total: 3.04s	remaining: 27.1s
101:	learn: 0.1119514	total: 3.07s	remaining: 27.1s
102:	learn: 0.1114692	total: 3.1s	remaining: 27s
103:	learn: 0.1111629	total: 3.14s	remaining: 27.1s
104:	learn: 0.1111091	total: 3.19s	remaining: 27.2s
105:	learn: 0.1106373	total: 3.22s	remaining: 27.2s
106:	learn: 0.1104896	total: 3.24s	remaining: 27s
107:	learn: 0.1102656	total: 3.27s	remaining: 27s
108:	learn: 0.1098560	total: 3.3s	remaining: 27s
109:	learn: 0.1096752	total: 3.33s	remaining: 27s
110:	learn: 0.1092436	total: 3.36s	remaining: 26.9s
111:	learn: 0.1089865	total: 3.39s	remaining: 26.9s
112:	learn: 0.1086571	total: 3.42s	remaining: 26.9s
113:	learn: 0.1083684	total: 3.45s	remaining: 26.8s
114:	learn: 0.1080766	total: 3.48s	remaining: 26.8s
115:	learn: 0.1078178	total: 3.51s	remaining: 26.8s
116:	learn: 0.1075530	total: 3.54s	remaining: 26.7s
117:	learn: 0.1072232	total: 3.57s	remaining: 26.7s
118:	learn: 0.1071510	total: 3.6s	remaining: 26.7s
119:	learn: 0.1068904	total: 3.63s	remaining: 26.6s
120:	learn: 0.1066112	total: 3.66s	remaining: 26.6s
121:	learn: 0.1066008	total: 3.68s	remaining: 26.5s
122:	learn: 0.1063073	total: 3.71s	remaining: 26.5s
123:	learn: 0.1059527	total: 3.74s	remaining: 26.4s
124:	learn: 0.1057266	total: 3.77s	remaining: 26.4s
125:	learn: 0.1054565	total: 3.8s	remaining: 26.4s
126:	learn: 0.1054393	total: 3.83s	remaining: 26.3s
127:	learn: 0.1052064	total: 3.86s	remaining: 26.3s
128:	learn: 0.1049627	total: 3.9s	remaining: 26.3s
129:	learn: 0.1048713	total: 3.93s	remaining: 26.3s
130:	learn: 0.1046157	total: 3.96s	remaining: 26.3s
131:	learn: 0.1045767	total: 3.99s	remaining: 26.2s
132:	learn: 0.1045690	total: 4s	remaining: 26.1s
133:	learn: 0.1042070	total: 4.03s	remaining: 26s
134:	learn: 0.1039720	total: 4.06s	remaining: 26s
135:	learn: 0.1037601	total: 4.09s	remaining: 26s
136:	learn: 0.1036279	total: 4.12s	remaining: 26s
137:	learn: 0.1036078	total: 4.14s	remaining: 25.8s
138:	learn: 0.1033440	total: 4.16s	remaining: 25.8s
139:	learn: 0.1031207	total: 4.19s	remaining: 25.8s
140:	learn: 0.1031011	total: 4.21s	remaining: 25.7s
141:	learn: 0.1028357	total: 4.24s	remaining: 25.6s
142:	learn: 0.1026343	total: 4.27s	remaining: 25.6s
143:	learn: 0.1024097	total: 4.3s	remaining: 25.6s
144:	learn: 0.1022096	total: 4.33s	remaining: 25.6s
145:	learn: 0.1019880	total: 4.37s	remaining: 25.5s
146:	learn: 0.1018004	total: 4.39s	remaining: 25.5s
147:	learn: 0.1017962	total: 4.43s	remaining: 25.5s
148:	learn: 0.1014721	total: 4.45s	remaining: 25.4s
149:	learn: 0.1013040	total: 4.49s	remaining: 25.4s
150:	learn: 0.1010040	total: 4.51s	remaining: 25.4s
151:	learn: 0.1009311	total: 4.54s	remaining: 25.4s
152:	learn: 0.1008362	total: 4.57s	remaining: 25.3s
153:	learn: 0.1007168	total: 4.6s	remaining: 25.3s
154:	learn: 0.1005227	total: 4.63s	remaining: 25.2s
155:	learn: 0.1004937	total: 4.66s	remaining: 25.2s
156:	learn: 0.1003587	total: 4.68s	remaining: 25.1s
157:	learn: 0.1003548	total: 4.71s	remaining: 25.1s
158:	learn: 0.1001645	total: 4.74s	remaining: 25.1s
159:	learn: 0.0999832	total: 4.77s	remaining: 25s
160:	learn: 0.0999018	total: 4.8s	remaining: 25s
161:	learn: 0.0997987	total: 4.83s	remaining: 25s
162:	learn: 0.0997754	total: 4.86s	remaining: 24.9s
163:	learn: 0.0994569	total: 4.89s	remaining: 24.9s
164:	learn: 0.0992897	total: 4.92s	remaining: 24.9s
165:	learn: 0.0990789	total: 4.95s	remaining: 24.9s
166:	learn: 0.0990421	total: 4.98s	remaining: 24.8s
167:	learn: 0.0990421	total: 4.99s	remaining: 24.7s
168:	learn: 0.0988227	total: 5.02s	remaining: 24.7s
169:	learn: 0.0986612	total: 5.05s	remaining: 24.6s
170:	learn: 0.0984724	total: 5.08s	remaining: 24.6s
171:	learn: 0.0984455	total: 5.11s	remaining: 24.6s
172:	learn: 0.0982603	total: 5.14s	remaining: 24.6s
173:	learn: 0.0982052	total: 5.17s	remaining: 24.5s
174:	learn: 0.0982052	total: 5.18s	remaining: 24.4s
175:	learn: 0.0980049	total: 5.2s	remaining: 24.4s
176:	learn: 0.0978154	total: 5.23s	remaining: 24.3s
177:	learn: 0.0976893	total: 5.26s	remaining: 24.3s
178:	learn: 0.0976271	total: 5.29s	remaining: 24.3s
179:	learn: 0.0975162	total: 5.34s	remaining: 24.3s
180:	learn: 0.0972858	total: 5.38s	remaining: 24.3s
181:	learn: 0.0970524	total: 5.41s	remaining: 24.3s
182:	learn: 0.0970391	total: 5.43s	remaining: 24.2s
183:	learn: 0.0970261	total: 5.44s	remaining: 24.1s
184:	learn: 0.0969877	total: 5.47s	remaining: 24.1s
185:	learn: 0.0968132	total: 5.5s	remaining: 24.1s
186:	learn: 0.0966997	total: 5.53s	remaining: 24s
187:	learn: 0.0966220	total: 5.56s	remaining: 24s
188:	learn: 0.0964908	total: 5.59s	remaining: 24s
189:	learn: 0.0964468	total: 5.64s	remaining: 24.1s
190:	learn: 0.0961170	total: 5.67s	remaining: 24s
191:	learn: 0.0959842	total: 5.7s	remaining: 24s
192:	learn: 0.0959733	total: 5.71s	remaining: 23.9s
193:	learn: 0.0959116	total: 5.74s	remaining: 23.9s
194:	learn: 0.0958740	total: 5.77s	remaining: 23.8s
195:	learn: 0.0958053	total: 5.8s	remaining: 23.8s
196:	learn: 0.0956363	total: 5.83s	remaining: 23.8s
197:	learn: 0.0956141	total: 5.86s	remaining: 23.7s
198:	learn: 0.0955811	total: 5.89s	remaining: 23.7s
199:	learn: 0.0955543	total: 5.92s	remaining: 23.7s
200:	learn: 0.0953776	total: 5.94s	remaining: 23.6s
201:	learn: 0.0953510	total: 5.97s	remaining: 23.6s
202:	learn: 0.0953418	total: 5.98s	remaining: 23.5s
203:	learn: 0.0951506	total: 6.01s	remaining: 23.5s
204:	learn: 0.0950625	total: 6.04s	remaining: 23.4s
205:	learn: 0.0949398	total: 6.07s	remaining: 23.4s
206:	learn: 0.0947668	total: 6.1s	remaining: 23.4s
207:	learn: 0.0945394	total: 6.13s	remaining: 23.4s
208:	learn: 0.0945087	total: 6.17s	remaining: 23.3s
209:	learn: 0.0944637	total: 6.2s	remaining: 23.3s
210:	learn: 0.0944004	total: 6.23s	remaining: 23.3s
211:	learn: 0.0943703	total: 6.26s	remaining: 23.3s
212:	learn: 0.0943370	total: 6.29s	remaining: 23.2s
213:	learn: 0.0941440	total: 6.33s	remaining: 23.3s
214:	learn: 0.0940423	total: 6.36s	remaining: 23.2s
215:	learn: 0.0940203	total: 6.4s	remaining: 23.2s
216:	learn: 0.0937106	total: 6.43s	remaining: 23.2s
217:	learn: 0.0936924	total: 6.46s	remaining: 23.2s
218:	learn: 0.0936536	total: 6.49s	remaining: 23.1s
219:	learn: 0.0936039	total: 6.52s	remaining: 23.1s
220:	learn: 0.0935755	total: 6.55s	remaining: 23.1s
221:	learn: 0.0934472	total: 6.58s	remaining: 23.1s
222:	learn: 0.0934252	total: 6.61s	remaining: 23s
223:	learn: 0.0933833	total: 6.64s	remaining: 23s
224:	learn: 0.0933432	total: 6.67s	remaining: 23s
225:	learn: 0.0933196	total: 6.69s	remaining: 22.9s
226:	learn: 0.0930088	total: 6.72s	remaining: 22.9s
227:	learn: 0.0929863	total: 6.75s	remaining: 22.9s
228:	learn: 0.0929642	total: 6.78s	remaining: 22.8s
229:	learn: 0.0929458	total: 6.82s	remaining: 22.8s
230:	learn: 0.0929219	total: 6.84s	remaining: 22.8s
231:	learn: 0.0928758	total: 6.87s	remaining: 22.7s
232:	learn: 0.0927966	total: 6.9s	remaining: 22.7s
233:	learn: 0.0926779	total: 6.93s	remaining: 22.7s
234:	learn: 0.0926473	total: 6.96s	remaining: 22.7s
235:	learn: 0.0922890	total: 6.99s	remaining: 22.6s
236:	learn: 0.0921443	total: 7.02s	remaining: 22.6s
237:	learn: 0.0920306	total: 7.05s	remaining: 22.6s
238:	learn: 0.0919587	total: 7.09s	remaining: 22.6s
239:	learn: 0.0919062	total: 7.12s	remaining: 22.5s
240:	learn: 0.0918625	total: 7.14s	remaining: 22.5s
241:	learn: 0.0918354	total: 7.17s	remaining: 22.5s
242:	learn: 0.0917996	total: 7.21s	remaining: 22.5s
243:	learn: 0.0915448	total: 7.24s	remaining: 22.4s
244:	learn: 0.0913132	total: 7.27s	remaining: 22.4s
245:	learn: 0.0912971	total: 7.3s	remaining: 22.4s
246:	learn: 0.0912783	total: 7.33s	remaining: 22.4s
247:	learn: 0.0911887	total: 7.36s	remaining: 22.3s
248:	learn: 0.0911698	total: 7.39s	remaining: 22.3s
249:	learn: 0.0911439	total: 7.44s	remaining: 22.3s
250:	learn: 0.0911146	total: 7.49s	remaining: 22.3s
251:	learn: 0.0909698	total: 7.52s	remaining: 22.3s
252:	learn: 0.0909456	total: 7.55s	remaining: 22.3s
253:	learn: 0.0907545	total: 7.58s	remaining: 22.2s
254:	learn: 0.0907307	total: 7.61s	remaining: 22.2s
255:	learn: 0.0907064	total: 7.64s	remaining: 22.2s
256:	learn: 0.0906447	total: 7.67s	remaining: 22.2s
257:	learn: 0.0905835	total: 7.72s	remaining: 22.2s
258:	learn: 0.0905627	total: 7.75s	remaining: 22.2s
259:	learn: 0.0905452	total: 7.78s	remaining: 22.1s
260:	learn: 0.0903825	total: 7.8s	remaining: 22.1s
261:	learn: 0.0903591	total: 7.84s	remaining: 22.1s
262:	learn: 0.0903396	total: 7.87s	remaining: 22.1s
263:	learn: 0.0903169	total: 7.9s	remaining: 22s
264:	learn: 0.0900485	total: 7.94s	remaining: 22s
265:	learn: 0.0898569	total: 7.97s	remaining: 22s
266:	learn: 0.0898336	total: 8s	remaining: 22s
267:	learn: 0.0898104	total: 8.03s	remaining: 21.9s
268:	learn: 0.0895783	total: 8.06s	remaining: 21.9s
269:	learn: 0.0895161	total: 8.09s	remaining: 21.9s
270:	learn: 0.0894850	total: 8.12s	remaining: 21.8s
271:	learn: 0.0894485	total: 8.15s	remaining: 21.8s
272:	learn: 0.0894271	total: 8.18s	remaining: 21.8s
273:	learn: 0.0892150	total: 8.21s	remaining: 21.8s
274:	learn: 0.0891258	total: 8.24s	remaining: 21.7s
275:	learn: 0.0889559	total: 8.27s	remaining: 21.7s
276:	learn: 0.0889351	total: 8.3s	remaining: 21.7s
277:	learn: 0.0889034	total: 8.33s	remaining: 21.6s
278:	learn: 0.0888936	total: 8.36s	remaining: 21.6s
279:	learn: 0.0886899	total: 8.39s	remaining: 21.6s
280:	learn: 0.0886184	total: 8.42s	remaining: 21.6s
281:	learn: 0.0885169	total: 8.45s	remaining: 21.5s
282:	learn: 0.0883798	total: 8.48s	remaining: 21.5s
283:	learn: 0.0883567	total: 8.51s	remaining: 21.5s
284:	learn: 0.0881874	total: 8.54s	remaining: 21.4s
285:	learn: 0.0881724	total: 8.57s	remaining: 21.4s
286:	learn: 0.0881526	total: 8.6s	remaining: 21.4s
287:	learn: 0.0879547	total: 8.63s	remaining: 21.3s
288:	learn: 0.0879437	total: 8.66s	remaining: 21.3s
289:	learn: 0.0878889	total: 8.69s	remaining: 21.3s
290:	learn: 0.0878684	total: 8.72s	remaining: 21.3s
291:	learn: 0.0878460	total: 8.76s	remaining: 21.2s
292:	learn: 0.0876775	total: 8.79s	remaining: 21.2s
293:	learn: 0.0876590	total: 8.82s	remaining: 21.2s
294:	learn: 0.0875200	total: 8.85s	remaining: 21.2s
295:	learn: 0.0874979	total: 8.88s	remaining: 21.1s
296:	learn: 0.0874324	total: 8.91s	remaining: 21.1s
297:	learn: 0.0873056	total: 8.94s	remaining: 21.1s
298:	learn: 0.0872620	total: 8.98s	remaining: 21s
299:	learn: 0.0871260	total: 9.01s	remaining: 21s
300:	learn: 0.0871127	total: 9.04s	remaining: 21s
301:	learn: 0.0870271	total: 9.07s	remaining: 21s
302:	learn: 0.0867878	total: 9.1s	remaining: 20.9s
303:	learn: 0.0866913	total: 9.13s	remaining: 20.9s
304:	learn: 0.0866258	total: 9.16s	remaining: 20.9s
305:	learn: 0.0865473	total: 9.19s	remaining: 20.8s
306:	learn: 0.0863877	total: 9.22s	remaining: 20.8s
307:	learn: 0.0861870	total: 9.25s	remaining: 20.8s
308:	learn: 0.0861175	total: 9.29s	remaining: 20.8s
309:	learn: 0.0860783	total: 9.32s	remaining: 20.7s
310:	learn: 0.0860460	total: 9.35s	remaining: 20.7s
311:	learn: 0.0859277	total: 9.38s	remaining: 20.7s
312:	learn: 0.0858209	total: 9.4s	remaining: 20.6s
313:	learn: 0.0857117	total: 9.44s	remaining: 20.6s
314:	learn: 0.0856932	total: 9.47s	remaining: 20.6s
315:	learn: 0.0856327	total: 9.5s	remaining: 20.6s
316:	learn: 0.0855958	total: 9.53s	remaining: 20.5s
317:	learn: 0.0855888	total: 9.56s	remaining: 20.5s
318:	learn: 0.0855717	total: 9.59s	remaining: 20.5s
319:	learn: 0.0854456	total: 9.63s	remaining: 20.5s
320:	learn: 0.0852928	total: 9.67s	remaining: 20.5s
321:	learn: 0.0852738	total: 9.7s	remaining: 20.4s
322:	learn: 0.0851932	total: 9.73s	remaining: 20.4s
323:	learn: 0.0851674	total: 9.77s	remaining: 20.4s
324:	learn: 0.0851127	total: 9.79s	remaining: 20.3s
325:	learn: 0.0849561	total: 9.82s	remaining: 20.3s
326:	learn: 0.0849258	total: 9.87s	remaining: 20.3s
327:	learn: 0.0847378	total: 9.9s	remaining: 20.3s
328:	learn: 0.0845694	total: 9.93s	remaining: 20.3s
329:	learn: 0.0845531	total: 9.96s	remaining: 20.2s
330:	learn: 0.0844396	total: 9.99s	remaining: 20.2s
331:	learn: 0.0842728	total: 10s	remaining: 20.2s
332:	learn: 0.0841975	total: 10.1s	remaining: 20.1s
333:	learn: 0.0841212	total: 10.1s	remaining: 20.1s
334:	learn: 0.0840186	total: 10.1s	remaining: 20.1s
335:	learn: 0.0838786	total: 10.1s	remaining: 20.1s
336:	learn: 0.0838279	total: 10.2s	remaining: 20s
337:	learn: 0.0838175	total: 10.2s	remaining: 20s
338:	learn: 0.0837003	total: 10.2s	remaining: 20s
339:	learn: 0.0836374	total: 10.3s	remaining: 19.9s
340:	learn: 0.0835014	total: 10.3s	remaining: 19.9s
341:	learn: 0.0833821	total: 10.3s	remaining: 19.9s
342:	learn: 0.0832050	total: 10.4s	remaining: 19.8s
343:	learn: 0.0830988	total: 10.4s	remaining: 19.8s
344:	learn: 0.0829884	total: 10.4s	remaining: 19.8s
345:	learn: 0.0828376	total: 10.4s	remaining: 19.8s
346:	learn: 0.0828238	total: 10.5s	remaining: 19.7s
347:	learn: 0.0827765	total: 10.5s	remaining: 19.7s
348:	learn: 0.0826908	total: 10.5s	remaining: 19.7s
349:	learn: 0.0826168	total: 10.6s	remaining: 19.6s
350:	learn: 0.0825999	total: 10.6s	remaining: 19.6s
351:	learn: 0.0825258	total: 10.6s	remaining: 19.6s
352:	learn: 0.0823568	total: 10.7s	remaining: 19.5s
353:	learn: 0.0822908	total: 10.7s	remaining: 19.5s
354:	learn: 0.0821268	total: 10.7s	remaining: 19.5s
355:	learn: 0.0820240	total: 10.8s	remaining: 19.4s
356:	learn: 0.0820084	total: 10.8s	remaining: 19.4s
357:	learn: 0.0818545	total: 10.8s	remaining: 19.4s
358:	learn: 0.0817075	total: 10.8s	remaining: 19.4s
359:	learn: 0.0816273	total: 10.9s	remaining: 19.3s
360:	learn: 0.0816062	total: 10.9s	remaining: 19.3s
361:	learn: 0.0814920	total: 10.9s	remaining: 19.3s
362:	learn: 0.0813689	total: 11s	remaining: 19.2s
363:	learn: 0.0812488	total: 11s	remaining: 19.2s
364:	learn: 0.0811031	total: 11s	remaining: 19.2s
365:	learn: 0.0810471	total: 11s	remaining: 19.1s
366:	learn: 0.0808765	total: 11.1s	remaining: 19.1s
367:	learn: 0.0807874	total: 11.1s	remaining: 19.1s
368:	learn: 0.0806305	total: 11.1s	remaining: 19s
369:	learn: 0.0805667	total: 11.2s	remaining: 19s
370:	learn: 0.0805018	total: 11.2s	remaining: 19s
371:	learn: 0.0804550	total: 11.2s	remaining: 18.9s
372:	learn: 0.0803208	total: 11.3s	remaining: 18.9s
373:	learn: 0.0803088	total: 11.3s	remaining: 18.9s
374:	learn: 0.0801485	total: 11.3s	remaining: 18.9s
375:	learn: 0.0801312	total: 11.3s	remaining: 18.8s
376:	learn: 0.0799905	total: 11.4s	remaining: 18.8s
377:	learn: 0.0799096	total: 11.4s	remaining: 18.8s
378:	learn: 0.0798682	total: 11.4s	remaining: 18.8s
379:	learn: 0.0796929	total: 11.5s	remaining: 18.7s
380:	learn: 0.0796798	total: 11.5s	remaining: 18.7s
381:	learn: 0.0795632	total: 11.5s	remaining: 18.7s
382:	learn: 0.0795511	total: 11.6s	remaining: 18.6s
383:	learn: 0.0793918	total: 11.6s	remaining: 18.6s
384:	learn: 0.0793183	total: 11.6s	remaining: 18.6s

CV folds:  42%|████▏     | 21/50 [11:05<15:17, 31.65s/fold]

997:	learn: 0.0460134	total: 30.9s	remaining: 61.9ms
998:	learn: 0.0459599	total: 30.9s	remaining: 31ms
999:	learn: 0.0459149	total: 31s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3908307	total: 24.7ms	remaining: 24.7s
1:	learn: 0.3800550	total: 55ms	remaining: 27.4s
2:	learn: 0.3696263	total: 85.2ms	remaining: 28.3s
3:	learn: 0.3592895	total: 118ms	remaining: 29.3s
4:	learn: 0.3500051	total: 148ms	remaining: 29.4s
5:	learn: 0.3407511	total: 176ms	remaining: 29.2s
6:	learn: 0.3314111	total: 205ms	remaining: 29s
7:	learn: 0.3227278	total: 235ms	remaining: 29.1s
8:	learn: 0.3138459	total: 265ms	remaining: 29.2s
9:	learn: 0.3058539	total: 296ms	remaining: 29.3s
10:	learn: 0.2986830	total: 327ms	remaining: 29.4s
11:	learn: 0.2909852	total: 356ms	remaining: 29.3s
12:	learn: 0.2839423	total: 388ms	remaining: 29.5s
13:	learn: 0.2767197	total: 418ms	remaining: 29.4s
14:	learn: 0.2698058	total: 473ms	remaining: 31.1s
15:	learn: 0.2639885	total: 509ms	remaining: 31.3s
16:	learn: 0.2583171	total: 549ms	remaining: 31.7s
17:	learn: 0.2526806	total: 596ms	remaining: 32.5s
18:	learn: 0.2469984	total: 624ms	remaining: 32.2s
19:	learn: 0.2420075	total: 649ms	remaining: 31.8s
20:	learn: 0.2368322	total: 680ms	remaining: 31.7s
21:	learn: 0.2318736	total: 711ms	remaining: 31.6s
22:	learn: 0.2268463	total: 741ms	remaining: 31.5s
23:	learn: 0.2222630	total: 773ms	remaining: 31.4s
24:	learn: 0.2184854	total: 804ms	remaining: 31.3s
25:	learn: 0.2144578	total: 834ms	remaining: 31.3s
26:	learn: 0.2103896	total: 864ms	remaining: 31.1s
27:	learn: 0.2068318	total: 896ms	remaining: 31.1s
28:	learn: 0.2030441	total: 927ms	remaining: 31s
29:	learn: 0.1994397	total: 958ms	remaining: 31s
30:	learn: 0.1958291	total: 989ms	remaining: 30.9s
31:	learn: 0.1925196	total: 1.02s	remaining: 30.9s
32:	learn: 0.1892673	total: 1.05s	remaining: 30.7s
33:	learn: 0.1859537	total: 1.08s	remaining: 30.7s
34:	learn: 0.1827242	total: 1.11s	remaining: 30.6s
35:	learn: 0.1798738	total: 1.14s	remaining: 30.5s
36:	learn: 0.1772673	total: 1.17s	remaining: 30.5s
37:	learn: 0.1747757	total: 1.2s	remaining: 30.4s
38:	learn: 0.1721736	total: 1.24s	remaining: 30.5s
39:	learn: 0.1698555	total: 1.27s	remaining: 30.5s
40:	learn: 0.1675270	total: 1.3s	remaining: 30.4s
41:	learn: 0.1649065	total: 1.33s	remaining: 30.3s
42:	learn: 0.1627016	total: 1.36s	remaining: 30.3s
43:	learn: 0.1608323	total: 1.39s	remaining: 30.1s
44:	learn: 0.1588533	total: 1.42s	remaining: 30.1s
45:	learn: 0.1569809	total: 1.45s	remaining: 30.1s
46:	learn: 0.1551325	total: 1.48s	remaining: 30s
47:	learn: 0.1534135	total: 1.51s	remaining: 29.9s
48:	learn: 0.1515844	total: 1.54s	remaining: 29.9s
49:	learn: 0.1504034	total: 1.57s	remaining: 29.8s
50:	learn: 0.1486719	total: 1.6s	remaining: 29.8s
51:	learn: 0.1469987	total: 1.63s	remaining: 29.7s
52:	learn: 0.1454526	total: 1.66s	remaining: 29.7s
53:	learn: 0.1438108	total: 1.7s	remaining: 29.7s
54:	learn: 0.1424246	total: 1.73s	remaining: 29.7s
55:	learn: 0.1411999	total: 1.76s	remaining: 29.7s
56:	learn: 0.1399509	total: 1.8s	remaining: 29.8s
57:	learn: 0.1386686	total: 1.83s	remaining: 29.7s
58:	learn: 0.1374947	total: 1.86s	remaining: 29.7s
59:	learn: 0.1364410	total: 1.89s	remaining: 29.6s
60:	learn: 0.1353366	total: 1.92s	remaining: 29.5s
61:	learn: 0.1342116	total: 1.95s	remaining: 29.4s
62:	learn: 0.1328860	total: 1.98s	remaining: 29.4s
63:	learn: 0.1318846	total: 2.01s	remaining: 29.4s
64:	learn: 0.1308439	total: 2.03s	remaining: 29.3s
65:	learn: 0.1298999	total: 2.06s	remaining: 29.2s
66:	learn: 0.1291477	total: 2.09s	remaining: 29.2s
67:	learn: 0.1282437	total: 2.13s	remaining: 29.2s
68:	learn: 0.1274176	total: 2.16s	remaining: 29.2s
69:	learn: 0.1265751	total: 2.19s	remaining: 29.2s
70:	learn: 0.1258792	total: 2.23s	remaining: 29.2s
71:	learn: 0.1250236	total: 2.26s	remaining: 29.1s
72:	learn: 0.1244585	total: 2.28s	remaining: 29s
73:	learn: 0.1235082	total: 2.31s	remaining: 28.9s
74:	learn: 0.1228812	total: 2.34s	remaining: 28.9s
75:	learn: 0.1221687	total: 2.38s	remaining: 28.9s
76:	learn: 0.1215406	total: 2.41s	remaining: 28.9s
77:	learn: 0.1207594	total: 2.44s	remaining: 28.8s
78:	learn: 0.1202431	total: 2.47s	remaining: 28.8s
79:	learn: 0.1197732	total: 2.5s	remaining: 28.7s
80:	learn: 0.1192284	total: 2.53s	remaining: 28.7s
81:	learn: 0.1185245	total: 2.56s	remaining: 28.7s
82:	learn: 0.1181297	total: 2.59s	remaining: 28.6s
83:	learn: 0.1175723	total: 2.62s	remaining: 28.6s
84:	learn: 0.1170380	total: 2.65s	remaining: 28.5s
85:	learn: 0.1165240	total: 2.68s	remaining: 28.5s
86:	learn: 0.1160855	total: 2.71s	remaining: 28.5s
87:	learn: 0.1155902	total: 2.74s	remaining: 28.4s
88:	learn: 0.1150992	total: 2.77s	remaining: 28.4s
89:	learn: 0.1144029	total: 2.8s	remaining: 28.4s
90:	learn: 0.1138788	total: 2.83s	remaining: 28.3s
91:	learn: 0.1134219	total: 2.87s	remaining: 28.3s
92:	learn: 0.1129315	total: 2.9s	remaining: 28.3s
93:	learn: 0.1126811	total: 2.93s	remaining: 28.3s
94:	learn: 0.1122610	total: 2.96s	remaining: 28.2s
95:	learn: 0.1118358	total: 2.99s	remaining: 28.2s
96:	learn: 0.1112150	total: 3.02s	remaining: 28.1s
97:	learn: 0.1108767	total: 3.05s	remaining: 28.1s
98:	learn: 0.1104432	total: 3.08s	remaining: 28.1s
99:	learn: 0.1100916	total: 3.11s	remaining: 28s
100:	learn: 0.1096611	total: 3.15s	remaining: 28s
101:	learn: 0.1093538	total: 3.17s	remaining: 28s
102:	learn: 0.1090063	total: 3.2s	remaining: 27.9s
103:	learn: 0.1086849	total: 3.23s	remaining: 27.9s
104:	learn: 0.1084259	total: 3.26s	remaining: 27.8s
105:	learn: 0.1080321	total: 3.29s	remaining: 27.8s
106:	learn: 0.1075729	total: 3.32s	remaining: 27.7s
107:	learn: 0.1072408	total: 3.37s	remaining: 27.8s
108:	learn: 0.1067558	total: 3.4s	remaining: 27.8s
109:	learn: 0.1063954	total: 3.43s	remaining: 27.7s
110:	learn: 0.1060380	total: 3.46s	remaining: 27.7s
111:	learn: 0.1057141	total: 3.49s	remaining: 27.7s
112:	learn: 0.1055112	total: 3.52s	remaining: 27.6s
113:	learn: 0.1052112	total: 3.55s	remaining: 27.6s
114:	learn: 0.1048096	total: 3.58s	remaining: 27.6s
115:	learn: 0.1045981	total: 3.61s	remaining: 27.5s
116:	learn: 0.1041810	total: 3.64s	remaining: 27.5s
117:	learn: 0.1038100	total: 3.67s	remaining: 27.5s
118:	learn: 0.1033172	total: 3.71s	remaining: 27.4s
119:	learn: 0.1029795	total: 3.74s	remaining: 27.4s
120:	learn: 0.1027586	total: 3.77s	remaining: 27.4s
121:	learn: 0.1024454	total: 3.8s	remaining: 27.3s
122:	learn: 0.1021754	total: 3.83s	remaining: 27.3s
123:	learn: 0.1018896	total: 3.86s	remaining: 27.3s
124:	learn: 0.1016506	total: 3.89s	remaining: 27.2s
125:	learn: 0.1013697	total: 3.92s	remaining: 27.2s
126:	learn: 0.1010195	total: 3.97s	remaining: 27.3s
127:	learn: 0.1007824	total: 4s	remaining: 27.3s
128:	learn: 0.1004684	total: 4.03s	remaining: 27.2s
129:	learn: 0.1003690	total: 4.06s	remaining: 27.2s
130:	learn: 0.1001461	total: 4.1s	remaining: 27.2s
131:	learn: 0.0998874	total: 4.12s	remaining: 27.1s
132:	learn: 0.0996843	total: 4.16s	remaining: 27.1s
133:	learn: 0.0993843	total: 4.19s	remaining: 27.1s
134:	learn: 0.0991194	total: 4.22s	remaining: 27s
135:	learn: 0.0988697	total: 4.26s	remaining: 27.1s
136:	learn: 0.0986088	total: 4.29s	remaining: 27s
137:	learn: 0.0984894	total: 4.32s	remaining: 27s
138:	learn: 0.0983756	total: 4.35s	remaining: 26.9s
139:	learn: 0.0981278	total: 4.38s	remaining: 26.9s
140:	learn: 0.0978724	total: 4.41s	remaining: 26.9s
141:	learn: 0.0978171	total: 4.43s	remaining: 26.8s
142:	learn: 0.0975619	total: 4.46s	remaining: 26.7s
143:	learn: 0.0975608	total: 4.47s	remaining: 26.5s
144:	learn: 0.0973818	total: 4.5s	remaining: 26.5s
145:	learn: 0.0972096	total: 4.53s	remaining: 26.5s
146:	learn: 0.0970724	total: 4.56s	remaining: 26.5s
147:	learn: 0.0969314	total: 4.59s	remaining: 26.4s
148:	learn: 0.0968325	total: 4.62s	remaining: 26.4s
149:	learn: 0.0967374	total: 4.65s	remaining: 26.4s
150:	learn: 0.0965345	total: 4.68s	remaining: 26.3s
151:	learn: 0.0963576	total: 4.71s	remaining: 26.3s
152:	learn: 0.0961401	total: 4.74s	remaining: 26.3s
153:	learn: 0.0957885	total: 4.78s	remaining: 26.2s
154:	learn: 0.0955986	total: 4.81s	remaining: 26.2s
155:	learn: 0.0954572	total: 4.84s	remaining: 26.2s
156:	learn: 0.0953171	total: 4.87s	remaining: 26.2s
157:	learn: 0.0951527	total: 4.9s	remaining: 26.1s
158:	learn: 0.0949980	total: 4.93s	remaining: 26.1s
159:	learn: 0.0947787	total: 4.96s	remaining: 26s
160:	learn: 0.0946225	total: 4.99s	remaining: 26s
161:	learn: 0.0944010	total: 5.03s	remaining: 26s
162:	learn: 0.0942324	total: 5.06s	remaining: 26s
163:	learn: 0.0940427	total: 5.09s	remaining: 26s
164:	learn: 0.0938414	total: 5.12s	remaining: 25.9s
165:	learn: 0.0937320	total: 5.15s	remaining: 25.9s
166:	learn: 0.0935672	total: 5.18s	remaining: 25.8s
167:	learn: 0.0933014	total: 5.21s	remaining: 25.8s
168:	learn: 0.0930436	total: 5.24s	remaining: 25.8s
169:	learn: 0.0928822	total: 5.27s	remaining: 25.7s
170:	learn: 0.0928288	total: 5.3s	remaining: 25.7s
171:	learn: 0.0926779	total: 5.33s	remaining: 25.6s
172:	learn: 0.0925036	total: 5.36s	remaining: 25.6s
173:	learn: 0.0923926	total: 5.39s	remaining: 25.6s
174:	learn: 0.0922773	total: 5.42s	remaining: 25.5s
175:	learn: 0.0921870	total: 5.45s	remaining: 25.5s
176:	learn: 0.0920010	total: 5.48s	remaining: 25.5s
177:	learn: 0.0919360	total: 5.51s	remaining: 25.4s
178:	learn: 0.0918235	total: 5.54s	remaining: 25.4s
179:	learn: 0.0915938	total: 5.57s	remaining: 25.4s
180:	learn: 0.0914214	total: 5.6s	remaining: 25.3s
181:	learn: 0.0911885	total: 5.63s	remaining: 25.3s
182:	learn: 0.0910357	total: 5.66s	remaining: 25.3s
183:	learn: 0.0909235	total: 5.7s	remaining: 25.3s
184:	learn: 0.0906822	total: 5.73s	remaining: 25.2s
185:	learn: 0.0905303	total: 5.76s	remaining: 25.2s
186:	learn: 0.0904207	total: 5.79s	remaining: 25.2s
187:	learn: 0.0903327	total: 5.82s	remaining: 25.1s
188:	learn: 0.0900419	total: 5.85s	remaining: 25.1s
189:	learn: 0.0898793	total: 5.88s	remaining: 25.1s
190:	learn: 0.0897571	total: 5.91s	remaining: 25s
191:	learn: 0.0897292	total: 5.94s	remaining: 25s
192:	learn: 0.0896367	total: 5.97s	remaining: 25s
193:	learn: 0.0896200	total: 6s	remaining: 24.9s
194:	learn: 0.0895512	total: 6.04s	remaining: 24.9s
195:	learn: 0.0895011	total: 6.07s	remaining: 24.9s
196:	learn: 0.0892779	total: 6.1s	remaining: 24.9s
197:	learn: 0.0891013	total: 6.13s	remaining: 24.8s
198:	learn: 0.0889147	total: 6.16s	remaining: 24.8s
199:	learn: 0.0887426	total: 6.19s	remaining: 24.8s
200:	learn: 0.0884860	total: 6.22s	remaining: 24.7s
201:	learn: 0.0883779	total: 6.25s	remaining: 24.7s
202:	learn: 0.0883408	total: 6.28s	remaining: 24.6s
203:	learn: 0.0882381	total: 6.31s	remaining: 24.6s
204:	learn: 0.0881420	total: 6.34s	remaining: 24.6s
205:	learn: 0.0880859	total: 6.37s	remaining: 24.5s
206:	learn: 0.0879513	total: 6.41s	remaining: 24.6s
207:	learn: 0.0878933	total: 6.44s	remaining: 24.5s
208:	learn: 0.0878766	total: 6.47s	remaining: 24.5s
209:	learn: 0.0876927	total: 6.5s	remaining: 24.4s
210:	learn: 0.0876372	total: 6.53s	remaining: 24.4s
211:	learn: 0.0875186	total: 6.56s	remaining: 24.4s
212:	learn: 0.0872738	total: 6.6s	remaining: 24.4s
213:	learn: 0.0872318	total: 6.63s	remaining: 24.3s
214:	learn: 0.0869905	total: 6.66s	remaining: 24.3s
215:	learn: 0.0868473	total: 6.69s	remaining: 24.3s
216:	learn: 0.0867871	total: 6.72s	remaining: 24.3s
217:	learn: 0.0867100	total: 6.75s	remaining: 24.2s
218:	learn: 0.0866374	total: 6.78s	remaining: 24.2s
219:	learn: 0.0866010	total: 6.81s	remaining: 24.2s
220:	learn: 0.0864934	total: 6.86s	remaining: 24.2s
221:	learn: 0.0863614	total: 6.89s	remaining: 24.2s
222:	learn: 0.0862050	total: 6.92s	remaining: 24.1s
223:	learn: 0.0861647	total: 6.95s	remaining: 24.1s
224:	learn: 0.0860298	total: 6.98s	remaining: 24s
225:	learn: 0.0858748	total: 7.01s	remaining: 24s
226:	learn: 0.0856965	total: 7.05s	remaining: 24s
227:	learn: 0.0855911	total: 7.07s	remaining: 24s
228:	learn: 0.0853997	total: 7.1s	remaining: 23.9s
229:	learn: 0.0852360	total: 7.13s	remaining: 23.9s
230:	learn: 0.0851165	total: 7.17s	remaining: 23.9s
231:	learn: 0.0850075	total: 7.2s	remaining: 23.8s
232:	learn: 0.0848789	total: 7.23s	remaining: 23.8s
233:	learn: 0.0847976	total: 7.26s	remaining: 23.8s
234:	learn: 0.0847385	total: 7.28s	remaining: 23.7s
235:	learn: 0.0846878	total: 7.31s	remaining: 23.7s
236:	learn: 0.0846047	total: 7.34s	remaining: 23.6s
237:	learn: 0.0844656	total: 7.37s	remaining: 23.6s
238:	learn: 0.0843217	total: 7.4s	remaining: 23.6s
239:	learn: 0.0842526	total: 7.43s	remaining: 23.5s
240:	learn: 0.0842048	total: 7.46s	remaining: 23.5s
241:	learn: 0.0841821	total: 7.49s	remaining: 23.5s
242:	learn: 0.0840256	total: 7.52s	remaining: 23.4s
243:	learn: 0.0840008	total: 7.55s	remaining: 23.4s
244:	learn: 0.0839660	total: 7.58s	remaining: 23.4s
245:	learn: 0.0839461	total: 7.61s	remaining: 23.3s
246:	learn: 0.0838015	total: 7.64s	remaining: 23.3s
247:	learn: 0.0836860	total: 7.67s	remaining: 23.2s
248:	learn: 0.0836424	total: 7.72s	remaining: 23.3s
249:	learn: 0.0835539	total: 7.75s	remaining: 23.3s
250:	learn: 0.0834471	total: 7.78s	remaining: 23.2s
251:	learn: 0.0832791	total: 7.81s	remaining: 23.2s
252:	learn: 0.0832377	total: 7.84s	remaining: 23.2s
253:	learn: 0.0831536	total: 7.87s	remaining: 23.1s
254:	learn: 0.0831303	total: 7.91s	remaining: 23.1s
255:	learn: 0.0830874	total: 7.93s	remaining: 23.1s
256:	learn: 0.0830617	total: 7.97s	remaining: 23s
257:	learn: 0.0828756	total: 8s	remaining: 23s
258:	learn: 0.0828471	total: 8.03s	remaining: 23s
259:	learn: 0.0827802	total: 8.05s	remaining: 22.9s
260:	learn: 0.0826920	total: 8.08s	remaining: 22.9s
261:	learn: 0.0825674	total: 8.12s	remaining: 22.9s
262:	learn: 0.0824118	total: 8.14s	remaining: 22.8s
263:	learn: 0.0823722	total: 8.17s	remaining: 22.8s
264:	learn: 0.0823307	total: 8.2s	remaining: 22.8s
265:	learn: 0.0823124	total: 8.23s	remaining: 22.7s
266:	learn: 0.0819899	total: 8.26s	remaining: 22.7s
267:	learn: 0.0819716	total: 8.29s	remaining: 22.7s
268:	learn: 0.0819519	total: 8.33s	remaining: 22.6s
269:	learn: 0.0818525	total: 8.36s	remaining: 22.6s
270:	learn: 0.0817160	total: 8.39s	remaining: 22.6s
271:	learn: 0.0815352	total: 8.42s	remaining: 22.5s
272:	learn: 0.0813882	total: 8.45s	remaining: 22.5s
273:	learn: 0.0812688	total: 8.49s	remaining: 22.5s
274:	learn: 0.0811417	total: 8.52s	remaining: 22.5s
275:	learn: 0.0810159	total: 8.56s	remaining: 22.4s
276:	learn: 0.0808907	total: 8.59s	remaining: 22.4s
277:	learn: 0.0807412	total: 8.62s	remaining: 22.4s
278:	learn: 0.0805730	total: 8.66s	remaining: 22.4s
279:	learn: 0.0804974	total: 8.69s	remaining: 22.4s
280:	learn: 0.0803986	total: 8.72s	remaining: 22.3s
281:	learn: 0.0802802	total: 8.76s	remaining: 22.3s
282:	learn: 0.0801616	total: 8.79s	remaining: 22.3s
283:	learn: 0.0800115	total: 8.82s	remaining: 22.2s
284:	learn: 0.0799952	total: 8.85s	remaining: 22.2s
285:	learn: 0.0799606	total: 8.88s	remaining: 22.2s
286:	learn: 0.0799405	total: 8.91s	remaining: 22.1s
287:	learn: 0.0799223	total: 8.94s	remaining: 22.1s
288:	learn: 0.0798074	total: 8.98s	remaining: 22.1s
289:	learn: 0.0797337	total: 9.01s	remaining: 22.1s
290:	learn: 0.0797184	total: 9.04s	remaining: 22s
291:	learn: 0.0796999	total: 9.07s	remaining: 22s
292:	learn: 0.0796316	total: 9.1s	remaining: 22s
293:	learn: 0.0795043	total: 9.13s	remaining: 21.9s
294:	learn: 0.0793455	total: 9.16s	remaining: 21.9s
295:	learn: 0.0792387	total: 9.19s	remaining: 21.9s
296:	learn: 0.0791984	total: 9.22s	remaining: 21.8s
297:	learn: 0.0790407	total: 9.26s	remaining: 21.8s
298:	learn: 0.0790184	total: 9.29s	remaining: 21.8s
299:	learn: 0.0788725	total: 9.32s	remaining: 21.7s
300:	learn: 0.0788635	total: 9.35s	remaining: 21.7s
301:	learn: 0.0787531	total: 9.38s	remaining: 21.7s
302:	learn: 0.0786358	total: 9.4s	remaining: 21.6s
303:	learn: 0.0785046	total: 9.44s	remaining: 21.6s
304:	learn: 0.0783220	total: 9.47s	remaining: 21.6s
305:	learn: 0.0782192	total: 9.5s	remaining: 21.5s
306:	learn: 0.0781074	total: 9.53s	remaining: 21.5s
307:	learn: 0.0778801	total: 9.56s	remaining: 21.5s
308:	learn: 0.0777182	total: 9.59s	remaining: 21.4s
309:	learn: 0.0777057	total: 9.61s	remaining: 21.4s
310:	learn: 0.0776138	total: 9.64s	remaining: 21.4s
311:	learn: 0.0775170	total: 9.67s	remaining: 21.3s
312:	learn: 0.0774791	total: 9.71s	remaining: 21.3s
313:	learn: 0.0774419	total: 9.74s	remaining: 21.3s
314:	learn: 0.0773862	total: 9.77s	remaining: 21.2s
315:	learn: 0.0772775	total: 9.8s	remaining: 21.2s
316:	learn: 0.0771834	total: 9.83s	remaining: 21.2s
317:	learn: 0.0771417	total: 9.86s	remaining: 21.2s
318:	learn: 0.0770828	total: 9.89s	remaining: 21.1s
319:	learn: 0.0770485	total: 9.93s	remaining: 21.1s
320:	learn: 0.0769291	total: 9.95s	remaining: 21.1s
321:	learn: 0.0769122	total: 9.99s	remaining: 21s
322:	learn: 0.0767457	total: 10s	remaining: 21s
323:	learn: 0.0766682	total: 10s	remaining: 21s
324:	learn: 0.0766218	total: 10.1s	remaining: 20.9s
325:	learn: 0.0765710	total: 10.1s	remaining: 20.9s
326:	learn: 0.0765428	total: 10.1s	remaining: 20.9s
327:	learn: 0.0764655	total: 10.2s	remaining: 20.8s
328:	learn: 0.0764184	total: 10.2s	remaining: 20.8s
329:	learn: 0.0763910	total: 10.2s	remaining: 20.8s
330:	learn: 0.0763767	total: 10.3s	remaining: 20.7s
331:	learn: 0.0763620	total: 10.3s	remaining: 20.7s
332:	learn: 0.0763453	total: 10.3s	remaining: 20.7s
333:	learn: 0.0762310	total: 10.4s	remaining: 20.6s
334:	learn: 0.0762234	total: 10.4s	remaining: 20.6s
335:	learn: 0.0762145	total: 10.4s	remaining: 20.6s
336:	learn: 0.0761115	total: 10.4s	remaining: 20.6s
337:	learn: 0.0760286	total: 10.5s	remaining: 20.5s
338:	learn: 0.0758489	total: 10.5s	remaining: 20.5s
339:	learn: 0.0757745	total: 10.5s	remaining: 20.5s
340:	learn: 0.0757213	total: 10.6s	remaining: 20.4s
341:	learn: 0.0756767	total: 10.6s	remaining: 20.4s
342:	learn: 0.0755876	total: 10.6s	remaining: 20.4s
343:	learn: 0.0754135	total: 10.7s	remaining: 20.3s
344:	learn: 0.0753977	total: 10.7s	remaining: 20.3s
345:	learn: 0.0753581	total: 10.7s	remaining: 20.3s
346:	learn: 0.0752177	total: 10.8s	remaining: 20.3s
347:	learn: 0.0751893	total: 10.8s	remaining: 20.2s
348:	learn: 0.0751004	total: 10.8s	remaining: 20.2s
349:	learn: 0.0749572	total: 10.9s	remaining: 20.2s
350:	learn: 0.0749279	total: 10.9s	remaining: 20.1s
351:	learn: 0.0748255	total: 10.9s	remaining: 20.1s
352:	learn: 0.0747439	total: 10.9s	remaining: 20.1s
353:	learn: 0.0746185	total: 11s	remaining: 20s
354:	learn: 0.0745520	total: 11s	remaining: 20s
355:	learn: 0.0745015	total: 11s	remaining: 20s
356:	learn: 0.0744134	total: 11.1s	remaining: 19.9s
357:	learn: 0.0743277	total: 11.1s	remaining: 19.9s
358:	learn: 0.0743207	total: 11.1s	remaining: 19.9s
359:	learn: 0.0742025	total: 11.2s	remaining: 19.8s
360:	learn: 0.0741265	total: 11.2s	remaining: 19.8s
361:	learn: 0.0739769	total: 11.2s	remaining: 19.8s
362:	learn: 0.0739670	total: 11.3s	remaining: 19.7s
363:	learn: 0.0738812	total: 11.3s	remaining: 19.7s
364:	learn: 0.0738335	total: 11.3s	remaining: 19.7s
365:	learn: 0.0737226	total: 11.3s	remaining: 19.6s
366:	learn: 0.0736718	total: 11.4s	remaining: 19.6s
367:	learn: 0.0735682	total: 11.4s	remaining: 19.6s
368:	learn: 0.0734814	total: 11.4s	remaining: 19.6s
369:	learn: 0.0734435	total: 11.5s	remaining: 19.5s
370:	learn: 0.0734371	total: 11.5s	remaining: 19.5s
371:	learn: 0.0732715	total: 11.5s	remaining: 19.5s
372:	learn: 0.0731334	total: 11.6s	remaining: 19.4s
373:	learn: 0.0730232	total: 11.6s	remaining: 19.4s
374:	learn: 0.0729961	total: 11.6s	remaining: 19.4s
375:	learn: 0.0729321	total: 11.7s	remaining: 19.3s
376:	learn: 0.0729114	total: 11.7s	remaining: 19.3s
377:	learn: 0.0728260	total: 11.7s	remaining: 19.3s
378:	learn: 0.0727616	total: 11.7s	remaining: 19.2s
379:	learn: 0.0727363	total: 11.8s	remaining: 19.2s
380:	learn: 0.0726077	total: 11.8s	remaining: 19.2s
381:	learn: 0.0725304	total: 11.8s	remaining: 19.2s
382:	learn: 0.0724272	total: 11.9s	remaining: 19.2s
383:	learn: 0.0724180	total: 11.9s	remaining: 19.1s
384:	learn: 0.0724093	total: 12s	remaining: 19.1s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'MiscFeature': 1 unseen categories converted to Unseen on transform.

CV folds:  44%|████▍     | 22/50 [11:36<14:48, 31.73s/fold]

998:	learn: 0.0427292	total: 31.4s	remaining: 31.4ms
999:	learn: 0.0426791	total: 31.4s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3872060	total: 29.1ms	remaining: 29s
1:	learn: 0.3768215	total: 58.3ms	remaining: 29.1s
2:	learn: 0.3670489	total: 86.4ms	remaining: 28.7s
3:	learn: 0.3579721	total: 118ms	remaining: 29.4s
4:	learn: 0.3484539	total: 148ms	remaining: 29.5s
5:	learn: 0.3395826	total: 180ms	remaining: 29.8s
6:	learn: 0.3308723	total: 210ms	remaining: 29.8s
7:	learn: 0.3227867	total: 247ms	remaining: 30.6s
8:	learn: 0.3153398	total: 277ms	remaining: 30.5s
9:	learn: 0.3075905	total: 329ms	remaining: 32.6s
10:	learn: 0.2999378	total: 362ms	remaining: 32.6s
11:	learn: 0.2917618	total: 394ms	remaining: 32.4s
12:	learn: 0.2845567	total: 422ms	remaining: 32s
13:	learn: 0.2777716	total: 453ms	remaining: 31.9s
14:	learn: 0.2718865	total: 484ms	remaining: 31.8s
15:	learn: 0.2657021	total: 514ms	remaining: 31.6s
16:	learn: 0.2594492	total: 545ms	remaining: 31.5s
17:	learn: 0.2533382	total: 579ms	remaining: 31.6s
18:	learn: 0.2479525	total: 618ms	remaining: 31.9s
19:	learn: 0.2425709	total: 648ms	remaining: 31.7s
20:	learn: 0.2381273	total: 678ms	remaining: 31.6s
21:	learn: 0.2334497	total: 705ms	remaining: 31.3s
22:	learn: 0.2290289	total: 734ms	remaining: 31.2s
23:	learn: 0.2246902	total: 762ms	remaining: 31s
24:	learn: 0.2202806	total: 788ms	remaining: 30.7s
25:	learn: 0.2160996	total: 814ms	remaining: 30.5s
26:	learn: 0.2123990	total: 841ms	remaining: 30.3s
27:	learn: 0.2086043	total: 869ms	remaining: 30.2s
28:	learn: 0.2047821	total: 902ms	remaining: 30.2s
29:	learn: 0.2011003	total: 930ms	remaining: 30.1s
30:	learn: 0.1976342	total: 957ms	remaining: 29.9s
31:	learn: 0.1950850	total: 980ms	remaining: 29.7s
32:	learn: 0.1919982	total: 1.01s	remaining: 29.6s
33:	learn: 0.1889962	total: 1.04s	remaining: 29.5s
34:	learn: 0.1862755	total: 1.06s	remaining: 29.4s
35:	learn: 0.1833702	total: 1.1s	remaining: 29.4s
36:	learn: 0.1805993	total: 1.13s	remaining: 29.4s
37:	learn: 0.1781263	total: 1.16s	remaining: 29.4s
38:	learn: 0.1755025	total: 1.19s	remaining: 29.4s
39:	learn: 0.1732208	total: 1.22s	remaining: 29.3s
40:	learn: 0.1709575	total: 1.25s	remaining: 29.3s
41:	learn: 0.1684576	total: 1.29s	remaining: 29.4s
42:	learn: 0.1664068	total: 1.32s	remaining: 29.4s
43:	learn: 0.1642226	total: 1.35s	remaining: 29.3s
44:	learn: 0.1621498	total: 1.38s	remaining: 29.3s
45:	learn: 0.1602796	total: 1.41s	remaining: 29.2s
46:	learn: 0.1584589	total: 1.44s	remaining: 29.3s
47:	learn: 0.1569803	total: 1.47s	remaining: 29.2s
48:	learn: 0.1552593	total: 1.5s	remaining: 29.1s
49:	learn: 0.1534235	total: 1.53s	remaining: 29.1s
50:	learn: 0.1517136	total: 1.56s	remaining: 29s
51:	learn: 0.1501682	total: 1.59s	remaining: 29s
52:	learn: 0.1486320	total: 1.62s	remaining: 29s
53:	learn: 0.1470943	total: 1.65s	remaining: 28.9s
54:	learn: 0.1458108	total: 1.68s	remaining: 28.9s
55:	learn: 0.1445556	total: 1.71s	remaining: 28.9s
56:	learn: 0.1433066	total: 1.74s	remaining: 28.8s
57:	learn: 0.1421784	total: 1.77s	remaining: 28.7s
58:	learn: 0.1410957	total: 1.8s	remaining: 28.7s
59:	learn: 0.1399370	total: 1.83s	remaining: 28.7s
60:	learn: 0.1387986	total: 1.86s	remaining: 28.6s
61:	learn: 0.1376446	total: 1.89s	remaining: 28.6s
62:	learn: 0.1367107	total: 1.92s	remaining: 28.5s
63:	learn: 0.1356552	total: 1.95s	remaining: 28.5s
64:	learn: 0.1347921	total: 1.98s	remaining: 28.4s
65:	learn: 0.1337671	total: 2.01s	remaining: 28.4s
66:	learn: 0.1330650	total: 2.04s	remaining: 28.4s
67:	learn: 0.1322650	total: 2.07s	remaining: 28.4s
68:	learn: 0.1315042	total: 2.1s	remaining: 28.3s
69:	learn: 0.1306843	total: 2.13s	remaining: 28.3s
70:	learn: 0.1298038	total: 2.16s	remaining: 28.3s
71:	learn: 0.1291267	total: 2.19s	remaining: 28.3s
72:	learn: 0.1284021	total: 2.23s	remaining: 28.3s
73:	learn: 0.1275697	total: 2.26s	remaining: 28.2s
74:	learn: 0.1269533	total: 2.29s	remaining: 28.2s
75:	learn: 0.1262414	total: 2.31s	remaining: 28.2s
76:	learn: 0.1255372	total: 2.34s	remaining: 28.1s
77:	learn: 0.1247757	total: 2.37s	remaining: 28.1s
78:	learn: 0.1240694	total: 2.4s	remaining: 28s
79:	learn: 0.1233517	total: 2.43s	remaining: 28s
80:	learn: 0.1226421	total: 2.46s	remaining: 28s
81:	learn: 0.1221530	total: 2.49s	remaining: 27.9s
82:	learn: 0.1215974	total: 2.52s	remaining: 27.8s
83:	learn: 0.1211011	total: 2.55s	remaining: 27.8s
84:	learn: 0.1205628	total: 2.58s	remaining: 27.8s
85:	learn: 0.1200050	total: 2.61s	remaining: 27.7s
86:	learn: 0.1195746	total: 2.64s	remaining: 27.7s
87:	learn: 0.1190593	total: 2.67s	remaining: 27.7s
88:	learn: 0.1186249	total: 2.71s	remaining: 27.8s
89:	learn: 0.1181636	total: 2.76s	remaining: 27.9s
90:	learn: 0.1177798	total: 2.79s	remaining: 27.9s
91:	learn: 0.1173082	total: 2.82s	remaining: 27.8s
92:	learn: 0.1168114	total: 2.85s	remaining: 27.8s
93:	learn: 0.1163815	total: 2.88s	remaining: 27.8s
94:	learn: 0.1160434	total: 2.92s	remaining: 27.8s
95:	learn: 0.1156328	total: 2.95s	remaining: 27.8s
96:	learn: 0.1151037	total: 2.99s	remaining: 27.8s
97:	learn: 0.1147417	total: 3.02s	remaining: 27.8s
98:	learn: 0.1144005	total: 3.05s	remaining: 27.8s
99:	learn: 0.1139784	total: 3.08s	remaining: 27.7s
100:	learn: 0.1136558	total: 3.11s	remaining: 27.7s
101:	learn: 0.1133419	total: 3.14s	remaining: 27.7s
102:	learn: 0.1130237	total: 3.17s	remaining: 27.6s
103:	learn: 0.1125999	total: 3.2s	remaining: 27.6s
104:	learn: 0.1122715	total: 3.23s	remaining: 27.5s
105:	learn: 0.1121164	total: 3.25s	remaining: 27.4s
106:	learn: 0.1117849	total: 3.28s	remaining: 27.3s
107:	learn: 0.1114399	total: 3.31s	remaining: 27.3s
108:	learn: 0.1110879	total: 3.34s	remaining: 27.3s
109:	learn: 0.1107584	total: 3.38s	remaining: 27.3s
110:	learn: 0.1104971	total: 3.41s	remaining: 27.3s
111:	learn: 0.1103131	total: 3.44s	remaining: 27.3s
112:	learn: 0.1100109	total: 3.47s	remaining: 27.2s
113:	learn: 0.1097292	total: 3.5s	remaining: 27.2s
114:	learn: 0.1093220	total: 3.53s	remaining: 27.2s
115:	learn: 0.1091276	total: 3.56s	remaining: 27.1s
116:	learn: 0.1087723	total: 3.6s	remaining: 27.1s
117:	learn: 0.1084704	total: 3.63s	remaining: 27.1s
118:	learn: 0.1081769	total: 3.66s	remaining: 27.1s
119:	learn: 0.1079419	total: 3.69s	remaining: 27.1s
120:	learn: 0.1076233	total: 3.72s	remaining: 27s
121:	learn: 0.1073330	total: 3.75s	remaining: 27s
122:	learn: 0.1073206	total: 3.77s	remaining: 26.9s
123:	learn: 0.1070660	total: 3.81s	remaining: 26.9s
124:	learn: 0.1066547	total: 3.84s	remaining: 26.9s
125:	learn: 0.1064356	total: 3.87s	remaining: 26.8s
126:	learn: 0.1064260	total: 3.88s	remaining: 26.7s
127:	learn: 0.1061269	total: 3.91s	remaining: 26.7s
128:	learn: 0.1058217	total: 3.94s	remaining: 26.6s
129:	learn: 0.1056289	total: 3.97s	remaining: 26.6s
130:	learn: 0.1053912	total: 4s	remaining: 26.6s
131:	learn: 0.1051842	total: 4.04s	remaining: 26.6s
132:	learn: 0.1051612	total: 4.07s	remaining: 26.5s
133:	learn: 0.1048665	total: 4.1s	remaining: 26.5s
134:	learn: 0.1046047	total: 4.13s	remaining: 26.5s
135:	learn: 0.1045889	total: 4.16s	remaining: 26.4s
136:	learn: 0.1043488	total: 4.19s	remaining: 26.4s
137:	learn: 0.1040798	total: 4.22s	remaining: 26.4s
138:	learn: 0.1038611	total: 4.25s	remaining: 26.3s
139:	learn: 0.1037813	total: 4.28s	remaining: 26.3s
140:	learn: 0.1035577	total: 4.31s	remaining: 26.3s
141:	learn: 0.1030141	total: 4.34s	remaining: 26.2s
142:	learn: 0.1027782	total: 4.37s	remaining: 26.2s
143:	learn: 0.1026934	total: 4.4s	remaining: 26.2s
144:	learn: 0.1024414	total: 4.43s	remaining: 26.1s
145:	learn: 0.1024352	total: 4.45s	remaining: 26s
146:	learn: 0.1024294	total: 4.46s	remaining: 25.9s
147:	learn: 0.1020586	total: 4.49s	remaining: 25.8s
148:	learn: 0.1020026	total: 4.52s	remaining: 25.8s
149:	learn: 0.1016344	total: 4.54s	remaining: 25.8s
150:	learn: 0.1014593	total: 4.58s	remaining: 25.8s
151:	learn: 0.1011553	total: 4.61s	remaining: 25.7s
152:	learn: 0.1009917	total: 4.64s	remaining: 25.7s
153:	learn: 0.1007765	total: 4.67s	remaining: 25.7s
154:	learn: 0.1004100	total: 4.7s	remaining: 25.6s
155:	learn: 0.1000871	total: 4.73s	remaining: 25.6s
156:	learn: 0.0997863	total: 4.77s	remaining: 25.6s
157:	learn: 0.0995997	total: 4.8s	remaining: 25.6s
158:	learn: 0.0995948	total: 4.82s	remaining: 25.5s
159:	learn: 0.0993860	total: 4.84s	remaining: 25.4s
160:	learn: 0.0992909	total: 4.88s	remaining: 25.4s
161:	learn: 0.0990442	total: 4.92s	remaining: 25.4s
162:	learn: 0.0988790	total: 4.95s	remaining: 25.4s
163:	learn: 0.0988576	total: 4.97s	remaining: 25.3s
164:	learn: 0.0988345	total: 5s	remaining: 25.3s
165:	learn: 0.0987639	total: 5.04s	remaining: 25.3s
166:	learn: 0.0984729	total: 5.07s	remaining: 25.3s
167:	learn: 0.0982794	total: 5.1s	remaining: 25.2s
168:	learn: 0.0980585	total: 5.13s	remaining: 25.2s
169:	learn: 0.0979313	total: 5.16s	remaining: 25.2s
170:	learn: 0.0977722	total: 5.2s	remaining: 25.2s
171:	learn: 0.0974961	total: 5.22s	remaining: 25.1s
172:	learn: 0.0972660	total: 5.25s	remaining: 25.1s
173:	learn: 0.0972454	total: 5.28s	remaining: 25s
174:	learn: 0.0972329	total: 5.3s	remaining: 25s
175:	learn: 0.0969995	total: 5.33s	remaining: 25s
176:	learn: 0.0967607	total: 5.36s	remaining: 24.9s
177:	learn: 0.0966242	total: 5.39s	remaining: 24.9s
178:	learn: 0.0964782	total: 5.42s	remaining: 24.9s
179:	learn: 0.0962297	total: 5.45s	remaining: 24.8s
180:	learn: 0.0958970	total: 5.48s	remaining: 24.8s
181:	learn: 0.0958563	total: 5.51s	remaining: 24.8s
182:	learn: 0.0958301	total: 5.54s	remaining: 24.7s
183:	learn: 0.0955834	total: 5.57s	remaining: 24.7s
184:	learn: 0.0954458	total: 5.6s	remaining: 24.7s
185:	learn: 0.0954218	total: 5.63s	remaining: 24.6s
186:	learn: 0.0951633	total: 5.66s	remaining: 24.6s
187:	learn: 0.0950573	total: 5.69s	remaining: 24.6s
188:	learn: 0.0949108	total: 5.72s	remaining: 24.6s
189:	learn: 0.0948883	total: 5.75s	remaining: 24.5s
190:	learn: 0.0948861	total: 5.77s	remaining: 24.4s
191:	learn: 0.0948586	total: 5.79s	remaining: 24.4s
192:	learn: 0.0948291	total: 5.83s	remaining: 24.4s
193:	learn: 0.0947166	total: 5.86s	remaining: 24.3s
194:	learn: 0.0943519	total: 5.88s	remaining: 24.3s
195:	learn: 0.0943323	total: 5.91s	remaining: 24.3s
196:	learn: 0.0941849	total: 5.94s	remaining: 24.2s
197:	learn: 0.0940552	total: 5.97s	remaining: 24.2s
198:	learn: 0.0937926	total: 6.01s	remaining: 24.2s
199:	learn: 0.0936453	total: 6.04s	remaining: 24.2s
200:	learn: 0.0936132	total: 6.07s	remaining: 24.1s
201:	learn: 0.0935930	total: 6.1s	remaining: 24.1s
202:	learn: 0.0935206	total: 6.13s	remaining: 24.1s
203:	learn: 0.0933514	total: 6.16s	remaining: 24s
204:	learn: 0.0931553	total: 6.19s	remaining: 24s
205:	learn: 0.0930242	total: 6.22s	remaining: 24s
206:	learn: 0.0928761	total: 6.25s	remaining: 24s
207:	learn: 0.0927593	total: 6.29s	remaining: 23.9s
208:	learn: 0.0925030	total: 6.32s	remaining: 23.9s
209:	learn: 0.0922975	total: 6.35s	remaining: 23.9s
210:	learn: 0.0921326	total: 6.38s	remaining: 23.8s
211:	learn: 0.0920029	total: 6.41s	remaining: 23.8s
212:	learn: 0.0917843	total: 6.44s	remaining: 23.8s
213:	learn: 0.0917565	total: 6.47s	remaining: 23.8s
214:	learn: 0.0916503	total: 6.5s	remaining: 23.7s
215:	learn: 0.0915689	total: 6.53s	remaining: 23.7s
216:	learn: 0.0914334	total: 6.56s	remaining: 23.7s
217:	learn: 0.0912254	total: 6.59s	remaining: 23.6s
218:	learn: 0.0910666	total: 6.62s	remaining: 23.6s
219:	learn: 0.0909468	total: 6.65s	remaining: 23.6s
220:	learn: 0.0908882	total: 6.68s	remaining: 23.6s
221:	learn: 0.0907603	total: 6.71s	remaining: 23.5s
222:	learn: 0.0907339	total: 6.75s	remaining: 23.5s
223:	learn: 0.0905933	total: 6.78s	remaining: 23.5s
224:	learn: 0.0905104	total: 6.81s	remaining: 23.4s
225:	learn: 0.0902969	total: 6.84s	remaining: 23.4s
226:	learn: 0.0902433	total: 6.89s	remaining: 23.5s
227:	learn: 0.0902229	total: 6.92s	remaining: 23.4s
228:	learn: 0.0901088	total: 6.95s	remaining: 23.4s
229:	learn: 0.0899032	total: 6.98s	remaining: 23.4s
230:	learn: 0.0897944	total: 7.01s	remaining: 23.3s
231:	learn: 0.0897723	total: 7.04s	remaining: 23.3s
232:	learn: 0.0897535	total: 7.08s	remaining: 23.3s
233:	learn: 0.0895547	total: 7.12s	remaining: 23.3s
234:	learn: 0.0894778	total: 7.15s	remaining: 23.3s
235:	learn: 0.0892709	total: 7.18s	remaining: 23.2s
236:	learn: 0.0892576	total: 7.21s	remaining: 23.2s
237:	learn: 0.0890985	total: 7.24s	remaining: 23.2s
238:	learn: 0.0890778	total: 7.27s	remaining: 23.1s
239:	learn: 0.0890542	total: 7.3s	remaining: 23.1s
240:	learn: 0.0888984	total: 7.33s	remaining: 23.1s
241:	learn: 0.0886955	total: 7.36s	remaining: 23.1s
242:	learn: 0.0885181	total: 7.39s	remaining: 23s
243:	learn: 0.0884954	total: 7.42s	remaining: 23s
244:	learn: 0.0884506	total: 7.45s	remaining: 23s
245:	learn: 0.0882308	total: 7.48s	remaining: 22.9s
246:	learn: 0.0881545	total: 7.51s	remaining: 22.9s
247:	learn: 0.0879414	total: 7.54s	remaining: 22.9s
248:	learn: 0.0879246	total: 7.57s	remaining: 22.8s
249:	learn: 0.0877816	total: 7.6s	remaining: 22.8s
250:	learn: 0.0877688	total: 7.63s	remaining: 22.8s
251:	learn: 0.0876369	total: 7.66s	remaining: 22.7s
252:	learn: 0.0875335	total: 7.69s	remaining: 22.7s
253:	learn: 0.0874614	total: 7.72s	remaining: 22.7s
254:	learn: 0.0874299	total: 7.75s	remaining: 22.7s
255:	learn: 0.0874128	total: 7.78s	remaining: 22.6s
256:	learn: 0.0873590	total: 7.81s	remaining: 22.6s
257:	learn: 0.0870767	total: 7.84s	remaining: 22.6s
258:	learn: 0.0868669	total: 7.87s	remaining: 22.5s
259:	learn: 0.0866423	total: 7.9s	remaining: 22.5s
260:	learn: 0.0866095	total: 7.93s	remaining: 22.5s
261:	learn: 0.0865844	total: 7.97s	remaining: 22.5s
262:	learn: 0.0865433	total: 8s	remaining: 22.4s
263:	learn: 0.0864098	total: 8.03s	remaining: 22.4s
264:	learn: 0.0862887	total: 8.07s	remaining: 22.4s
265:	learn: 0.0862733	total: 8.1s	remaining: 22.3s
266:	learn: 0.0862591	total: 8.13s	remaining: 22.3s
267:	learn: 0.0861235	total: 8.16s	remaining: 22.3s
268:	learn: 0.0860850	total: 8.19s	remaining: 22.2s
269:	learn: 0.0858985	total: 8.21s	remaining: 22.2s
270:	learn: 0.0857194	total: 8.24s	remaining: 22.2s
271:	learn: 0.0856773	total: 8.27s	remaining: 22.1s
272:	learn: 0.0856624	total: 8.3s	remaining: 22.1s
273:	learn: 0.0856481	total: 8.33s	remaining: 22.1s
274:	learn: 0.0854616	total: 8.36s	remaining: 22s
275:	learn: 0.0853614	total: 8.39s	remaining: 22s
276:	learn: 0.0852294	total: 8.42s	remaining: 22s
277:	learn: 0.0850765	total: 8.45s	remaining: 21.9s
278:	learn: 0.0850548	total: 8.47s	remaining: 21.9s
279:	learn: 0.0850419	total: 8.51s	remaining: 21.9s
280:	learn: 0.0848801	total: 8.54s	remaining: 21.8s
281:	learn: 0.0846563	total: 8.57s	remaining: 21.8s
282:	learn: 0.0846339	total: 8.6s	remaining: 21.8s
283:	learn: 0.0846216	total: 8.63s	remaining: 21.8s
284:	learn: 0.0845039	total: 8.67s	remaining: 21.7s
285:	learn: 0.0843265	total: 8.7s	remaining: 21.7s
286:	learn: 0.0843010	total: 8.73s	remaining: 21.7s
287:	learn: 0.0842923	total: 8.77s	remaining: 21.7s
288:	learn: 0.0841938	total: 8.8s	remaining: 21.6s
289:	learn: 0.0841821	total: 8.83s	remaining: 21.6s
290:	learn: 0.0840858	total: 8.86s	remaining: 21.6s
291:	learn: 0.0839112	total: 8.89s	remaining: 21.6s
292:	learn: 0.0837147	total: 8.93s	remaining: 21.5s
293:	learn: 0.0835634	total: 8.96s	remaining: 21.5s
294:	learn: 0.0834306	total: 8.99s	remaining: 21.5s
295:	learn: 0.0832906	total: 9.02s	remaining: 21.5s
296:	learn: 0.0832804	total: 9.05s	remaining: 21.4s
297:	learn: 0.0832086	total: 9.09s	remaining: 21.4s
298:	learn: 0.0831652	total: 9.12s	remaining: 21.4s
299:	learn: 0.0831586	total: 9.15s	remaining: 21.4s
300:	learn: 0.0829609	total: 9.18s	remaining: 21.3s
301:	learn: 0.0827514	total: 9.22s	remaining: 21.3s
302:	learn: 0.0826217	total: 9.25s	remaining: 21.3s
303:	learn: 0.0825326	total: 9.28s	remaining: 21.3s
304:	learn: 0.0824758	total: 9.31s	remaining: 21.2s
305:	learn: 0.0823910	total: 9.34s	remaining: 21.2s
306:	learn: 0.0823045	total: 9.37s	remaining: 21.2s
307:	learn: 0.0821710	total: 9.41s	remaining: 21.1s
308:	learn: 0.0821654	total: 9.44s	remaining: 21.1s
309:	learn: 0.0821568	total: 9.47s	remaining: 21.1s
310:	learn: 0.0821330	total: 9.5s	remaining: 21s
311:	learn: 0.0821253	total: 9.53s	remaining: 21s
312:	learn: 0.0820824	total: 9.56s	remaining: 21s
313:	learn: 0.0820723	total: 9.59s	remaining: 21s
314:	learn: 0.0819893	total: 9.62s	remaining: 20.9s
315:	learn: 0.0819800	total: 9.66s	remaining: 20.9s
316:	learn: 0.0819376	total: 9.69s	remaining: 20.9s
317:	learn: 0.0818342	total: 9.72s	remaining: 20.8s
318:	learn: 0.0817940	total: 9.75s	remaining: 20.8s
319:	learn: 0.0816887	total: 9.78s	remaining: 20.8s
320:	learn: 0.0815002	total: 9.81s	remaining: 20.8s
321:	learn: 0.0814187	total: 9.84s	remaining: 20.7s
322:	learn: 0.0813983	total: 9.88s	remaining: 20.7s
323:	learn: 0.0812753	total: 9.91s	remaining: 20.7s
324:	learn: 0.0812682	total: 9.94s	remaining: 20.7s
325:	learn: 0.0811267	total: 9.98s	remaining: 20.6s
326:	learn: 0.0810341	total: 10s	remaining: 20.6s
327:	learn: 0.0810270	total: 10s	remaining: 20.6s
328:	learn: 0.0810189	total: 10.1s	remaining: 20.6s
329:	learn: 0.0810022	total: 10.1s	remaining: 20.5s
330:	learn: 0.0808658	total: 10.1s	remaining: 20.5s
331:	learn: 0.0807210	total: 10.2s	remaining: 20.4s
332:	learn: 0.0807125	total: 10.2s	remaining: 20.4s
333:	learn: 0.0807048	total: 10.2s	remaining: 20.4s
334:	learn: 0.0805333	total: 10.3s	remaining: 20.4s
335:	learn: 0.0805241	total: 10.3s	remaining: 20.3s
336:	learn: 0.0803719	total: 10.3s	remaining: 20.3s
337:	learn: 0.0803641	total: 10.3s	remaining: 20.3s
338:	learn: 0.0802208	total: 10.4s	remaining: 20.2s
339:	learn: 0.0801528	total: 10.4s	remaining: 20.2s
340:	learn: 0.0800701	total: 10.4s	remaining: 20.2s
341:	learn: 0.0800617	total: 10.5s	remaining: 20.1s
342:	learn: 0.0799216	total: 10.5s	remaining: 20.1s
343:	learn: 0.0797414	total: 10.5s	remaining: 20.1s
344:	learn: 0.0797243	total: 10.6s	remaining: 20.1s
345:	learn: 0.0797074	total: 10.6s	remaining: 20s
346:	learn: 0.0796405	total: 10.6s	remaining: 20s
347:	learn: 0.0795931	total: 10.7s	remaining: 20s
348:	learn: 0.0795185	total: 10.7s	remaining: 19.9s
349:	learn: 0.0794549	total: 10.7s	remaining: 19.9s
350:	learn: 0.0793825	total: 10.7s	remaining: 19.9s
351:	learn: 0.0792169	total: 10.8s	remaining: 19.8s
352:	learn: 0.0790247	total: 10.8s	remaining: 19.8s
353:	learn: 0.0789578	total: 10.8s	remaining: 19.8s
354:	learn: 0.0789225	total: 10.9s	remaining: 19.8s
355:	learn: 0.0788198	total: 10.9s	remaining: 19.7s
356:	learn: 0.0786878	total: 10.9s	remaining: 19.7s
357:	learn: 0.0786531	total: 11s	remaining: 19.7s
358:	learn: 0.0786120	total: 11s	remaining: 19.6s
359:	learn: 0.0785908	total: 11s	remaining: 19.6s
360:	learn: 0.0784921	total: 11.1s	remaining: 19.6s
361:	learn: 0.0784350	total: 11.1s	remaining: 19.6s
362:	learn: 0.0784256	total: 11.1s	remaining: 19.6s
363:	learn: 0.0783518	total: 11.2s	remaining: 19.5s
364:	learn: 0.0782519	total: 11.2s	remaining: 19.5s
365:	learn: 0.0781060	total: 11.2s	remaining: 19.5s
366:	learn: 0.0779502	total: 11.3s	remaining: 19.5s
367:	learn: 0.0778137	total: 11.3s	remaining: 19.4s
368:	learn: 0.0778058	total: 11.4s	remaining: 19.4s
369:	learn: 0.0777994	total: 11.4s	remaining: 19.4s
370:	learn: 0.0776917	total: 11.4s	remaining: 19.4s
371:	learn: 0.0775641	total: 11.5s	remaining: 19.4s
372:	learn: 0.0774296	total: 11.5s	remaining: 19.3s
373:	learn: 0.0772879	total: 11.5s	remaining: 19.3s
374:	learn: 0.0771736	total: 11.6s	remaining: 19.3s
375:	learn: 0.0771651	total: 11.6s	remaining: 19.3s
376:	learn: 0.0770421	total: 11.6s	remaining: 19.2s
377:	learn: 0.0768545	total: 11.7s	remaining: 19.2s
378:	learn: 0.0768481	total: 11.7s	remaining: 19.2s
379:	learn: 0.0768133	total: 11.7s	remaining: 19.1s
380:	learn: 0.0767123	total: 11.8s	remaining: 19.1s
381:	learn: 0.0766064	total: 11.8s	remaining: 19.1s
382:	learn: 0.0765888	total: 11.8s	remaining: 19s
383:	learn: 0.0764335	total: 11.8s	remaining: 19s
384:	learn: 0.0762906	total: 11.9s	remaining: 19s
385:	learn: 0.0761555	total: 11.9s	remaining: 18.9s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior1st': 1 unseen categories converted to Unseen on transform.

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior2nd': 3 unseen categories converted to Unseen on transform.

CV folds:  46%|████▌     | 23/50 [12:08<14:18, 31.80s/fold]

Learning rate set to 0.042738
0:	learn: 0.3871487	total: 27.5ms	remaining: 27.4s
1:	learn: 0.3771581	total: 63.4ms	remaining: 31.6s
2:	learn: 0.3670342	total: 95.7ms	remaining: 31.8s
3:	learn: 0.3564413	total: 129ms	remaining: 32.1s
4:	learn: 0.3472072	total: 163ms	remaining: 32.4s
5:	learn: 0.3378142	total: 205ms	remaining: 33.9s
6:	learn: 0.3290692	total: 253ms	remaining: 36s
7:	learn: 0.3205718	total: 286ms	remaining: 35.5s
8:	learn: 0.3130019	total: 314ms	remaining: 34.6s
9:	learn: 0.3047071	total: 344ms	remaining: 34.1s
10:	learn: 0.2974677	total: 373ms	remaining: 33.6s
11:	learn: 0.2894937	total: 403ms	remaining: 33.2s
12:	learn: 0.2825824	total: 434ms	remaining: 32.9s
13:	learn: 0.2756052	total: 463ms	remaining: 32.6s
14:	learn: 0.2693658	total: 493ms	remaining: 32.4s
15:	learn: 0.2632042	total: 523ms	remaining: 32.2s
16:	learn: 0.2574096	total: 552ms	remaining: 31.9s
17:	learn: 0.2516512	total: 579ms	remaining: 31.6s
18:	learn: 0.2459908	total: 610ms	remaining: 31.5s
19:	learn: 0.2406617	total: 638ms	remaining: 31.3s
20:	learn: 0.2360649	total: 670ms	remaining: 31.2s
21:	learn: 0.2314845	total: 704ms	remaining: 31.3s
22:	learn: 0.2269578	total: 734ms	remaining: 31.2s
23:	learn: 0.2228682	total: 765ms	remaining: 31.1s
24:	learn: 0.2185633	total: 796ms	remaining: 31s
25:	learn: 0.2147321	total: 824ms	remaining: 30.9s
26:	learn: 0.2107393	total: 853ms	remaining: 30.8s
27:	learn: 0.2069524	total: 880ms	remaining: 30.6s
28:	learn: 0.2031872	total: 910ms	remaining: 30.5s
29:	learn: 0.1996939	total: 939ms	remaining: 30.4s
30:	learn: 0.1967470	total: 968ms	remaining: 30.3s
31:	learn: 0.1933358	total: 999ms	remaining: 30.2s
32:	learn: 0.1905119	total: 1.03s	remaining: 30.2s
33:	learn: 0.1878126	total: 1.06s	remaining: 30.1s
34:	learn: 0.1850933	total: 1.09s	remaining: 30s
35:	learn: 0.1823219	total: 1.11s	remaining: 29.8s
36:	learn: 0.1796716	total: 1.14s	remaining: 29.7s
37:	learn: 0.1771768	total: 1.18s	remaining: 29.8s
38:	learn: 0.1748503	total: 1.22s	remaining: 30s
39:	learn: 0.1723857	total: 1.24s	remaining: 29.9s
40:	learn: 0.1701083	total: 1.27s	remaining: 29.8s
41:	learn: 0.1681054	total: 1.3s	remaining: 29.8s
42:	learn: 0.1660002	total: 1.33s	remaining: 29.7s
43:	learn: 0.1639767	total: 1.37s	remaining: 29.7s
44:	learn: 0.1619716	total: 1.4s	remaining: 29.7s
45:	learn: 0.1601625	total: 1.43s	remaining: 29.7s
46:	learn: 0.1582611	total: 1.46s	remaining: 29.7s
47:	learn: 0.1564549	total: 1.5s	remaining: 29.7s
48:	learn: 0.1548968	total: 1.53s	remaining: 29.6s
49:	learn: 0.1532622	total: 1.56s	remaining: 29.6s
50:	learn: 0.1519363	total: 1.59s	remaining: 29.6s
51:	learn: 0.1503791	total: 1.62s	remaining: 29.5s
52:	learn: 0.1489429	total: 1.65s	remaining: 29.5s
53:	learn: 0.1478080	total: 1.68s	remaining: 29.4s
54:	learn: 0.1463941	total: 1.7s	remaining: 29.3s
55:	learn: 0.1451375	total: 1.74s	remaining: 29.3s
56:	learn: 0.1438130	total: 1.76s	remaining: 29.2s
57:	learn: 0.1427015	total: 1.79s	remaining: 29.1s
58:	learn: 0.1416419	total: 1.82s	remaining: 29.1s
59:	learn: 0.1403643	total: 1.85s	remaining: 29.1s
60:	learn: 0.1391562	total: 1.88s	remaining: 29s
61:	learn: 0.1380429	total: 1.91s	remaining: 28.9s
62:	learn: 0.1370135	total: 1.94s	remaining: 28.9s
63:	learn: 0.1362381	total: 1.98s	remaining: 28.9s
64:	learn: 0.1352855	total: 2.01s	remaining: 28.9s
65:	learn: 0.1346421	total: 2.04s	remaining: 28.8s
66:	learn: 0.1337780	total: 2.07s	remaining: 28.8s
67:	learn: 0.1330283	total: 2.1s	remaining: 28.8s
68:	learn: 0.1320878	total: 2.13s	remaining: 28.8s
69:	learn: 0.1311847	total: 2.16s	remaining: 28.7s
70:	learn: 0.1303361	total: 2.19s	remaining: 28.7s
71:	learn: 0.1296621	total: 2.22s	remaining: 28.7s
72:	learn: 0.1289733	total: 2.25s	remaining: 28.6s
73:	learn: 0.1280939	total: 2.28s	remaining: 28.6s
74:	learn: 0.1274224	total: 2.31s	remaining: 28.5s
75:	learn: 0.1266232	total: 2.34s	remaining: 28.5s
76:	learn: 0.1258075	total: 2.37s	remaining: 28.4s
77:	learn: 0.1252388	total: 2.4s	remaining: 28.4s
78:	learn: 0.1246084	total: 2.43s	remaining: 28.4s
79:	learn: 0.1241154	total: 2.46s	remaining: 28.3s
80:	learn: 0.1235544	total: 2.49s	remaining: 28.3s
81:	learn: 0.1230980	total: 2.52s	remaining: 28.2s
82:	learn: 0.1224376	total: 2.55s	remaining: 28.2s
83:	learn: 0.1216264	total: 2.58s	remaining: 28.2s
84:	learn: 0.1211020	total: 2.62s	remaining: 28.2s
85:	learn: 0.1203708	total: 2.64s	remaining: 28.1s
86:	learn: 0.1196318	total: 2.68s	remaining: 28.1s
87:	learn: 0.1191636	total: 2.7s	remaining: 28s
88:	learn: 0.1187438	total: 2.73s	remaining: 28s
89:	learn: 0.1182435	total: 2.76s	remaining: 27.9s
90:	learn: 0.1177323	total: 2.79s	remaining: 27.9s
91:	learn: 0.1172850	total: 2.83s	remaining: 27.9s
92:	learn: 0.1167722	total: 2.87s	remaining: 28s
93:	learn: 0.1164198	total: 2.91s	remaining: 28.1s
94:	learn: 0.1161084	total: 2.94s	remaining: 28s
95:	learn: 0.1156384	total: 2.97s	remaining: 28s
96:	learn: 0.1151125	total: 3s	remaining: 27.9s
97:	learn: 0.1148187	total: 3.03s	remaining: 27.9s
98:	learn: 0.1145154	total: 3.06s	remaining: 27.8s
99:	learn: 0.1141043	total: 3.09s	remaining: 27.8s
100:	learn: 0.1138671	total: 3.13s	remaining: 27.8s
101:	learn: 0.1135563	total: 3.16s	remaining: 27.8s
102:	learn: 0.1131543	total: 3.19s	remaining: 27.8s
103:	learn: 0.1128459	total: 3.22s	remaining: 27.7s
104:	learn: 0.1124575	total: 3.25s	remaining: 27.7s
105:	learn: 0.1119450	total: 3.28s	remaining: 27.6s
106:	learn: 0.1115214	total: 3.31s	remaining: 27.6s
107:	learn: 0.1111559	total: 3.35s	remaining: 27.7s
108:	learn: 0.1107776	total: 3.38s	remaining: 27.6s
109:	learn: 0.1104468	total: 3.41s	remaining: 27.6s
110:	learn: 0.1101534	total: 3.44s	remaining: 27.5s
111:	learn: 0.1098814	total: 3.47s	remaining: 27.5s
112:	learn: 0.1096261	total: 3.5s	remaining: 27.5s
113:	learn: 0.1092517	total: 3.54s	remaining: 27.5s
114:	learn: 0.1090617	total: 3.56s	remaining: 27.4s
115:	learn: 0.1087451	total: 3.59s	remaining: 27.4s
116:	learn: 0.1084062	total: 3.62s	remaining: 27.3s
117:	learn: 0.1081843	total: 3.65s	remaining: 27.3s
118:	learn: 0.1078075	total: 3.68s	remaining: 27.3s
119:	learn: 0.1076207	total: 3.71s	remaining: 27.2s
120:	learn: 0.1073197	total: 3.74s	remaining: 27.2s
121:	learn: 0.1070899	total: 3.77s	remaining: 27.2s
122:	learn: 0.1068459	total: 3.8s	remaining: 27.1s
123:	learn: 0.1065803	total: 3.83s	remaining: 27.1s
124:	learn: 0.1063735	total: 3.86s	remaining: 27s
125:	learn: 0.1062055	total: 3.89s	remaining: 27s
126:	learn: 0.1059330	total: 3.93s	remaining: 27s
127:	learn: 0.1057016	total: 3.96s	remaining: 27s
128:	learn: 0.1053816	total: 3.99s	remaining: 26.9s
129:	learn: 0.1051542	total: 4.02s	remaining: 26.9s
130:	learn: 0.1049189	total: 4.05s	remaining: 26.9s
131:	learn: 0.1046848	total: 4.08s	remaining: 26.8s
132:	learn: 0.1045011	total: 4.11s	remaining: 26.8s
133:	learn: 0.1043357	total: 4.14s	remaining: 26.8s
134:	learn: 0.1041479	total: 4.18s	remaining: 26.8s
135:	learn: 0.1039568	total: 4.21s	remaining: 26.7s
136:	learn: 0.1036008	total: 4.24s	remaining: 26.7s
137:	learn: 0.1034157	total: 4.27s	remaining: 26.7s
138:	learn: 0.1031169	total: 4.3s	remaining: 26.6s
139:	learn: 0.1028899	total: 4.33s	remaining: 26.6s
140:	learn: 0.1027880	total: 4.36s	remaining: 26.6s
141:	learn: 0.1025478	total: 4.39s	remaining: 26.5s
142:	learn: 0.1022488	total: 4.42s	remaining: 26.5s
143:	learn: 0.1020607	total: 4.46s	remaining: 26.5s
144:	learn: 0.1018481	total: 4.49s	remaining: 26.5s
145:	learn: 0.1015773	total: 4.52s	remaining: 26.4s
146:	learn: 0.1014021	total: 4.55s	remaining: 26.4s
147:	learn: 0.1011075	total: 4.58s	remaining: 26.4s
148:	learn: 0.1008588	total: 4.61s	remaining: 26.3s
149:	learn: 0.1006900	total: 4.64s	remaining: 26.3s
150:	learn: 0.1004260	total: 4.67s	remaining: 26.3s
151:	learn: 0.1002425	total: 4.7s	remaining: 26.2s
152:	learn: 0.1001067	total: 4.73s	remaining: 26.2s
153:	learn: 0.0998579	total: 4.76s	remaining: 26.2s
154:	learn: 0.0997032	total: 4.79s	remaining: 26.1s
155:	learn: 0.0994163	total: 4.83s	remaining: 26.1s
156:	learn: 0.0992186	total: 4.86s	remaining: 26.1s
157:	learn: 0.0989917	total: 4.9s	remaining: 26.1s
158:	learn: 0.0988148	total: 4.93s	remaining: 26.1s
159:	learn: 0.0987152	total: 4.96s	remaining: 26.1s
160:	learn: 0.0985044	total: 5s	remaining: 26s
161:	learn: 0.0983198	total: 5.04s	remaining: 26.1s
162:	learn: 0.0980879	total: 5.07s	remaining: 26s
163:	learn: 0.0978377	total: 5.11s	remaining: 26.1s
164:	learn: 0.0976779	total: 5.14s	remaining: 26s
165:	learn: 0.0975540	total: 5.17s	remaining: 26s
166:	learn: 0.0974576	total: 5.2s	remaining: 25.9s
167:	learn: 0.0971914	total: 5.22s	remaining: 25.9s
168:	learn: 0.0970363	total: 5.25s	remaining: 25.8s
169:	learn: 0.0969743	total: 5.29s	remaining: 25.8s
170:	learn: 0.0967806	total: 5.32s	remaining: 25.8s
171:	learn: 0.0966188	total: 5.35s	remaining: 25.8s
172:	learn: 0.0964478	total: 5.38s	remaining: 25.7s
173:	learn: 0.0963495	total: 5.42s	remaining: 25.7s
174:	learn: 0.0962291	total: 5.45s	remaining: 25.7s
175:	learn: 0.0960709	total: 5.5s	remaining: 25.8s
176:	learn: 0.0958813	total: 5.55s	remaining: 25.8s
177:	learn: 0.0955958	total: 5.58s	remaining: 25.8s
178:	learn: 0.0953874	total: 5.61s	remaining: 25.7s
179:	learn: 0.0952605	total: 5.64s	remaining: 25.7s
180:	learn: 0.0951004	total: 5.67s	remaining: 25.7s
181:	learn: 0.0948555	total: 5.71s	remaining: 25.6s
182:	learn: 0.0946767	total: 5.74s	remaining: 25.6s
183:	learn: 0.0945838	total: 5.77s	remaining: 25.6s
184:	learn: 0.0943035	total: 5.8s	remaining: 25.6s
185:	learn: 0.0942053	total: 5.83s	remaining: 25.5s
186:	learn: 0.0941210	total: 5.86s	remaining: 25.5s
187:	learn: 0.0939712	total: 5.89s	remaining: 25.4s
188:	learn: 0.0937228	total: 5.92s	remaining: 25.4s
189:	learn: 0.0936415	total: 5.95s	remaining: 25.4s
190:	learn: 0.0934909	total: 5.98s	remaining: 25.3s
191:	learn: 0.0932162	total: 6.01s	remaining: 25.3s
192:	learn: 0.0931286	total: 6.04s	remaining: 25.3s
193:	learn: 0.0930162	total: 6.07s	remaining: 25.2s
194:	learn: 0.0929707	total: 6.1s	remaining: 25.2s
195:	learn: 0.0929002	total: 6.13s	remaining: 25.2s
196:	learn: 0.0927077	total: 6.16s	remaining: 25.1s
197:	learn: 0.0926784	total: 6.19s	remaining: 25.1s
198:	learn: 0.0925414	total: 6.23s	remaining: 25.1s
199:	learn: 0.0924306	total: 6.26s	remaining: 25s
200:	learn: 0.0922894	total: 6.29s	remaining: 25s
201:	learn: 0.0920781	total: 6.32s	remaining: 25s
202:	learn: 0.0920175	total: 6.35s	remaining: 24.9s
203:	learn: 0.0919433	total: 6.38s	remaining: 24.9s
204:	learn: 0.0919015	total: 6.41s	remaining: 24.9s
205:	learn: 0.0918668	total: 6.44s	remaining: 24.8s
206:	learn: 0.0917730	total: 6.47s	remaining: 24.8s
207:	learn: 0.0916138	total: 6.5s	remaining: 24.7s
208:	learn: 0.0915030	total: 6.53s	remaining: 24.7s
209:	learn: 0.0913524	total: 6.56s	remaining: 24.7s
210:	learn: 0.0911181	total: 6.59s	remaining: 24.6s
211:	learn: 0.0909620	total: 6.62s	remaining: 24.6s
212:	learn: 0.0909014	total: 6.66s	remaining: 24.6s
213:	learn: 0.0908709	total: 6.69s	remaining: 24.6s
214:	learn: 0.0907159	total: 6.71s	remaining: 24.5s
215:	learn: 0.0906972	total: 6.74s	remaining: 24.5s
216:	learn: 0.0906460	total: 6.77s	remaining: 24.4s
217:	learn: 0.0904288	total: 6.8s	remaining: 24.4s
218:	learn: 0.0903023	total: 6.83s	remaining: 24.4s
219:	learn: 0.0901735	total: 6.86s	remaining: 24.3s
220:	learn: 0.0901252	total: 6.89s	remaining: 24.3s
221:	learn: 0.0898536	total: 6.92s	remaining: 24.3s
222:	learn: 0.0897494	total: 6.95s	remaining: 24.2s
223:	learn: 0.0896104	total: 6.98s	remaining: 24.2s
224:	learn: 0.0895148	total: 7.01s	remaining: 24.2s
225:	learn: 0.0894424	total: 7.05s	remaining: 24.1s
226:	learn: 0.0893198	total: 7.08s	remaining: 24.1s
227:	learn: 0.0893053	total: 7.11s	remaining: 24.1s
228:	learn: 0.0892560	total: 7.14s	remaining: 24.1s
229:	learn: 0.0892035	total: 7.18s	remaining: 24s
230:	learn: 0.0890173	total: 7.21s	remaining: 24s
231:	learn: 0.0889053	total: 7.25s	remaining: 24s
232:	learn: 0.0888930	total: 7.29s	remaining: 24s
233:	learn: 0.0888783	total: 7.32s	remaining: 24s
234:	learn: 0.0886647	total: 7.35s	remaining: 23.9s
235:	learn: 0.0886481	total: 7.38s	remaining: 23.9s
236:	learn: 0.0885965	total: 7.41s	remaining: 23.9s
237:	learn: 0.0883335	total: 7.44s	remaining: 23.8s
238:	learn: 0.0882102	total: 7.47s	remaining: 23.8s
239:	learn: 0.0881547	total: 7.5s	remaining: 23.8s
240:	learn: 0.0881389	total: 7.53s	remaining: 23.7s
241:	learn: 0.0880620	total: 7.56s	remaining: 23.7s
242:	learn: 0.0880475	total: 7.59s	remaining: 23.7s
243:	learn: 0.0880129	total: 7.65s	remaining: 23.7s
244:	learn: 0.0879491	total: 7.68s	remaining: 23.7s
245:	learn: 0.0879297	total: 7.71s	remaining: 23.6s
246:	learn: 0.0879004	total: 7.74s	remaining: 23.6s
247:	learn: 0.0878587	total: 7.77s	remaining: 23.6s
248:	learn: 0.0877921	total: 7.81s	remaining: 23.5s
249:	learn: 0.0877792	total: 7.84s	remaining: 23.5s
250:	learn: 0.0877342	total: 7.87s	remaining: 23.5s
251:	learn: 0.0876772	total: 7.89s	remaining: 23.4s
252:	learn: 0.0875805	total: 7.93s	remaining: 23.4s
253:	learn: 0.0875668	total: 7.95s	remaining: 23.4s
254:	learn: 0.0875521	total: 7.98s	remaining: 23.3s
255:	learn: 0.0875268	total: 8.02s	remaining: 23.3s
256:	learn: 0.0873280	total: 8.05s	remaining: 23.3s
257:	learn: 0.0873155	total: 8.08s	remaining: 23.2s
258:	learn: 0.0872992	total: 8.11s	remaining: 23.2s
259:	learn: 0.0872833	total: 8.14s	remaining: 23.2s
260:	learn: 0.0872597	total: 8.17s	remaining: 23.1s
261:	learn: 0.0870722	total: 8.2s	remaining: 23.1s
262:	learn: 0.0869213	total: 8.23s	remaining: 23.1s
263:	learn: 0.0869025	total: 8.26s	remaining: 23s
264:	learn: 0.0867044	total: 8.29s	remaining: 23s
265:	learn: 0.0865688	total: 8.32s	remaining: 23s
266:	learn: 0.0865516	total: 8.35s	remaining: 22.9s
267:	learn: 0.0865315	total: 8.38s	remaining: 22.9s
268:	learn: 0.0865166	total: 8.42s	remaining: 22.9s
269:	learn: 0.0863983	total: 8.44s	remaining: 22.8s
270:	learn: 0.0863292	total: 8.48s	remaining: 22.8s
271:	learn: 0.0862929	total: 8.51s	remaining: 22.8s
272:	learn: 0.0862831	total: 8.54s	remaining: 22.7s
273:	learn: 0.0862711	total: 8.57s	remaining: 22.7s
274:	learn: 0.0862219	total: 8.6s	remaining: 22.7s
275:	learn: 0.0861482	total: 8.63s	remaining: 22.6s
276:	learn: 0.0861315	total: 8.66s	remaining: 22.6s
277:	learn: 0.0861212	total: 8.69s	remaining: 22.6s
278:	learn: 0.0860527	total: 8.72s	remaining: 22.5s
279:	learn: 0.0860273	total: 8.75s	remaining: 22.5s
280:	learn: 0.0860141	total: 8.79s	remaining: 22.5s
281:	learn: 0.0859885	total: 8.82s	remaining: 22.5s
282:	learn: 0.0859531	total: 8.85s	remaining: 22.4s
283:	learn: 0.0858972	total: 8.88s	remaining: 22.4s
284:	learn: 0.0857503	total: 8.91s	remaining: 22.3s
285:	learn: 0.0857089	total: 8.94s	remaining: 22.3s
286:	learn: 0.0856804	total: 8.97s	remaining: 22.3s
287:	learn: 0.0856595	total: 9s	remaining: 22.3s
288:	learn: 0.0855637	total: 9.03s	remaining: 22.2s
289:	learn: 0.0854666	total: 9.06s	remaining: 22.2s
290:	learn: 0.0852432	total: 9.09s	remaining: 22.2s
291:	learn: 0.0852153	total: 9.12s	remaining: 22.1s
292:	learn: 0.0850023	total: 9.15s	remaining: 22.1s
293:	learn: 0.0848108	total: 9.18s	remaining: 22s
294:	learn: 0.0846300	total: 9.21s	remaining: 22s
295:	learn: 0.0844806	total: 9.24s	remaining: 22s
296:	learn: 0.0844349	total: 9.27s	remaining: 22s
297:	learn: 0.0842895	total: 9.3s	remaining: 21.9s
298:	learn: 0.0842383	total: 9.33s	remaining: 21.9s
299:	learn: 0.0841794	total: 9.36s	remaining: 21.8s
300:	learn: 0.0841628	total: 9.39s	remaining: 21.8s
301:	learn: 0.0840323	total: 9.42s	remaining: 21.8s
302:	learn: 0.0839247	total: 9.46s	remaining: 21.8s
303:	learn: 0.0838307	total: 9.49s	remaining: 21.7s
304:	learn: 0.0836983	total: 9.52s	remaining: 21.7s
305:	learn: 0.0836712	total: 9.54s	remaining: 21.6s
306:	learn: 0.0835613	total: 9.57s	remaining: 21.6s
307:	learn: 0.0834853	total: 9.6s	remaining: 21.6s
308:	learn: 0.0834748	total: 9.65s	remaining: 21.6s
309:	learn: 0.0833998	total: 9.68s	remaining: 21.5s
310:	learn: 0.0832278	total: 9.71s	remaining: 21.5s
311:	learn: 0.0832077	total: 9.74s	remaining: 21.5s
312:	learn: 0.0831948	total: 9.78s	remaining: 21.5s
313:	learn: 0.0829717	total: 9.82s	remaining: 21.4s
314:	learn: 0.0829528	total: 9.85s	remaining: 21.4s
315:	learn: 0.0829429	total: 9.88s	remaining: 21.4s
316:	learn: 0.0829300	total: 9.91s	remaining: 21.3s
317:	learn: 0.0829187	total: 9.94s	remaining: 21.3s
318:	learn: 0.0826731	total: 9.97s	remaining: 21.3s
319:	learn: 0.0826585	total: 10s	remaining: 21.3s
320:	learn: 0.0824423	total: 10s	remaining: 21.2s
321:	learn: 0.0823235	total: 10.1s	remaining: 21.2s
322:	learn: 0.0821582	total: 10.1s	remaining: 21.2s
323:	learn: 0.0821140	total: 10.1s	remaining: 21.1s
324:	learn: 0.0819889	total: 10.2s	remaining: 21.1s
325:	learn: 0.0819815	total: 10.2s	remaining: 21.1s
326:	learn: 0.0819324	total: 10.2s	remaining: 21s
327:	learn: 0.0818218	total: 10.3s	remaining: 21s
328:	learn: 0.0816534	total: 10.3s	remaining: 21s
329:	learn: 0.0815663	total: 10.3s	remaining: 20.9s
330:	learn: 0.0814081	total: 10.3s	remaining: 20.9s
331:	learn: 0.0813948	total: 10.4s	remaining: 20.9s
332:	learn: 0.0813784	total: 10.4s	remaining: 20.8s
333:	learn: 0.0812650	total: 10.4s	remaining: 20.8s
334:	learn: 0.0812274	total: 10.5s	remaining: 20.8s
335:	learn: 0.0812164	total: 10.5s	remaining: 20.7s
336:	learn: 0.0811843	total: 10.5s	remaining: 20.7s
337:	learn: 0.0810088	total: 10.6s	remaining: 20.7s
338:	learn: 0.0809351	total: 10.6s	remaining: 20.7s
339:	learn: 0.0809018	total: 10.6s	remaining: 20.6s
340:	learn: 0.0807549	total: 10.7s	remaining: 20.6s
341:	learn: 0.0807436	total: 10.7s	remaining: 20.6s
342:	learn: 0.0805443	total: 10.7s	remaining: 20.6s
343:	learn: 0.0805336	total: 10.8s	remaining: 20.5s
344:	learn: 0.0805232	total: 10.8s	remaining: 20.5s
345:	learn: 0.0804625	total: 10.8s	remaining: 20.5s
346:	learn: 0.0803933	total: 10.9s	remaining: 20.4s
347:	learn: 0.0802506	total: 10.9s	remaining: 20.4s
348:	learn: 0.0802286	total: 10.9s	remaining: 20.4s
349:	learn: 0.0801993	total: 10.9s	remaining: 20.3s
350:	learn: 0.0801439	total: 11s	remaining: 20.3s
351:	learn: 0.0800321	total: 11s	remaining: 20.3s
352:	learn: 0.0799110	total: 11s	remaining: 20.2s
353:	learn: 0.0797798	total: 11.1s	remaining: 20.2s
354:	learn: 0.0797342	total: 11.1s	remaining: 20.2s
355:	learn: 0.0797208	total: 11.1s	remaining: 20.2s
356:	learn: 0.0795867	total: 11.2s	remaining: 20.1s
357:	learn: 0.0795142	total: 11.2s	remaining: 20.1s
358:	learn: 0.0794817	total: 11.2s	remaining: 20s
359:	learn: 0.0794587	total: 11.3s	remaining: 20s
360:	learn: 0.0793198	total: 11.3s	remaining: 20s
361:	learn: 0.0792830	total: 11.3s	remaining: 20s
362:	learn: 0.0792030	total: 11.4s	remaining: 19.9s
363:	learn: 0.0791231	total: 11.4s	remaining: 19.9s
364:	learn: 0.0790167	total: 11.4s	remaining: 19.9s
365:	learn: 0.0789085	total: 11.5s	remaining: 19.9s
366:	learn: 0.0788754	total: 11.5s	remaining: 19.8s
367:	learn: 0.0786939	total: 11.5s	remaining: 19.8s
368:	learn: 0.0785866	total: 11.6s	remaining: 19.8s
369:	learn: 0.0785344	total: 11.6s	remaining: 19.7s
370:	learn: 0.0784649	total: 11.6s	remaining: 19.7s
371:	learn: 0.0784394	total: 11.6s	remaining: 19.7s
372:	learn: 0.0783274	total: 11.7s	remaining: 19.6s
373:	learn: 0.0782222	total: 11.7s	remaining: 19.6s
374:	learn: 0.0782022	total: 11.7s	remaining: 19.6s
375:	learn: 0.0781846	total: 11.8s	remaining: 19.5s
376:	learn: 0.0780239	total: 11.8s	remaining: 19.5s
377:	learn: 0.0780056	total: 11.8s	remaining: 19.5s
378:	learn: 0.0779667	total: 11.9s	remaining: 19.4s
379:	learn: 0.0778845	total: 11.9s	remaining: 19.4s
380:	learn: 0.0778760	total: 12s	remaining: 19.4s
381:	learn: 0.0778580	total: 12s	remaining: 19.4s
382:	learn: 0.0778511	total: 12s	remaining: 19.4s
383:	learn: 0.0778423	total: 12s	remaining: 19.3s
384:	learn: 0.0778191	total: 12.1s	remaining: 19.3s
385:	learn: 0.0776795	total: 12.1s	remaining: 19.3s
386:	learn: 0.0776678	total: 12.1s	remaining: 19.2s
387:	learn: 0.0774925	total: 12.2s	remaining: 19.2s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Functional': 1 unseen categories converted to Unseen on transform.

CV folds:  48%|████▊     | 24/50 [12:41<13:49, 31.89s/fold]

997:	learn: 0.0447790	total: 31.5s	remaining: 63.2ms
998:	learn: 0.0447691	total: 31.6s	remaining: 31.6ms
999:	learn: 0.0447475	total: 31.6s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3875189	total: 24.8ms	remaining: 24.7s
1:	learn: 0.3770981	total: 54.5ms	remaining: 27.2s
2:	learn: 0.3666773	total: 83.8ms	remaining: 27.8s
3:	learn: 0.3573801	total: 115ms	remaining: 28.5s
4:	learn: 0.3474056	total: 144ms	remaining: 28.7s
5:	learn: 0.3384583	total: 174ms	remaining: 28.8s
6:	learn: 0.3297085	total: 203ms	remaining: 28.8s
7:	learn: 0.3211202	total: 233ms	remaining: 28.9s
8:	learn: 0.3128761	total: 265ms	remaining: 29.2s
9:	learn: 0.3045583	total: 295ms	remaining: 29.2s
10:	learn: 0.2967131	total: 322ms	remaining: 29s
11:	learn: 0.2891579	total: 352ms	remaining: 29s
12:	learn: 0.2831691	total: 382ms	remaining: 29s
13:	learn: 0.2764432	total: 413ms	remaining: 29.1s
14:	learn: 0.2701495	total: 443ms	remaining: 29.1s
15:	learn: 0.2637174	total: 477ms	remaining: 29.3s
16:	learn: 0.2576860	total: 508ms	remaining: 29.4s
17:	learn: 0.2520286	total: 539ms	remaining: 29.4s
18:	learn: 0.2464992	total: 566ms	remaining: 29.2s
19:	learn: 0.2417897	total: 595ms	remaining: 29.1s
20:	learn: 0.2366785	total: 624ms	remaining: 29.1s
21:	learn: 0.2316411	total: 654ms	remaining: 29.1s
22:	learn: 0.2271696	total: 685ms	remaining: 29.1s
23:	learn: 0.2224851	total: 723ms	remaining: 29.4s
24:	learn: 0.2182722	total: 755ms	remaining: 29.4s
25:	learn: 0.2140477	total: 783ms	remaining: 29.3s
26:	learn: 0.2098854	total: 814ms	remaining: 29.3s
27:	learn: 0.2059187	total: 844ms	remaining: 29.3s
28:	learn: 0.2022187	total: 877ms	remaining: 29.3s
29:	learn: 0.1987950	total: 908ms	remaining: 29.4s
30:	learn: 0.1957490	total: 939ms	remaining: 29.4s
31:	learn: 0.1929552	total: 970ms	remaining: 29.3s
32:	learn: 0.1902194	total: 1s	remaining: 29.3s
33:	learn: 0.1878623	total: 1.02s	remaining: 29.1s
34:	learn: 0.1849531	total: 1.05s	remaining: 29s
35:	learn: 0.1823231	total: 1.08s	remaining: 29s
36:	learn: 0.1797025	total: 1.12s	remaining: 29.1s
37:	learn: 0.1768303	total: 1.15s	remaining: 29.1s
38:	learn: 0.1743996	total: 1.18s	remaining: 29.1s
39:	learn: 0.1722125	total: 1.21s	remaining: 29s
40:	learn: 0.1696955	total: 1.24s	remaining: 29s
41:	learn: 0.1676419	total: 1.27s	remaining: 28.9s
42:	learn: 0.1654056	total: 1.3s	remaining: 28.9s
43:	learn: 0.1636163	total: 1.33s	remaining: 28.8s
44:	learn: 0.1615174	total: 1.36s	remaining: 28.9s
45:	learn: 0.1596365	total: 1.39s	remaining: 28.8s
46:	learn: 0.1576767	total: 1.42s	remaining: 28.8s
47:	learn: 0.1556863	total: 1.45s	remaining: 28.8s
48:	learn: 0.1541579	total: 1.48s	remaining: 28.8s
49:	learn: 0.1525772	total: 1.51s	remaining: 28.7s
50:	learn: 0.1511688	total: 1.57s	remaining: 29.2s
51:	learn: 0.1495458	total: 1.6s	remaining: 29.2s
52:	learn: 0.1478596	total: 1.65s	remaining: 29.4s
53:	learn: 0.1465151	total: 1.68s	remaining: 29.5s
54:	learn: 0.1452542	total: 1.72s	remaining: 29.5s
55:	learn: 0.1438515	total: 1.75s	remaining: 29.5s
56:	learn: 0.1425263	total: 1.78s	remaining: 29.5s
57:	learn: 0.1412358	total: 1.82s	remaining: 29.5s
58:	learn: 0.1399312	total: 1.84s	remaining: 29.4s
59:	learn: 0.1389628	total: 1.87s	remaining: 29.4s
60:	learn: 0.1381412	total: 1.9s	remaining: 29.3s
61:	learn: 0.1369776	total: 1.93s	remaining: 29.2s
62:	learn: 0.1360112	total: 1.96s	remaining: 29.2s
63:	learn: 0.1349524	total: 2s	remaining: 29.2s
64:	learn: 0.1342307	total: 2.02s	remaining: 29.1s
65:	learn: 0.1334482	total: 2.05s	remaining: 29s
66:	learn: 0.1325054	total: 2.08s	remaining: 28.9s
67:	learn: 0.1314049	total: 2.11s	remaining: 28.9s
68:	learn: 0.1304979	total: 2.14s	remaining: 28.8s
69:	learn: 0.1294460	total: 2.17s	remaining: 28.8s
70:	learn: 0.1286995	total: 2.2s	remaining: 28.8s
71:	learn: 0.1278761	total: 2.23s	remaining: 28.7s
72:	learn: 0.1268604	total: 2.26s	remaining: 28.7s
73:	learn: 0.1261204	total: 2.28s	remaining: 28.6s
74:	learn: 0.1253963	total: 2.31s	remaining: 28.5s
75:	learn: 0.1247431	total: 2.34s	remaining: 28.5s
76:	learn: 0.1240609	total: 2.37s	remaining: 28.4s
77:	learn: 0.1236077	total: 2.4s	remaining: 28.3s
78:	learn: 0.1230212	total: 2.43s	remaining: 28.3s
79:	learn: 0.1222492	total: 2.46s	remaining: 28.3s
80:	learn: 0.1215226	total: 2.49s	remaining: 28.3s
81:	learn: 0.1209597	total: 2.52s	remaining: 28.2s
82:	learn: 0.1204629	total: 2.55s	remaining: 28.2s
83:	learn: 0.1198219	total: 2.58s	remaining: 28.1s
84:	learn: 0.1192386	total: 2.61s	remaining: 28.1s
85:	learn: 0.1187657	total: 2.64s	remaining: 28.1s
86:	learn: 0.1183352	total: 2.67s	remaining: 28s
87:	learn: 0.1178608	total: 2.7s	remaining: 28s
88:	learn: 0.1174490	total: 2.73s	remaining: 27.9s
89:	learn: 0.1168535	total: 2.76s	remaining: 27.9s
90:	learn: 0.1165594	total: 2.79s	remaining: 27.9s
91:	learn: 0.1161698	total: 2.82s	remaining: 27.8s
92:	learn: 0.1157891	total: 2.85s	remaining: 27.8s
93:	learn: 0.1152336	total: 2.88s	remaining: 27.8s
94:	learn: 0.1147706	total: 2.91s	remaining: 27.7s
95:	learn: 0.1143523	total: 2.94s	remaining: 27.7s
96:	learn: 0.1139113	total: 2.97s	remaining: 27.7s
97:	learn: 0.1134997	total: 3s	remaining: 27.6s
98:	learn: 0.1129462	total: 3.03s	remaining: 27.6s
99:	learn: 0.1125897	total: 3.06s	remaining: 27.5s
100:	learn: 0.1121893	total: 3.09s	remaining: 27.5s
101:	learn: 0.1118378	total: 3.12s	remaining: 27.5s
102:	learn: 0.1113403	total: 3.15s	remaining: 27.4s
103:	learn: 0.1109942	total: 3.18s	remaining: 27.4s
104:	learn: 0.1105306	total: 3.21s	remaining: 27.3s
105:	learn: 0.1100927	total: 3.23s	remaining: 27.3s
106:	learn: 0.1097110	total: 3.26s	remaining: 27.2s
107:	learn: 0.1093575	total: 3.29s	remaining: 27.2s
108:	learn: 0.1090318	total: 3.33s	remaining: 27.2s
109:	learn: 0.1087195	total: 3.35s	remaining: 27.1s
110:	learn: 0.1081750	total: 3.38s	remaining: 27.1s
111:	learn: 0.1076382	total: 3.41s	remaining: 27.1s
112:	learn: 0.1074947	total: 3.44s	remaining: 27s
113:	learn: 0.1072166	total: 3.47s	remaining: 27s
114:	learn: 0.1069102	total: 3.5s	remaining: 27s
115:	learn: 0.1066352	total: 3.54s	remaining: 26.9s
116:	learn: 0.1062918	total: 3.57s	remaining: 26.9s
117:	learn: 0.1060208	total: 3.6s	remaining: 26.9s
118:	learn: 0.1058201	total: 3.63s	remaining: 26.9s
119:	learn: 0.1055602	total: 3.66s	remaining: 26.8s
120:	learn: 0.1052369	total: 3.69s	remaining: 26.8s
121:	learn: 0.1048637	total: 3.73s	remaining: 26.8s
122:	learn: 0.1045911	total: 3.76s	remaining: 26.8s
123:	learn: 0.1043418	total: 3.79s	remaining: 26.8s
124:	learn: 0.1040044	total: 3.82s	remaining: 26.7s
125:	learn: 0.1038356	total: 3.85s	remaining: 26.7s
126:	learn: 0.1036117	total: 3.88s	remaining: 26.7s
127:	learn: 0.1033861	total: 3.92s	remaining: 26.7s
128:	learn: 0.1031629	total: 3.95s	remaining: 26.6s
129:	learn: 0.1029199	total: 3.98s	remaining: 26.6s
130:	learn: 0.1028357	total: 4.02s	remaining: 26.7s
131:	learn: 0.1024208	total: 4.05s	remaining: 26.6s
132:	learn: 0.1022519	total: 4.08s	remaining: 26.6s
133:	learn: 0.1020409	total: 4.11s	remaining: 26.6s
134:	learn: 0.1017726	total: 4.14s	remaining: 26.5s
135:	learn: 0.1015720	total: 4.17s	remaining: 26.5s
136:	learn: 0.1012060	total: 4.21s	remaining: 26.5s
137:	learn: 0.1008320	total: 4.26s	remaining: 26.6s
138:	learn: 0.1006316	total: 4.29s	remaining: 26.6s
139:	learn: 0.1003140	total: 4.32s	remaining: 26.6s
140:	learn: 0.1001111	total: 4.36s	remaining: 26.5s
141:	learn: 0.0998821	total: 4.38s	remaining: 26.5s
142:	learn: 0.0997147	total: 4.41s	remaining: 26.5s
143:	learn: 0.0994764	total: 4.44s	remaining: 26.4s
144:	learn: 0.0994100	total: 4.47s	remaining: 26.4s
145:	learn: 0.0992063	total: 4.5s	remaining: 26.4s
146:	learn: 0.0989432	total: 4.53s	remaining: 26.3s
147:	learn: 0.0987311	total: 4.57s	remaining: 26.3s
148:	learn: 0.0985958	total: 4.6s	remaining: 26.3s
149:	learn: 0.0983958	total: 4.63s	remaining: 26.2s
150:	learn: 0.0980494	total: 4.66s	remaining: 26.2s
151:	learn: 0.0978395	total: 4.72s	remaining: 26.3s
152:	learn: 0.0976589	total: 4.75s	remaining: 26.3s
153:	learn: 0.0974984	total: 4.79s	remaining: 26.3s
154:	learn: 0.0972975	total: 4.82s	remaining: 26.3s
155:	learn: 0.0971333	total: 4.85s	remaining: 26.2s
156:	learn: 0.0969862	total: 4.88s	remaining: 26.2s
157:	learn: 0.0968906	total: 4.91s	remaining: 26.2s
158:	learn: 0.0967959	total: 4.94s	remaining: 26.1s
159:	learn: 0.0966626	total: 4.97s	remaining: 26.1s
160:	learn: 0.0965647	total: 5s	remaining: 26.1s
161:	learn: 0.0963657	total: 5.04s	remaining: 26s
162:	learn: 0.0962760	total: 5.07s	remaining: 26s
163:	learn: 0.0959129	total: 5.1s	remaining: 26s
164:	learn: 0.0955907	total: 5.13s	remaining: 26s
165:	learn: 0.0952575	total: 5.16s	remaining: 25.9s
166:	learn: 0.0952163	total: 5.19s	remaining: 25.9s
167:	learn: 0.0949867	total: 5.22s	remaining: 25.9s
168:	learn: 0.0946543	total: 5.25s	remaining: 25.8s
169:	learn: 0.0944432	total: 5.28s	remaining: 25.8s
170:	learn: 0.0943854	total: 5.32s	remaining: 25.8s
171:	learn: 0.0942597	total: 5.34s	remaining: 25.7s
172:	learn: 0.0940424	total: 5.38s	remaining: 25.7s
173:	learn: 0.0938940	total: 5.41s	remaining: 25.7s
174:	learn: 0.0936528	total: 5.44s	remaining: 25.6s
175:	learn: 0.0935398	total: 5.47s	remaining: 25.6s
176:	learn: 0.0932883	total: 5.5s	remaining: 25.6s
177:	learn: 0.0930909	total: 5.53s	remaining: 25.5s
178:	learn: 0.0930517	total: 5.56s	remaining: 25.5s
179:	learn: 0.0928707	total: 5.58s	remaining: 25.4s
180:	learn: 0.0927492	total: 5.61s	remaining: 25.4s
181:	learn: 0.0924835	total: 5.64s	remaining: 25.4s
182:	learn: 0.0923924	total: 5.67s	remaining: 25.3s
183:	learn: 0.0922155	total: 5.71s	remaining: 25.3s
184:	learn: 0.0919950	total: 5.74s	remaining: 25.3s
185:	learn: 0.0919565	total: 5.77s	remaining: 25.3s
186:	learn: 0.0918456	total: 5.8s	remaining: 25.2s
187:	learn: 0.0916826	total: 5.83s	remaining: 25.2s
188:	learn: 0.0914472	total: 5.88s	remaining: 25.2s
189:	learn: 0.0914223	total: 5.91s	remaining: 25.2s
190:	learn: 0.0913173	total: 5.95s	remaining: 25.2s
191:	learn: 0.0912519	total: 6s	remaining: 25.2s
192:	learn: 0.0909815	total: 6.03s	remaining: 25.2s
193:	learn: 0.0909572	total: 6.06s	remaining: 25.2s
194:	learn: 0.0908577	total: 6.09s	remaining: 25.1s
195:	learn: 0.0906433	total: 6.12s	remaining: 25.1s
196:	learn: 0.0904365	total: 6.15s	remaining: 25.1s
197:	learn: 0.0902611	total: 6.18s	remaining: 25s
198:	learn: 0.0902340	total: 6.21s	remaining: 25s
199:	learn: 0.0901286	total: 6.25s	remaining: 25s
200:	learn: 0.0900361	total: 6.28s	remaining: 25s
201:	learn: 0.0898929	total: 6.31s	remaining: 24.9s
202:	learn: 0.0897772	total: 6.34s	remaining: 24.9s
203:	learn: 0.0897116	total: 6.37s	remaining: 24.9s
204:	learn: 0.0896827	total: 6.4s	remaining: 24.8s
205:	learn: 0.0894122	total: 6.43s	remaining: 24.8s
206:	learn: 0.0892091	total: 6.46s	remaining: 24.8s
207:	learn: 0.0891569	total: 6.49s	remaining: 24.7s
208:	learn: 0.0891210	total: 6.52s	remaining: 24.7s
209:	learn: 0.0890048	total: 6.55s	remaining: 24.6s
210:	learn: 0.0889863	total: 6.57s	remaining: 24.6s
211:	learn: 0.0888320	total: 6.6s	remaining: 24.5s
212:	learn: 0.0887618	total: 6.63s	remaining: 24.5s
213:	learn: 0.0887225	total: 6.67s	remaining: 24.5s
214:	learn: 0.0886348	total: 6.7s	remaining: 24.5s
215:	learn: 0.0885501	total: 6.73s	remaining: 24.4s
216:	learn: 0.0884089	total: 6.77s	remaining: 24.4s
217:	learn: 0.0883691	total: 6.8s	remaining: 24.4s
218:	learn: 0.0882028	total: 6.83s	remaining: 24.3s
219:	learn: 0.0881875	total: 6.86s	remaining: 24.3s
220:	learn: 0.0881332	total: 6.89s	remaining: 24.3s
221:	learn: 0.0878797	total: 6.92s	remaining: 24.2s
222:	learn: 0.0877155	total: 6.95s	remaining: 24.2s
223:	learn: 0.0877064	total: 6.98s	remaining: 24.2s
224:	learn: 0.0875137	total: 7.01s	remaining: 24.2s
225:	learn: 0.0874585	total: 7.04s	remaining: 24.1s
226:	learn: 0.0874192	total: 7.07s	remaining: 24.1s
227:	learn: 0.0873766	total: 7.1s	remaining: 24.1s
228:	learn: 0.0873198	total: 7.13s	remaining: 24s
229:	learn: 0.0872424	total: 7.17s	remaining: 24s
230:	learn: 0.0872222	total: 7.2s	remaining: 24s
231:	learn: 0.0871392	total: 7.23s	remaining: 23.9s
232:	learn: 0.0870956	total: 7.26s	remaining: 23.9s
233:	learn: 0.0870872	total: 7.29s	remaining: 23.9s
234:	learn: 0.0870441	total: 7.33s	remaining: 23.9s
235:	learn: 0.0868877	total: 7.36s	remaining: 23.8s
236:	learn: 0.0866143	total: 7.39s	remaining: 23.8s
237:	learn: 0.0865377	total: 7.42s	remaining: 23.8s
238:	learn: 0.0864954	total: 7.46s	remaining: 23.7s
239:	learn: 0.0864706	total: 7.49s	remaining: 23.7s
240:	learn: 0.0863789	total: 7.52s	remaining: 23.7s
241:	learn: 0.0863552	total: 7.55s	remaining: 23.7s
242:	learn: 0.0863097	total: 7.58s	remaining: 23.6s
243:	learn: 0.0862783	total: 7.61s	remaining: 23.6s
244:	learn: 0.0861543	total: 7.64s	remaining: 23.6s
245:	learn: 0.0860713	total: 7.67s	remaining: 23.5s
246:	learn: 0.0860162	total: 7.71s	remaining: 23.5s
247:	learn: 0.0860014	total: 7.74s	remaining: 23.5s
248:	learn: 0.0858814	total: 7.77s	remaining: 23.4s
249:	learn: 0.0858425	total: 7.8s	remaining: 23.4s
250:	learn: 0.0856893	total: 7.83s	remaining: 23.4s
251:	learn: 0.0856707	total: 7.86s	remaining: 23.3s
252:	learn: 0.0856020	total: 7.9s	remaining: 23.3s
253:	learn: 0.0855788	total: 7.93s	remaining: 23.3s
254:	learn: 0.0854753	total: 7.97s	remaining: 23.3s
255:	learn: 0.0852419	total: 8.02s	remaining: 23.3s
256:	learn: 0.0851148	total: 8.05s	remaining: 23.3s
257:	learn: 0.0850870	total: 8.08s	remaining: 23.2s
258:	learn: 0.0850366	total: 8.11s	remaining: 23.2s
259:	learn: 0.0849560	total: 8.14s	remaining: 23.2s
260:	learn: 0.0848898	total: 8.17s	remaining: 23.1s
261:	learn: 0.0847584	total: 8.21s	remaining: 23.1s
262:	learn: 0.0846738	total: 8.24s	remaining: 23.1s
263:	learn: 0.0846217	total: 8.27s	remaining: 23.1s
264:	learn: 0.0843622	total: 8.3s	remaining: 23s
265:	learn: 0.0843521	total: 8.33s	remaining: 23s
266:	learn: 0.0842012	total: 8.36s	remaining: 23s
267:	learn: 0.0841706	total: 8.39s	remaining: 22.9s
268:	learn: 0.0840343	total: 8.43s	remaining: 22.9s
269:	learn: 0.0840186	total: 8.48s	remaining: 22.9s
270:	learn: 0.0838851	total: 8.51s	remaining: 22.9s
271:	learn: 0.0838366	total: 8.54s	remaining: 22.8s
272:	learn: 0.0836535	total: 8.57s	remaining: 22.8s
273:	learn: 0.0834529	total: 8.6s	remaining: 22.8s
274:	learn: 0.0834291	total: 8.63s	remaining: 22.8s
275:	learn: 0.0833597	total: 8.66s	remaining: 22.7s
276:	learn: 0.0832985	total: 8.7s	remaining: 22.7s
277:	learn: 0.0832398	total: 8.73s	remaining: 22.7s
278:	learn: 0.0831692	total: 8.76s	remaining: 22.6s
279:	learn: 0.0831345	total: 8.79s	remaining: 22.6s
280:	learn: 0.0830947	total: 8.82s	remaining: 22.6s
281:	learn: 0.0830452	total: 8.85s	remaining: 22.5s
282:	learn: 0.0828905	total: 8.88s	remaining: 22.5s
283:	learn: 0.0828543	total: 8.91s	remaining: 22.5s
284:	learn: 0.0828311	total: 8.95s	remaining: 22.4s
285:	learn: 0.0827625	total: 8.97s	remaining: 22.4s
286:	learn: 0.0827534	total: 9.01s	remaining: 22.4s
287:	learn: 0.0827133	total: 9.04s	remaining: 22.3s
288:	learn: 0.0826733	total: 9.07s	remaining: 22.3s
289:	learn: 0.0826315	total: 9.1s	remaining: 22.3s
290:	learn: 0.0825956	total: 9.13s	remaining: 22.2s
291:	learn: 0.0824337	total: 9.16s	remaining: 22.2s
292:	learn: 0.0824227	total: 9.19s	remaining: 22.2s
293:	learn: 0.0824066	total: 9.22s	remaining: 22.1s
294:	learn: 0.0822230	total: 9.26s	remaining: 22.1s
295:	learn: 0.0821327	total: 9.29s	remaining: 22.1s
296:	learn: 0.0820880	total: 9.32s	remaining: 22.1s
297:	learn: 0.0820734	total: 9.35s	remaining: 22s
298:	learn: 0.0819932	total: 9.4s	remaining: 22s
299:	learn: 0.0819762	total: 9.43s	remaining: 22s
300:	learn: 0.0819638	total: 9.46s	remaining: 22s
301:	learn: 0.0818249	total: 9.49s	remaining: 21.9s
302:	learn: 0.0818127	total: 9.53s	remaining: 21.9s
303:	learn: 0.0817964	total: 9.56s	remaining: 21.9s
304:	learn: 0.0816836	total: 9.59s	remaining: 21.8s
305:	learn: 0.0815393	total: 9.62s	remaining: 21.8s
306:	learn: 0.0814176	total: 9.65s	remaining: 21.8s
307:	learn: 0.0814092	total: 9.68s	remaining: 21.7s
308:	learn: 0.0813697	total: 9.71s	remaining: 21.7s
309:	learn: 0.0812069	total: 9.74s	remaining: 21.7s
310:	learn: 0.0810781	total: 9.77s	remaining: 21.6s
311:	learn: 0.0810191	total: 9.8s	remaining: 21.6s
312:	learn: 0.0809422	total: 9.83s	remaining: 21.6s
313:	learn: 0.0809075	total: 9.86s	remaining: 21.5s
314:	learn: 0.0807150	total: 9.89s	remaining: 21.5s
315:	learn: 0.0806105	total: 9.92s	remaining: 21.5s
316:	learn: 0.0805889	total: 9.95s	remaining: 21.4s
317:	learn: 0.0804407	total: 9.99s	remaining: 21.4s
318:	learn: 0.0804036	total: 10s	remaining: 21.4s
319:	learn: 0.0802627	total: 10s	remaining: 21.4s
320:	learn: 0.0801610	total: 10.1s	remaining: 21.3s
321:	learn: 0.0801409	total: 10.1s	remaining: 21.3s
322:	learn: 0.0801060	total: 10.1s	remaining: 21.3s
323:	learn: 0.0800845	total: 10.2s	remaining: 21.3s
324:	learn: 0.0799663	total: 10.2s	remaining: 21.2s
325:	learn: 0.0799291	total: 10.3s	remaining: 21.3s
326:	learn: 0.0798062	total: 10.3s	remaining: 21.2s
327:	learn: 0.0796890	total: 10.3s	remaining: 21.2s
328:	learn: 0.0796674	total: 10.4s	remaining: 21.2s
329:	learn: 0.0796027	total: 10.4s	remaining: 21.1s
330:	learn: 0.0795074	total: 10.4s	remaining: 21.1s
331:	learn: 0.0794460	total: 10.5s	remaining: 21.1s
332:	learn: 0.0794157	total: 10.5s	remaining: 21.1s
333:	learn: 0.0793274	total: 10.5s	remaining: 21s
334:	learn: 0.0792637	total: 10.6s	remaining: 21s
335:	learn: 0.0792597	total: 10.6s	remaining: 21s
336:	learn: 0.0791338	total: 10.6s	remaining: 20.9s
337:	learn: 0.0791206	total: 10.7s	remaining: 20.9s
338:	learn: 0.0791106	total: 10.7s	remaining: 20.9s
339:	learn: 0.0790406	total: 10.7s	remaining: 20.8s
340:	learn: 0.0788557	total: 10.8s	remaining: 20.8s
341:	learn: 0.0788291	total: 10.8s	remaining: 20.8s
342:	learn: 0.0787331	total: 10.8s	remaining: 20.7s
343:	learn: 0.0786737	total: 10.9s	remaining: 20.7s
344:	learn: 0.0785884	total: 10.9s	remaining: 20.7s
345:	learn: 0.0784387	total: 10.9s	remaining: 20.6s
346:	learn: 0.0783849	total: 11s	remaining: 20.6s
347:	learn: 0.0783793	total: 11s	remaining: 20.6s
348:	learn: 0.0783208	total: 11s	remaining: 20.5s
349:	learn: 0.0782917	total: 11s	remaining: 20.5s
350:	learn: 0.0782487	total: 11.1s	remaining: 20.5s
351:	learn: 0.0782396	total: 11.1s	remaining: 20.4s
352:	learn: 0.0782168	total: 11.1s	remaining: 20.4s
353:	learn: 0.0781652	total: 11.2s	remaining: 20.4s
354:	learn: 0.0781379	total: 11.2s	remaining: 20.3s
355:	learn: 0.0781231	total: 11.2s	remaining: 20.3s
356:	learn: 0.0781186	total: 11.3s	remaining: 20.3s
357:	learn: 0.0779690	total: 11.3s	remaining: 20.2s
358:	learn: 0.0779533	total: 11.3s	remaining: 20.2s
359:	learn: 0.0778111	total: 11.4s	remaining: 20.2s
360:	learn: 0.0777895	total: 11.4s	remaining: 20.2s
361:	learn: 0.0777481	total: 11.4s	remaining: 20.1s
362:	learn: 0.0777294	total: 11.5s	remaining: 20.1s
363:	learn: 0.0775979	total: 11.5s	remaining: 20.1s
364:	learn: 0.0774417	total: 11.5s	remaining: 20s
365:	learn: 0.0772859	total: 11.5s	remaining: 20s
366:	learn: 0.0772271	total: 11.6s	remaining: 20s
367:	learn: 0.0771127	total: 11.6s	remaining: 19.9s
368:	learn: 0.0770331	total: 11.6s	remaining: 19.9s
369:	learn: 0.0769696	total: 11.7s	remaining: 19.9s
370:	learn: 0.0769583	total: 11.7s	remaining: 19.8s
371:	learn: 0.0768772	total: 11.7s	remaining: 19.8s
372:	learn: 0.0767336	total: 11.8s	remaining: 19.8s
373:	learn: 0.0766331	total: 11.8s	remaining: 19.8s
374:	learn: 0.0764655	total: 11.8s	remaining: 19.7s
375:	learn: 0.0763536	total: 11.9s	remaining: 19.7s
376:	learn: 0.0763108	total: 11.9s	remaining: 19.7s
377:	learn: 0.0762623	total: 11.9s	remaining: 19.7s
378:	learn: 0.0762326	total: 12s	remaining: 19.6s
379:	learn: 0.0761037	total: 12s	remaining: 19.6s
380:	learn: 0.0760900	total: 12s	remaining: 19.6s
381:	learn: 0.0760579	total: 12.1s	remaining: 19.5s
382:	learn: 0.0760315	total: 12.1s	remaining: 19.5s
383:	learn: 0.0758836	total: 12.1s	remaining: 19.4s
384:	learn: 0.0758581	total: 12.2s	remaining: 19.4s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior1st': 1 unseen categories converted to Unseen on transform.

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior2nd': 2 unseen categories converted to Unseen on transform.

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'HeatingQC': 1 unseen categories converted to Unseen on transform.

CV folds:  50%|█████     | 25/50 [13:13<13:19, 32.00s/fold]

999:	learn: 0.0449676	total: 31.7s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3880222	total: 24.9ms	remaining: 24.9s
1:	learn: 0.3775917	total: 53.9ms	remaining: 26.9s
2:	learn: 0.3670762	total: 82.4ms	remaining: 27.4s
3:	learn: 0.3571824	total: 114ms	remaining: 28.4s
4:	learn: 0.3475068	total: 143ms	remaining: 28.5s
5:	learn: 0.3386810	total: 173ms	remaining: 28.6s
6:	learn: 0.3296734	total: 201ms	remaining: 28.5s
7:	learn: 0.3218796	total: 230ms	remaining: 28.5s
8:	learn: 0.3137287	total: 261ms	remaining: 28.7s
9:	learn: 0.3060011	total: 293ms	remaining: 29s
10:	learn: 0.2987318	total: 320ms	remaining: 28.8s
11:	learn: 0.2914920	total: 352ms	remaining: 28.9s
12:	learn: 0.2848292	total: 383ms	remaining: 29.1s
13:	learn: 0.2785800	total: 413ms	remaining: 29.1s
14:	learn: 0.2727463	total: 444ms	remaining: 29.1s
15:	learn: 0.2668761	total: 482ms	remaining: 29.6s
16:	learn: 0.2606056	total: 514ms	remaining: 29.7s
17:	learn: 0.2549496	total: 545ms	remaining: 29.7s
18:	learn: 0.2493423	total: 576ms	remaining: 29.7s
19:	learn: 0.2441168	total: 604ms	remaining: 29.6s
20:	learn: 0.2394855	total: 634ms	remaining: 29.5s
21:	learn: 0.2344029	total: 664ms	remaining: 29.5s
22:	learn: 0.2299801	total: 698ms	remaining: 29.7s
23:	learn: 0.2257061	total: 729ms	remaining: 29.6s
24:	learn: 0.2214813	total: 758ms	remaining: 29.6s
25:	learn: 0.2174898	total: 789ms	remaining: 29.6s
26:	learn: 0.2135840	total: 823ms	remaining: 29.7s
27:	learn: 0.2097556	total: 853ms	remaining: 29.6s
28:	learn: 0.2062515	total: 883ms	remaining: 29.6s
29:	learn: 0.2029873	total: 914ms	remaining: 29.5s
30:	learn: 0.1997147	total: 946ms	remaining: 29.6s
31:	learn: 0.1966042	total: 976ms	remaining: 29.5s
32:	learn: 0.1936386	total: 1s	remaining: 29.4s
33:	learn: 0.1905914	total: 1.03s	remaining: 29.4s
34:	learn: 0.1876744	total: 1.06s	remaining: 29.3s
35:	learn: 0.1849233	total: 1.09s	remaining: 29.3s
36:	learn: 0.1819922	total: 1.12s	remaining: 29.2s
37:	learn: 0.1794389	total: 1.15s	remaining: 29.2s
38:	learn: 0.1770723	total: 1.18s	remaining: 29.2s
39:	learn: 0.1744877	total: 1.21s	remaining: 29.1s
40:	learn: 0.1719324	total: 1.24s	remaining: 29.1s
41:	learn: 0.1696821	total: 1.27s	remaining: 29s
42:	learn: 0.1674031	total: 1.3s	remaining: 29s
43:	learn: 0.1654362	total: 1.33s	remaining: 28.9s
44:	learn: 0.1636696	total: 1.36s	remaining: 28.8s
45:	learn: 0.1616243	total: 1.39s	remaining: 28.9s
46:	learn: 0.1598463	total: 1.42s	remaining: 28.9s
47:	learn: 0.1580033	total: 1.45s	remaining: 28.8s
48:	learn: 0.1562105	total: 1.48s	remaining: 28.7s
49:	learn: 0.1547017	total: 1.51s	remaining: 28.7s
50:	learn: 0.1532988	total: 1.54s	remaining: 28.7s
51:	learn: 0.1518186	total: 1.57s	remaining: 28.7s
52:	learn: 0.1504412	total: 1.6s	remaining: 28.6s
53:	learn: 0.1492506	total: 1.63s	remaining: 28.6s
54:	learn: 0.1477236	total: 1.66s	remaining: 28.6s
55:	learn: 0.1464875	total: 1.71s	remaining: 28.8s
56:	learn: 0.1452616	total: 1.74s	remaining: 28.8s
57:	learn: 0.1439582	total: 1.77s	remaining: 28.8s
58:	learn: 0.1429679	total: 1.8s	remaining: 28.8s
59:	learn: 0.1418468	total: 1.86s	remaining: 29.1s
60:	learn: 0.1407688	total: 1.88s	remaining: 29s
61:	learn: 0.1397241	total: 1.92s	remaining: 29s
62:	learn: 0.1388281	total: 1.94s	remaining: 28.9s
63:	learn: 0.1378822	total: 1.97s	remaining: 28.9s
64:	learn: 0.1370286	total: 2s	remaining: 28.8s
65:	learn: 0.1363538	total: 2.04s	remaining: 28.8s
66:	learn: 0.1355185	total: 2.07s	remaining: 28.8s
67:	learn: 0.1344374	total: 2.1s	remaining: 28.8s
68:	learn: 0.1336227	total: 2.13s	remaining: 28.7s
69:	learn: 0.1327209	total: 2.16s	remaining: 28.6s
70:	learn: 0.1319482	total: 2.18s	remaining: 28.6s
71:	learn: 0.1311104	total: 2.21s	remaining: 28.5s
72:	learn: 0.1304445	total: 2.24s	remaining: 28.5s
73:	learn: 0.1296638	total: 2.27s	remaining: 28.4s
74:	learn: 0.1288114	total: 2.3s	remaining: 28.4s
75:	learn: 0.1280552	total: 2.33s	remaining: 28.4s
76:	learn: 0.1272036	total: 2.37s	remaining: 28.4s
77:	learn: 0.1263646	total: 2.4s	remaining: 28.3s
78:	learn: 0.1256707	total: 2.43s	remaining: 28.3s
79:	learn: 0.1251500	total: 2.46s	remaining: 28.3s
80:	learn: 0.1244560	total: 2.49s	remaining: 28.2s
81:	learn: 0.1237912	total: 2.52s	remaining: 28.2s
82:	learn: 0.1233004	total: 2.55s	remaining: 28.2s
83:	learn: 0.1226942	total: 2.58s	remaining: 28.2s
84:	learn: 0.1222819	total: 2.62s	remaining: 28.2s
85:	learn: 0.1217716	total: 2.65s	remaining: 28.2s
86:	learn: 0.1211125	total: 2.68s	remaining: 28.1s
87:	learn: 0.1205301	total: 2.71s	remaining: 28.1s
88:	learn: 0.1200284	total: 2.73s	remaining: 28s
89:	learn: 0.1197025	total: 2.76s	remaining: 27.9s
90:	learn: 0.1191112	total: 2.79s	remaining: 27.9s
91:	learn: 0.1185413	total: 2.82s	remaining: 27.9s
92:	learn: 0.1181977	total: 2.86s	remaining: 27.9s
93:	learn: 0.1177010	total: 2.88s	remaining: 27.8s
94:	learn: 0.1172005	total: 2.92s	remaining: 27.8s
95:	learn: 0.1166815	total: 2.94s	remaining: 27.7s
96:	learn: 0.1163086	total: 2.98s	remaining: 27.7s
97:	learn: 0.1159432	total: 3.01s	remaining: 27.7s
98:	learn: 0.1155075	total: 3.04s	remaining: 27.7s
99:	learn: 0.1152492	total: 3.07s	remaining: 27.7s
100:	learn: 0.1148601	total: 3.1s	remaining: 27.6s
101:	learn: 0.1144694	total: 3.13s	remaining: 27.6s
102:	learn: 0.1141182	total: 3.16s	remaining: 27.6s
103:	learn: 0.1138480	total: 3.19s	remaining: 27.5s
104:	learn: 0.1134614	total: 3.22s	remaining: 27.5s
105:	learn: 0.1130872	total: 3.25s	remaining: 27.4s
106:	learn: 0.1127736	total: 3.28s	remaining: 27.4s
107:	learn: 0.1124335	total: 3.31s	remaining: 27.4s
108:	learn: 0.1121033	total: 3.35s	remaining: 27.4s
109:	learn: 0.1117785	total: 3.38s	remaining: 27.3s
110:	learn: 0.1115271	total: 3.4s	remaining: 27.3s
111:	learn: 0.1111708	total: 3.43s	remaining: 27.2s
112:	learn: 0.1107978	total: 3.46s	remaining: 27.2s
113:	learn: 0.1104279	total: 3.49s	remaining: 27.2s
114:	learn: 0.1101179	total: 3.52s	remaining: 27.1s
115:	learn: 0.1096445	total: 3.55s	remaining: 27.1s
116:	learn: 0.1093934	total: 3.58s	remaining: 27.1s
117:	learn: 0.1090191	total: 3.61s	remaining: 27s
118:	learn: 0.1088541	total: 3.64s	remaining: 26.9s
119:	learn: 0.1085528	total: 3.67s	remaining: 26.9s
120:	learn: 0.1083243	total: 3.69s	remaining: 26.8s
121:	learn: 0.1080395	total: 3.72s	remaining: 26.8s
122:	learn: 0.1077961	total: 3.76s	remaining: 26.8s
123:	learn: 0.1074780	total: 3.79s	remaining: 26.8s
124:	learn: 0.1072451	total: 3.82s	remaining: 26.7s
125:	learn: 0.1069925	total: 3.85s	remaining: 26.7s
126:	learn: 0.1067377	total: 3.88s	remaining: 26.7s
127:	learn: 0.1065545	total: 3.92s	remaining: 26.7s
128:	learn: 0.1062106	total: 3.94s	remaining: 26.6s
129:	learn: 0.1060479	total: 3.98s	remaining: 26.6s
130:	learn: 0.1059076	total: 4.02s	remaining: 26.6s
131:	learn: 0.1056612	total: 4.05s	remaining: 26.6s
132:	learn: 0.1053338	total: 4.08s	remaining: 26.6s
133:	learn: 0.1050472	total: 4.11s	remaining: 26.6s
134:	learn: 0.1048375	total: 4.14s	remaining: 26.5s
135:	learn: 0.1046389	total: 4.17s	remaining: 26.5s
136:	learn: 0.1044545	total: 4.2s	remaining: 26.5s
137:	learn: 0.1042499	total: 4.23s	remaining: 26.4s
138:	learn: 0.1041226	total: 4.26s	remaining: 26.4s
139:	learn: 0.1038402	total: 4.29s	remaining: 26.3s
140:	learn: 0.1036859	total: 4.32s	remaining: 26.3s
141:	learn: 0.1034304	total: 4.35s	remaining: 26.3s
142:	learn: 0.1032263	total: 4.38s	remaining: 26.2s
143:	learn: 0.1029967	total: 4.41s	remaining: 26.2s
144:	learn: 0.1027321	total: 4.44s	remaining: 26.2s
145:	learn: 0.1025074	total: 4.47s	remaining: 26.1s
146:	learn: 0.1021669	total: 4.5s	remaining: 26.1s
147:	learn: 0.1019561	total: 4.53s	remaining: 26.1s
148:	learn: 0.1017188	total: 4.56s	remaining: 26.1s
149:	learn: 0.1014742	total: 4.59s	remaining: 26s
150:	learn: 0.1013304	total: 4.62s	remaining: 26s
151:	learn: 0.1011651	total: 4.66s	remaining: 26s
152:	learn: 0.1009687	total: 4.69s	remaining: 26s
153:	learn: 0.1007373	total: 4.72s	remaining: 25.9s
154:	learn: 0.1004403	total: 4.75s	remaining: 25.9s
155:	learn: 0.1002753	total: 4.77s	remaining: 25.8s
156:	learn: 0.1001372	total: 4.8s	remaining: 25.8s
157:	learn: 0.0999808	total: 4.83s	remaining: 25.8s
158:	learn: 0.0998847	total: 4.87s	remaining: 25.8s
159:	learn: 0.0996969	total: 4.9s	remaining: 25.7s
160:	learn: 0.0995764	total: 4.93s	remaining: 25.7s
161:	learn: 0.0993879	total: 4.96s	remaining: 25.7s
162:	learn: 0.0992245	total: 4.99s	remaining: 25.6s
163:	learn: 0.0990690	total: 5.02s	remaining: 25.6s
164:	learn: 0.0989352	total: 5.05s	remaining: 25.6s
165:	learn: 0.0987133	total: 5.08s	remaining: 25.5s
166:	learn: 0.0985797	total: 5.11s	remaining: 25.5s
167:	learn: 0.0984496	total: 5.14s	remaining: 25.5s
168:	learn: 0.0984187	total: 5.17s	remaining: 25.4s
169:	learn: 0.0982096	total: 5.22s	remaining: 25.5s
170:	learn: 0.0980316	total: 5.25s	remaining: 25.5s
171:	learn: 0.0977562	total: 5.28s	remaining: 25.4s
172:	learn: 0.0977132	total: 5.32s	remaining: 25.4s
173:	learn: 0.0975285	total: 5.35s	remaining: 25.4s
174:	learn: 0.0974322	total: 5.38s	remaining: 25.4s
175:	learn: 0.0973082	total: 5.41s	remaining: 25.3s
176:	learn: 0.0971016	total: 5.44s	remaining: 25.3s
177:	learn: 0.0968709	total: 5.47s	remaining: 25.3s
178:	learn: 0.0966797	total: 5.5s	remaining: 25.2s
179:	learn: 0.0965194	total: 5.53s	remaining: 25.2s
180:	learn: 0.0964328	total: 5.56s	remaining: 25.2s
181:	learn: 0.0962879	total: 5.6s	remaining: 25.2s
182:	learn: 0.0961535	total: 5.63s	remaining: 25.1s
183:	learn: 0.0960364	total: 5.66s	remaining: 25.1s
184:	learn: 0.0958129	total: 5.69s	remaining: 25.1s
185:	learn: 0.0957216	total: 5.72s	remaining: 25s
186:	learn: 0.0955944	total: 5.75s	remaining: 25s
187:	learn: 0.0953247	total: 5.78s	remaining: 25s
188:	learn: 0.0950961	total: 5.81s	remaining: 24.9s
189:	learn: 0.0949270	total: 5.84s	remaining: 24.9s
190:	learn: 0.0947126	total: 5.87s	remaining: 24.9s
191:	learn: 0.0944819	total: 5.9s	remaining: 24.8s
192:	learn: 0.0943767	total: 5.93s	remaining: 24.8s
193:	learn: 0.0943052	total: 5.97s	remaining: 24.8s
194:	learn: 0.0941725	total: 6s	remaining: 24.8s
195:	learn: 0.0940636	total: 6.03s	remaining: 24.7s
196:	learn: 0.0938322	total: 6.06s	remaining: 24.7s
197:	learn: 0.0937367	total: 6.1s	remaining: 24.7s
198:	learn: 0.0936544	total: 6.13s	remaining: 24.7s
199:	learn: 0.0935435	total: 6.17s	remaining: 24.7s
200:	learn: 0.0933850	total: 6.2s	remaining: 24.6s
201:	learn: 0.0931198	total: 6.22s	remaining: 24.6s
202:	learn: 0.0930493	total: 6.25s	remaining: 24.6s
203:	learn: 0.0929361	total: 6.29s	remaining: 24.5s
204:	learn: 0.0928528	total: 6.32s	remaining: 24.5s
205:	learn: 0.0926307	total: 6.35s	remaining: 24.5s
206:	learn: 0.0925076	total: 6.38s	remaining: 24.5s
207:	learn: 0.0922243	total: 6.41s	remaining: 24.4s
208:	learn: 0.0921163	total: 6.44s	remaining: 24.4s
209:	learn: 0.0920526	total: 6.47s	remaining: 24.4s
210:	learn: 0.0918790	total: 6.5s	remaining: 24.3s
211:	learn: 0.0916987	total: 6.53s	remaining: 24.3s
212:	learn: 0.0914796	total: 6.56s	remaining: 24.3s
213:	learn: 0.0913738	total: 6.59s	remaining: 24.2s
214:	learn: 0.0912614	total: 6.62s	remaining: 24.2s
215:	learn: 0.0911861	total: 6.65s	remaining: 24.1s
216:	learn: 0.0910064	total: 6.68s	remaining: 24.1s
217:	learn: 0.0908227	total: 6.71s	remaining: 24.1s
218:	learn: 0.0906111	total: 6.74s	remaining: 24s
219:	learn: 0.0904675	total: 6.78s	remaining: 24s
220:	learn: 0.0904331	total: 6.81s	remaining: 24s
221:	learn: 0.0903684	total: 6.84s	remaining: 24s
222:	learn: 0.0903585	total: 6.87s	remaining: 24s
223:	learn: 0.0903392	total: 6.9s	remaining: 23.9s
224:	learn: 0.0902776	total: 6.94s	remaining: 23.9s
225:	learn: 0.0901803	total: 6.97s	remaining: 23.9s
226:	learn: 0.0900834	total: 7s	remaining: 23.8s
227:	learn: 0.0899231	total: 7.03s	remaining: 23.8s
228:	learn: 0.0898189	total: 7.06s	remaining: 23.8s
229:	learn: 0.0896916	total: 7.09s	remaining: 23.7s
230:	learn: 0.0895423	total: 7.13s	remaining: 23.7s
231:	learn: 0.0893962	total: 7.15s	remaining: 23.7s
232:	learn: 0.0893141	total: 7.18s	remaining: 23.6s
233:	learn: 0.0892027	total: 7.21s	remaining: 23.6s
234:	learn: 0.0890834	total: 7.24s	remaining: 23.6s
235:	learn: 0.0889559	total: 7.27s	remaining: 23.5s
236:	learn: 0.0889020	total: 7.3s	remaining: 23.5s
237:	learn: 0.0887076	total: 7.33s	remaining: 23.5s
238:	learn: 0.0886734	total: 7.36s	remaining: 23.4s
239:	learn: 0.0886373	total: 7.39s	remaining: 23.4s
240:	learn: 0.0885548	total: 7.43s	remaining: 23.4s
241:	learn: 0.0884759	total: 7.47s	remaining: 23.4s
242:	learn: 0.0883716	total: 7.5s	remaining: 23.4s
243:	learn: 0.0883223	total: 7.53s	remaining: 23.3s
244:	learn: 0.0880496	total: 7.56s	remaining: 23.3s
245:	learn: 0.0879070	total: 7.6s	remaining: 23.3s
246:	learn: 0.0878459	total: 7.63s	remaining: 23.3s
247:	learn: 0.0878140	total: 7.66s	remaining: 23.2s
248:	learn: 0.0875924	total: 7.69s	remaining: 23.2s
249:	learn: 0.0875395	total: 7.72s	remaining: 23.2s
250:	learn: 0.0874354	total: 7.76s	remaining: 23.1s
251:	learn: 0.0872435	total: 7.79s	remaining: 23.1s
252:	learn: 0.0871404	total: 7.82s	remaining: 23.1s
253:	learn: 0.0870956	total: 7.85s	remaining: 23.1s
254:	learn: 0.0870174	total: 7.88s	remaining: 23s
255:	learn: 0.0869480	total: 7.91s	remaining: 23s
256:	learn: 0.0867824	total: 7.95s	remaining: 23s
257:	learn: 0.0867355	total: 7.98s	remaining: 22.9s
258:	learn: 0.0866199	total: 8.01s	remaining: 22.9s
259:	learn: 0.0864974	total: 8.04s	remaining: 22.9s
260:	learn: 0.0863560	total: 8.07s	remaining: 22.8s
261:	learn: 0.0862099	total: 8.1s	remaining: 22.8s
262:	learn: 0.0861632	total: 8.13s	remaining: 22.8s
263:	learn: 0.0861266	total: 8.16s	remaining: 22.7s
264:	learn: 0.0860070	total: 8.19s	remaining: 22.7s
265:	learn: 0.0858448	total: 8.22s	remaining: 22.7s
266:	learn: 0.0858131	total: 8.24s	remaining: 22.6s
267:	learn: 0.0856197	total: 8.28s	remaining: 22.6s
268:	learn: 0.0855169	total: 8.32s	remaining: 22.6s
269:	learn: 0.0854437	total: 8.35s	remaining: 22.6s
270:	learn: 0.0852232	total: 8.38s	remaining: 22.6s
271:	learn: 0.0851255	total: 8.41s	remaining: 22.5s
272:	learn: 0.0849734	total: 8.44s	remaining: 22.5s
273:	learn: 0.0849353	total: 8.47s	remaining: 22.5s
274:	learn: 0.0848705	total: 8.51s	remaining: 22.4s
275:	learn: 0.0846601	total: 8.54s	remaining: 22.4s
276:	learn: 0.0845725	total: 8.58s	remaining: 22.4s
277:	learn: 0.0844982	total: 8.61s	remaining: 22.4s
278:	learn: 0.0843625	total: 8.64s	remaining: 22.3s
279:	learn: 0.0843325	total: 8.67s	remaining: 22.3s
280:	learn: 0.0842312	total: 8.7s	remaining: 22.3s
281:	learn: 0.0841712	total: 8.73s	remaining: 22.2s
282:	learn: 0.0840191	total: 8.76s	remaining: 22.2s
283:	learn: 0.0839921	total: 8.79s	remaining: 22.2s
284:	learn: 0.0838305	total: 8.82s	remaining: 22.1s
285:	learn: 0.0838179	total: 8.85s	remaining: 22.1s
286:	learn: 0.0836713	total: 8.88s	remaining: 22.1s
287:	learn: 0.0835813	total: 8.91s	remaining: 22s
288:	learn: 0.0834001	total: 8.94s	remaining: 22s
289:	learn: 0.0832898	total: 8.97s	remaining: 22s
290:	learn: 0.0831915	total: 9s	remaining: 21.9s
291:	learn: 0.0831351	total: 9.03s	remaining: 21.9s
292:	learn: 0.0830059	total: 9.07s	remaining: 21.9s
293:	learn: 0.0829846	total: 9.1s	remaining: 21.8s
294:	learn: 0.0828602	total: 9.13s	remaining: 21.8s
295:	learn: 0.0827168	total: 9.16s	remaining: 21.8s
296:	learn: 0.0825295	total: 9.19s	remaining: 21.8s
297:	learn: 0.0825189	total: 9.22s	remaining: 21.7s
298:	learn: 0.0824850	total: 9.25s	remaining: 21.7s
299:	learn: 0.0823737	total: 9.28s	remaining: 21.7s
300:	learn: 0.0822908	total: 9.31s	remaining: 21.6s
301:	learn: 0.0821407	total: 9.34s	remaining: 21.6s
302:	learn: 0.0821183	total: 9.37s	remaining: 21.6s
303:	learn: 0.0819871	total: 9.4s	remaining: 21.5s
304:	learn: 0.0818566	total: 9.45s	remaining: 21.5s
305:	learn: 0.0817512	total: 9.48s	remaining: 21.5s
306:	learn: 0.0816357	total: 9.51s	remaining: 21.5s
307:	learn: 0.0815257	total: 9.54s	remaining: 21.4s
308:	learn: 0.0815139	total: 9.57s	remaining: 21.4s
309:	learn: 0.0813463	total: 9.6s	remaining: 21.4s
310:	learn: 0.0812384	total: 9.63s	remaining: 21.3s
311:	learn: 0.0811851	total: 9.66s	remaining: 21.3s
312:	learn: 0.0811736	total: 9.7s	remaining: 21.3s
313:	learn: 0.0810713	total: 9.73s	remaining: 21.3s
314:	learn: 0.0809792	total: 9.76s	remaining: 21.2s
315:	learn: 0.0809552	total: 9.79s	remaining: 21.2s
316:	learn: 0.0809012	total: 9.82s	remaining: 21.2s
317:	learn: 0.0807924	total: 9.85s	remaining: 21.1s
318:	learn: 0.0807319	total: 9.88s	remaining: 21.1s
319:	learn: 0.0806367	total: 9.91s	remaining: 21.1s
320:	learn: 0.0805089	total: 9.95s	remaining: 21s
321:	learn: 0.0804371	total: 9.98s	remaining: 21s
322:	learn: 0.0803626	total: 10s	remaining: 21s
323:	learn: 0.0803340	total: 10s	remaining: 20.9s
324:	learn: 0.0802704	total: 10.1s	remaining: 20.9s
325:	learn: 0.0802426	total: 10.1s	remaining: 20.9s
326:	learn: 0.0802186	total: 10.1s	remaining: 20.9s
327:	learn: 0.0802086	total: 10.2s	remaining: 20.8s
328:	learn: 0.0801750	total: 10.2s	remaining: 20.8s
329:	learn: 0.0801572	total: 10.2s	remaining: 20.8s
330:	learn: 0.0801200	total: 10.3s	remaining: 20.7s
331:	learn: 0.0799745	total: 10.3s	remaining: 20.7s
332:	learn: 0.0798322	total: 10.3s	remaining: 20.7s
333:	learn: 0.0797850	total: 10.4s	remaining: 20.6s
334:	learn: 0.0796711	total: 10.4s	remaining: 20.6s
335:	learn: 0.0795145	total: 10.4s	remaining: 20.6s
336:	learn: 0.0794563	total: 10.5s	remaining: 20.6s
337:	learn: 0.0793149	total: 10.5s	remaining: 20.5s
338:	learn: 0.0791795	total: 10.5s	remaining: 20.5s
339:	learn: 0.0790470	total: 10.6s	remaining: 20.5s
340:	learn: 0.0790269	total: 10.6s	remaining: 20.5s
341:	learn: 0.0789483	total: 10.6s	remaining: 20.4s
342:	learn: 0.0788899	total: 10.6s	remaining: 20.4s
343:	learn: 0.0788706	total: 10.7s	remaining: 20.4s
344:	learn: 0.0787479	total: 10.7s	remaining: 20.3s
345:	learn: 0.0786467	total: 10.7s	remaining: 20.3s
346:	learn: 0.0785937	total: 10.8s	remaining: 20.3s
347:	learn: 0.0784808	total: 10.8s	remaining: 20.2s
348:	learn: 0.0784625	total: 10.8s	remaining: 20.2s
349:	learn: 0.0782611	total: 10.9s	remaining: 20.2s
350:	learn: 0.0781499	total: 10.9s	remaining: 20.1s
351:	learn: 0.0780066	total: 10.9s	remaining: 20.1s
352:	learn: 0.0778549	total: 11s	remaining: 20.1s
353:	learn: 0.0777769	total: 11s	remaining: 20.1s
354:	learn: 0.0777233	total: 11s	remaining: 20s
355:	learn: 0.0775148	total: 11.1s	remaining: 20s
356:	learn: 0.0774348	total: 11.1s	remaining: 20s
357:	learn: 0.0773622	total: 11.1s	remaining: 19.9s
358:	learn: 0.0772406	total: 11.1s	remaining: 19.9s
359:	learn: 0.0771267	total: 11.2s	remaining: 19.9s
360:	learn: 0.0771024	total: 11.2s	remaining: 19.8s
361:	learn: 0.0769969	total: 11.2s	remaining: 19.8s
362:	learn: 0.0769303	total: 11.3s	remaining: 19.8s
363:	learn: 0.0768462	total: 11.3s	remaining: 19.7s
364:	learn: 0.0768315	total: 11.3s	remaining: 19.7s
365:	learn: 0.0767624	total: 11.4s	remaining: 19.7s
366:	learn: 0.0766383	total: 11.4s	remaining: 19.6s
367:	learn: 0.0764788	total: 11.4s	remaining: 19.6s
368:	learn: 0.0763902	total: 11.4s	remaining: 19.6s
369:	learn: 0.0762831	total: 11.5s	remaining: 19.5s
370:	learn: 0.0761791	total: 11.5s	remaining: 19.5s
371:	learn: 0.0760989	total: 11.5s	remaining: 19.5s
372:	learn: 0.0760244	total: 11.6s	remaining: 19.5s
373:	learn: 0.0760156	total: 11.6s	remaining: 19.4s
374:	learn: 0.0759340	total: 11.6s	remaining: 19.4s
375:	learn: 0.0758292	total: 11.7s	remaining: 19.4s
376:	learn: 0.0756762	total: 11.7s	remaining: 19.3s
377:	learn: 0.0755673	total: 11.7s	remaining: 19.3s
378:	learn: 0.0754712	total: 11.8s	remaining: 19.3s
379:	learn: 0.0754585	total: 11.8s	remaining: 19.3s
380:	learn: 0.0753505	total: 11.8s	remaining: 19.2s
381:	learn: 0.0753158	total: 11.9s	remaining: 19.2s
382:	learn: 0.0752061	total: 11.9s	remaining: 19.2s
383:	learn: 0.0751757	total: 11.9s	remaining: 19.1s
384:	learn: 0.0751319	total: 12s	remaining: 19.1s
385:	learn: 0.0751222	total: 12s	remaining: 19.1s
386:	learn: 0.0750323	total: 12s	remaining: 19s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'ExterCond': 1 unseen categories converted to Unseen on transform.

CV folds:  52%|█████▏    | 26/50 [13:45<12:47, 31.96s/fold]

Learning rate set to 0.042738
0:	learn: 0.3860650	total: 28.4ms	remaining: 28.4s
1:	learn: 0.3756006	total: 60.5ms	remaining: 30.2s
2:	learn: 0.3646607	total: 91ms	remaining: 30.2s
3:	learn: 0.3546568	total: 121ms	remaining: 30.1s
4:	learn: 0.3454270	total: 150ms	remaining: 29.8s
5:	learn: 0.3363320	total: 179ms	remaining: 29.7s
6:	learn: 0.3271908	total: 211ms	remaining: 29.9s
7:	learn: 0.3193786	total: 248ms	remaining: 30.8s
8:	learn: 0.3110714	total: 280ms	remaining: 30.9s
9:	learn: 0.3034199	total: 320ms	remaining: 31.6s
10:	learn: 0.2958119	total: 351ms	remaining: 31.6s
11:	learn: 0.2888839	total: 378ms	remaining: 31.1s
12:	learn: 0.2814947	total: 409ms	remaining: 31s
13:	learn: 0.2748900	total: 445ms	remaining: 31.4s
14:	learn: 0.2688867	total: 475ms	remaining: 31.2s
15:	learn: 0.2624187	total: 504ms	remaining: 31s
16:	learn: 0.2565868	total: 533ms	remaining: 30.8s
17:	learn: 0.2512420	total: 567ms	remaining: 30.9s
18:	learn: 0.2459346	total: 594ms	remaining: 30.7s
19:	learn: 0.2406590	total: 640ms	remaining: 31.3s
20:	learn: 0.2356094	total: 675ms	remaining: 31.4s
21:	learn: 0.2310942	total: 706ms	remaining: 31.4s
22:	learn: 0.2261738	total: 735ms	remaining: 31.2s
23:	learn: 0.2220475	total: 764ms	remaining: 31.1s
24:	learn: 0.2181553	total: 792ms	remaining: 30.9s
25:	learn: 0.2143108	total: 822ms	remaining: 30.8s
26:	learn: 0.2099238	total: 863ms	remaining: 31.1s
27:	learn: 0.2061880	total: 892ms	remaining: 31s
28:	learn: 0.2028211	total: 930ms	remaining: 31.2s
29:	learn: 0.1994238	total: 959ms	remaining: 31s
30:	learn: 0.1956741	total: 998ms	remaining: 31.2s
31:	learn: 0.1923999	total: 1.03s	remaining: 31.1s
32:	learn: 0.1893522	total: 1.06s	remaining: 31s
33:	learn: 0.1863279	total: 1.09s	remaining: 30.9s
34:	learn: 0.1839732	total: 1.12s	remaining: 30.8s
35:	learn: 0.1812188	total: 1.14s	remaining: 30.6s
36:	learn: 0.1788288	total: 1.17s	remaining: 30.6s
37:	learn: 0.1764841	total: 1.2s	remaining: 30.5s
38:	learn: 0.1741168	total: 1.23s	remaining: 30.4s
39:	learn: 0.1720469	total: 1.26s	remaining: 30.4s
40:	learn: 0.1697617	total: 1.29s	remaining: 30.3s
41:	learn: 0.1674103	total: 1.32s	remaining: 30.2s
42:	learn: 0.1651744	total: 1.35s	remaining: 30.1s
43:	learn: 0.1634991	total: 1.38s	remaining: 30s
44:	learn: 0.1616711	total: 1.41s	remaining: 29.9s
45:	learn: 0.1599070	total: 1.44s	remaining: 29.8s
46:	learn: 0.1580503	total: 1.47s	remaining: 29.8s
47:	learn: 0.1565064	total: 1.5s	remaining: 29.7s
48:	learn: 0.1547438	total: 1.53s	remaining: 29.6s
49:	learn: 0.1531964	total: 1.56s	remaining: 29.7s
50:	learn: 0.1518735	total: 1.59s	remaining: 29.6s
51:	learn: 0.1505855	total: 1.64s	remaining: 29.9s
52:	learn: 0.1491618	total: 1.67s	remaining: 29.8s
53:	learn: 0.1476954	total: 1.7s	remaining: 29.8s
54:	learn: 0.1462344	total: 1.73s	remaining: 29.7s
55:	learn: 0.1450799	total: 1.76s	remaining: 29.7s
56:	learn: 0.1439989	total: 1.79s	remaining: 29.6s
57:	learn: 0.1428577	total: 1.82s	remaining: 29.6s
58:	learn: 0.1417413	total: 1.85s	remaining: 29.6s
59:	learn: 0.1405977	total: 1.88s	remaining: 29.5s
60:	learn: 0.1393217	total: 1.92s	remaining: 29.5s
61:	learn: 0.1382214	total: 1.94s	remaining: 29.4s
62:	learn: 0.1371479	total: 1.97s	remaining: 29.3s
63:	learn: 0.1363739	total: 2s	remaining: 29.3s
64:	learn: 0.1353654	total: 2.04s	remaining: 29.3s
65:	learn: 0.1343752	total: 2.07s	remaining: 29.3s
66:	learn: 0.1334772	total: 2.1s	remaining: 29.3s
67:	learn: 0.1324803	total: 2.13s	remaining: 29.2s
68:	learn: 0.1317092	total: 2.16s	remaining: 29.1s
69:	learn: 0.1309744	total: 2.19s	remaining: 29.1s
70:	learn: 0.1300867	total: 2.22s	remaining: 29.1s
71:	learn: 0.1293323	total: 2.25s	remaining: 29s
72:	learn: 0.1285626	total: 2.28s	remaining: 29s
73:	learn: 0.1278691	total: 2.31s	remaining: 28.9s
74:	learn: 0.1270511	total: 2.35s	remaining: 28.9s
75:	learn: 0.1263734	total: 2.38s	remaining: 28.9s
76:	learn: 0.1257612	total: 2.41s	remaining: 28.9s
77:	learn: 0.1249930	total: 2.44s	remaining: 28.8s
78:	learn: 0.1243572	total: 2.5s	remaining: 29.1s
79:	learn: 0.1238550	total: 2.53s	remaining: 29.1s
80:	learn: 0.1233539	total: 2.56s	remaining: 29.1s
81:	learn: 0.1227682	total: 2.59s	remaining: 29s
82:	learn: 0.1222095	total: 2.63s	remaining: 29s
83:	learn: 0.1216942	total: 2.65s	remaining: 29s
84:	learn: 0.1212919	total: 2.68s	remaining: 28.9s
85:	learn: 0.1207336	total: 2.71s	remaining: 28.8s
86:	learn: 0.1201003	total: 2.74s	remaining: 28.8s
87:	learn: 0.1195502	total: 2.77s	remaining: 28.7s
88:	learn: 0.1190574	total: 2.8s	remaining: 28.6s
89:	learn: 0.1184414	total: 2.83s	remaining: 28.6s
90:	learn: 0.1179986	total: 2.86s	remaining: 28.5s
91:	learn: 0.1177061	total: 2.89s	remaining: 28.5s
92:	learn: 0.1174148	total: 2.91s	remaining: 28.4s
93:	learn: 0.1169468	total: 2.94s	remaining: 28.3s
94:	learn: 0.1164485	total: 2.97s	remaining: 28.3s
95:	learn: 0.1160517	total: 3.01s	remaining: 28.3s
96:	learn: 0.1155025	total: 3.04s	remaining: 28.3s
97:	learn: 0.1151505	total: 3.07s	remaining: 28.2s
98:	learn: 0.1146583	total: 3.1s	remaining: 28.2s
99:	learn: 0.1144014	total: 3.13s	remaining: 28.2s
100:	learn: 0.1139778	total: 3.16s	remaining: 28.1s
101:	learn: 0.1136792	total: 3.19s	remaining: 28.1s
102:	learn: 0.1133275	total: 3.22s	remaining: 28s
103:	learn: 0.1130031	total: 3.25s	remaining: 28s
104:	learn: 0.1126603	total: 3.28s	remaining: 28s
105:	learn: 0.1123989	total: 3.31s	remaining: 28s
106:	learn: 0.1119762	total: 3.35s	remaining: 27.9s
107:	learn: 0.1116924	total: 3.38s	remaining: 27.9s
108:	learn: 0.1112632	total: 3.41s	remaining: 27.9s
109:	learn: 0.1109843	total: 3.44s	remaining: 27.8s
110:	learn: 0.1106123	total: 3.47s	remaining: 27.8s
111:	learn: 0.1103171	total: 3.5s	remaining: 27.8s
112:	learn: 0.1100260	total: 3.53s	remaining: 27.7s
113:	learn: 0.1097290	total: 3.56s	remaining: 27.7s
114:	learn: 0.1093412	total: 3.59s	remaining: 27.6s
115:	learn: 0.1090340	total: 3.62s	remaining: 27.6s
116:	learn: 0.1088486	total: 3.65s	remaining: 27.6s
117:	learn: 0.1085928	total: 3.68s	remaining: 27.5s
118:	learn: 0.1083953	total: 3.71s	remaining: 27.5s
119:	learn: 0.1081535	total: 3.74s	remaining: 27.4s
120:	learn: 0.1078736	total: 3.77s	remaining: 27.4s
121:	learn: 0.1075076	total: 3.79s	remaining: 27.3s
122:	learn: 0.1073419	total: 3.82s	remaining: 27.2s
123:	learn: 0.1071312	total: 3.85s	remaining: 27.2s
124:	learn: 0.1068146	total: 3.87s	remaining: 27.1s
125:	learn: 0.1066280	total: 3.9s	remaining: 27.1s
126:	learn: 0.1064378	total: 3.93s	remaining: 27s
127:	learn: 0.1061235	total: 3.96s	remaining: 27s
128:	learn: 0.1059146	total: 3.99s	remaining: 27s
129:	learn: 0.1056573	total: 4.02s	remaining: 26.9s
130:	learn: 0.1054071	total: 4.05s	remaining: 26.9s
131:	learn: 0.1052202	total: 4.08s	remaining: 26.9s
132:	learn: 0.1049415	total: 4.11s	remaining: 26.8s
133:	learn: 0.1047651	total: 4.15s	remaining: 26.8s
134:	learn: 0.1045552	total: 4.18s	remaining: 26.8s
135:	learn: 0.1044180	total: 4.21s	remaining: 26.7s
136:	learn: 0.1042274	total: 4.24s	remaining: 26.7s
137:	learn: 0.1040512	total: 4.27s	remaining: 26.7s
138:	learn: 0.1037911	total: 4.3s	remaining: 26.7s
139:	learn: 0.1035505	total: 4.33s	remaining: 26.6s
140:	learn: 0.1033339	total: 4.36s	remaining: 26.6s
141:	learn: 0.1031742	total: 4.39s	remaining: 26.5s
142:	learn: 0.1029475	total: 4.42s	remaining: 26.5s
143:	learn: 0.1025803	total: 4.45s	remaining: 26.5s
144:	learn: 0.1022378	total: 4.48s	remaining: 26.4s
145:	learn: 0.1021066	total: 4.52s	remaining: 26.4s
146:	learn: 0.1018846	total: 4.55s	remaining: 26.4s
147:	learn: 0.1017544	total: 4.58s	remaining: 26.3s
148:	learn: 0.1015799	total: 4.61s	remaining: 26.3s
149:	learn: 0.1011224	total: 4.65s	remaining: 26.4s
150:	learn: 0.1009344	total: 4.68s	remaining: 26.3s
151:	learn: 0.1006247	total: 4.71s	remaining: 26.3s
152:	learn: 0.1003968	total: 4.74s	remaining: 26.2s
153:	learn: 0.1002287	total: 4.77s	remaining: 26.2s
154:	learn: 0.1000578	total: 4.8s	remaining: 26.2s
155:	learn: 0.1000573	total: 4.81s	remaining: 26s
156:	learn: 0.0998899	total: 4.84s	remaining: 26s
157:	learn: 0.0997418	total: 4.87s	remaining: 25.9s
158:	learn: 0.0995029	total: 4.9s	remaining: 25.9s
159:	learn: 0.0994714	total: 4.96s	remaining: 26s
160:	learn: 0.0992997	total: 4.99s	remaining: 26s
161:	learn: 0.0990823	total: 5.02s	remaining: 26s
162:	learn: 0.0988091	total: 5.05s	remaining: 25.9s
163:	learn: 0.0986146	total: 5.08s	remaining: 25.9s
164:	learn: 0.0984433	total: 5.11s	remaining: 25.9s
165:	learn: 0.0982304	total: 5.17s	remaining: 26s
166:	learn: 0.0978507	total: 5.2s	remaining: 25.9s
167:	learn: 0.0975945	total: 5.22s	remaining: 25.9s
168:	learn: 0.0974101	total: 5.25s	remaining: 25.8s
169:	learn: 0.0972671	total: 5.29s	remaining: 25.8s
170:	learn: 0.0970435	total: 5.32s	remaining: 25.8s
171:	learn: 0.0968121	total: 5.34s	remaining: 25.7s
172:	learn: 0.0966730	total: 5.37s	remaining: 25.7s
173:	learn: 0.0965244	total: 5.4s	remaining: 25.6s
174:	learn: 0.0964225	total: 5.43s	remaining: 25.6s
175:	learn: 0.0962963	total: 5.46s	remaining: 25.6s
176:	learn: 0.0960422	total: 5.49s	remaining: 25.5s
177:	learn: 0.0959218	total: 5.52s	remaining: 25.5s
178:	learn: 0.0958050	total: 5.55s	remaining: 25.4s
179:	learn: 0.0954759	total: 5.58s	remaining: 25.4s
180:	learn: 0.0953807	total: 5.61s	remaining: 25.4s
181:	learn: 0.0952280	total: 5.64s	remaining: 25.3s
182:	learn: 0.0949593	total: 5.67s	remaining: 25.3s
183:	learn: 0.0947536	total: 5.7s	remaining: 25.3s
184:	learn: 0.0945318	total: 5.73s	remaining: 25.2s
185:	learn: 0.0943432	total: 5.76s	remaining: 25.2s
186:	learn: 0.0942346	total: 5.79s	remaining: 25.2s
187:	learn: 0.0940901	total: 5.82s	remaining: 25.1s
188:	learn: 0.0938844	total: 5.85s	remaining: 25.1s
189:	learn: 0.0936986	total: 5.88s	remaining: 25.1s
190:	learn: 0.0934921	total: 5.91s	remaining: 25s
191:	learn: 0.0934542	total: 5.94s	remaining: 25s
192:	learn: 0.0933232	total: 5.97s	remaining: 25s
193:	learn: 0.0932381	total: 6s	remaining: 24.9s
194:	learn: 0.0930968	total: 6.03s	remaining: 24.9s
195:	learn: 0.0929554	total: 6.06s	remaining: 24.9s
196:	learn: 0.0928317	total: 6.09s	remaining: 24.8s
197:	learn: 0.0926478	total: 6.13s	remaining: 24.8s
198:	learn: 0.0925034	total: 6.16s	remaining: 24.8s
199:	learn: 0.0924212	total: 6.19s	remaining: 24.7s
200:	learn: 0.0923079	total: 6.22s	remaining: 24.7s
201:	learn: 0.0921956	total: 6.25s	remaining: 24.7s
202:	learn: 0.0920923	total: 6.28s	remaining: 24.7s
203:	learn: 0.0919325	total: 6.31s	remaining: 24.6s
204:	learn: 0.0917890	total: 6.34s	remaining: 24.6s
205:	learn: 0.0916663	total: 6.38s	remaining: 24.6s
206:	learn: 0.0915775	total: 6.41s	remaining: 24.6s
207:	learn: 0.0914280	total: 6.45s	remaining: 24.6s
208:	learn: 0.0912814	total: 6.48s	remaining: 24.5s
209:	learn: 0.0911976	total: 6.51s	remaining: 24.5s
210:	learn: 0.0910788	total: 6.54s	remaining: 24.5s
211:	learn: 0.0908718	total: 6.57s	remaining: 24.4s
212:	learn: 0.0906603	total: 6.6s	remaining: 24.4s
213:	learn: 0.0905998	total: 6.63s	remaining: 24.4s
214:	learn: 0.0904499	total: 6.66s	remaining: 24.3s
215:	learn: 0.0903794	total: 6.7s	remaining: 24.3s
216:	learn: 0.0902946	total: 6.72s	remaining: 24.3s
217:	learn: 0.0900854	total: 6.75s	remaining: 24.2s
218:	learn: 0.0899506	total: 6.79s	remaining: 24.2s
219:	learn: 0.0898901	total: 6.82s	remaining: 24.2s
220:	learn: 0.0897618	total: 6.85s	remaining: 24.1s
221:	learn: 0.0896966	total: 6.88s	remaining: 24.1s
222:	learn: 0.0896116	total: 6.91s	remaining: 24.1s
223:	learn: 0.0894874	total: 6.94s	remaining: 24.1s
224:	learn: 0.0894358	total: 6.97s	remaining: 24s
225:	learn: 0.0892508	total: 7.01s	remaining: 24s
226:	learn: 0.0891991	total: 7.04s	remaining: 24s
227:	learn: 0.0891057	total: 7.08s	remaining: 24s
228:	learn: 0.0888927	total: 7.12s	remaining: 24s
229:	learn: 0.0887947	total: 7.15s	remaining: 23.9s
230:	learn: 0.0886561	total: 7.18s	remaining: 23.9s
231:	learn: 0.0885410	total: 7.21s	remaining: 23.9s
232:	learn: 0.0884855	total: 7.24s	remaining: 23.8s
233:	learn: 0.0884339	total: 7.27s	remaining: 23.8s
234:	learn: 0.0883122	total: 7.3s	remaining: 23.8s
235:	learn: 0.0882541	total: 7.33s	remaining: 23.7s
236:	learn: 0.0881208	total: 7.36s	remaining: 23.7s
237:	learn: 0.0879151	total: 7.4s	remaining: 23.7s
238:	learn: 0.0878084	total: 7.42s	remaining: 23.6s
239:	learn: 0.0876122	total: 7.46s	remaining: 23.6s
240:	learn: 0.0875862	total: 7.49s	remaining: 23.6s
241:	learn: 0.0875626	total: 7.52s	remaining: 23.5s
242:	learn: 0.0875272	total: 7.55s	remaining: 23.5s
243:	learn: 0.0874797	total: 7.58s	remaining: 23.5s
244:	learn: 0.0874243	total: 7.61s	remaining: 23.5s
245:	learn: 0.0873903	total: 7.64s	remaining: 23.4s
246:	learn: 0.0873147	total: 7.67s	remaining: 23.4s
247:	learn: 0.0870928	total: 7.71s	remaining: 23.4s
248:	learn: 0.0868867	total: 7.74s	remaining: 23.3s
249:	learn: 0.0868150	total: 7.77s	remaining: 23.3s
250:	learn: 0.0866302	total: 7.8s	remaining: 23.3s
251:	learn: 0.0865964	total: 7.83s	remaining: 23.2s
252:	learn: 0.0864833	total: 7.86s	remaining: 23.2s
253:	learn: 0.0864641	total: 7.89s	remaining: 23.2s
254:	learn: 0.0863730	total: 7.92s	remaining: 23.1s
255:	learn: 0.0862621	total: 7.95s	remaining: 23.1s
256:	learn: 0.0862424	total: 7.99s	remaining: 23.1s
257:	learn: 0.0862132	total: 8.02s	remaining: 23.1s
258:	learn: 0.0861969	total: 8.05s	remaining: 23s
259:	learn: 0.0861528	total: 8.08s	remaining: 23s
260:	learn: 0.0861315	total: 8.11s	remaining: 23s
261:	learn: 0.0861098	total: 8.14s	remaining: 22.9s
262:	learn: 0.0860588	total: 8.17s	remaining: 22.9s
263:	learn: 0.0859228	total: 8.2s	remaining: 22.9s
264:	learn: 0.0857897	total: 8.23s	remaining: 22.8s
265:	learn: 0.0856141	total: 8.26s	remaining: 22.8s
266:	learn: 0.0855847	total: 8.29s	remaining: 22.8s
267:	learn: 0.0855697	total: 8.32s	remaining: 22.7s
268:	learn: 0.0855306	total: 8.35s	remaining: 22.7s
269:	learn: 0.0854372	total: 8.38s	remaining: 22.7s
270:	learn: 0.0852608	total: 8.41s	remaining: 22.6s
271:	learn: 0.0851756	total: 8.44s	remaining: 22.6s
272:	learn: 0.0851389	total: 8.47s	remaining: 22.6s
273:	learn: 0.0850767	total: 8.5s	remaining: 22.5s
274:	learn: 0.0849299	total: 8.53s	remaining: 22.5s
275:	learn: 0.0849043	total: 8.56s	remaining: 22.5s
276:	learn: 0.0847992	total: 8.59s	remaining: 22.4s
277:	learn: 0.0847813	total: 8.62s	remaining: 22.4s
278:	learn: 0.0847697	total: 8.66s	remaining: 22.4s
279:	learn: 0.0847469	total: 8.69s	remaining: 22.3s
280:	learn: 0.0846244	total: 8.72s	remaining: 22.3s
281:	learn: 0.0846057	total: 8.75s	remaining: 22.3s
282:	learn: 0.0844727	total: 8.78s	remaining: 22.2s
283:	learn: 0.0843686	total: 8.81s	remaining: 22.2s
284:	learn: 0.0843579	total: 8.84s	remaining: 22.2s
285:	learn: 0.0843419	total: 8.87s	remaining: 22.2s
286:	learn: 0.0841295	total: 8.9s	remaining: 22.1s
287:	learn: 0.0840001	total: 8.94s	remaining: 22.1s
288:	learn: 0.0838679	total: 8.98s	remaining: 22.1s
289:	learn: 0.0837984	total: 9.01s	remaining: 22.1s
290:	learn: 0.0837716	total: 9.04s	remaining: 22s
291:	learn: 0.0835506	total: 9.07s	remaining: 22s
292:	learn: 0.0834325	total: 9.1s	remaining: 22s
293:	learn: 0.0833862	total: 9.13s	remaining: 21.9s
294:	learn: 0.0832675	total: 9.16s	remaining: 21.9s
295:	learn: 0.0831511	total: 9.19s	remaining: 21.9s
296:	learn: 0.0830288	total: 9.22s	remaining: 21.8s
297:	learn: 0.0829125	total: 9.25s	remaining: 21.8s
298:	learn: 0.0829010	total: 9.29s	remaining: 21.8s
299:	learn: 0.0828560	total: 9.32s	remaining: 21.7s
300:	learn: 0.0827290	total: 9.35s	remaining: 21.7s
301:	learn: 0.0827200	total: 9.38s	remaining: 21.7s
302:	learn: 0.0826602	total: 9.41s	remaining: 21.6s
303:	learn: 0.0824719	total: 9.45s	remaining: 21.6s
304:	learn: 0.0824594	total: 9.5s	remaining: 21.6s
305:	learn: 0.0824184	total: 9.52s	remaining: 21.6s
306:	learn: 0.0823779	total: 9.55s	remaining: 21.6s
307:	learn: 0.0823361	total: 9.58s	remaining: 21.5s
308:	learn: 0.0822073	total: 9.61s	remaining: 21.5s
309:	learn: 0.0821680	total: 9.64s	remaining: 21.5s
310:	learn: 0.0821004	total: 9.67s	remaining: 21.4s
311:	learn: 0.0819480	total: 9.7s	remaining: 21.4s
312:	learn: 0.0819345	total: 9.73s	remaining: 21.4s
313:	learn: 0.0819232	total: 9.77s	remaining: 21.3s
314:	learn: 0.0818285	total: 9.8s	remaining: 21.3s
315:	learn: 0.0818201	total: 9.83s	remaining: 21.3s
316:	learn: 0.0817263	total: 9.86s	remaining: 21.2s
317:	learn: 0.0817136	total: 9.89s	remaining: 21.2s
318:	learn: 0.0816926	total: 9.92s	remaining: 21.2s
319:	learn: 0.0816158	total: 9.95s	remaining: 21.1s
320:	learn: 0.0815617	total: 9.98s	remaining: 21.1s
321:	learn: 0.0814357	total: 10s	remaining: 21.1s
322:	learn: 0.0812612	total: 10s	remaining: 21s
323:	learn: 0.0812413	total: 10.1s	remaining: 21s
324:	learn: 0.0811923	total: 10.1s	remaining: 21s
325:	learn: 0.0810615	total: 10.1s	remaining: 21s
326:	learn: 0.0808870	total: 10.2s	remaining: 20.9s
327:	learn: 0.0807128	total: 10.2s	remaining: 20.9s
328:	learn: 0.0807041	total: 10.2s	remaining: 20.9s
329:	learn: 0.0806926	total: 10.3s	remaining: 20.8s
330:	learn: 0.0806842	total: 10.3s	remaining: 20.8s
331:	learn: 0.0806331	total: 10.3s	remaining: 20.8s
332:	learn: 0.0806218	total: 10.4s	remaining: 20.7s
333:	learn: 0.0805391	total: 10.4s	remaining: 20.7s
334:	learn: 0.0804321	total: 10.4s	remaining: 20.7s
335:	learn: 0.0803567	total: 10.4s	remaining: 20.7s
336:	learn: 0.0803019	total: 10.5s	remaining: 20.6s
337:	learn: 0.0802917	total: 10.5s	remaining: 20.6s
338:	learn: 0.0802634	total: 10.6s	remaining: 20.6s
339:	learn: 0.0801613	total: 10.6s	remaining: 20.5s
340:	learn: 0.0800959	total: 10.6s	remaining: 20.5s
341:	learn: 0.0800694	total: 10.6s	remaining: 20.5s
342:	learn: 0.0799063	total: 10.7s	remaining: 20.5s
343:	learn: 0.0798978	total: 10.7s	remaining: 20.4s
344:	learn: 0.0798306	total: 10.7s	remaining: 20.4s
345:	learn: 0.0797949	total: 10.8s	remaining: 20.4s
346:	learn: 0.0797725	total: 10.8s	remaining: 20.3s
347:	learn: 0.0797621	total: 10.8s	remaining: 20.3s
348:	learn: 0.0797558	total: 10.9s	remaining: 20.3s
349:	learn: 0.0797472	total: 10.9s	remaining: 20.2s
350:	learn: 0.0796733	total: 10.9s	remaining: 20.2s
351:	learn: 0.0795973	total: 11s	remaining: 20.2s
352:	learn: 0.0794634	total: 11s	remaining: 20.1s
353:	learn: 0.0793788	total: 11s	remaining: 20.1s
354:	learn: 0.0793079	total: 11.1s	remaining: 20.1s
355:	learn: 0.0792346	total: 11.1s	remaining: 20.1s
356:	learn: 0.0791753	total: 11.1s	remaining: 20.1s
357:	learn: 0.0791652	total: 11.2s	remaining: 20s
358:	learn: 0.0790462	total: 11.2s	remaining: 20s
359:	learn: 0.0789742	total: 11.2s	remaining: 20s
360:	learn: 0.0789596	total: 11.3s	remaining: 19.9s
361:	learn: 0.0789498	total: 11.3s	remaining: 19.9s
362:	learn: 0.0788947	total: 11.3s	remaining: 19.9s
363:	learn: 0.0787630	total: 11.3s	remaining: 19.8s
364:	learn: 0.0786183	total: 11.4s	remaining: 19.8s
365:	learn: 0.0786084	total: 11.4s	remaining: 19.8s
366:	learn: 0.0785141	total: 11.4s	remaining: 19.7s
367:	learn: 0.0784856	total: 11.5s	remaining: 19.7s
368:	learn: 0.0784609	total: 11.5s	remaining: 19.7s
369:	learn: 0.0784395	total: 11.5s	remaining: 19.6s
370:	learn: 0.0784165	total: 11.6s	remaining: 19.6s
371:	learn: 0.0783727	total: 11.6s	remaining: 19.6s
372:	learn: 0.0782681	total: 11.6s	remaining: 19.5s
373:	learn: 0.0781755	total: 11.7s	remaining: 19.5s
374:	learn: 0.0781503	total: 11.7s	remaining: 19.5s
375:	learn: 0.0780891	total: 11.7s	remaining: 19.4s
376:	learn: 0.0778913	total: 11.7s	remaining: 19.4s
377:	learn: 0.0777753	total: 11.8s	remaining: 19.4s
378:	learn: 0.0777591	total: 11.8s	remaining: 19.3s
379:	learn: 0.0776767	total: 11.8s	remaining: 19.3s
380:	learn: 0.0776216	total: 11.9s	remaining: 19.3s
381:	learn: 0.0775076	total: 11.9s	remaining: 19.2s
382:	learn: 0.0774432	total: 11.9s	remaining: 19.2s
383:	learn: 0.0773880	total: 12s	remaining: 19.2s
384:	learn: 0.0773790	total: 12s	remaining: 19.1s
385:	learn: 0.0773214	total: 12s	remaining: 19.1s
386:	learn: 0.0771905	total: 12s	remaining: 19.1s
387:	learn: 0.0770868	total: 12.1s	remaining: 19s

CV folds:  54%|█████▍    | 27/50 [14:16<12:13, 31.88s/fold]

998:	learn: 0.0446942	total: 31.2s	remaining: 31.2ms
999:	learn: 0.0446176	total: 31.2s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3881192	total: 24.7ms	remaining: 24.6s
1:	learn: 0.3777794	total: 54.6ms	remaining: 27.3s
2:	learn: 0.3671743	total: 84.7ms	remaining: 28.1s
3:	learn: 0.3578964	total: 112ms	remaining: 28s
4:	learn: 0.3484873	total: 142ms	remaining: 28.3s
5:	learn: 0.3396415	total: 172ms	remaining: 28.5s
6:	learn: 0.3309490	total: 202ms	remaining: 28.7s
7:	learn: 0.3224087	total: 238ms	remaining: 29.5s
8:	learn: 0.3145129	total: 273ms	remaining: 30.1s
9:	learn: 0.3064085	total: 300ms	remaining: 29.7s
10:	learn: 0.2985942	total: 330ms	remaining: 29.7s
11:	learn: 0.2915574	total: 358ms	remaining: 29.5s
12:	learn: 0.2844682	total: 391ms	remaining: 29.7s
13:	learn: 0.2778672	total: 420ms	remaining: 29.6s
14:	learn: 0.2717130	total: 450ms	remaining: 29.5s
15:	learn: 0.2660210	total: 480ms	remaining: 29.5s
16:	learn: 0.2599192	total: 511ms	remaining: 29.5s
17:	learn: 0.2541329	total: 541ms	remaining: 29.5s
18:	learn: 0.2485271	total: 570ms	remaining: 29.4s
19:	learn: 0.2434472	total: 599ms	remaining: 29.3s
20:	learn: 0.2385186	total: 629ms	remaining: 29.3s
21:	learn: 0.2334911	total: 659ms	remaining: 29.3s
22:	learn: 0.2286090	total: 693ms	remaining: 29.4s
23:	learn: 0.2243119	total: 723ms	remaining: 29.4s
24:	learn: 0.2198772	total: 752ms	remaining: 29.3s
25:	learn: 0.2155315	total: 782ms	remaining: 29.3s
26:	learn: 0.2115578	total: 812ms	remaining: 29.3s
27:	learn: 0.2076172	total: 839ms	remaining: 29.1s
28:	learn: 0.2036472	total: 870ms	remaining: 29.1s
29:	learn: 0.2001756	total: 900ms	remaining: 29.1s
30:	learn: 0.1966192	total: 931ms	remaining: 29.1s
31:	learn: 0.1935202	total: 962ms	remaining: 29.1s
32:	learn: 0.1903930	total: 991ms	remaining: 29s
33:	learn: 0.1873682	total: 1.02s	remaining: 28.9s
34:	learn: 0.1843427	total: 1.04s	remaining: 28.8s
35:	learn: 0.1815519	total: 1.07s	remaining: 28.7s
36:	learn: 0.1789970	total: 1.11s	remaining: 28.8s
37:	learn: 0.1767199	total: 1.14s	remaining: 28.9s
38:	learn: 0.1744647	total: 1.18s	remaining: 29s
39:	learn: 0.1721643	total: 1.2s	remaining: 28.9s
40:	learn: 0.1701715	total: 1.23s	remaining: 28.8s
41:	learn: 0.1680955	total: 1.26s	remaining: 28.8s
42:	learn: 0.1658597	total: 1.29s	remaining: 28.7s
43:	learn: 0.1637442	total: 1.32s	remaining: 28.7s
44:	learn: 0.1619554	total: 1.35s	remaining: 28.7s
45:	learn: 0.1601169	total: 1.38s	remaining: 28.7s
46:	learn: 0.1581812	total: 1.41s	remaining: 28.7s
47:	learn: 0.1565126	total: 1.44s	remaining: 28.6s
48:	learn: 0.1548910	total: 1.47s	remaining: 28.5s
49:	learn: 0.1534822	total: 1.49s	remaining: 28.3s
50:	learn: 0.1519910	total: 1.52s	remaining: 28.2s
51:	learn: 0.1507213	total: 1.55s	remaining: 28.2s
52:	learn: 0.1493059	total: 1.58s	remaining: 28.2s
53:	learn: 0.1477585	total: 1.61s	remaining: 28.2s
54:	learn: 0.1463539	total: 1.64s	remaining: 28.1s
55:	learn: 0.1449372	total: 1.67s	remaining: 28.1s
56:	learn: 0.1436191	total: 1.7s	remaining: 28.1s
57:	learn: 0.1423999	total: 1.73s	remaining: 28.1s
58:	learn: 0.1412058	total: 1.76s	remaining: 28.1s
59:	learn: 0.1398417	total: 1.79s	remaining: 28s
60:	learn: 0.1388223	total: 1.82s	remaining: 28s
61:	learn: 0.1377908	total: 1.85s	remaining: 28s
62:	learn: 0.1368376	total: 1.88s	remaining: 27.9s
63:	learn: 0.1359715	total: 1.91s	remaining: 27.9s
64:	learn: 0.1351156	total: 1.94s	remaining: 27.9s
65:	learn: 0.1341378	total: 1.97s	remaining: 27.8s
66:	learn: 0.1333781	total: 2s	remaining: 27.8s
67:	learn: 0.1324014	total: 2.03s	remaining: 27.8s
68:	learn: 0.1316030	total: 2.06s	remaining: 27.8s
69:	learn: 0.1307963	total: 2.08s	remaining: 27.7s
70:	learn: 0.1300412	total: 2.12s	remaining: 27.7s
71:	learn: 0.1293043	total: 2.15s	remaining: 27.7s
72:	learn: 0.1287424	total: 2.18s	remaining: 27.7s
73:	learn: 0.1280948	total: 2.21s	remaining: 27.6s
74:	learn: 0.1273036	total: 2.24s	remaining: 27.6s
75:	learn: 0.1266960	total: 2.27s	remaining: 27.5s
76:	learn: 0.1258053	total: 2.3s	remaining: 27.5s
77:	learn: 0.1251379	total: 2.32s	remaining: 27.5s
78:	learn: 0.1245012	total: 2.35s	remaining: 27.4s
79:	learn: 0.1239514	total: 2.38s	remaining: 27.4s
80:	learn: 0.1232372	total: 2.42s	remaining: 27.4s
81:	learn: 0.1226346	total: 2.45s	remaining: 27.4s
82:	learn: 0.1219348	total: 2.48s	remaining: 27.4s
83:	learn: 0.1213523	total: 2.51s	remaining: 27.3s
84:	learn: 0.1209498	total: 2.54s	remaining: 27.3s
85:	learn: 0.1204471	total: 2.56s	remaining: 27.3s
86:	learn: 0.1198727	total: 2.6s	remaining: 27.2s
87:	learn: 0.1193809	total: 2.63s	remaining: 27.2s
88:	learn: 0.1188091	total: 2.66s	remaining: 27.2s
89:	learn: 0.1182471	total: 2.69s	remaining: 27.2s
90:	learn: 0.1177992	total: 2.71s	remaining: 27.1s
91:	learn: 0.1173376	total: 2.74s	remaining: 27.1s
92:	learn: 0.1169089	total: 2.77s	remaining: 27s
93:	learn: 0.1164803	total: 2.8s	remaining: 27s
94:	learn: 0.1161121	total: 2.83s	remaining: 27s
95:	learn: 0.1156526	total: 2.86s	remaining: 26.9s
96:	learn: 0.1152776	total: 2.89s	remaining: 26.9s
97:	learn: 0.1148961	total: 2.92s	remaining: 26.9s
98:	learn: 0.1146701	total: 2.95s	remaining: 26.9s
99:	learn: 0.1143278	total: 2.98s	remaining: 26.8s
100:	learn: 0.1139333	total: 3.01s	remaining: 26.8s
101:	learn: 0.1135699	total: 3.04s	remaining: 26.7s
102:	learn: 0.1132278	total: 3.07s	remaining: 26.7s
103:	learn: 0.1128981	total: 3.12s	remaining: 26.9s
104:	learn: 0.1126032	total: 3.15s	remaining: 26.8s
105:	learn: 0.1122147	total: 3.18s	remaining: 26.8s
106:	learn: 0.1119853	total: 3.2s	remaining: 26.7s
107:	learn: 0.1116512	total: 3.23s	remaining: 26.7s
108:	learn: 0.1113394	total: 3.26s	remaining: 26.7s
109:	learn: 0.1111229	total: 3.3s	remaining: 26.7s
110:	learn: 0.1107396	total: 3.35s	remaining: 26.9s
111:	learn: 0.1104154	total: 3.38s	remaining: 26.8s
112:	learn: 0.1100810	total: 3.41s	remaining: 26.8s
113:	learn: 0.1097801	total: 3.44s	remaining: 26.8s
114:	learn: 0.1094838	total: 3.47s	remaining: 26.7s
115:	learn: 0.1091501	total: 3.5s	remaining: 26.7s
116:	learn: 0.1089899	total: 3.53s	remaining: 26.7s
117:	learn: 0.1087522	total: 3.56s	remaining: 26.6s
118:	learn: 0.1084266	total: 3.59s	remaining: 26.6s
119:	learn: 0.1081260	total: 3.62s	remaining: 26.6s
120:	learn: 0.1078979	total: 3.66s	remaining: 26.6s
121:	learn: 0.1076418	total: 3.69s	remaining: 26.5s
122:	learn: 0.1072242	total: 3.72s	remaining: 26.5s
123:	learn: 0.1068718	total: 3.75s	remaining: 26.5s
124:	learn: 0.1065123	total: 3.79s	remaining: 26.5s
125:	learn: 0.1061461	total: 3.83s	remaining: 26.6s
126:	learn: 0.1057710	total: 3.87s	remaining: 26.6s
127:	learn: 0.1056092	total: 3.91s	remaining: 26.6s
128:	learn: 0.1053227	total: 3.95s	remaining: 26.7s
129:	learn: 0.1048542	total: 3.97s	remaining: 26.6s
130:	learn: 0.1044228	total: 4s	remaining: 26.6s
131:	learn: 0.1042023	total: 4.03s	remaining: 26.5s
132:	learn: 0.1038342	total: 4.07s	remaining: 26.5s
133:	learn: 0.1036830	total: 4.1s	remaining: 26.5s
134:	learn: 0.1034298	total: 4.14s	remaining: 26.5s
135:	learn: 0.1031674	total: 4.17s	remaining: 26.5s
136:	learn: 0.1029225	total: 4.2s	remaining: 26.5s
137:	learn: 0.1026373	total: 4.23s	remaining: 26.4s
138:	learn: 0.1024282	total: 4.26s	remaining: 26.4s
139:	learn: 0.1022273	total: 4.3s	remaining: 26.4s
140:	learn: 0.1019772	total: 4.33s	remaining: 26.4s
141:	learn: 0.1017828	total: 4.36s	remaining: 26.4s
142:	learn: 0.1015089	total: 4.39s	remaining: 26.3s
143:	learn: 0.1012656	total: 4.44s	remaining: 26.4s
144:	learn: 0.1012015	total: 4.46s	remaining: 26.3s
145:	learn: 0.1009923	total: 4.49s	remaining: 26.2s
146:	learn: 0.1007847	total: 4.52s	remaining: 26.2s
147:	learn: 0.1005608	total: 4.55s	remaining: 26.2s
148:	learn: 0.1003304	total: 4.58s	remaining: 26.2s
149:	learn: 0.1000798	total: 4.61s	remaining: 26.1s
150:	learn: 0.0998264	total: 4.64s	remaining: 26.1s
151:	learn: 0.0996826	total: 4.67s	remaining: 26.1s
152:	learn: 0.0995619	total: 4.71s	remaining: 26.1s
153:	learn: 0.0994113	total: 4.74s	remaining: 26s
154:	learn: 0.0991927	total: 4.77s	remaining: 26s
155:	learn: 0.0990562	total: 4.8s	remaining: 26s
156:	learn: 0.0988287	total: 4.82s	remaining: 25.9s
157:	learn: 0.0986538	total: 4.85s	remaining: 25.9s
158:	learn: 0.0984421	total: 4.88s	remaining: 25.8s
159:	learn: 0.0982821	total: 4.92s	remaining: 25.9s
160:	learn: 0.0981636	total: 4.96s	remaining: 25.9s
161:	learn: 0.0979287	total: 5s	remaining: 25.9s
162:	learn: 0.0977654	total: 5.03s	remaining: 25.8s
163:	learn: 0.0975100	total: 5.06s	remaining: 25.8s
164:	learn: 0.0972929	total: 5.1s	remaining: 25.8s
165:	learn: 0.0971681	total: 5.13s	remaining: 25.8s
166:	learn: 0.0970454	total: 5.16s	remaining: 25.7s
167:	learn: 0.0969099	total: 5.19s	remaining: 25.7s
168:	learn: 0.0967740	total: 5.22s	remaining: 25.7s
169:	learn: 0.0966594	total: 5.25s	remaining: 25.6s
170:	learn: 0.0963914	total: 5.28s	remaining: 25.6s
171:	learn: 0.0962644	total: 5.31s	remaining: 25.6s
172:	learn: 0.0960742	total: 5.34s	remaining: 25.5s
173:	learn: 0.0959608	total: 5.37s	remaining: 25.5s
174:	learn: 0.0958541	total: 5.4s	remaining: 25.5s
175:	learn: 0.0956789	total: 5.45s	remaining: 25.5s
176:	learn: 0.0955133	total: 5.5s	remaining: 25.6s
177:	learn: 0.0954136	total: 5.54s	remaining: 25.6s
178:	learn: 0.0952527	total: 5.58s	remaining: 25.6s
179:	learn: 0.0951033	total: 5.62s	remaining: 25.6s
180:	learn: 0.0950104	total: 5.67s	remaining: 25.6s
181:	learn: 0.0949218	total: 5.69s	remaining: 25.6s
182:	learn: 0.0947299	total: 5.72s	remaining: 25.5s
183:	learn: 0.0946293	total: 5.75s	remaining: 25.5s
184:	learn: 0.0945330	total: 5.77s	remaining: 25.4s
185:	learn: 0.0942891	total: 5.8s	remaining: 25.4s
186:	learn: 0.0942251	total: 5.85s	remaining: 25.4s
187:	learn: 0.0940955	total: 5.88s	remaining: 25.4s
188:	learn: 0.0938079	total: 5.91s	remaining: 25.4s
189:	learn: 0.0937102	total: 5.94s	remaining: 25.3s
190:	learn: 0.0936331	total: 5.97s	remaining: 25.3s
191:	learn: 0.0935228	total: 6s	remaining: 25.3s
192:	learn: 0.0933033	total: 6.04s	remaining: 25.3s
193:	learn: 0.0929290	total: 6.07s	remaining: 25.2s
194:	learn: 0.0928130	total: 6.1s	remaining: 25.2s
195:	learn: 0.0927184	total: 6.13s	remaining: 25.1s
196:	learn: 0.0924243	total: 6.16s	remaining: 25.1s
197:	learn: 0.0923549	total: 6.18s	remaining: 25.1s
198:	learn: 0.0922937	total: 6.21s	remaining: 25s
199:	learn: 0.0922364	total: 6.24s	remaining: 25s
200:	learn: 0.0921287	total: 6.27s	remaining: 24.9s
201:	learn: 0.0919661	total: 6.3s	remaining: 24.9s
202:	learn: 0.0919140	total: 6.33s	remaining: 24.9s
203:	learn: 0.0917804	total: 6.37s	remaining: 24.8s
204:	learn: 0.0915271	total: 6.4s	remaining: 24.8s
205:	learn: 0.0914040	total: 6.43s	remaining: 24.8s
206:	learn: 0.0913435	total: 6.46s	remaining: 24.7s
207:	learn: 0.0911996	total: 6.48s	remaining: 24.7s
208:	learn: 0.0910236	total: 6.51s	remaining: 24.7s
209:	learn: 0.0907577	total: 6.54s	remaining: 24.6s
210:	learn: 0.0905996	total: 6.57s	remaining: 24.6s
211:	learn: 0.0904351	total: 6.6s	remaining: 24.5s
212:	learn: 0.0903494	total: 6.63s	remaining: 24.5s
213:	learn: 0.0903069	total: 6.66s	remaining: 24.5s
214:	learn: 0.0901020	total: 6.7s	remaining: 24.4s
215:	learn: 0.0899457	total: 6.73s	remaining: 24.4s
216:	learn: 0.0898717	total: 6.75s	remaining: 24.4s
217:	learn: 0.0898285	total: 6.78s	remaining: 24.3s
218:	learn: 0.0896974	total: 6.81s	remaining: 24.3s
219:	learn: 0.0895502	total: 6.84s	remaining: 24.3s
220:	learn: 0.0893657	total: 6.88s	remaining: 24.2s
221:	learn: 0.0892528	total: 6.91s	remaining: 24.2s
222:	learn: 0.0890056	total: 6.94s	remaining: 24.2s
223:	learn: 0.0888610	total: 6.97s	remaining: 24.1s
224:	learn: 0.0886620	total: 7s	remaining: 24.1s
225:	learn: 0.0885971	total: 7.03s	remaining: 24.1s
226:	learn: 0.0884169	total: 7.06s	remaining: 24s
227:	learn: 0.0882661	total: 7.09s	remaining: 24s
228:	learn: 0.0882443	total: 7.12s	remaining: 24s
229:	learn: 0.0880541	total: 7.17s	remaining: 24s
230:	learn: 0.0879225	total: 7.19s	remaining: 23.9s
231:	learn: 0.0878715	total: 7.22s	remaining: 23.9s
232:	learn: 0.0878255	total: 7.26s	remaining: 23.9s
233:	learn: 0.0877740	total: 7.29s	remaining: 23.9s
234:	learn: 0.0877261	total: 7.32s	remaining: 23.8s
235:	learn: 0.0877053	total: 7.36s	remaining: 23.8s
236:	learn: 0.0876681	total: 7.39s	remaining: 23.8s
237:	learn: 0.0875382	total: 7.42s	remaining: 23.8s
238:	learn: 0.0875031	total: 7.45s	remaining: 23.7s
239:	learn: 0.0873068	total: 7.47s	remaining: 23.7s
240:	learn: 0.0871620	total: 7.5s	remaining: 23.6s
241:	learn: 0.0870011	total: 7.54s	remaining: 23.6s
242:	learn: 0.0869648	total: 7.57s	remaining: 23.6s
243:	learn: 0.0869219	total: 7.62s	remaining: 23.6s
244:	learn: 0.0867809	total: 7.65s	remaining: 23.6s
245:	learn: 0.0866622	total: 7.67s	remaining: 23.5s
246:	learn: 0.0866134	total: 7.71s	remaining: 23.5s
247:	learn: 0.0864083	total: 7.74s	remaining: 23.5s
248:	learn: 0.0863141	total: 7.77s	remaining: 23.4s
249:	learn: 0.0862329	total: 7.8s	remaining: 23.4s
250:	learn: 0.0860755	total: 7.83s	remaining: 23.4s
251:	learn: 0.0859299	total: 7.86s	remaining: 23.3s
252:	learn: 0.0858341	total: 7.89s	remaining: 23.3s
253:	learn: 0.0857855	total: 7.92s	remaining: 23.3s
254:	learn: 0.0857581	total: 7.95s	remaining: 23.2s
255:	learn: 0.0856728	total: 7.98s	remaining: 23.2s
256:	learn: 0.0856552	total: 8.01s	remaining: 23.2s
257:	learn: 0.0856224	total: 8.04s	remaining: 23.1s
258:	learn: 0.0854100	total: 8.07s	remaining: 23.1s
259:	learn: 0.0853307	total: 8.11s	remaining: 23.1s
260:	learn: 0.0851821	total: 8.14s	remaining: 23.1s
261:	learn: 0.0850398	total: 8.17s	remaining: 23s
262:	learn: 0.0849105	total: 8.2s	remaining: 23s
263:	learn: 0.0848882	total: 8.23s	remaining: 23s
264:	learn: 0.0848674	total: 8.27s	remaining: 22.9s
265:	learn: 0.0848212	total: 8.3s	remaining: 22.9s
266:	learn: 0.0847209	total: 8.34s	remaining: 22.9s
267:	learn: 0.0846484	total: 8.37s	remaining: 22.8s
268:	learn: 0.0845994	total: 8.4s	remaining: 22.8s
269:	learn: 0.0845742	total: 8.43s	remaining: 22.8s
270:	learn: 0.0845537	total: 8.46s	remaining: 22.8s
271:	learn: 0.0845287	total: 8.49s	remaining: 22.7s
272:	learn: 0.0844353	total: 8.52s	remaining: 22.7s
273:	learn: 0.0843073	total: 8.55s	remaining: 22.7s
274:	learn: 0.0842811	total: 8.58s	remaining: 22.6s
275:	learn: 0.0841008	total: 8.61s	remaining: 22.6s
276:	learn: 0.0839955	total: 8.64s	remaining: 22.5s
277:	learn: 0.0839447	total: 8.67s	remaining: 22.5s
278:	learn: 0.0839015	total: 8.7s	remaining: 22.5s
279:	learn: 0.0838319	total: 8.72s	remaining: 22.4s
280:	learn: 0.0837915	total: 8.75s	remaining: 22.4s
281:	learn: 0.0836044	total: 8.78s	remaining: 22.4s
282:	learn: 0.0835818	total: 8.82s	remaining: 22.3s
283:	learn: 0.0834743	total: 8.84s	remaining: 22.3s
284:	learn: 0.0834266	total: 8.87s	remaining: 22.3s
285:	learn: 0.0833558	total: 8.91s	remaining: 22.2s
286:	learn: 0.0832798	total: 8.94s	remaining: 22.2s
287:	learn: 0.0832288	total: 8.97s	remaining: 22.2s
288:	learn: 0.0831202	total: 9s	remaining: 22.1s
289:	learn: 0.0829795	total: 9.03s	remaining: 22.1s
290:	learn: 0.0829249	total: 9.06s	remaining: 22.1s
291:	learn: 0.0827951	total: 9.09s	remaining: 22.1s
292:	learn: 0.0827333	total: 9.12s	remaining: 22s
293:	learn: 0.0826542	total: 9.15s	remaining: 22s
294:	learn: 0.0826325	total: 9.19s	remaining: 22s
295:	learn: 0.0826055	total: 9.21s	remaining: 21.9s
296:	learn: 0.0824524	total: 9.24s	remaining: 21.9s
297:	learn: 0.0823758	total: 9.27s	remaining: 21.8s
298:	learn: 0.0823454	total: 9.31s	remaining: 21.8s
299:	learn: 0.0822761	total: 9.34s	remaining: 21.8s
300:	learn: 0.0821564	total: 9.38s	remaining: 21.8s
301:	learn: 0.0821294	total: 9.41s	remaining: 21.7s
302:	learn: 0.0819637	total: 9.44s	remaining: 21.7s
303:	learn: 0.0818275	total: 9.47s	remaining: 21.7s
304:	learn: 0.0817552	total: 9.5s	remaining: 21.7s
305:	learn: 0.0815909	total: 9.55s	remaining: 21.7s
306:	learn: 0.0815806	total: 9.58s	remaining: 21.6s
307:	learn: 0.0814972	total: 9.61s	remaining: 21.6s
308:	learn: 0.0813807	total: 9.63s	remaining: 21.5s
309:	learn: 0.0812458	total: 9.66s	remaining: 21.5s
310:	learn: 0.0812270	total: 9.69s	remaining: 21.5s
311:	learn: 0.0809785	total: 9.72s	remaining: 21.4s
312:	learn: 0.0809625	total: 9.76s	remaining: 21.4s
313:	learn: 0.0808505	total: 9.8s	remaining: 21.4s
314:	learn: 0.0808312	total: 9.83s	remaining: 21.4s
315:	learn: 0.0806766	total: 9.86s	remaining: 21.3s
316:	learn: 0.0805193	total: 9.89s	remaining: 21.3s
317:	learn: 0.0804986	total: 9.92s	remaining: 21.3s
318:	learn: 0.0803626	total: 9.95s	remaining: 21.2s
319:	learn: 0.0802812	total: 9.98s	remaining: 21.2s
320:	learn: 0.0801651	total: 10s	remaining: 21.2s
321:	learn: 0.0801370	total: 10s	remaining: 21.1s
322:	learn: 0.0800908	total: 10.1s	remaining: 21.1s
323:	learn: 0.0800529	total: 10.1s	remaining: 21.1s
324:	learn: 0.0799670	total: 10.1s	remaining: 21.1s
325:	learn: 0.0799094	total: 10.2s	remaining: 21s
326:	learn: 0.0798719	total: 10.2s	remaining: 21s
327:	learn: 0.0798561	total: 10.2s	remaining: 21s
328:	learn: 0.0798212	total: 10.3s	remaining: 20.9s
329:	learn: 0.0796433	total: 10.3s	remaining: 20.9s
330:	learn: 0.0795078	total: 10.3s	remaining: 20.9s
331:	learn: 0.0793709	total: 10.4s	remaining: 20.8s
332:	learn: 0.0793156	total: 10.4s	remaining: 20.8s
333:	learn: 0.0792842	total: 10.4s	remaining: 20.8s
334:	learn: 0.0792687	total: 10.4s	remaining: 20.7s
335:	learn: 0.0791313	total: 10.5s	remaining: 20.7s
336:	learn: 0.0790903	total: 10.5s	remaining: 20.7s
337:	learn: 0.0789752	total: 10.5s	remaining: 20.6s
338:	learn: 0.0789368	total: 10.6s	remaining: 20.6s
339:	learn: 0.0788332	total: 10.6s	remaining: 20.6s
340:	learn: 0.0788064	total: 10.6s	remaining: 20.5s
341:	learn: 0.0787060	total: 10.7s	remaining: 20.5s
342:	learn: 0.0786491	total: 10.7s	remaining: 20.5s
343:	learn: 0.0784353	total: 10.7s	remaining: 20.4s
344:	learn: 0.0783919	total: 10.7s	remaining: 20.4s
345:	learn: 0.0782484	total: 10.8s	remaining: 20.4s
346:	learn: 0.0782312	total: 10.8s	remaining: 20.3s
347:	learn: 0.0781534	total: 10.8s	remaining: 20.3s
348:	learn: 0.0780905	total: 10.9s	remaining: 20.3s
349:	learn: 0.0780658	total: 10.9s	remaining: 20.2s
350:	learn: 0.0780148	total: 10.9s	remaining: 20.2s
351:	learn: 0.0779945	total: 11s	remaining: 20.2s
352:	learn: 0.0779627	total: 11s	remaining: 20.1s
353:	learn: 0.0778516	total: 11s	remaining: 20.1s
354:	learn: 0.0777538	total: 11.1s	remaining: 20.1s
355:	learn: 0.0777124	total: 11.1s	remaining: 20s
356:	learn: 0.0776966	total: 11.1s	remaining: 20s
357:	learn: 0.0776080	total: 11.1s	remaining: 20s
358:	learn: 0.0775372	total: 11.2s	remaining: 19.9s
359:	learn: 0.0774765	total: 11.2s	remaining: 19.9s
360:	learn: 0.0774600	total: 11.2s	remaining: 19.9s
361:	learn: 0.0774423	total: 11.3s	remaining: 19.8s
362:	learn: 0.0774089	total: 11.3s	remaining: 19.8s
363:	learn: 0.0772846	total: 11.3s	remaining: 19.8s
364:	learn: 0.0772601	total: 11.4s	remaining: 19.8s
365:	learn: 0.0771586	total: 11.4s	remaining: 19.7s
366:	learn: 0.0770147	total: 11.4s	remaining: 19.7s
367:	learn: 0.0769459	total: 11.4s	remaining: 19.7s
368:	learn: 0.0767799	total: 11.5s	remaining: 19.6s
369:	learn: 0.0766849	total: 11.5s	remaining: 19.6s
370:	learn: 0.0766733	total: 11.5s	remaining: 19.6s
371:	learn: 0.0765696	total: 11.6s	remaining: 19.5s
372:	learn: 0.0764486	total: 11.6s	remaining: 19.5s
373:	learn: 0.0763262	total: 11.6s	remaining: 19.5s
374:	learn: 0.0761222	total: 11.7s	remaining: 19.4s
375:	learn: 0.0760305	total: 11.7s	remaining: 19.4s
376:	learn: 0.0759987	total: 11.7s	remaining: 19.4s
377:	learn: 0.0758669	total: 11.8s	remaining: 19.3s
378:	learn: 0.0758267	total: 11.8s	remaining: 19.3s
379:	learn: 0.0758053	total: 11.8s	remaining: 19.3s
380:	learn: 0.0757807	total: 11.8s	remaining: 19.2s
381:	learn: 0.0756717	total: 11.9s	remaining: 19.2s
382:	learn: 0.0755216	total: 11.9s	remaining: 19.2s
383:	learn: 0.0755004	total: 12s	remaining: 19.2s
384:	learn: 0.0753562	total: 12s	remaining: 19.1s
385:	learn: 0.0752294	total: 12s	remaining: 19.1s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Electrical': 1 unseen categories converted to Unseen on transform.

CV folds:  56%|█████▌    | 28/50 [14:48<11:38, 31.76s/fold]

Learning rate set to 0.042743
0:	learn: 0.3863737	total: 27.4ms	remaining: 27.4s
1:	learn: 0.3760119	total: 66.7ms	remaining: 33.3s
2:	learn: 0.3654391	total: 103ms	remaining: 34.2s
3:	learn: 0.3560792	total: 132ms	remaining: 32.8s
4:	learn: 0.3468753	total: 159ms	remaining: 31.6s
5:	learn: 0.3379498	total: 188ms	remaining: 31.1s
6:	learn: 0.3295834	total: 219ms	remaining: 31.1s
7:	learn: 0.3216640	total: 274ms	remaining: 34s
8:	learn: 0.3138919	total: 311ms	remaining: 34.2s
9:	learn: 0.3056219	total: 343ms	remaining: 34s
10:	learn: 0.2978041	total: 369ms	remaining: 33.2s
11:	learn: 0.2907263	total: 398ms	remaining: 32.8s
12:	learn: 0.2836913	total: 425ms	remaining: 32.2s
13:	learn: 0.2770081	total: 457ms	remaining: 32.2s
14:	learn: 0.2708554	total: 488ms	remaining: 32s
15:	learn: 0.2647163	total: 516ms	remaining: 31.8s
16:	learn: 0.2581167	total: 544ms	remaining: 31.5s
17:	learn: 0.2526695	total: 574ms	remaining: 31.3s
18:	learn: 0.2471722	total: 602ms	remaining: 31.1s
19:	learn: 0.2423227	total: 631ms	remaining: 30.9s
20:	learn: 0.2376641	total: 662ms	remaining: 30.8s
21:	learn: 0.2325664	total: 691ms	remaining: 30.7s
22:	learn: 0.2279584	total: 723ms	remaining: 30.7s
23:	learn: 0.2235942	total: 751ms	remaining: 30.6s
24:	learn: 0.2197682	total: 783ms	remaining: 30.5s
25:	learn: 0.2157873	total: 814ms	remaining: 30.5s
26:	learn: 0.2117822	total: 842ms	remaining: 30.3s
27:	learn: 0.2080273	total: 870ms	remaining: 30.2s
28:	learn: 0.2041634	total: 900ms	remaining: 30.1s
29:	learn: 0.2005082	total: 934ms	remaining: 30.2s
30:	learn: 0.1972767	total: 963ms	remaining: 30.1s
31:	learn: 0.1940956	total: 992ms	remaining: 30s
32:	learn: 0.1909287	total: 1.02s	remaining: 29.9s
33:	learn: 0.1880051	total: 1.05s	remaining: 29.8s
34:	learn: 0.1853329	total: 1.08s	remaining: 29.8s
35:	learn: 0.1827213	total: 1.11s	remaining: 29.8s
36:	learn: 0.1798674	total: 1.16s	remaining: 30.3s
37:	learn: 0.1774937	total: 1.19s	remaining: 30.2s
38:	learn: 0.1748235	total: 1.22s	remaining: 30.1s
39:	learn: 0.1725507	total: 1.25s	remaining: 30s
40:	learn: 0.1700629	total: 1.28s	remaining: 29.9s
41:	learn: 0.1678786	total: 1.31s	remaining: 30s
42:	learn: 0.1654090	total: 1.34s	remaining: 29.9s
43:	learn: 0.1634848	total: 1.38s	remaining: 29.9s
44:	learn: 0.1614164	total: 1.4s	remaining: 29.8s
45:	learn: 0.1595661	total: 1.43s	remaining: 29.7s
46:	learn: 0.1577882	total: 1.46s	remaining: 29.6s
47:	learn: 0.1563562	total: 1.49s	remaining: 29.5s
48:	learn: 0.1546295	total: 1.52s	remaining: 29.5s
49:	learn: 0.1528468	total: 1.55s	remaining: 29.5s
50:	learn: 0.1513107	total: 1.58s	remaining: 29.4s
51:	learn: 0.1499145	total: 1.61s	remaining: 29.3s
52:	learn: 0.1486324	total: 1.64s	remaining: 29.3s
53:	learn: 0.1475108	total: 1.67s	remaining: 29.2s
54:	learn: 0.1462481	total: 1.7s	remaining: 29.2s
55:	learn: 0.1449639	total: 1.73s	remaining: 29.2s
56:	learn: 0.1438109	total: 1.76s	remaining: 29.1s
57:	learn: 0.1426181	total: 1.79s	remaining: 29.1s
58:	learn: 0.1415343	total: 1.82s	remaining: 29s
59:	learn: 0.1403818	total: 1.85s	remaining: 29s
60:	learn: 0.1394491	total: 1.88s	remaining: 28.9s
61:	learn: 0.1384964	total: 1.91s	remaining: 28.9s
62:	learn: 0.1374158	total: 1.94s	remaining: 28.9s
63:	learn: 0.1364368	total: 1.97s	remaining: 28.8s
64:	learn: 0.1355314	total: 2s	remaining: 28.8s
65:	learn: 0.1346555	total: 2.03s	remaining: 28.7s
66:	learn: 0.1338787	total: 2.06s	remaining: 28.7s
67:	learn: 0.1331192	total: 2.09s	remaining: 28.7s
68:	learn: 0.1320150	total: 2.12s	remaining: 28.6s
69:	learn: 0.1311711	total: 2.15s	remaining: 28.6s
70:	learn: 0.1304311	total: 2.18s	remaining: 28.5s
71:	learn: 0.1294009	total: 2.22s	remaining: 28.7s
72:	learn: 0.1286293	total: 2.26s	remaining: 28.7s
73:	learn: 0.1280000	total: 2.29s	remaining: 28.6s
74:	learn: 0.1275054	total: 2.32s	remaining: 28.6s
75:	learn: 0.1267622	total: 2.35s	remaining: 28.6s
76:	learn: 0.1261615	total: 2.38s	remaining: 28.6s
77:	learn: 0.1253933	total: 2.41s	remaining: 28.5s
78:	learn: 0.1249594	total: 2.44s	remaining: 28.4s
79:	learn: 0.1243223	total: 2.47s	remaining: 28.4s
80:	learn: 0.1236072	total: 2.5s	remaining: 28.3s
81:	learn: 0.1228401	total: 2.53s	remaining: 28.3s
82:	learn: 0.1222777	total: 2.56s	remaining: 28.3s
83:	learn: 0.1217619	total: 2.59s	remaining: 28.2s
84:	learn: 0.1212458	total: 2.62s	remaining: 28.2s
85:	learn: 0.1207619	total: 2.65s	remaining: 28.1s
86:	learn: 0.1202910	total: 2.68s	remaining: 28.1s
87:	learn: 0.1198534	total: 2.71s	remaining: 28.1s
88:	learn: 0.1193616	total: 2.74s	remaining: 28.1s
89:	learn: 0.1188882	total: 2.77s	remaining: 28s
90:	learn: 0.1184231	total: 2.81s	remaining: 28s
91:	learn: 0.1179289	total: 2.84s	remaining: 28s
92:	learn: 0.1174954	total: 2.89s	remaining: 28.2s
93:	learn: 0.1171147	total: 2.92s	remaining: 28.1s
94:	learn: 0.1167836	total: 2.95s	remaining: 28.1s
95:	learn: 0.1164419	total: 2.98s	remaining: 28.1s
96:	learn: 0.1159007	total: 3.01s	remaining: 28.1s
97:	learn: 0.1155645	total: 3.04s	remaining: 28s
98:	learn: 0.1150757	total: 3.07s	remaining: 27.9s
99:	learn: 0.1147504	total: 3.1s	remaining: 27.9s
100:	learn: 0.1144134	total: 3.13s	remaining: 27.8s
101:	learn: 0.1140524	total: 3.16s	remaining: 27.8s
102:	learn: 0.1136971	total: 3.19s	remaining: 27.8s
103:	learn: 0.1132774	total: 3.22s	remaining: 27.7s
104:	learn: 0.1128485	total: 3.25s	remaining: 27.7s
105:	learn: 0.1126297	total: 3.27s	remaining: 27.6s
106:	learn: 0.1123626	total: 3.31s	remaining: 27.6s
107:	learn: 0.1121125	total: 3.33s	remaining: 27.6s
108:	learn: 0.1117889	total: 3.37s	remaining: 27.5s
109:	learn: 0.1114305	total: 3.39s	remaining: 27.5s
110:	learn: 0.1109289	total: 3.42s	remaining: 27.4s
111:	learn: 0.1106151	total: 3.45s	remaining: 27.4s
112:	learn: 0.1103664	total: 3.48s	remaining: 27.4s
113:	learn: 0.1100441	total: 3.52s	remaining: 27.3s
114:	learn: 0.1097603	total: 3.55s	remaining: 27.3s
115:	learn: 0.1094157	total: 3.58s	remaining: 27.3s
116:	learn: 0.1091010	total: 3.61s	remaining: 27.2s
117:	learn: 0.1088011	total: 3.64s	remaining: 27.2s
118:	learn: 0.1085712	total: 3.67s	remaining: 27.2s
119:	learn: 0.1084303	total: 3.7s	remaining: 27.1s
120:	learn: 0.1081227	total: 3.73s	remaining: 27.1s
121:	learn: 0.1077465	total: 3.77s	remaining: 27.1s
122:	learn: 0.1073611	total: 3.79s	remaining: 27s
123:	learn: 0.1071227	total: 3.83s	remaining: 27s
124:	learn: 0.1068253	total: 3.85s	remaining: 27s
125:	learn: 0.1065972	total: 3.88s	remaining: 26.9s
126:	learn: 0.1063770	total: 3.91s	remaining: 26.9s
127:	learn: 0.1061967	total: 3.94s	remaining: 26.9s
128:	learn: 0.1060032	total: 3.98s	remaining: 26.8s
129:	learn: 0.1058544	total: 4.01s	remaining: 26.8s
130:	learn: 0.1055373	total: 4.04s	remaining: 26.8s
131:	learn: 0.1051979	total: 4.07s	remaining: 26.8s
132:	learn: 0.1049366	total: 4.1s	remaining: 26.7s
133:	learn: 0.1047784	total: 4.13s	remaining: 26.7s
134:	learn: 0.1045237	total: 4.16s	remaining: 26.6s
135:	learn: 0.1043422	total: 4.19s	remaining: 26.6s
136:	learn: 0.1040080	total: 4.22s	remaining: 26.6s
137:	learn: 0.1037753	total: 4.25s	remaining: 26.6s
138:	learn: 0.1035685	total: 4.29s	remaining: 26.5s
139:	learn: 0.1034434	total: 4.32s	remaining: 26.5s
140:	learn: 0.1033346	total: 4.34s	remaining: 26.5s
141:	learn: 0.1031356	total: 4.39s	remaining: 26.5s
142:	learn: 0.1028828	total: 4.43s	remaining: 26.6s
143:	learn: 0.1027242	total: 4.46s	remaining: 26.5s
144:	learn: 0.1025704	total: 4.49s	remaining: 26.5s
145:	learn: 0.1022466	total: 4.52s	remaining: 26.5s
146:	learn: 0.1020209	total: 4.55s	remaining: 26.4s
147:	learn: 0.1018487	total: 4.59s	remaining: 26.4s
148:	learn: 0.1017352	total: 4.62s	remaining: 26.4s
149:	learn: 0.1016730	total: 4.65s	remaining: 26.3s
150:	learn: 0.1014839	total: 4.67s	remaining: 26.3s
151:	learn: 0.1012837	total: 4.71s	remaining: 26.3s
152:	learn: 0.1010502	total: 4.74s	remaining: 26.3s
153:	learn: 0.1008732	total: 4.77s	remaining: 26.2s
154:	learn: 0.1007408	total: 4.8s	remaining: 26.2s
155:	learn: 0.1005562	total: 4.83s	remaining: 26.1s
156:	learn: 0.1003935	total: 4.86s	remaining: 26.1s
157:	learn: 0.1001890	total: 4.89s	remaining: 26.1s
158:	learn: 0.1000134	total: 4.92s	remaining: 26s
159:	learn: 0.0998842	total: 4.95s	remaining: 26s
160:	learn: 0.0996877	total: 4.98s	remaining: 25.9s
161:	learn: 0.0995577	total: 5.01s	remaining: 25.9s
162:	learn: 0.0994130	total: 5.04s	remaining: 25.9s
163:	learn: 0.0992508	total: 5.07s	remaining: 25.8s
164:	learn: 0.0991489	total: 5.1s	remaining: 25.8s
165:	learn: 0.0990112	total: 5.13s	remaining: 25.8s
166:	learn: 0.0988889	total: 5.16s	remaining: 25.7s
167:	learn: 0.0985797	total: 5.19s	remaining: 25.7s
168:	learn: 0.0984450	total: 5.22s	remaining: 25.7s
169:	learn: 0.0983081	total: 5.25s	remaining: 25.6s
170:	learn: 0.0981165	total: 5.28s	remaining: 25.6s
171:	learn: 0.0979346	total: 5.31s	remaining: 25.6s
172:	learn: 0.0978169	total: 5.34s	remaining: 25.5s
173:	learn: 0.0975792	total: 5.37s	remaining: 25.5s
174:	learn: 0.0974176	total: 5.4s	remaining: 25.5s
175:	learn: 0.0971493	total: 5.43s	remaining: 25.4s
176:	learn: 0.0969807	total: 5.46s	remaining: 25.4s
177:	learn: 0.0968542	total: 5.49s	remaining: 25.4s
178:	learn: 0.0966792	total: 5.52s	remaining: 25.3s
179:	learn: 0.0964417	total: 5.55s	remaining: 25.3s
180:	learn: 0.0963783	total: 5.58s	remaining: 25.3s
181:	learn: 0.0962845	total: 5.61s	remaining: 25.2s
182:	learn: 0.0961949	total: 5.64s	remaining: 25.2s
183:	learn: 0.0960739	total: 5.67s	remaining: 25.1s
184:	learn: 0.0958626	total: 5.7s	remaining: 25.1s
185:	learn: 0.0956932	total: 5.73s	remaining: 25.1s
186:	learn: 0.0955450	total: 5.76s	remaining: 25s
187:	learn: 0.0954531	total: 5.79s	remaining: 25s
188:	learn: 0.0952150	total: 5.82s	remaining: 25s
189:	learn: 0.0951731	total: 5.85s	remaining: 24.9s
190:	learn: 0.0949031	total: 5.88s	remaining: 24.9s
191:	learn: 0.0947334	total: 5.91s	remaining: 24.9s
192:	learn: 0.0945915	total: 5.94s	remaining: 24.8s
193:	learn: 0.0943808	total: 5.97s	remaining: 24.8s
194:	learn: 0.0941857	total: 6s	remaining: 24.8s
195:	learn: 0.0940808	total: 6.03s	remaining: 24.7s
196:	learn: 0.0939139	total: 6.06s	remaining: 24.7s
197:	learn: 0.0937234	total: 6.09s	remaining: 24.7s
198:	learn: 0.0936132	total: 6.12s	remaining: 24.6s
199:	learn: 0.0935115	total: 6.15s	remaining: 24.6s
200:	learn: 0.0934013	total: 6.18s	remaining: 24.6s
201:	learn: 0.0933063	total: 6.21s	remaining: 24.5s
202:	learn: 0.0931566	total: 6.24s	remaining: 24.5s
203:	learn: 0.0930215	total: 6.27s	remaining: 24.5s
204:	learn: 0.0928685	total: 6.3s	remaining: 24.4s
205:	learn: 0.0928171	total: 6.33s	remaining: 24.4s
206:	learn: 0.0926108	total: 6.36s	remaining: 24.4s
207:	learn: 0.0925180	total: 6.39s	remaining: 24.3s
208:	learn: 0.0923634	total: 6.42s	remaining: 24.3s
209:	learn: 0.0922801	total: 6.45s	remaining: 24.3s
210:	learn: 0.0920627	total: 6.48s	remaining: 24.2s
211:	learn: 0.0919498	total: 6.51s	remaining: 24.2s
212:	learn: 0.0919093	total: 6.55s	remaining: 24.2s
213:	learn: 0.0917730	total: 6.58s	remaining: 24.2s
214:	learn: 0.0916579	total: 6.61s	remaining: 24.1s
215:	learn: 0.0915500	total: 6.64s	remaining: 24.1s
216:	learn: 0.0913922	total: 6.67s	remaining: 24.1s
217:	learn: 0.0912280	total: 6.7s	remaining: 24s
218:	learn: 0.0911935	total: 6.73s	remaining: 24s
219:	learn: 0.0910894	total: 6.76s	remaining: 24s
220:	learn: 0.0909069	total: 6.79s	remaining: 23.9s
221:	learn: 0.0908165	total: 6.82s	remaining: 23.9s
222:	learn: 0.0907474	total: 6.85s	remaining: 23.9s
223:	learn: 0.0906653	total: 6.88s	remaining: 23.8s
224:	learn: 0.0904247	total: 6.91s	remaining: 23.8s
225:	learn: 0.0902757	total: 6.94s	remaining: 23.8s
226:	learn: 0.0901811	total: 6.97s	remaining: 23.8s
227:	learn: 0.0901577	total: 7.01s	remaining: 23.7s
228:	learn: 0.0899954	total: 7.04s	remaining: 23.7s
229:	learn: 0.0899587	total: 7.07s	remaining: 23.7s
230:	learn: 0.0898473	total: 7.09s	remaining: 23.6s
231:	learn: 0.0897558	total: 7.13s	remaining: 23.6s
232:	learn: 0.0896694	total: 7.16s	remaining: 23.6s
233:	learn: 0.0894917	total: 7.18s	remaining: 23.5s
234:	learn: 0.0892854	total: 7.22s	remaining: 23.5s
235:	learn: 0.0891636	total: 7.25s	remaining: 23.5s
236:	learn: 0.0890139	total: 7.28s	remaining: 23.4s
237:	learn: 0.0889368	total: 7.31s	remaining: 23.4s
238:	learn: 0.0888224	total: 7.34s	remaining: 23.4s
239:	learn: 0.0885965	total: 7.37s	remaining: 23.3s
240:	learn: 0.0884165	total: 7.4s	remaining: 23.3s
241:	learn: 0.0882446	total: 7.42s	remaining: 23.3s
242:	learn: 0.0881294	total: 7.45s	remaining: 23.2s
243:	learn: 0.0880822	total: 7.48s	remaining: 23.2s
244:	learn: 0.0880487	total: 7.51s	remaining: 23.1s
245:	learn: 0.0879872	total: 7.54s	remaining: 23.1s
246:	learn: 0.0878777	total: 7.58s	remaining: 23.1s
247:	learn: 0.0877533	total: 7.6s	remaining: 23.1s
248:	learn: 0.0876812	total: 7.63s	remaining: 23s
249:	learn: 0.0875990	total: 7.66s	remaining: 23s
250:	learn: 0.0874763	total: 7.7s	remaining: 23s
251:	learn: 0.0874256	total: 7.73s	remaining: 22.9s
252:	learn: 0.0873650	total: 7.76s	remaining: 22.9s
253:	learn: 0.0872824	total: 7.79s	remaining: 22.9s
254:	learn: 0.0871794	total: 7.81s	remaining: 22.8s
255:	learn: 0.0871286	total: 7.84s	remaining: 22.8s
256:	learn: 0.0869875	total: 7.87s	remaining: 22.8s
257:	learn: 0.0869333	total: 7.91s	remaining: 22.7s
258:	learn: 0.0867819	total: 7.94s	remaining: 22.7s
259:	learn: 0.0867676	total: 7.97s	remaining: 22.7s
260:	learn: 0.0867203	total: 8s	remaining: 22.6s
261:	learn: 0.0866077	total: 8.03s	remaining: 22.6s
262:	learn: 0.0864618	total: 8.06s	remaining: 22.6s
263:	learn: 0.0863200	total: 8.09s	remaining: 22.6s
264:	learn: 0.0861704	total: 8.12s	remaining: 22.5s
265:	learn: 0.0861404	total: 8.15s	remaining: 22.5s
266:	learn: 0.0859376	total: 8.18s	remaining: 22.5s
267:	learn: 0.0859250	total: 8.21s	remaining: 22.4s
268:	learn: 0.0858288	total: 8.24s	remaining: 22.4s
269:	learn: 0.0858166	total: 8.27s	remaining: 22.4s
270:	learn: 0.0857542	total: 8.3s	remaining: 22.3s
271:	learn: 0.0857400	total: 8.34s	remaining: 22.3s
272:	learn: 0.0855432	total: 8.37s	remaining: 22.3s
273:	learn: 0.0853827	total: 8.39s	remaining: 22.2s
274:	learn: 0.0853177	total: 8.43s	remaining: 22.2s
275:	learn: 0.0852493	total: 8.46s	remaining: 22.2s
276:	learn: 0.0851785	total: 8.49s	remaining: 22.2s
277:	learn: 0.0851626	total: 8.52s	remaining: 22.1s
278:	learn: 0.0850748	total: 8.55s	remaining: 22.1s
279:	learn: 0.0848418	total: 8.58s	remaining: 22.1s
280:	learn: 0.0847961	total: 8.61s	remaining: 22s
281:	learn: 0.0846533	total: 8.64s	remaining: 22s
282:	learn: 0.0845198	total: 8.72s	remaining: 22.1s
283:	learn: 0.0844163	total: 8.75s	remaining: 22.1s
284:	learn: 0.0843163	total: 8.77s	remaining: 22s
285:	learn: 0.0842455	total: 8.81s	remaining: 22s
286:	learn: 0.0842290	total: 8.84s	remaining: 22s
287:	learn: 0.0840656	total: 8.87s	remaining: 21.9s
288:	learn: 0.0840504	total: 8.89s	remaining: 21.9s
289:	learn: 0.0838731	total: 8.93s	remaining: 21.9s
290:	learn: 0.0837330	total: 8.96s	remaining: 21.8s
291:	learn: 0.0836638	total: 8.99s	remaining: 21.8s
292:	learn: 0.0835113	total: 9.03s	remaining: 21.8s
293:	learn: 0.0833675	total: 9.06s	remaining: 21.8s
294:	learn: 0.0833457	total: 9.09s	remaining: 21.7s
295:	learn: 0.0831990	total: 9.12s	remaining: 21.7s
296:	learn: 0.0831041	total: 9.15s	remaining: 21.7s
297:	learn: 0.0830853	total: 9.18s	remaining: 21.6s
298:	learn: 0.0830747	total: 9.22s	remaining: 21.6s
299:	learn: 0.0830124	total: 9.25s	remaining: 21.6s
300:	learn: 0.0829962	total: 9.28s	remaining: 21.5s
301:	learn: 0.0829805	total: 9.31s	remaining: 21.5s
302:	learn: 0.0829349	total: 9.34s	remaining: 21.5s
303:	learn: 0.0828789	total: 9.37s	remaining: 21.4s
304:	learn: 0.0828679	total: 9.4s	remaining: 21.4s
305:	learn: 0.0827140	total: 9.43s	remaining: 21.4s
306:	learn: 0.0826148	total: 9.46s	remaining: 21.3s
307:	learn: 0.0825108	total: 9.48s	remaining: 21.3s
308:	learn: 0.0824942	total: 9.52s	remaining: 21.3s
309:	learn: 0.0823918	total: 9.54s	remaining: 21.2s
310:	learn: 0.0822653	total: 9.57s	remaining: 21.2s
311:	learn: 0.0822493	total: 9.6s	remaining: 21.2s
312:	learn: 0.0820883	total: 9.64s	remaining: 21.2s
313:	learn: 0.0819644	total: 9.67s	remaining: 21.1s
314:	learn: 0.0818826	total: 9.7s	remaining: 21.1s
315:	learn: 0.0817969	total: 9.73s	remaining: 21.1s
316:	learn: 0.0817360	total: 9.76s	remaining: 21s
317:	learn: 0.0816318	total: 9.79s	remaining: 21s
318:	learn: 0.0815192	total: 9.81s	remaining: 21s
319:	learn: 0.0814171	total: 9.85s	remaining: 20.9s
320:	learn: 0.0813347	total: 9.88s	remaining: 20.9s
321:	learn: 0.0811393	total: 9.91s	remaining: 20.9s
322:	learn: 0.0811203	total: 9.94s	remaining: 20.8s
323:	learn: 0.0810798	total: 9.97s	remaining: 20.8s
324:	learn: 0.0809961	total: 10s	remaining: 20.8s
325:	learn: 0.0809782	total: 10s	remaining: 20.7s
326:	learn: 0.0809679	total: 10.1s	remaining: 20.7s
327:	learn: 0.0808689	total: 10.1s	remaining: 20.7s
328:	learn: 0.0808588	total: 10.1s	remaining: 20.7s
329:	learn: 0.0808082	total: 10.2s	remaining: 20.6s
330:	learn: 0.0806751	total: 10.2s	remaining: 20.6s
331:	learn: 0.0806639	total: 10.2s	remaining: 20.6s
332:	learn: 0.0806552	total: 10.3s	remaining: 20.6s
333:	learn: 0.0806130	total: 10.3s	remaining: 20.5s
334:	learn: 0.0805947	total: 10.3s	remaining: 20.5s
335:	learn: 0.0804520	total: 10.4s	remaining: 20.5s
336:	learn: 0.0804351	total: 10.4s	remaining: 20.4s
337:	learn: 0.0802871	total: 10.4s	remaining: 20.4s
338:	learn: 0.0800869	total: 10.4s	remaining: 20.4s
339:	learn: 0.0799437	total: 10.5s	remaining: 20.3s
340:	learn: 0.0799247	total: 10.5s	remaining: 20.3s
341:	learn: 0.0798447	total: 10.5s	remaining: 20.3s
342:	learn: 0.0798289	total: 10.6s	remaining: 20.2s
343:	learn: 0.0798109	total: 10.6s	remaining: 20.2s
344:	learn: 0.0797921	total: 10.6s	remaining: 20.2s
345:	learn: 0.0797752	total: 10.7s	remaining: 20.1s
346:	learn: 0.0796786	total: 10.7s	remaining: 20.1s
347:	learn: 0.0795505	total: 10.7s	remaining: 20.1s
348:	learn: 0.0794693	total: 10.7s	remaining: 20s
349:	learn: 0.0794303	total: 10.8s	remaining: 20s
350:	learn: 0.0794194	total: 10.8s	remaining: 20s
351:	learn: 0.0793521	total: 10.9s	remaining: 20s
352:	learn: 0.0793350	total: 10.9s	remaining: 20s
353:	learn: 0.0793162	total: 10.9s	remaining: 19.9s
354:	learn: 0.0791712	total: 11s	remaining: 19.9s
355:	learn: 0.0790088	total: 11s	remaining: 19.9s
356:	learn: 0.0789714	total: 11s	remaining: 19.8s
357:	learn: 0.0788773	total: 11s	remaining: 19.8s
358:	learn: 0.0787545	total: 11.1s	remaining: 19.8s
359:	learn: 0.0786855	total: 11.1s	remaining: 19.7s
360:	learn: 0.0785670	total: 11.1s	remaining: 19.7s
361:	learn: 0.0785127	total: 11.2s	remaining: 19.7s
362:	learn: 0.0784972	total: 11.2s	remaining: 19.7s
363:	learn: 0.0783578	total: 11.2s	remaining: 19.6s
364:	learn: 0.0783320	total: 11.3s	remaining: 19.6s
365:	learn: 0.0783140	total: 11.3s	remaining: 19.6s
366:	learn: 0.0783009	total: 11.3s	remaining: 19.5s
367:	learn: 0.0782789	total: 11.3s	remaining: 19.5s
368:	learn: 0.0781550	total: 11.4s	remaining: 19.5s
369:	learn: 0.0781333	total: 11.4s	remaining: 19.4s
370:	learn: 0.0778716	total: 11.4s	remaining: 19.4s
371:	learn: 0.0778005	total: 11.5s	remaining: 19.4s
372:	learn: 0.0777884	total: 11.5s	remaining: 19.3s
373:	learn: 0.0776732	total: 11.5s	remaining: 19.3s
374:	learn: 0.0775763	total: 11.6s	remaining: 19.3s
375:	learn: 0.0775618	total: 11.6s	remaining: 19.3s
376:	learn: 0.0775414	total: 11.6s	remaining: 19.2s
377:	learn: 0.0775261	total: 11.7s	remaining: 19.2s
378:	learn: 0.0774826	total: 11.7s	remaining: 19.2s
379:	learn: 0.0773019	total: 11.7s	remaining: 19.1s
380:	learn: 0.0772736	total: 11.7s	remaining: 19.1s
381:	learn: 0.0772643	total: 11.8s	remaining: 19.1s
382:	learn: 0.0772471	total: 11.8s	remaining: 19s
383:	learn: 0.0772360	total: 11.8s	remaining: 19s
384:	learn: 0.0771486	total: 11.9s	remaining: 19s
385:	learn: 0.0770308	total: 11.9s	remaining: 18.9s
386:	learn: 0.0769766	total: 11.9s	remaining: 18.9s
387:	learn: 0.0769142	total: 12s	remaining: 18.9s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior1st': 1 unseen categories converted to Unseen on transform.

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'GarageCond': 2 unseen categories converted to Unseen on transform.

CV folds:  58%|█████▊    | 29/50 [15:20<11:06, 31.73s/fold]

998:	learn: 0.0442632	total: 31.2s	remaining: 31.2ms
999:	learn: 0.0442287	total: 31.2s	remaining: 0us
Learning rate set to 0.042743
0:	learn: 0.3894021	total: 24.7ms	remaining: 24.7s
1:	learn: 0.3788844	total: 55.4ms	remaining: 27.6s
2:	learn: 0.3683121	total: 84.4ms	remaining: 28.1s
3:	learn: 0.3583670	total: 113ms	remaining: 28.2s
4:	learn: 0.3487935	total: 145ms	remaining: 28.9s
5:	learn: 0.3395854	total: 178ms	remaining: 29.5s
6:	learn: 0.3306048	total: 215ms	remaining: 30.6s
7:	learn: 0.3229223	total: 282ms	remaining: 34.9s
8:	learn: 0.3148030	total: 314ms	remaining: 34.6s
9:	learn: 0.3072035	total: 344ms	remaining: 34.1s
10:	learn: 0.2992348	total: 374ms	remaining: 33.6s
11:	learn: 0.2925999	total: 403ms	remaining: 33.2s
12:	learn: 0.2861860	total: 434ms	remaining: 32.9s
13:	learn: 0.2793372	total: 463ms	remaining: 32.6s
14:	learn: 0.2730673	total: 493ms	remaining: 32.4s
15:	learn: 0.2667203	total: 520ms	remaining: 32s
16:	learn: 0.2602665	total: 552ms	remaining: 31.9s
17:	learn: 0.2546149	total: 584ms	remaining: 31.9s
18:	learn: 0.2490704	total: 614ms	remaining: 31.7s
19:	learn: 0.2443339	total: 646ms	remaining: 31.7s
20:	learn: 0.2392963	total: 680ms	remaining: 31.7s
21:	learn: 0.2348077	total: 710ms	remaining: 31.5s
22:	learn: 0.2315379	total: 725ms	remaining: 30.8s
23:	learn: 0.2273924	total: 757ms	remaining: 30.8s
24:	learn: 0.2232117	total: 786ms	remaining: 30.6s
25:	learn: 0.2191383	total: 814ms	remaining: 30.5s
26:	learn: 0.2150519	total: 845ms	remaining: 30.4s
27:	learn: 0.2115268	total: 876ms	remaining: 30.4s
28:	learn: 0.2076372	total: 908ms	remaining: 30.4s
29:	learn: 0.2040373	total: 941ms	remaining: 30.4s
30:	learn: 0.2009266	total: 977ms	remaining: 30.5s
31:	learn: 0.1975356	total: 1s	remaining: 30.4s
32:	learn: 0.1944487	total: 1.03s	remaining: 30.3s
33:	learn: 0.1913012	total: 1.06s	remaining: 30.2s
34:	learn: 0.1885818	total: 1.09s	remaining: 30.1s
35:	learn: 0.1858499	total: 1.12s	remaining: 30s
36:	learn: 0.1830226	total: 1.15s	remaining: 30s
37:	learn: 0.1802551	total: 1.18s	remaining: 29.9s
38:	learn: 0.1776278	total: 1.21s	remaining: 29.8s
39:	learn: 0.1752393	total: 1.24s	remaining: 29.7s
40:	learn: 0.1728189	total: 1.27s	remaining: 29.7s
41:	learn: 0.1707024	total: 1.3s	remaining: 29.6s
42:	learn: 0.1685250	total: 1.33s	remaining: 29.6s
43:	learn: 0.1664083	total: 1.36s	remaining: 29.6s
44:	learn: 0.1642504	total: 1.39s	remaining: 29.6s
45:	learn: 0.1623491	total: 1.42s	remaining: 29.5s
46:	learn: 0.1608003	total: 1.45s	remaining: 29.5s
47:	learn: 0.1591232	total: 1.48s	remaining: 29.5s
48:	learn: 0.1573277	total: 1.51s	remaining: 29.4s
49:	learn: 0.1557115	total: 1.54s	remaining: 29.3s
50:	learn: 0.1542236	total: 1.57s	remaining: 29.3s
51:	learn: 0.1528378	total: 1.6s	remaining: 29.1s
52:	learn: 0.1511749	total: 1.63s	remaining: 29.1s
53:	learn: 0.1496859	total: 1.66s	remaining: 29s
54:	learn: 0.1482852	total: 1.68s	remaining: 28.9s
55:	learn: 0.1469116	total: 1.72s	remaining: 28.9s
56:	learn: 0.1457501	total: 1.75s	remaining: 28.9s
57:	learn: 0.1445302	total: 1.77s	remaining: 28.8s
58:	learn: 0.1432496	total: 1.8s	remaining: 28.8s
59:	learn: 0.1421518	total: 1.84s	remaining: 28.8s
60:	learn: 0.1411405	total: 1.86s	remaining: 28.7s
61:	learn: 0.1398871	total: 1.89s	remaining: 28.6s
62:	learn: 0.1389186	total: 1.91s	remaining: 28.4s
63:	learn: 0.1378902	total: 1.94s	remaining: 28.4s
64:	learn: 0.1369251	total: 1.97s	remaining: 28.3s
65:	learn: 0.1359578	total: 2s	remaining: 28.3s
66:	learn: 0.1349908	total: 2.03s	remaining: 28.2s
67:	learn: 0.1341102	total: 2.06s	remaining: 28.2s
68:	learn: 0.1332800	total: 2.09s	remaining: 28.1s
69:	learn: 0.1324785	total: 2.11s	remaining: 28.1s
70:	learn: 0.1317658	total: 2.14s	remaining: 28s
71:	learn: 0.1308194	total: 2.17s	remaining: 28s
72:	learn: 0.1300488	total: 2.2s	remaining: 27.9s
73:	learn: 0.1291061	total: 2.23s	remaining: 27.9s
74:	learn: 0.1283679	total: 2.26s	remaining: 27.9s
75:	learn: 0.1276406	total: 2.3s	remaining: 28s
76:	learn: 0.1270167	total: 2.33s	remaining: 27.9s
77:	learn: 0.1263578	total: 2.36s	remaining: 27.9s
78:	learn: 0.1257240	total: 2.39s	remaining: 27.8s
79:	learn: 0.1251739	total: 2.42s	remaining: 27.8s
80:	learn: 0.1246126	total: 2.45s	remaining: 27.8s
81:	learn: 0.1239961	total: 2.48s	remaining: 27.8s
82:	learn: 0.1233910	total: 2.51s	remaining: 27.7s
83:	learn: 0.1229409	total: 2.54s	remaining: 27.7s
84:	learn: 0.1224682	total: 2.57s	remaining: 27.7s
85:	learn: 0.1220136	total: 2.6s	remaining: 27.7s
86:	learn: 0.1215915	total: 2.63s	remaining: 27.6s
87:	learn: 0.1209471	total: 2.67s	remaining: 27.6s
88:	learn: 0.1203755	total: 2.69s	remaining: 27.6s
89:	learn: 0.1197169	total: 2.72s	remaining: 27.5s
90:	learn: 0.1191938	total: 2.75s	remaining: 27.5s
91:	learn: 0.1186086	total: 2.78s	remaining: 27.5s
92:	learn: 0.1181636	total: 2.81s	remaining: 27.4s
93:	learn: 0.1176925	total: 2.84s	remaining: 27.4s
94:	learn: 0.1173601	total: 2.88s	remaining: 27.4s
95:	learn: 0.1170915	total: 2.91s	remaining: 27.4s
96:	learn: 0.1166443	total: 2.95s	remaining: 27.4s
97:	learn: 0.1163525	total: 2.98s	remaining: 27.4s
98:	learn: 0.1160480	total: 3.01s	remaining: 27.4s
99:	learn: 0.1157272	total: 3.03s	remaining: 27.3s
100:	learn: 0.1152661	total: 3.06s	remaining: 27.2s
101:	learn: 0.1148894	total: 3.12s	remaining: 27.4s
102:	learn: 0.1144679	total: 3.14s	remaining: 27.4s
103:	learn: 0.1140617	total: 3.17s	remaining: 27.3s
104:	learn: 0.1137366	total: 3.21s	remaining: 27.3s
105:	learn: 0.1133980	total: 3.24s	remaining: 27.3s
106:	learn: 0.1130791	total: 3.27s	remaining: 27.3s
107:	learn: 0.1126237	total: 3.3s	remaining: 27.3s
108:	learn: 0.1122453	total: 3.33s	remaining: 27.2s
109:	learn: 0.1119459	total: 3.36s	remaining: 27.2s
110:	learn: 0.1116022	total: 3.39s	remaining: 27.1s
111:	learn: 0.1113523	total: 3.42s	remaining: 27.1s
112:	learn: 0.1110813	total: 3.45s	remaining: 27.1s
113:	learn: 0.1107435	total: 3.48s	remaining: 27.1s
114:	learn: 0.1104571	total: 3.51s	remaining: 27s
115:	learn: 0.1103372	total: 3.53s	remaining: 26.9s
116:	learn: 0.1101415	total: 3.56s	remaining: 26.9s
117:	learn: 0.1098704	total: 3.59s	remaining: 26.8s
118:	learn: 0.1095060	total: 3.62s	remaining: 26.8s
119:	learn: 0.1092516	total: 3.65s	remaining: 26.8s
120:	learn: 0.1089934	total: 3.68s	remaining: 26.8s
121:	learn: 0.1086190	total: 3.71s	remaining: 26.7s
122:	learn: 0.1084443	total: 3.75s	remaining: 26.7s
123:	learn: 0.1081958	total: 3.77s	remaining: 26.7s
124:	learn: 0.1080095	total: 3.8s	remaining: 26.6s
125:	learn: 0.1078013	total: 3.83s	remaining: 26.6s
126:	learn: 0.1075766	total: 3.86s	remaining: 26.6s
127:	learn: 0.1074325	total: 3.89s	remaining: 26.5s
128:	learn: 0.1071749	total: 3.92s	remaining: 26.5s
129:	learn: 0.1069209	total: 3.95s	remaining: 26.5s
130:	learn: 0.1066782	total: 3.98s	remaining: 26.4s
131:	learn: 0.1064782	total: 4.01s	remaining: 26.4s
132:	learn: 0.1062622	total: 4.04s	remaining: 26.3s
133:	learn: 0.1061789	total: 4.06s	remaining: 26.2s
134:	learn: 0.1059813	total: 4.08s	remaining: 26.2s
135:	learn: 0.1056240	total: 4.11s	remaining: 26.1s
136:	learn: 0.1053328	total: 4.14s	remaining: 26.1s
137:	learn: 0.1052087	total: 4.17s	remaining: 26.1s
138:	learn: 0.1050140	total: 4.21s	remaining: 26.1s
139:	learn: 0.1048731	total: 4.24s	remaining: 26.1s
140:	learn: 0.1046793	total: 4.27s	remaining: 26s
141:	learn: 0.1044994	total: 4.3s	remaining: 26s
142:	learn: 0.1043244	total: 4.34s	remaining: 26s
143:	learn: 0.1040627	total: 4.37s	remaining: 26s
144:	learn: 0.1038750	total: 4.4s	remaining: 25.9s
145:	learn: 0.1036652	total: 4.42s	remaining: 25.9s
146:	learn: 0.1034674	total: 4.46s	remaining: 25.9s
147:	learn: 0.1033258	total: 4.49s	remaining: 25.8s
148:	learn: 0.1031473	total: 4.52s	remaining: 25.8s
149:	learn: 0.1028368	total: 4.55s	remaining: 25.8s
150:	learn: 0.1026218	total: 4.58s	remaining: 25.8s
151:	learn: 0.1024211	total: 4.61s	remaining: 25.7s
152:	learn: 0.1023394	total: 4.64s	remaining: 25.7s
153:	learn: 0.1021657	total: 4.67s	remaining: 25.7s
154:	learn: 0.1019113	total: 4.7s	remaining: 25.6s
155:	learn: 0.1017012	total: 4.73s	remaining: 25.6s
156:	learn: 0.1014787	total: 4.76s	remaining: 25.6s
157:	learn: 0.1013070	total: 4.8s	remaining: 25.6s
158:	learn: 0.1011594	total: 4.83s	remaining: 25.5s
159:	learn: 0.1010172	total: 4.86s	remaining: 25.5s
160:	learn: 0.1008458	total: 4.89s	remaining: 25.5s
161:	learn: 0.1006387	total: 4.92s	remaining: 25.4s
162:	learn: 0.1002798	total: 4.95s	remaining: 25.4s
163:	learn: 0.1000444	total: 4.98s	remaining: 25.4s
164:	learn: 0.0998525	total: 5.01s	remaining: 25.3s
165:	learn: 0.0997291	total: 5.04s	remaining: 25.3s
166:	learn: 0.0995156	total: 5.06s	remaining: 25.3s
167:	learn: 0.0993358	total: 5.09s	remaining: 25.2s
168:	learn: 0.0992100	total: 5.12s	remaining: 25.2s
169:	learn: 0.0990359	total: 5.16s	remaining: 25.2s
170:	learn: 0.0989277	total: 5.18s	remaining: 25.1s
171:	learn: 0.0986790	total: 5.22s	remaining: 25.1s
172:	learn: 0.0986044	total: 5.26s	remaining: 25.1s
173:	learn: 0.0984494	total: 5.3s	remaining: 25.1s
174:	learn: 0.0982719	total: 5.33s	remaining: 25.1s
175:	learn: 0.0981649	total: 5.35s	remaining: 25.1s
176:	learn: 0.0981315	total: 5.38s	remaining: 25s
177:	learn: 0.0980038	total: 5.41s	remaining: 25s
178:	learn: 0.0978324	total: 5.44s	remaining: 25s
179:	learn: 0.0976630	total: 5.47s	remaining: 24.9s
180:	learn: 0.0975001	total: 5.5s	remaining: 24.9s
181:	learn: 0.0972866	total: 5.53s	remaining: 24.9s
182:	learn: 0.0971868	total: 5.56s	remaining: 24.8s
183:	learn: 0.0969578	total: 5.61s	remaining: 24.9s
184:	learn: 0.0967913	total: 5.64s	remaining: 24.9s
185:	learn: 0.0965426	total: 5.67s	remaining: 24.8s
186:	learn: 0.0964412	total: 5.71s	remaining: 24.8s
187:	learn: 0.0963446	total: 5.74s	remaining: 24.8s
188:	learn: 0.0963065	total: 5.77s	remaining: 24.8s
189:	learn: 0.0960609	total: 5.8s	remaining: 24.7s
190:	learn: 0.0959769	total: 5.83s	remaining: 24.7s
191:	learn: 0.0958726	total: 5.86s	remaining: 24.7s
192:	learn: 0.0957853	total: 5.89s	remaining: 24.6s
193:	learn: 0.0957464	total: 5.92s	remaining: 24.6s
194:	learn: 0.0955156	total: 5.95s	remaining: 24.6s
195:	learn: 0.0953819	total: 5.98s	remaining: 24.5s
196:	learn: 0.0952307	total: 6.01s	remaining: 24.5s
197:	learn: 0.0951155	total: 6.05s	remaining: 24.5s
198:	learn: 0.0948848	total: 6.07s	remaining: 24.5s
199:	learn: 0.0947001	total: 6.11s	remaining: 24.4s
200:	learn: 0.0944756	total: 6.13s	remaining: 24.4s
201:	learn: 0.0944379	total: 6.17s	remaining: 24.4s
202:	learn: 0.0943342	total: 6.2s	remaining: 24.3s
203:	learn: 0.0942037	total: 6.23s	remaining: 24.3s
204:	learn: 0.0939804	total: 6.26s	remaining: 24.3s
205:	learn: 0.0939490	total: 6.29s	remaining: 24.3s
206:	learn: 0.0937829	total: 6.32s	remaining: 24.2s
207:	learn: 0.0936504	total: 6.35s	remaining: 24.2s
208:	learn: 0.0934633	total: 6.38s	remaining: 24.2s
209:	learn: 0.0933742	total: 6.42s	remaining: 24.1s
210:	learn: 0.0932981	total: 6.44s	remaining: 24.1s
211:	learn: 0.0932586	total: 6.47s	remaining: 24.1s
212:	learn: 0.0930754	total: 6.5s	remaining: 24s
213:	learn: 0.0928537	total: 6.54s	remaining: 24s
214:	learn: 0.0927821	total: 6.57s	remaining: 24s
215:	learn: 0.0926343	total: 6.6s	remaining: 23.9s
216:	learn: 0.0924922	total: 6.63s	remaining: 23.9s
217:	learn: 0.0923626	total: 6.66s	remaining: 23.9s
218:	learn: 0.0923175	total: 6.69s	remaining: 23.9s
219:	learn: 0.0920859	total: 6.72s	remaining: 23.8s
220:	learn: 0.0920084	total: 6.75s	remaining: 23.8s
221:	learn: 0.0919789	total: 6.78s	remaining: 23.8s
222:	learn: 0.0919554	total: 6.81s	remaining: 23.7s
223:	learn: 0.0918843	total: 6.84s	remaining: 23.7s
224:	learn: 0.0917622	total: 6.87s	remaining: 23.7s
225:	learn: 0.0916012	total: 6.9s	remaining: 23.6s
226:	learn: 0.0914255	total: 6.94s	remaining: 23.6s
227:	learn: 0.0912967	total: 6.97s	remaining: 23.6s
228:	learn: 0.0911484	total: 7s	remaining: 23.6s
229:	learn: 0.0910180	total: 7.03s	remaining: 23.5s
230:	learn: 0.0909240	total: 7.07s	remaining: 23.5s
231:	learn: 0.0908987	total: 7.09s	remaining: 23.5s
232:	learn: 0.0907828	total: 7.13s	remaining: 23.5s
233:	learn: 0.0907448	total: 7.15s	remaining: 23.4s
234:	learn: 0.0906011	total: 7.18s	remaining: 23.4s
235:	learn: 0.0905621	total: 7.21s	remaining: 23.4s
236:	learn: 0.0904990	total: 7.25s	remaining: 23.3s
237:	learn: 0.0904730	total: 7.28s	remaining: 23.3s
238:	learn: 0.0903053	total: 7.31s	remaining: 23.3s
239:	learn: 0.0902809	total: 7.33s	remaining: 23.2s
240:	learn: 0.0900477	total: 7.36s	remaining: 23.2s
241:	learn: 0.0900139	total: 7.39s	remaining: 23.2s
242:	learn: 0.0899990	total: 7.44s	remaining: 23.2s
243:	learn: 0.0898191	total: 7.46s	remaining: 23.1s
244:	learn: 0.0896878	total: 7.5s	remaining: 23.1s
245:	learn: 0.0895961	total: 7.53s	remaining: 23.1s
246:	learn: 0.0894067	total: 7.56s	remaining: 23s
247:	learn: 0.0892497	total: 7.59s	remaining: 23s
248:	learn: 0.0892276	total: 7.62s	remaining: 23s
249:	learn: 0.0891949	total: 7.65s	remaining: 22.9s
250:	learn: 0.0891564	total: 7.69s	remaining: 22.9s
251:	learn: 0.0890106	total: 7.72s	remaining: 22.9s
252:	learn: 0.0888294	total: 7.75s	remaining: 22.9s
253:	learn: 0.0887991	total: 7.78s	remaining: 22.8s
254:	learn: 0.0886836	total: 7.81s	remaining: 22.8s
255:	learn: 0.0886646	total: 7.84s	remaining: 22.8s
256:	learn: 0.0886403	total: 7.87s	remaining: 22.7s
257:	learn: 0.0885834	total: 7.9s	remaining: 22.7s
258:	learn: 0.0884985	total: 7.92s	remaining: 22.7s
259:	learn: 0.0884707	total: 7.96s	remaining: 22.6s
260:	learn: 0.0883333	total: 7.99s	remaining: 22.6s
261:	learn: 0.0883144	total: 8.02s	remaining: 22.6s
262:	learn: 0.0881393	total: 8.05s	remaining: 22.6s
263:	learn: 0.0879850	total: 8.08s	remaining: 22.5s
264:	learn: 0.0877072	total: 8.11s	remaining: 22.5s
265:	learn: 0.0876767	total: 8.14s	remaining: 22.5s
266:	learn: 0.0874722	total: 8.17s	remaining: 22.4s
267:	learn: 0.0873519	total: 8.2s	remaining: 22.4s
268:	learn: 0.0872104	total: 8.23s	remaining: 22.4s
269:	learn: 0.0871522	total: 8.26s	remaining: 22.3s
270:	learn: 0.0871041	total: 8.29s	remaining: 22.3s
271:	learn: 0.0870219	total: 8.32s	remaining: 22.3s
272:	learn: 0.0868699	total: 8.36s	remaining: 22.3s
273:	learn: 0.0867752	total: 8.41s	remaining: 22.3s
274:	learn: 0.0867183	total: 8.44s	remaining: 22.2s
275:	learn: 0.0865831	total: 8.46s	remaining: 22.2s
276:	learn: 0.0865506	total: 8.49s	remaining: 22.2s
277:	learn: 0.0864411	total: 8.53s	remaining: 22.1s
278:	learn: 0.0863814	total: 8.55s	remaining: 22.1s
279:	learn: 0.0862151	total: 8.59s	remaining: 22.1s
280:	learn: 0.0862010	total: 8.62s	remaining: 22.1s
281:	learn: 0.0861562	total: 8.65s	remaining: 22s
282:	learn: 0.0859675	total: 8.68s	remaining: 22s
283:	learn: 0.0859308	total: 8.71s	remaining: 21.9s
284:	learn: 0.0857040	total: 8.74s	remaining: 21.9s
285:	learn: 0.0856621	total: 8.77s	remaining: 21.9s
286:	learn: 0.0855593	total: 8.81s	remaining: 21.9s
287:	learn: 0.0854000	total: 8.84s	remaining: 21.9s
288:	learn: 0.0853817	total: 8.87s	remaining: 21.8s
289:	learn: 0.0853065	total: 8.9s	remaining: 21.8s
290:	learn: 0.0850403	total: 8.93s	remaining: 21.8s
291:	learn: 0.0848792	total: 8.96s	remaining: 21.7s
292:	learn: 0.0847384	total: 8.99s	remaining: 21.7s
293:	learn: 0.0845380	total: 9.02s	remaining: 21.7s
294:	learn: 0.0844309	total: 9.05s	remaining: 21.6s
295:	learn: 0.0842639	total: 9.08s	remaining: 21.6s
296:	learn: 0.0841236	total: 9.11s	remaining: 21.6s
297:	learn: 0.0840588	total: 9.14s	remaining: 21.5s
298:	learn: 0.0840148	total: 9.16s	remaining: 21.5s
299:	learn: 0.0839529	total: 9.19s	remaining: 21.5s
300:	learn: 0.0838838	total: 9.23s	remaining: 21.4s
301:	learn: 0.0837556	total: 9.26s	remaining: 21.4s
302:	learn: 0.0836281	total: 9.29s	remaining: 21.4s
303:	learn: 0.0835000	total: 9.32s	remaining: 21.3s
304:	learn: 0.0834503	total: 9.35s	remaining: 21.3s
305:	learn: 0.0833530	total: 9.38s	remaining: 21.3s
306:	learn: 0.0832257	total: 9.4s	remaining: 21.2s
307:	learn: 0.0831267	total: 9.43s	remaining: 21.2s
308:	learn: 0.0830491	total: 9.46s	remaining: 21.2s
309:	learn: 0.0829327	total: 9.49s	remaining: 21.1s
310:	learn: 0.0828955	total: 9.53s	remaining: 21.1s
311:	learn: 0.0828063	total: 9.57s	remaining: 21.1s
312:	learn: 0.0827293	total: 9.6s	remaining: 21.1s
313:	learn: 0.0826682	total: 9.63s	remaining: 21s
314:	learn: 0.0826328	total: 9.66s	remaining: 21s
315:	learn: 0.0824983	total: 9.69s	remaining: 21s
316:	learn: 0.0823231	total: 9.72s	remaining: 20.9s
317:	learn: 0.0822198	total: 9.75s	remaining: 20.9s
318:	learn: 0.0821334	total: 9.78s	remaining: 20.9s
319:	learn: 0.0819726	total: 9.81s	remaining: 20.8s
320:	learn: 0.0818480	total: 9.84s	remaining: 20.8s
321:	learn: 0.0818291	total: 9.87s	remaining: 20.8s
322:	learn: 0.0817095	total: 9.9s	remaining: 20.8s
323:	learn: 0.0816011	total: 9.93s	remaining: 20.7s
324:	learn: 0.0815817	total: 9.96s	remaining: 20.7s
325:	learn: 0.0815514	total: 9.99s	remaining: 20.7s
326:	learn: 0.0815256	total: 10s	remaining: 20.6s
327:	learn: 0.0814624	total: 10.1s	remaining: 20.6s
328:	learn: 0.0813679	total: 10.1s	remaining: 20.6s
329:	learn: 0.0813212	total: 10.1s	remaining: 20.5s
330:	learn: 0.0810988	total: 10.2s	remaining: 20.5s
331:	learn: 0.0809828	total: 10.2s	remaining: 20.5s
332:	learn: 0.0809688	total: 10.2s	remaining: 20.5s
333:	learn: 0.0809190	total: 10.2s	remaining: 20.4s
334:	learn: 0.0807898	total: 10.3s	remaining: 20.4s
335:	learn: 0.0807609	total: 10.3s	remaining: 20.4s
336:	learn: 0.0807047	total: 10.3s	remaining: 20.3s
337:	learn: 0.0806866	total: 10.4s	remaining: 20.3s
338:	learn: 0.0806014	total: 10.4s	remaining: 20.3s
339:	learn: 0.0805777	total: 10.4s	remaining: 20.2s
340:	learn: 0.0805322	total: 10.5s	remaining: 20.2s
341:	learn: 0.0804041	total: 10.5s	remaining: 20.2s
342:	learn: 0.0802692	total: 10.5s	remaining: 20.2s
343:	learn: 0.0801849	total: 10.6s	remaining: 20.1s
344:	learn: 0.0799960	total: 10.6s	remaining: 20.1s
345:	learn: 0.0798913	total: 10.6s	remaining: 20.1s
346:	learn: 0.0798462	total: 10.7s	remaining: 20s
347:	learn: 0.0797803	total: 10.7s	remaining: 20s
348:	learn: 0.0797555	total: 10.7s	remaining: 20s
349:	learn: 0.0797224	total: 10.7s	remaining: 20s
350:	learn: 0.0796543	total: 10.8s	remaining: 19.9s
351:	learn: 0.0794415	total: 10.8s	remaining: 19.9s
352:	learn: 0.0794078	total: 10.8s	remaining: 19.9s
353:	learn: 0.0793883	total: 10.9s	remaining: 19.8s
354:	learn: 0.0793636	total: 10.9s	remaining: 19.8s
355:	learn: 0.0791885	total: 10.9s	remaining: 19.8s
356:	learn: 0.0791225	total: 11s	remaining: 19.7s
357:	learn: 0.0791112	total: 11s	remaining: 19.8s
358:	learn: 0.0789317	total: 11s	remaining: 19.7s
359:	learn: 0.0788252	total: 11.1s	remaining: 19.7s
360:	learn: 0.0788151	total: 11.1s	remaining: 19.7s
361:	learn: 0.0787612	total: 11.1s	remaining: 19.6s
362:	learn: 0.0787480	total: 11.2s	remaining: 19.6s
363:	learn: 0.0786160	total: 11.2s	remaining: 19.6s
364:	learn: 0.0786076	total: 11.2s	remaining: 19.5s
365:	learn: 0.0784940	total: 11.3s	remaining: 19.5s
366:	learn: 0.0784907	total: 11.3s	remaining: 19.5s
367:	learn: 0.0784764	total: 11.3s	remaining: 19.4s
368:	learn: 0.0784654	total: 11.3s	remaining: 19.4s
369:	learn: 0.0783737	total: 11.4s	remaining: 19.4s
370:	learn: 0.0783571	total: 11.4s	remaining: 19.3s
371:	learn: 0.0783467	total: 11.4s	remaining: 19.3s
372:	learn: 0.0783416	total: 11.5s	remaining: 19.3s
373:	learn: 0.0782545	total: 11.5s	remaining: 19.3s
374:	learn: 0.0781927	total: 11.5s	remaining: 19.2s
375:	learn: 0.0781743	total: 11.6s	remaining: 19.2s
376:	learn: 0.0781592	total: 11.6s	remaining: 19.2s
377:	learn: 0.0781195	total: 11.6s	remaining: 19.1s
378:	learn: 0.0780928	total: 11.7s	remaining: 19.1s
379:	learn: 0.0780856	total: 11.7s	remaining: 19.1s
380:	learn: 0.0780240	total: 11.7s	remaining: 19.1s
381:	learn: 0.0780140	total: 11.8s	remaining: 19s
382:	learn: 0.0779995	total: 11.8s	remaining: 19s
383:	learn: 0.0778798	total: 11.8s	remaining: 19s
384:	learn: 0.0778565	total: 11.9s	remaining: 18.9s
385:	learn: 0.0777196	total: 11.9s	remaining: 18.9s

CV folds:  60%|██████    | 30/50 [15:51<10:34, 31.71s/fold]

Learning rate set to 0.042738
0:	learn: 0.3891834	total: 23.3ms	remaining: 23.3s
1:	learn: 0.3792156	total: 51.3ms	remaining: 25.6s
2:	learn: 0.3689215	total: 83.3ms	remaining: 27.7s
3:	learn: 0.3584670	total: 112ms	remaining: 27.8s
4:	learn: 0.3492428	total: 140ms	remaining: 27.8s
5:	learn: 0.3402617	total: 170ms	remaining: 28.2s
6:	learn: 0.3320807	total: 203ms	remaining: 28.8s
7:	learn: 0.3239815	total: 243ms	remaining: 30.2s
8:	learn: 0.3165121	total: 276ms	remaining: 30.4s
9:	learn: 0.3082143	total: 304ms	remaining: 30.1s
10:	learn: 0.3011462	total: 333ms	remaining: 29.9s
11:	learn: 0.2939103	total: 360ms	remaining: 29.6s
12:	learn: 0.2866346	total: 389ms	remaining: 29.5s
13:	learn: 0.2804900	total: 418ms	remaining: 29.4s
14:	learn: 0.2739569	total: 450ms	remaining: 29.6s
15:	learn: 0.2675041	total: 481ms	remaining: 29.6s
16:	learn: 0.2619134	total: 510ms	remaining: 29.5s
17:	learn: 0.2559081	total: 539ms	remaining: 29.4s
18:	learn: 0.2504180	total: 571ms	remaining: 29.5s
19:	learn: 0.2450274	total: 602ms	remaining: 29.5s
20:	learn: 0.2399366	total: 632ms	remaining: 29.5s
21:	learn: 0.2351738	total: 667ms	remaining: 29.6s
22:	learn: 0.2305809	total: 697ms	remaining: 29.6s
23:	learn: 0.2263163	total: 726ms	remaining: 29.5s
24:	learn: 0.2223921	total: 755ms	remaining: 29.4s
25:	learn: 0.2179971	total: 784ms	remaining: 29.4s
26:	learn: 0.2141918	total: 812ms	remaining: 29.3s
27:	learn: 0.2102197	total: 842ms	remaining: 29.2s
28:	learn: 0.2063932	total: 870ms	remaining: 29.1s
29:	learn: 0.2031499	total: 898ms	remaining: 29s
30:	learn: 0.1995396	total: 927ms	remaining: 29s
31:	learn: 0.1960917	total: 955ms	remaining: 28.9s
32:	learn: 0.1931351	total: 987ms	remaining: 28.9s
33:	learn: 0.1901526	total: 1.01s	remaining: 28.8s
34:	learn: 0.1873125	total: 1.06s	remaining: 29.2s
35:	learn: 0.1843061	total: 1.1s	remaining: 29.4s
36:	learn: 0.1817508	total: 1.13s	remaining: 29.3s
37:	learn: 0.1791704	total: 1.16s	remaining: 29.2s
38:	learn: 0.1769757	total: 1.19s	remaining: 29.2s
39:	learn: 0.1744154	total: 1.21s	remaining: 29.1s
40:	learn: 0.1718270	total: 1.24s	remaining: 29s
41:	learn: 0.1695752	total: 1.28s	remaining: 29.3s
42:	learn: 0.1673032	total: 1.32s	remaining: 29.4s
43:	learn: 0.1652184	total: 1.35s	remaining: 29.3s
44:	learn: 0.1632580	total: 1.38s	remaining: 29.3s
45:	learn: 0.1615092	total: 1.41s	remaining: 29.2s
46:	learn: 0.1595388	total: 1.44s	remaining: 29.2s
47:	learn: 0.1578240	total: 1.47s	remaining: 29.1s
48:	learn: 0.1562400	total: 1.5s	remaining: 29.1s
49:	learn: 0.1548492	total: 1.53s	remaining: 29.1s
50:	learn: 0.1532914	total: 1.56s	remaining: 29s
51:	learn: 0.1518515	total: 1.59s	remaining: 29s
52:	learn: 0.1504858	total: 1.62s	remaining: 29s
53:	learn: 0.1490022	total: 1.65s	remaining: 29s
54:	learn: 0.1475439	total: 1.69s	remaining: 29s
55:	learn: 0.1461188	total: 1.72s	remaining: 28.9s
56:	learn: 0.1446680	total: 1.75s	remaining: 28.9s
57:	learn: 0.1433413	total: 1.77s	remaining: 28.8s
58:	learn: 0.1421526	total: 1.82s	remaining: 29s
59:	learn: 0.1411111	total: 1.85s	remaining: 28.9s
60:	learn: 0.1399095	total: 1.87s	remaining: 28.9s
61:	learn: 0.1390023	total: 1.91s	remaining: 28.8s
62:	learn: 0.1379612	total: 1.94s	remaining: 28.8s
63:	learn: 0.1369824	total: 1.97s	remaining: 28.8s
64:	learn: 0.1360197	total: 2s	remaining: 28.7s
65:	learn: 0.1350746	total: 2.03s	remaining: 28.7s
66:	learn: 0.1342095	total: 2.06s	remaining: 28.6s
67:	learn: 0.1334023	total: 2.09s	remaining: 28.7s
68:	learn: 0.1326343	total: 2.12s	remaining: 28.7s
69:	learn: 0.1318902	total: 2.15s	remaining: 28.6s
70:	learn: 0.1311505	total: 2.19s	remaining: 28.6s
71:	learn: 0.1304540	total: 2.22s	remaining: 28.6s
72:	learn: 0.1294908	total: 2.25s	remaining: 28.6s
73:	learn: 0.1287362	total: 2.28s	remaining: 28.6s
74:	learn: 0.1281004	total: 2.31s	remaining: 28.5s
75:	learn: 0.1273842	total: 2.34s	remaining: 28.5s
76:	learn: 0.1265422	total: 2.37s	remaining: 28.4s
77:	learn: 0.1259415	total: 2.4s	remaining: 28.4s
78:	learn: 0.1252209	total: 2.44s	remaining: 28.4s
79:	learn: 0.1244626	total: 2.47s	remaining: 28.4s
80:	learn: 0.1239652	total: 2.5s	remaining: 28.3s
81:	learn: 0.1233545	total: 2.52s	remaining: 28.2s
82:	learn: 0.1227627	total: 2.55s	remaining: 28.2s
83:	learn: 0.1222231	total: 2.58s	remaining: 28.2s
84:	learn: 0.1215583	total: 2.61s	remaining: 28.1s
85:	learn: 0.1209585	total: 2.64s	remaining: 28.1s
86:	learn: 0.1205406	total: 2.67s	remaining: 28.1s
87:	learn: 0.1198806	total: 2.7s	remaining: 28s
88:	learn: 0.1193533	total: 2.73s	remaining: 28s
89:	learn: 0.1187948	total: 2.76s	remaining: 28s
90:	learn: 0.1183035	total: 2.79s	remaining: 27.9s
91:	learn: 0.1178493	total: 2.83s	remaining: 28s
92:	learn: 0.1174480	total: 2.87s	remaining: 28s
93:	learn: 0.1170334	total: 2.9s	remaining: 28s
94:	learn: 0.1165153	total: 2.93s	remaining: 27.9s
95:	learn: 0.1161515	total: 2.96s	remaining: 27.9s
96:	learn: 0.1158184	total: 2.99s	remaining: 27.8s
97:	learn: 0.1152640	total: 3.02s	remaining: 27.8s
98:	learn: 0.1148827	total: 3.04s	remaining: 27.7s
99:	learn: 0.1144807	total: 3.07s	remaining: 27.6s
100:	learn: 0.1141412	total: 3.1s	remaining: 27.6s
101:	learn: 0.1136604	total: 3.13s	remaining: 27.6s
102:	learn: 0.1132968	total: 3.16s	remaining: 27.5s
103:	learn: 0.1129849	total: 3.19s	remaining: 27.5s
104:	learn: 0.1126018	total: 3.22s	remaining: 27.5s
105:	learn: 0.1122915	total: 3.25s	remaining: 27.4s
106:	learn: 0.1119099	total: 3.28s	remaining: 27.4s
107:	learn: 0.1116294	total: 3.31s	remaining: 27.3s
108:	learn: 0.1111777	total: 3.33s	remaining: 27.3s
109:	learn: 0.1107332	total: 3.36s	remaining: 27.2s
110:	learn: 0.1102767	total: 3.39s	remaining: 27.2s
111:	learn: 0.1099672	total: 3.42s	remaining: 27.1s
112:	learn: 0.1096334	total: 3.45s	remaining: 27.1s
113:	learn: 0.1093596	total: 3.48s	remaining: 27.1s
114:	learn: 0.1091008	total: 3.51s	remaining: 27s
115:	learn: 0.1087944	total: 3.54s	remaining: 27s
116:	learn: 0.1084328	total: 3.57s	remaining: 27s
117:	learn: 0.1079348	total: 3.6s	remaining: 26.9s
118:	learn: 0.1076446	total: 3.64s	remaining: 26.9s
119:	learn: 0.1072457	total: 3.67s	remaining: 26.9s
120:	learn: 0.1068610	total: 3.7s	remaining: 26.9s
121:	learn: 0.1064847	total: 3.73s	remaining: 26.9s
122:	learn: 0.1060266	total: 3.76s	remaining: 26.8s
123:	learn: 0.1058781	total: 3.79s	remaining: 26.8s
124:	learn: 0.1056333	total: 3.83s	remaining: 26.8s
125:	learn: 0.1052774	total: 3.86s	remaining: 26.8s
126:	learn: 0.1051115	total: 3.89s	remaining: 26.7s
127:	learn: 0.1048846	total: 3.92s	remaining: 26.7s
128:	learn: 0.1046928	total: 3.96s	remaining: 26.8s
129:	learn: 0.1043922	total: 4s	remaining: 26.8s
130:	learn: 0.1041210	total: 4.03s	remaining: 26.7s
131:	learn: 0.1038885	total: 4.05s	remaining: 26.7s
132:	learn: 0.1037184	total: 4.09s	remaining: 26.6s
133:	learn: 0.1032988	total: 4.12s	remaining: 26.6s
134:	learn: 0.1030203	total: 4.15s	remaining: 26.6s
135:	learn: 0.1027082	total: 4.18s	remaining: 26.5s
136:	learn: 0.1024858	total: 4.21s	remaining: 26.5s
137:	learn: 0.1022632	total: 4.24s	remaining: 26.5s
138:	learn: 0.1020270	total: 4.27s	remaining: 26.4s
139:	learn: 0.1018375	total: 4.3s	remaining: 26.4s
140:	learn: 0.1017051	total: 4.33s	remaining: 26.4s
141:	learn: 0.1014895	total: 4.36s	remaining: 26.4s
142:	learn: 0.1013394	total: 4.39s	remaining: 26.3s
143:	learn: 0.1011371	total: 4.42s	remaining: 26.3s
144:	learn: 0.1008979	total: 4.45s	remaining: 26.2s
145:	learn: 0.1006893	total: 4.48s	remaining: 26.2s
146:	learn: 0.1005064	total: 4.5s	remaining: 26.1s
147:	learn: 0.1002379	total: 4.53s	remaining: 26.1s
148:	learn: 0.0999547	total: 4.56s	remaining: 26.1s
149:	learn: 0.0997571	total: 4.59s	remaining: 26s
150:	learn: 0.0996195	total: 4.63s	remaining: 26s
151:	learn: 0.0994237	total: 4.66s	remaining: 26s
152:	learn: 0.0992570	total: 4.69s	remaining: 26s
153:	learn: 0.0991465	total: 4.72s	remaining: 25.9s
154:	learn: 0.0989073	total: 4.75s	remaining: 25.9s
155:	learn: 0.0986379	total: 4.78s	remaining: 25.9s
156:	learn: 0.0984176	total: 4.81s	remaining: 25.8s
157:	learn: 0.0982337	total: 4.84s	remaining: 25.8s
158:	learn: 0.0980497	total: 4.87s	remaining: 25.8s
159:	learn: 0.0978966	total: 4.9s	remaining: 25.7s
160:	learn: 0.0977472	total: 4.93s	remaining: 25.7s
161:	learn: 0.0975503	total: 4.96s	remaining: 25.7s
162:	learn: 0.0973634	total: 4.99s	remaining: 25.6s
163:	learn: 0.0972364	total: 5.02s	remaining: 25.6s
164:	learn: 0.0970841	total: 5.05s	remaining: 25.6s
165:	learn: 0.0968993	total: 5.08s	remaining: 25.5s
166:	learn: 0.0966317	total: 5.11s	remaining: 25.5s
167:	learn: 0.0964546	total: 5.14s	remaining: 25.5s
168:	learn: 0.0962803	total: 5.17s	remaining: 25.4s
169:	learn: 0.0961381	total: 5.2s	remaining: 25.4s
170:	learn: 0.0959391	total: 5.23s	remaining: 25.3s
171:	learn: 0.0957234	total: 5.25s	remaining: 25.3s
172:	learn: 0.0955898	total: 5.29s	remaining: 25.3s
173:	learn: 0.0954410	total: 5.32s	remaining: 25.3s
174:	learn: 0.0952349	total: 5.35s	remaining: 25.2s
175:	learn: 0.0950821	total: 5.38s	remaining: 25.2s
176:	learn: 0.0948753	total: 5.41s	remaining: 25.1s
177:	learn: 0.0946762	total: 5.44s	remaining: 25.1s
178:	learn: 0.0944327	total: 5.47s	remaining: 25.1s
179:	learn: 0.0943319	total: 5.5s	remaining: 25s
180:	learn: 0.0942116	total: 5.53s	remaining: 25s
181:	learn: 0.0940977	total: 5.56s	remaining: 25s
182:	learn: 0.0939719	total: 5.59s	remaining: 25s
183:	learn: 0.0937565	total: 5.62s	remaining: 24.9s
184:	learn: 0.0936309	total: 5.65s	remaining: 24.9s
185:	learn: 0.0934955	total: 5.68s	remaining: 24.9s
186:	learn: 0.0933097	total: 5.72s	remaining: 24.9s
187:	learn: 0.0931550	total: 5.75s	remaining: 24.8s
188:	learn: 0.0930222	total: 5.78s	remaining: 24.8s
189:	learn: 0.0928564	total: 5.81s	remaining: 24.8s
190:	learn: 0.0927859	total: 5.84s	remaining: 24.7s
191:	learn: 0.0926286	total: 5.87s	remaining: 24.7s
192:	learn: 0.0924433	total: 5.9s	remaining: 24.7s
193:	learn: 0.0923537	total: 5.93s	remaining: 24.6s
194:	learn: 0.0922202	total: 5.96s	remaining: 24.6s
195:	learn: 0.0921601	total: 5.99s	remaining: 24.6s
196:	learn: 0.0920899	total: 6.02s	remaining: 24.5s
197:	learn: 0.0920266	total: 6.05s	remaining: 24.5s
198:	learn: 0.0919364	total: 6.08s	remaining: 24.5s
199:	learn: 0.0917807	total: 6.13s	remaining: 24.5s
200:	learn: 0.0915765	total: 6.16s	remaining: 24.5s
201:	learn: 0.0915095	total: 6.2s	remaining: 24.5s
202:	learn: 0.0914389	total: 6.22s	remaining: 24.4s
203:	learn: 0.0912684	total: 6.25s	remaining: 24.4s
204:	learn: 0.0909310	total: 6.28s	remaining: 24.4s
205:	learn: 0.0906457	total: 6.31s	remaining: 24.3s
206:	learn: 0.0904983	total: 6.34s	remaining: 24.3s
207:	learn: 0.0903024	total: 6.37s	remaining: 24.3s
208:	learn: 0.0902599	total: 6.4s	remaining: 24.2s
209:	learn: 0.0901455	total: 6.43s	remaining: 24.2s
210:	learn: 0.0898971	total: 6.46s	remaining: 24.2s
211:	learn: 0.0898294	total: 6.49s	remaining: 24.1s
212:	learn: 0.0896360	total: 6.52s	remaining: 24.1s
213:	learn: 0.0895290	total: 6.55s	remaining: 24.1s
214:	learn: 0.0892952	total: 6.58s	remaining: 24s
215:	learn: 0.0892528	total: 6.61s	remaining: 24s
216:	learn: 0.0890481	total: 6.65s	remaining: 24s
217:	learn: 0.0890070	total: 6.68s	remaining: 23.9s
218:	learn: 0.0889374	total: 6.71s	remaining: 23.9s
219:	learn: 0.0888831	total: 6.74s	remaining: 23.9s
220:	learn: 0.0887681	total: 6.76s	remaining: 23.8s
221:	learn: 0.0886709	total: 6.79s	remaining: 23.8s
222:	learn: 0.0885322	total: 6.82s	remaining: 23.8s
223:	learn: 0.0885098	total: 6.85s	remaining: 23.7s
224:	learn: 0.0884665	total: 6.88s	remaining: 23.7s
225:	learn: 0.0884427	total: 6.91s	remaining: 23.7s
226:	learn: 0.0883952	total: 6.94s	remaining: 23.6s
227:	learn: 0.0883578	total: 6.97s	remaining: 23.6s
228:	learn: 0.0883156	total: 7s	remaining: 23.6s
229:	learn: 0.0882109	total: 7.03s	remaining: 23.5s
230:	learn: 0.0880621	total: 7.06s	remaining: 23.5s
231:	learn: 0.0879661	total: 7.09s	remaining: 23.5s
232:	learn: 0.0877963	total: 7.13s	remaining: 23.5s
233:	learn: 0.0876186	total: 7.17s	remaining: 23.5s
234:	learn: 0.0873987	total: 7.2s	remaining: 23.4s
235:	learn: 0.0872340	total: 7.23s	remaining: 23.4s
236:	learn: 0.0871250	total: 7.26s	remaining: 23.4s
237:	learn: 0.0870697	total: 7.29s	remaining: 23.3s
238:	learn: 0.0870247	total: 7.32s	remaining: 23.3s
239:	learn: 0.0868692	total: 7.35s	remaining: 23.3s
240:	learn: 0.0868371	total: 7.38s	remaining: 23.2s
241:	learn: 0.0868153	total: 7.41s	remaining: 23.2s
242:	learn: 0.0867804	total: 7.44s	remaining: 23.2s
243:	learn: 0.0866278	total: 7.47s	remaining: 23.1s
244:	learn: 0.0865704	total: 7.5s	remaining: 23.1s
245:	learn: 0.0865284	total: 7.53s	remaining: 23.1s
246:	learn: 0.0862753	total: 7.56s	remaining: 23.1s
247:	learn: 0.0861265	total: 7.59s	remaining: 23s
248:	learn: 0.0858981	total: 7.62s	remaining: 23s
249:	learn: 0.0858644	total: 7.66s	remaining: 23s
250:	learn: 0.0856593	total: 7.68s	remaining: 22.9s
251:	learn: 0.0855924	total: 7.71s	remaining: 22.9s
252:	learn: 0.0854295	total: 7.75s	remaining: 22.9s
253:	learn: 0.0854107	total: 7.78s	remaining: 22.8s
254:	learn: 0.0853531	total: 7.8s	remaining: 22.8s
255:	learn: 0.0853018	total: 7.83s	remaining: 22.8s
256:	learn: 0.0852000	total: 7.86s	remaining: 22.7s
257:	learn: 0.0850523	total: 7.89s	remaining: 22.7s
258:	learn: 0.0848977	total: 7.92s	remaining: 22.7s
259:	learn: 0.0848481	total: 7.95s	remaining: 22.6s
260:	learn: 0.0847291	total: 7.98s	remaining: 22.6s
261:	learn: 0.0847168	total: 8.01s	remaining: 22.6s
262:	learn: 0.0846873	total: 8.04s	remaining: 22.5s
263:	learn: 0.0845466	total: 8.07s	remaining: 22.5s
264:	learn: 0.0844945	total: 8.1s	remaining: 22.5s
265:	learn: 0.0843528	total: 8.13s	remaining: 22.4s
266:	learn: 0.0841811	total: 8.16s	remaining: 22.4s
267:	learn: 0.0841098	total: 8.2s	remaining: 22.4s
268:	learn: 0.0840963	total: 8.23s	remaining: 22.4s
269:	learn: 0.0839842	total: 8.28s	remaining: 22.4s
270:	learn: 0.0839672	total: 8.31s	remaining: 22.4s
271:	learn: 0.0838665	total: 8.34s	remaining: 22.3s
272:	learn: 0.0838045	total: 8.37s	remaining: 22.3s
273:	learn: 0.0836062	total: 8.4s	remaining: 22.3s
274:	learn: 0.0835677	total: 8.43s	remaining: 22.2s
275:	learn: 0.0833960	total: 8.46s	remaining: 22.2s
276:	learn: 0.0833772	total: 8.49s	remaining: 22.2s
277:	learn: 0.0832428	total: 8.52s	remaining: 22.1s
278:	learn: 0.0831385	total: 8.55s	remaining: 22.1s
279:	learn: 0.0830449	total: 8.58s	remaining: 22.1s
280:	learn: 0.0829569	total: 8.61s	remaining: 22s
281:	learn: 0.0829461	total: 8.64s	remaining: 22s
282:	learn: 0.0827464	total: 8.67s	remaining: 22s
283:	learn: 0.0825747	total: 8.7s	remaining: 21.9s
284:	learn: 0.0825626	total: 8.73s	remaining: 21.9s
285:	learn: 0.0824396	total: 8.75s	remaining: 21.9s
286:	learn: 0.0822625	total: 8.78s	remaining: 21.8s
287:	learn: 0.0821593	total: 8.81s	remaining: 21.8s
288:	learn: 0.0821422	total: 8.85s	remaining: 21.8s
289:	learn: 0.0820763	total: 8.88s	remaining: 21.7s
290:	learn: 0.0820531	total: 8.91s	remaining: 21.7s
291:	learn: 0.0819852	total: 8.94s	remaining: 21.7s
292:	learn: 0.0818755	total: 8.96s	remaining: 21.6s
293:	learn: 0.0817558	total: 8.99s	remaining: 21.6s
294:	learn: 0.0817365	total: 9.02s	remaining: 21.6s
295:	learn: 0.0815878	total: 9.05s	remaining: 21.5s
296:	learn: 0.0814302	total: 9.08s	remaining: 21.5s
297:	learn: 0.0813667	total: 9.12s	remaining: 21.5s
298:	learn: 0.0813488	total: 9.15s	remaining: 21.4s
299:	learn: 0.0812963	total: 9.18s	remaining: 21.4s
300:	learn: 0.0811867	total: 9.21s	remaining: 21.4s
301:	learn: 0.0810757	total: 9.23s	remaining: 21.3s
302:	learn: 0.0810130	total: 9.26s	remaining: 21.3s
303:	learn: 0.0809809	total: 9.29s	remaining: 21.3s
304:	learn: 0.0808696	total: 9.32s	remaining: 21.2s
305:	learn: 0.0807424	total: 9.35s	remaining: 21.2s
306:	learn: 0.0807250	total: 9.38s	remaining: 21.2s
307:	learn: 0.0805503	total: 9.41s	remaining: 21.1s
308:	learn: 0.0804915	total: 9.45s	remaining: 21.1s
309:	learn: 0.0804694	total: 9.48s	remaining: 21.1s
310:	learn: 0.0803350	total: 9.51s	remaining: 21.1s
311:	learn: 0.0802033	total: 9.54s	remaining: 21s
312:	learn: 0.0800933	total: 9.57s	remaining: 21s
313:	learn: 0.0800078	total: 9.6s	remaining: 21s
314:	learn: 0.0799503	total: 9.63s	remaining: 20.9s
315:	learn: 0.0799354	total: 9.66s	remaining: 20.9s
316:	learn: 0.0798239	total: 9.69s	remaining: 20.9s
317:	learn: 0.0797378	total: 9.72s	remaining: 20.9s
318:	learn: 0.0797207	total: 9.75s	remaining: 20.8s
319:	learn: 0.0797028	total: 9.78s	remaining: 20.8s
320:	learn: 0.0795841	total: 9.82s	remaining: 20.8s
321:	learn: 0.0795480	total: 9.85s	remaining: 20.7s
322:	learn: 0.0794091	total: 9.87s	remaining: 20.7s
323:	learn: 0.0793812	total: 9.9s	remaining: 20.7s
324:	learn: 0.0793714	total: 9.93s	remaining: 20.6s
325:	learn: 0.0792818	total: 9.96s	remaining: 20.6s
326:	learn: 0.0791765	total: 9.99s	remaining: 20.6s
327:	learn: 0.0789943	total: 10s	remaining: 20.5s
328:	learn: 0.0789781	total: 10.1s	remaining: 20.5s
329:	learn: 0.0789325	total: 10.1s	remaining: 20.5s
330:	learn: 0.0788318	total: 10.1s	remaining: 20.4s
331:	learn: 0.0786399	total: 10.1s	remaining: 20.4s
332:	learn: 0.0785102	total: 10.2s	remaining: 20.4s
333:	learn: 0.0784999	total: 10.2s	remaining: 20.4s
334:	learn: 0.0784821	total: 10.2s	remaining: 20.3s
335:	learn: 0.0784151	total: 10.3s	remaining: 20.3s
336:	learn: 0.0783029	total: 10.3s	remaining: 20.3s
337:	learn: 0.0782149	total: 10.3s	remaining: 20.2s
338:	learn: 0.0780721	total: 10.4s	remaining: 20.2s
339:	learn: 0.0779646	total: 10.4s	remaining: 20.2s
340:	learn: 0.0779508	total: 10.4s	remaining: 20.2s
341:	learn: 0.0778478	total: 10.5s	remaining: 20.1s
342:	learn: 0.0778252	total: 10.5s	remaining: 20.1s
343:	learn: 0.0776571	total: 10.5s	remaining: 20.1s
344:	learn: 0.0775594	total: 10.5s	remaining: 20s
345:	learn: 0.0775484	total: 10.6s	remaining: 20s
346:	learn: 0.0774145	total: 10.6s	remaining: 20s
347:	learn: 0.0773030	total: 10.6s	remaining: 20s
348:	learn: 0.0772833	total: 10.7s	remaining: 19.9s
349:	learn: 0.0771890	total: 10.7s	remaining: 19.9s
350:	learn: 0.0770566	total: 10.7s	remaining: 19.9s
351:	learn: 0.0770453	total: 10.8s	remaining: 19.8s
352:	learn: 0.0769435	total: 10.8s	remaining: 19.8s
353:	learn: 0.0769277	total: 10.8s	remaining: 19.8s
354:	learn: 0.0769103	total: 10.9s	remaining: 19.7s
355:	learn: 0.0768951	total: 10.9s	remaining: 19.7s
356:	learn: 0.0768777	total: 10.9s	remaining: 19.6s
357:	learn: 0.0768186	total: 10.9s	remaining: 19.6s
358:	learn: 0.0767423	total: 11s	remaining: 19.6s
359:	learn: 0.0767380	total: 11s	remaining: 19.6s
360:	learn: 0.0766376	total: 11s	remaining: 19.5s
361:	learn: 0.0765551	total: 11.1s	remaining: 19.5s
362:	learn: 0.0764603	total: 11.1s	remaining: 19.5s
363:	learn: 0.0763446	total: 11.1s	remaining: 19.4s
364:	learn: 0.0762580	total: 11.2s	remaining: 19.4s
365:	learn: 0.0762203	total: 11.2s	remaining: 19.4s
366:	learn: 0.0762080	total: 11.2s	remaining: 19.3s
367:	learn: 0.0760838	total: 11.2s	remaining: 19.3s
368:	learn: 0.0759420	total: 11.3s	remaining: 19.3s
369:	learn: 0.0758583	total: 11.3s	remaining: 19.3s
370:	learn: 0.0757738	total: 11.3s	remaining: 19.2s
371:	learn: 0.0757221	total: 11.4s	remaining: 19.2s
372:	learn: 0.0756034	total: 11.4s	remaining: 19.2s
373:	learn: 0.0755713	total: 11.4s	remaining: 19.1s
374:	learn: 0.0754928	total: 11.5s	remaining: 19.1s
375:	learn: 0.0753997	total: 11.5s	remaining: 19.1s
376:	learn: 0.0753920	total: 11.5s	remaining: 19.1s
377:	learn: 0.0752706	total: 11.6s	remaining: 19s
378:	learn: 0.0751788	total: 11.6s	remaining: 19s
379:	learn: 0.0750695	total: 11.6s	remaining: 19s
380:	learn: 0.0750429	total: 11.7s	remaining: 19s
381:	learn: 0.0750153	total: 11.7s	remaining: 18.9s
382:	learn: 0.0749599	total: 11.7s	remaining: 18.9s
383:	learn: 0.0748542	total: 11.8s	remaining: 18.9s
384:	learn: 0.0746398	total: 11.8s	remaining: 18.8s
385:	learn: 0.0745023	total: 11.8s	remaining: 18.8s
386:	learn: 0.0744804	total: 11.8s	remaining: 18.8s
387:	learn: 0.0744459	total: 11.9s	remaining: 18.7s

CV folds:  62%|██████▏   | 31/50 [16:23<10:00, 31.62s/fold]

997:	learn: 0.0437524	total: 30.8s	remaining: 61.8ms
998:	learn: 0.0437309	total: 30.9s	remaining: 30.9ms
999:	learn: 0.0436759	total: 30.9s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3862178	total: 24.8ms	remaining: 24.7s
1:	learn: 0.3757885	total: 53.2ms	remaining: 26.6s
2:	learn: 0.3661674	total: 83.3ms	remaining: 27.7s
3:	learn: 0.3569336	total: 112ms	remaining: 28s
4:	learn: 0.3470488	total: 143ms	remaining: 28.4s
5:	learn: 0.3381898	total: 170ms	remaining: 28.1s
6:	learn: 0.3287687	total: 198ms	remaining: 28.1s
7:	learn: 0.3206150	total: 228ms	remaining: 28.3s
8:	learn: 0.3124959	total: 261ms	remaining: 28.8s
9:	learn: 0.3042979	total: 291ms	remaining: 28.8s
10:	learn: 0.2968948	total: 319ms	remaining: 28.7s
11:	learn: 0.2893311	total: 346ms	remaining: 28.5s
12:	learn: 0.2828969	total: 377ms	remaining: 28.6s
13:	learn: 0.2760356	total: 405ms	remaining: 28.5s
14:	learn: 0.2694917	total: 435ms	remaining: 28.6s
15:	learn: 0.2637410	total: 464ms	remaining: 28.6s
16:	learn: 0.2580581	total: 484ms	remaining: 28s
17:	learn: 0.2525330	total: 511ms	remaining: 27.9s
18:	learn: 0.2467435	total: 540ms	remaining: 27.9s
19:	learn: 0.2413846	total: 571ms	remaining: 28s
20:	learn: 0.2362645	total: 601ms	remaining: 28s
21:	learn: 0.2315566	total: 629ms	remaining: 28s
22:	learn: 0.2269691	total: 656ms	remaining: 27.9s
23:	learn: 0.2226213	total: 686ms	remaining: 27.9s
24:	learn: 0.2180567	total: 714ms	remaining: 27.8s
25:	learn: 0.2136928	total: 764ms	remaining: 28.6s
26:	learn: 0.2096245	total: 796ms	remaining: 28.7s
27:	learn: 0.2059505	total: 823ms	remaining: 28.6s
28:	learn: 0.2025328	total: 849ms	remaining: 28.4s
29:	learn: 0.1989355	total: 879ms	remaining: 28.4s
30:	learn: 0.1957220	total: 908ms	remaining: 28.4s
31:	learn: 0.1927270	total: 938ms	remaining: 28.4s
32:	learn: 0.1898535	total: 968ms	remaining: 28.4s
33:	learn: 0.1870479	total: 995ms	remaining: 28.3s
34:	learn: 0.1840174	total: 1.02s	remaining: 28.1s
35:	learn: 0.1812132	total: 1.05s	remaining: 28s
36:	learn: 0.1785335	total: 1.07s	remaining: 28s
37:	learn: 0.1762907	total: 1.1s	remaining: 28s
38:	learn: 0.1737609	total: 1.13s	remaining: 27.9s
39:	learn: 0.1714722	total: 1.16s	remaining: 27.9s
40:	learn: 0.1689008	total: 1.19s	remaining: 27.8s
41:	learn: 0.1665273	total: 1.22s	remaining: 27.8s
42:	learn: 0.1644091	total: 1.25s	remaining: 27.7s
43:	learn: 0.1624528	total: 1.28s	remaining: 27.7s
44:	learn: 0.1603277	total: 1.3s	remaining: 27.7s
45:	learn: 0.1587248	total: 1.33s	remaining: 27.7s
46:	learn: 0.1569066	total: 1.36s	remaining: 27.7s
47:	learn: 0.1552145	total: 1.39s	remaining: 27.6s
48:	learn: 0.1533112	total: 1.42s	remaining: 27.6s
49:	learn: 0.1518622	total: 1.45s	remaining: 27.6s
50:	learn: 0.1501285	total: 1.48s	remaining: 27.5s
51:	learn: 0.1485496	total: 1.51s	remaining: 27.5s
52:	learn: 0.1472662	total: 1.53s	remaining: 27.4s
53:	learn: 0.1457605	total: 1.57s	remaining: 27.5s
54:	learn: 0.1444763	total: 1.6s	remaining: 27.5s
55:	learn: 0.1431409	total: 1.63s	remaining: 27.4s
56:	learn: 0.1418263	total: 1.66s	remaining: 27.4s
57:	learn: 0.1404646	total: 1.68s	remaining: 27.4s
58:	learn: 0.1392195	total: 1.71s	remaining: 27.3s
59:	learn: 0.1379899	total: 1.74s	remaining: 27.2s
60:	learn: 0.1368967	total: 1.77s	remaining: 27.2s
61:	learn: 0.1359315	total: 1.79s	remaining: 27.1s
62:	learn: 0.1350355	total: 1.83s	remaining: 27.2s
63:	learn: 0.1340296	total: 1.86s	remaining: 27.1s
64:	learn: 0.1330187	total: 1.89s	remaining: 27.2s
65:	learn: 0.1320401	total: 1.92s	remaining: 27.1s
66:	learn: 0.1313141	total: 1.94s	remaining: 27s
67:	learn: 0.1302916	total: 1.97s	remaining: 27s
68:	learn: 0.1295306	total: 2s	remaining: 27s
69:	learn: 0.1286541	total: 2.03s	remaining: 27s
70:	learn: 0.1278665	total: 2.06s	remaining: 26.9s
71:	learn: 0.1270422	total: 2.08s	remaining: 26.9s
72:	learn: 0.1262355	total: 2.11s	remaining: 26.8s
73:	learn: 0.1255703	total: 2.14s	remaining: 26.8s
74:	learn: 0.1246702	total: 2.17s	remaining: 26.8s
75:	learn: 0.1240350	total: 2.2s	remaining: 26.8s
76:	learn: 0.1234623	total: 2.23s	remaining: 26.8s
77:	learn: 0.1228814	total: 2.28s	remaining: 26.9s
78:	learn: 0.1221784	total: 2.31s	remaining: 26.9s
79:	learn: 0.1215081	total: 2.33s	remaining: 26.8s
80:	learn: 0.1209194	total: 2.36s	remaining: 26.8s
81:	learn: 0.1203776	total: 2.39s	remaining: 26.8s
82:	learn: 0.1197011	total: 2.42s	remaining: 26.7s
83:	learn: 0.1192878	total: 2.45s	remaining: 26.7s
84:	learn: 0.1186998	total: 2.48s	remaining: 26.7s
85:	learn: 0.1182204	total: 2.51s	remaining: 26.7s
86:	learn: 0.1178076	total: 2.54s	remaining: 26.7s
87:	learn: 0.1173453	total: 2.57s	remaining: 26.6s
88:	learn: 0.1166611	total: 2.6s	remaining: 26.6s
89:	learn: 0.1162152	total: 2.63s	remaining: 26.6s
90:	learn: 0.1156665	total: 2.66s	remaining: 26.5s
91:	learn: 0.1152781	total: 2.7s	remaining: 26.7s
92:	learn: 0.1148912	total: 2.73s	remaining: 26.7s
93:	learn: 0.1143846	total: 2.76s	remaining: 26.6s
94:	learn: 0.1140011	total: 2.79s	remaining: 26.6s
95:	learn: 0.1136091	total: 2.82s	remaining: 26.6s
96:	learn: 0.1132033	total: 2.85s	remaining: 26.5s
97:	learn: 0.1128934	total: 2.89s	remaining: 26.6s
98:	learn: 0.1124962	total: 2.92s	remaining: 26.6s
99:	learn: 0.1120364	total: 2.96s	remaining: 26.6s
100:	learn: 0.1114371	total: 2.98s	remaining: 26.5s
101:	learn: 0.1110405	total: 3.01s	remaining: 26.5s
102:	learn: 0.1106972	total: 3.04s	remaining: 26.5s
103:	learn: 0.1103522	total: 3.07s	remaining: 26.5s
104:	learn: 0.1101146	total: 3.09s	remaining: 26.3s
105:	learn: 0.1097853	total: 3.12s	remaining: 26.3s
106:	learn: 0.1094955	total: 3.15s	remaining: 26.3s
107:	learn: 0.1091127	total: 3.18s	remaining: 26.3s
108:	learn: 0.1087608	total: 3.21s	remaining: 26.2s
109:	learn: 0.1083994	total: 3.23s	remaining: 26.2s
110:	learn: 0.1081219	total: 3.26s	remaining: 26.1s
111:	learn: 0.1078060	total: 3.29s	remaining: 26.1s
112:	learn: 0.1075911	total: 3.32s	remaining: 26.1s
113:	learn: 0.1073635	total: 3.35s	remaining: 26s
114:	learn: 0.1071032	total: 3.38s	remaining: 26s
115:	learn: 0.1067823	total: 3.41s	remaining: 26s
116:	learn: 0.1065110	total: 3.44s	remaining: 26s
117:	learn: 0.1061964	total: 3.47s	remaining: 26s
118:	learn: 0.1059010	total: 3.5s	remaining: 25.9s
119:	learn: 0.1055060	total: 3.53s	remaining: 25.9s
120:	learn: 0.1052532	total: 3.56s	remaining: 25.9s
121:	learn: 0.1050175	total: 3.58s	remaining: 25.8s
122:	learn: 0.1047461	total: 3.6s	remaining: 25.7s
123:	learn: 0.1045042	total: 3.63s	remaining: 25.7s
124:	learn: 0.1042760	total: 3.66s	remaining: 25.6s
125:	learn: 0.1039784	total: 3.69s	remaining: 25.6s
126:	learn: 0.1036480	total: 3.72s	remaining: 25.6s
127:	learn: 0.1034758	total: 3.75s	remaining: 25.5s
128:	learn: 0.1032731	total: 3.77s	remaining: 25.5s
129:	learn: 0.1029896	total: 3.8s	remaining: 25.4s
130:	learn: 0.1027410	total: 3.83s	remaining: 25.4s
131:	learn: 0.1025170	total: 3.85s	remaining: 25.3s
132:	learn: 0.1022485	total: 3.88s	remaining: 25.3s
133:	learn: 0.1020718	total: 3.91s	remaining: 25.3s
134:	learn: 0.1018860	total: 3.94s	remaining: 25.3s
135:	learn: 0.1017476	total: 3.97s	remaining: 25.2s
136:	learn: 0.1014744	total: 4s	remaining: 25.2s
137:	learn: 0.1011958	total: 4.03s	remaining: 25.2s
138:	learn: 0.1010048	total: 4.06s	remaining: 25.2s
139:	learn: 0.1006809	total: 4.09s	remaining: 25.1s
140:	learn: 0.1004462	total: 4.12s	remaining: 25.1s
141:	learn: 0.1002231	total: 4.15s	remaining: 25.1s
142:	learn: 0.0999217	total: 4.18s	remaining: 25s
143:	learn: 0.0997622	total: 4.2s	remaining: 25s
144:	learn: 0.0995641	total: 4.24s	remaining: 25s
145:	learn: 0.0994147	total: 4.26s	remaining: 25s
146:	learn: 0.0992570	total: 4.29s	remaining: 24.9s
147:	learn: 0.0990228	total: 4.32s	remaining: 24.9s
148:	learn: 0.0988377	total: 4.35s	remaining: 24.9s
149:	learn: 0.0985643	total: 4.38s	remaining: 24.8s
150:	learn: 0.0983470	total: 4.41s	remaining: 24.8s
151:	learn: 0.0981698	total: 4.44s	remaining: 24.8s
152:	learn: 0.0980196	total: 4.47s	remaining: 24.8s
153:	learn: 0.0978754	total: 4.5s	remaining: 24.8s
154:	learn: 0.0976733	total: 4.53s	remaining: 24.7s
155:	learn: 0.0973101	total: 4.57s	remaining: 24.7s
156:	learn: 0.0971832	total: 4.61s	remaining: 24.8s
157:	learn: 0.0970098	total: 4.64s	remaining: 24.7s
158:	learn: 0.0968084	total: 4.67s	remaining: 24.7s
159:	learn: 0.0966462	total: 4.7s	remaining: 24.7s
160:	learn: 0.0963832	total: 4.73s	remaining: 24.7s
161:	learn: 0.0962831	total: 4.76s	remaining: 24.6s
162:	learn: 0.0961543	total: 4.79s	remaining: 24.6s
163:	learn: 0.0959234	total: 4.82s	remaining: 24.6s
164:	learn: 0.0956873	total: 4.85s	remaining: 24.5s
165:	learn: 0.0955096	total: 4.88s	remaining: 24.5s
166:	learn: 0.0953595	total: 4.91s	remaining: 24.5s
167:	learn: 0.0951909	total: 4.94s	remaining: 24.5s
168:	learn: 0.0949681	total: 4.97s	remaining: 24.4s
169:	learn: 0.0947910	total: 5s	remaining: 24.4s
170:	learn: 0.0945609	total: 5.03s	remaining: 24.4s
171:	learn: 0.0943718	total: 5.07s	remaining: 24.4s
172:	learn: 0.0942710	total: 5.1s	remaining: 24.4s
173:	learn: 0.0941683	total: 5.13s	remaining: 24.4s
174:	learn: 0.0940201	total: 5.16s	remaining: 24.3s
175:	learn: 0.0938916	total: 5.19s	remaining: 24.3s
176:	learn: 0.0936885	total: 5.22s	remaining: 24.3s
177:	learn: 0.0935132	total: 5.26s	remaining: 24.3s
178:	learn: 0.0934437	total: 5.31s	remaining: 24.4s
179:	learn: 0.0933283	total: 5.34s	remaining: 24.3s
180:	learn: 0.0931796	total: 5.37s	remaining: 24.3s
181:	learn: 0.0930393	total: 5.4s	remaining: 24.3s
182:	learn: 0.0926672	total: 5.43s	remaining: 24.2s
183:	learn: 0.0924795	total: 5.46s	remaining: 24.2s
184:	learn: 0.0923317	total: 5.49s	remaining: 24.2s
185:	learn: 0.0922092	total: 5.52s	remaining: 24.2s
186:	learn: 0.0919311	total: 5.55s	remaining: 24.1s
187:	learn: 0.0917330	total: 5.58s	remaining: 24.1s
188:	learn: 0.0915650	total: 5.61s	remaining: 24.1s
189:	learn: 0.0914275	total: 5.64s	remaining: 24.1s
190:	learn: 0.0912405	total: 5.67s	remaining: 24s
191:	learn: 0.0911807	total: 5.7s	remaining: 24s
192:	learn: 0.0910179	total: 5.73s	remaining: 24s
193:	learn: 0.0908443	total: 5.76s	remaining: 23.9s
194:	learn: 0.0907394	total: 5.79s	remaining: 23.9s
195:	learn: 0.0905724	total: 5.82s	remaining: 23.9s
196:	learn: 0.0904687	total: 5.84s	remaining: 23.8s
197:	learn: 0.0903873	total: 5.87s	remaining: 23.8s
198:	learn: 0.0902377	total: 5.9s	remaining: 23.8s
199:	learn: 0.0901344	total: 5.93s	remaining: 23.7s
200:	learn: 0.0900238	total: 5.97s	remaining: 23.7s
201:	learn: 0.0899410	total: 6s	remaining: 23.7s
202:	learn: 0.0898428	total: 6.03s	remaining: 23.7s
203:	learn: 0.0897780	total: 6.05s	remaining: 23.6s
204:	learn: 0.0896922	total: 6.08s	remaining: 23.6s
205:	learn: 0.0896133	total: 6.11s	remaining: 23.6s
206:	learn: 0.0895618	total: 6.14s	remaining: 23.5s
207:	learn: 0.0894303	total: 6.17s	remaining: 23.5s
208:	learn: 0.0893164	total: 6.2s	remaining: 23.5s
209:	learn: 0.0892364	total: 6.23s	remaining: 23.4s
210:	learn: 0.0891695	total: 6.26s	remaining: 23.4s
211:	learn: 0.0890426	total: 6.29s	remaining: 23.4s
212:	learn: 0.0889930	total: 6.32s	remaining: 23.3s
213:	learn: 0.0888336	total: 6.35s	remaining: 23.3s
214:	learn: 0.0887738	total: 6.38s	remaining: 23.3s
215:	learn: 0.0887160	total: 6.41s	remaining: 23.3s
216:	learn: 0.0884627	total: 6.44s	remaining: 23.2s
217:	learn: 0.0883309	total: 6.47s	remaining: 23.2s
218:	learn: 0.0882528	total: 6.5s	remaining: 23.2s
219:	learn: 0.0881707	total: 6.53s	remaining: 23.2s
220:	learn: 0.0881349	total: 6.56s	remaining: 23.1s
221:	learn: 0.0880743	total: 6.59s	remaining: 23.1s
222:	learn: 0.0878775	total: 6.62s	remaining: 23.1s
223:	learn: 0.0878363	total: 6.65s	remaining: 23s
224:	learn: 0.0876438	total: 6.68s	remaining: 23s
225:	learn: 0.0875667	total: 6.71s	remaining: 23s
226:	learn: 0.0873906	total: 6.74s	remaining: 22.9s
227:	learn: 0.0871304	total: 6.76s	remaining: 22.9s
228:	learn: 0.0870807	total: 6.79s	remaining: 22.9s
229:	learn: 0.0869259	total: 6.82s	remaining: 22.8s
230:	learn: 0.0867579	total: 6.86s	remaining: 22.8s
231:	learn: 0.0866541	total: 6.89s	remaining: 22.8s
232:	learn: 0.0866070	total: 6.92s	remaining: 22.8s
233:	learn: 0.0863757	total: 6.95s	remaining: 22.8s
234:	learn: 0.0862148	total: 6.98s	remaining: 22.7s
235:	learn: 0.0861186	total: 7.01s	remaining: 22.7s
236:	learn: 0.0860313	total: 7.04s	remaining: 22.7s
237:	learn: 0.0859852	total: 7.07s	remaining: 22.6s
238:	learn: 0.0859179	total: 7.1s	remaining: 22.6s
239:	learn: 0.0858228	total: 7.13s	remaining: 22.6s
240:	learn: 0.0857086	total: 7.16s	remaining: 22.6s
241:	learn: 0.0856395	total: 7.2s	remaining: 22.5s
242:	learn: 0.0855918	total: 7.23s	remaining: 22.5s
243:	learn: 0.0855253	total: 7.26s	remaining: 22.5s
244:	learn: 0.0853321	total: 7.29s	remaining: 22.5s
245:	learn: 0.0853244	total: 7.32s	remaining: 22.4s
246:	learn: 0.0852105	total: 7.35s	remaining: 22.4s
247:	learn: 0.0850879	total: 7.38s	remaining: 22.4s
248:	learn: 0.0850173	total: 7.41s	remaining: 22.3s
249:	learn: 0.0849797	total: 7.43s	remaining: 22.3s
250:	learn: 0.0849064	total: 7.47s	remaining: 22.3s
251:	learn: 0.0846661	total: 7.5s	remaining: 22.3s
252:	learn: 0.0845859	total: 7.53s	remaining: 22.2s
253:	learn: 0.0845218	total: 7.56s	remaining: 22.2s
254:	learn: 0.0844406	total: 7.59s	remaining: 22.2s
255:	learn: 0.0843504	total: 7.62s	remaining: 22.1s
256:	learn: 0.0843018	total: 7.65s	remaining: 22.1s
257:	learn: 0.0842148	total: 7.67s	remaining: 22.1s
258:	learn: 0.0841162	total: 7.71s	remaining: 22s
259:	learn: 0.0839803	total: 7.74s	remaining: 22s
260:	learn: 0.0839226	total: 7.77s	remaining: 22s
261:	learn: 0.0838898	total: 7.79s	remaining: 22s
262:	learn: 0.0838232	total: 7.82s	remaining: 21.9s
263:	learn: 0.0836420	total: 7.85s	remaining: 21.9s
264:	learn: 0.0835445	total: 7.88s	remaining: 21.9s
265:	learn: 0.0834252	total: 7.91s	remaining: 21.8s
266:	learn: 0.0832286	total: 7.95s	remaining: 21.8s
267:	learn: 0.0830737	total: 7.97s	remaining: 21.8s
268:	learn: 0.0830042	total: 8.01s	remaining: 21.8s
269:	learn: 0.0829417	total: 8.04s	remaining: 21.7s
270:	learn: 0.0829129	total: 8.06s	remaining: 21.7s
271:	learn: 0.0828803	total: 8.11s	remaining: 21.7s
272:	learn: 0.0828240	total: 8.14s	remaining: 21.7s
273:	learn: 0.0826181	total: 8.18s	remaining: 21.7s
274:	learn: 0.0825911	total: 8.2s	remaining: 21.6s
275:	learn: 0.0824661	total: 8.23s	remaining: 21.6s
276:	learn: 0.0823199	total: 8.26s	remaining: 21.6s
277:	learn: 0.0821810	total: 8.29s	remaining: 21.5s
278:	learn: 0.0821265	total: 8.32s	remaining: 21.5s
279:	learn: 0.0820256	total: 8.36s	remaining: 21.5s
280:	learn: 0.0819402	total: 8.38s	remaining: 21.5s
281:	learn: 0.0818555	total: 8.41s	remaining: 21.4s
282:	learn: 0.0817151	total: 8.45s	remaining: 21.4s
283:	learn: 0.0817066	total: 8.48s	remaining: 21.4s
284:	learn: 0.0816943	total: 8.51s	remaining: 21.3s
285:	learn: 0.0815356	total: 8.54s	remaining: 21.3s
286:	learn: 0.0815231	total: 8.57s	remaining: 21.3s
287:	learn: 0.0814639	total: 8.6s	remaining: 21.3s
288:	learn: 0.0812380	total: 8.64s	remaining: 21.3s
289:	learn: 0.0811614	total: 8.68s	remaining: 21.2s
290:	learn: 0.0810503	total: 8.71s	remaining: 21.2s
291:	learn: 0.0809770	total: 8.73s	remaining: 21.2s
292:	learn: 0.0808072	total: 8.76s	remaining: 21.1s
293:	learn: 0.0805147	total: 8.79s	remaining: 21.1s
294:	learn: 0.0802425	total: 8.82s	remaining: 21.1s
295:	learn: 0.0799849	total: 8.85s	remaining: 21.1s
296:	learn: 0.0797617	total: 8.9s	remaining: 21.1s
297:	learn: 0.0795457	total: 8.93s	remaining: 21s
298:	learn: 0.0793314	total: 8.97s	remaining: 21s
299:	learn: 0.0792443	total: 9s	remaining: 21s
300:	learn: 0.0791616	total: 9.03s	remaining: 21s
301:	learn: 0.0790481	total: 9.06s	remaining: 20.9s
302:	learn: 0.0790284	total: 9.09s	remaining: 20.9s
303:	learn: 0.0789587	total: 9.12s	remaining: 20.9s
304:	learn: 0.0788555	total: 9.15s	remaining: 20.9s
305:	learn: 0.0788335	total: 9.18s	remaining: 20.8s
306:	learn: 0.0787710	total: 9.21s	remaining: 20.8s
307:	learn: 0.0787469	total: 9.24s	remaining: 20.8s
308:	learn: 0.0786616	total: 9.27s	remaining: 20.7s
309:	learn: 0.0785619	total: 9.3s	remaining: 20.7s
310:	learn: 0.0784133	total: 9.33s	remaining: 20.7s
311:	learn: 0.0783928	total: 9.37s	remaining: 20.7s
312:	learn: 0.0783715	total: 9.4s	remaining: 20.6s
313:	learn: 0.0782878	total: 9.43s	remaining: 20.6s
314:	learn: 0.0782656	total: 9.46s	remaining: 20.6s
315:	learn: 0.0779595	total: 9.48s	remaining: 20.5s
316:	learn: 0.0777797	total: 9.52s	remaining: 20.5s
317:	learn: 0.0776805	total: 9.55s	remaining: 20.5s
318:	learn: 0.0776507	total: 9.58s	remaining: 20.4s
319:	learn: 0.0775849	total: 9.61s	remaining: 20.4s
320:	learn: 0.0775034	total: 9.64s	remaining: 20.4s
321:	learn: 0.0773952	total: 9.67s	remaining: 20.4s
322:	learn: 0.0772248	total: 9.7s	remaining: 20.3s
323:	learn: 0.0771028	total: 9.73s	remaining: 20.3s
324:	learn: 0.0769983	total: 9.76s	remaining: 20.3s
325:	learn: 0.0769180	total: 9.8s	remaining: 20.3s
326:	learn: 0.0769008	total: 9.82s	remaining: 20.2s
327:	learn: 0.0767383	total: 9.85s	remaining: 20.2s
328:	learn: 0.0766039	total: 9.89s	remaining: 20.2s
329:	learn: 0.0764833	total: 9.91s	remaining: 20.1s
330:	learn: 0.0763641	total: 9.95s	remaining: 20.1s
331:	learn: 0.0762076	total: 9.98s	remaining: 20.1s
332:	learn: 0.0761517	total: 10s	remaining: 20s
333:	learn: 0.0759799	total: 10.1s	remaining: 20s
334:	learn: 0.0759698	total: 10.1s	remaining: 20s
335:	learn: 0.0759640	total: 10.1s	remaining: 20s
336:	learn: 0.0759416	total: 10.1s	remaining: 20s
337:	learn: 0.0758745	total: 10.2s	remaining: 19.9s
338:	learn: 0.0757793	total: 10.2s	remaining: 19.9s
339:	learn: 0.0756587	total: 10.2s	remaining: 19.9s
340:	learn: 0.0756395	total: 10.3s	remaining: 19.8s
341:	learn: 0.0755491	total: 10.3s	remaining: 19.8s
342:	learn: 0.0754222	total: 10.3s	remaining: 19.8s
343:	learn: 0.0753265	total: 10.4s	remaining: 19.8s
344:	learn: 0.0753086	total: 10.4s	remaining: 19.7s
345:	learn: 0.0751639	total: 10.4s	remaining: 19.7s
346:	learn: 0.0751514	total: 10.5s	remaining: 19.7s
347:	learn: 0.0750221	total: 10.5s	remaining: 19.7s
348:	learn: 0.0748728	total: 10.5s	remaining: 19.6s
349:	learn: 0.0748282	total: 10.6s	remaining: 19.6s
350:	learn: 0.0746614	total: 10.6s	remaining: 19.6s
351:	learn: 0.0746496	total: 10.6s	remaining: 19.5s
352:	learn: 0.0745708	total: 10.6s	remaining: 19.5s
353:	learn: 0.0745428	total: 10.7s	remaining: 19.5s
354:	learn: 0.0744518	total: 10.7s	remaining: 19.4s
355:	learn: 0.0743984	total: 10.7s	remaining: 19.4s
356:	learn: 0.0742848	total: 10.8s	remaining: 19.4s
357:	learn: 0.0742361	total: 10.8s	remaining: 19.4s
358:	learn: 0.0741611	total: 10.8s	remaining: 19.3s
359:	learn: 0.0740809	total: 10.8s	remaining: 19.3s
360:	learn: 0.0740714	total: 10.9s	remaining: 19.3s
361:	learn: 0.0739886	total: 10.9s	remaining: 19.2s
362:	learn: 0.0738977	total: 10.9s	remaining: 19.2s
363:	learn: 0.0738883	total: 11s	remaining: 19.2s
364:	learn: 0.0737895	total: 11s	remaining: 19.1s
365:	learn: 0.0737128	total: 11s	remaining: 19.1s
366:	learn: 0.0737019	total: 11.1s	remaining: 19.1s
367:	learn: 0.0736803	total: 11.1s	remaining: 19s
368:	learn: 0.0735278	total: 11.1s	remaining: 19s
369:	learn: 0.0735159	total: 11.2s	remaining: 19s
370:	learn: 0.0733791	total: 11.2s	remaining: 19s
371:	learn: 0.0732435	total: 11.2s	remaining: 18.9s
372:	learn: 0.0732355	total: 11.2s	remaining: 18.9s
373:	learn: 0.0732201	total: 11.3s	remaining: 18.9s
374:	learn: 0.0731212	total: 11.3s	remaining: 18.8s
375:	learn: 0.0730611	total: 11.3s	remaining: 18.8s
376:	learn: 0.0728489	total: 11.4s	remaining: 18.8s
377:	learn: 0.0727740	total: 11.4s	remaining: 18.7s
378:	learn: 0.0726979	total: 11.4s	remaining: 18.7s
379:	learn: 0.0726387	total: 11.4s	remaining: 18.7s
380:	learn: 0.0725793	total: 11.5s	remaining: 18.6s
381:	learn: 0.0724530	total: 11.5s	remaining: 18.7s
382:	learn: 0.0724474	total: 11.6s	remaining: 18.6s
383:	learn: 0.0724404	total: 11.6s	remaining: 18.6s
384:	learn: 0.0723383	total: 11.6s	remaining: 18.6s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'ExterCond': 1 unseen categories converted to Unseen on transform.

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Electrical': 1 unseen categories converted to Unseen on transform.

CV folds:  64%|██████▍   | 32/50 [16:54<09:27, 31.51s/fold]

999:	learn: 0.0441260	total: 30.7s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3854438	total: 23.5ms	remaining: 23.5s
1:	learn: 0.3750165	total: 53.5ms	remaining: 26.7s
2:	learn: 0.3640915	total: 82.3ms	remaining: 27.3s
3:	learn: 0.3539055	total: 111ms	remaining: 27.7s
4:	learn: 0.3443641	total: 142ms	remaining: 28.3s
5:	learn: 0.3358371	total: 171ms	remaining: 28.4s
6:	learn: 0.3266087	total: 199ms	remaining: 28.2s
7:	learn: 0.3189694	total: 227ms	remaining: 28.1s
8:	learn: 0.3111861	total: 264ms	remaining: 29s
9:	learn: 0.3035387	total: 290ms	remaining: 28.7s
10:	learn: 0.2970019	total: 318ms	remaining: 28.6s
11:	learn: 0.2899150	total: 345ms	remaining: 28.4s
12:	learn: 0.2833667	total: 376ms	remaining: 28.6s
13:	learn: 0.2774508	total: 409ms	remaining: 28.8s
14:	learn: 0.2706878	total: 437ms	remaining: 28.7s
15:	learn: 0.2649821	total: 470ms	remaining: 28.9s
16:	learn: 0.2587027	total: 502ms	remaining: 29s
17:	learn: 0.2534964	total: 530ms	remaining: 28.9s
18:	learn: 0.2481751	total: 558ms	remaining: 28.8s
19:	learn: 0.2430898	total: 588ms	remaining: 28.8s
20:	learn: 0.2383474	total: 616ms	remaining: 28.7s
21:	learn: 0.2338061	total: 644ms	remaining: 28.6s
22:	learn: 0.2294081	total: 674ms	remaining: 28.6s
23:	learn: 0.2249864	total: 707ms	remaining: 28.7s
24:	learn: 0.2210513	total: 737ms	remaining: 28.7s
25:	learn: 0.2168106	total: 767ms	remaining: 28.7s
26:	learn: 0.2130335	total: 794ms	remaining: 28.6s
27:	learn: 0.2091067	total: 840ms	remaining: 29.2s
28:	learn: 0.2053403	total: 873ms	remaining: 29.2s
29:	learn: 0.2019358	total: 906ms	remaining: 29.3s
30:	learn: 0.1986672	total: 935ms	remaining: 29.2s
31:	learn: 0.1957475	total: 965ms	remaining: 29.2s
32:	learn: 0.1927166	total: 994ms	remaining: 29.1s
33:	learn: 0.1894101	total: 1.02s	remaining: 29.1s
34:	learn: 0.1867572	total: 1.05s	remaining: 29.1s
35:	learn: 0.1837665	total: 1.08s	remaining: 29s
36:	learn: 0.1807236	total: 1.11s	remaining: 29s
37:	learn: 0.1781871	total: 1.14s	remaining: 28.9s
38:	learn: 0.1758668	total: 1.17s	remaining: 28.8s
39:	learn: 0.1735130	total: 1.2s	remaining: 28.7s
40:	learn: 0.1713094	total: 1.23s	remaining: 28.8s
41:	learn: 0.1693908	total: 1.26s	remaining: 28.7s
42:	learn: 0.1672156	total: 1.29s	remaining: 28.7s
43:	learn: 0.1649476	total: 1.31s	remaining: 28.6s
44:	learn: 0.1630507	total: 1.35s	remaining: 28.6s
45:	learn: 0.1612552	total: 1.37s	remaining: 28.5s
46:	learn: 0.1596213	total: 1.4s	remaining: 28.4s
47:	learn: 0.1578049	total: 1.43s	remaining: 28.4s
48:	learn: 0.1562229	total: 1.46s	remaining: 28.3s
49:	learn: 0.1546406	total: 1.49s	remaining: 28.3s
50:	learn: 0.1531597	total: 1.52s	remaining: 28.2s
51:	learn: 0.1518445	total: 1.55s	remaining: 28.2s
52:	learn: 0.1504972	total: 1.58s	remaining: 28.2s
53:	learn: 0.1490994	total: 1.61s	remaining: 28.2s
54:	learn: 0.1475090	total: 1.64s	remaining: 28.2s
55:	learn: 0.1462416	total: 1.67s	remaining: 28.1s
56:	learn: 0.1446802	total: 1.7s	remaining: 28.1s
57:	learn: 0.1434594	total: 1.73s	remaining: 28s
58:	learn: 0.1422896	total: 1.76s	remaining: 28s
59:	learn: 0.1413356	total: 1.79s	remaining: 28s
60:	learn: 0.1401673	total: 1.82s	remaining: 28s
61:	learn: 0.1392636	total: 1.84s	remaining: 27.8s
62:	learn: 0.1382725	total: 1.87s	remaining: 27.8s
63:	learn: 0.1371140	total: 1.9s	remaining: 27.8s
64:	learn: 0.1361260	total: 1.93s	remaining: 27.8s
65:	learn: 0.1352432	total: 1.96s	remaining: 27.7s
66:	learn: 0.1346177	total: 2s	remaining: 27.9s
67:	learn: 0.1338888	total: 2.03s	remaining: 27.9s
68:	learn: 0.1332427	total: 2.06s	remaining: 27.8s
69:	learn: 0.1322317	total: 2.09s	remaining: 27.8s
70:	learn: 0.1314166	total: 2.12s	remaining: 27.7s
71:	learn: 0.1306728	total: 2.15s	remaining: 27.7s
72:	learn: 0.1298844	total: 2.18s	remaining: 27.6s
73:	learn: 0.1291182	total: 2.21s	remaining: 27.6s
74:	learn: 0.1283541	total: 2.24s	remaining: 27.6s
75:	learn: 0.1275968	total: 2.27s	remaining: 27.6s
76:	learn: 0.1269179	total: 2.29s	remaining: 27.5s
77:	learn: 0.1261949	total: 2.33s	remaining: 27.5s
78:	learn: 0.1256121	total: 2.35s	remaining: 27.5s
79:	learn: 0.1250582	total: 2.38s	remaining: 27.4s
80:	learn: 0.1244207	total: 2.41s	remaining: 27.4s
81:	learn: 0.1238842	total: 2.44s	remaining: 27.3s
82:	learn: 0.1231799	total: 2.47s	remaining: 27.3s
83:	learn: 0.1225182	total: 2.5s	remaining: 27.3s
84:	learn: 0.1216881	total: 2.53s	remaining: 27.3s
85:	learn: 0.1212031	total: 2.56s	remaining: 27.3s
86:	learn: 0.1205913	total: 2.59s	remaining: 27.2s
87:	learn: 0.1202049	total: 2.62s	remaining: 27.2s
88:	learn: 0.1197134	total: 2.65s	remaining: 27.1s
89:	learn: 0.1191798	total: 2.68s	remaining: 27.1s
90:	learn: 0.1187459	total: 2.71s	remaining: 27s
91:	learn: 0.1183006	total: 2.73s	remaining: 27s
92:	learn: 0.1178706	total: 2.76s	remaining: 26.9s
93:	learn: 0.1173959	total: 2.79s	remaining: 26.9s
94:	learn: 0.1169657	total: 2.81s	remaining: 26.8s
95:	learn: 0.1168263	total: 2.82s	remaining: 26.6s
96:	learn: 0.1164673	total: 2.85s	remaining: 26.5s
97:	learn: 0.1159609	total: 2.88s	remaining: 26.5s
98:	learn: 0.1154844	total: 2.91s	remaining: 26.5s
99:	learn: 0.1150576	total: 2.94s	remaining: 26.4s
100:	learn: 0.1147247	total: 2.97s	remaining: 26.4s
101:	learn: 0.1143359	total: 3s	remaining: 26.4s
102:	learn: 0.1140131	total: 3.03s	remaining: 26.4s
103:	learn: 0.1136873	total: 3.06s	remaining: 26.3s
104:	learn: 0.1133787	total: 3.09s	remaining: 26.3s
105:	learn: 0.1129968	total: 3.12s	remaining: 26.3s
106:	learn: 0.1124981	total: 3.15s	remaining: 26.3s
107:	learn: 0.1121596	total: 3.18s	remaining: 26.3s
108:	learn: 0.1117626	total: 3.21s	remaining: 26.2s
109:	learn: 0.1114661	total: 3.24s	remaining: 26.2s
110:	learn: 0.1111790	total: 3.26s	remaining: 26.1s
111:	learn: 0.1108625	total: 3.29s	remaining: 26.1s
112:	learn: 0.1105836	total: 3.32s	remaining: 26.1s
113:	learn: 0.1102674	total: 3.35s	remaining: 26.1s
114:	learn: 0.1099414	total: 3.38s	remaining: 26s
115:	learn: 0.1096378	total: 3.41s	remaining: 26s
116:	learn: 0.1093005	total: 3.44s	remaining: 26s
117:	learn: 0.1089546	total: 3.47s	remaining: 25.9s
118:	learn: 0.1087205	total: 3.5s	remaining: 25.9s
119:	learn: 0.1084157	total: 3.53s	remaining: 25.9s
120:	learn: 0.1081928	total: 3.56s	remaining: 25.8s
121:	learn: 0.1078930	total: 3.59s	remaining: 25.8s
122:	learn: 0.1076961	total: 3.62s	remaining: 25.8s
123:	learn: 0.1075093	total: 3.65s	remaining: 25.8s
124:	learn: 0.1072201	total: 3.68s	remaining: 25.8s
125:	learn: 0.1070013	total: 3.71s	remaining: 25.7s
126:	learn: 0.1068191	total: 3.74s	remaining: 25.7s
127:	learn: 0.1065463	total: 3.77s	remaining: 25.7s
128:	learn: 0.1063346	total: 3.8s	remaining: 25.6s
129:	learn: 0.1060616	total: 3.83s	remaining: 25.6s
130:	learn: 0.1058738	total: 3.86s	remaining: 25.6s
131:	learn: 0.1056573	total: 3.88s	remaining: 25.5s
132:	learn: 0.1054844	total: 3.91s	remaining: 25.5s
133:	learn: 0.1053040	total: 3.94s	remaining: 25.5s
134:	learn: 0.1049270	total: 3.97s	remaining: 25.4s
135:	learn: 0.1046540	total: 4s	remaining: 25.4s
136:	learn: 0.1044690	total: 4.03s	remaining: 25.4s
137:	learn: 0.1041786	total: 4.06s	remaining: 25.4s
138:	learn: 0.1039805	total: 4.09s	remaining: 25.3s
139:	learn: 0.1037956	total: 4.12s	remaining: 25.3s
140:	learn: 0.1036105	total: 4.16s	remaining: 25.4s
141:	learn: 0.1033394	total: 4.19s	remaining: 25.3s
142:	learn: 0.1030967	total: 4.21s	remaining: 25.3s
143:	learn: 0.1028109	total: 4.25s	remaining: 25.2s
144:	learn: 0.1025640	total: 4.27s	remaining: 25.2s
145:	learn: 0.1023106	total: 4.3s	remaining: 25.2s
146:	learn: 0.1020924	total: 4.33s	remaining: 25.2s
147:	learn: 0.1017984	total: 4.36s	remaining: 25.1s
148:	learn: 0.1015182	total: 4.39s	remaining: 25.1s
149:	learn: 0.1012731	total: 4.42s	remaining: 25s
150:	learn: 0.1010309	total: 4.45s	remaining: 25s
151:	learn: 0.1008189	total: 4.48s	remaining: 25s
152:	learn: 0.1006849	total: 4.51s	remaining: 25s
153:	learn: 0.1004667	total: 4.54s	remaining: 24.9s
154:	learn: 0.1003373	total: 4.56s	remaining: 24.9s
155:	learn: 0.1001575	total: 4.59s	remaining: 24.8s
156:	learn: 0.0999842	total: 4.62s	remaining: 24.8s
157:	learn: 0.0998395	total: 4.65s	remaining: 24.8s
158:	learn: 0.0996967	total: 4.68s	remaining: 24.7s
159:	learn: 0.0995069	total: 4.71s	remaining: 24.7s
160:	learn: 0.0992697	total: 4.74s	remaining: 24.7s
161:	learn: 0.0991217	total: 4.77s	remaining: 24.7s
162:	learn: 0.0989312	total: 4.8s	remaining: 24.6s
163:	learn: 0.0986598	total: 4.83s	remaining: 24.6s
164:	learn: 0.0985068	total: 4.86s	remaining: 24.6s
165:	learn: 0.0983601	total: 4.88s	remaining: 24.5s
166:	learn: 0.0982156	total: 4.91s	remaining: 24.5s
167:	learn: 0.0980593	total: 4.94s	remaining: 24.5s
168:	learn: 0.0978884	total: 4.97s	remaining: 24.4s
169:	learn: 0.0977539	total: 5s	remaining: 24.4s
170:	learn: 0.0976281	total: 5.03s	remaining: 24.4s
171:	learn: 0.0974470	total: 5.06s	remaining: 24.4s
172:	learn: 0.0972785	total: 5.09s	remaining: 24.4s
173:	learn: 0.0970893	total: 5.13s	remaining: 24.3s
174:	learn: 0.0969262	total: 5.16s	remaining: 24.3s
175:	learn: 0.0967827	total: 5.2s	remaining: 24.4s
176:	learn: 0.0966468	total: 5.23s	remaining: 24.3s
177:	learn: 0.0965077	total: 5.26s	remaining: 24.3s
178:	learn: 0.0962467	total: 5.29s	remaining: 24.3s
179:	learn: 0.0961053	total: 5.33s	remaining: 24.3s
180:	learn: 0.0959343	total: 5.38s	remaining: 24.3s
181:	learn: 0.0957446	total: 5.41s	remaining: 24.3s
182:	learn: 0.0955730	total: 5.44s	remaining: 24.3s
183:	learn: 0.0953860	total: 5.46s	remaining: 24.2s
184:	learn: 0.0951694	total: 5.49s	remaining: 24.2s
185:	learn: 0.0948903	total: 5.52s	remaining: 24.2s
186:	learn: 0.0946461	total: 5.55s	remaining: 24.1s
187:	learn: 0.0945477	total: 5.58s	remaining: 24.1s
188:	learn: 0.0943785	total: 5.61s	remaining: 24.1s
189:	learn: 0.0942557	total: 5.64s	remaining: 24s
190:	learn: 0.0940432	total: 5.67s	remaining: 24s
191:	learn: 0.0939434	total: 5.7s	remaining: 24s
192:	learn: 0.0937612	total: 5.72s	remaining: 23.9s
193:	learn: 0.0936371	total: 5.75s	remaining: 23.9s
194:	learn: 0.0934712	total: 5.78s	remaining: 23.9s
195:	learn: 0.0933194	total: 5.81s	remaining: 23.8s
196:	learn: 0.0932504	total: 5.84s	remaining: 23.8s
197:	learn: 0.0931012	total: 5.87s	remaining: 23.8s
198:	learn: 0.0929371	total: 5.9s	remaining: 23.7s
199:	learn: 0.0928395	total: 5.93s	remaining: 23.7s
200:	learn: 0.0926803	total: 5.96s	remaining: 23.7s
201:	learn: 0.0925422	total: 5.99s	remaining: 23.7s
202:	learn: 0.0923255	total: 6.02s	remaining: 23.6s
203:	learn: 0.0921251	total: 6.05s	remaining: 23.6s
204:	learn: 0.0919491	total: 6.08s	remaining: 23.6s
205:	learn: 0.0918597	total: 6.11s	remaining: 23.6s
206:	learn: 0.0917209	total: 6.14s	remaining: 23.5s
207:	learn: 0.0916364	total: 6.18s	remaining: 23.5s
208:	learn: 0.0914620	total: 6.21s	remaining: 23.5s
209:	learn: 0.0913645	total: 6.24s	remaining: 23.5s
210:	learn: 0.0912300	total: 6.26s	remaining: 23.4s
211:	learn: 0.0911557	total: 6.3s	remaining: 23.4s
212:	learn: 0.0909639	total: 6.33s	remaining: 23.4s
213:	learn: 0.0908396	total: 6.36s	remaining: 23.4s
214:	learn: 0.0907304	total: 6.39s	remaining: 23.3s
215:	learn: 0.0906011	total: 6.42s	remaining: 23.3s
216:	learn: 0.0905307	total: 6.45s	remaining: 23.3s
217:	learn: 0.0904703	total: 6.48s	remaining: 23.2s
218:	learn: 0.0903413	total: 6.51s	remaining: 23.2s
219:	learn: 0.0902670	total: 6.54s	remaining: 23.2s
220:	learn: 0.0901270	total: 6.57s	remaining: 23.2s
221:	learn: 0.0899759	total: 6.6s	remaining: 23.1s
222:	learn: 0.0899177	total: 6.63s	remaining: 23.1s
223:	learn: 0.0897674	total: 6.66s	remaining: 23.1s
224:	learn: 0.0896475	total: 6.69s	remaining: 23s
225:	learn: 0.0894975	total: 6.72s	remaining: 23s
226:	learn: 0.0893539	total: 6.75s	remaining: 23s
227:	learn: 0.0892134	total: 6.78s	remaining: 23s
228:	learn: 0.0891231	total: 6.81s	remaining: 22.9s
229:	learn: 0.0890098	total: 6.85s	remaining: 22.9s
230:	learn: 0.0888781	total: 6.88s	remaining: 22.9s
231:	learn: 0.0887589	total: 6.91s	remaining: 22.9s
232:	learn: 0.0886746	total: 6.94s	remaining: 22.8s
233:	learn: 0.0885363	total: 6.97s	remaining: 22.8s
234:	learn: 0.0884097	total: 7s	remaining: 22.8s
235:	learn: 0.0882530	total: 7.03s	remaining: 22.8s
236:	learn: 0.0882056	total: 7.06s	remaining: 22.7s
237:	learn: 0.0880375	total: 7.09s	remaining: 22.7s
238:	learn: 0.0878597	total: 7.12s	remaining: 22.7s
239:	learn: 0.0877207	total: 7.15s	remaining: 22.6s
240:	learn: 0.0875568	total: 7.18s	remaining: 22.6s
241:	learn: 0.0875053	total: 7.21s	remaining: 22.6s
242:	learn: 0.0873635	total: 7.24s	remaining: 22.5s
243:	learn: 0.0873148	total: 7.27s	remaining: 22.5s
244:	learn: 0.0872391	total: 7.29s	remaining: 22.5s
245:	learn: 0.0871999	total: 7.32s	remaining: 22.4s
246:	learn: 0.0870922	total: 7.35s	remaining: 22.4s
247:	learn: 0.0870653	total: 7.38s	remaining: 22.4s
248:	learn: 0.0868994	total: 7.41s	remaining: 22.3s
249:	learn: 0.0867657	total: 7.43s	remaining: 22.3s
250:	learn: 0.0866773	total: 7.46s	remaining: 22.3s
251:	learn: 0.0866259	total: 7.49s	remaining: 22.2s
252:	learn: 0.0865087	total: 7.52s	remaining: 22.2s
253:	learn: 0.0864086	total: 7.55s	remaining: 22.2s
254:	learn: 0.0862964	total: 7.58s	remaining: 22.1s
255:	learn: 0.0861929	total: 7.61s	remaining: 22.1s
256:	learn: 0.0861332	total: 7.65s	remaining: 22.1s
257:	learn: 0.0860109	total: 7.68s	remaining: 22.1s
258:	learn: 0.0858609	total: 7.71s	remaining: 22.1s
259:	learn: 0.0857571	total: 7.74s	remaining: 22s
260:	learn: 0.0857287	total: 7.77s	remaining: 22s
261:	learn: 0.0856994	total: 7.8s	remaining: 22s
262:	learn: 0.0856729	total: 7.83s	remaining: 21.9s
263:	learn: 0.0855160	total: 7.86s	remaining: 21.9s
264:	learn: 0.0853808	total: 7.89s	remaining: 21.9s
265:	learn: 0.0852448	total: 7.92s	remaining: 21.9s
266:	learn: 0.0852144	total: 7.95s	remaining: 21.8s
267:	learn: 0.0851025	total: 7.98s	remaining: 21.8s
268:	learn: 0.0849210	total: 8.01s	remaining: 21.8s
269:	learn: 0.0847918	total: 8.04s	remaining: 21.7s
270:	learn: 0.0846708	total: 8.07s	remaining: 21.7s
271:	learn: 0.0846264	total: 8.11s	remaining: 21.7s
272:	learn: 0.0845232	total: 8.13s	remaining: 21.7s
273:	learn: 0.0844496	total: 8.17s	remaining: 21.6s
274:	learn: 0.0842207	total: 8.2s	remaining: 21.6s
275:	learn: 0.0842005	total: 8.23s	remaining: 21.6s
276:	learn: 0.0841422	total: 8.26s	remaining: 21.6s
277:	learn: 0.0840700	total: 8.29s	remaining: 21.5s
278:	learn: 0.0838567	total: 8.32s	remaining: 21.5s
279:	learn: 0.0838309	total: 8.35s	remaining: 21.5s
280:	learn: 0.0837049	total: 8.38s	remaining: 21.4s
281:	learn: 0.0836076	total: 8.4s	remaining: 21.4s
282:	learn: 0.0835183	total: 8.44s	remaining: 21.4s
283:	learn: 0.0834368	total: 8.48s	remaining: 21.4s
284:	learn: 0.0833315	total: 8.51s	remaining: 21.3s
285:	learn: 0.0832938	total: 8.54s	remaining: 21.3s
286:	learn: 0.0831683	total: 8.57s	remaining: 21.3s
287:	learn: 0.0831296	total: 8.6s	remaining: 21.3s
288:	learn: 0.0830784	total: 8.63s	remaining: 21.2s
289:	learn: 0.0830583	total: 8.66s	remaining: 21.2s
290:	learn: 0.0828994	total: 8.69s	remaining: 21.2s
291:	learn: 0.0828567	total: 8.72s	remaining: 21.2s
292:	learn: 0.0827813	total: 8.75s	remaining: 21.1s
293:	learn: 0.0827065	total: 8.79s	remaining: 21.1s
294:	learn: 0.0825969	total: 8.81s	remaining: 21.1s
295:	learn: 0.0824599	total: 8.84s	remaining: 21s
296:	learn: 0.0824123	total: 8.87s	remaining: 21s
297:	learn: 0.0823273	total: 8.9s	remaining: 21s
298:	learn: 0.0822886	total: 8.93s	remaining: 20.9s
299:	learn: 0.0821473	total: 8.96s	remaining: 20.9s
300:	learn: 0.0820158	total: 8.98s	remaining: 20.9s
301:	learn: 0.0819492	total: 9.01s	remaining: 20.8s
302:	learn: 0.0819222	total: 9.04s	remaining: 20.8s
303:	learn: 0.0817644	total: 9.07s	remaining: 20.8s
304:	learn: 0.0816559	total: 9.1s	remaining: 20.7s
305:	learn: 0.0815568	total: 9.13s	remaining: 20.7s
306:	learn: 0.0814938	total: 9.16s	remaining: 20.7s
307:	learn: 0.0813814	total: 9.19s	remaining: 20.7s
308:	learn: 0.0813299	total: 9.22s	remaining: 20.6s
309:	learn: 0.0812215	total: 9.25s	remaining: 20.6s
310:	learn: 0.0811758	total: 9.28s	remaining: 20.6s
311:	learn: 0.0810663	total: 9.31s	remaining: 20.5s
312:	learn: 0.0810182	total: 9.35s	remaining: 20.5s
313:	learn: 0.0809015	total: 9.38s	remaining: 20.5s
314:	learn: 0.0808762	total: 9.41s	remaining: 20.5s
315:	learn: 0.0807849	total: 9.44s	remaining: 20.4s
316:	learn: 0.0807527	total: 9.47s	remaining: 20.4s
317:	learn: 0.0806690	total: 9.5s	remaining: 20.4s
318:	learn: 0.0805341	total: 9.53s	remaining: 20.3s
319:	learn: 0.0804635	total: 9.55s	remaining: 20.3s
320:	learn: 0.0803456	total: 9.6s	remaining: 20.3s
321:	learn: 0.0802837	total: 9.64s	remaining: 20.3s
322:	learn: 0.0801714	total: 9.67s	remaining: 20.3s
323:	learn: 0.0801303	total: 9.7s	remaining: 20.2s
324:	learn: 0.0800853	total: 9.72s	remaining: 20.2s
325:	learn: 0.0799915	total: 9.75s	remaining: 20.2s
326:	learn: 0.0797799	total: 9.78s	remaining: 20.1s
327:	learn: 0.0796664	total: 9.81s	remaining: 20.1s
328:	learn: 0.0796399	total: 9.85s	remaining: 20.1s
329:	learn: 0.0795665	total: 9.88s	remaining: 20.1s
330:	learn: 0.0794646	total: 9.9s	remaining: 20s
331:	learn: 0.0793236	total: 9.94s	remaining: 20s
332:	learn: 0.0792832	total: 9.97s	remaining: 20s
333:	learn: 0.0791565	total: 10s	remaining: 19.9s
334:	learn: 0.0790589	total: 10s	remaining: 19.9s
335:	learn: 0.0789299	total: 10.1s	remaining: 19.9s
336:	learn: 0.0789037	total: 10.1s	remaining: 19.9s
337:	learn: 0.0788434	total: 10.1s	remaining: 19.8s
338:	learn: 0.0788100	total: 10.2s	remaining: 19.8s
339:	learn: 0.0787967	total: 10.2s	remaining: 19.8s
340:	learn: 0.0787392	total: 10.2s	remaining: 19.7s
341:	learn: 0.0786964	total: 10.2s	remaining: 19.7s
342:	learn: 0.0786809	total: 10.3s	remaining: 19.7s
343:	learn: 0.0786473	total: 10.3s	remaining: 19.6s
344:	learn: 0.0786134	total: 10.3s	remaining: 19.6s
345:	learn: 0.0784616	total: 10.4s	remaining: 19.6s
346:	learn: 0.0784366	total: 10.4s	remaining: 19.5s
347:	learn: 0.0783895	total: 10.4s	remaining: 19.5s
348:	learn: 0.0783739	total: 10.4s	remaining: 19.5s
349:	learn: 0.0782830	total: 10.5s	remaining: 19.5s
350:	learn: 0.0782510	total: 10.5s	remaining: 19.4s
351:	learn: 0.0781023	total: 10.5s	remaining: 19.4s
352:	learn: 0.0780716	total: 10.6s	remaining: 19.4s
353:	learn: 0.0780124	total: 10.6s	remaining: 19.4s
354:	learn: 0.0778544	total: 10.6s	remaining: 19.3s
355:	learn: 0.0777363	total: 10.7s	remaining: 19.3s
356:	learn: 0.0776159	total: 10.7s	remaining: 19.3s
357:	learn: 0.0775144	total: 10.7s	remaining: 19.3s
358:	learn: 0.0774940	total: 10.8s	remaining: 19.2s
359:	learn: 0.0774767	total: 10.8s	remaining: 19.2s
360:	learn: 0.0774325	total: 10.8s	remaining: 19.2s
361:	learn: 0.0773993	total: 10.9s	remaining: 19.1s
362:	learn: 0.0772780	total: 10.9s	remaining: 19.1s
363:	learn: 0.0772037	total: 10.9s	remaining: 19.1s
364:	learn: 0.0771626	total: 10.9s	remaining: 19s
365:	learn: 0.0771332	total: 11s	remaining: 19s
366:	learn: 0.0770894	total: 11s	remaining: 19s
367:	learn: 0.0770386	total: 11s	remaining: 19s
368:	learn: 0.0769795	total: 11.1s	remaining: 18.9s
369:	learn: 0.0769611	total: 11.1s	remaining: 18.9s
370:	learn: 0.0769193	total: 11.1s	remaining: 18.9s
371:	learn: 0.0768730	total: 11.2s	remaining: 18.9s
372:	learn: 0.0767601	total: 11.2s	remaining: 18.8s
373:	learn: 0.0766773	total: 11.2s	remaining: 18.8s
374:	learn: 0.0765989	total: 11.3s	remaining: 18.8s
375:	learn: 0.0765074	total: 11.3s	remaining: 18.7s
376:	learn: 0.0764432	total: 11.3s	remaining: 18.7s
377:	learn: 0.0764047	total: 11.3s	remaining: 18.7s
378:	learn: 0.0763877	total: 11.4s	remaining: 18.7s
379:	learn: 0.0763129	total: 11.4s	remaining: 18.6s
380:	learn: 0.0762407	total: 11.4s	remaining: 18.6s
381:	learn: 0.0761512	total: 11.5s	remaining: 18.6s
382:	learn: 0.0760556	total: 11.5s	remaining: 18.5s
383:	learn: 0.0760076	total: 11.5s	remaining: 18.5s
384:	learn: 0.0759203	total: 11.6s	remaining: 18.5s
385:	learn: 0.0758316	total: 11.6s	remaining: 18.4s
386:	learn: 0.0757616	total: 11.6s	remaining: 18.4s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Functional': 1 unseen categories converted to Unseen on transform.

CV folds:  66%|██████▌   | 33/50 [17:25<08:52, 31.31s/fold]

Learning rate set to 0.042738
0:	learn: 0.3858262	total: 27.3ms	remaining: 27.2s
1:	learn: 0.3754890	total: 55.8ms	remaining: 27.8s
2:	learn: 0.3651639	total: 86.8ms	remaining: 28.8s
3:	learn: 0.3559326	total: 117ms	remaining: 29.1s
4:	learn: 0.3465722	total: 147ms	remaining: 29.2s
5:	learn: 0.3375065	total: 177ms	remaining: 29.4s
6:	learn: 0.3289742	total: 224ms	remaining: 31.8s
7:	learn: 0.3204754	total: 311ms	remaining: 38.6s
8:	learn: 0.3123288	total: 338ms	remaining: 37.2s
9:	learn: 0.3043391	total: 367ms	remaining: 36.3s
10:	learn: 0.2966989	total: 395ms	remaining: 35.5s
11:	learn: 0.2902964	total: 422ms	remaining: 34.7s
12:	learn: 0.2830170	total: 452ms	remaining: 34.4s
13:	learn: 0.2766382	total: 481ms	remaining: 33.9s
14:	learn: 0.2702361	total: 510ms	remaining: 33.5s
15:	learn: 0.2643159	total: 539ms	remaining: 33.1s
16:	learn: 0.2589362	total: 570ms	remaining: 32.9s
17:	learn: 0.2530926	total: 601ms	remaining: 32.8s
18:	learn: 0.2478045	total: 629ms	remaining: 32.5s
19:	learn: 0.2436144	total: 658ms	remaining: 32.3s
20:	learn: 0.2387050	total: 689ms	remaining: 32.1s
21:	learn: 0.2337723	total: 720ms	remaining: 32s
22:	learn: 0.2289179	total: 750ms	remaining: 31.9s
23:	learn: 0.2242304	total: 780ms	remaining: 31.7s
24:	learn: 0.2203501	total: 808ms	remaining: 31.5s
25:	learn: 0.2163328	total: 836ms	remaining: 31.3s
26:	learn: 0.2124427	total: 865ms	remaining: 31.2s
27:	learn: 0.2083662	total: 898ms	remaining: 31.2s
28:	learn: 0.2044329	total: 929ms	remaining: 31.1s
29:	learn: 0.2007899	total: 958ms	remaining: 31s
30:	learn: 0.1972086	total: 986ms	remaining: 30.8s
31:	learn: 0.1941824	total: 1.01s	remaining: 30.7s
32:	learn: 0.1913988	total: 1.04s	remaining: 30.6s
33:	learn: 0.1883628	total: 1.07s	remaining: 30.5s
34:	learn: 0.1851838	total: 1.1s	remaining: 30.3s
35:	learn: 0.1826449	total: 1.13s	remaining: 30.2s
36:	learn: 0.1801055	total: 1.16s	remaining: 30.1s
37:	learn: 0.1774648	total: 1.19s	remaining: 30.1s
38:	learn: 0.1751388	total: 1.22s	remaining: 30s
39:	learn: 0.1728462	total: 1.25s	remaining: 30s
40:	learn: 0.1704497	total: 1.28s	remaining: 29.9s
41:	learn: 0.1682907	total: 1.31s	remaining: 29.8s
42:	learn: 0.1665685	total: 1.33s	remaining: 29.7s
43:	learn: 0.1648542	total: 1.36s	remaining: 29.7s
44:	learn: 0.1627520	total: 1.39s	remaining: 29.6s
45:	learn: 0.1610584	total: 1.42s	remaining: 29.5s
46:	learn: 0.1590662	total: 1.45s	remaining: 29.4s
47:	learn: 0.1575031	total: 1.5s	remaining: 29.8s
48:	learn: 0.1556440	total: 1.53s	remaining: 29.7s
49:	learn: 0.1543463	total: 1.56s	remaining: 29.6s
50:	learn: 0.1529036	total: 1.59s	remaining: 29.6s
51:	learn: 0.1511950	total: 1.62s	remaining: 29.6s
52:	learn: 0.1497310	total: 1.65s	remaining: 29.5s
53:	learn: 0.1483777	total: 1.68s	remaining: 29.5s
54:	learn: 0.1471133	total: 1.71s	remaining: 29.3s
55:	learn: 0.1456803	total: 1.74s	remaining: 29.3s
56:	learn: 0.1440494	total: 1.77s	remaining: 29.2s
57:	learn: 0.1426883	total: 1.8s	remaining: 29.2s
58:	learn: 0.1413585	total: 1.83s	remaining: 29.2s
59:	learn: 0.1402105	total: 1.86s	remaining: 29.1s
60:	learn: 0.1391519	total: 1.89s	remaining: 29.1s
61:	learn: 0.1380662	total: 1.92s	remaining: 29s
62:	learn: 0.1369645	total: 1.95s	remaining: 29s
63:	learn: 0.1360552	total: 1.98s	remaining: 29s
64:	learn: 0.1350556	total: 2.01s	remaining: 28.9s
65:	learn: 0.1340729	total: 2.04s	remaining: 28.9s
66:	learn: 0.1332659	total: 2.08s	remaining: 28.9s
67:	learn: 0.1321343	total: 2.11s	remaining: 28.9s
68:	learn: 0.1312434	total: 2.14s	remaining: 28.8s
69:	learn: 0.1304451	total: 2.17s	remaining: 28.8s
70:	learn: 0.1296658	total: 2.2s	remaining: 28.7s
71:	learn: 0.1287919	total: 2.22s	remaining: 28.7s
72:	learn: 0.1280210	total: 2.25s	remaining: 28.6s
73:	learn: 0.1270511	total: 2.28s	remaining: 28.6s
74:	learn: 0.1261023	total: 2.31s	remaining: 28.5s
75:	learn: 0.1255222	total: 2.34s	remaining: 28.5s
76:	learn: 0.1247816	total: 2.37s	remaining: 28.4s
77:	learn: 0.1242678	total: 2.4s	remaining: 28.4s
78:	learn: 0.1235369	total: 2.43s	remaining: 28.4s
79:	learn: 0.1229398	total: 2.46s	remaining: 28.3s
80:	learn: 0.1224179	total: 2.49s	remaining: 28.3s
81:	learn: 0.1219111	total: 2.52s	remaining: 28.2s
82:	learn: 0.1212584	total: 2.55s	remaining: 28.2s
83:	learn: 0.1205252	total: 2.58s	remaining: 28.1s
84:	learn: 0.1200426	total: 2.61s	remaining: 28.1s
85:	learn: 0.1194455	total: 2.64s	remaining: 28.1s
86:	learn: 0.1190264	total: 2.67s	remaining: 28s
87:	learn: 0.1186273	total: 2.7s	remaining: 28s
88:	learn: 0.1181280	total: 2.73s	remaining: 28s
89:	learn: 0.1177291	total: 2.76s	remaining: 27.9s
90:	learn: 0.1173295	total: 2.79s	remaining: 27.9s
91:	learn: 0.1168701	total: 2.82s	remaining: 27.8s
92:	learn: 0.1163556	total: 2.85s	remaining: 27.8s
93:	learn: 0.1159184	total: 2.88s	remaining: 27.8s
94:	learn: 0.1155542	total: 2.91s	remaining: 27.7s
95:	learn: 0.1151116	total: 2.94s	remaining: 27.7s
96:	learn: 0.1146555	total: 2.97s	remaining: 27.7s
97:	learn: 0.1142763	total: 3s	remaining: 27.6s
98:	learn: 0.1139013	total: 3.03s	remaining: 27.6s
99:	learn: 0.1135374	total: 3.06s	remaining: 27.5s
100:	learn: 0.1131937	total: 3.08s	remaining: 27.4s
101:	learn: 0.1128751	total: 3.11s	remaining: 27.4s
102:	learn: 0.1125728	total: 3.14s	remaining: 27.4s
103:	learn: 0.1122436	total: 3.17s	remaining: 27.3s
104:	learn: 0.1118846	total: 3.2s	remaining: 27.3s
105:	learn: 0.1116756	total: 3.23s	remaining: 27.2s
106:	learn: 0.1113292	total: 3.25s	remaining: 27.2s
107:	learn: 0.1108681	total: 3.28s	remaining: 27.1s
108:	learn: 0.1106338	total: 3.31s	remaining: 27.1s
109:	learn: 0.1104083	total: 3.34s	remaining: 27.1s
110:	learn: 0.1100720	total: 3.37s	remaining: 27s
111:	learn: 0.1096898	total: 3.4s	remaining: 27s
112:	learn: 0.1094326	total: 3.43s	remaining: 27s
113:	learn: 0.1090267	total: 3.47s	remaining: 26.9s
114:	learn: 0.1088366	total: 3.49s	remaining: 26.9s
115:	learn: 0.1086003	total: 3.52s	remaining: 26.9s
116:	learn: 0.1081959	total: 3.55s	remaining: 26.8s
117:	learn: 0.1078264	total: 3.58s	remaining: 26.8s
118:	learn: 0.1075863	total: 3.61s	remaining: 26.7s
119:	learn: 0.1073443	total: 3.65s	remaining: 26.8s
120:	learn: 0.1071153	total: 3.69s	remaining: 26.8s
121:	learn: 0.1067908	total: 3.71s	remaining: 26.7s
122:	learn: 0.1065087	total: 3.74s	remaining: 26.7s
123:	learn: 0.1061364	total: 3.77s	remaining: 26.6s
124:	learn: 0.1059080	total: 3.8s	remaining: 26.6s
125:	learn: 0.1058116	total: 3.82s	remaining: 26.5s
126:	learn: 0.1055855	total: 3.85s	remaining: 26.5s
127:	learn: 0.1052551	total: 3.88s	remaining: 26.5s
128:	learn: 0.1050451	total: 3.91s	remaining: 26.4s
129:	learn: 0.1048831	total: 3.94s	remaining: 26.4s
130:	learn: 0.1046830	total: 3.97s	remaining: 26.3s
131:	learn: 0.1044291	total: 4s	remaining: 26.3s
132:	learn: 0.1043010	total: 4.03s	remaining: 26.3s
133:	learn: 0.1041280	total: 4.06s	remaining: 26.3s
134:	learn: 0.1040089	total: 4.09s	remaining: 26.2s
135:	learn: 0.1037400	total: 4.12s	remaining: 26.2s
136:	learn: 0.1035257	total: 4.15s	remaining: 26.1s
137:	learn: 0.1033326	total: 4.18s	remaining: 26.1s
138:	learn: 0.1030737	total: 4.2s	remaining: 26s
139:	learn: 0.1029038	total: 4.23s	remaining: 26s
140:	learn: 0.1027481	total: 4.26s	remaining: 26s
141:	learn: 0.1024995	total: 4.29s	remaining: 25.9s
142:	learn: 0.1023195	total: 4.32s	remaining: 25.9s
143:	learn: 0.1021553	total: 4.35s	remaining: 25.9s
144:	learn: 0.1019103	total: 4.38s	remaining: 25.8s
145:	learn: 0.1017448	total: 4.41s	remaining: 25.8s
146:	learn: 0.1015645	total: 4.44s	remaining: 25.8s
147:	learn: 0.1014121	total: 4.47s	remaining: 25.7s
148:	learn: 0.1012366	total: 4.5s	remaining: 25.7s
149:	learn: 0.1010387	total: 4.53s	remaining: 25.7s
150:	learn: 0.1008280	total: 4.56s	remaining: 25.7s
151:	learn: 0.1006421	total: 4.59s	remaining: 25.6s
152:	learn: 0.1003557	total: 4.62s	remaining: 25.6s
153:	learn: 0.1002427	total: 4.65s	remaining: 25.5s
154:	learn: 0.1001036	total: 4.67s	remaining: 25.5s
155:	learn: 0.0997763	total: 4.72s	remaining: 25.6s
156:	learn: 0.0994965	total: 4.75s	remaining: 25.5s
157:	learn: 0.0993418	total: 4.78s	remaining: 25.5s
158:	learn: 0.0991746	total: 4.81s	remaining: 25.4s
159:	learn: 0.0990830	total: 4.84s	remaining: 25.4s
160:	learn: 0.0989083	total: 4.87s	remaining: 25.4s
161:	learn: 0.0987109	total: 4.9s	remaining: 25.3s
162:	learn: 0.0983695	total: 4.93s	remaining: 25.3s
163:	learn: 0.0980975	total: 4.95s	remaining: 25.3s
164:	learn: 0.0979115	total: 4.98s	remaining: 25.2s
165:	learn: 0.0977783	total: 5.01s	remaining: 25.2s
166:	learn: 0.0976937	total: 5.04s	remaining: 25.1s
167:	learn: 0.0975012	total: 5.07s	remaining: 25.1s
168:	learn: 0.0973332	total: 5.1s	remaining: 25.1s
169:	learn: 0.0970900	total: 5.13s	remaining: 25s
170:	learn: 0.0969431	total: 5.16s	remaining: 25s
171:	learn: 0.0967550	total: 5.18s	remaining: 24.9s
172:	learn: 0.0966493	total: 5.21s	remaining: 24.9s
173:	learn: 0.0965074	total: 5.24s	remaining: 24.9s
174:	learn: 0.0962341	total: 5.27s	remaining: 24.8s
175:	learn: 0.0960777	total: 5.3s	remaining: 24.8s
176:	learn: 0.0958960	total: 5.33s	remaining: 24.8s
177:	learn: 0.0957284	total: 5.37s	remaining: 24.8s
178:	learn: 0.0955733	total: 5.4s	remaining: 24.8s
179:	learn: 0.0953447	total: 5.43s	remaining: 24.7s
180:	learn: 0.0952360	total: 5.46s	remaining: 24.7s
181:	learn: 0.0950576	total: 5.49s	remaining: 24.7s
182:	learn: 0.0947988	total: 5.52s	remaining: 24.7s
183:	learn: 0.0947488	total: 5.55s	remaining: 24.6s
184:	learn: 0.0946523	total: 5.58s	remaining: 24.6s
185:	learn: 0.0944685	total: 5.62s	remaining: 24.6s
186:	learn: 0.0943552	total: 5.64s	remaining: 24.5s
187:	learn: 0.0942662	total: 5.67s	remaining: 24.5s
188:	learn: 0.0941204	total: 5.7s	remaining: 24.5s
189:	learn: 0.0940224	total: 5.73s	remaining: 24.4s
190:	learn: 0.0938763	total: 5.76s	remaining: 24.4s
191:	learn: 0.0935866	total: 5.81s	remaining: 24.4s
192:	learn: 0.0934228	total: 5.84s	remaining: 24.4s
193:	learn: 0.0932717	total: 5.86s	remaining: 24.4s
194:	learn: 0.0931484	total: 5.89s	remaining: 24.3s
195:	learn: 0.0930063	total: 5.92s	remaining: 24.3s
196:	learn: 0.0928237	total: 5.95s	remaining: 24.3s
197:	learn: 0.0926946	total: 5.98s	remaining: 24.2s
198:	learn: 0.0925400	total: 6.01s	remaining: 24.2s
199:	learn: 0.0923921	total: 6.04s	remaining: 24.2s
200:	learn: 0.0921800	total: 6.08s	remaining: 24.1s
201:	learn: 0.0920483	total: 6.11s	remaining: 24.1s
202:	learn: 0.0917866	total: 6.13s	remaining: 24.1s
203:	learn: 0.0916929	total: 6.16s	remaining: 24s
204:	learn: 0.0916588	total: 6.19s	remaining: 24s
205:	learn: 0.0915548	total: 6.22s	remaining: 24s
206:	learn: 0.0913301	total: 6.25s	remaining: 23.9s
207:	learn: 0.0911363	total: 6.28s	remaining: 23.9s
208:	learn: 0.0910173	total: 6.31s	remaining: 23.9s
209:	learn: 0.0908412	total: 6.34s	remaining: 23.9s
210:	learn: 0.0907090	total: 6.37s	remaining: 23.8s
211:	learn: 0.0905677	total: 6.4s	remaining: 23.8s
212:	learn: 0.0903514	total: 6.44s	remaining: 23.8s
213:	learn: 0.0901841	total: 6.47s	remaining: 23.8s
214:	learn: 0.0900899	total: 6.5s	remaining: 23.7s
215:	learn: 0.0899813	total: 6.53s	remaining: 23.7s
216:	learn: 0.0898871	total: 6.56s	remaining: 23.7s
217:	learn: 0.0897190	total: 6.59s	remaining: 23.6s
218:	learn: 0.0895389	total: 6.62s	remaining: 23.6s
219:	learn: 0.0893459	total: 6.65s	remaining: 23.6s
220:	learn: 0.0892677	total: 6.68s	remaining: 23.6s
221:	learn: 0.0891287	total: 6.71s	remaining: 23.5s
222:	learn: 0.0890758	total: 6.74s	remaining: 23.5s
223:	learn: 0.0888641	total: 6.77s	remaining: 23.5s
224:	learn: 0.0887463	total: 6.8s	remaining: 23.4s
225:	learn: 0.0885453	total: 6.83s	remaining: 23.4s
226:	learn: 0.0884461	total: 6.86s	remaining: 23.4s
227:	learn: 0.0882553	total: 6.89s	remaining: 23.3s
228:	learn: 0.0881850	total: 6.92s	remaining: 23.3s
229:	learn: 0.0881548	total: 6.95s	remaining: 23.3s
230:	learn: 0.0880770	total: 6.97s	remaining: 23.2s
231:	learn: 0.0878768	total: 7s	remaining: 23.2s
232:	learn: 0.0877111	total: 7.04s	remaining: 23.2s
233:	learn: 0.0876491	total: 7.07s	remaining: 23.1s
234:	learn: 0.0875885	total: 7.1s	remaining: 23.1s
235:	learn: 0.0873896	total: 7.13s	remaining: 23.1s
236:	learn: 0.0873190	total: 7.16s	remaining: 23.1s
237:	learn: 0.0872192	total: 7.19s	remaining: 23s
238:	learn: 0.0871116	total: 7.22s	remaining: 23s
239:	learn: 0.0870299	total: 7.25s	remaining: 23s
240:	learn: 0.0869772	total: 7.28s	remaining: 22.9s
241:	learn: 0.0868221	total: 7.31s	remaining: 22.9s
242:	learn: 0.0867399	total: 7.34s	remaining: 22.9s
243:	learn: 0.0866854	total: 7.37s	remaining: 22.8s
244:	learn: 0.0866446	total: 7.4s	remaining: 22.8s
245:	learn: 0.0865769	total: 7.43s	remaining: 22.8s
246:	learn: 0.0865120	total: 7.46s	remaining: 22.7s
247:	learn: 0.0864370	total: 7.49s	remaining: 22.7s
248:	learn: 0.0864107	total: 7.52s	remaining: 22.7s
249:	learn: 0.0863941	total: 7.55s	remaining: 22.6s
250:	learn: 0.0862864	total: 7.57s	remaining: 22.6s
251:	learn: 0.0862518	total: 7.6s	remaining: 22.6s
252:	learn: 0.0861840	total: 7.63s	remaining: 22.5s
253:	learn: 0.0860690	total: 7.66s	remaining: 22.5s
254:	learn: 0.0860164	total: 7.69s	remaining: 22.5s
255:	learn: 0.0859801	total: 7.72s	remaining: 22.4s
256:	learn: 0.0859359	total: 7.75s	remaining: 22.4s
257:	learn: 0.0858601	total: 7.78s	remaining: 22.4s
258:	learn: 0.0856341	total: 7.81s	remaining: 22.3s
259:	learn: 0.0855501	total: 7.84s	remaining: 22.3s
260:	learn: 0.0854364	total: 7.87s	remaining: 22.3s
261:	learn: 0.0854038	total: 7.89s	remaining: 22.2s
262:	learn: 0.0853276	total: 7.92s	remaining: 22.2s
263:	learn: 0.0851923	total: 7.96s	remaining: 22.2s
264:	learn: 0.0850931	total: 8s	remaining: 22.2s
265:	learn: 0.0849938	total: 8.03s	remaining: 22.2s
266:	learn: 0.0848648	total: 8.06s	remaining: 22.1s
267:	learn: 0.0847355	total: 8.1s	remaining: 22.1s
268:	learn: 0.0845992	total: 8.13s	remaining: 22.1s
269:	learn: 0.0845393	total: 8.16s	remaining: 22.1s
270:	learn: 0.0844453	total: 8.19s	remaining: 22s
271:	learn: 0.0843807	total: 8.22s	remaining: 22s
272:	learn: 0.0843567	total: 8.26s	remaining: 22s
273:	learn: 0.0842060	total: 8.29s	remaining: 22s
274:	learn: 0.0841798	total: 8.32s	remaining: 21.9s
275:	learn: 0.0841403	total: 8.35s	remaining: 21.9s
276:	learn: 0.0840774	total: 8.38s	remaining: 21.9s
277:	learn: 0.0840154	total: 8.41s	remaining: 21.8s
278:	learn: 0.0839245	total: 8.44s	remaining: 21.8s
279:	learn: 0.0838834	total: 8.46s	remaining: 21.8s
280:	learn: 0.0837629	total: 8.49s	remaining: 21.7s
281:	learn: 0.0836652	total: 8.53s	remaining: 21.7s
282:	learn: 0.0836287	total: 8.56s	remaining: 21.7s
283:	learn: 0.0835463	total: 8.59s	remaining: 21.6s
284:	learn: 0.0834586	total: 8.61s	remaining: 21.6s
285:	learn: 0.0832633	total: 8.64s	remaining: 21.6s
286:	learn: 0.0830591	total: 8.67s	remaining: 21.5s
287:	learn: 0.0830378	total: 8.7s	remaining: 21.5s
288:	learn: 0.0829165	total: 8.73s	remaining: 21.5s
289:	learn: 0.0827840	total: 8.76s	remaining: 21.5s
290:	learn: 0.0827459	total: 8.79s	remaining: 21.4s
291:	learn: 0.0826198	total: 8.82s	remaining: 21.4s
292:	learn: 0.0825503	total: 8.85s	remaining: 21.4s
293:	learn: 0.0825117	total: 8.88s	remaining: 21.3s
294:	learn: 0.0824776	total: 8.91s	remaining: 21.3s
295:	learn: 0.0823759	total: 8.96s	remaining: 21.3s
296:	learn: 0.0823581	total: 8.99s	remaining: 21.3s
297:	learn: 0.0822586	total: 9.02s	remaining: 21.2s
298:	learn: 0.0821098	total: 9.05s	remaining: 21.2s
299:	learn: 0.0820762	total: 9.08s	remaining: 21.2s
300:	learn: 0.0819944	total: 9.11s	remaining: 21.2s
301:	learn: 0.0818171	total: 9.14s	remaining: 21.1s
302:	learn: 0.0817554	total: 9.17s	remaining: 21.1s
303:	learn: 0.0817231	total: 9.2s	remaining: 21.1s
304:	learn: 0.0816360	total: 9.23s	remaining: 21s
305:	learn: 0.0815131	total: 9.26s	remaining: 21s
306:	learn: 0.0814824	total: 9.29s	remaining: 21s
307:	learn: 0.0813808	total: 9.32s	remaining: 20.9s
308:	learn: 0.0812624	total: 9.35s	remaining: 20.9s
309:	learn: 0.0811980	total: 9.38s	remaining: 20.9s
310:	learn: 0.0810063	total: 9.41s	remaining: 20.8s
311:	learn: 0.0809539	total: 9.44s	remaining: 20.8s
312:	learn: 0.0808545	total: 9.47s	remaining: 20.8s
313:	learn: 0.0806981	total: 9.5s	remaining: 20.8s
314:	learn: 0.0806760	total: 9.54s	remaining: 20.7s
315:	learn: 0.0806570	total: 9.57s	remaining: 20.7s
316:	learn: 0.0806480	total: 9.61s	remaining: 20.7s
317:	learn: 0.0806167	total: 9.64s	remaining: 20.7s
318:	learn: 0.0805623	total: 9.67s	remaining: 20.6s
319:	learn: 0.0805430	total: 9.7s	remaining: 20.6s
320:	learn: 0.0804369	total: 9.73s	remaining: 20.6s
321:	learn: 0.0803716	total: 9.77s	remaining: 20.6s
322:	learn: 0.0803249	total: 9.81s	remaining: 20.6s
323:	learn: 0.0801357	total: 9.84s	remaining: 20.5s
324:	learn: 0.0800310	total: 9.87s	remaining: 20.5s
325:	learn: 0.0799422	total: 9.9s	remaining: 20.5s
326:	learn: 0.0799021	total: 9.93s	remaining: 20.4s
327:	learn: 0.0798825	total: 9.96s	remaining: 20.4s
328:	learn: 0.0797601	total: 9.99s	remaining: 20.4s
329:	learn: 0.0796089	total: 10s	remaining: 20.4s
330:	learn: 0.0795687	total: 10.1s	remaining: 20.3s
331:	learn: 0.0794431	total: 10.1s	remaining: 20.3s
332:	learn: 0.0794062	total: 10.1s	remaining: 20.3s
333:	learn: 0.0793150	total: 10.2s	remaining: 20.3s
334:	learn: 0.0792219	total: 10.2s	remaining: 20.2s
335:	learn: 0.0790825	total: 10.2s	remaining: 20.2s
336:	learn: 0.0790513	total: 10.3s	remaining: 20.2s
337:	learn: 0.0789864	total: 10.3s	remaining: 20.2s
338:	learn: 0.0788999	total: 10.3s	remaining: 20.1s
339:	learn: 0.0787919	total: 10.3s	remaining: 20.1s
340:	learn: 0.0787529	total: 10.4s	remaining: 20.1s
341:	learn: 0.0786765	total: 10.4s	remaining: 20s
342:	learn: 0.0786604	total: 10.4s	remaining: 20s
343:	learn: 0.0785732	total: 10.5s	remaining: 20s
344:	learn: 0.0785372	total: 10.5s	remaining: 19.9s
345:	learn: 0.0783636	total: 10.6s	remaining: 19.9s
346:	learn: 0.0783040	total: 10.6s	remaining: 19.9s
347:	learn: 0.0782129	total: 10.6s	remaining: 19.9s
348:	learn: 0.0780973	total: 10.6s	remaining: 19.9s
349:	learn: 0.0779679	total: 10.7s	remaining: 19.8s
350:	learn: 0.0778887	total: 10.7s	remaining: 19.8s
351:	learn: 0.0778668	total: 10.7s	remaining: 19.8s
352:	learn: 0.0777756	total: 10.8s	remaining: 19.7s
353:	learn: 0.0777343	total: 10.8s	remaining: 19.7s
354:	learn: 0.0777260	total: 10.8s	remaining: 19.7s
355:	learn: 0.0776703	total: 10.9s	remaining: 19.6s
356:	learn: 0.0776310	total: 10.9s	remaining: 19.6s
357:	learn: 0.0775248	total: 10.9s	remaining: 19.6s
358:	learn: 0.0774552	total: 11s	remaining: 19.6s
359:	learn: 0.0773259	total: 11s	remaining: 19.5s
360:	learn: 0.0773168	total: 11s	remaining: 19.5s
361:	learn: 0.0772193	total: 11s	remaining: 19.5s
362:	learn: 0.0771333	total: 11.1s	remaining: 19.4s
363:	learn: 0.0770241	total: 11.1s	remaining: 19.4s
364:	learn: 0.0770074	total: 11.1s	remaining: 19.4s
365:	learn: 0.0768836	total: 11.2s	remaining: 19.3s
366:	learn: 0.0768128	total: 11.2s	remaining: 19.3s
367:	learn: 0.0767576	total: 11.2s	remaining: 19.3s
368:	learn: 0.0767366	total: 11.3s	remaining: 19.2s
369:	learn: 0.0767294	total: 11.3s	remaining: 19.2s
370:	learn: 0.0766690	total: 11.3s	remaining: 19.2s
371:	learn: 0.0765271	total: 11.3s	remaining: 19.1s
372:	learn: 0.0764786	total: 11.4s	remaining: 19.1s
373:	learn: 0.0764546	total: 11.4s	remaining: 19.1s
374:	learn: 0.0764495	total: 11.4s	remaining: 19.1s
375:	learn: 0.0764401	total: 11.5s	remaining: 19s
376:	learn: 0.0763278	total: 11.5s	remaining: 19s
377:	learn: 0.0762086	total: 11.5s	remaining: 19s
378:	learn: 0.0761652	total: 11.5s	remaining: 18.9s
379:	learn: 0.0760086	total: 11.6s	remaining: 18.9s
380:	learn: 0.0759014	total: 11.6s	remaining: 18.9s
381:	learn: 0.0758667	total: 11.6s	remaining: 18.8s
382:	learn: 0.0757704	total: 11.7s	remaining: 18.8s
383:	learn: 0.0757011	total: 11.7s	remaining: 18.8s
384:	learn: 0.0756561	total: 11.7s	remaining: 18.7s
385:	learn: 0.0755510	total: 11.8s	remaining: 18.7s
386:	learn: 0.0755394	total: 11.8s	remaining: 18.7s
387:	learn: 0.0754541	total: 11.8s	remaining: 18.6s

CV folds:  68%|██████▊   | 34/50 [17:56<08:20, 31.28s/fold]

998:	learn: 0.0448554	total: 30.7s	remaining: 30.7ms
999:	learn: 0.0448326	total: 30.7s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3891763	total: 22.5ms	remaining: 22.5s
1:	learn: 0.3791746	total: 51.7ms	remaining: 25.8s
2:	learn: 0.3689695	total: 81.1ms	remaining: 26.9s
3:	learn: 0.3584702	total: 110ms	remaining: 27.4s
4:	learn: 0.3490978	total: 138ms	remaining: 27.4s
5:	learn: 0.3399121	total: 166ms	remaining: 27.4s
6:	learn: 0.3313311	total: 195ms	remaining: 27.7s
7:	learn: 0.3221211	total: 223ms	remaining: 27.7s
8:	learn: 0.3146700	total: 253ms	remaining: 27.8s
9:	learn: 0.3066339	total: 283ms	remaining: 28s
10:	learn: 0.2991998	total: 312ms	remaining: 28s
11:	learn: 0.2923676	total: 341ms	remaining: 28s
12:	learn: 0.2856468	total: 370ms	remaining: 28.1s
13:	learn: 0.2784852	total: 398ms	remaining: 28s
14:	learn: 0.2718951	total: 427ms	remaining: 28s
15:	learn: 0.2659776	total: 457ms	remaining: 28.1s
16:	learn: 0.2608492	total: 488ms	remaining: 28.2s
17:	learn: 0.2550233	total: 515ms	remaining: 28.1s
18:	learn: 0.2494233	total: 543ms	remaining: 28s
19:	learn: 0.2440679	total: 571ms	remaining: 28s
20:	learn: 0.2385825	total: 597ms	remaining: 27.8s
21:	learn: 0.2336453	total: 627ms	remaining: 27.9s
22:	learn: 0.2290507	total: 669ms	remaining: 28.4s
23:	learn: 0.2242475	total: 696ms	remaining: 28.3s
24:	learn: 0.2198001	total: 724ms	remaining: 28.2s
25:	learn: 0.2155519	total: 752ms	remaining: 28.2s
26:	learn: 0.2113878	total: 781ms	remaining: 28.2s
27:	learn: 0.2076394	total: 810ms	remaining: 28.1s
28:	learn: 0.2036217	total: 840ms	remaining: 28.1s
29:	learn: 0.1997984	total: 868ms	remaining: 28.1s
30:	learn: 0.1963089	total: 898ms	remaining: 28.1s
31:	learn: 0.1934690	total: 930ms	remaining: 28.1s
32:	learn: 0.1905104	total: 958ms	remaining: 28.1s
33:	learn: 0.1876202	total: 988ms	remaining: 28.1s
34:	learn: 0.1846580	total: 1.02s	remaining: 28s
35:	learn: 0.1818372	total: 1.04s	remaining: 28s
36:	learn: 0.1795130	total: 1.07s	remaining: 27.9s
37:	learn: 0.1771315	total: 1.1s	remaining: 27.8s
38:	learn: 0.1749962	total: 1.13s	remaining: 27.9s
39:	learn: 0.1724944	total: 1.16s	remaining: 27.9s
40:	learn: 0.1702212	total: 1.19s	remaining: 27.9s
41:	learn: 0.1679934	total: 1.22s	remaining: 27.9s
42:	learn: 0.1656590	total: 1.25s	remaining: 27.9s
43:	learn: 0.1636375	total: 1.28s	remaining: 27.8s
44:	learn: 0.1614887	total: 1.31s	remaining: 27.8s
45:	learn: 0.1592818	total: 1.34s	remaining: 27.8s
46:	learn: 0.1575821	total: 1.37s	remaining: 27.8s
47:	learn: 0.1557394	total: 1.4s	remaining: 27.8s
48:	learn: 0.1540343	total: 1.43s	remaining: 27.7s
49:	learn: 0.1525112	total: 1.46s	remaining: 27.7s
50:	learn: 0.1509022	total: 1.49s	remaining: 27.7s
51:	learn: 0.1492635	total: 1.52s	remaining: 27.7s
52:	learn: 0.1477249	total: 1.55s	remaining: 27.6s
53:	learn: 0.1461816	total: 1.57s	remaining: 27.6s
54:	learn: 0.1448668	total: 1.6s	remaining: 27.6s
55:	learn: 0.1436957	total: 1.64s	remaining: 27.6s
56:	learn: 0.1425556	total: 1.66s	remaining: 27.5s
57:	learn: 0.1412922	total: 1.69s	remaining: 27.5s
58:	learn: 0.1399842	total: 1.72s	remaining: 27.5s
59:	learn: 0.1385961	total: 1.75s	remaining: 27.5s
60:	learn: 0.1374143	total: 1.78s	remaining: 27.4s
61:	learn: 0.1362896	total: 1.81s	remaining: 27.4s
62:	learn: 0.1352854	total: 1.84s	remaining: 27.4s
63:	learn: 0.1343666	total: 1.87s	remaining: 27.3s
64:	learn: 0.1335529	total: 1.9s	remaining: 27.4s
65:	learn: 0.1327568	total: 1.93s	remaining: 27.3s
66:	learn: 0.1318075	total: 1.96s	remaining: 27.3s
67:	learn: 0.1308721	total: 1.99s	remaining: 27.3s
68:	learn: 0.1298826	total: 2.02s	remaining: 27.2s
69:	learn: 0.1291532	total: 2.05s	remaining: 27.2s
70:	learn: 0.1284056	total: 2.08s	remaining: 27.2s
71:	learn: 0.1275821	total: 2.1s	remaining: 27.1s
72:	learn: 0.1267898	total: 2.13s	remaining: 27.1s
73:	learn: 0.1259026	total: 2.17s	remaining: 27.1s
74:	learn: 0.1250956	total: 2.19s	remaining: 27.1s
75:	learn: 0.1242248	total: 2.22s	remaining: 27s
76:	learn: 0.1235187	total: 2.25s	remaining: 27s
77:	learn: 0.1227294	total: 2.28s	remaining: 27s
78:	learn: 0.1220842	total: 2.31s	remaining: 27s
79:	learn: 0.1215849	total: 2.34s	remaining: 26.9s
80:	learn: 0.1207448	total: 2.37s	remaining: 26.9s
81:	learn: 0.1201489	total: 2.39s	remaining: 26.8s
82:	learn: 0.1197171	total: 2.42s	remaining: 26.8s
83:	learn: 0.1190698	total: 2.45s	remaining: 26.8s
84:	learn: 0.1186021	total: 2.48s	remaining: 26.8s
85:	learn: 0.1180343	total: 2.51s	remaining: 26.7s
86:	learn: 0.1175023	total: 2.54s	remaining: 26.7s
87:	learn: 0.1169933	total: 2.57s	remaining: 26.7s
88:	learn: 0.1165036	total: 2.6s	remaining: 26.6s
89:	learn: 0.1159807	total: 2.63s	remaining: 26.6s
90:	learn: 0.1155080	total: 2.65s	remaining: 26.5s
91:	learn: 0.1150419	total: 2.68s	remaining: 26.5s
92:	learn: 0.1145926	total: 2.71s	remaining: 26.4s
93:	learn: 0.1142203	total: 2.75s	remaining: 26.5s
94:	learn: 0.1138121	total: 2.77s	remaining: 26.4s
95:	learn: 0.1134462	total: 2.82s	remaining: 26.5s
96:	learn: 0.1130213	total: 2.86s	remaining: 26.7s
97:	learn: 0.1124820	total: 2.9s	remaining: 26.7s
98:	learn: 0.1120431	total: 2.93s	remaining: 26.6s
99:	learn: 0.1116375	total: 2.96s	remaining: 26.7s
100:	learn: 0.1112284	total: 2.99s	remaining: 26.6s
101:	learn: 0.1108461	total: 3.02s	remaining: 26.6s
102:	learn: 0.1104751	total: 3.05s	remaining: 26.5s
103:	learn: 0.1101806	total: 3.08s	remaining: 26.5s
104:	learn: 0.1098282	total: 3.1s	remaining: 26.4s
105:	learn: 0.1093975	total: 3.13s	remaining: 26.4s
106:	learn: 0.1091176	total: 3.16s	remaining: 26.4s
107:	learn: 0.1086774	total: 3.19s	remaining: 26.4s
108:	learn: 0.1083938	total: 3.22s	remaining: 26.3s
109:	learn: 0.1080614	total: 3.25s	remaining: 26.3s
110:	learn: 0.1077233	total: 3.28s	remaining: 26.3s
111:	learn: 0.1072792	total: 3.31s	remaining: 26.3s
112:	learn: 0.1070149	total: 3.34s	remaining: 26.2s
113:	learn: 0.1067234	total: 3.38s	remaining: 26.3s
114:	learn: 0.1064351	total: 3.41s	remaining: 26.2s
115:	learn: 0.1060459	total: 3.43s	remaining: 26.2s
116:	learn: 0.1057759	total: 3.46s	remaining: 26.1s
117:	learn: 0.1055752	total: 3.5s	remaining: 26.1s
118:	learn: 0.1052382	total: 3.52s	remaining: 26.1s
119:	learn: 0.1050045	total: 3.55s	remaining: 26.1s
120:	learn: 0.1047525	total: 3.58s	remaining: 26s
121:	learn: 0.1044648	total: 3.61s	remaining: 26s
122:	learn: 0.1041819	total: 3.65s	remaining: 26s
123:	learn: 0.1039523	total: 3.67s	remaining: 26s
124:	learn: 0.1038035	total: 3.7s	remaining: 25.9s
125:	learn: 0.1034546	total: 3.73s	remaining: 25.9s
126:	learn: 0.1032816	total: 3.76s	remaining: 25.9s
127:	learn: 0.1030412	total: 3.79s	remaining: 25.8s
128:	learn: 0.1029247	total: 3.81s	remaining: 25.7s
129:	learn: 0.1027956	total: 3.84s	remaining: 25.7s
130:	learn: 0.1025605	total: 3.86s	remaining: 25.6s
131:	learn: 0.1022877	total: 3.89s	remaining: 25.6s
132:	learn: 0.1019887	total: 3.92s	remaining: 25.6s
133:	learn: 0.1017428	total: 3.96s	remaining: 25.6s
134:	learn: 0.1015265	total: 3.98s	remaining: 25.5s
135:	learn: 0.1011818	total: 4.01s	remaining: 25.5s
136:	learn: 0.1009864	total: 4.04s	remaining: 25.5s
137:	learn: 0.1007131	total: 4.07s	remaining: 25.4s
138:	learn: 0.1003969	total: 4.1s	remaining: 25.4s
139:	learn: 0.1002734	total: 4.13s	remaining: 25.4s
140:	learn: 0.1000721	total: 4.16s	remaining: 25.3s
141:	learn: 0.0998998	total: 4.19s	remaining: 25.3s
142:	learn: 0.0996724	total: 4.22s	remaining: 25.3s
143:	learn: 0.0994496	total: 4.25s	remaining: 25.3s
144:	learn: 0.0991903	total: 4.3s	remaining: 25.4s
145:	learn: 0.0990352	total: 4.34s	remaining: 25.4s
146:	learn: 0.0988858	total: 4.37s	remaining: 25.3s
147:	learn: 0.0986342	total: 4.4s	remaining: 25.3s
148:	learn: 0.0984724	total: 4.43s	remaining: 25.3s
149:	learn: 0.0981890	total: 4.46s	remaining: 25.3s
150:	learn: 0.0980239	total: 4.49s	remaining: 25.2s
151:	learn: 0.0978958	total: 4.51s	remaining: 25.2s
152:	learn: 0.0976859	total: 4.55s	remaining: 25.2s
153:	learn: 0.0975057	total: 4.58s	remaining: 25.2s
154:	learn: 0.0974227	total: 4.59s	remaining: 25s
155:	learn: 0.0971166	total: 4.62s	remaining: 25s
156:	learn: 0.0969303	total: 4.65s	remaining: 25s
157:	learn: 0.0966951	total: 4.68s	remaining: 24.9s
158:	learn: 0.0964634	total: 4.71s	remaining: 24.9s
159:	learn: 0.0962759	total: 4.74s	remaining: 24.9s
160:	learn: 0.0961332	total: 4.77s	remaining: 24.8s
161:	learn: 0.0960069	total: 4.79s	remaining: 24.8s
162:	learn: 0.0959093	total: 4.81s	remaining: 24.7s
163:	learn: 0.0957587	total: 4.84s	remaining: 24.7s
164:	learn: 0.0954661	total: 4.87s	remaining: 24.6s
165:	learn: 0.0953123	total: 4.91s	remaining: 24.7s
166:	learn: 0.0949711	total: 4.95s	remaining: 24.7s
167:	learn: 0.0948297	total: 4.98s	remaining: 24.7s
168:	learn: 0.0946477	total: 5.01s	remaining: 24.7s
169:	learn: 0.0944338	total: 5.04s	remaining: 24.6s
170:	learn: 0.0942234	total: 5.07s	remaining: 24.6s
171:	learn: 0.0939881	total: 5.1s	remaining: 24.6s
172:	learn: 0.0937621	total: 5.13s	remaining: 24.5s
173:	learn: 0.0936000	total: 5.17s	remaining: 24.5s
174:	learn: 0.0934633	total: 5.2s	remaining: 24.5s
175:	learn: 0.0933534	total: 5.23s	remaining: 24.5s
176:	learn: 0.0932252	total: 5.26s	remaining: 24.4s
177:	learn: 0.0931234	total: 5.29s	remaining: 24.4s
178:	learn: 0.0930205	total: 5.32s	remaining: 24.4s
179:	learn: 0.0928333	total: 5.35s	remaining: 24.4s
180:	learn: 0.0926799	total: 5.38s	remaining: 24.3s
181:	learn: 0.0925202	total: 5.41s	remaining: 24.3s
182:	learn: 0.0924099	total: 5.44s	remaining: 24.3s
183:	learn: 0.0922761	total: 5.47s	remaining: 24.3s
184:	learn: 0.0920422	total: 5.5s	remaining: 24.2s
185:	learn: 0.0918260	total: 5.53s	remaining: 24.2s
186:	learn: 0.0916772	total: 5.56s	remaining: 24.2s
187:	learn: 0.0915196	total: 5.58s	remaining: 24.1s
188:	learn: 0.0913620	total: 5.61s	remaining: 24.1s
189:	learn: 0.0912623	total: 5.64s	remaining: 24.1s
190:	learn: 0.0912126	total: 5.67s	remaining: 24s
191:	learn: 0.0911065	total: 5.71s	remaining: 24s
192:	learn: 0.0909799	total: 5.73s	remaining: 24s
193:	learn: 0.0908412	total: 5.76s	remaining: 23.9s
194:	learn: 0.0907512	total: 5.79s	remaining: 23.9s
195:	learn: 0.0905488	total: 5.82s	remaining: 23.9s
196:	learn: 0.0903969	total: 5.85s	remaining: 23.9s
197:	learn: 0.0902742	total: 5.88s	remaining: 23.8s
198:	learn: 0.0902376	total: 5.91s	remaining: 23.8s
199:	learn: 0.0900731	total: 5.94s	remaining: 23.8s
200:	learn: 0.0899936	total: 5.99s	remaining: 23.8s
201:	learn: 0.0899173	total: 6.03s	remaining: 23.8s
202:	learn: 0.0897626	total: 6.06s	remaining: 23.8s
203:	learn: 0.0897100	total: 6.09s	remaining: 23.8s
204:	learn: 0.0895442	total: 6.12s	remaining: 23.7s
205:	learn: 0.0894253	total: 6.16s	remaining: 23.7s
206:	learn: 0.0893417	total: 6.19s	remaining: 23.7s
207:	learn: 0.0892206	total: 6.22s	remaining: 23.7s
208:	learn: 0.0889566	total: 6.25s	remaining: 23.7s
209:	learn: 0.0888476	total: 6.28s	remaining: 23.6s
210:	learn: 0.0887825	total: 6.31s	remaining: 23.6s
211:	learn: 0.0886901	total: 6.34s	remaining: 23.6s
212:	learn: 0.0885338	total: 6.37s	remaining: 23.5s
213:	learn: 0.0884386	total: 6.4s	remaining: 23.5s
214:	learn: 0.0883269	total: 6.43s	remaining: 23.5s
215:	learn: 0.0881461	total: 6.46s	remaining: 23.4s
216:	learn: 0.0880779	total: 6.49s	remaining: 23.4s
217:	learn: 0.0879570	total: 6.52s	remaining: 23.4s
218:	learn: 0.0879144	total: 6.55s	remaining: 23.4s
219:	learn: 0.0878538	total: 6.58s	remaining: 23.3s
220:	learn: 0.0877809	total: 6.61s	remaining: 23.3s
221:	learn: 0.0877275	total: 6.64s	remaining: 23.3s
222:	learn: 0.0875575	total: 6.67s	remaining: 23.2s
223:	learn: 0.0875240	total: 6.7s	remaining: 23.2s
224:	learn: 0.0873854	total: 6.73s	remaining: 23.2s
225:	learn: 0.0872709	total: 6.76s	remaining: 23.1s
226:	learn: 0.0870777	total: 6.79s	remaining: 23.1s
227:	learn: 0.0869657	total: 6.82s	remaining: 23.1s
228:	learn: 0.0869499	total: 6.84s	remaining: 23s
229:	learn: 0.0868244	total: 6.88s	remaining: 23s
230:	learn: 0.0867815	total: 6.9s	remaining: 23s
231:	learn: 0.0866759	total: 6.94s	remaining: 23s
232:	learn: 0.0866068	total: 6.96s	remaining: 22.9s
233:	learn: 0.0864644	total: 7s	remaining: 22.9s
234:	learn: 0.0863487	total: 7.02s	remaining: 22.9s
235:	learn: 0.0862238	total: 7.06s	remaining: 22.9s
236:	learn: 0.0861908	total: 7.1s	remaining: 22.8s
237:	learn: 0.0860433	total: 7.14s	remaining: 22.8s
238:	learn: 0.0859304	total: 7.17s	remaining: 22.8s
239:	learn: 0.0859077	total: 7.2s	remaining: 22.8s
240:	learn: 0.0857518	total: 7.23s	remaining: 22.8s
241:	learn: 0.0856951	total: 7.27s	remaining: 22.8s
242:	learn: 0.0856749	total: 7.3s	remaining: 22.7s
243:	learn: 0.0855711	total: 7.33s	remaining: 22.7s
244:	learn: 0.0854678	total: 7.36s	remaining: 22.7s
245:	learn: 0.0853852	total: 7.38s	remaining: 22.6s
246:	learn: 0.0853121	total: 7.42s	remaining: 22.6s
247:	learn: 0.0852431	total: 7.45s	remaining: 22.6s
248:	learn: 0.0850686	total: 7.47s	remaining: 22.5s
249:	learn: 0.0849842	total: 7.5s	remaining: 22.5s
250:	learn: 0.0848515	total: 7.54s	remaining: 22.5s
251:	learn: 0.0847168	total: 7.57s	remaining: 22.5s
252:	learn: 0.0845811	total: 7.6s	remaining: 22.4s
253:	learn: 0.0843542	total: 7.63s	remaining: 22.4s
254:	learn: 0.0841039	total: 7.66s	remaining: 22.4s
255:	learn: 0.0840019	total: 7.69s	remaining: 22.3s
256:	learn: 0.0839235	total: 7.72s	remaining: 22.3s
257:	learn: 0.0837611	total: 7.75s	remaining: 22.3s
258:	learn: 0.0835749	total: 7.78s	remaining: 22.3s
259:	learn: 0.0834349	total: 7.81s	remaining: 22.2s
260:	learn: 0.0833895	total: 7.84s	remaining: 22.2s
261:	learn: 0.0833371	total: 7.87s	remaining: 22.2s
262:	learn: 0.0833205	total: 7.9s	remaining: 22.1s
263:	learn: 0.0831519	total: 7.93s	remaining: 22.1s
264:	learn: 0.0830881	total: 7.96s	remaining: 22.1s
265:	learn: 0.0829019	total: 7.99s	remaining: 22s
266:	learn: 0.0828214	total: 8.02s	remaining: 22s
267:	learn: 0.0827507	total: 8.06s	remaining: 22s
268:	learn: 0.0826901	total: 8.09s	remaining: 22s
269:	learn: 0.0825708	total: 8.12s	remaining: 22s
270:	learn: 0.0824256	total: 8.15s	remaining: 21.9s
271:	learn: 0.0822798	total: 8.18s	remaining: 21.9s
272:	learn: 0.0821586	total: 8.21s	remaining: 21.9s
273:	learn: 0.0821319	total: 8.24s	remaining: 21.8s
274:	learn: 0.0819225	total: 8.27s	remaining: 21.8s
275:	learn: 0.0818192	total: 8.3s	remaining: 21.8s
276:	learn: 0.0817170	total: 8.34s	remaining: 21.8s
277:	learn: 0.0816428	total: 8.37s	remaining: 21.7s
278:	learn: 0.0815948	total: 8.4s	remaining: 21.7s
279:	learn: 0.0813988	total: 8.43s	remaining: 21.7s
280:	learn: 0.0813182	total: 8.46s	remaining: 21.6s
281:	learn: 0.0811746	total: 8.49s	remaining: 21.6s
282:	learn: 0.0811501	total: 8.52s	remaining: 21.6s
283:	learn: 0.0810790	total: 8.55s	remaining: 21.6s
284:	learn: 0.0810581	total: 8.58s	remaining: 21.5s
285:	learn: 0.0810446	total: 8.61s	remaining: 21.5s
286:	learn: 0.0810287	total: 8.64s	remaining: 21.5s
287:	learn: 0.0808968	total: 8.67s	remaining: 21.4s
288:	learn: 0.0808767	total: 8.72s	remaining: 21.5s
289:	learn: 0.0807128	total: 8.76s	remaining: 21.4s
290:	learn: 0.0805659	total: 8.78s	remaining: 21.4s
291:	learn: 0.0804903	total: 8.81s	remaining: 21.4s
292:	learn: 0.0802720	total: 8.84s	remaining: 21.3s
293:	learn: 0.0802594	total: 8.87s	remaining: 21.3s
294:	learn: 0.0802429	total: 8.9s	remaining: 21.3s
295:	learn: 0.0800912	total: 8.93s	remaining: 21.2s
296:	learn: 0.0799889	total: 8.95s	remaining: 21.2s
297:	learn: 0.0798488	total: 8.99s	remaining: 21.2s
298:	learn: 0.0796762	total: 9.02s	remaining: 21.1s
299:	learn: 0.0796043	total: 9.05s	remaining: 21.1s
300:	learn: 0.0795112	total: 9.08s	remaining: 21.1s
301:	learn: 0.0794337	total: 9.11s	remaining: 21s
302:	learn: 0.0793607	total: 9.13s	remaining: 21s
303:	learn: 0.0791938	total: 9.16s	remaining: 21s
304:	learn: 0.0791294	total: 9.2s	remaining: 21s
305:	learn: 0.0790474	total: 9.23s	remaining: 20.9s
306:	learn: 0.0790268	total: 9.28s	remaining: 20.9s
307:	learn: 0.0788535	total: 9.31s	remaining: 20.9s
308:	learn: 0.0788158	total: 9.34s	remaining: 20.9s
309:	learn: 0.0787612	total: 9.37s	remaining: 20.9s
310:	learn: 0.0787523	total: 9.4s	remaining: 20.8s
311:	learn: 0.0786806	total: 9.43s	remaining: 20.8s
312:	learn: 0.0785832	total: 9.46s	remaining: 20.8s
313:	learn: 0.0785208	total: 9.49s	remaining: 20.7s
314:	learn: 0.0783305	total: 9.52s	remaining: 20.7s
315:	learn: 0.0782946	total: 9.55s	remaining: 20.7s
316:	learn: 0.0781162	total: 9.58s	remaining: 20.6s
317:	learn: 0.0780667	total: 9.62s	remaining: 20.6s
318:	learn: 0.0779849	total: 9.64s	remaining: 20.6s
319:	learn: 0.0779241	total: 9.67s	remaining: 20.6s
320:	learn: 0.0777982	total: 9.7s	remaining: 20.5s
321:	learn: 0.0776656	total: 9.73s	remaining: 20.5s
322:	learn: 0.0776572	total: 9.77s	remaining: 20.5s
323:	learn: 0.0776027	total: 9.79s	remaining: 20.4s
324:	learn: 0.0775064	total: 9.82s	remaining: 20.4s
325:	learn: 0.0774642	total: 9.85s	remaining: 20.4s
326:	learn: 0.0773743	total: 9.88s	remaining: 20.3s
327:	learn: 0.0773632	total: 9.91s	remaining: 20.3s
328:	learn: 0.0773436	total: 9.94s	remaining: 20.3s
329:	learn: 0.0772709	total: 9.97s	remaining: 20.2s
330:	learn: 0.0772197	total: 10s	remaining: 20.2s
331:	learn: 0.0771720	total: 10s	remaining: 20.2s
332:	learn: 0.0771637	total: 10.1s	remaining: 20.2s
333:	learn: 0.0770378	total: 10.1s	remaining: 20.1s
334:	learn: 0.0769402	total: 10.1s	remaining: 20.1s
335:	learn: 0.0769324	total: 10.2s	remaining: 20.1s
336:	learn: 0.0768616	total: 10.2s	remaining: 20s
337:	learn: 0.0768310	total: 10.2s	remaining: 20s
338:	learn: 0.0767251	total: 10.3s	remaining: 20s
339:	learn: 0.0767061	total: 10.3s	remaining: 20s
340:	learn: 0.0766464	total: 10.3s	remaining: 19.9s
341:	learn: 0.0764991	total: 10.3s	remaining: 19.9s
342:	learn: 0.0763085	total: 10.4s	remaining: 19.9s
343:	learn: 0.0761801	total: 10.4s	remaining: 19.8s
344:	learn: 0.0761739	total: 10.4s	remaining: 19.8s
345:	learn: 0.0760768	total: 10.5s	remaining: 19.8s
346:	learn: 0.0760311	total: 10.5s	remaining: 19.7s
347:	learn: 0.0759802	total: 10.5s	remaining: 19.7s
348:	learn: 0.0758786	total: 10.5s	remaining: 19.7s
349:	learn: 0.0757178	total: 10.6s	remaining: 19.6s
350:	learn: 0.0756421	total: 10.6s	remaining: 19.6s
351:	learn: 0.0755492	total: 10.6s	remaining: 19.6s
352:	learn: 0.0754136	total: 10.7s	remaining: 19.5s
353:	learn: 0.0753073	total: 10.7s	remaining: 19.5s
354:	learn: 0.0752997	total: 10.7s	remaining: 19.5s
355:	learn: 0.0752943	total: 10.8s	remaining: 19.4s
356:	learn: 0.0751714	total: 10.8s	remaining: 19.4s
357:	learn: 0.0751554	total: 10.8s	remaining: 19.4s
358:	learn: 0.0751178	total: 10.8s	remaining: 19.4s
359:	learn: 0.0750852	total: 10.9s	remaining: 19.3s
360:	learn: 0.0749954	total: 10.9s	remaining: 19.3s
361:	learn: 0.0749891	total: 10.9s	remaining: 19.3s
362:	learn: 0.0749096	total: 11s	remaining: 19.3s
363:	learn: 0.0748479	total: 11s	remaining: 19.3s
364:	learn: 0.0748364	total: 11s	remaining: 19.2s
365:	learn: 0.0748047	total: 11.1s	remaining: 19.2s
366:	learn: 0.0747981	total: 11.1s	remaining: 19.2s
367:	learn: 0.0747575	total: 11.1s	remaining: 19.1s
368:	learn: 0.0746016	total: 11.2s	remaining: 19.1s
369:	learn: 0.0744771	total: 11.2s	remaining: 19.1s
370:	learn: 0.0743773	total: 11.2s	remaining: 19s
371:	learn: 0.0743215	total: 11.3s	remaining: 19s
372:	learn: 0.0742111	total: 11.3s	remaining: 19s
373:	learn: 0.0742082	total: 11.3s	remaining: 18.9s
374:	learn: 0.0740660	total: 11.3s	remaining: 18.9s
375:	learn: 0.0739664	total: 11.4s	remaining: 18.9s
376:	learn: 0.0738438	total: 11.4s	remaining: 18.9s
377:	learn: 0.0738344	total: 11.5s	remaining: 18.8s
378:	learn: 0.0738303	total: 11.5s	remaining: 18.8s
379:	learn: 0.0736886	total: 11.5s	remaining: 18.8s
380:	learn: 0.0736663	total: 11.5s	remaining: 18.7s
381:	learn: 0.0736606	total: 11.6s	remaining: 18.7s
382:	learn: 0.0735684	total: 11.6s	remaining: 18.7s
383:	learn: 0.0735650	total: 11.6s	remaining: 18.7s
384:	learn: 0.0734902	total: 11.7s	remaining: 18.7s
385:	learn: 0.0734008	total: 11.7s	remaining: 18.6s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior1st': 1 unseen categories converted to Unseen on transform.

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior2nd': 1 unseen categories converted to Unseen on transform.

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'HeatingQC': 1 unseen categories converted to Unseen on transform.

CV folds:  70%|███████   | 35/50 [18:27<07:48, 31.22s/fold]

Learning rate set to 0.042738
0:	learn: 0.3883983	total: 24.3ms	remaining: 24.3s
1:	learn: 0.3775585	total: 54.4ms	remaining: 27.1s
2:	learn: 0.3672576	total: 80.9ms	remaining: 26.9s
3:	learn: 0.3575029	total: 108ms	remaining: 27s
4:	learn: 0.3483319	total: 138ms	remaining: 27.4s
5:	learn: 0.3390581	total: 168ms	remaining: 27.8s
6:	learn: 0.3298462	total: 200ms	remaining: 28.4s
7:	learn: 0.3213366	total: 235ms	remaining: 29.2s
8:	learn: 0.3140288	total: 272ms	remaining: 29.9s
9:	learn: 0.3060898	total: 302ms	remaining: 29.9s
10:	learn: 0.2982838	total: 336ms	remaining: 30.2s
11:	learn: 0.2910859	total: 372ms	remaining: 30.6s
12:	learn: 0.2843434	total: 404ms	remaining: 30.7s
13:	learn: 0.2776021	total: 437ms	remaining: 30.8s
14:	learn: 0.2712360	total: 465ms	remaining: 30.5s
15:	learn: 0.2654955	total: 494ms	remaining: 30.4s
16:	learn: 0.2595249	total: 523ms	remaining: 30.2s
17:	learn: 0.2536807	total: 551ms	remaining: 30.1s
18:	learn: 0.2478931	total: 582ms	remaining: 30.1s
19:	learn: 0.2427226	total: 618ms	remaining: 30.3s
20:	learn: 0.2378308	total: 644ms	remaining: 30s
21:	learn: 0.2332720	total: 674ms	remaining: 30s
22:	learn: 0.2291996	total: 702ms	remaining: 29.8s
23:	learn: 0.2244006	total: 729ms	remaining: 29.6s
24:	learn: 0.2196776	total: 758ms	remaining: 29.6s
25:	learn: 0.2153558	total: 788ms	remaining: 29.5s
26:	learn: 0.2114249	total: 816ms	remaining: 29.4s
27:	learn: 0.2075600	total: 842ms	remaining: 29.2s
28:	learn: 0.2038920	total: 871ms	remaining: 29.2s
29:	learn: 0.2006693	total: 901ms	remaining: 29.1s
30:	learn: 0.1973108	total: 932ms	remaining: 29.1s
31:	learn: 0.1937972	total: 964ms	remaining: 29.2s
32:	learn: 0.1909545	total: 1.01s	remaining: 29.6s
33:	learn: 0.1882075	total: 1.04s	remaining: 29.5s
34:	learn: 0.1853717	total: 1.07s	remaining: 29.4s
35:	learn: 0.1824684	total: 1.1s	remaining: 29.4s
36:	learn: 0.1798587	total: 1.13s	remaining: 29.3s
37:	learn: 0.1773613	total: 1.16s	remaining: 29.3s
38:	learn: 0.1748792	total: 1.19s	remaining: 29.3s
39:	learn: 0.1726201	total: 1.21s	remaining: 29.1s
40:	learn: 0.1703049	total: 1.24s	remaining: 29.1s
41:	learn: 0.1682933	total: 1.27s	remaining: 29s
42:	learn: 0.1661054	total: 1.3s	remaining: 28.9s
43:	learn: 0.1641628	total: 1.33s	remaining: 28.9s
44:	learn: 0.1621625	total: 1.36s	remaining: 28.8s
45:	learn: 0.1602375	total: 1.39s	remaining: 28.8s
46:	learn: 0.1585531	total: 1.42s	remaining: 28.7s
47:	learn: 0.1566055	total: 1.44s	remaining: 28.6s
48:	learn: 0.1548211	total: 1.47s	remaining: 28.6s
49:	learn: 0.1532465	total: 1.5s	remaining: 28.5s
50:	learn: 0.1516980	total: 1.53s	remaining: 28.5s
51:	learn: 0.1500372	total: 1.56s	remaining: 28.5s
52:	learn: 0.1484545	total: 1.59s	remaining: 28.5s
53:	learn: 0.1472507	total: 1.62s	remaining: 28.4s
54:	learn: 0.1459512	total: 1.65s	remaining: 28.3s
55:	learn: 0.1445574	total: 1.68s	remaining: 28.3s
56:	learn: 0.1434192	total: 1.71s	remaining: 28.2s
57:	learn: 0.1422583	total: 1.73s	remaining: 28.1s
58:	learn: 0.1410825	total: 1.76s	remaining: 28.1s
59:	learn: 0.1400043	total: 1.79s	remaining: 28s
60:	learn: 0.1387925	total: 1.82s	remaining: 28s
61:	learn: 0.1378493	total: 1.85s	remaining: 28s
62:	learn: 0.1367932	total: 1.88s	remaining: 27.9s
63:	learn: 0.1357924	total: 1.9s	remaining: 27.8s
64:	learn: 0.1347844	total: 1.93s	remaining: 27.8s
65:	learn: 0.1340941	total: 1.95s	remaining: 27.6s
66:	learn: 0.1331882	total: 1.98s	remaining: 27.5s
67:	learn: 0.1323749	total: 2s	remaining: 27.5s
68:	learn: 0.1315788	total: 2.03s	remaining: 27.4s
69:	learn: 0.1308104	total: 2.09s	remaining: 27.8s
70:	learn: 0.1298818	total: 2.13s	remaining: 27.9s
71:	learn: 0.1291603	total: 2.16s	remaining: 27.8s
72:	learn: 0.1284092	total: 2.19s	remaining: 27.8s
73:	learn: 0.1276607	total: 2.21s	remaining: 27.7s
74:	learn: 0.1270518	total: 2.25s	remaining: 27.7s
75:	learn: 0.1264858	total: 2.28s	remaining: 27.7s
76:	learn: 0.1258492	total: 2.31s	remaining: 27.6s
77:	learn: 0.1252370	total: 2.33s	remaining: 27.6s
78:	learn: 0.1244998	total: 2.36s	remaining: 27.5s
79:	learn: 0.1238702	total: 2.39s	remaining: 27.5s
80:	learn: 0.1232247	total: 2.42s	remaining: 27.5s
81:	learn: 0.1227449	total: 2.45s	remaining: 27.4s
82:	learn: 0.1222616	total: 2.48s	remaining: 27.4s
83:	learn: 0.1217502	total: 2.51s	remaining: 27.3s
84:	learn: 0.1211219	total: 2.54s	remaining: 27.3s
85:	learn: 0.1204686	total: 2.56s	remaining: 27.3s
86:	learn: 0.1198584	total: 2.59s	remaining: 27.2s
87:	learn: 0.1194044	total: 2.63s	remaining: 27.2s
88:	learn: 0.1188722	total: 2.65s	remaining: 27.2s
89:	learn: 0.1184529	total: 2.68s	remaining: 27.1s
90:	learn: 0.1181057	total: 2.71s	remaining: 27.1s
91:	learn: 0.1176039	total: 2.74s	remaining: 27.1s
92:	learn: 0.1171112	total: 2.77s	remaining: 27s
93:	learn: 0.1165920	total: 2.8s	remaining: 27s
94:	learn: 0.1161219	total: 2.83s	remaining: 27s
95:	learn: 0.1156538	total: 2.86s	remaining: 27s
96:	learn: 0.1152447	total: 2.89s	remaining: 26.9s
97:	learn: 0.1148716	total: 2.92s	remaining: 26.9s
98:	learn: 0.1144770	total: 2.95s	remaining: 26.9s
99:	learn: 0.1141390	total: 2.98s	remaining: 26.8s
100:	learn: 0.1137149	total: 3.01s	remaining: 26.8s
101:	learn: 0.1134512	total: 3.06s	remaining: 26.9s
102:	learn: 0.1131600	total: 3.08s	remaining: 26.9s
103:	learn: 0.1127499	total: 3.11s	remaining: 26.8s
104:	learn: 0.1123259	total: 3.14s	remaining: 26.8s
105:	learn: 0.1118466	total: 3.17s	remaining: 26.8s
106:	learn: 0.1116334	total: 3.2s	remaining: 26.7s
107:	learn: 0.1112294	total: 3.23s	remaining: 26.7s
108:	learn: 0.1108106	total: 3.26s	remaining: 26.7s
109:	learn: 0.1105053	total: 3.29s	remaining: 26.6s
110:	learn: 0.1101770	total: 3.33s	remaining: 26.7s
111:	learn: 0.1099102	total: 3.36s	remaining: 26.6s
112:	learn: 0.1097133	total: 3.39s	remaining: 26.6s
113:	learn: 0.1095006	total: 3.42s	remaining: 26.6s
114:	learn: 0.1092303	total: 3.45s	remaining: 26.5s
115:	learn: 0.1089478	total: 3.48s	remaining: 26.5s
116:	learn: 0.1085251	total: 3.51s	remaining: 26.5s
117:	learn: 0.1083596	total: 3.54s	remaining: 26.5s
118:	learn: 0.1081438	total: 3.57s	remaining: 26.4s
119:	learn: 0.1078045	total: 3.6s	remaining: 26.4s
120:	learn: 0.1075620	total: 3.63s	remaining: 26.4s
121:	learn: 0.1073494	total: 3.66s	remaining: 26.3s
122:	learn: 0.1070745	total: 3.69s	remaining: 26.3s
123:	learn: 0.1065935	total: 3.72s	remaining: 26.3s
124:	learn: 0.1062372	total: 3.75s	remaining: 26.2s
125:	learn: 0.1061574	total: 3.77s	remaining: 26.2s
126:	learn: 0.1060202	total: 3.8s	remaining: 26.1s
127:	learn: 0.1057429	total: 3.83s	remaining: 26.1s
128:	learn: 0.1053986	total: 3.85s	remaining: 26s
129:	learn: 0.1052505	total: 3.89s	remaining: 26s
130:	learn: 0.1050373	total: 3.92s	remaining: 26s
131:	learn: 0.1047353	total: 3.94s	remaining: 25.9s
132:	learn: 0.1045098	total: 3.98s	remaining: 25.9s
133:	learn: 0.1042448	total: 4s	remaining: 25.9s
134:	learn: 0.1040442	total: 4.03s	remaining: 25.8s
135:	learn: 0.1039846	total: 4.05s	remaining: 25.7s
136:	learn: 0.1037764	total: 4.08s	remaining: 25.7s
137:	learn: 0.1036376	total: 4.1s	remaining: 25.6s
138:	learn: 0.1034576	total: 4.13s	remaining: 25.6s
139:	learn: 0.1034368	total: 4.14s	remaining: 25.4s
140:	learn: 0.1033888	total: 4.16s	remaining: 25.3s
141:	learn: 0.1033544	total: 4.17s	remaining: 25.2s
142:	learn: 0.1030373	total: 4.2s	remaining: 25.2s
143:	learn: 0.1028300	total: 4.24s	remaining: 25.2s
144:	learn: 0.1026599	total: 4.28s	remaining: 25.2s
145:	learn: 0.1023982	total: 4.3s	remaining: 25.2s
146:	learn: 0.1021782	total: 4.33s	remaining: 25.1s
147:	learn: 0.1019478	total: 4.36s	remaining: 25.1s
148:	learn: 0.1017725	total: 4.39s	remaining: 25.1s
149:	learn: 0.1016167	total: 4.42s	remaining: 25.1s
150:	learn: 0.1014179	total: 4.45s	remaining: 25s
151:	learn: 0.1012000	total: 4.48s	remaining: 25s
152:	learn: 0.1010692	total: 4.51s	remaining: 25s
153:	learn: 0.1009373	total: 4.54s	remaining: 24.9s
154:	learn: 0.1007144	total: 4.57s	remaining: 24.9s
155:	learn: 0.1005043	total: 4.6s	remaining: 24.9s
156:	learn: 0.1002131	total: 4.63s	remaining: 24.9s
157:	learn: 0.0999702	total: 4.66s	remaining: 24.8s
158:	learn: 0.0997362	total: 4.69s	remaining: 24.8s
159:	learn: 0.0995078	total: 4.72s	remaining: 24.8s
160:	learn: 0.0994544	total: 4.73s	remaining: 24.7s
161:	learn: 0.0993097	total: 4.76s	remaining: 24.6s
162:	learn: 0.0990173	total: 4.79s	remaining: 24.6s
163:	learn: 0.0988360	total: 4.82s	remaining: 24.6s
164:	learn: 0.0986375	total: 4.85s	remaining: 24.6s
165:	learn: 0.0985488	total: 4.88s	remaining: 24.5s
166:	learn: 0.0984603	total: 4.92s	remaining: 24.5s
167:	learn: 0.0982580	total: 4.95s	remaining: 24.5s
168:	learn: 0.0981094	total: 4.98s	remaining: 24.5s
169:	learn: 0.0979535	total: 5.01s	remaining: 24.4s
170:	learn: 0.0978047	total: 5.04s	remaining: 24.4s
171:	learn: 0.0976466	total: 5.06s	remaining: 24.4s
172:	learn: 0.0975150	total: 5.09s	remaining: 24.3s
173:	learn: 0.0972389	total: 5.12s	remaining: 24.3s
174:	learn: 0.0970047	total: 5.15s	remaining: 24.3s
175:	learn: 0.0969024	total: 5.18s	remaining: 24.3s
176:	learn: 0.0967655	total: 5.21s	remaining: 24.2s
177:	learn: 0.0965709	total: 5.24s	remaining: 24.2s
178:	learn: 0.0964256	total: 5.26s	remaining: 24.1s
179:	learn: 0.0963574	total: 5.29s	remaining: 24.1s
180:	learn: 0.0961135	total: 5.32s	remaining: 24.1s
181:	learn: 0.0960500	total: 5.35s	remaining: 24s
182:	learn: 0.0959771	total: 5.38s	remaining: 24s
183:	learn: 0.0959144	total: 5.4s	remaining: 23.9s
184:	learn: 0.0958172	total: 5.43s	remaining: 23.9s
185:	learn: 0.0956369	total: 5.46s	remaining: 23.9s
186:	learn: 0.0955425	total: 5.49s	remaining: 23.9s
187:	learn: 0.0952917	total: 5.52s	remaining: 23.8s
188:	learn: 0.0952299	total: 5.55s	remaining: 23.8s
189:	learn: 0.0951901	total: 5.58s	remaining: 23.8s
190:	learn: 0.0951241	total: 5.61s	remaining: 23.8s
191:	learn: 0.0950688	total: 5.64s	remaining: 23.7s
192:	learn: 0.0948348	total: 5.67s	remaining: 23.7s
193:	learn: 0.0946240	total: 5.69s	remaining: 23.7s
194:	learn: 0.0945525	total: 5.72s	remaining: 23.6s
195:	learn: 0.0943842	total: 5.75s	remaining: 23.6s
196:	learn: 0.0942045	total: 5.78s	remaining: 23.6s
197:	learn: 0.0940680	total: 5.81s	remaining: 23.6s
198:	learn: 0.0939013	total: 5.85s	remaining: 23.5s
199:	learn: 0.0938649	total: 5.88s	remaining: 23.5s
200:	learn: 0.0937066	total: 5.9s	remaining: 23.5s
201:	learn: 0.0936665	total: 5.93s	remaining: 23.4s
202:	learn: 0.0934928	total: 5.96s	remaining: 23.4s
203:	learn: 0.0932315	total: 5.99s	remaining: 23.4s
204:	learn: 0.0931186	total: 6.02s	remaining: 23.3s
205:	learn: 0.0929822	total: 6.05s	remaining: 23.3s
206:	learn: 0.0927890	total: 6.08s	remaining: 23.3s
207:	learn: 0.0926246	total: 6.11s	remaining: 23.3s
208:	learn: 0.0925712	total: 6.14s	remaining: 23.2s
209:	learn: 0.0924755	total: 6.17s	remaining: 23.2s
210:	learn: 0.0924427	total: 6.2s	remaining: 23.2s
211:	learn: 0.0923959	total: 6.22s	remaining: 23.1s
212:	learn: 0.0923430	total: 6.25s	remaining: 23.1s
213:	learn: 0.0922535	total: 6.29s	remaining: 23.1s
214:	learn: 0.0922215	total: 6.31s	remaining: 23s
215:	learn: 0.0920047	total: 6.34s	remaining: 23s
216:	learn: 0.0917884	total: 6.38s	remaining: 23s
217:	learn: 0.0916216	total: 6.42s	remaining: 23s
218:	learn: 0.0915435	total: 6.46s	remaining: 23s
219:	learn: 0.0914942	total: 6.5s	remaining: 23s
220:	learn: 0.0914522	total: 6.53s	remaining: 23s
221:	learn: 0.0914241	total: 6.55s	remaining: 23s
222:	learn: 0.0913939	total: 6.58s	remaining: 22.9s
223:	learn: 0.0912407	total: 6.61s	remaining: 22.9s
224:	learn: 0.0911196	total: 6.64s	remaining: 22.9s
225:	learn: 0.0910019	total: 6.67s	remaining: 22.8s
226:	learn: 0.0908387	total: 6.7s	remaining: 22.8s
227:	learn: 0.0906744	total: 6.73s	remaining: 22.8s
228:	learn: 0.0906584	total: 6.76s	remaining: 22.8s
229:	learn: 0.0906298	total: 6.78s	remaining: 22.7s
230:	learn: 0.0904874	total: 6.82s	remaining: 22.7s
231:	learn: 0.0904523	total: 6.84s	remaining: 22.7s
232:	learn: 0.0902921	total: 6.87s	remaining: 22.6s
233:	learn: 0.0901218	total: 6.91s	remaining: 22.6s
234:	learn: 0.0899883	total: 6.94s	remaining: 22.6s
235:	learn: 0.0899676	total: 6.97s	remaining: 22.6s
236:	learn: 0.0897334	total: 7s	remaining: 22.5s
237:	learn: 0.0896964	total: 7.03s	remaining: 22.5s
238:	learn: 0.0896601	total: 7.06s	remaining: 22.5s
239:	learn: 0.0895192	total: 7.09s	remaining: 22.4s
240:	learn: 0.0894158	total: 7.13s	remaining: 22.5s
241:	learn: 0.0893180	total: 7.16s	remaining: 22.4s
242:	learn: 0.0892864	total: 7.19s	remaining: 22.4s
243:	learn: 0.0891954	total: 7.22s	remaining: 22.4s
244:	learn: 0.0891815	total: 7.25s	remaining: 22.3s
245:	learn: 0.0890515	total: 7.28s	remaining: 22.3s
246:	learn: 0.0888965	total: 7.31s	remaining: 22.3s
247:	learn: 0.0888142	total: 7.34s	remaining: 22.3s
248:	learn: 0.0886066	total: 7.37s	remaining: 22.2s
249:	learn: 0.0884569	total: 7.4s	remaining: 22.2s
250:	learn: 0.0884238	total: 7.43s	remaining: 22.2s
251:	learn: 0.0883174	total: 7.47s	remaining: 22.2s
252:	learn: 0.0881652	total: 7.5s	remaining: 22.1s
253:	learn: 0.0881468	total: 7.53s	remaining: 22.1s
254:	learn: 0.0880941	total: 7.56s	remaining: 22.1s
255:	learn: 0.0879632	total: 7.59s	remaining: 22.1s
256:	learn: 0.0877092	total: 7.61s	remaining: 22s
257:	learn: 0.0876780	total: 7.64s	remaining: 22s
258:	learn: 0.0875107	total: 7.67s	remaining: 22s
259:	learn: 0.0874360	total: 7.7s	remaining: 21.9s
260:	learn: 0.0872408	total: 7.73s	remaining: 21.9s
261:	learn: 0.0870955	total: 7.76s	remaining: 21.9s
262:	learn: 0.0869364	total: 7.79s	remaining: 21.8s
263:	learn: 0.0867854	total: 7.82s	remaining: 21.8s
264:	learn: 0.0866596	total: 7.84s	remaining: 21.8s
265:	learn: 0.0865212	total: 7.87s	remaining: 21.7s
266:	learn: 0.0863737	total: 7.9s	remaining: 21.7s
267:	learn: 0.0862488	total: 7.93s	remaining: 21.7s
268:	learn: 0.0861564	total: 7.96s	remaining: 21.6s
269:	learn: 0.0860149	total: 7.99s	remaining: 21.6s
270:	learn: 0.0859954	total: 8.03s	remaining: 21.6s
271:	learn: 0.0859652	total: 8.06s	remaining: 21.6s
272:	learn: 0.0859374	total: 8.09s	remaining: 21.5s
273:	learn: 0.0857887	total: 8.11s	remaining: 21.5s
274:	learn: 0.0857074	total: 8.14s	remaining: 21.5s
275:	learn: 0.0856726	total: 8.17s	remaining: 21.4s
276:	learn: 0.0854760	total: 8.21s	remaining: 21.4s
277:	learn: 0.0852872	total: 8.24s	remaining: 21.4s
278:	learn: 0.0852409	total: 8.27s	remaining: 21.4s
279:	learn: 0.0852228	total: 8.3s	remaining: 21.3s
280:	learn: 0.0852060	total: 8.33s	remaining: 21.3s
281:	learn: 0.0851899	total: 8.36s	remaining: 21.3s
282:	learn: 0.0851744	total: 8.39s	remaining: 21.3s
283:	learn: 0.0851580	total: 8.42s	remaining: 21.2s
284:	learn: 0.0851391	total: 8.45s	remaining: 21.2s
285:	learn: 0.0851104	total: 8.48s	remaining: 21.2s
286:	learn: 0.0850920	total: 8.51s	remaining: 21.1s
287:	learn: 0.0849244	total: 8.56s	remaining: 21.2s
288:	learn: 0.0848598	total: 8.59s	remaining: 21.1s
289:	learn: 0.0848238	total: 8.62s	remaining: 21.1s
290:	learn: 0.0848084	total: 8.65s	remaining: 21.1s
291:	learn: 0.0847671	total: 8.69s	remaining: 21.1s
292:	learn: 0.0846249	total: 8.72s	remaining: 21s
293:	learn: 0.0845408	total: 8.75s	remaining: 21s
294:	learn: 0.0842658	total: 8.78s	remaining: 21s
295:	learn: 0.0839655	total: 8.8s	remaining: 20.9s
296:	learn: 0.0838963	total: 8.84s	remaining: 20.9s
297:	learn: 0.0836033	total: 8.86s	remaining: 20.9s
298:	learn: 0.0834607	total: 8.89s	remaining: 20.9s
299:	learn: 0.0834067	total: 8.92s	remaining: 20.8s
300:	learn: 0.0831352	total: 8.95s	remaining: 20.8s
301:	learn: 0.0828526	total: 8.98s	remaining: 20.8s
302:	learn: 0.0828171	total: 9.01s	remaining: 20.7s
303:	learn: 0.0828048	total: 9.04s	remaining: 20.7s
304:	learn: 0.0827112	total: 9.07s	remaining: 20.7s
305:	learn: 0.0825952	total: 9.1s	remaining: 20.6s
306:	learn: 0.0824680	total: 9.13s	remaining: 20.6s
307:	learn: 0.0823558	total: 9.16s	remaining: 20.6s
308:	learn: 0.0821767	total: 9.19s	remaining: 20.6s
309:	learn: 0.0820531	total: 9.22s	remaining: 20.5s
310:	learn: 0.0820387	total: 9.25s	remaining: 20.5s
311:	learn: 0.0818369	total: 9.28s	remaining: 20.5s
312:	learn: 0.0818259	total: 9.31s	remaining: 20.4s
313:	learn: 0.0818153	total: 9.34s	remaining: 20.4s
314:	learn: 0.0817780	total: 9.37s	remaining: 20.4s
315:	learn: 0.0816774	total: 9.4s	remaining: 20.3s
316:	learn: 0.0815397	total: 9.43s	remaining: 20.3s
317:	learn: 0.0814015	total: 9.46s	remaining: 20.3s
318:	learn: 0.0811953	total: 9.49s	remaining: 20.3s
319:	learn: 0.0811840	total: 9.52s	remaining: 20.2s
320:	learn: 0.0810894	total: 9.55s	remaining: 20.2s
321:	learn: 0.0810510	total: 9.58s	remaining: 20.2s
322:	learn: 0.0809993	total: 9.61s	remaining: 20.1s
323:	learn: 0.0808698	total: 9.64s	remaining: 20.1s
324:	learn: 0.0807957	total: 9.67s	remaining: 20.1s
325:	learn: 0.0807864	total: 9.7s	remaining: 20.1s
326:	learn: 0.0807727	total: 9.73s	remaining: 20s
327:	learn: 0.0807080	total: 9.76s	remaining: 20s
328:	learn: 0.0806949	total: 9.79s	remaining: 20s
329:	learn: 0.0806857	total: 9.82s	remaining: 19.9s
330:	learn: 0.0805544	total: 9.85s	remaining: 19.9s
331:	learn: 0.0804008	total: 9.88s	remaining: 19.9s
332:	learn: 0.0802942	total: 9.91s	remaining: 19.9s
333:	learn: 0.0802657	total: 9.94s	remaining: 19.8s
334:	learn: 0.0801542	total: 9.97s	remaining: 19.8s
335:	learn: 0.0799975	total: 10s	remaining: 19.8s
336:	learn: 0.0799338	total: 10s	remaining: 19.7s
337:	learn: 0.0798569	total: 10.1s	remaining: 19.7s
338:	learn: 0.0797344	total: 10.1s	remaining: 19.7s
339:	learn: 0.0795921	total: 10.1s	remaining: 19.7s
340:	learn: 0.0795620	total: 10.2s	remaining: 19.6s
341:	learn: 0.0794262	total: 10.2s	remaining: 19.6s
342:	learn: 0.0793335	total: 10.2s	remaining: 19.6s
343:	learn: 0.0793207	total: 10.2s	remaining: 19.5s
344:	learn: 0.0792944	total: 10.3s	remaining: 19.5s
345:	learn: 0.0791265	total: 10.3s	remaining: 19.5s
346:	learn: 0.0790354	total: 10.3s	remaining: 19.4s
347:	learn: 0.0789228	total: 10.4s	remaining: 19.4s
348:	learn: 0.0787777	total: 10.4s	remaining: 19.4s
349:	learn: 0.0787661	total: 10.4s	remaining: 19.4s
350:	learn: 0.0787564	total: 10.5s	remaining: 19.3s
351:	learn: 0.0787145	total: 10.5s	remaining: 19.3s
352:	learn: 0.0787038	total: 10.5s	remaining: 19.3s
353:	learn: 0.0786202	total: 10.6s	remaining: 19.3s
354:	learn: 0.0785990	total: 10.6s	remaining: 19.2s
355:	learn: 0.0784977	total: 10.6s	remaining: 19.2s
356:	learn: 0.0783912	total: 10.7s	remaining: 19.2s
357:	learn: 0.0782574	total: 10.7s	remaining: 19.2s
358:	learn: 0.0781488	total: 10.7s	remaining: 19.2s
359:	learn: 0.0780263	total: 10.8s	remaining: 19.1s
360:	learn: 0.0779654	total: 10.8s	remaining: 19.1s
361:	learn: 0.0779006	total: 10.8s	remaining: 19.1s
362:	learn: 0.0778847	total: 10.9s	remaining: 19.1s
363:	learn: 0.0777497	total: 10.9s	remaining: 19s
364:	learn: 0.0776495	total: 10.9s	remaining: 19s
365:	learn: 0.0775926	total: 11s	remaining: 19s
366:	learn: 0.0774809	total: 11s	remaining: 18.9s
367:	learn: 0.0774746	total: 11s	remaining: 18.9s
368:	learn: 0.0773585	total: 11s	remaining: 18.9s
369:	learn: 0.0772987	total: 11.1s	remaining: 18.9s
370:	learn: 0.0772391	total: 11.1s	remaining: 18.8s
371:	learn: 0.0771667	total: 11.1s	remaining: 18.8s
372:	learn: 0.0771568	total: 11.2s	remaining: 18.8s
373:	learn: 0.0770698	total: 11.2s	remaining: 18.7s
374:	learn: 0.0770102	total: 11.2s	remaining: 18.7s
375:	learn: 0.0769990	total: 11.3s	remaining: 18.7s
376:	learn: 0.0768832	total: 11.3s	remaining: 18.7s
377:	learn: 0.0768092	total: 11.3s	remaining: 18.6s
378:	learn: 0.0767987	total: 11.4s	remaining: 18.6s
379:	learn: 0.0766996	total: 11.4s	remaining: 18.6s
380:	learn: 0.0766495	total: 11.4s	remaining: 18.5s
381:	learn: 0.0764890	total: 11.4s	remaining: 18.5s
382:	learn: 0.0763902	total: 11.5s	remaining: 18.5s
383:	learn: 0.0763043	total: 11.5s	remaining: 18.4s
384:	learn: 0.0762319	total: 11.5s	remaining: 18.4s
385:	learn: 0.0761860	total: 11.6s	remaining: 18.4s
386:	learn: 0.0760830	total: 11.6s	remaining: 18.3s
387:	learn: 0.0759389	total: 11.6s	remaining: 18.3s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'MiscFeature': 1 unseen categories converted to Unseen on transform.

CV folds:  72%|███████▏  | 36/50 [18:58<07:16, 31.15s/fold]

Learning rate set to 0.042738
0:	learn: 0.3906945	total: 27.4ms	remaining: 27.4s
1:	learn: 0.3799626	total: 58.6ms	remaining: 29.2s
2:	learn: 0.3697364	total: 90.7ms	remaining: 30.1s
3:	learn: 0.3602566	total: 119ms	remaining: 29.7s
4:	learn: 0.3506376	total: 149ms	remaining: 29.6s
5:	learn: 0.3416141	total: 179ms	remaining: 29.7s
6:	learn: 0.3330829	total: 211ms	remaining: 29.9s
7:	learn: 0.3244436	total: 253ms	remaining: 31.4s
8:	learn: 0.3161338	total: 285ms	remaining: 31.4s
9:	learn: 0.3081961	total: 311ms	remaining: 30.8s
10:	learn: 0.3002279	total: 339ms	remaining: 30.5s
11:	learn: 0.2926092	total: 370ms	remaining: 30.5s
12:	learn: 0.2857187	total: 398ms	remaining: 30.2s
13:	learn: 0.2788293	total: 429ms	remaining: 30.2s
14:	learn: 0.2722201	total: 459ms	remaining: 30.2s
15:	learn: 0.2661216	total: 492ms	remaining: 30.2s
16:	learn: 0.2598111	total: 521ms	remaining: 30.1s
17:	learn: 0.2537628	total: 554ms	remaining: 30.2s
18:	learn: 0.2484554	total: 584ms	remaining: 30.2s
19:	learn: 0.2430390	total: 613ms	remaining: 30s
20:	learn: 0.2380193	total: 643ms	remaining: 30s
21:	learn: 0.2327762	total: 673ms	remaining: 29.9s
22:	learn: 0.2278176	total: 701ms	remaining: 29.8s
23:	learn: 0.2236226	total: 728ms	remaining: 29.6s
24:	learn: 0.2197625	total: 755ms	remaining: 29.4s
25:	learn: 0.2157435	total: 783ms	remaining: 29.3s
26:	learn: 0.2120154	total: 811ms	remaining: 29.2s
27:	learn: 0.2083411	total: 840ms	remaining: 29.2s
28:	learn: 0.2043635	total: 871ms	remaining: 29.2s
29:	learn: 0.2007207	total: 900ms	remaining: 29.1s
30:	learn: 0.1970966	total: 931ms	remaining: 29.1s
31:	learn: 0.1938807	total: 960ms	remaining: 29s
32:	learn: 0.1911739	total: 990ms	remaining: 29s
33:	learn: 0.1880793	total: 1.02s	remaining: 28.9s
34:	learn: 0.1852107	total: 1.05s	remaining: 28.9s
35:	learn: 0.1826199	total: 1.07s	remaining: 28.8s
36:	learn: 0.1797747	total: 1.1s	remaining: 28.7s
37:	learn: 0.1772734	total: 1.13s	remaining: 28.7s
38:	learn: 0.1745613	total: 1.16s	remaining: 28.7s
39:	learn: 0.1720296	total: 1.2s	remaining: 28.7s
40:	learn: 0.1697498	total: 1.23s	remaining: 28.7s
41:	learn: 0.1674118	total: 1.25s	remaining: 28.6s
42:	learn: 0.1651847	total: 1.3s	remaining: 29.1s
43:	learn: 0.1630440	total: 1.34s	remaining: 29.1s
44:	learn: 0.1609856	total: 1.37s	remaining: 29.1s
45:	learn: 0.1590777	total: 1.4s	remaining: 29s
46:	learn: 0.1570597	total: 1.45s	remaining: 29.5s
47:	learn: 0.1552964	total: 1.48s	remaining: 29.4s
48:	learn: 0.1535518	total: 1.51s	remaining: 29.4s
49:	learn: 0.1521283	total: 1.54s	remaining: 29.3s
50:	learn: 0.1506356	total: 1.57s	remaining: 29.3s
51:	learn: 0.1490934	total: 1.6s	remaining: 29.3s
52:	learn: 0.1477846	total: 1.63s	remaining: 29.2s
53:	learn: 0.1467068	total: 1.66s	remaining: 29.1s
54:	learn: 0.1453254	total: 1.69s	remaining: 29.1s
55:	learn: 0.1441505	total: 1.72s	remaining: 29.1s
56:	learn: 0.1426762	total: 1.75s	remaining: 29s
57:	learn: 0.1412677	total: 1.78s	remaining: 29s
58:	learn: 0.1399633	total: 1.81s	remaining: 28.9s
59:	learn: 0.1387085	total: 1.84s	remaining: 28.9s
60:	learn: 0.1376068	total: 1.87s	remaining: 28.8s
61:	learn: 0.1365588	total: 1.9s	remaining: 28.8s
62:	learn: 0.1353588	total: 1.93s	remaining: 28.7s
63:	learn: 0.1343492	total: 1.96s	remaining: 28.7s
64:	learn: 0.1334105	total: 1.99s	remaining: 28.7s
65:	learn: 0.1324297	total: 2.02s	remaining: 28.7s
66:	learn: 0.1313964	total: 2.05s	remaining: 28.6s
67:	learn: 0.1304122	total: 2.08s	remaining: 28.6s
68:	learn: 0.1295142	total: 2.11s	remaining: 28.5s
69:	learn: 0.1286121	total: 2.15s	remaining: 28.5s
70:	learn: 0.1276907	total: 2.18s	remaining: 28.5s
71:	learn: 0.1269597	total: 2.2s	remaining: 28.4s
72:	learn: 0.1262530	total: 2.23s	remaining: 28.4s
73:	learn: 0.1255414	total: 2.26s	remaining: 28.3s
74:	learn: 0.1248001	total: 2.29s	remaining: 28.3s
75:	learn: 0.1241928	total: 2.32s	remaining: 28.2s
76:	learn: 0.1235214	total: 2.35s	remaining: 28.2s
77:	learn: 0.1227235	total: 2.38s	remaining: 28.1s
78:	learn: 0.1221158	total: 2.41s	remaining: 28.1s
79:	learn: 0.1214887	total: 2.44s	remaining: 28s
80:	learn: 0.1209538	total: 2.47s	remaining: 28s
81:	learn: 0.1202884	total: 2.5s	remaining: 28s
82:	learn: 0.1197099	total: 2.53s	remaining: 27.9s
83:	learn: 0.1191417	total: 2.58s	remaining: 28.1s
84:	learn: 0.1186157	total: 2.6s	remaining: 28s
85:	learn: 0.1181007	total: 2.63s	remaining: 28s
86:	learn: 0.1174399	total: 2.66s	remaining: 27.9s
87:	learn: 0.1168986	total: 2.69s	remaining: 27.9s
88:	learn: 0.1163734	total: 2.72s	remaining: 27.9s
89:	learn: 0.1160128	total: 2.75s	remaining: 27.8s
90:	learn: 0.1155807	total: 2.78s	remaining: 27.8s
91:	learn: 0.1151293	total: 2.81s	remaining: 27.7s
92:	learn: 0.1147132	total: 2.84s	remaining: 27.7s
93:	learn: 0.1142647	total: 2.87s	remaining: 27.7s
94:	learn: 0.1138927	total: 2.9s	remaining: 27.7s
95:	learn: 0.1135105	total: 2.93s	remaining: 27.6s
96:	learn: 0.1131667	total: 2.96s	remaining: 27.6s
97:	learn: 0.1128253	total: 2.99s	remaining: 27.5s
98:	learn: 0.1124540	total: 3.02s	remaining: 27.5s
99:	learn: 0.1121365	total: 3.05s	remaining: 27.4s
100:	learn: 0.1116492	total: 3.08s	remaining: 27.4s
101:	learn: 0.1112018	total: 3.1s	remaining: 27.3s
102:	learn: 0.1108202	total: 3.13s	remaining: 27.3s
103:	learn: 0.1104731	total: 3.19s	remaining: 27.5s
104:	learn: 0.1101102	total: 3.22s	remaining: 27.5s
105:	learn: 0.1097698	total: 3.25s	remaining: 27.4s
106:	learn: 0.1093017	total: 3.28s	remaining: 27.4s
107:	learn: 0.1090250	total: 3.31s	remaining: 27.3s
108:	learn: 0.1086763	total: 3.34s	remaining: 27.3s
109:	learn: 0.1084202	total: 3.37s	remaining: 27.3s
110:	learn: 0.1081689	total: 3.4s	remaining: 27.2s
111:	learn: 0.1077359	total: 3.43s	remaining: 27.2s
112:	learn: 0.1075411	total: 3.46s	remaining: 27.2s
113:	learn: 0.1073188	total: 3.49s	remaining: 27.1s
114:	learn: 0.1069394	total: 3.52s	remaining: 27.1s
115:	learn: 0.1066283	total: 3.55s	remaining: 27.1s
116:	learn: 0.1062507	total: 3.59s	remaining: 27.1s
117:	learn: 0.1059584	total: 3.62s	remaining: 27.1s
118:	learn: 0.1057436	total: 3.65s	remaining: 27.1s
119:	learn: 0.1053379	total: 3.68s	remaining: 27s
120:	learn: 0.1050403	total: 3.71s	remaining: 27s
121:	learn: 0.1048534	total: 3.74s	remaining: 26.9s
122:	learn: 0.1045244	total: 3.77s	remaining: 26.9s
123:	learn: 0.1044033	total: 3.8s	remaining: 26.9s
124:	learn: 0.1042081	total: 3.83s	remaining: 26.8s
125:	learn: 0.1038989	total: 3.86s	remaining: 26.8s
126:	learn: 0.1036588	total: 3.89s	remaining: 26.8s
127:	learn: 0.1033721	total: 3.92s	remaining: 26.7s
128:	learn: 0.1031554	total: 3.95s	remaining: 26.7s
129:	learn: 0.1029663	total: 3.98s	remaining: 26.6s
130:	learn: 0.1026196	total: 4.01s	remaining: 26.6s
131:	learn: 0.1024246	total: 4.04s	remaining: 26.6s
132:	learn: 0.1022355	total: 4.07s	remaining: 26.5s
133:	learn: 0.1020068	total: 4.1s	remaining: 26.5s
134:	learn: 0.1017621	total: 4.13s	remaining: 26.5s
135:	learn: 0.1015751	total: 4.16s	remaining: 26.4s
136:	learn: 0.1013327	total: 4.19s	remaining: 26.4s
137:	learn: 0.1011891	total: 4.22s	remaining: 26.4s
138:	learn: 0.1009795	total: 4.26s	remaining: 26.4s
139:	learn: 0.1007305	total: 4.29s	remaining: 26.4s
140:	learn: 0.1005231	total: 4.32s	remaining: 26.3s
141:	learn: 0.1003438	total: 4.35s	remaining: 26.3s
142:	learn: 0.1001969	total: 4.38s	remaining: 26.2s
143:	learn: 0.1000511	total: 4.41s	remaining: 26.2s
144:	learn: 0.0998821	total: 4.44s	remaining: 26.2s
145:	learn: 0.0997610	total: 4.47s	remaining: 26.1s
146:	learn: 0.0996139	total: 4.5s	remaining: 26.1s
147:	learn: 0.0993617	total: 4.53s	remaining: 26.1s
148:	learn: 0.0991655	total: 4.56s	remaining: 26s
149:	learn: 0.0989543	total: 4.59s	remaining: 26s
150:	learn: 0.0986089	total: 4.62s	remaining: 25.9s
151:	learn: 0.0984272	total: 4.65s	remaining: 25.9s
152:	learn: 0.0983190	total: 4.67s	remaining: 25.9s
153:	learn: 0.0980622	total: 4.71s	remaining: 25.9s
154:	learn: 0.0979642	total: 4.74s	remaining: 25.8s
155:	learn: 0.0978246	total: 4.77s	remaining: 25.8s
156:	learn: 0.0975737	total: 4.79s	remaining: 25.7s
157:	learn: 0.0973044	total: 4.82s	remaining: 25.7s
158:	learn: 0.0971037	total: 4.85s	remaining: 25.7s
159:	learn: 0.0969948	total: 4.88s	remaining: 25.6s
160:	learn: 0.0968122	total: 4.92s	remaining: 25.6s
161:	learn: 0.0966173	total: 4.95s	remaining: 25.6s
162:	learn: 0.0963693	total: 4.98s	remaining: 25.6s
163:	learn: 0.0960371	total: 5.01s	remaining: 25.5s
164:	learn: 0.0957073	total: 5.04s	remaining: 25.5s
165:	learn: 0.0954342	total: 5.07s	remaining: 25.5s
166:	learn: 0.0951973	total: 5.1s	remaining: 25.5s
167:	learn: 0.0951191	total: 5.13s	remaining: 25.4s
168:	learn: 0.0950123	total: 5.17s	remaining: 25.4s
169:	learn: 0.0948010	total: 5.2s	remaining: 25.4s
170:	learn: 0.0945697	total: 5.23s	remaining: 25.3s
171:	learn: 0.0943071	total: 5.26s	remaining: 25.3s
172:	learn: 0.0940667	total: 5.29s	remaining: 25.3s
173:	learn: 0.0938684	total: 5.32s	remaining: 25.2s
174:	learn: 0.0936940	total: 5.35s	remaining: 25.2s
175:	learn: 0.0934295	total: 5.38s	remaining: 25.2s
176:	learn: 0.0932891	total: 5.4s	remaining: 25.1s
177:	learn: 0.0930788	total: 5.43s	remaining: 25.1s
178:	learn: 0.0929343	total: 5.46s	remaining: 25.1s
179:	learn: 0.0927924	total: 5.49s	remaining: 25s
180:	learn: 0.0926101	total: 5.52s	remaining: 25s
181:	learn: 0.0924288	total: 5.55s	remaining: 24.9s
182:	learn: 0.0923488	total: 5.58s	remaining: 24.9s
183:	learn: 0.0921652	total: 5.61s	remaining: 24.9s
184:	learn: 0.0920891	total: 5.64s	remaining: 24.8s
185:	learn: 0.0919532	total: 5.66s	remaining: 24.8s
186:	learn: 0.0918488	total: 5.69s	remaining: 24.7s
187:	learn: 0.0915934	total: 5.73s	remaining: 24.7s
188:	learn: 0.0913811	total: 5.77s	remaining: 24.8s
189:	learn: 0.0912866	total: 5.8s	remaining: 24.7s
190:	learn: 0.0910651	total: 5.82s	remaining: 24.7s
191:	learn: 0.0909974	total: 5.85s	remaining: 24.6s
192:	learn: 0.0908072	total: 5.88s	remaining: 24.6s
193:	learn: 0.0906120	total: 5.92s	remaining: 24.6s
194:	learn: 0.0904521	total: 5.96s	remaining: 24.6s
195:	learn: 0.0903173	total: 6s	remaining: 24.6s
196:	learn: 0.0901878	total: 6.03s	remaining: 24.6s
197:	learn: 0.0901471	total: 6.05s	remaining: 24.5s
198:	learn: 0.0899033	total: 6.09s	remaining: 24.5s
199:	learn: 0.0897672	total: 6.12s	remaining: 24.5s
200:	learn: 0.0895784	total: 6.15s	remaining: 24.4s
201:	learn: 0.0894433	total: 6.18s	remaining: 24.4s
202:	learn: 0.0893551	total: 6.21s	remaining: 24.4s
203:	learn: 0.0892892	total: 6.24s	remaining: 24.3s
204:	learn: 0.0891175	total: 6.26s	remaining: 24.3s
205:	learn: 0.0890416	total: 6.29s	remaining: 24.3s
206:	learn: 0.0888641	total: 6.32s	remaining: 24.2s
207:	learn: 0.0888148	total: 6.35s	remaining: 24.2s
208:	learn: 0.0886005	total: 6.38s	remaining: 24.2s
209:	learn: 0.0884471	total: 6.41s	remaining: 24.1s
210:	learn: 0.0882932	total: 6.44s	remaining: 24.1s
211:	learn: 0.0881926	total: 6.47s	remaining: 24.1s
212:	learn: 0.0879955	total: 6.5s	remaining: 24s
213:	learn: 0.0879061	total: 6.53s	remaining: 24s
214:	learn: 0.0877532	total: 6.56s	remaining: 24s
215:	learn: 0.0876306	total: 6.59s	remaining: 23.9s
216:	learn: 0.0874934	total: 6.62s	remaining: 23.9s
217:	learn: 0.0874094	total: 6.65s	remaining: 23.9s
218:	learn: 0.0873468	total: 6.68s	remaining: 23.8s
219:	learn: 0.0872131	total: 6.71s	remaining: 23.8s
220:	learn: 0.0870452	total: 6.74s	remaining: 23.8s
221:	learn: 0.0869689	total: 6.77s	remaining: 23.7s
222:	learn: 0.0868240	total: 6.8s	remaining: 23.7s
223:	learn: 0.0866216	total: 6.83s	remaining: 23.7s
224:	learn: 0.0865291	total: 6.87s	remaining: 23.7s
225:	learn: 0.0864544	total: 6.91s	remaining: 23.7s
226:	learn: 0.0863428	total: 6.95s	remaining: 23.7s
227:	learn: 0.0862972	total: 6.97s	remaining: 23.6s
228:	learn: 0.0862426	total: 7s	remaining: 23.6s
229:	learn: 0.0861431	total: 7.03s	remaining: 23.5s
230:	learn: 0.0860692	total: 7.06s	remaining: 23.5s
231:	learn: 0.0859184	total: 7.09s	remaining: 23.5s
232:	learn: 0.0858108	total: 7.12s	remaining: 23.4s
233:	learn: 0.0856625	total: 7.15s	remaining: 23.4s
234:	learn: 0.0855824	total: 7.18s	remaining: 23.4s
235:	learn: 0.0854449	total: 7.21s	remaining: 23.3s
236:	learn: 0.0853573	total: 7.24s	remaining: 23.3s
237:	learn: 0.0852447	total: 7.27s	remaining: 23.3s
238:	learn: 0.0851241	total: 7.3s	remaining: 23.2s
239:	learn: 0.0849702	total: 7.33s	remaining: 23.2s
240:	learn: 0.0848330	total: 7.36s	remaining: 23.2s
241:	learn: 0.0845882	total: 7.39s	remaining: 23.1s
242:	learn: 0.0845278	total: 7.42s	remaining: 23.1s
243:	learn: 0.0844257	total: 7.45s	remaining: 23.1s
244:	learn: 0.0843498	total: 7.48s	remaining: 23s
245:	learn: 0.0843026	total: 7.51s	remaining: 23s
246:	learn: 0.0841359	total: 7.54s	remaining: 23s
247:	learn: 0.0839531	total: 7.57s	remaining: 22.9s
248:	learn: 0.0837621	total: 7.59s	remaining: 22.9s
249:	learn: 0.0836579	total: 7.63s	remaining: 22.9s
250:	learn: 0.0835017	total: 7.65s	remaining: 22.8s
251:	learn: 0.0834159	total: 7.68s	remaining: 22.8s
252:	learn: 0.0832672	total: 7.71s	remaining: 22.8s
253:	learn: 0.0831456	total: 7.74s	remaining: 22.7s
254:	learn: 0.0829814	total: 7.77s	remaining: 22.7s
255:	learn: 0.0828904	total: 7.8s	remaining: 22.7s
256:	learn: 0.0828116	total: 7.83s	remaining: 22.6s
257:	learn: 0.0826779	total: 7.86s	remaining: 22.6s
258:	learn: 0.0825087	total: 7.91s	remaining: 22.6s
259:	learn: 0.0824886	total: 7.94s	remaining: 22.6s
260:	learn: 0.0823860	total: 7.97s	remaining: 22.6s
261:	learn: 0.0822278	total: 8.01s	remaining: 22.5s
262:	learn: 0.0821208	total: 8.03s	remaining: 22.5s
263:	learn: 0.0819947	total: 8.07s	remaining: 22.5s
264:	learn: 0.0819820	total: 8.1s	remaining: 22.5s
265:	learn: 0.0818242	total: 8.13s	remaining: 22.4s
266:	learn: 0.0817850	total: 8.16s	remaining: 22.4s
267:	learn: 0.0817540	total: 8.19s	remaining: 22.4s
268:	learn: 0.0816720	total: 8.22s	remaining: 22.3s
269:	learn: 0.0816598	total: 8.26s	remaining: 22.3s
270:	learn: 0.0816131	total: 8.29s	remaining: 22.3s
271:	learn: 0.0814189	total: 8.32s	remaining: 22.3s
272:	learn: 0.0813830	total: 8.35s	remaining: 22.2s
273:	learn: 0.0813769	total: 8.38s	remaining: 22.2s
274:	learn: 0.0813229	total: 8.41s	remaining: 22.2s
275:	learn: 0.0813004	total: 8.45s	remaining: 22.2s
276:	learn: 0.0812728	total: 8.47s	remaining: 22.1s
277:	learn: 0.0811133	total: 8.5s	remaining: 22.1s
278:	learn: 0.0809244	total: 8.53s	remaining: 22s
279:	learn: 0.0808614	total: 8.56s	remaining: 22s
280:	learn: 0.0808357	total: 8.59s	remaining: 22s
281:	learn: 0.0807055	total: 8.62s	remaining: 21.9s
282:	learn: 0.0806691	total: 8.65s	remaining: 21.9s
283:	learn: 0.0806004	total: 8.68s	remaining: 21.9s
284:	learn: 0.0804869	total: 8.71s	remaining: 21.8s
285:	learn: 0.0804203	total: 8.74s	remaining: 21.8s
286:	learn: 0.0803655	total: 8.77s	remaining: 21.8s
287:	learn: 0.0802773	total: 8.8s	remaining: 21.7s
288:	learn: 0.0802258	total: 8.82s	remaining: 21.7s
289:	learn: 0.0802097	total: 8.85s	remaining: 21.7s
290:	learn: 0.0801273	total: 8.88s	remaining: 21.6s
291:	learn: 0.0800928	total: 8.91s	remaining: 21.6s
292:	learn: 0.0799570	total: 8.94s	remaining: 21.6s
293:	learn: 0.0798217	total: 8.97s	remaining: 21.5s
294:	learn: 0.0796761	total: 9s	remaining: 21.5s
295:	learn: 0.0795037	total: 9.03s	remaining: 21.5s
296:	learn: 0.0794796	total: 9.06s	remaining: 21.5s
297:	learn: 0.0794193	total: 9.09s	remaining: 21.4s
298:	learn: 0.0793079	total: 9.13s	remaining: 21.4s
299:	learn: 0.0792225	total: 9.16s	remaining: 21.4s
300:	learn: 0.0790625	total: 9.19s	remaining: 21.3s
301:	learn: 0.0789245	total: 9.22s	remaining: 21.3s
302:	learn: 0.0787732	total: 9.25s	remaining: 21.3s
303:	learn: 0.0786857	total: 9.28s	remaining: 21.2s
304:	learn: 0.0785732	total: 9.31s	remaining: 21.2s
305:	learn: 0.0785155	total: 9.34s	remaining: 21.2s
306:	learn: 0.0784831	total: 9.37s	remaining: 21.1s
307:	learn: 0.0784422	total: 9.4s	remaining: 21.1s
308:	learn: 0.0783886	total: 9.43s	remaining: 21.1s
309:	learn: 0.0783662	total: 9.46s	remaining: 21.1s
310:	learn: 0.0782288	total: 9.49s	remaining: 21s
311:	learn: 0.0780451	total: 9.52s	remaining: 21s
312:	learn: 0.0780219	total: 9.55s	remaining: 21s
313:	learn: 0.0779617	total: 9.58s	remaining: 20.9s
314:	learn: 0.0779029	total: 9.61s	remaining: 20.9s
315:	learn: 0.0777908	total: 9.64s	remaining: 20.9s
316:	learn: 0.0777084	total: 9.67s	remaining: 20.8s
317:	learn: 0.0775990	total: 9.7s	remaining: 20.8s
318:	learn: 0.0775895	total: 9.73s	remaining: 20.8s
319:	learn: 0.0775745	total: 9.76s	remaining: 20.7s
320:	learn: 0.0774747	total: 9.79s	remaining: 20.7s
321:	learn: 0.0774328	total: 9.83s	remaining: 20.7s
322:	learn: 0.0773812	total: 9.86s	remaining: 20.7s
323:	learn: 0.0772780	total: 9.89s	remaining: 20.6s
324:	learn: 0.0771251	total: 9.93s	remaining: 20.6s
325:	learn: 0.0771134	total: 9.96s	remaining: 20.6s
326:	learn: 0.0770505	total: 9.99s	remaining: 20.6s
327:	learn: 0.0770061	total: 10s	remaining: 20.5s
328:	learn: 0.0769172	total: 10.1s	remaining: 20.5s
329:	learn: 0.0767490	total: 10.1s	remaining: 20.5s
330:	learn: 0.0767079	total: 10.1s	remaining: 20.5s
331:	learn: 0.0766150	total: 10.2s	remaining: 20.4s
332:	learn: 0.0766040	total: 10.2s	remaining: 20.4s
333:	learn: 0.0765820	total: 10.2s	remaining: 20.4s
334:	learn: 0.0764884	total: 10.3s	remaining: 20.4s
335:	learn: 0.0763439	total: 10.3s	remaining: 20.3s
336:	learn: 0.0763202	total: 10.3s	remaining: 20.3s
337:	learn: 0.0762795	total: 10.3s	remaining: 20.3s
338:	learn: 0.0762095	total: 10.4s	remaining: 20.2s
339:	learn: 0.0761938	total: 10.4s	remaining: 20.2s
340:	learn: 0.0761618	total: 10.4s	remaining: 20.2s
341:	learn: 0.0760772	total: 10.5s	remaining: 20.1s
342:	learn: 0.0760363	total: 10.5s	remaining: 20.1s
343:	learn: 0.0758612	total: 10.5s	remaining: 20.1s
344:	learn: 0.0757456	total: 10.5s	remaining: 20s
345:	learn: 0.0757313	total: 10.6s	remaining: 20s
346:	learn: 0.0757205	total: 10.6s	remaining: 20s
347:	learn: 0.0755961	total: 10.6s	remaining: 19.9s
348:	learn: 0.0755548	total: 10.7s	remaining: 19.9s
349:	learn: 0.0754683	total: 10.7s	remaining: 19.9s
350:	learn: 0.0754519	total: 10.7s	remaining: 19.8s
351:	learn: 0.0754363	total: 10.8s	remaining: 19.8s
352:	learn: 0.0753920	total: 10.8s	remaining: 19.8s
353:	learn: 0.0753684	total: 10.8s	remaining: 19.7s
354:	learn: 0.0753603	total: 10.8s	remaining: 19.7s
355:	learn: 0.0753553	total: 10.9s	remaining: 19.7s
356:	learn: 0.0753450	total: 10.9s	remaining: 19.6s
357:	learn: 0.0753301	total: 10.9s	remaining: 19.6s
358:	learn: 0.0752902	total: 11s	remaining: 19.6s
359:	learn: 0.0752827	total: 11s	remaining: 19.5s
360:	learn: 0.0752159	total: 11s	remaining: 19.5s
361:	learn: 0.0751469	total: 11s	remaining: 19.5s
362:	learn: 0.0751011	total: 11.1s	remaining: 19.4s
363:	learn: 0.0750807	total: 11.1s	remaining: 19.4s
364:	learn: 0.0750611	total: 11.1s	remaining: 19.4s
365:	learn: 0.0750391	total: 11.2s	remaining: 19.4s
366:	learn: 0.0750270	total: 11.2s	remaining: 19.3s
367:	learn: 0.0750124	total: 11.3s	remaining: 19.3s
368:	learn: 0.0749992	total: 11.3s	remaining: 19.3s
369:	learn: 0.0748458	total: 11.3s	remaining: 19.3s
370:	learn: 0.0748022	total: 11.3s	remaining: 19.2s
371:	learn: 0.0747939	total: 11.4s	remaining: 19.2s
372:	learn: 0.0746498	total: 11.4s	remaining: 19.2s
373:	learn: 0.0746114	total: 11.4s	remaining: 19.1s
374:	learn: 0.0745185	total: 11.5s	remaining: 19.1s
375:	learn: 0.0744551	total: 11.5s	remaining: 19.1s
376:	learn: 0.0744103	total: 11.5s	remaining: 19s
377:	learn: 0.0743814	total: 11.6s	remaining: 19s
378:	learn: 0.0742928	total: 11.6s	remaining: 19s
379:	learn: 0.0741916	total: 11.6s	remaining: 18.9s
380:	learn: 0.0741154	total: 11.6s	remaining: 18.9s
381:	learn: 0.0740923	total: 11.7s	remaining: 18.9s
382:	learn: 0.0740599	total: 11.7s	remaining: 18.8s
383:	learn: 0.0739887	total: 11.7s	remaining: 18.8s
384:	learn: 0.0739720	total: 11.8s	remaining: 18.8s
385:	learn: 0.0739635	total: 11.8s	remaining: 18.8s
386:	learn: 0.0739157	total: 11.8s	remaining: 18.7s
387:	learn: 0.0738233	total: 11.8s	remaining: 18.7s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior1st': 1 unseen categories converted to Unseen on transform.

CV folds:  74%|███████▍  | 37/50 [19:29<06:45, 31.21s/fold]

Learning rate set to 0.042738
0:	learn: 0.3857177	total: 24.9ms	remaining: 24.9s
1:	learn: 0.3753177	total: 57.8ms	remaining: 28.9s
2:	learn: 0.3647669	total: 88.8ms	remaining: 29.5s
3:	learn: 0.3542624	total: 116ms	remaining: 28.9s
4:	learn: 0.3446741	total: 143ms	remaining: 28.4s
5:	learn: 0.3359272	total: 171ms	remaining: 28.3s
6:	learn: 0.3267475	total: 200ms	remaining: 28.4s
7:	learn: 0.3189084	total: 234ms	remaining: 29s
8:	learn: 0.3107854	total: 271ms	remaining: 29.9s
9:	learn: 0.3032583	total: 300ms	remaining: 29.7s
10:	learn: 0.2954147	total: 329ms	remaining: 29.6s
11:	learn: 0.2887600	total: 357ms	remaining: 29.4s
12:	learn: 0.2816975	total: 386ms	remaining: 29.3s
13:	learn: 0.2754016	total: 414ms	remaining: 29.2s
14:	learn: 0.2687179	total: 443ms	remaining: 29.1s
15:	learn: 0.2624246	total: 481ms	remaining: 29.6s
16:	learn: 0.2558975	total: 515ms	remaining: 29.8s
17:	learn: 0.2501649	total: 543ms	remaining: 29.6s
18:	learn: 0.2447405	total: 572ms	remaining: 29.5s
19:	learn: 0.2397917	total: 603ms	remaining: 29.6s
20:	learn: 0.2348419	total: 632ms	remaining: 29.5s
21:	learn: 0.2299239	total: 664ms	remaining: 29.5s
22:	learn: 0.2254578	total: 696ms	remaining: 29.5s
23:	learn: 0.2207014	total: 724ms	remaining: 29.4s
24:	learn: 0.2167514	total: 754ms	remaining: 29.4s
25:	learn: 0.2127018	total: 780ms	remaining: 29.2s
26:	learn: 0.2088291	total: 810ms	remaining: 29.2s
27:	learn: 0.2049877	total: 841ms	remaining: 29.2s
28:	learn: 0.2012779	total: 874ms	remaining: 29.3s
29:	learn: 0.1972934	total: 903ms	remaining: 29.2s
30:	learn: 0.1939368	total: 933ms	remaining: 29.2s
31:	learn: 0.1907858	total: 963ms	remaining: 29.1s
32:	learn: 0.1874151	total: 992ms	remaining: 29.1s
33:	learn: 0.1843446	total: 1.02s	remaining: 29s
34:	learn: 0.1816436	total: 1.05s	remaining: 29.1s
35:	learn: 0.1788022	total: 1.08s	remaining: 29s
36:	learn: 0.1762633	total: 1.11s	remaining: 29s
37:	learn: 0.1738221	total: 1.14s	remaining: 28.9s
38:	learn: 0.1714036	total: 1.17s	remaining: 28.8s
39:	learn: 0.1692166	total: 1.2s	remaining: 28.8s
40:	learn: 0.1668141	total: 1.23s	remaining: 28.7s
41:	learn: 0.1644896	total: 1.26s	remaining: 28.7s
42:	learn: 0.1622215	total: 1.29s	remaining: 28.6s
43:	learn: 0.1603018	total: 1.31s	remaining: 28.6s
44:	learn: 0.1584409	total: 1.34s	remaining: 28.5s
45:	learn: 0.1567981	total: 1.37s	remaining: 28.5s
46:	learn: 0.1550705	total: 1.4s	remaining: 28.4s
47:	learn: 0.1532734	total: 1.43s	remaining: 28.4s
48:	learn: 0.1515486	total: 1.46s	remaining: 28.3s
49:	learn: 0.1499419	total: 1.49s	remaining: 28.3s
50:	learn: 0.1485331	total: 1.51s	remaining: 28.2s
51:	learn: 0.1469048	total: 1.55s	remaining: 28.2s
52:	learn: 0.1454031	total: 1.57s	remaining: 28.1s
53:	learn: 0.1440714	total: 1.6s	remaining: 28.1s
54:	learn: 0.1426515	total: 1.63s	remaining: 28s
55:	learn: 0.1413188	total: 1.66s	remaining: 27.9s
56:	learn: 0.1399648	total: 1.69s	remaining: 27.9s
57:	learn: 0.1385956	total: 1.71s	remaining: 27.8s
58:	learn: 0.1373197	total: 1.74s	remaining: 27.8s
59:	learn: 0.1361953	total: 1.77s	remaining: 27.7s
60:	learn: 0.1353483	total: 1.8s	remaining: 27.7s
61:	learn: 0.1343533	total: 1.82s	remaining: 27.6s
62:	learn: 0.1332100	total: 1.85s	remaining: 27.6s
63:	learn: 0.1322133	total: 1.89s	remaining: 27.6s
64:	learn: 0.1313149	total: 1.91s	remaining: 27.5s
65:	learn: 0.1306393	total: 1.94s	remaining: 27.5s
66:	learn: 0.1297974	total: 1.97s	remaining: 27.5s
67:	learn: 0.1288211	total: 2s	remaining: 27.4s
68:	learn: 0.1281759	total: 2.03s	remaining: 27.4s
69:	learn: 0.1273872	total: 2.06s	remaining: 27.3s
70:	learn: 0.1265907	total: 2.08s	remaining: 27.3s
71:	learn: 0.1257712	total: 2.11s	remaining: 27.2s
72:	learn: 0.1249358	total: 2.14s	remaining: 27.2s
73:	learn: 0.1243097	total: 2.17s	remaining: 27.1s
74:	learn: 0.1235755	total: 2.2s	remaining: 27.1s
75:	learn: 0.1228347	total: 2.23s	remaining: 27.1s
76:	learn: 0.1221539	total: 2.26s	remaining: 27.1s
77:	learn: 0.1215975	total: 2.29s	remaining: 27s
78:	learn: 0.1208586	total: 2.31s	remaining: 27s
79:	learn: 0.1203077	total: 2.35s	remaining: 27s
80:	learn: 0.1196480	total: 2.38s	remaining: 26.9s
81:	learn: 0.1188729	total: 2.4s	remaining: 26.9s
82:	learn: 0.1183500	total: 2.43s	remaining: 26.9s
83:	learn: 0.1176561	total: 2.46s	remaining: 26.9s
84:	learn: 0.1171390	total: 2.49s	remaining: 26.8s
85:	learn: 0.1167521	total: 2.52s	remaining: 26.8s
86:	learn: 0.1162246	total: 2.55s	remaining: 26.8s
87:	learn: 0.1158292	total: 2.58s	remaining: 26.8s
88:	learn: 0.1153460	total: 2.61s	remaining: 26.8s
89:	learn: 0.1148428	total: 2.66s	remaining: 26.9s
90:	learn: 0.1143698	total: 2.69s	remaining: 26.9s
91:	learn: 0.1140451	total: 2.71s	remaining: 26.8s
92:	learn: 0.1136590	total: 2.74s	remaining: 26.8s
93:	learn: 0.1132989	total: 2.77s	remaining: 26.7s
94:	learn: 0.1129102	total: 2.79s	remaining: 26.6s
95:	learn: 0.1125495	total: 2.83s	remaining: 26.6s
96:	learn: 0.1124514	total: 2.84s	remaining: 26.4s
97:	learn: 0.1120777	total: 2.87s	remaining: 26.4s
98:	learn: 0.1115353	total: 2.89s	remaining: 26.3s
99:	learn: 0.1111457	total: 2.93s	remaining: 26.3s
100:	learn: 0.1107285	total: 2.96s	remaining: 26.3s
101:	learn: 0.1101381	total: 2.99s	remaining: 26.3s
102:	learn: 0.1096310	total: 3.02s	remaining: 26.3s
103:	learn: 0.1092628	total: 3.05s	remaining: 26.3s
104:	learn: 0.1088855	total: 3.09s	remaining: 26.4s
105:	learn: 0.1083455	total: 3.13s	remaining: 26.4s
106:	learn: 0.1079066	total: 3.16s	remaining: 26.3s
107:	learn: 0.1075581	total: 3.19s	remaining: 26.3s
108:	learn: 0.1071185	total: 3.21s	remaining: 26.3s
109:	learn: 0.1066670	total: 3.25s	remaining: 26.3s
110:	learn: 0.1062988	total: 3.27s	remaining: 26.2s
111:	learn: 0.1058804	total: 3.31s	remaining: 26.2s
112:	learn: 0.1056214	total: 3.34s	remaining: 26.2s
113:	learn: 0.1053969	total: 3.37s	remaining: 26.2s
114:	learn: 0.1051622	total: 3.4s	remaining: 26.1s
115:	learn: 0.1046981	total: 3.42s	remaining: 26.1s
116:	learn: 0.1044869	total: 3.45s	remaining: 26.1s
117:	learn: 0.1041670	total: 3.48s	remaining: 26s
118:	learn: 0.1039078	total: 3.51s	remaining: 26s
119:	learn: 0.1035612	total: 3.54s	remaining: 26s
120:	learn: 0.1034510	total: 3.56s	remaining: 25.9s
121:	learn: 0.1031723	total: 3.59s	remaining: 25.8s
122:	learn: 0.1027845	total: 3.62s	remaining: 25.8s
123:	learn: 0.1026061	total: 3.65s	remaining: 25.8s
124:	learn: 0.1023956	total: 3.68s	remaining: 25.8s
125:	learn: 0.1021207	total: 3.71s	remaining: 25.8s
126:	learn: 0.1018633	total: 3.74s	remaining: 25.7s
127:	learn: 0.1016670	total: 3.77s	remaining: 25.7s
128:	learn: 0.1015098	total: 3.8s	remaining: 25.7s
129:	learn: 0.1012045	total: 3.83s	remaining: 25.7s
130:	learn: 0.1009373	total: 3.87s	remaining: 25.6s
131:	learn: 0.1007009	total: 3.9s	remaining: 25.6s
132:	learn: 0.1003231	total: 3.92s	remaining: 25.6s
133:	learn: 0.1000724	total: 3.95s	remaining: 25.6s
134:	learn: 0.0998085	total: 3.98s	remaining: 25.5s
135:	learn: 0.0995215	total: 4.01s	remaining: 25.5s
136:	learn: 0.0992080	total: 4.06s	remaining: 25.6s
137:	learn: 0.0989515	total: 4.08s	remaining: 25.5s
138:	learn: 0.0986559	total: 4.11s	remaining: 25.5s
139:	learn: 0.0983976	total: 4.14s	remaining: 25.4s
140:	learn: 0.0982478	total: 4.17s	remaining: 25.4s
141:	learn: 0.0980898	total: 4.2s	remaining: 25.4s
142:	learn: 0.0979152	total: 4.23s	remaining: 25.3s
143:	learn: 0.0976679	total: 4.26s	remaining: 25.3s
144:	learn: 0.0974686	total: 4.29s	remaining: 25.3s
145:	learn: 0.0972904	total: 4.32s	remaining: 25.3s
146:	learn: 0.0971125	total: 4.35s	remaining: 25.3s
147:	learn: 0.0969448	total: 4.38s	remaining: 25.2s
148:	learn: 0.0968547	total: 4.41s	remaining: 25.2s
149:	learn: 0.0966788	total: 4.44s	remaining: 25.2s
150:	learn: 0.0965498	total: 4.48s	remaining: 25.2s
151:	learn: 0.0963996	total: 4.51s	remaining: 25.2s
152:	learn: 0.0960652	total: 4.54s	remaining: 25.1s
153:	learn: 0.0959000	total: 4.57s	remaining: 25.1s
154:	learn: 0.0957009	total: 4.6s	remaining: 25.1s
155:	learn: 0.0954487	total: 4.63s	remaining: 25s
156:	learn: 0.0952960	total: 4.66s	remaining: 25s
157:	learn: 0.0951577	total: 4.69s	remaining: 25s
158:	learn: 0.0949678	total: 4.72s	remaining: 25s
159:	learn: 0.0949151	total: 4.75s	remaining: 24.9s
160:	learn: 0.0947896	total: 4.79s	remaining: 25s
161:	learn: 0.0946559	total: 4.83s	remaining: 25s
162:	learn: 0.0944989	total: 4.86s	remaining: 24.9s
163:	learn: 0.0942485	total: 4.88s	remaining: 24.9s
164:	learn: 0.0940918	total: 4.92s	remaining: 24.9s
165:	learn: 0.0939455	total: 4.95s	remaining: 24.9s
166:	learn: 0.0938699	total: 4.99s	remaining: 24.9s
167:	learn: 0.0936383	total: 5.01s	remaining: 24.8s
168:	learn: 0.0934731	total: 5.05s	remaining: 24.8s
169:	learn: 0.0933462	total: 5.07s	remaining: 24.8s
170:	learn: 0.0931293	total: 5.1s	remaining: 24.7s
171:	learn: 0.0929784	total: 5.13s	remaining: 24.7s
172:	learn: 0.0929383	total: 5.16s	remaining: 24.7s
173:	learn: 0.0927649	total: 5.19s	remaining: 24.6s
174:	learn: 0.0926018	total: 5.22s	remaining: 24.6s
175:	learn: 0.0925474	total: 5.24s	remaining: 24.6s
176:	learn: 0.0924399	total: 5.27s	remaining: 24.5s
177:	learn: 0.0923856	total: 5.3s	remaining: 24.5s
178:	learn: 0.0922846	total: 5.33s	remaining: 24.4s
179:	learn: 0.0922772	total: 5.35s	remaining: 24.4s
180:	learn: 0.0921322	total: 5.38s	remaining: 24.3s
181:	learn: 0.0920388	total: 5.4s	remaining: 24.3s
182:	learn: 0.0918219	total: 5.43s	remaining: 24.3s
183:	learn: 0.0917166	total: 5.46s	remaining: 24.2s
184:	learn: 0.0916111	total: 5.5s	remaining: 24.2s
185:	learn: 0.0914364	total: 5.52s	remaining: 24.2s
186:	learn: 0.0912302	total: 5.55s	remaining: 24.2s
187:	learn: 0.0911180	total: 5.58s	remaining: 24.1s
188:	learn: 0.0910506	total: 5.62s	remaining: 24.1s
189:	learn: 0.0910016	total: 5.64s	remaining: 24.1s
190:	learn: 0.0909198	total: 5.67s	remaining: 24s
191:	learn: 0.0906753	total: 5.7s	remaining: 24s
192:	learn: 0.0906414	total: 5.73s	remaining: 24s
193:	learn: 0.0905890	total: 5.76s	remaining: 23.9s
194:	learn: 0.0905355	total: 5.79s	remaining: 23.9s
195:	learn: 0.0904867	total: 5.82s	remaining: 23.9s
196:	learn: 0.0903653	total: 5.85s	remaining: 23.8s
197:	learn: 0.0900517	total: 5.87s	remaining: 23.8s
198:	learn: 0.0899016	total: 5.9s	remaining: 23.8s
199:	learn: 0.0898659	total: 5.93s	remaining: 23.7s
200:	learn: 0.0898305	total: 5.96s	remaining: 23.7s
201:	learn: 0.0896955	total: 6s	remaining: 23.7s
202:	learn: 0.0896740	total: 6.03s	remaining: 23.7s
203:	learn: 0.0896506	total: 6.06s	remaining: 23.6s
204:	learn: 0.0895964	total: 6.09s	remaining: 23.6s
205:	learn: 0.0894719	total: 6.12s	remaining: 23.6s
206:	learn: 0.0894211	total: 6.14s	remaining: 23.5s
207:	learn: 0.0893835	total: 6.17s	remaining: 23.5s
208:	learn: 0.0893700	total: 6.21s	remaining: 23.5s
209:	learn: 0.0892326	total: 6.24s	remaining: 23.5s
210:	learn: 0.0890978	total: 6.27s	remaining: 23.4s
211:	learn: 0.0890422	total: 6.3s	remaining: 23.4s
212:	learn: 0.0888478	total: 6.33s	remaining: 23.4s
213:	learn: 0.0886178	total: 6.36s	remaining: 23.3s
214:	learn: 0.0884223	total: 6.38s	remaining: 23.3s
215:	learn: 0.0882842	total: 6.41s	remaining: 23.3s
216:	learn: 0.0881990	total: 6.44s	remaining: 23.2s
217:	learn: 0.0880453	total: 6.47s	remaining: 23.2s
218:	learn: 0.0879209	total: 6.5s	remaining: 23.2s
219:	learn: 0.0878374	total: 6.53s	remaining: 23.1s
220:	learn: 0.0878187	total: 6.56s	remaining: 23.1s
221:	learn: 0.0878035	total: 6.59s	remaining: 23.1s
222:	learn: 0.0876556	total: 6.62s	remaining: 23.1s
223:	learn: 0.0876076	total: 6.65s	remaining: 23s
224:	learn: 0.0875740	total: 6.68s	remaining: 23s
225:	learn: 0.0874765	total: 6.71s	remaining: 23s
226:	learn: 0.0874477	total: 6.74s	remaining: 23s
227:	learn: 0.0872135	total: 6.77s	remaining: 22.9s
228:	learn: 0.0870508	total: 6.8s	remaining: 22.9s
229:	learn: 0.0868242	total: 6.83s	remaining: 22.9s
230:	learn: 0.0868075	total: 6.86s	remaining: 22.8s
231:	learn: 0.0867972	total: 6.89s	remaining: 22.8s
232:	learn: 0.0867762	total: 6.92s	remaining: 22.8s
233:	learn: 0.0866504	total: 6.97s	remaining: 22.8s
234:	learn: 0.0865310	total: 7s	remaining: 22.8s
235:	learn: 0.0863837	total: 7.03s	remaining: 22.7s
236:	learn: 0.0862277	total: 7.05s	remaining: 22.7s
237:	learn: 0.0861134	total: 7.08s	remaining: 22.7s
238:	learn: 0.0860981	total: 7.12s	remaining: 22.7s
239:	learn: 0.0860218	total: 7.14s	remaining: 22.6s
240:	learn: 0.0858467	total: 7.18s	remaining: 22.6s
241:	learn: 0.0856862	total: 7.21s	remaining: 22.6s
242:	learn: 0.0855824	total: 7.23s	remaining: 22.5s
243:	learn: 0.0855475	total: 7.26s	remaining: 22.5s
244:	learn: 0.0855215	total: 7.29s	remaining: 22.5s
245:	learn: 0.0855063	total: 7.32s	remaining: 22.4s
246:	learn: 0.0854693	total: 7.35s	remaining: 22.4s
247:	learn: 0.0853307	total: 7.4s	remaining: 22.4s
248:	learn: 0.0851556	total: 7.43s	remaining: 22.4s
249:	learn: 0.0851235	total: 7.46s	remaining: 22.4s
250:	learn: 0.0849461	total: 7.49s	remaining: 22.4s
251:	learn: 0.0847307	total: 7.52s	remaining: 22.3s
252:	learn: 0.0845734	total: 7.55s	remaining: 22.3s
253:	learn: 0.0843889	total: 7.58s	remaining: 22.3s
254:	learn: 0.0841742	total: 7.61s	remaining: 22.2s
255:	learn: 0.0840270	total: 7.64s	remaining: 22.2s
256:	learn: 0.0840153	total: 7.67s	remaining: 22.2s
257:	learn: 0.0838551	total: 7.7s	remaining: 22.2s
258:	learn: 0.0837101	total: 7.73s	remaining: 22.1s
259:	learn: 0.0836166	total: 7.76s	remaining: 22.1s
260:	learn: 0.0836007	total: 7.79s	remaining: 22.1s
261:	learn: 0.0835915	total: 7.82s	remaining: 22s
262:	learn: 0.0835830	total: 7.86s	remaining: 22s
263:	learn: 0.0835593	total: 7.89s	remaining: 22s
264:	learn: 0.0834215	total: 7.92s	remaining: 22s
265:	learn: 0.0834094	total: 7.95s	remaining: 21.9s
266:	learn: 0.0832784	total: 7.98s	remaining: 21.9s
267:	learn: 0.0831444	total: 8.01s	remaining: 21.9s
268:	learn: 0.0831282	total: 8.04s	remaining: 21.8s
269:	learn: 0.0831023	total: 8.07s	remaining: 21.8s
270:	learn: 0.0829343	total: 8.1s	remaining: 21.8s
271:	learn: 0.0829140	total: 8.13s	remaining: 21.8s
272:	learn: 0.0828459	total: 8.16s	remaining: 21.7s
273:	learn: 0.0827719	total: 8.2s	remaining: 21.7s
274:	learn: 0.0825539	total: 8.23s	remaining: 21.7s
275:	learn: 0.0824639	total: 8.26s	remaining: 21.7s
276:	learn: 0.0823306	total: 8.29s	remaining: 21.6s
277:	learn: 0.0821477	total: 8.32s	remaining: 21.6s
278:	learn: 0.0821051	total: 8.35s	remaining: 21.6s
279:	learn: 0.0819608	total: 8.39s	remaining: 21.6s
280:	learn: 0.0818464	total: 8.42s	remaining: 21.5s
281:	learn: 0.0817113	total: 8.45s	remaining: 21.5s
282:	learn: 0.0816209	total: 8.49s	remaining: 21.5s
283:	learn: 0.0814259	total: 8.52s	remaining: 21.5s
284:	learn: 0.0814038	total: 8.55s	remaining: 21.5s
285:	learn: 0.0812228	total: 8.58s	remaining: 21.4s
286:	learn: 0.0811837	total: 8.62s	remaining: 21.4s
287:	learn: 0.0811180	total: 8.65s	remaining: 21.4s
288:	learn: 0.0810648	total: 8.68s	remaining: 21.3s
289:	learn: 0.0809477	total: 8.7s	remaining: 21.3s
290:	learn: 0.0808245	total: 8.73s	remaining: 21.3s
291:	learn: 0.0805561	total: 8.77s	remaining: 21.3s
292:	learn: 0.0803709	total: 8.79s	remaining: 21.2s
293:	learn: 0.0801728	total: 8.83s	remaining: 21.2s
294:	learn: 0.0800333	total: 8.86s	remaining: 21.2s
295:	learn: 0.0800117	total: 8.89s	remaining: 21.2s
296:	learn: 0.0798832	total: 8.92s	remaining: 21.1s
297:	learn: 0.0797507	total: 8.95s	remaining: 21.1s
298:	learn: 0.0796842	total: 8.98s	remaining: 21.1s
299:	learn: 0.0796375	total: 9.02s	remaining: 21s
300:	learn: 0.0794770	total: 9.04s	remaining: 21s
301:	learn: 0.0793926	total: 9.09s	remaining: 21s
302:	learn: 0.0792339	total: 9.13s	remaining: 21s
303:	learn: 0.0791008	total: 9.15s	remaining: 21s
304:	learn: 0.0789616	total: 9.18s	remaining: 20.9s
305:	learn: 0.0788788	total: 9.21s	remaining: 20.9s
306:	learn: 0.0787434	total: 9.25s	remaining: 20.9s
307:	learn: 0.0786035	total: 9.28s	remaining: 20.9s
308:	learn: 0.0785702	total: 9.31s	remaining: 20.8s
309:	learn: 0.0785553	total: 9.34s	remaining: 20.8s
310:	learn: 0.0785024	total: 9.37s	remaining: 20.8s
311:	learn: 0.0784707	total: 9.4s	remaining: 20.7s
312:	learn: 0.0783285	total: 9.43s	remaining: 20.7s
313:	learn: 0.0782825	total: 9.46s	remaining: 20.7s
314:	learn: 0.0782587	total: 9.49s	remaining: 20.6s
315:	learn: 0.0782285	total: 9.52s	remaining: 20.6s
316:	learn: 0.0782194	total: 9.55s	remaining: 20.6s
317:	learn: 0.0780096	total: 9.58s	remaining: 20.5s
318:	learn: 0.0780011	total: 9.61s	remaining: 20.5s
319:	learn: 0.0779886	total: 9.64s	remaining: 20.5s
320:	learn: 0.0779759	total: 9.67s	remaining: 20.5s
321:	learn: 0.0778600	total: 9.7s	remaining: 20.4s
322:	learn: 0.0777393	total: 9.74s	remaining: 20.4s
323:	learn: 0.0777270	total: 9.77s	remaining: 20.4s
324:	learn: 0.0776648	total: 9.8s	remaining: 20.4s
325:	learn: 0.0775239	total: 9.83s	remaining: 20.3s
326:	learn: 0.0774309	total: 9.86s	remaining: 20.3s
327:	learn: 0.0774189	total: 9.89s	remaining: 20.3s
328:	learn: 0.0772932	total: 9.92s	remaining: 20.2s
329:	learn: 0.0771829	total: 9.95s	remaining: 20.2s
330:	learn: 0.0771750	total: 9.98s	remaining: 20.2s
331:	learn: 0.0770061	total: 10s	remaining: 20.1s
332:	learn: 0.0769839	total: 10s	remaining: 20.1s
333:	learn: 0.0769519	total: 10.1s	remaining: 20.1s
334:	learn: 0.0769397	total: 10.1s	remaining: 20.1s
335:	learn: 0.0769062	total: 10.1s	remaining: 20s
336:	learn: 0.0767632	total: 10.2s	remaining: 20s
337:	learn: 0.0767183	total: 10.2s	remaining: 20s
338:	learn: 0.0766602	total: 10.2s	remaining: 20s
339:	learn: 0.0766358	total: 10.3s	remaining: 19.9s
340:	learn: 0.0766064	total: 10.3s	remaining: 19.9s
341:	learn: 0.0765799	total: 10.3s	remaining: 19.9s
342:	learn: 0.0765429	total: 10.4s	remaining: 19.9s
343:	learn: 0.0765370	total: 10.4s	remaining: 19.8s
344:	learn: 0.0765310	total: 10.4s	remaining: 19.8s
345:	learn: 0.0764860	total: 10.5s	remaining: 19.8s
346:	learn: 0.0763622	total: 10.5s	remaining: 19.7s
347:	learn: 0.0763154	total: 10.5s	remaining: 19.7s
348:	learn: 0.0762057	total: 10.5s	remaining: 19.7s
349:	learn: 0.0761126	total: 10.6s	remaining: 19.6s
350:	learn: 0.0759798	total: 10.6s	remaining: 19.6s
351:	learn: 0.0758556	total: 10.6s	remaining: 19.6s
352:	learn: 0.0757249	total: 10.7s	remaining: 19.6s
353:	learn: 0.0756314	total: 10.7s	remaining: 19.5s
354:	learn: 0.0755339	total: 10.7s	remaining: 19.5s
355:	learn: 0.0754722	total: 10.8s	remaining: 19.5s
356:	learn: 0.0753957	total: 10.8s	remaining: 19.4s
357:	learn: 0.0753760	total: 10.8s	remaining: 19.4s
358:	learn: 0.0752960	total: 10.9s	remaining: 19.4s
359:	learn: 0.0752113	total: 10.9s	remaining: 19.4s
360:	learn: 0.0751502	total: 10.9s	remaining: 19.3s
361:	learn: 0.0750074	total: 10.9s	remaining: 19.3s
362:	learn: 0.0748954	total: 11s	remaining: 19.3s
363:	learn: 0.0747775	total: 11s	remaining: 19.2s
364:	learn: 0.0746355	total: 11s	remaining: 19.2s
365:	learn: 0.0745592	total: 11.1s	remaining: 19.2s
366:	learn: 0.0744492	total: 11.1s	remaining: 19.1s
367:	learn: 0.0743971	total: 11.1s	remaining: 19.1s
368:	learn: 0.0741639	total: 11.2s	remaining: 19.1s
369:	learn: 0.0740981	total: 11.2s	remaining: 19.1s
370:	learn: 0.0740276	total: 11.2s	remaining: 19s
371:	learn: 0.0738995	total: 11.3s	remaining: 19s
372:	learn: 0.0737634	total: 11.3s	remaining: 19s
373:	learn: 0.0736719	total: 11.3s	remaining: 19s
374:	learn: 0.0735986	total: 11.4s	remaining: 18.9s
375:	learn: 0.0735095	total: 11.4s	remaining: 18.9s
376:	learn: 0.0734910	total: 11.4s	remaining: 18.9s
377:	learn: 0.0733828	total: 11.5s	remaining: 18.8s
378:	learn: 0.0733507	total: 11.5s	remaining: 18.8s
379:	learn: 0.0732609	total: 11.5s	remaining: 18.8s
380:	learn: 0.0731831	total: 11.5s	remaining: 18.8s
381:	learn: 0.0731443	total: 11.6s	remaining: 18.7s
382:	learn: 0.0730031	total: 11.6s	remaining: 18.7s
383:	learn: 0.0728532	total: 11.6s	remaining: 18.7s
384:	learn: 0.0727801	total: 11.7s	remaining: 18.6s
385:	learn: 0.0726518	total: 11.7s	remaining: 18.6s
386:	learn: 0.0725558	total: 11.7s	remaining: 18.6s
387:	learn: 0.0725460	total: 11.8s	remaining: 18.6s

CV folds:  76%|███████▌  | 38/50 [20:00<06:14, 31.21s/fold]

Learning rate set to 0.042743
0:	learn: 0.3907883	total: 23.8ms	remaining: 23.7s
1:	learn: 0.3802285	total: 51.8ms	remaining: 25.9s
2:	learn: 0.3700810	total: 79.2ms	remaining: 26.3s
3:	learn: 0.3606988	total: 108ms	remaining: 26.9s
4:	learn: 0.3511196	total: 138ms	remaining: 27.4s
5:	learn: 0.3422461	total: 167ms	remaining: 27.6s
6:	learn: 0.3336735	total: 197ms	remaining: 27.9s
7:	learn: 0.3253278	total: 231ms	remaining: 28.7s
8:	learn: 0.3170028	total: 266ms	remaining: 29.3s
9:	learn: 0.3089359	total: 296ms	remaining: 29.3s
10:	learn: 0.3010972	total: 323ms	remaining: 29s
11:	learn: 0.2941162	total: 351ms	remaining: 28.9s
12:	learn: 0.2867551	total: 378ms	remaining: 28.7s
13:	learn: 0.2802086	total: 407ms	remaining: 28.6s
14:	learn: 0.2741116	total: 437ms	remaining: 28.7s
15:	learn: 0.2679449	total: 472ms	remaining: 29s
16:	learn: 0.2621653	total: 503ms	remaining: 29.1s
17:	learn: 0.2563266	total: 534ms	remaining: 29.1s
18:	learn: 0.2511981	total: 563ms	remaining: 29.1s
19:	learn: 0.2463927	total: 592ms	remaining: 29s
20:	learn: 0.2412799	total: 622ms	remaining: 29s
21:	learn: 0.2363042	total: 655ms	remaining: 29.1s
22:	learn: 0.2316094	total: 686ms	remaining: 29.2s
23:	learn: 0.2270271	total: 718ms	remaining: 29.2s
24:	learn: 0.2226810	total: 747ms	remaining: 29.1s
25:	learn: 0.2186766	total: 779ms	remaining: 29.2s
26:	learn: 0.2149244	total: 805ms	remaining: 29s
27:	learn: 0.2110640	total: 833ms	remaining: 28.9s
28:	learn: 0.2077390	total: 861ms	remaining: 28.8s
29:	learn: 0.2041705	total: 890ms	remaining: 28.8s
30:	learn: 0.2008111	total: 918ms	remaining: 28.7s
31:	learn: 0.1976839	total: 937ms	remaining: 28.4s
32:	learn: 0.1948428	total: 966ms	remaining: 28.3s
33:	learn: 0.1919155	total: 996ms	remaining: 28.3s
34:	learn: 0.1887949	total: 1.03s	remaining: 28.3s
35:	learn: 0.1858982	total: 1.05s	remaining: 28.2s
36:	learn: 0.1833232	total: 1.09s	remaining: 28.3s
37:	learn: 0.1806556	total: 1.11s	remaining: 28.2s
38:	learn: 0.1781320	total: 1.15s	remaining: 28.3s
39:	learn: 0.1760098	total: 1.18s	remaining: 28.3s
40:	learn: 0.1740957	total: 1.21s	remaining: 28.2s
41:	learn: 0.1717177	total: 1.23s	remaining: 28.1s
42:	learn: 0.1696792	total: 1.26s	remaining: 28s
43:	learn: 0.1678191	total: 1.28s	remaining: 27.8s
44:	learn: 0.1658554	total: 1.31s	remaining: 27.7s
45:	learn: 0.1640108	total: 1.33s	remaining: 27.7s
46:	learn: 0.1621848	total: 1.36s	remaining: 27.7s
47:	learn: 0.1604720	total: 1.39s	remaining: 27.7s
48:	learn: 0.1588766	total: 1.42s	remaining: 27.6s
49:	learn: 0.1573444	total: 1.45s	remaining: 27.6s
50:	learn: 0.1555856	total: 1.48s	remaining: 27.6s
51:	learn: 0.1541615	total: 1.51s	remaining: 27.6s
52:	learn: 0.1525476	total: 1.54s	remaining: 27.5s
53:	learn: 0.1510873	total: 1.57s	remaining: 27.5s
54:	learn: 0.1493630	total: 1.6s	remaining: 27.5s
55:	learn: 0.1478906	total: 1.63s	remaining: 27.5s
56:	learn: 0.1466066	total: 1.66s	remaining: 27.4s
57:	learn: 0.1452186	total: 1.69s	remaining: 27.5s
58:	learn: 0.1440292	total: 1.72s	remaining: 27.4s
59:	learn: 0.1428765	total: 1.75s	remaining: 27.4s
60:	learn: 0.1417258	total: 1.78s	remaining: 27.4s
61:	learn: 0.1405832	total: 1.8s	remaining: 27.3s
62:	learn: 0.1395484	total: 1.85s	remaining: 27.5s
63:	learn: 0.1385962	total: 1.88s	remaining: 27.5s
64:	learn: 0.1375374	total: 1.91s	remaining: 27.4s
65:	learn: 0.1367733	total: 1.94s	remaining: 27.4s
66:	learn: 0.1360015	total: 1.97s	remaining: 27.4s
67:	learn: 0.1350244	total: 2s	remaining: 27.4s
68:	learn: 0.1341646	total: 2.02s	remaining: 27.3s
69:	learn: 0.1334200	total: 2.05s	remaining: 27.3s
70:	learn: 0.1326632	total: 2.09s	remaining: 27.3s
71:	learn: 0.1317745	total: 2.12s	remaining: 27.3s
72:	learn: 0.1309659	total: 2.14s	remaining: 27.2s
73:	learn: 0.1302458	total: 2.17s	remaining: 27.2s
74:	learn: 0.1296140	total: 2.21s	remaining: 27.3s
75:	learn: 0.1288585	total: 2.25s	remaining: 27.3s
76:	learn: 0.1283043	total: 2.27s	remaining: 27.3s
77:	learn: 0.1276499	total: 2.3s	remaining: 27.2s
78:	learn: 0.1271069	total: 2.33s	remaining: 27.2s
79:	learn: 0.1264971	total: 2.36s	remaining: 27.2s
80:	learn: 0.1259631	total: 2.39s	remaining: 27.1s
81:	learn: 0.1254467	total: 2.42s	remaining: 27.1s
82:	learn: 0.1246365	total: 2.45s	remaining: 27s
83:	learn: 0.1238409	total: 2.48s	remaining: 27s
84:	learn: 0.1233100	total: 2.51s	remaining: 27s
85:	learn: 0.1225932	total: 2.54s	remaining: 27s
86:	learn: 0.1218615	total: 2.57s	remaining: 26.9s
87:	learn: 0.1213539	total: 2.6s	remaining: 26.9s
88:	learn: 0.1206435	total: 2.63s	remaining: 26.9s
89:	learn: 0.1201035	total: 2.66s	remaining: 26.9s
90:	learn: 0.1195486	total: 2.69s	remaining: 26.9s
91:	learn: 0.1192294	total: 2.72s	remaining: 26.9s
92:	learn: 0.1187954	total: 2.75s	remaining: 26.9s
93:	learn: 0.1184429	total: 2.78s	remaining: 26.8s
94:	learn: 0.1180641	total: 2.81s	remaining: 26.8s
95:	learn: 0.1177014	total: 2.84s	remaining: 26.7s
96:	learn: 0.1173893	total: 2.87s	remaining: 26.7s
97:	learn: 0.1169209	total: 2.9s	remaining: 26.7s
98:	learn: 0.1164851	total: 2.93s	remaining: 26.7s
99:	learn: 0.1162202	total: 2.96s	remaining: 26.6s
100:	learn: 0.1159150	total: 2.98s	remaining: 26.6s
101:	learn: 0.1155421	total: 3.01s	remaining: 26.5s
102:	learn: 0.1149647	total: 3.04s	remaining: 26.5s
103:	learn: 0.1146509	total: 3.07s	remaining: 26.5s
104:	learn: 0.1142167	total: 3.1s	remaining: 26.4s
105:	learn: 0.1139962	total: 3.13s	remaining: 26.4s
106:	learn: 0.1136670	total: 3.16s	remaining: 26.4s
107:	learn: 0.1133364	total: 3.19s	remaining: 26.3s
108:	learn: 0.1129632	total: 3.22s	remaining: 26.3s
109:	learn: 0.1127434	total: 3.25s	remaining: 26.3s
110:	learn: 0.1124717	total: 3.28s	remaining: 26.3s
111:	learn: 0.1121917	total: 3.31s	remaining: 26.2s
112:	learn: 0.1120234	total: 3.34s	remaining: 26.2s
113:	learn: 0.1116824	total: 3.37s	remaining: 26.2s
114:	learn: 0.1114193	total: 3.4s	remaining: 26.2s
115:	learn: 0.1110973	total: 3.43s	remaining: 26.1s
116:	learn: 0.1108609	total: 3.46s	remaining: 26.1s
117:	learn: 0.1106261	total: 3.5s	remaining: 26.1s
118:	learn: 0.1102155	total: 3.52s	remaining: 26.1s
119:	learn: 0.1100214	total: 3.55s	remaining: 26.1s
120:	learn: 0.1097496	total: 3.58s	remaining: 26s
121:	learn: 0.1095509	total: 3.61s	remaining: 26s
122:	learn: 0.1092369	total: 3.64s	remaining: 26s
123:	learn: 0.1089641	total: 3.69s	remaining: 26.1s
124:	learn: 0.1087025	total: 3.73s	remaining: 26.1s
125:	learn: 0.1084598	total: 3.76s	remaining: 26.1s
126:	learn: 0.1082948	total: 3.79s	remaining: 26s
127:	learn: 0.1080040	total: 3.82s	remaining: 26s
128:	learn: 0.1077921	total: 3.85s	remaining: 26s
129:	learn: 0.1074422	total: 3.87s	remaining: 25.9s
130:	learn: 0.1072362	total: 3.91s	remaining: 25.9s
131:	learn: 0.1070248	total: 3.94s	remaining: 25.9s
132:	learn: 0.1068633	total: 3.97s	remaining: 25.9s
133:	learn: 0.1065722	total: 4.01s	remaining: 25.9s
134:	learn: 0.1063410	total: 4.04s	remaining: 25.9s
135:	learn: 0.1060813	total: 4.07s	remaining: 25.9s
136:	learn: 0.1057671	total: 4.1s	remaining: 25.8s
137:	learn: 0.1056771	total: 4.13s	remaining: 25.8s
138:	learn: 0.1054348	total: 4.16s	remaining: 25.8s
139:	learn: 0.1052132	total: 4.19s	remaining: 25.8s
140:	learn: 0.1049455	total: 4.22s	remaining: 25.7s
141:	learn: 0.1047401	total: 4.25s	remaining: 25.7s
142:	learn: 0.1044913	total: 4.28s	remaining: 25.7s
143:	learn: 0.1043116	total: 4.31s	remaining: 25.6s
144:	learn: 0.1040875	total: 4.34s	remaining: 25.6s
145:	learn: 0.1038855	total: 4.38s	remaining: 25.6s
146:	learn: 0.1036692	total: 4.42s	remaining: 25.7s
147:	learn: 0.1036064	total: 4.45s	remaining: 25.6s
148:	learn: 0.1033369	total: 4.49s	remaining: 25.6s
149:	learn: 0.1032657	total: 4.51s	remaining: 25.6s
150:	learn: 0.1030532	total: 4.54s	remaining: 25.5s
151:	learn: 0.1028352	total: 4.57s	remaining: 25.5s
152:	learn: 0.1026035	total: 4.6s	remaining: 25.5s
153:	learn: 0.1024190	total: 4.63s	remaining: 25.4s
154:	learn: 0.1021471	total: 4.67s	remaining: 25.5s
155:	learn: 0.1018679	total: 4.7s	remaining: 25.4s
156:	learn: 0.1016091	total: 4.72s	remaining: 25.4s
157:	learn: 0.1014118	total: 4.75s	remaining: 25.3s
158:	learn: 0.1012372	total: 4.78s	remaining: 25.3s
159:	learn: 0.1010696	total: 4.81s	remaining: 25.3s
160:	learn: 0.1008604	total: 4.84s	remaining: 25.2s
161:	learn: 0.1006256	total: 4.87s	remaining: 25.2s
162:	learn: 0.1004333	total: 4.9s	remaining: 25.2s
163:	learn: 0.1002620	total: 4.93s	remaining: 25.2s
164:	learn: 0.1001654	total: 4.96s	remaining: 25.1s
165:	learn: 0.1000014	total: 4.99s	remaining: 25.1s
166:	learn: 0.0997078	total: 5.02s	remaining: 25s
167:	learn: 0.0995729	total: 5.05s	remaining: 25s
168:	learn: 0.0994070	total: 5.08s	remaining: 25s
169:	learn: 0.0992723	total: 5.11s	remaining: 24.9s
170:	learn: 0.0991400	total: 5.14s	remaining: 24.9s
171:	learn: 0.0989765	total: 5.17s	remaining: 24.9s
172:	learn: 0.0987754	total: 5.2s	remaining: 24.8s
173:	learn: 0.0987163	total: 5.22s	remaining: 24.8s
174:	learn: 0.0985145	total: 5.25s	remaining: 24.8s
175:	learn: 0.0984841	total: 5.28s	remaining: 24.7s
176:	learn: 0.0984590	total: 5.31s	remaining: 24.7s
177:	learn: 0.0982774	total: 5.35s	remaining: 24.7s
178:	learn: 0.0981040	total: 5.38s	remaining: 24.7s
179:	learn: 0.0979557	total: 5.41s	remaining: 24.6s
180:	learn: 0.0977644	total: 5.43s	remaining: 24.6s
181:	learn: 0.0975599	total: 5.46s	remaining: 24.6s
182:	learn: 0.0974017	total: 5.5s	remaining: 24.5s
183:	learn: 0.0971921	total: 5.52s	remaining: 24.5s
184:	learn: 0.0970667	total: 5.55s	remaining: 24.5s
185:	learn: 0.0969612	total: 5.59s	remaining: 24.4s
186:	learn: 0.0968827	total: 5.62s	remaining: 24.4s
187:	learn: 0.0967256	total: 5.65s	remaining: 24.4s
188:	learn: 0.0965494	total: 5.67s	remaining: 24.4s
189:	learn: 0.0964774	total: 5.7s	remaining: 24.3s
190:	learn: 0.0964034	total: 5.73s	remaining: 24.3s
191:	learn: 0.0963145	total: 5.76s	remaining: 24.3s
192:	learn: 0.0961143	total: 5.79s	remaining: 24.2s
193:	learn: 0.0960490	total: 5.83s	remaining: 24.2s
194:	learn: 0.0958222	total: 5.86s	remaining: 24.2s
195:	learn: 0.0956081	total: 5.88s	remaining: 24.1s
196:	learn: 0.0954221	total: 5.91s	remaining: 24.1s
197:	learn: 0.0953532	total: 5.94s	remaining: 24.1s
198:	learn: 0.0952347	total: 5.97s	remaining: 24s
199:	learn: 0.0951553	total: 6s	remaining: 24s
200:	learn: 0.0949409	total: 6.03s	remaining: 24s
201:	learn: 0.0948538	total: 6.06s	remaining: 23.9s
202:	learn: 0.0945572	total: 6.09s	remaining: 23.9s
203:	learn: 0.0944834	total: 6.12s	remaining: 23.9s
204:	learn: 0.0942509	total: 6.16s	remaining: 23.9s
205:	learn: 0.0941681	total: 6.19s	remaining: 23.9s
206:	learn: 0.0940182	total: 6.21s	remaining: 23.8s
207:	learn: 0.0937505	total: 6.25s	remaining: 23.8s
208:	learn: 0.0935358	total: 6.28s	remaining: 23.8s
209:	learn: 0.0934654	total: 6.3s	remaining: 23.7s
210:	learn: 0.0933913	total: 6.33s	remaining: 23.7s
211:	learn: 0.0933206	total: 6.36s	remaining: 23.6s
212:	learn: 0.0932192	total: 6.39s	remaining: 23.6s
213:	learn: 0.0931619	total: 6.42s	remaining: 23.6s
214:	learn: 0.0931074	total: 6.45s	remaining: 23.5s
215:	learn: 0.0929823	total: 6.47s	remaining: 23.5s
216:	learn: 0.0928327	total: 6.5s	remaining: 23.5s
217:	learn: 0.0926515	total: 6.53s	remaining: 23.4s
218:	learn: 0.0925076	total: 6.56s	remaining: 23.4s
219:	learn: 0.0922410	total: 6.59s	remaining: 23.4s
220:	learn: 0.0920815	total: 6.62s	remaining: 23.3s
221:	learn: 0.0919833	total: 6.66s	remaining: 23.3s
222:	learn: 0.0919084	total: 6.69s	remaining: 23.3s
223:	learn: 0.0918315	total: 6.72s	remaining: 23.3s
224:	learn: 0.0917158	total: 6.75s	remaining: 23.2s
225:	learn: 0.0915986	total: 6.78s	remaining: 23.2s
226:	learn: 0.0915694	total: 6.81s	remaining: 23.2s
227:	learn: 0.0915261	total: 6.83s	remaining: 23.1s
228:	learn: 0.0914324	total: 6.86s	remaining: 23.1s
229:	learn: 0.0913583	total: 6.89s	remaining: 23.1s
230:	learn: 0.0912643	total: 6.92s	remaining: 23s
231:	learn: 0.0910267	total: 6.95s	remaining: 23s
232:	learn: 0.0909697	total: 6.98s	remaining: 23s
233:	learn: 0.0908008	total: 7.01s	remaining: 23s
234:	learn: 0.0907184	total: 7.04s	remaining: 22.9s
235:	learn: 0.0906770	total: 7.07s	remaining: 22.9s
236:	learn: 0.0904558	total: 7.11s	remaining: 22.9s
237:	learn: 0.0902356	total: 7.14s	remaining: 22.9s
238:	learn: 0.0901609	total: 7.17s	remaining: 22.8s
239:	learn: 0.0900415	total: 7.2s	remaining: 22.8s
240:	learn: 0.0899490	total: 7.23s	remaining: 22.8s
241:	learn: 0.0897604	total: 7.26s	remaining: 22.7s
242:	learn: 0.0896608	total: 7.29s	remaining: 22.7s
243:	learn: 0.0896270	total: 7.32s	remaining: 22.7s
244:	learn: 0.0894908	total: 7.35s	remaining: 22.6s
245:	learn: 0.0894319	total: 7.38s	remaining: 22.6s
246:	learn: 0.0893922	total: 7.4s	remaining: 22.6s
247:	learn: 0.0893367	total: 7.43s	remaining: 22.5s
248:	learn: 0.0892964	total: 7.46s	remaining: 22.5s
249:	learn: 0.0892472	total: 7.49s	remaining: 22.5s
250:	learn: 0.0891075	total: 7.52s	remaining: 22.4s
251:	learn: 0.0890482	total: 7.55s	remaining: 22.4s
252:	learn: 0.0888692	total: 7.58s	remaining: 22.4s
253:	learn: 0.0888412	total: 7.61s	remaining: 22.4s
254:	learn: 0.0887979	total: 7.64s	remaining: 22.3s
255:	learn: 0.0887802	total: 7.67s	remaining: 22.3s
256:	learn: 0.0887171	total: 7.7s	remaining: 22.3s
257:	learn: 0.0886127	total: 7.73s	remaining: 22.2s
258:	learn: 0.0885645	total: 7.76s	remaining: 22.2s
259:	learn: 0.0885151	total: 7.79s	remaining: 22.2s
260:	learn: 0.0883590	total: 7.82s	remaining: 22.2s
261:	learn: 0.0882014	total: 7.85s	remaining: 22.1s
262:	learn: 0.0881529	total: 7.88s	remaining: 22.1s
263:	learn: 0.0880403	total: 7.91s	remaining: 22.1s
264:	learn: 0.0880162	total: 7.94s	remaining: 22s
265:	learn: 0.0879015	total: 7.98s	remaining: 22s
266:	learn: 0.0877746	total: 8.03s	remaining: 22s
267:	learn: 0.0877224	total: 8.06s	remaining: 22s
268:	learn: 0.0877084	total: 8.1s	remaining: 22s
269:	learn: 0.0876923	total: 8.13s	remaining: 22s
270:	learn: 0.0876064	total: 8.16s	remaining: 21.9s
271:	learn: 0.0875743	total: 8.19s	remaining: 21.9s
272:	learn: 0.0874775	total: 8.22s	remaining: 21.9s
273:	learn: 0.0874640	total: 8.25s	remaining: 21.9s
274:	learn: 0.0873251	total: 8.28s	remaining: 21.8s
275:	learn: 0.0871417	total: 8.31s	remaining: 21.8s
276:	learn: 0.0869720	total: 8.34s	remaining: 21.8s
277:	learn: 0.0869209	total: 8.37s	remaining: 21.7s
278:	learn: 0.0869032	total: 8.4s	remaining: 21.7s
279:	learn: 0.0867903	total: 8.43s	remaining: 21.7s
280:	learn: 0.0867684	total: 8.46s	remaining: 21.7s
281:	learn: 0.0866448	total: 8.49s	remaining: 21.6s
282:	learn: 0.0866225	total: 8.52s	remaining: 21.6s
283:	learn: 0.0865970	total: 8.55s	remaining: 21.6s
284:	learn: 0.0864552	total: 8.59s	remaining: 21.5s
285:	learn: 0.0863895	total: 8.62s	remaining: 21.5s
286:	learn: 0.0862363	total: 8.67s	remaining: 21.5s
287:	learn: 0.0861234	total: 8.7s	remaining: 21.5s
288:	learn: 0.0860454	total: 8.73s	remaining: 21.5s
289:	learn: 0.0859977	total: 8.76s	remaining: 21.5s
290:	learn: 0.0859221	total: 8.79s	remaining: 21.4s
291:	learn: 0.0859107	total: 8.82s	remaining: 21.4s
292:	learn: 0.0858253	total: 8.86s	remaining: 21.4s
293:	learn: 0.0857934	total: 8.89s	remaining: 21.4s
294:	learn: 0.0857720	total: 8.93s	remaining: 21.3s
295:	learn: 0.0855842	total: 8.95s	remaining: 21.3s
296:	learn: 0.0855340	total: 8.98s	remaining: 21.3s
297:	learn: 0.0854724	total: 9.01s	remaining: 21.2s
298:	learn: 0.0854659	total: 9.04s	remaining: 21.2s
299:	learn: 0.0854393	total: 9.07s	remaining: 21.2s
300:	learn: 0.0854137	total: 9.11s	remaining: 21.1s
301:	learn: 0.0853167	total: 9.13s	remaining: 21.1s
302:	learn: 0.0852335	total: 9.16s	remaining: 21.1s
303:	learn: 0.0851972	total: 9.19s	remaining: 21s
304:	learn: 0.0851231	total: 9.22s	remaining: 21s
305:	learn: 0.0850618	total: 9.25s	remaining: 21s
306:	learn: 0.0849884	total: 9.28s	remaining: 21s
307:	learn: 0.0848617	total: 9.31s	remaining: 20.9s
308:	learn: 0.0847852	total: 9.34s	remaining: 20.9s
309:	learn: 0.0846508	total: 9.37s	remaining: 20.9s
310:	learn: 0.0845975	total: 9.4s	remaining: 20.8s
311:	learn: 0.0845271	total: 9.43s	remaining: 20.8s
312:	learn: 0.0844841	total: 9.46s	remaining: 20.8s
313:	learn: 0.0844024	total: 9.49s	remaining: 20.7s
314:	learn: 0.0843814	total: 9.52s	remaining: 20.7s
315:	learn: 0.0842368	total: 9.55s	remaining: 20.7s
316:	learn: 0.0840980	total: 9.58s	remaining: 20.6s
317:	learn: 0.0840729	total: 9.61s	remaining: 20.6s
318:	learn: 0.0840144	total: 9.64s	remaining: 20.6s
319:	learn: 0.0839746	total: 9.68s	remaining: 20.6s
320:	learn: 0.0839180	total: 9.71s	remaining: 20.5s
321:	learn: 0.0838808	total: 9.74s	remaining: 20.5s
322:	learn: 0.0838293	total: 9.77s	remaining: 20.5s
323:	learn: 0.0838107	total: 9.8s	remaining: 20.4s
324:	learn: 0.0836921	total: 9.83s	remaining: 20.4s
325:	learn: 0.0835846	total: 9.86s	remaining: 20.4s
326:	learn: 0.0834929	total: 9.88s	remaining: 20.3s
327:	learn: 0.0834470	total: 9.92s	remaining: 20.3s
328:	learn: 0.0834265	total: 9.95s	remaining: 20.3s
329:	learn: 0.0834045	total: 9.98s	remaining: 20.3s
330:	learn: 0.0832462	total: 10s	remaining: 20.2s
331:	learn: 0.0830663	total: 10s	remaining: 20.2s
332:	learn: 0.0829421	total: 10.1s	remaining: 20.2s
333:	learn: 0.0829173	total: 10.1s	remaining: 20.1s
334:	learn: 0.0828246	total: 10.1s	remaining: 20.1s
335:	learn: 0.0826869	total: 10.2s	remaining: 20.1s
336:	learn: 0.0824811	total: 10.2s	remaining: 20s
337:	learn: 0.0824734	total: 10.2s	remaining: 20s
338:	learn: 0.0824205	total: 10.3s	remaining: 20s
339:	learn: 0.0823892	total: 10.3s	remaining: 20s
340:	learn: 0.0822644	total: 10.3s	remaining: 19.9s
341:	learn: 0.0822444	total: 10.3s	remaining: 19.9s
342:	learn: 0.0822325	total: 10.4s	remaining: 19.9s
343:	learn: 0.0821688	total: 10.4s	remaining: 19.8s
344:	learn: 0.0821205	total: 10.4s	remaining: 19.8s
345:	learn: 0.0819432	total: 10.5s	remaining: 19.8s
346:	learn: 0.0818334	total: 10.5s	remaining: 19.8s
347:	learn: 0.0817103	total: 10.5s	remaining: 19.7s
348:	learn: 0.0815636	total: 10.6s	remaining: 19.7s
349:	learn: 0.0815523	total: 10.6s	remaining: 19.7s
350:	learn: 0.0815336	total: 10.6s	remaining: 19.6s
351:	learn: 0.0815063	total: 10.7s	remaining: 19.6s
352:	learn: 0.0813766	total: 10.7s	remaining: 19.6s
353:	learn: 0.0813097	total: 10.7s	remaining: 19.6s
354:	learn: 0.0812806	total: 10.7s	remaining: 19.5s
355:	learn: 0.0812129	total: 10.8s	remaining: 19.5s
356:	learn: 0.0811592	total: 10.8s	remaining: 19.5s
357:	learn: 0.0811456	total: 10.8s	remaining: 19.4s
358:	learn: 0.0810469	total: 10.9s	remaining: 19.4s
359:	learn: 0.0810071	total: 10.9s	remaining: 19.4s
360:	learn: 0.0809078	total: 10.9s	remaining: 19.3s
361:	learn: 0.0808970	total: 11s	remaining: 19.3s
362:	learn: 0.0808468	total: 11s	remaining: 19.3s
363:	learn: 0.0808397	total: 11s	remaining: 19.3s
364:	learn: 0.0808362	total: 11.1s	remaining: 19.2s
365:	learn: 0.0807365	total: 11.1s	remaining: 19.2s
366:	learn: 0.0807257	total: 11.1s	remaining: 19.2s
367:	learn: 0.0806957	total: 11.1s	remaining: 19.1s
368:	learn: 0.0806242	total: 11.2s	remaining: 19.1s
369:	learn: 0.0806060	total: 11.2s	remaining: 19.1s
370:	learn: 0.0805581	total: 11.2s	remaining: 19.1s
371:	learn: 0.0804886	total: 11.3s	remaining: 19s
372:	learn: 0.0803206	total: 11.3s	remaining: 19s
373:	learn: 0.0803173	total: 11.3s	remaining: 19s
374:	learn: 0.0802198	total: 11.4s	remaining: 18.9s
375:	learn: 0.0800824	total: 11.4s	remaining: 18.9s
376:	learn: 0.0800754	total: 11.4s	remaining: 18.9s
377:	learn: 0.0799825	total: 11.5s	remaining: 18.8s
378:	learn: 0.0798693	total: 11.5s	remaining: 18.8s
379:	learn: 0.0798150	total: 11.5s	remaining: 18.8s
380:	learn: 0.0796914	total: 11.5s	remaining: 18.8s
381:	learn: 0.0796429	total: 11.6s	remaining: 18.7s
382:	learn: 0.0795369	total: 11.6s	remaining: 18.7s
383:	learn: 0.0794062	total: 11.6s	remaining: 18.7s
384:	learn: 0.0793884	total: 11.7s	remaining: 18.6s
385:	learn: 0.0793387	total: 11.7s	remaining: 18.6s
386:	learn: 0.0792469	total: 11.7s	remaining: 18.6s
387:	learn: 0.0792354	total: 11.8s	remaining: 18.5s

CV folds:  78%|███████▊  | 39/50 [20:32<05:43, 31.24s/fold]

Learning rate set to 0.042743
0:	learn: 0.3887504	total: 25.6ms	remaining: 25.6s
1:	learn: 0.3784091	total: 55ms	remaining: 27.4s
2:	learn: 0.3675495	total: 87.1ms	remaining: 28.9s
3:	learn: 0.3575749	total: 118ms	remaining: 29.4s
4:	learn: 0.3479518	total: 148ms	remaining: 29.4s
5:	learn: 0.3392212	total: 176ms	remaining: 29.2s
6:	learn: 0.3303248	total: 207ms	remaining: 29.4s
7:	learn: 0.3223399	total: 247ms	remaining: 30.6s
8:	learn: 0.3141352	total: 278ms	remaining: 30.7s
9:	learn: 0.3065468	total: 307ms	remaining: 30.4s
10:	learn: 0.2987813	total: 335ms	remaining: 30.1s
11:	learn: 0.2917364	total: 367ms	remaining: 30.2s
12:	learn: 0.2854491	total: 395ms	remaining: 30s
13:	learn: 0.2790740	total: 426ms	remaining: 30s
14:	learn: 0.2728158	total: 455ms	remaining: 29.9s
15:	learn: 0.2669708	total: 486ms	remaining: 29.9s
16:	learn: 0.2615059	total: 514ms	remaining: 29.7s
17:	learn: 0.2559891	total: 543ms	remaining: 29.6s
18:	learn: 0.2509186	total: 573ms	remaining: 29.6s
19:	learn: 0.2459463	total: 601ms	remaining: 29.4s
20:	learn: 0.2409039	total: 631ms	remaining: 29.4s
21:	learn: 0.2359385	total: 660ms	remaining: 29.3s
22:	learn: 0.2314289	total: 688ms	remaining: 29.2s
23:	learn: 0.2274703	total: 717ms	remaining: 29.2s
24:	learn: 0.2231288	total: 746ms	remaining: 29.1s
25:	learn: 0.2190260	total: 773ms	remaining: 29s
26:	learn: 0.2150311	total: 801ms	remaining: 28.9s
27:	learn: 0.2116272	total: 829ms	remaining: 28.8s
28:	learn: 0.2080325	total: 859ms	remaining: 28.8s
29:	learn: 0.2042264	total: 891ms	remaining: 28.8s
30:	learn: 0.2007304	total: 939ms	remaining: 29.3s
31:	learn: 0.1975420	total: 971ms	remaining: 29.4s
32:	learn: 0.1948307	total: 1s	remaining: 29.4s
33:	learn: 0.1921381	total: 1.03s	remaining: 29.3s
34:	learn: 0.1896381	total: 1.06s	remaining: 29.3s
35:	learn: 0.1865264	total: 1.09s	remaining: 29.3s
36:	learn: 0.1839073	total: 1.12s	remaining: 29.2s
37:	learn: 0.1810914	total: 1.15s	remaining: 29.1s
38:	learn: 0.1784002	total: 1.18s	remaining: 29.1s
39:	learn: 0.1757667	total: 1.21s	remaining: 29s
40:	learn: 0.1735201	total: 1.23s	remaining: 28.9s
41:	learn: 0.1713519	total: 1.26s	remaining: 28.8s
42:	learn: 0.1693704	total: 1.29s	remaining: 28.8s
43:	learn: 0.1674574	total: 1.32s	remaining: 28.7s
44:	learn: 0.1655622	total: 1.35s	remaining: 28.7s
45:	learn: 0.1634586	total: 1.38s	remaining: 28.6s
46:	learn: 0.1615834	total: 1.41s	remaining: 28.6s
47:	learn: 0.1596542	total: 1.44s	remaining: 28.5s
48:	learn: 0.1581896	total: 1.47s	remaining: 28.5s
49:	learn: 0.1565275	total: 1.5s	remaining: 28.4s
50:	learn: 0.1550079	total: 1.53s	remaining: 28.4s
51:	learn: 0.1532199	total: 1.56s	remaining: 28.4s
52:	learn: 0.1518137	total: 1.59s	remaining: 28.4s
53:	learn: 0.1505920	total: 1.61s	remaining: 28.3s
54:	learn: 0.1493530	total: 1.64s	remaining: 28.3s
55:	learn: 0.1481751	total: 1.67s	remaining: 28.2s
56:	learn: 0.1469992	total: 1.7s	remaining: 28.2s
57:	learn: 0.1457806	total: 1.73s	remaining: 28.1s
58:	learn: 0.1445565	total: 1.76s	remaining: 28.1s
59:	learn: 0.1433283	total: 1.79s	remaining: 28.1s
60:	learn: 0.1422994	total: 1.82s	remaining: 28.1s
61:	learn: 0.1413760	total: 1.85s	remaining: 28s
62:	learn: 0.1403041	total: 1.88s	remaining: 28s
63:	learn: 0.1393834	total: 1.91s	remaining: 28s
64:	learn: 0.1383147	total: 1.96s	remaining: 28.2s
65:	learn: 0.1374059	total: 2.02s	remaining: 28.6s
66:	learn: 0.1364849	total: 2.05s	remaining: 28.5s
67:	learn: 0.1356108	total: 2.08s	remaining: 28.5s
68:	learn: 0.1346929	total: 2.1s	remaining: 28.4s
69:	learn: 0.1337713	total: 2.13s	remaining: 28.3s
70:	learn: 0.1330430	total: 2.16s	remaining: 28.2s
71:	learn: 0.1321694	total: 2.19s	remaining: 28.2s
72:	learn: 0.1314198	total: 2.21s	remaining: 28.1s
73:	learn: 0.1306475	total: 2.24s	remaining: 28.1s
74:	learn: 0.1299436	total: 2.27s	remaining: 28s
75:	learn: 0.1291742	total: 2.3s	remaining: 28s
76:	learn: 0.1285339	total: 2.33s	remaining: 27.9s
77:	learn: 0.1276805	total: 2.36s	remaining: 27.9s
78:	learn: 0.1269810	total: 2.39s	remaining: 27.9s
79:	learn: 0.1264888	total: 2.42s	remaining: 27.8s
80:	learn: 0.1257967	total: 2.45s	remaining: 27.8s
81:	learn: 0.1252689	total: 2.48s	remaining: 27.8s
82:	learn: 0.1246654	total: 2.51s	remaining: 27.8s
83:	learn: 0.1244038	total: 2.53s	remaining: 27.6s
84:	learn: 0.1239415	total: 2.56s	remaining: 27.5s
85:	learn: 0.1233410	total: 2.59s	remaining: 27.5s
86:	learn: 0.1229217	total: 2.62s	remaining: 27.5s
87:	learn: 0.1222542	total: 2.65s	remaining: 27.4s
88:	learn: 0.1216598	total: 2.67s	remaining: 27.4s
89:	learn: 0.1213330	total: 2.7s	remaining: 27.3s
90:	learn: 0.1207672	total: 2.73s	remaining: 27.3s
91:	learn: 0.1202890	total: 2.76s	remaining: 27.2s
92:	learn: 0.1196101	total: 2.79s	remaining: 27.2s
93:	learn: 0.1190703	total: 2.82s	remaining: 27.2s
94:	learn: 0.1184668	total: 2.85s	remaining: 27.1s
95:	learn: 0.1180934	total: 2.88s	remaining: 27.1s
96:	learn: 0.1177600	total: 2.91s	remaining: 27.1s
97:	learn: 0.1174023	total: 2.94s	remaining: 27s
98:	learn: 0.1169267	total: 2.97s	remaining: 27s
99:	learn: 0.1165216	total: 3s	remaining: 27s
100:	learn: 0.1159695	total: 3.02s	remaining: 26.9s
101:	learn: 0.1156776	total: 3.06s	remaining: 26.9s
102:	learn: 0.1154584	total: 3.11s	remaining: 27s
103:	learn: 0.1150113	total: 3.14s	remaining: 27.1s
104:	learn: 0.1146678	total: 3.17s	remaining: 27s
105:	learn: 0.1142978	total: 3.2s	remaining: 27s
106:	learn: 0.1139386	total: 3.23s	remaining: 26.9s
107:	learn: 0.1134293	total: 3.26s	remaining: 26.9s
108:	learn: 0.1130469	total: 3.29s	remaining: 26.9s
109:	learn: 0.1126215	total: 3.31s	remaining: 26.8s
110:	learn: 0.1122033	total: 3.34s	remaining: 26.8s
111:	learn: 0.1117605	total: 3.38s	remaining: 26.8s
112:	learn: 0.1114334	total: 3.41s	remaining: 26.8s
113:	learn: 0.1110872	total: 3.44s	remaining: 26.7s
114:	learn: 0.1107267	total: 3.47s	remaining: 26.7s
115:	learn: 0.1104376	total: 3.5s	remaining: 26.7s
116:	learn: 0.1101394	total: 3.53s	remaining: 26.6s
117:	learn: 0.1099641	total: 3.56s	remaining: 26.6s
118:	learn: 0.1095433	total: 3.59s	remaining: 26.6s
119:	learn: 0.1091842	total: 3.62s	remaining: 26.6s
120:	learn: 0.1088745	total: 3.65s	remaining: 26.5s
121:	learn: 0.1085812	total: 3.68s	remaining: 26.5s
122:	learn: 0.1083355	total: 3.71s	remaining: 26.5s
123:	learn: 0.1080354	total: 3.74s	remaining: 26.4s
124:	learn: 0.1078160	total: 3.77s	remaining: 26.4s
125:	learn: 0.1075738	total: 3.8s	remaining: 26.4s
126:	learn: 0.1074025	total: 3.83s	remaining: 26.3s
127:	learn: 0.1071196	total: 3.86s	remaining: 26.3s
128:	learn: 0.1068509	total: 3.89s	remaining: 26.3s
129:	learn: 0.1066329	total: 3.92s	remaining: 26.2s
130:	learn: 0.1064535	total: 3.94s	remaining: 26.2s
131:	learn: 0.1062893	total: 3.97s	remaining: 26.1s
132:	learn: 0.1060017	total: 4s	remaining: 26.1s
133:	learn: 0.1057774	total: 4.03s	remaining: 26.1s
134:	learn: 0.1054443	total: 4.06s	remaining: 26s
135:	learn: 0.1051536	total: 4.09s	remaining: 26s
136:	learn: 0.1049410	total: 4.12s	remaining: 26s
137:	learn: 0.1048478	total: 4.15s	remaining: 25.9s
138:	learn: 0.1046106	total: 4.18s	remaining: 25.9s
139:	learn: 0.1043165	total: 4.21s	remaining: 25.9s
140:	learn: 0.1040538	total: 4.24s	remaining: 25.8s
141:	learn: 0.1036773	total: 4.27s	remaining: 25.8s
142:	learn: 0.1034424	total: 4.3s	remaining: 25.8s
143:	learn: 0.1032058	total: 4.33s	remaining: 25.7s
144:	learn: 0.1030498	total: 4.36s	remaining: 25.7s
145:	learn: 0.1028493	total: 4.4s	remaining: 25.7s
146:	learn: 0.1026525	total: 4.43s	remaining: 25.7s
147:	learn: 0.1024793	total: 4.46s	remaining: 25.7s
148:	learn: 0.1022737	total: 4.49s	remaining: 25.6s
149:	learn: 0.1020452	total: 4.52s	remaining: 25.6s
150:	learn: 0.1018038	total: 4.55s	remaining: 25.6s
151:	learn: 0.1016535	total: 4.58s	remaining: 25.6s
152:	learn: 0.1015145	total: 4.61s	remaining: 25.5s
153:	learn: 0.1013193	total: 4.64s	remaining: 25.5s
154:	learn: 0.1010431	total: 4.67s	remaining: 25.5s
155:	learn: 0.1008012	total: 4.7s	remaining: 25.4s
156:	learn: 0.1005891	total: 4.73s	remaining: 25.4s
157:	learn: 0.1004231	total: 4.76s	remaining: 25.4s
158:	learn: 0.1002509	total: 4.79s	remaining: 25.4s
159:	learn: 0.1000227	total: 4.82s	remaining: 25.3s
160:	learn: 0.0999019	total: 4.85s	remaining: 25.3s
161:	learn: 0.0997023	total: 4.88s	remaining: 25.3s
162:	learn: 0.0994610	total: 4.91s	remaining: 25.2s
163:	learn: 0.0992539	total: 4.94s	remaining: 25.2s
164:	learn: 0.0990835	total: 4.98s	remaining: 25.2s
165:	learn: 0.0989664	total: 5.01s	remaining: 25.1s
166:	learn: 0.0986552	total: 5.04s	remaining: 25.1s
167:	learn: 0.0985513	total: 5.07s	remaining: 25.1s
168:	learn: 0.0983164	total: 5.09s	remaining: 25s
169:	learn: 0.0981164	total: 5.12s	remaining: 25s
170:	learn: 0.0980327	total: 5.15s	remaining: 25s
171:	learn: 0.0978240	total: 5.18s	remaining: 24.9s
172:	learn: 0.0977076	total: 5.22s	remaining: 25s
173:	learn: 0.0973732	total: 5.26s	remaining: 25s
174:	learn: 0.0972504	total: 5.29s	remaining: 24.9s
175:	learn: 0.0971156	total: 5.32s	remaining: 24.9s
176:	learn: 0.0970095	total: 5.35s	remaining: 24.9s
177:	learn: 0.0968693	total: 5.39s	remaining: 24.9s
178:	learn: 0.0967366	total: 5.42s	remaining: 24.8s
179:	learn: 0.0966061	total: 5.45s	remaining: 24.8s
180:	learn: 0.0963941	total: 5.49s	remaining: 24.8s
181:	learn: 0.0962178	total: 5.53s	remaining: 24.8s
182:	learn: 0.0960007	total: 5.56s	remaining: 24.8s
183:	learn: 0.0957477	total: 5.6s	remaining: 24.8s
184:	learn: 0.0955534	total: 5.63s	remaining: 24.8s
185:	learn: 0.0954727	total: 5.66s	remaining: 24.8s
186:	learn: 0.0953386	total: 5.69s	remaining: 24.7s
187:	learn: 0.0951277	total: 5.72s	remaining: 24.7s
188:	learn: 0.0949555	total: 5.76s	remaining: 24.7s
189:	learn: 0.0948365	total: 5.8s	remaining: 24.8s
190:	learn: 0.0947589	total: 5.84s	remaining: 24.7s
191:	learn: 0.0946869	total: 5.87s	remaining: 24.7s
192:	learn: 0.0944035	total: 5.91s	remaining: 24.7s
193:	learn: 0.0942566	total: 5.93s	remaining: 24.7s
194:	learn: 0.0941052	total: 5.96s	remaining: 24.6s
195:	learn: 0.0939731	total: 5.99s	remaining: 24.6s
196:	learn: 0.0937232	total: 6.02s	remaining: 24.5s
197:	learn: 0.0935779	total: 6.05s	remaining: 24.5s
198:	learn: 0.0934288	total: 6.08s	remaining: 24.5s
199:	learn: 0.0932562	total: 6.11s	remaining: 24.4s
200:	learn: 0.0931001	total: 6.14s	remaining: 24.4s
201:	learn: 0.0929897	total: 6.17s	remaining: 24.4s
202:	learn: 0.0928966	total: 6.2s	remaining: 24.3s
203:	learn: 0.0927841	total: 6.23s	remaining: 24.3s
204:	learn: 0.0926376	total: 6.26s	remaining: 24.3s
205:	learn: 0.0924571	total: 6.29s	remaining: 24.2s
206:	learn: 0.0923973	total: 6.32s	remaining: 24.2s
207:	learn: 0.0922150	total: 6.35s	remaining: 24.2s
208:	learn: 0.0921628	total: 6.38s	remaining: 24.1s
209:	learn: 0.0920040	total: 6.41s	remaining: 24.1s
210:	learn: 0.0919310	total: 6.44s	remaining: 24.1s
211:	learn: 0.0918599	total: 6.46s	remaining: 24s
212:	learn: 0.0917269	total: 6.5s	remaining: 24s
213:	learn: 0.0915693	total: 6.53s	remaining: 24s
214:	learn: 0.0914846	total: 6.56s	remaining: 24s
215:	learn: 0.0913701	total: 6.59s	remaining: 23.9s
216:	learn: 0.0912962	total: 6.62s	remaining: 23.9s
217:	learn: 0.0911714	total: 6.64s	remaining: 23.8s
218:	learn: 0.0910737	total: 6.68s	remaining: 23.8s
219:	learn: 0.0909977	total: 6.71s	remaining: 23.8s
220:	learn: 0.0908733	total: 6.74s	remaining: 23.8s
221:	learn: 0.0907229	total: 6.77s	remaining: 23.7s
222:	learn: 0.0906359	total: 6.79s	remaining: 23.7s
223:	learn: 0.0904830	total: 6.82s	remaining: 23.6s
224:	learn: 0.0904318	total: 6.85s	remaining: 23.6s
225:	learn: 0.0902500	total: 6.88s	remaining: 23.6s
226:	learn: 0.0901669	total: 6.91s	remaining: 23.5s
227:	learn: 0.0900753	total: 6.94s	remaining: 23.5s
228:	learn: 0.0900233	total: 6.97s	remaining: 23.5s
229:	learn: 0.0898829	total: 7s	remaining: 23.4s
230:	learn: 0.0897195	total: 7.03s	remaining: 23.4s
231:	learn: 0.0895819	total: 7.06s	remaining: 23.4s
232:	learn: 0.0894278	total: 7.11s	remaining: 23.4s
233:	learn: 0.0893730	total: 7.14s	remaining: 23.4s
234:	learn: 0.0892736	total: 7.17s	remaining: 23.3s
235:	learn: 0.0891595	total: 7.2s	remaining: 23.3s
236:	learn: 0.0890727	total: 7.22s	remaining: 23.3s
237:	learn: 0.0889590	total: 7.25s	remaining: 23.2s
238:	learn: 0.0888546	total: 7.28s	remaining: 23.2s
239:	learn: 0.0887701	total: 7.32s	remaining: 23.2s
240:	learn: 0.0886231	total: 7.35s	remaining: 23.1s
241:	learn: 0.0885408	total: 7.4s	remaining: 23.2s
242:	learn: 0.0884448	total: 7.43s	remaining: 23.1s
243:	learn: 0.0883757	total: 7.46s	remaining: 23.1s
244:	learn: 0.0881504	total: 7.49s	remaining: 23.1s
245:	learn: 0.0881178	total: 7.52s	remaining: 23s
246:	learn: 0.0879516	total: 7.55s	remaining: 23s
247:	learn: 0.0877696	total: 7.59s	remaining: 23s
248:	learn: 0.0877203	total: 7.62s	remaining: 23s
249:	learn: 0.0876611	total: 7.64s	remaining: 22.9s
250:	learn: 0.0875954	total: 7.67s	remaining: 22.9s
251:	learn: 0.0875660	total: 7.7s	remaining: 22.9s
252:	learn: 0.0875080	total: 7.74s	remaining: 22.8s
253:	learn: 0.0873894	total: 7.77s	remaining: 22.8s
254:	learn: 0.0872187	total: 7.8s	remaining: 22.8s
255:	learn: 0.0871802	total: 7.83s	remaining: 22.8s
256:	learn: 0.0870887	total: 7.86s	remaining: 22.7s
257:	learn: 0.0868702	total: 7.89s	remaining: 22.7s
258:	learn: 0.0867901	total: 7.92s	remaining: 22.7s
259:	learn: 0.0866654	total: 7.95s	remaining: 22.6s
260:	learn: 0.0865437	total: 7.98s	remaining: 22.6s
261:	learn: 0.0864901	total: 8.01s	remaining: 22.6s
262:	learn: 0.0864609	total: 8.04s	remaining: 22.5s
263:	learn: 0.0863585	total: 8.07s	remaining: 22.5s
264:	learn: 0.0861601	total: 8.1s	remaining: 22.5s
265:	learn: 0.0860353	total: 8.13s	remaining: 22.4s
266:	learn: 0.0859166	total: 8.16s	remaining: 22.4s
267:	learn: 0.0858616	total: 8.19s	remaining: 22.4s
268:	learn: 0.0857355	total: 8.22s	remaining: 22.3s
269:	learn: 0.0855730	total: 8.26s	remaining: 22.3s
270:	learn: 0.0854542	total: 8.29s	remaining: 22.3s
271:	learn: 0.0852732	total: 8.32s	remaining: 22.3s
272:	learn: 0.0851693	total: 8.35s	remaining: 22.2s
273:	learn: 0.0850300	total: 8.38s	remaining: 22.2s
274:	learn: 0.0849622	total: 8.41s	remaining: 22.2s
275:	learn: 0.0848468	total: 8.44s	remaining: 22.1s
276:	learn: 0.0847948	total: 8.47s	remaining: 22.1s
277:	learn: 0.0846872	total: 8.5s	remaining: 22.1s
278:	learn: 0.0845966	total: 8.53s	remaining: 22s
279:	learn: 0.0845879	total: 8.56s	remaining: 22s
280:	learn: 0.0845025	total: 8.59s	remaining: 22s
281:	learn: 0.0844553	total: 8.62s	remaining: 21.9s
282:	learn: 0.0843138	total: 8.65s	remaining: 21.9s
283:	learn: 0.0842137	total: 8.68s	remaining: 21.9s
284:	learn: 0.0841060	total: 8.71s	remaining: 21.9s
285:	learn: 0.0839790	total: 8.74s	remaining: 21.8s
286:	learn: 0.0838962	total: 8.77s	remaining: 21.8s
287:	learn: 0.0838569	total: 8.8s	remaining: 21.8s
288:	learn: 0.0837537	total: 8.83s	remaining: 21.7s
289:	learn: 0.0836399	total: 8.86s	remaining: 21.7s
290:	learn: 0.0834720	total: 8.88s	remaining: 21.6s
291:	learn: 0.0833511	total: 8.91s	remaining: 21.6s
292:	learn: 0.0831840	total: 8.95s	remaining: 21.6s
293:	learn: 0.0829875	total: 8.98s	remaining: 21.6s
294:	learn: 0.0829244	total: 9.01s	remaining: 21.5s
295:	learn: 0.0828587	total: 9.04s	remaining: 21.5s
296:	learn: 0.0827898	total: 9.07s	remaining: 21.5s
297:	learn: 0.0827539	total: 9.1s	remaining: 21.4s
298:	learn: 0.0826034	total: 9.13s	remaining: 21.4s
299:	learn: 0.0825683	total: 9.16s	remaining: 21.4s
300:	learn: 0.0823509	total: 9.19s	remaining: 21.3s
301:	learn: 0.0823120	total: 9.21s	remaining: 21.3s
302:	learn: 0.0823038	total: 9.24s	remaining: 21.3s
303:	learn: 0.0821364	total: 9.27s	remaining: 21.2s
304:	learn: 0.0820744	total: 9.3s	remaining: 21.2s
305:	learn: 0.0818829	total: 9.33s	remaining: 21.2s
306:	learn: 0.0818189	total: 9.36s	remaining: 21.1s
307:	learn: 0.0817254	total: 9.4s	remaining: 21.1s
308:	learn: 0.0816115	total: 9.43s	remaining: 21.1s
309:	learn: 0.0815004	total: 9.47s	remaining: 21.1s
310:	learn: 0.0814045	total: 9.5s	remaining: 21s
311:	learn: 0.0813559	total: 9.54s	remaining: 21s
312:	learn: 0.0813397	total: 9.58s	remaining: 21s
313:	learn: 0.0812386	total: 9.62s	remaining: 21s
314:	learn: 0.0811814	total: 9.65s	remaining: 21s
315:	learn: 0.0811698	total: 9.67s	remaining: 20.9s
316:	learn: 0.0810631	total: 9.72s	remaining: 20.9s
317:	learn: 0.0810556	total: 9.76s	remaining: 20.9s
318:	learn: 0.0809821	total: 9.79s	remaining: 20.9s
319:	learn: 0.0809357	total: 9.82s	remaining: 20.9s
320:	learn: 0.0808727	total: 9.85s	remaining: 20.8s
321:	learn: 0.0807663	total: 9.88s	remaining: 20.8s
322:	learn: 0.0807440	total: 9.91s	remaining: 20.8s
323:	learn: 0.0806435	total: 9.94s	remaining: 20.7s
324:	learn: 0.0805183	total: 9.97s	remaining: 20.7s
325:	learn: 0.0803422	total: 10s	remaining: 20.7s
326:	learn: 0.0802258	total: 10s	remaining: 20.7s
327:	learn: 0.0801845	total: 10.1s	remaining: 20.6s
328:	learn: 0.0801110	total: 10.1s	remaining: 20.6s
329:	learn: 0.0800280	total: 10.1s	remaining: 20.6s
330:	learn: 0.0799144	total: 10.2s	remaining: 20.5s
331:	learn: 0.0798039	total: 10.2s	remaining: 20.5s
332:	learn: 0.0797508	total: 10.2s	remaining: 20.5s
333:	learn: 0.0797426	total: 10.2s	remaining: 20.4s
334:	learn: 0.0796429	total: 10.3s	remaining: 20.4s
335:	learn: 0.0796204	total: 10.3s	remaining: 20.4s
336:	learn: 0.0795319	total: 10.3s	remaining: 20.3s
337:	learn: 0.0794802	total: 10.4s	remaining: 20.3s
338:	learn: 0.0794704	total: 10.4s	remaining: 20.3s
339:	learn: 0.0793403	total: 10.4s	remaining: 20.3s
340:	learn: 0.0792365	total: 10.5s	remaining: 20.2s
341:	learn: 0.0791313	total: 10.5s	remaining: 20.2s
342:	learn: 0.0790724	total: 10.5s	remaining: 20.1s
343:	learn: 0.0790577	total: 10.6s	remaining: 20.1s
344:	learn: 0.0789971	total: 10.6s	remaining: 20.1s
345:	learn: 0.0789853	total: 10.6s	remaining: 20.1s
346:	learn: 0.0788829	total: 10.6s	remaining: 20s
347:	learn: 0.0787387	total: 10.7s	remaining: 20s
348:	learn: 0.0787315	total: 10.7s	remaining: 20s
349:	learn: 0.0787172	total: 10.7s	remaining: 19.9s
350:	learn: 0.0785688	total: 10.8s	remaining: 19.9s
351:	learn: 0.0785216	total: 10.8s	remaining: 19.9s
352:	learn: 0.0783836	total: 10.8s	remaining: 19.8s
353:	learn: 0.0783767	total: 10.9s	remaining: 19.8s
354:	learn: 0.0783714	total: 10.9s	remaining: 19.8s
355:	learn: 0.0783325	total: 10.9s	remaining: 19.7s
356:	learn: 0.0781808	total: 10.9s	remaining: 19.7s
357:	learn: 0.0781671	total: 11s	remaining: 19.7s
358:	learn: 0.0781021	total: 11s	remaining: 19.6s
359:	learn: 0.0778932	total: 11s	remaining: 19.6s
360:	learn: 0.0778258	total: 11.1s	remaining: 19.6s
361:	learn: 0.0777101	total: 11.1s	remaining: 19.5s
362:	learn: 0.0776963	total: 11.1s	remaining: 19.5s
363:	learn: 0.0776149	total: 11.1s	remaining: 19.5s
364:	learn: 0.0775265	total: 11.2s	remaining: 19.4s
365:	learn: 0.0773738	total: 11.2s	remaining: 19.4s
366:	learn: 0.0772821	total: 11.2s	remaining: 19.4s
367:	learn: 0.0771809	total: 11.3s	remaining: 19.4s
368:	learn: 0.0770866	total: 11.3s	remaining: 19.3s
369:	learn: 0.0769813	total: 11.3s	remaining: 19.3s
370:	learn: 0.0768169	total: 11.4s	remaining: 19.3s
371:	learn: 0.0767484	total: 11.4s	remaining: 19.2s
372:	learn: 0.0765952	total: 11.4s	remaining: 19.2s
373:	learn: 0.0765637	total: 11.5s	remaining: 19.2s
374:	learn: 0.0764324	total: 11.5s	remaining: 19.1s
375:	learn: 0.0762651	total: 11.5s	remaining: 19.1s
376:	learn: 0.0762500	total: 11.6s	remaining: 19.1s
377:	learn: 0.0761283	total: 11.6s	remaining: 19.1s
378:	learn: 0.0760100	total: 11.6s	remaining: 19s
379:	learn: 0.0759786	total: 11.7s	remaining: 19s
380:	learn: 0.0759098	total: 11.7s	remaining: 19s
381:	learn: 0.0758574	total: 11.7s	remaining: 19s
382:	learn: 0.0758462	total: 11.8s	remaining: 18.9s
383:	learn: 0.0758266	total: 11.8s	remaining: 18.9s
384:	learn: 0.0758127	total: 11.8s	remaining: 18.9s
385:	learn: 0.0758069	total: 11.8s	remaining: 18.8s
386:	learn: 0.0756335	total: 11.9s	remaining: 18.8s
387:	learn: 0.0755994	total: 11.9s	remaining: 18.8s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior1st': 1 unseen categories converted to Unseen on transform.

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior2nd': 1 unseen categories converted to Unseen on transform.

CV folds:  80%|████████  | 40/50 [21:03<05:13, 31.34s/fold]

998:	learn: 0.0442300	total: 31s	remaining: 31.1ms
999:	learn: 0.0441530	total: 31.1s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3882199	total: 24.1ms	remaining: 24s
1:	learn: 0.3783427	total: 52ms	remaining: 25.9s
2:	learn: 0.3681936	total: 78.9ms	remaining: 26.2s
3:	learn: 0.3576974	total: 107ms	remaining: 26.7s
4:	learn: 0.3485837	total: 135ms	remaining: 26.8s
5:	learn: 0.3387826	total: 163ms	remaining: 27s
6:	learn: 0.3302206	total: 192ms	remaining: 27.2s
7:	learn: 0.3219080	total: 223ms	remaining: 27.6s
8:	learn: 0.3137481	total: 252ms	remaining: 27.8s
9:	learn: 0.3062361	total: 283ms	remaining: 28s
10:	learn: 0.2986815	total: 312ms	remaining: 28s
11:	learn: 0.2917859	total: 343ms	remaining: 28.3s
12:	learn: 0.2846806	total: 372ms	remaining: 28.2s
13:	learn: 0.2789622	total: 402ms	remaining: 28.3s
14:	learn: 0.2729867	total: 436ms	remaining: 28.6s
15:	learn: 0.2666608	total: 463ms	remaining: 28.5s
16:	learn: 0.2608142	total: 493ms	remaining: 28.5s
17:	learn: 0.2551324	total: 522ms	remaining: 28.5s
18:	learn: 0.2495476	total: 551ms	remaining: 28.4s
19:	learn: 0.2445464	total: 579ms	remaining: 28.4s
20:	learn: 0.2397372	total: 609ms	remaining: 28.4s
21:	learn: 0.2353195	total: 641ms	remaining: 28.5s
22:	learn: 0.2303240	total: 670ms	remaining: 28.5s
23:	learn: 0.2256449	total: 701ms	remaining: 28.5s
24:	learn: 0.2216754	total: 731ms	remaining: 28.5s
25:	learn: 0.2169616	total: 759ms	remaining: 28.4s
26:	learn: 0.2134459	total: 787ms	remaining: 28.3s
27:	learn: 0.2098314	total: 818ms	remaining: 28.4s
28:	learn: 0.2059840	total: 848ms	remaining: 28.4s
29:	learn: 0.2019296	total: 876ms	remaining: 28.3s
30:	learn: 0.1985197	total: 908ms	remaining: 28.4s
31:	learn: 0.1954797	total: 940ms	remaining: 28.4s
32:	learn: 0.1922968	total: 969ms	remaining: 28.4s
33:	learn: 0.1890405	total: 996ms	remaining: 28.3s
34:	learn: 0.1863767	total: 1.02s	remaining: 28.2s
35:	learn: 0.1834777	total: 1.05s	remaining: 28.3s
36:	learn: 0.1805863	total: 1.08s	remaining: 28.2s
37:	learn: 0.1777594	total: 1.11s	remaining: 28.1s
38:	learn: 0.1753422	total: 1.14s	remaining: 28.1s
39:	learn: 0.1728876	total: 1.17s	remaining: 28s
40:	learn: 0.1707164	total: 1.2s	remaining: 28s
41:	learn: 0.1682774	total: 1.23s	remaining: 28s
42:	learn: 0.1661920	total: 1.25s	remaining: 27.9s
43:	learn: 0.1643193	total: 1.29s	remaining: 28s
44:	learn: 0.1625134	total: 1.32s	remaining: 27.9s
45:	learn: 0.1606642	total: 1.35s	remaining: 28s
46:	learn: 0.1587368	total: 1.38s	remaining: 28s
47:	learn: 0.1568959	total: 1.41s	remaining: 28s
48:	learn: 0.1551891	total: 1.44s	remaining: 28s
49:	learn: 0.1536492	total: 1.47s	remaining: 28s
50:	learn: 0.1519616	total: 1.5s	remaining: 27.9s
51:	learn: 0.1504292	total: 1.53s	remaining: 27.9s
52:	learn: 0.1488701	total: 1.56s	remaining: 27.9s
53:	learn: 0.1474929	total: 1.59s	remaining: 27.9s
54:	learn: 0.1461130	total: 1.62s	remaining: 27.8s
55:	learn: 0.1449718	total: 1.65s	remaining: 27.8s
56:	learn: 0.1436775	total: 1.68s	remaining: 27.8s
57:	learn: 0.1424750	total: 1.71s	remaining: 27.8s
58:	learn: 0.1413022	total: 1.74s	remaining: 27.8s
59:	learn: 0.1401934	total: 1.77s	remaining: 27.8s
60:	learn: 0.1390537	total: 1.8s	remaining: 27.8s
61:	learn: 0.1379721	total: 1.83s	remaining: 27.8s
62:	learn: 0.1370715	total: 1.87s	remaining: 27.8s
63:	learn: 0.1362327	total: 1.9s	remaining: 27.8s
64:	learn: 0.1351213	total: 1.95s	remaining: 28s
65:	learn: 0.1342770	total: 1.98s	remaining: 28s
66:	learn: 0.1334256	total: 2.01s	remaining: 28s
67:	learn: 0.1325847	total: 2.04s	remaining: 27.9s
68:	learn: 0.1317521	total: 2.07s	remaining: 27.9s
69:	learn: 0.1310607	total: 2.1s	remaining: 27.8s
70:	learn: 0.1301050	total: 2.13s	remaining: 27.8s
71:	learn: 0.1293238	total: 2.15s	remaining: 27.8s
72:	learn: 0.1285045	total: 2.18s	remaining: 27.7s
73:	learn: 0.1278818	total: 2.21s	remaining: 27.7s
74:	learn: 0.1270712	total: 2.24s	remaining: 27.6s
75:	learn: 0.1261397	total: 2.27s	remaining: 27.6s
76:	learn: 0.1254724	total: 2.3s	remaining: 27.6s
77:	learn: 0.1249042	total: 2.33s	remaining: 27.5s
78:	learn: 0.1242692	total: 2.38s	remaining: 27.7s
79:	learn: 0.1235746	total: 2.41s	remaining: 27.7s
80:	learn: 0.1229906	total: 2.44s	remaining: 27.7s
81:	learn: 0.1225001	total: 2.47s	remaining: 27.7s
82:	learn: 0.1219562	total: 2.5s	remaining: 27.6s
83:	learn: 0.1213001	total: 2.53s	remaining: 27.6s
84:	learn: 0.1207927	total: 2.56s	remaining: 27.6s
85:	learn: 0.1201643	total: 2.59s	remaining: 27.5s
86:	learn: 0.1198389	total: 2.61s	remaining: 27.4s
87:	learn: 0.1194628	total: 2.64s	remaining: 27.4s
88:	learn: 0.1190344	total: 2.68s	remaining: 27.4s
89:	learn: 0.1184884	total: 2.71s	remaining: 27.4s
90:	learn: 0.1179215	total: 2.74s	remaining: 27.4s
91:	learn: 0.1175800	total: 2.77s	remaining: 27.3s
92:	learn: 0.1171137	total: 2.8s	remaining: 27.3s
93:	learn: 0.1165625	total: 2.83s	remaining: 27.2s
94:	learn: 0.1161524	total: 2.86s	remaining: 27.2s
95:	learn: 0.1154976	total: 2.9s	remaining: 27.3s
96:	learn: 0.1151284	total: 2.93s	remaining: 27.3s
97:	learn: 0.1148212	total: 2.96s	remaining: 27.2s
98:	learn: 0.1144463	total: 2.99s	remaining: 27.2s
99:	learn: 0.1139544	total: 3.02s	remaining: 27.1s
100:	learn: 0.1135138	total: 3.04s	remaining: 27.1s
101:	learn: 0.1129824	total: 3.07s	remaining: 27s
102:	learn: 0.1126692	total: 3.1s	remaining: 27s
103:	learn: 0.1123178	total: 3.13s	remaining: 27s
104:	learn: 0.1120763	total: 3.16s	remaining: 27s
105:	learn: 0.1116288	total: 3.19s	remaining: 26.9s
106:	learn: 0.1111492	total: 3.22s	remaining: 26.9s
107:	learn: 0.1108722	total: 3.25s	remaining: 26.8s
108:	learn: 0.1104967	total: 3.28s	remaining: 26.8s
109:	learn: 0.1100693	total: 3.3s	remaining: 26.7s
110:	learn: 0.1096241	total: 3.33s	remaining: 26.7s
111:	learn: 0.1093568	total: 3.36s	remaining: 26.7s
112:	learn: 0.1089219	total: 3.39s	remaining: 26.6s
113:	learn: 0.1086074	total: 3.42s	remaining: 26.6s
114:	learn: 0.1083919	total: 3.45s	remaining: 26.6s
115:	learn: 0.1081145	total: 3.48s	remaining: 26.5s
116:	learn: 0.1078592	total: 3.51s	remaining: 26.5s
117:	learn: 0.1076130	total: 3.54s	remaining: 26.5s
118:	learn: 0.1072254	total: 3.57s	remaining: 26.4s
119:	learn: 0.1069197	total: 3.6s	remaining: 26.4s
120:	learn: 0.1066478	total: 3.63s	remaining: 26.4s
121:	learn: 0.1064103	total: 3.66s	remaining: 26.4s
122:	learn: 0.1061516	total: 3.69s	remaining: 26.3s
123:	learn: 0.1058120	total: 3.72s	remaining: 26.3s
124:	learn: 0.1054811	total: 3.75s	remaining: 26.3s
125:	learn: 0.1052163	total: 3.78s	remaining: 26.2s
126:	learn: 0.1049471	total: 3.81s	remaining: 26.2s
127:	learn: 0.1046569	total: 3.84s	remaining: 26.2s
128:	learn: 0.1043940	total: 3.87s	remaining: 26.1s
129:	learn: 0.1041370	total: 3.9s	remaining: 26.1s
130:	learn: 0.1039809	total: 3.94s	remaining: 26.1s
131:	learn: 0.1037450	total: 3.97s	remaining: 26.1s
132:	learn: 0.1035821	total: 4s	remaining: 26.1s
133:	learn: 0.1032840	total: 4.03s	remaining: 26s
134:	learn: 0.1031393	total: 4.06s	remaining: 26s
135:	learn: 0.1030558	total: 4.1s	remaining: 26s
136:	learn: 0.1028867	total: 4.13s	remaining: 26s
137:	learn: 0.1026979	total: 4.16s	remaining: 26s
138:	learn: 0.1024605	total: 4.19s	remaining: 25.9s
139:	learn: 0.1022782	total: 4.22s	remaining: 25.9s
140:	learn: 0.1021691	total: 4.25s	remaining: 25.9s
141:	learn: 0.1019681	total: 4.28s	remaining: 25.9s
142:	learn: 0.1017881	total: 4.31s	remaining: 25.8s
143:	learn: 0.1015962	total: 4.34s	remaining: 25.8s
144:	learn: 0.1013457	total: 4.36s	remaining: 25.7s
145:	learn: 0.1011509	total: 4.39s	remaining: 25.7s
146:	learn: 0.1009660	total: 4.42s	remaining: 25.7s
147:	learn: 0.1008617	total: 4.44s	remaining: 25.6s
148:	learn: 0.1005985	total: 4.47s	remaining: 25.5s
149:	learn: 0.1004421	total: 4.5s	remaining: 25.5s
150:	learn: 0.1002898	total: 4.53s	remaining: 25.4s
151:	learn: 0.1001956	total: 4.55s	remaining: 25.4s
152:	learn: 0.0998833	total: 4.58s	remaining: 25.4s
153:	learn: 0.0997385	total: 4.61s	remaining: 25.3s
154:	learn: 0.0995558	total: 4.64s	remaining: 25.3s
155:	learn: 0.0994224	total: 4.67s	remaining: 25.3s
156:	learn: 0.0993103	total: 4.71s	remaining: 25.3s
157:	learn: 0.0992000	total: 4.74s	remaining: 25.2s
158:	learn: 0.0991118	total: 4.77s	remaining: 25.2s
159:	learn: 0.0989050	total: 4.8s	remaining: 25.2s
160:	learn: 0.0988316	total: 4.83s	remaining: 25.2s
161:	learn: 0.0986779	total: 4.86s	remaining: 25.1s
162:	learn: 0.0984919	total: 4.89s	remaining: 25.1s
163:	learn: 0.0983714	total: 4.92s	remaining: 25.1s
164:	learn: 0.0981616	total: 4.95s	remaining: 25s
165:	learn: 0.0981161	total: 4.96s	remaining: 24.9s
166:	learn: 0.0980985	total: 4.96s	remaining: 24.8s
167:	learn: 0.0978809	total: 4.99s	remaining: 24.7s
168:	learn: 0.0977041	total: 5.02s	remaining: 24.7s
169:	learn: 0.0976180	total: 5.05s	remaining: 24.7s
170:	learn: 0.0975225	total: 5.08s	remaining: 24.6s
171:	learn: 0.0973055	total: 5.11s	remaining: 24.6s
172:	learn: 0.0971702	total: 5.14s	remaining: 24.6s
173:	learn: 0.0968947	total: 5.17s	remaining: 24.5s
174:	learn: 0.0967907	total: 5.2s	remaining: 24.5s
175:	learn: 0.0967156	total: 5.23s	remaining: 24.5s
176:	learn: 0.0966019	total: 5.26s	remaining: 24.5s
177:	learn: 0.0964837	total: 5.29s	remaining: 24.4s
178:	learn: 0.0964114	total: 5.32s	remaining: 24.4s
179:	learn: 0.0962968	total: 5.37s	remaining: 24.5s
180:	learn: 0.0961958	total: 5.4s	remaining: 24.5s
181:	learn: 0.0959704	total: 5.43s	remaining: 24.4s
182:	learn: 0.0958022	total: 5.46s	remaining: 24.4s
183:	learn: 0.0955190	total: 5.49s	remaining: 24.4s
184:	learn: 0.0954052	total: 5.52s	remaining: 24.3s
185:	learn: 0.0952922	total: 5.55s	remaining: 24.3s
186:	learn: 0.0950682	total: 5.58s	remaining: 24.3s
187:	learn: 0.0948276	total: 5.61s	remaining: 24.2s
188:	learn: 0.0947555	total: 5.64s	remaining: 24.2s
189:	learn: 0.0946593	total: 5.67s	remaining: 24.2s
190:	learn: 0.0944837	total: 5.7s	remaining: 24.1s
191:	learn: 0.0942737	total: 5.73s	remaining: 24.1s
192:	learn: 0.0941949	total: 5.75s	remaining: 24.1s
193:	learn: 0.0940229	total: 5.79s	remaining: 24s
194:	learn: 0.0937993	total: 5.82s	remaining: 24s
195:	learn: 0.0936262	total: 5.85s	remaining: 24s
196:	learn: 0.0935762	total: 5.88s	remaining: 24s
197:	learn: 0.0934683	total: 5.91s	remaining: 23.9s
198:	learn: 0.0933726	total: 5.94s	remaining: 23.9s
199:	learn: 0.0933177	total: 5.97s	remaining: 23.9s
200:	learn: 0.0931709	total: 6s	remaining: 23.8s
201:	learn: 0.0931070	total: 6.03s	remaining: 23.8s
202:	learn: 0.0930623	total: 6.05s	remaining: 23.8s
203:	learn: 0.0928812	total: 6.08s	remaining: 23.7s
204:	learn: 0.0928021	total: 6.12s	remaining: 23.7s
205:	learn: 0.0926078	total: 6.15s	remaining: 23.7s
206:	learn: 0.0923082	total: 6.17s	remaining: 23.7s
207:	learn: 0.0922547	total: 6.2s	remaining: 23.6s
208:	learn: 0.0921517	total: 6.25s	remaining: 23.6s
209:	learn: 0.0920175	total: 6.28s	remaining: 23.6s
210:	learn: 0.0919466	total: 6.31s	remaining: 23.6s
211:	learn: 0.0919035	total: 6.34s	remaining: 23.6s
212:	learn: 0.0917616	total: 6.37s	remaining: 23.5s
213:	learn: 0.0916528	total: 6.4s	remaining: 23.5s
214:	learn: 0.0915506	total: 6.43s	remaining: 23.5s
215:	learn: 0.0914867	total: 6.46s	remaining: 23.4s
216:	learn: 0.0913314	total: 6.49s	remaining: 23.4s
217:	learn: 0.0910727	total: 6.52s	remaining: 23.4s
218:	learn: 0.0909008	total: 6.55s	remaining: 23.3s
219:	learn: 0.0908630	total: 6.58s	remaining: 23.3s
220:	learn: 0.0907325	total: 6.6s	remaining: 23.3s
221:	learn: 0.0906982	total: 6.63s	remaining: 23.2s
222:	learn: 0.0904107	total: 6.66s	remaining: 23.2s
223:	learn: 0.0902883	total: 6.69s	remaining: 23.2s
224:	learn: 0.0900760	total: 6.72s	remaining: 23.2s
225:	learn: 0.0900397	total: 6.75s	remaining: 23.1s
226:	learn: 0.0899654	total: 6.78s	remaining: 23.1s
227:	learn: 0.0898872	total: 6.82s	remaining: 23.1s
228:	learn: 0.0898272	total: 6.84s	remaining: 23s
229:	learn: 0.0897403	total: 6.88s	remaining: 23s
230:	learn: 0.0895859	total: 6.91s	remaining: 23s
231:	learn: 0.0895492	total: 6.94s	remaining: 23s
232:	learn: 0.0893235	total: 6.97s	remaining: 22.9s
233:	learn: 0.0892817	total: 7s	remaining: 22.9s
234:	learn: 0.0892641	total: 7.03s	remaining: 22.9s
235:	learn: 0.0891714	total: 7.06s	remaining: 22.9s
236:	learn: 0.0891428	total: 7.09s	remaining: 22.8s
237:	learn: 0.0891058	total: 7.12s	remaining: 22.8s
238:	learn: 0.0889714	total: 7.15s	remaining: 22.8s
239:	learn: 0.0887825	total: 7.18s	remaining: 22.7s
240:	learn: 0.0885595	total: 7.21s	remaining: 22.7s
241:	learn: 0.0884625	total: 7.24s	remaining: 22.7s
242:	learn: 0.0883857	total: 7.27s	remaining: 22.6s
243:	learn: 0.0883627	total: 7.3s	remaining: 22.6s
244:	learn: 0.0881780	total: 7.33s	remaining: 22.6s
245:	learn: 0.0880748	total: 7.36s	remaining: 22.6s
246:	learn: 0.0879186	total: 7.39s	remaining: 22.5s
247:	learn: 0.0878415	total: 7.42s	remaining: 22.5s
248:	learn: 0.0877877	total: 7.45s	remaining: 22.5s
249:	learn: 0.0876840	total: 7.48s	remaining: 22.4s
250:	learn: 0.0876635	total: 7.51s	remaining: 22.4s
251:	learn: 0.0876465	total: 7.54s	remaining: 22.4s
252:	learn: 0.0874950	total: 7.57s	remaining: 22.3s
253:	learn: 0.0873374	total: 7.59s	remaining: 22.3s
254:	learn: 0.0871627	total: 7.62s	remaining: 22.3s
255:	learn: 0.0871146	total: 7.65s	remaining: 22.2s
256:	learn: 0.0870763	total: 7.68s	remaining: 22.2s
257:	learn: 0.0870187	total: 7.71s	remaining: 22.2s
258:	learn: 0.0867916	total: 7.74s	remaining: 22.2s
259:	learn: 0.0867393	total: 7.77s	remaining: 22.1s
260:	learn: 0.0865390	total: 7.8s	remaining: 22.1s
261:	learn: 0.0864739	total: 7.84s	remaining: 22.1s
262:	learn: 0.0863826	total: 7.87s	remaining: 22s
263:	learn: 0.0862743	total: 7.9s	remaining: 22s
264:	learn: 0.0861681	total: 7.93s	remaining: 22s
265:	learn: 0.0860536	total: 7.98s	remaining: 22s
266:	learn: 0.0857949	total: 8.01s	remaining: 22s
267:	learn: 0.0855690	total: 8.04s	remaining: 22s
268:	learn: 0.0853212	total: 8.07s	remaining: 21.9s
269:	learn: 0.0850411	total: 8.1s	remaining: 21.9s
270:	learn: 0.0848102	total: 8.13s	remaining: 21.9s
271:	learn: 0.0846684	total: 8.16s	remaining: 21.8s
272:	learn: 0.0845365	total: 8.18s	remaining: 21.8s
273:	learn: 0.0842879	total: 8.21s	remaining: 21.8s
274:	learn: 0.0841863	total: 8.25s	remaining: 21.7s
275:	learn: 0.0840658	total: 8.28s	remaining: 21.7s
276:	learn: 0.0839087	total: 8.31s	remaining: 21.7s
277:	learn: 0.0838492	total: 8.34s	remaining: 21.6s
278:	learn: 0.0838169	total: 8.37s	remaining: 21.6s
279:	learn: 0.0835768	total: 8.4s	remaining: 21.6s
280:	learn: 0.0834975	total: 8.44s	remaining: 21.6s
281:	learn: 0.0833534	total: 8.46s	remaining: 21.6s
282:	learn: 0.0833026	total: 8.5s	remaining: 21.5s
283:	learn: 0.0831503	total: 8.53s	remaining: 21.5s
284:	learn: 0.0829682	total: 8.56s	remaining: 21.5s
285:	learn: 0.0829452	total: 8.59s	remaining: 21.4s
286:	learn: 0.0829242	total: 8.62s	remaining: 21.4s
287:	learn: 0.0828881	total: 8.65s	remaining: 21.4s
288:	learn: 0.0828593	total: 8.68s	remaining: 21.4s
289:	learn: 0.0827271	total: 8.71s	remaining: 21.3s
290:	learn: 0.0826531	total: 8.74s	remaining: 21.3s
291:	learn: 0.0825180	total: 8.79s	remaining: 21.3s
292:	learn: 0.0824119	total: 8.82s	remaining: 21.3s
293:	learn: 0.0823757	total: 8.85s	remaining: 21.2s
294:	learn: 0.0822442	total: 8.88s	remaining: 21.2s
295:	learn: 0.0820588	total: 8.91s	remaining: 21.2s
296:	learn: 0.0820312	total: 8.94s	remaining: 21.2s
297:	learn: 0.0820109	total: 8.97s	remaining: 21.1s
298:	learn: 0.0819488	total: 9s	remaining: 21.1s
299:	learn: 0.0817237	total: 9.03s	remaining: 21.1s
300:	learn: 0.0815933	total: 9.05s	remaining: 21s
301:	learn: 0.0815598	total: 9.09s	remaining: 21s
302:	learn: 0.0814684	total: 9.12s	remaining: 21s
303:	learn: 0.0814306	total: 9.15s	remaining: 20.9s
304:	learn: 0.0813954	total: 9.18s	remaining: 20.9s
305:	learn: 0.0813601	total: 9.21s	remaining: 20.9s
306:	learn: 0.0813393	total: 9.24s	remaining: 20.8s
307:	learn: 0.0812519	total: 9.27s	remaining: 20.8s
308:	learn: 0.0811590	total: 9.29s	remaining: 20.8s
309:	learn: 0.0811292	total: 9.32s	remaining: 20.8s
310:	learn: 0.0810330	total: 9.36s	remaining: 20.7s
311:	learn: 0.0809727	total: 9.39s	remaining: 20.7s
312:	learn: 0.0809033	total: 9.42s	remaining: 20.7s
313:	learn: 0.0808809	total: 9.45s	remaining: 20.6s
314:	learn: 0.0808570	total: 9.48s	remaining: 20.6s
315:	learn: 0.0808253	total: 9.51s	remaining: 20.6s
316:	learn: 0.0808056	total: 9.54s	remaining: 20.6s
317:	learn: 0.0807754	total: 9.58s	remaining: 20.5s
318:	learn: 0.0807371	total: 9.61s	remaining: 20.5s
319:	learn: 0.0805239	total: 9.64s	remaining: 20.5s
320:	learn: 0.0804898	total: 9.67s	remaining: 20.4s
321:	learn: 0.0802644	total: 9.7s	remaining: 20.4s
322:	learn: 0.0800799	total: 9.73s	remaining: 20.4s
323:	learn: 0.0800260	total: 9.76s	remaining: 20.4s
324:	learn: 0.0799725	total: 9.79s	remaining: 20.3s
325:	learn: 0.0799635	total: 9.84s	remaining: 20.3s
326:	learn: 0.0798777	total: 9.87s	remaining: 20.3s
327:	learn: 0.0798262	total: 9.9s	remaining: 20.3s
328:	learn: 0.0798116	total: 9.93s	remaining: 20.3s
329:	learn: 0.0797879	total: 9.96s	remaining: 20.2s
330:	learn: 0.0797730	total: 9.99s	remaining: 20.2s
331:	learn: 0.0796685	total: 10s	remaining: 20.2s
332:	learn: 0.0796498	total: 10.1s	remaining: 20.1s
333:	learn: 0.0794947	total: 10.1s	remaining: 20.1s
334:	learn: 0.0794707	total: 10.1s	remaining: 20.1s
335:	learn: 0.0793585	total: 10.1s	remaining: 20.1s
336:	learn: 0.0793167	total: 10.2s	remaining: 20s
337:	learn: 0.0792008	total: 10.2s	remaining: 20s
338:	learn: 0.0791840	total: 10.2s	remaining: 20s
339:	learn: 0.0790844	total: 10.3s	remaining: 19.9s
340:	learn: 0.0790291	total: 10.3s	remaining: 19.9s
341:	learn: 0.0789703	total: 10.3s	remaining: 19.9s
342:	learn: 0.0788675	total: 10.4s	remaining: 19.9s
343:	learn: 0.0788457	total: 10.4s	remaining: 19.8s
344:	learn: 0.0787681	total: 10.4s	remaining: 19.8s
345:	learn: 0.0786262	total: 10.5s	remaining: 19.8s
346:	learn: 0.0786202	total: 10.5s	remaining: 19.7s
347:	learn: 0.0786038	total: 10.5s	remaining: 19.7s
348:	learn: 0.0785167	total: 10.6s	remaining: 19.7s
349:	learn: 0.0784279	total: 10.6s	remaining: 19.7s
350:	learn: 0.0784109	total: 10.6s	remaining: 19.6s
351:	learn: 0.0783007	total: 10.7s	remaining: 19.6s
352:	learn: 0.0782267	total: 10.7s	remaining: 19.6s
353:	learn: 0.0782079	total: 10.7s	remaining: 19.5s
354:	learn: 0.0781979	total: 10.7s	remaining: 19.5s
355:	learn: 0.0781091	total: 10.8s	remaining: 19.5s
356:	learn: 0.0780931	total: 10.8s	remaining: 19.5s
357:	learn: 0.0779910	total: 10.8s	remaining: 19.4s
358:	learn: 0.0779810	total: 10.9s	remaining: 19.4s
359:	learn: 0.0779371	total: 10.9s	remaining: 19.4s
360:	learn: 0.0778955	total: 10.9s	remaining: 19.3s
361:	learn: 0.0778447	total: 11s	remaining: 19.3s
362:	learn: 0.0776789	total: 11s	remaining: 19.3s
363:	learn: 0.0776063	total: 11s	remaining: 19.2s
364:	learn: 0.0775495	total: 11s	remaining: 19.2s
365:	learn: 0.0774527	total: 11.1s	remaining: 19.2s
366:	learn: 0.0774352	total: 11.1s	remaining: 19.2s
367:	learn: 0.0773367	total: 11.2s	remaining: 19.2s
368:	learn: 0.0773242	total: 11.2s	remaining: 19.1s
369:	learn: 0.0771830	total: 11.2s	remaining: 19.1s
370:	learn: 0.0770723	total: 11.2s	remaining: 19.1s
371:	learn: 0.0770652	total: 11.3s	remaining: 19s
372:	learn: 0.0769201	total: 11.3s	remaining: 19s
373:	learn: 0.0768788	total: 11.3s	remaining: 19s
374:	learn: 0.0767714	total: 11.4s	remaining: 18.9s
375:	learn: 0.0767639	total: 11.4s	remaining: 18.9s
376:	learn: 0.0766895	total: 11.4s	remaining: 18.9s
377:	learn: 0.0766608	total: 11.5s	remaining: 18.9s
378:	learn: 0.0765302	total: 11.5s	remaining: 18.8s
379:	learn: 0.0764923	total: 11.5s	remaining: 18.8s
380:	learn: 0.0764178	total: 11.6s	remaining: 18.8s
381:	learn: 0.0763330	total: 11.6s	remaining: 18.8s
382:	learn: 0.0762008	total: 11.6s	remaining: 18.7s
383:	learn: 0.0761355	total: 11.7s	remaining: 18.7s
384:	learn: 0.0761113	total: 11.7s	remaining: 18.7s
385:	learn: 0.0759448	total: 11.7s	remaining: 18.6s
386:	learn: 0.0758674	total: 11.7s	remaining: 18.6s

CV folds:  82%|████████▏ | 41/50 [21:35<04:41, 31.33s/fold]

Learning rate set to 0.042738
0:	learn: 0.3866637	total: 24.1ms	remaining: 24s
1:	learn: 0.3759113	total: 53.2ms	remaining: 26.6s
2:	learn: 0.3651205	total: 81.3ms	remaining: 27s
3:	learn: 0.3557061	total: 109ms	remaining: 27.2s
4:	learn: 0.3465123	total: 142ms	remaining: 28.3s
5:	learn: 0.3367184	total: 170ms	remaining: 28.1s
6:	learn: 0.3276413	total: 199ms	remaining: 28.3s
7:	learn: 0.3196691	total: 235ms	remaining: 29.1s
8:	learn: 0.3121872	total: 272ms	remaining: 29.9s
9:	learn: 0.3041520	total: 302ms	remaining: 29.9s
10:	learn: 0.2966067	total: 333ms	remaining: 30s
11:	learn: 0.2897914	total: 364ms	remaining: 30s
12:	learn: 0.2833903	total: 393ms	remaining: 29.8s
13:	learn: 0.2768943	total: 420ms	remaining: 29.6s
14:	learn: 0.2701806	total: 448ms	remaining: 29.4s
15:	learn: 0.2637886	total: 481ms	remaining: 29.6s
16:	learn: 0.2584297	total: 512ms	remaining: 29.6s
17:	learn: 0.2527993	total: 547ms	remaining: 29.8s
18:	learn: 0.2474263	total: 577ms	remaining: 29.8s
19:	learn: 0.2422271	total: 605ms	remaining: 29.7s
20:	learn: 0.2369735	total: 634ms	remaining: 29.5s
21:	learn: 0.2323881	total: 665ms	remaining: 29.5s
22:	learn: 0.2282220	total: 694ms	remaining: 29.5s
23:	learn: 0.2239023	total: 724ms	remaining: 29.4s
24:	learn: 0.2196850	total: 754ms	remaining: 29.4s
25:	learn: 0.2156017	total: 784ms	remaining: 29.4s
26:	learn: 0.2118285	total: 829ms	remaining: 29.9s
27:	learn: 0.2077662	total: 863ms	remaining: 30s
28:	learn: 0.2043566	total: 896ms	remaining: 30s
29:	learn: 0.2007936	total: 927ms	remaining: 30s
30:	learn: 0.1973339	total: 958ms	remaining: 29.9s
31:	learn: 0.1941540	total: 995ms	remaining: 30.1s
32:	learn: 0.1907875	total: 1.03s	remaining: 30.1s
33:	learn: 0.1880620	total: 1.06s	remaining: 30s
34:	learn: 0.1850256	total: 1.08s	remaining: 29.9s
35:	learn: 0.1820077	total: 1.11s	remaining: 29.8s
36:	learn: 0.1792810	total: 1.14s	remaining: 29.8s
37:	learn: 0.1765362	total: 1.17s	remaining: 29.7s
38:	learn: 0.1739285	total: 1.2s	remaining: 29.6s
39:	learn: 0.1715866	total: 1.23s	remaining: 29.5s
40:	learn: 0.1692399	total: 1.26s	remaining: 29.4s
41:	learn: 0.1671303	total: 1.29s	remaining: 29.4s
42:	learn: 0.1652568	total: 1.32s	remaining: 29.3s
43:	learn: 0.1631900	total: 1.34s	remaining: 29.2s
44:	learn: 0.1612031	total: 1.38s	remaining: 29.2s
45:	learn: 0.1596395	total: 1.41s	remaining: 29.2s
46:	learn: 0.1577378	total: 1.43s	remaining: 29.1s
47:	learn: 0.1557598	total: 1.46s	remaining: 29s
48:	learn: 0.1539594	total: 1.49s	remaining: 28.9s
49:	learn: 0.1522807	total: 1.52s	remaining: 28.9s
50:	learn: 0.1507367	total: 1.56s	remaining: 29s
51:	learn: 0.1493860	total: 1.59s	remaining: 28.9s
52:	learn: 0.1477572	total: 1.61s	remaining: 28.9s
53:	learn: 0.1462232	total: 1.64s	remaining: 28.8s
54:	learn: 0.1448450	total: 1.67s	remaining: 28.8s
55:	learn: 0.1436805	total: 1.7s	remaining: 28.7s
56:	learn: 0.1424301	total: 1.73s	remaining: 28.7s
57:	learn: 0.1410794	total: 1.77s	remaining: 28.7s
58:	learn: 0.1396573	total: 1.79s	remaining: 28.6s
59:	learn: 0.1384199	total: 1.82s	remaining: 28.6s
60:	learn: 0.1372752	total: 1.85s	remaining: 28.6s
61:	learn: 0.1363162	total: 1.88s	remaining: 28.5s
62:	learn: 0.1353305	total: 1.91s	remaining: 28.5s
63:	learn: 0.1342752	total: 1.94s	remaining: 28.4s
64:	learn: 0.1333502	total: 1.97s	remaining: 28.4s
65:	learn: 0.1324367	total: 2s	remaining: 28.3s
66:	learn: 0.1314453	total: 2.03s	remaining: 28.3s
67:	learn: 0.1306795	total: 2.06s	remaining: 28.2s
68:	learn: 0.1296918	total: 2.09s	remaining: 28.2s
69:	learn: 0.1288496	total: 2.12s	remaining: 28.1s
70:	learn: 0.1280213	total: 2.15s	remaining: 28.1s
71:	learn: 0.1272302	total: 2.18s	remaining: 28.1s
72:	learn: 0.1263796	total: 2.21s	remaining: 28s
73:	learn: 0.1256966	total: 2.24s	remaining: 28s
74:	learn: 0.1250657	total: 2.27s	remaining: 28s
75:	learn: 0.1242515	total: 2.3s	remaining: 28s
76:	learn: 0.1236157	total: 2.33s	remaining: 28s
77:	learn: 0.1228652	total: 2.36s	remaining: 27.9s
78:	learn: 0.1222702	total: 2.39s	remaining: 27.9s
79:	learn: 0.1216692	total: 2.42s	remaining: 27.9s
80:	learn: 0.1211278	total: 2.45s	remaining: 27.8s
81:	learn: 0.1205865	total: 2.48s	remaining: 27.8s
82:	learn: 0.1200235	total: 2.51s	remaining: 27.7s
83:	learn: 0.1193161	total: 2.54s	remaining: 27.7s
84:	learn: 0.1185062	total: 2.57s	remaining: 27.7s
85:	learn: 0.1181338	total: 2.6s	remaining: 27.7s
86:	learn: 0.1176342	total: 2.63s	remaining: 27.6s
87:	learn: 0.1172557	total: 2.66s	remaining: 27.6s
88:	learn: 0.1167792	total: 2.69s	remaining: 27.5s
89:	learn: 0.1162814	total: 2.72s	remaining: 27.5s
90:	learn: 0.1157948	total: 2.75s	remaining: 27.5s
91:	learn: 0.1153139	total: 2.78s	remaining: 27.4s
92:	learn: 0.1146924	total: 2.81s	remaining: 27.4s
93:	learn: 0.1143000	total: 2.84s	remaining: 27.4s
94:	learn: 0.1139125	total: 2.87s	remaining: 27.4s
95:	learn: 0.1133826	total: 2.92s	remaining: 27.5s
96:	learn: 0.1129747	total: 2.95s	remaining: 27.5s
97:	learn: 0.1124562	total: 2.98s	remaining: 27.4s
98:	learn: 0.1121236	total: 3.01s	remaining: 27.4s
99:	learn: 0.1117707	total: 3.04s	remaining: 27.3s
100:	learn: 0.1114749	total: 3.07s	remaining: 27.3s
101:	learn: 0.1110293	total: 3.1s	remaining: 27.3s
102:	learn: 0.1105722	total: 3.14s	remaining: 27.3s
103:	learn: 0.1102110	total: 3.17s	remaining: 27.4s
104:	learn: 0.1099925	total: 3.21s	remaining: 27.3s
105:	learn: 0.1096615	total: 3.24s	remaining: 27.3s
106:	learn: 0.1092451	total: 3.27s	remaining: 27.3s
107:	learn: 0.1089925	total: 3.3s	remaining: 27.3s
108:	learn: 0.1087829	total: 3.33s	remaining: 27.2s
109:	learn: 0.1084945	total: 3.36s	remaining: 27.2s
110:	learn: 0.1080144	total: 3.39s	remaining: 27.2s
111:	learn: 0.1075685	total: 3.44s	remaining: 27.3s
112:	learn: 0.1072766	total: 3.47s	remaining: 27.2s
113:	learn: 0.1068464	total: 3.49s	remaining: 27.2s
114:	learn: 0.1066080	total: 3.52s	remaining: 27.1s
115:	learn: 0.1062504	total: 3.55s	remaining: 27.1s
116:	learn: 0.1061258	total: 3.57s	remaining: 26.9s
117:	learn: 0.1059145	total: 3.6s	remaining: 26.9s
118:	learn: 0.1056524	total: 3.62s	remaining: 26.8s
119:	learn: 0.1054201	total: 3.66s	remaining: 26.8s
120:	learn: 0.1050504	total: 3.69s	remaining: 26.8s
121:	learn: 0.1048533	total: 3.74s	remaining: 26.9s
122:	learn: 0.1044822	total: 3.78s	remaining: 27s
123:	learn: 0.1041356	total: 3.81s	remaining: 26.9s
124:	learn: 0.1037961	total: 3.84s	remaining: 26.9s
125:	learn: 0.1035267	total: 3.87s	remaining: 26.8s
126:	learn: 0.1033013	total: 3.9s	remaining: 26.8s
127:	learn: 0.1030028	total: 3.93s	remaining: 26.7s
128:	learn: 0.1027292	total: 3.96s	remaining: 26.7s
129:	learn: 0.1024173	total: 3.98s	remaining: 26.7s
130:	learn: 0.1022675	total: 4.02s	remaining: 26.6s
131:	learn: 0.1020358	total: 4.04s	remaining: 26.6s
132:	learn: 0.1018028	total: 4.07s	remaining: 26.6s
133:	learn: 0.1015758	total: 4.1s	remaining: 26.5s
134:	learn: 0.1013327	total: 4.13s	remaining: 26.5s
135:	learn: 0.1011152	total: 4.16s	remaining: 26.5s
136:	learn: 0.1008398	total: 4.2s	remaining: 26.4s
137:	learn: 0.1006481	total: 4.22s	remaining: 26.4s
138:	learn: 0.1003274	total: 4.26s	remaining: 26.4s
139:	learn: 0.1001259	total: 4.29s	remaining: 26.3s
140:	learn: 0.0999758	total: 4.3s	remaining: 26.2s
141:	learn: 0.0996711	total: 4.33s	remaining: 26.2s
142:	learn: 0.0994709	total: 4.37s	remaining: 26.2s
143:	learn: 0.0993324	total: 4.4s	remaining: 26.1s
144:	learn: 0.0991568	total: 4.43s	remaining: 26.1s
145:	learn: 0.0989321	total: 4.46s	remaining: 26.1s
146:	learn: 0.0987277	total: 4.49s	remaining: 26.1s
147:	learn: 0.0985823	total: 4.52s	remaining: 26s
148:	learn: 0.0983998	total: 4.56s	remaining: 26s
149:	learn: 0.0981204	total: 4.58s	remaining: 26s
150:	learn: 0.0979567	total: 4.62s	remaining: 26s
151:	learn: 0.0977725	total: 4.65s	remaining: 25.9s
152:	learn: 0.0974968	total: 4.68s	remaining: 25.9s
153:	learn: 0.0973200	total: 4.71s	remaining: 25.9s
154:	learn: 0.0970701	total: 4.75s	remaining: 25.9s
155:	learn: 0.0968009	total: 4.78s	remaining: 25.9s
156:	learn: 0.0965969	total: 4.81s	remaining: 25.8s
157:	learn: 0.0963265	total: 4.83s	remaining: 25.8s
158:	learn: 0.0962023	total: 4.87s	remaining: 25.7s
159:	learn: 0.0961173	total: 4.89s	remaining: 25.7s
160:	learn: 0.0959469	total: 4.92s	remaining: 25.7s
161:	learn: 0.0957912	total: 4.95s	remaining: 25.6s
162:	learn: 0.0956394	total: 4.99s	remaining: 25.6s
163:	learn: 0.0954489	total: 5.01s	remaining: 25.6s
164:	learn: 0.0952873	total: 5.04s	remaining: 25.5s
165:	learn: 0.0951998	total: 5.08s	remaining: 25.5s
166:	learn: 0.0950571	total: 5.11s	remaining: 25.5s
167:	learn: 0.0948500	total: 5.13s	remaining: 25.4s
168:	learn: 0.0947410	total: 5.16s	remaining: 25.4s
169:	learn: 0.0945959	total: 5.2s	remaining: 25.4s
170:	learn: 0.0945202	total: 5.23s	remaining: 25.3s
171:	learn: 0.0943783	total: 5.26s	remaining: 25.3s
172:	learn: 0.0941921	total: 5.3s	remaining: 25.4s
173:	learn: 0.0939786	total: 5.34s	remaining: 25.4s
174:	learn: 0.0938281	total: 5.37s	remaining: 25.3s
175:	learn: 0.0937184	total: 5.41s	remaining: 25.3s
176:	learn: 0.0934775	total: 5.44s	remaining: 25.3s
177:	learn: 0.0932962	total: 5.47s	remaining: 25.3s
178:	learn: 0.0930974	total: 5.5s	remaining: 25.2s
179:	learn: 0.0929133	total: 5.53s	remaining: 25.2s
180:	learn: 0.0927089	total: 5.56s	remaining: 25.2s
181:	learn: 0.0926313	total: 5.6s	remaining: 25.2s
182:	learn: 0.0924349	total: 5.63s	remaining: 25.1s
183:	learn: 0.0922826	total: 5.66s	remaining: 25.1s
184:	learn: 0.0920898	total: 5.69s	remaining: 25.1s
185:	learn: 0.0919184	total: 5.72s	remaining: 25s
186:	learn: 0.0917771	total: 5.75s	remaining: 25s
187:	learn: 0.0916091	total: 5.78s	remaining: 25s
188:	learn: 0.0915022	total: 5.81s	remaining: 24.9s
189:	learn: 0.0913597	total: 5.84s	remaining: 24.9s
190:	learn: 0.0912738	total: 5.87s	remaining: 24.9s
191:	learn: 0.0910693	total: 5.9s	remaining: 24.8s
192:	learn: 0.0909432	total: 5.93s	remaining: 24.8s
193:	learn: 0.0908515	total: 5.96s	remaining: 24.8s
194:	learn: 0.0906045	total: 6s	remaining: 24.8s
195:	learn: 0.0904557	total: 6.03s	remaining: 24.7s
196:	learn: 0.0903938	total: 6.06s	remaining: 24.7s
197:	learn: 0.0902477	total: 6.09s	remaining: 24.7s
198:	learn: 0.0901563	total: 6.12s	remaining: 24.6s
199:	learn: 0.0899988	total: 6.15s	remaining: 24.6s
200:	learn: 0.0898568	total: 6.18s	remaining: 24.6s
201:	learn: 0.0896929	total: 6.21s	remaining: 24.5s
202:	learn: 0.0895451	total: 6.24s	remaining: 24.5s
203:	learn: 0.0893805	total: 6.27s	remaining: 24.5s
204:	learn: 0.0892382	total: 6.3s	remaining: 24.4s
205:	learn: 0.0891794	total: 6.33s	remaining: 24.4s
206:	learn: 0.0890430	total: 6.36s	remaining: 24.4s
207:	learn: 0.0888139	total: 6.39s	remaining: 24.3s
208:	learn: 0.0886137	total: 6.42s	remaining: 24.3s
209:	learn: 0.0884507	total: 6.45s	remaining: 24.3s
210:	learn: 0.0882848	total: 6.48s	remaining: 24.2s
211:	learn: 0.0881951	total: 6.51s	remaining: 24.2s
212:	learn: 0.0881073	total: 6.55s	remaining: 24.2s
213:	learn: 0.0879402	total: 6.59s	remaining: 24.2s
214:	learn: 0.0878280	total: 6.62s	remaining: 24.2s
215:	learn: 0.0877346	total: 6.65s	remaining: 24.1s
216:	learn: 0.0876519	total: 6.68s	remaining: 24.1s
217:	learn: 0.0875018	total: 6.71s	remaining: 24.1s
218:	learn: 0.0874378	total: 6.74s	remaining: 24s
219:	learn: 0.0873517	total: 6.77s	remaining: 24s
220:	learn: 0.0872648	total: 6.8s	remaining: 24s
221:	learn: 0.0871514	total: 6.83s	remaining: 23.9s
222:	learn: 0.0870946	total: 6.87s	remaining: 23.9s
223:	learn: 0.0870052	total: 6.9s	remaining: 23.9s
224:	learn: 0.0869521	total: 6.93s	remaining: 23.9s
225:	learn: 0.0868548	total: 6.96s	remaining: 23.8s
226:	learn: 0.0867552	total: 6.99s	remaining: 23.8s
227:	learn: 0.0866393	total: 7.02s	remaining: 23.8s
228:	learn: 0.0864920	total: 7.05s	remaining: 23.8s
229:	learn: 0.0864160	total: 7.09s	remaining: 23.7s
230:	learn: 0.0863698	total: 7.12s	remaining: 23.7s
231:	learn: 0.0861633	total: 7.15s	remaining: 23.7s
232:	learn: 0.0860102	total: 7.18s	remaining: 23.6s
233:	learn: 0.0859846	total: 7.22s	remaining: 23.6s
234:	learn: 0.0859416	total: 7.25s	remaining: 23.6s
235:	learn: 0.0858969	total: 7.28s	remaining: 23.6s
236:	learn: 0.0858578	total: 7.31s	remaining: 23.5s
237:	learn: 0.0857920	total: 7.35s	remaining: 23.5s
238:	learn: 0.0857690	total: 7.38s	remaining: 23.5s
239:	learn: 0.0856733	total: 7.41s	remaining: 23.5s
240:	learn: 0.0856037	total: 7.44s	remaining: 23.4s
241:	learn: 0.0854752	total: 7.5s	remaining: 23.5s
242:	learn: 0.0853032	total: 7.53s	remaining: 23.4s
243:	learn: 0.0852442	total: 7.55s	remaining: 23.4s
244:	learn: 0.0850609	total: 7.58s	remaining: 23.4s
245:	learn: 0.0849907	total: 7.61s	remaining: 23.3s
246:	learn: 0.0849332	total: 7.64s	remaining: 23.3s
247:	learn: 0.0847864	total: 7.67s	remaining: 23.3s
248:	learn: 0.0847676	total: 7.71s	remaining: 23.2s
249:	learn: 0.0845369	total: 7.74s	remaining: 23.2s
250:	learn: 0.0845303	total: 7.77s	remaining: 23.2s
251:	learn: 0.0844740	total: 7.79s	remaining: 23.1s
252:	learn: 0.0844308	total: 7.83s	remaining: 23.1s
253:	learn: 0.0842242	total: 7.85s	remaining: 23.1s
254:	learn: 0.0842173	total: 7.88s	remaining: 23s
255:	learn: 0.0840725	total: 7.92s	remaining: 23s
256:	learn: 0.0840666	total: 7.95s	remaining: 23s
257:	learn: 0.0840396	total: 7.98s	remaining: 22.9s
258:	learn: 0.0838956	total: 8.01s	remaining: 22.9s
259:	learn: 0.0837474	total: 8.04s	remaining: 22.9s
260:	learn: 0.0837293	total: 8.07s	remaining: 22.8s
261:	learn: 0.0836528	total: 8.1s	remaining: 22.8s
262:	learn: 0.0835955	total: 8.13s	remaining: 22.8s
263:	learn: 0.0835811	total: 8.16s	remaining: 22.8s
264:	learn: 0.0833902	total: 8.19s	remaining: 22.7s
265:	learn: 0.0833730	total: 8.22s	remaining: 22.7s
266:	learn: 0.0833670	total: 8.25s	remaining: 22.7s
267:	learn: 0.0832881	total: 8.28s	remaining: 22.6s
268:	learn: 0.0831249	total: 8.31s	remaining: 22.6s
269:	learn: 0.0829560	total: 8.34s	remaining: 22.6s
270:	learn: 0.0829502	total: 8.37s	remaining: 22.5s
271:	learn: 0.0829287	total: 8.41s	remaining: 22.5s
272:	learn: 0.0829171	total: 8.44s	remaining: 22.5s
273:	learn: 0.0829123	total: 8.47s	remaining: 22.4s
274:	learn: 0.0828767	total: 8.5s	remaining: 22.4s
275:	learn: 0.0828715	total: 8.54s	remaining: 22.4s
276:	learn: 0.0828664	total: 8.57s	remaining: 22.4s
277:	learn: 0.0828591	total: 8.6s	remaining: 22.3s
278:	learn: 0.0828551	total: 8.63s	remaining: 22.3s
279:	learn: 0.0826920	total: 8.66s	remaining: 22.3s
280:	learn: 0.0825093	total: 8.69s	remaining: 22.2s
281:	learn: 0.0823632	total: 8.72s	remaining: 22.2s
282:	learn: 0.0821977	total: 8.76s	remaining: 22.2s
283:	learn: 0.0820556	total: 8.79s	remaining: 22.2s
284:	learn: 0.0820500	total: 8.82s	remaining: 22.1s
285:	learn: 0.0819556	total: 8.85s	remaining: 22.1s
286:	learn: 0.0818248	total: 8.88s	remaining: 22.1s
287:	learn: 0.0815871	total: 8.91s	remaining: 22s
288:	learn: 0.0815548	total: 8.94s	remaining: 22s
289:	learn: 0.0815372	total: 8.97s	remaining: 22s
290:	learn: 0.0813453	total: 9s	remaining: 21.9s
291:	learn: 0.0812539	total: 9.04s	remaining: 21.9s
292:	learn: 0.0810922	total: 9.07s	remaining: 21.9s
293:	learn: 0.0810050	total: 9.1s	remaining: 21.8s
294:	learn: 0.0809221	total: 9.13s	remaining: 21.8s
295:	learn: 0.0807130	total: 9.15s	remaining: 21.8s
296:	learn: 0.0806994	total: 9.18s	remaining: 21.7s
297:	learn: 0.0806138	total: 9.21s	remaining: 21.7s
298:	learn: 0.0805008	total: 9.24s	remaining: 21.7s
299:	learn: 0.0804807	total: 9.28s	remaining: 21.6s
300:	learn: 0.0804708	total: 9.3s	remaining: 21.6s
301:	learn: 0.0803140	total: 9.34s	remaining: 21.6s
302:	learn: 0.0802738	total: 9.37s	remaining: 21.5s
303:	learn: 0.0801536	total: 9.4s	remaining: 21.5s
304:	learn: 0.0801051	total: 9.42s	remaining: 21.5s
305:	learn: 0.0800987	total: 9.46s	remaining: 21.4s
306:	learn: 0.0799327	total: 9.49s	remaining: 21.4s
307:	learn: 0.0798556	total: 9.52s	remaining: 21.4s
308:	learn: 0.0798214	total: 9.55s	remaining: 21.4s
309:	learn: 0.0797299	total: 9.57s	remaining: 21.3s
310:	learn: 0.0796536	total: 9.6s	remaining: 21.3s
311:	learn: 0.0795831	total: 9.65s	remaining: 21.3s
312:	learn: 0.0794700	total: 9.68s	remaining: 21.2s
313:	learn: 0.0793241	total: 9.71s	remaining: 21.2s
314:	learn: 0.0793104	total: 9.74s	remaining: 21.2s
315:	learn: 0.0791626	total: 9.77s	remaining: 21.2s
316:	learn: 0.0791471	total: 9.81s	remaining: 21.1s
317:	learn: 0.0790408	total: 9.84s	remaining: 21.1s
318:	learn: 0.0790348	total: 9.87s	remaining: 21.1s
319:	learn: 0.0789859	total: 9.9s	remaining: 21s
320:	learn: 0.0789437	total: 9.93s	remaining: 21s
321:	learn: 0.0788804	total: 9.96s	remaining: 21s
322:	learn: 0.0788653	total: 9.99s	remaining: 20.9s
323:	learn: 0.0788595	total: 10s	remaining: 20.9s
324:	learn: 0.0788045	total: 10.1s	remaining: 20.9s
325:	learn: 0.0787164	total: 10.1s	remaining: 20.9s
326:	learn: 0.0785896	total: 10.1s	remaining: 20.9s
327:	learn: 0.0785838	total: 10.2s	remaining: 20.8s
328:	learn: 0.0785708	total: 10.2s	remaining: 20.8s
329:	learn: 0.0785693	total: 10.2s	remaining: 20.8s
330:	learn: 0.0784330	total: 10.3s	remaining: 20.7s
331:	learn: 0.0784276	total: 10.3s	remaining: 20.7s
332:	learn: 0.0783855	total: 10.3s	remaining: 20.7s
333:	learn: 0.0782691	total: 10.4s	remaining: 20.6s
334:	learn: 0.0782228	total: 10.4s	remaining: 20.6s
335:	learn: 0.0782144	total: 10.4s	remaining: 20.6s
336:	learn: 0.0781690	total: 10.4s	remaining: 20.5s
337:	learn: 0.0780752	total: 10.5s	remaining: 20.5s
338:	learn: 0.0780679	total: 10.5s	remaining: 20.5s
339:	learn: 0.0780041	total: 10.5s	remaining: 20.5s
340:	learn: 0.0777996	total: 10.6s	remaining: 20.5s
341:	learn: 0.0777643	total: 10.6s	remaining: 20.4s
342:	learn: 0.0777195	total: 10.6s	remaining: 20.4s
343:	learn: 0.0776051	total: 10.7s	remaining: 20.4s
344:	learn: 0.0775083	total: 10.7s	remaining: 20.3s
345:	learn: 0.0774098	total: 10.7s	remaining: 20.3s
346:	learn: 0.0773981	total: 10.8s	remaining: 20.3s
347:	learn: 0.0773328	total: 10.8s	remaining: 20.2s
348:	learn: 0.0771742	total: 10.8s	remaining: 20.2s
349:	learn: 0.0771176	total: 10.9s	remaining: 20.2s
350:	learn: 0.0769950	total: 10.9s	remaining: 20.2s
351:	learn: 0.0768864	total: 10.9s	remaining: 20.1s
352:	learn: 0.0768511	total: 11s	remaining: 20.1s
353:	learn: 0.0766590	total: 11s	remaining: 20s
354:	learn: 0.0766019	total: 11s	remaining: 20s
355:	learn: 0.0765925	total: 11s	remaining: 20s
356:	learn: 0.0765867	total: 11.1s	remaining: 20s
357:	learn: 0.0763927	total: 11.1s	remaining: 19.9s
358:	learn: 0.0762507	total: 11.1s	remaining: 19.9s
359:	learn: 0.0761264	total: 11.2s	remaining: 19.9s
360:	learn: 0.0761152	total: 11.2s	remaining: 19.8s
361:	learn: 0.0760248	total: 11.2s	remaining: 19.8s
362:	learn: 0.0759235	total: 11.3s	remaining: 19.8s
363:	learn: 0.0757905	total: 11.3s	remaining: 19.7s
364:	learn: 0.0757647	total: 11.3s	remaining: 19.7s
365:	learn: 0.0757556	total: 11.4s	remaining: 19.7s
366:	learn: 0.0756844	total: 11.4s	remaining: 19.6s
367:	learn: 0.0756192	total: 11.4s	remaining: 19.6s
368:	learn: 0.0755681	total: 11.4s	remaining: 19.6s
369:	learn: 0.0754879	total: 11.5s	remaining: 19.5s
370:	learn: 0.0753614	total: 11.5s	remaining: 19.5s
371:	learn: 0.0752928	total: 11.5s	remaining: 19.5s
372:	learn: 0.0751277	total: 11.6s	remaining: 19.4s
373:	learn: 0.0750657	total: 11.6s	remaining: 19.5s
374:	learn: 0.0749525	total: 11.7s	remaining: 19.4s
375:	learn: 0.0749067	total: 11.7s	remaining: 19.4s
376:	learn: 0.0747167	total: 11.7s	remaining: 19.4s
377:	learn: 0.0746991	total: 11.7s	remaining: 19.3s
378:	learn: 0.0745259	total: 11.8s	remaining: 19.3s
379:	learn: 0.0743696	total: 11.8s	remaining: 19.3s
380:	learn: 0.0741735	total: 11.9s	remaining: 19.3s
381:	learn: 0.0741540	total: 11.9s	remaining: 19.2s
382:	learn: 0.0740920	total: 11.9s	remaining: 19.2s
383:	learn: 0.0739350	total: 11.9s	remaining: 19.2s
384:	learn: 0.0738209	total: 12s	remaining: 19.1s
385:	learn: 0.0736964	total: 12s	remaining: 19.1s
386:	learn: 0.0734846	total: 12s	remaining: 19.1s
387:	learn: 0.0734772	total: 12.1s	remaining: 19s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'MiscFeature': 1 unseen categories converted to Unseen on transform.

CV folds:  84%|████████▍ | 42/50 [22:07<04:11, 31.49s/fold]

999:	learn: 0.0420899	total: 31.4s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3868826	total: 24.6ms	remaining: 24.6s
1:	learn: 0.3763047	total: 57.7ms	remaining: 28.8s
2:	learn: 0.3652752	total: 91.2ms	remaining: 30.3s
3:	learn: 0.3551211	total: 122ms	remaining: 30.4s
4:	learn: 0.3456923	total: 153ms	remaining: 30.4s
5:	learn: 0.3368222	total: 183ms	remaining: 30.4s
6:	learn: 0.3276688	total: 216ms	remaining: 30.6s
7:	learn: 0.3195933	total: 246ms	remaining: 30.5s
8:	learn: 0.3110314	total: 279ms	remaining: 30.7s
9:	learn: 0.3035153	total: 312ms	remaining: 30.9s
10:	learn: 0.2955761	total: 340ms	remaining: 30.6s
11:	learn: 0.2888145	total: 369ms	remaining: 30.4s
12:	learn: 0.2818432	total: 400ms	remaining: 30.4s
13:	learn: 0.2750406	total: 433ms	remaining: 30.5s
14:	learn: 0.2687908	total: 463ms	remaining: 30.4s
15:	learn: 0.2624400	total: 493ms	remaining: 30.3s
16:	learn: 0.2566213	total: 525ms	remaining: 30.4s
17:	learn: 0.2511170	total: 557ms	remaining: 30.4s
18:	learn: 0.2456631	total: 588ms	remaining: 30.4s
19:	learn: 0.2404390	total: 618ms	remaining: 30.3s
20:	learn: 0.2352507	total: 650ms	remaining: 30.3s
21:	learn: 0.2304265	total: 682ms	remaining: 30.3s
22:	learn: 0.2258455	total: 717ms	remaining: 30.5s
23:	learn: 0.2217344	total: 750ms	remaining: 30.5s
24:	learn: 0.2175733	total: 783ms	remaining: 30.6s
25:	learn: 0.2133365	total: 813ms	remaining: 30.5s
26:	learn: 0.2093975	total: 843ms	remaining: 30.4s
27:	learn: 0.2058392	total: 872ms	remaining: 30.3s
28:	learn: 0.2020064	total: 903ms	remaining: 30.2s
29:	learn: 0.1981788	total: 933ms	remaining: 30.2s
30:	learn: 0.1949027	total: 964ms	remaining: 30.1s
31:	learn: 0.1915563	total: 993ms	remaining: 30s
32:	learn: 0.1886265	total: 1.02s	remaining: 30s
33:	learn: 0.1861149	total: 1.05s	remaining: 29.9s
34:	learn: 0.1832316	total: 1.08s	remaining: 29.8s
35:	learn: 0.1803900	total: 1.11s	remaining: 29.8s
36:	learn: 0.1777412	total: 1.14s	remaining: 29.8s
37:	learn: 0.1750272	total: 1.17s	remaining: 29.7s
38:	learn: 0.1727707	total: 1.2s	remaining: 29.6s
39:	learn: 0.1705270	total: 1.23s	remaining: 29.6s
40:	learn: 0.1686628	total: 1.26s	remaining: 29.5s
41:	learn: 0.1665473	total: 1.29s	remaining: 29.4s
42:	learn: 0.1643570	total: 1.32s	remaining: 29.3s
43:	learn: 0.1623603	total: 1.35s	remaining: 29.3s
44:	learn: 0.1606816	total: 1.38s	remaining: 29.2s
45:	learn: 0.1589794	total: 1.42s	remaining: 29.5s
46:	learn: 0.1573438	total: 1.45s	remaining: 29.5s
47:	learn: 0.1558078	total: 1.48s	remaining: 29.4s
48:	learn: 0.1540959	total: 1.51s	remaining: 29.4s
49:	learn: 0.1521799	total: 1.54s	remaining: 29.3s
50:	learn: 0.1507477	total: 1.58s	remaining: 29.4s
51:	learn: 0.1491650	total: 1.61s	remaining: 29.4s
52:	learn: 0.1477390	total: 1.64s	remaining: 29.3s
53:	learn: 0.1462949	total: 1.7s	remaining: 29.7s
54:	learn: 0.1450755	total: 1.73s	remaining: 29.6s
55:	learn: 0.1437110	total: 1.75s	remaining: 29.5s
56:	learn: 0.1424097	total: 1.78s	remaining: 29.5s
57:	learn: 0.1411556	total: 1.81s	remaining: 29.5s
58:	learn: 0.1400638	total: 1.84s	remaining: 29.4s
59:	learn: 0.1389773	total: 1.87s	remaining: 29.4s
60:	learn: 0.1379236	total: 1.91s	remaining: 29.4s
61:	learn: 0.1368111	total: 1.94s	remaining: 29.4s
62:	learn: 0.1357612	total: 1.97s	remaining: 29.3s
63:	learn: 0.1344695	total: 2s	remaining: 29.2s
64:	learn: 0.1335668	total: 2.03s	remaining: 29.2s
65:	learn: 0.1325512	total: 2.06s	remaining: 29.1s
66:	learn: 0.1317277	total: 2.09s	remaining: 29.1s
67:	learn: 0.1307903	total: 2.11s	remaining: 29s
68:	learn: 0.1299352	total: 2.14s	remaining: 28.9s
69:	learn: 0.1293350	total: 2.17s	remaining: 28.9s
70:	learn: 0.1285435	total: 2.2s	remaining: 28.8s
71:	learn: 0.1277718	total: 2.23s	remaining: 28.8s
72:	learn: 0.1269395	total: 2.26s	remaining: 28.7s
73:	learn: 0.1262666	total: 2.29s	remaining: 28.7s
74:	learn: 0.1257047	total: 2.32s	remaining: 28.6s
75:	learn: 0.1249212	total: 2.35s	remaining: 28.5s
76:	learn: 0.1243858	total: 2.37s	remaining: 28.4s
77:	learn: 0.1237021	total: 2.4s	remaining: 28.4s
78:	learn: 0.1231339	total: 2.43s	remaining: 28.3s
79:	learn: 0.1226513	total: 2.46s	remaining: 28.3s
80:	learn: 0.1219643	total: 2.49s	remaining: 28.3s
81:	learn: 0.1214499	total: 2.52s	remaining: 28.2s
82:	learn: 0.1208790	total: 2.55s	remaining: 28.2s
83:	learn: 0.1202587	total: 2.58s	remaining: 28.1s
84:	learn: 0.1196533	total: 2.61s	remaining: 28.1s
85:	learn: 0.1191648	total: 2.64s	remaining: 28.1s
86:	learn: 0.1188284	total: 2.67s	remaining: 28.1s
87:	learn: 0.1183189	total: 2.71s	remaining: 28.1s
88:	learn: 0.1180256	total: 2.74s	remaining: 28s
89:	learn: 0.1176905	total: 2.79s	remaining: 28.2s
90:	learn: 0.1173168	total: 2.81s	remaining: 28.1s
91:	learn: 0.1168293	total: 2.85s	remaining: 28.1s
92:	learn: 0.1163556	total: 2.87s	remaining: 28s
93:	learn: 0.1160319	total: 2.9s	remaining: 28s
94:	learn: 0.1155302	total: 2.93s	remaining: 28s
95:	learn: 0.1150763	total: 2.96s	remaining: 27.9s
96:	learn: 0.1147000	total: 3s	remaining: 27.9s
97:	learn: 0.1143612	total: 3.03s	remaining: 27.9s
98:	learn: 0.1139293	total: 3.06s	remaining: 27.8s
99:	learn: 0.1133496	total: 3.09s	remaining: 27.8s
100:	learn: 0.1128904	total: 3.12s	remaining: 27.8s
101:	learn: 0.1125492	total: 3.15s	remaining: 27.7s
102:	learn: 0.1122096	total: 3.18s	remaining: 27.7s
103:	learn: 0.1118961	total: 3.21s	remaining: 27.7s
104:	learn: 0.1116164	total: 3.24s	remaining: 27.6s
105:	learn: 0.1114238	total: 3.26s	remaining: 27.5s
106:	learn: 0.1110906	total: 3.29s	remaining: 27.5s
107:	learn: 0.1108681	total: 3.33s	remaining: 27.5s
108:	learn: 0.1106116	total: 3.35s	remaining: 27.4s
109:	learn: 0.1103247	total: 3.38s	remaining: 27.4s
110:	learn: 0.1099632	total: 3.42s	remaining: 27.4s
111:	learn: 0.1095925	total: 3.44s	remaining: 27.3s
112:	learn: 0.1093791	total: 3.47s	remaining: 27.3s
113:	learn: 0.1090816	total: 3.5s	remaining: 27.2s
114:	learn: 0.1089359	total: 3.53s	remaining: 27.2s
115:	learn: 0.1087401	total: 3.56s	remaining: 27.2s
116:	learn: 0.1085696	total: 3.6s	remaining: 27.1s
117:	learn: 0.1081995	total: 3.63s	remaining: 27.1s
118:	learn: 0.1079047	total: 3.66s	remaining: 27.1s
119:	learn: 0.1077252	total: 3.69s	remaining: 27.1s
120:	learn: 0.1074241	total: 3.72s	remaining: 27s
121:	learn: 0.1071115	total: 3.75s	remaining: 27s
122:	learn: 0.1068108	total: 3.78s	remaining: 26.9s
123:	learn: 0.1064135	total: 3.82s	remaining: 27s
124:	learn: 0.1062544	total: 3.85s	remaining: 27s
125:	learn: 0.1059448	total: 3.88s	remaining: 26.9s
126:	learn: 0.1056927	total: 3.91s	remaining: 26.9s
127:	learn: 0.1053667	total: 3.94s	remaining: 26.9s
128:	learn: 0.1051235	total: 3.97s	remaining: 26.8s
129:	learn: 0.1048324	total: 4.01s	remaining: 26.8s
130:	learn: 0.1046052	total: 4.04s	remaining: 26.8s
131:	learn: 0.1042479	total: 4.06s	remaining: 26.7s
132:	learn: 0.1039790	total: 4.09s	remaining: 26.7s
133:	learn: 0.1038179	total: 4.12s	remaining: 26.6s
134:	learn: 0.1036681	total: 4.15s	remaining: 26.6s
135:	learn: 0.1035265	total: 4.18s	remaining: 26.5s
136:	learn: 0.1034468	total: 4.21s	remaining: 26.5s
137:	learn: 0.1033251	total: 4.24s	remaining: 26.5s
138:	learn: 0.1031377	total: 4.27s	remaining: 26.5s
139:	learn: 0.1029628	total: 4.3s	remaining: 26.4s
140:	learn: 0.1026985	total: 4.33s	remaining: 26.4s
141:	learn: 0.1023204	total: 4.36s	remaining: 26.4s
142:	learn: 0.1021659	total: 4.39s	remaining: 26.3s
143:	learn: 0.1019570	total: 4.42s	remaining: 26.3s
144:	learn: 0.1018246	total: 4.45s	remaining: 26.2s
145:	learn: 0.1016991	total: 4.48s	remaining: 26.2s
146:	learn: 0.1015081	total: 4.51s	remaining: 26.2s
147:	learn: 0.1013032	total: 4.54s	remaining: 26.1s
148:	learn: 0.1011448	total: 4.56s	remaining: 26.1s
149:	learn: 0.1009416	total: 4.59s	remaining: 26s
150:	learn: 0.1007650	total: 4.62s	remaining: 26s
151:	learn: 0.1005635	total: 4.66s	remaining: 26s
152:	learn: 0.1005134	total: 4.67s	remaining: 25.9s
153:	learn: 0.1002517	total: 4.7s	remaining: 25.8s
154:	learn: 0.1000681	total: 4.74s	remaining: 25.8s
155:	learn: 0.0999318	total: 4.77s	remaining: 25.8s
156:	learn: 0.0996313	total: 4.8s	remaining: 25.8s
157:	learn: 0.0995498	total: 4.83s	remaining: 25.7s
158:	learn: 0.0992853	total: 4.86s	remaining: 25.7s
159:	learn: 0.0990416	total: 4.89s	remaining: 25.7s
160:	learn: 0.0987959	total: 4.92s	remaining: 25.6s
161:	learn: 0.0985564	total: 4.95s	remaining: 25.6s
162:	learn: 0.0983750	total: 4.98s	remaining: 25.6s
163:	learn: 0.0982283	total: 5.01s	remaining: 25.5s
164:	learn: 0.0980262	total: 5.04s	remaining: 25.5s
165:	learn: 0.0979397	total: 5.07s	remaining: 25.5s
166:	learn: 0.0977366	total: 5.1s	remaining: 25.4s
167:	learn: 0.0975550	total: 5.13s	remaining: 25.4s
168:	learn: 0.0973942	total: 5.16s	remaining: 25.4s
169:	learn: 0.0971162	total: 5.19s	remaining: 25.3s
170:	learn: 0.0969495	total: 5.22s	remaining: 25.3s
171:	learn: 0.0967322	total: 5.25s	remaining: 25.3s
172:	learn: 0.0965637	total: 5.28s	remaining: 25.3s
173:	learn: 0.0963309	total: 5.31s	remaining: 25.2s
174:	learn: 0.0961750	total: 5.34s	remaining: 25.2s
175:	learn: 0.0960922	total: 5.37s	remaining: 25.1s
176:	learn: 0.0959049	total: 5.4s	remaining: 25.1s
177:	learn: 0.0957214	total: 5.43s	remaining: 25.1s
178:	learn: 0.0956440	total: 5.46s	remaining: 25.1s
179:	learn: 0.0955612	total: 5.5s	remaining: 25s
180:	learn: 0.0953980	total: 5.52s	remaining: 25s
181:	learn: 0.0952494	total: 5.55s	remaining: 25s
182:	learn: 0.0951301	total: 5.58s	remaining: 24.9s
183:	learn: 0.0949975	total: 5.61s	remaining: 24.9s
184:	learn: 0.0947710	total: 5.64s	remaining: 24.9s
185:	learn: 0.0946756	total: 5.67s	remaining: 24.8s
186:	learn: 0.0944998	total: 5.71s	remaining: 24.8s
187:	learn: 0.0943348	total: 5.74s	remaining: 24.8s
188:	learn: 0.0942087	total: 5.77s	remaining: 24.8s
189:	learn: 0.0939943	total: 5.8s	remaining: 24.7s
190:	learn: 0.0938876	total: 5.83s	remaining: 24.7s
191:	learn: 0.0938429	total: 5.86s	remaining: 24.7s
192:	learn: 0.0936731	total: 5.89s	remaining: 24.6s
193:	learn: 0.0935510	total: 5.94s	remaining: 24.7s
194:	learn: 0.0934240	total: 5.99s	remaining: 24.7s
195:	learn: 0.0933004	total: 6.01s	remaining: 24.7s
196:	learn: 0.0930515	total: 6.04s	remaining: 24.6s
197:	learn: 0.0929545	total: 6.07s	remaining: 24.6s
198:	learn: 0.0929054	total: 6.11s	remaining: 24.6s
199:	learn: 0.0927854	total: 6.14s	remaining: 24.6s
200:	learn: 0.0927133	total: 6.17s	remaining: 24.5s
201:	learn: 0.0926669	total: 6.2s	remaining: 24.5s
202:	learn: 0.0926197	total: 6.23s	remaining: 24.5s
203:	learn: 0.0924713	total: 6.26s	remaining: 24.4s
204:	learn: 0.0923284	total: 6.29s	remaining: 24.4s
205:	learn: 0.0922124	total: 6.32s	remaining: 24.4s
206:	learn: 0.0919285	total: 6.35s	remaining: 24.3s
207:	learn: 0.0918289	total: 6.38s	remaining: 24.3s
208:	learn: 0.0917040	total: 6.41s	remaining: 24.3s
209:	learn: 0.0916015	total: 6.44s	remaining: 24.2s
210:	learn: 0.0915378	total: 6.47s	remaining: 24.2s
211:	learn: 0.0914767	total: 6.5s	remaining: 24.2s
212:	learn: 0.0912240	total: 6.53s	remaining: 24.1s
213:	learn: 0.0911320	total: 6.56s	remaining: 24.1s
214:	learn: 0.0909109	total: 6.59s	remaining: 24.1s
215:	learn: 0.0906966	total: 6.62s	remaining: 24s
216:	learn: 0.0906377	total: 6.65s	remaining: 24s
217:	learn: 0.0905755	total: 6.68s	remaining: 24s
218:	learn: 0.0905032	total: 6.71s	remaining: 23.9s
219:	learn: 0.0903969	total: 6.75s	remaining: 23.9s
220:	learn: 0.0902459	total: 6.78s	remaining: 23.9s
221:	learn: 0.0901650	total: 6.81s	remaining: 23.9s
222:	learn: 0.0901354	total: 6.83s	remaining: 23.8s
223:	learn: 0.0900977	total: 6.87s	remaining: 23.8s
224:	learn: 0.0899572	total: 6.9s	remaining: 23.8s
225:	learn: 0.0898412	total: 6.93s	remaining: 23.7s
226:	learn: 0.0896207	total: 6.96s	remaining: 23.7s
227:	learn: 0.0895741	total: 6.99s	remaining: 23.7s
228:	learn: 0.0895305	total: 7.02s	remaining: 23.6s
229:	learn: 0.0894599	total: 7.05s	remaining: 23.6s
230:	learn: 0.0892705	total: 7.08s	remaining: 23.6s
231:	learn: 0.0892325	total: 7.11s	remaining: 23.5s
232:	learn: 0.0892078	total: 7.14s	remaining: 23.5s
233:	learn: 0.0890628	total: 7.17s	remaining: 23.5s
234:	learn: 0.0889572	total: 7.21s	remaining: 23.5s
235:	learn: 0.0888064	total: 7.24s	remaining: 23.4s
236:	learn: 0.0887389	total: 7.27s	remaining: 23.4s
237:	learn: 0.0885928	total: 7.3s	remaining: 23.4s
238:	learn: 0.0884814	total: 7.32s	remaining: 23.3s
239:	learn: 0.0883127	total: 7.35s	remaining: 23.3s
240:	learn: 0.0882415	total: 7.38s	remaining: 23.2s
241:	learn: 0.0882015	total: 7.41s	remaining: 23.2s
242:	learn: 0.0881302	total: 7.44s	remaining: 23.2s
243:	learn: 0.0880510	total: 7.47s	remaining: 23.2s
244:	learn: 0.0879248	total: 7.5s	remaining: 23.1s
245:	learn: 0.0878896	total: 7.54s	remaining: 23.1s
246:	learn: 0.0876273	total: 7.57s	remaining: 23.1s
247:	learn: 0.0875828	total: 7.6s	remaining: 23s
248:	learn: 0.0874767	total: 7.62s	remaining: 23s
249:	learn: 0.0874409	total: 7.66s	remaining: 23s
250:	learn: 0.0872972	total: 7.69s	remaining: 22.9s
251:	learn: 0.0872560	total: 7.72s	remaining: 22.9s
252:	learn: 0.0870743	total: 7.75s	remaining: 22.9s
253:	learn: 0.0869934	total: 7.78s	remaining: 22.8s
254:	learn: 0.0868613	total: 7.81s	remaining: 22.8s
255:	learn: 0.0866688	total: 7.84s	remaining: 22.8s
256:	learn: 0.0865423	total: 7.87s	remaining: 22.8s
257:	learn: 0.0864171	total: 7.9s	remaining: 22.7s
258:	learn: 0.0863000	total: 7.93s	remaining: 22.7s
259:	learn: 0.0862723	total: 7.96s	remaining: 22.7s
260:	learn: 0.0862397	total: 8s	remaining: 22.6s
261:	learn: 0.0861176	total: 8.03s	remaining: 22.6s
262:	learn: 0.0860956	total: 8.06s	remaining: 22.6s
263:	learn: 0.0859601	total: 8.09s	remaining: 22.5s
264:	learn: 0.0858355	total: 8.13s	remaining: 22.5s
265:	learn: 0.0857108	total: 8.16s	remaining: 22.5s
266:	learn: 0.0856873	total: 8.19s	remaining: 22.5s
267:	learn: 0.0856250	total: 8.22s	remaining: 22.4s
268:	learn: 0.0855210	total: 8.25s	remaining: 22.4s
269:	learn: 0.0854568	total: 8.28s	remaining: 22.4s
270:	learn: 0.0853030	total: 8.31s	remaining: 22.4s
271:	learn: 0.0852896	total: 8.34s	remaining: 22.3s
272:	learn: 0.0850875	total: 8.37s	remaining: 22.3s
273:	learn: 0.0850531	total: 8.4s	remaining: 22.3s
274:	learn: 0.0849229	total: 8.44s	remaining: 22.2s
275:	learn: 0.0847827	total: 8.46s	remaining: 22.2s
276:	learn: 0.0846479	total: 8.51s	remaining: 22.2s
277:	learn: 0.0846220	total: 8.54s	remaining: 22.2s
278:	learn: 0.0845604	total: 8.57s	remaining: 22.2s
279:	learn: 0.0845454	total: 8.6s	remaining: 22.1s
280:	learn: 0.0844939	total: 8.63s	remaining: 22.1s
281:	learn: 0.0843079	total: 8.66s	remaining: 22.1s
282:	learn: 0.0841506	total: 8.69s	remaining: 22s
283:	learn: 0.0839740	total: 8.73s	remaining: 22s
284:	learn: 0.0837814	total: 8.76s	remaining: 22s
285:	learn: 0.0836996	total: 8.78s	remaining: 21.9s
286:	learn: 0.0836534	total: 8.81s	remaining: 21.9s
287:	learn: 0.0834648	total: 8.84s	remaining: 21.9s
288:	learn: 0.0833199	total: 8.87s	remaining: 21.8s
289:	learn: 0.0832035	total: 8.9s	remaining: 21.8s
290:	learn: 0.0830727	total: 8.93s	remaining: 21.8s
291:	learn: 0.0830345	total: 8.97s	remaining: 21.7s
292:	learn: 0.0829198	total: 9s	remaining: 21.7s
293:	learn: 0.0827929	total: 9.02s	remaining: 21.7s
294:	learn: 0.0827739	total: 9.05s	remaining: 21.6s
295:	learn: 0.0826465	total: 9.08s	remaining: 21.6s
296:	learn: 0.0825663	total: 9.11s	remaining: 21.6s
297:	learn: 0.0825341	total: 9.14s	remaining: 21.5s
298:	learn: 0.0824847	total: 9.17s	remaining: 21.5s
299:	learn: 0.0824071	total: 9.2s	remaining: 21.5s
300:	learn: 0.0822691	total: 9.23s	remaining: 21.4s
301:	learn: 0.0821642	total: 9.26s	remaining: 21.4s
302:	learn: 0.0820127	total: 9.29s	remaining: 21.4s
303:	learn: 0.0818963	total: 9.32s	remaining: 21.3s
304:	learn: 0.0818083	total: 9.35s	remaining: 21.3s
305:	learn: 0.0816830	total: 9.38s	remaining: 21.3s
306:	learn: 0.0815132	total: 9.41s	remaining: 21.2s
307:	learn: 0.0813331	total: 9.44s	remaining: 21.2s
308:	learn: 0.0812693	total: 9.47s	remaining: 21.2s
309:	learn: 0.0810649	total: 9.5s	remaining: 21.1s
310:	learn: 0.0808752	total: 9.53s	remaining: 21.1s
311:	learn: 0.0808117	total: 9.56s	remaining: 21.1s
312:	learn: 0.0807697	total: 9.59s	remaining: 21.1s
313:	learn: 0.0806471	total: 9.62s	remaining: 21s
314:	learn: 0.0805556	total: 9.65s	remaining: 21s
315:	learn: 0.0804690	total: 9.68s	remaining: 21s
316:	learn: 0.0803465	total: 9.72s	remaining: 20.9s
317:	learn: 0.0802697	total: 9.74s	remaining: 20.9s
318:	learn: 0.0801493	total: 9.77s	remaining: 20.9s
319:	learn: 0.0801103	total: 9.81s	remaining: 20.8s
320:	learn: 0.0799717	total: 9.84s	remaining: 20.8s
321:	learn: 0.0798812	total: 9.86s	remaining: 20.8s
322:	learn: 0.0798301	total: 9.89s	remaining: 20.7s
323:	learn: 0.0798106	total: 9.92s	remaining: 20.7s
324:	learn: 0.0796747	total: 9.95s	remaining: 20.7s
325:	learn: 0.0796462	total: 9.98s	remaining: 20.6s
326:	learn: 0.0796052	total: 10s	remaining: 20.6s
327:	learn: 0.0795835	total: 10s	remaining: 20.6s
328:	learn: 0.0795511	total: 10.1s	remaining: 20.5s
329:	learn: 0.0794413	total: 10.1s	remaining: 20.5s
330:	learn: 0.0793454	total: 10.1s	remaining: 20.5s
331:	learn: 0.0792632	total: 10.2s	remaining: 20.4s
332:	learn: 0.0791559	total: 10.2s	remaining: 20.4s
333:	learn: 0.0791402	total: 10.2s	remaining: 20.4s
334:	learn: 0.0791194	total: 10.3s	remaining: 20.4s
335:	learn: 0.0789673	total: 10.3s	remaining: 20.4s
336:	learn: 0.0788989	total: 10.4s	remaining: 20.4s
337:	learn: 0.0787773	total: 10.4s	remaining: 20.3s
338:	learn: 0.0786279	total: 10.4s	remaining: 20.3s
339:	learn: 0.0784877	total: 10.4s	remaining: 20.3s
340:	learn: 0.0783541	total: 10.5s	remaining: 20.2s
341:	learn: 0.0782902	total: 10.5s	remaining: 20.2s
342:	learn: 0.0782575	total: 10.5s	remaining: 20.2s
343:	learn: 0.0781331	total: 10.6s	remaining: 20.1s
344:	learn: 0.0780410	total: 10.6s	remaining: 20.1s
345:	learn: 0.0778649	total: 10.6s	remaining: 20.1s
346:	learn: 0.0777668	total: 10.7s	remaining: 20s
347:	learn: 0.0777025	total: 10.7s	remaining: 20s
348:	learn: 0.0775978	total: 10.7s	remaining: 20s
349:	learn: 0.0775507	total: 10.7s	remaining: 20s
350:	learn: 0.0775378	total: 10.8s	remaining: 19.9s
351:	learn: 0.0774741	total: 10.8s	remaining: 19.9s
352:	learn: 0.0774202	total: 10.8s	remaining: 19.9s
353:	learn: 0.0772786	total: 10.9s	remaining: 19.8s
354:	learn: 0.0771732	total: 10.9s	remaining: 19.8s
355:	learn: 0.0770187	total: 10.9s	remaining: 19.8s
356:	learn: 0.0769334	total: 11s	remaining: 19.7s
357:	learn: 0.0769145	total: 11s	remaining: 19.7s
358:	learn: 0.0767733	total: 11s	remaining: 19.7s
359:	learn: 0.0767543	total: 11s	remaining: 19.6s
360:	learn: 0.0766730	total: 11.1s	remaining: 19.6s
361:	learn: 0.0766536	total: 11.1s	remaining: 19.6s
362:	learn: 0.0764610	total: 11.1s	remaining: 19.5s
363:	learn: 0.0764072	total: 11.2s	remaining: 19.5s
364:	learn: 0.0763316	total: 11.2s	remaining: 19.5s
365:	learn: 0.0762725	total: 11.2s	remaining: 19.5s
366:	learn: 0.0761326	total: 11.3s	remaining: 19.4s
367:	learn: 0.0760256	total: 11.3s	remaining: 19.4s
368:	learn: 0.0758829	total: 11.3s	remaining: 19.4s
369:	learn: 0.0757780	total: 11.4s	remaining: 19.3s
370:	learn: 0.0757108	total: 11.4s	remaining: 19.3s
371:	learn: 0.0756506	total: 11.4s	remaining: 19.3s
372:	learn: 0.0754364	total: 11.4s	remaining: 19.2s
373:	learn: 0.0753717	total: 11.5s	remaining: 19.2s
374:	learn: 0.0751984	total: 11.5s	remaining: 19.2s
375:	learn: 0.0751601	total: 11.5s	remaining: 19.1s
376:	learn: 0.0751121	total: 11.6s	remaining: 19.1s
377:	learn: 0.0750598	total: 11.6s	remaining: 19.1s
378:	learn: 0.0750352	total: 11.6s	remaining: 19.1s
379:	learn: 0.0749148	total: 11.7s	remaining: 19s
380:	learn: 0.0748655	total: 11.7s	remaining: 19s
381:	learn: 0.0746998	total: 11.7s	remaining: 19s
382:	learn: 0.0746609	total: 11.8s	remaining: 18.9s
383:	learn: 0.0745230	total: 11.8s	remaining: 18.9s
384:	learn: 0.0744059	total: 11.8s	remaining: 18.9s
385:	learn: 0.0743634	total: 11.9s	remaining: 18.9s
386:	learn: 0.0743070	total: 11.9s	remaining: 18.8s

CV folds:  86%|████████▌ | 43/50 [22:38<03:40, 31.49s/fold]

998:	learn: 0.0442902	total: 31s	remaining: 31ms
999:	learn: 0.0442251	total: 31s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3887475	total: 28.7ms	remaining: 28.7s
1:	learn: 0.3776537	total: 59.3ms	remaining: 29.6s
2:	learn: 0.3672480	total: 87.3ms	remaining: 29s
3:	learn: 0.3576309	total: 119ms	remaining: 29.7s
4:	learn: 0.3481740	total: 151ms	remaining: 30.1s
5:	learn: 0.3389034	total: 178ms	remaining: 29.5s
6:	learn: 0.3297190	total: 207ms	remaining: 29.3s
7:	learn: 0.3216531	total: 239ms	remaining: 29.6s
8:	learn: 0.3138302	total: 271ms	remaining: 29.9s
9:	learn: 0.3055185	total: 301ms	remaining: 29.8s
10:	learn: 0.2986521	total: 334ms	remaining: 30s
11:	learn: 0.2914878	total: 365ms	remaining: 30s
12:	learn: 0.2845511	total: 397ms	remaining: 30.2s
13:	learn: 0.2779704	total: 424ms	remaining: 29.9s
14:	learn: 0.2715205	total: 455ms	remaining: 29.9s
15:	learn: 0.2650652	total: 485ms	remaining: 29.8s
16:	learn: 0.2587505	total: 536ms	remaining: 31s
17:	learn: 0.2524195	total: 565ms	remaining: 30.8s
18:	learn: 0.2476065	total: 595ms	remaining: 30.7s
19:	learn: 0.2424284	total: 622ms	remaining: 30.5s
20:	learn: 0.2375433	total: 653ms	remaining: 30.4s
21:	learn: 0.2327515	total: 685ms	remaining: 30.5s
22:	learn: 0.2283039	total: 715ms	remaining: 30.4s
23:	learn: 0.2236411	total: 744ms	remaining: 30.3s
24:	learn: 0.2195071	total: 773ms	remaining: 30.2s
25:	learn: 0.2153410	total: 805ms	remaining: 30.1s
26:	learn: 0.2112045	total: 834ms	remaining: 30.1s
27:	learn: 0.2073214	total: 863ms	remaining: 30s
28:	learn: 0.2033502	total: 891ms	remaining: 29.8s
29:	learn: 0.2002563	total: 919ms	remaining: 29.7s
30:	learn: 0.1971407	total: 952ms	remaining: 29.7s
31:	learn: 0.1943340	total: 982ms	remaining: 29.7s
32:	learn: 0.1912571	total: 1.01s	remaining: 29.7s
33:	learn: 0.1881394	total: 1.04s	remaining: 29.6s
34:	learn: 0.1852736	total: 1.07s	remaining: 29.5s
35:	learn: 0.1825780	total: 1.1s	remaining: 29.5s
36:	learn: 0.1797095	total: 1.13s	remaining: 29.5s
37:	learn: 0.1770669	total: 1.16s	remaining: 29.4s
38:	learn: 0.1745392	total: 1.19s	remaining: 29.4s
39:	learn: 0.1719341	total: 1.23s	remaining: 29.4s
40:	learn: 0.1696666	total: 1.26s	remaining: 29.4s
41:	learn: 0.1675950	total: 1.28s	remaining: 29.3s
42:	learn: 0.1653870	total: 1.31s	remaining: 29.2s
43:	learn: 0.1632706	total: 1.34s	remaining: 29.2s
44:	learn: 0.1612441	total: 1.37s	remaining: 29.2s
45:	learn: 0.1596448	total: 1.41s	remaining: 29.1s
46:	learn: 0.1578508	total: 1.43s	remaining: 29.1s
47:	learn: 0.1562641	total: 1.46s	remaining: 29s
48:	learn: 0.1546273	total: 1.49s	remaining: 29s
49:	learn: 0.1530698	total: 1.52s	remaining: 29s
50:	learn: 0.1513763	total: 1.55s	remaining: 28.9s
51:	learn: 0.1498976	total: 1.59s	remaining: 28.9s
52:	learn: 0.1483617	total: 1.61s	remaining: 28.8s
53:	learn: 0.1470279	total: 1.64s	remaining: 28.8s
54:	learn: 0.1457564	total: 1.67s	remaining: 28.7s
55:	learn: 0.1445582	total: 1.7s	remaining: 28.7s
56:	learn: 0.1432578	total: 1.73s	remaining: 28.6s
57:	learn: 0.1418598	total: 1.76s	remaining: 28.5s
58:	learn: 0.1407906	total: 1.79s	remaining: 28.5s
59:	learn: 0.1398636	total: 1.81s	remaining: 28.4s
60:	learn: 0.1387259	total: 1.84s	remaining: 28.4s
61:	learn: 0.1376739	total: 1.87s	remaining: 28.3s
62:	learn: 0.1367900	total: 1.9s	remaining: 28.3s
63:	learn: 0.1357540	total: 1.93s	remaining: 28.3s
64:	learn: 0.1347571	total: 1.98s	remaining: 28.4s
65:	learn: 0.1339156	total: 2.01s	remaining: 28.4s
66:	learn: 0.1331995	total: 2.04s	remaining: 28.5s
67:	learn: 0.1323359	total: 2.08s	remaining: 28.5s
68:	learn: 0.1315773	total: 2.11s	remaining: 28.5s
69:	learn: 0.1306923	total: 2.14s	remaining: 28.5s
70:	learn: 0.1300431	total: 2.17s	remaining: 28.4s
71:	learn: 0.1294805	total: 2.2s	remaining: 28.4s
72:	learn: 0.1287657	total: 2.23s	remaining: 28.3s
73:	learn: 0.1280879	total: 2.26s	remaining: 28.3s
74:	learn: 0.1274262	total: 2.29s	remaining: 28.3s
75:	learn: 0.1266037	total: 2.32s	remaining: 28.2s
76:	learn: 0.1260906	total: 2.35s	remaining: 28.2s
77:	learn: 0.1255351	total: 2.38s	remaining: 28.1s
78:	learn: 0.1250054	total: 2.41s	remaining: 28.1s
79:	learn: 0.1244419	total: 2.44s	remaining: 28s
80:	learn: 0.1237658	total: 2.47s	remaining: 28s
81:	learn: 0.1231070	total: 2.5s	remaining: 28s
82:	learn: 0.1225209	total: 2.53s	remaining: 28s
83:	learn: 0.1219214	total: 2.56s	remaining: 27.9s
84:	learn: 0.1213938	total: 2.59s	remaining: 27.9s
85:	learn: 0.1208744	total: 2.62s	remaining: 27.8s
86:	learn: 0.1204226	total: 2.65s	remaining: 27.8s
87:	learn: 0.1197703	total: 2.7s	remaining: 28s
88:	learn: 0.1192134	total: 2.73s	remaining: 28s
89:	learn: 0.1187084	total: 2.76s	remaining: 27.9s
90:	learn: 0.1182255	total: 2.79s	remaining: 27.9s
91:	learn: 0.1178369	total: 2.82s	remaining: 27.8s
92:	learn: 0.1173879	total: 2.85s	remaining: 27.8s
93:	learn: 0.1169672	total: 2.88s	remaining: 27.8s
94:	learn: 0.1166237	total: 2.91s	remaining: 27.8s
95:	learn: 0.1162016	total: 2.94s	remaining: 27.7s
96:	learn: 0.1157144	total: 2.98s	remaining: 27.7s
97:	learn: 0.1152103	total: 3.01s	remaining: 27.7s
98:	learn: 0.1148587	total: 3.04s	remaining: 27.7s
99:	learn: 0.1144534	total: 3.08s	remaining: 27.7s
100:	learn: 0.1140038	total: 3.11s	remaining: 27.7s
101:	learn: 0.1136234	total: 3.14s	remaining: 27.7s
102:	learn: 0.1130455	total: 3.19s	remaining: 27.8s
103:	learn: 0.1127548	total: 3.22s	remaining: 27.8s
104:	learn: 0.1124516	total: 3.25s	remaining: 27.7s
105:	learn: 0.1120799	total: 3.28s	remaining: 27.7s
106:	learn: 0.1115948	total: 3.31s	remaining: 27.6s
107:	learn: 0.1112290	total: 3.34s	remaining: 27.6s
108:	learn: 0.1107738	total: 3.37s	remaining: 27.6s
109:	learn: 0.1104565	total: 3.4s	remaining: 27.5s
110:	learn: 0.1101786	total: 3.43s	remaining: 27.5s
111:	learn: 0.1098868	total: 3.46s	remaining: 27.4s
112:	learn: 0.1095832	total: 3.49s	remaining: 27.4s
113:	learn: 0.1092300	total: 3.52s	remaining: 27.4s
114:	learn: 0.1088277	total: 3.55s	remaining: 27.3s
115:	learn: 0.1085836	total: 3.58s	remaining: 27.3s
116:	learn: 0.1083620	total: 3.61s	remaining: 27.2s
117:	learn: 0.1080510	total: 3.64s	remaining: 27.2s
118:	learn: 0.1076705	total: 3.67s	remaining: 27.2s
119:	learn: 0.1074576	total: 3.71s	remaining: 27.2s
120:	learn: 0.1071595	total: 3.74s	remaining: 27.2s
121:	learn: 0.1068461	total: 3.78s	remaining: 27.2s
122:	learn: 0.1066012	total: 3.81s	remaining: 27.2s
123:	learn: 0.1063194	total: 3.84s	remaining: 27.1s
124:	learn: 0.1060494	total: 3.87s	remaining: 27.1s
125:	learn: 0.1057293	total: 3.9s	remaining: 27.1s
126:	learn: 0.1054837	total: 3.93s	remaining: 27s
127:	learn: 0.1051336	total: 3.97s	remaining: 27s
128:	learn: 0.1049585	total: 4s	remaining: 27s
129:	learn: 0.1048008	total: 4.03s	remaining: 27s
130:	learn: 0.1045876	total: 4.06s	remaining: 26.9s
131:	learn: 0.1044169	total: 4.09s	remaining: 26.9s
132:	learn: 0.1041255	total: 4.13s	remaining: 26.9s
133:	learn: 0.1039244	total: 4.16s	remaining: 26.9s
134:	learn: 0.1036930	total: 4.19s	remaining: 26.8s
135:	learn: 0.1034657	total: 4.22s	remaining: 26.8s
136:	learn: 0.1033574	total: 4.25s	remaining: 26.8s
137:	learn: 0.1031099	total: 4.28s	remaining: 26.7s
138:	learn: 0.1028320	total: 4.3s	remaining: 26.7s
139:	learn: 0.1026045	total: 4.33s	remaining: 26.6s
140:	learn: 0.1024355	total: 4.36s	remaining: 26.6s
141:	learn: 0.1022440	total: 4.39s	remaining: 26.6s
142:	learn: 0.1019010	total: 4.42s	remaining: 26.5s
143:	learn: 0.1017006	total: 4.45s	remaining: 26.5s
144:	learn: 0.1015056	total: 4.48s	remaining: 26.4s
145:	learn: 0.1013478	total: 4.51s	remaining: 26.4s
146:	learn: 0.1011594	total: 4.54s	remaining: 26.3s
147:	learn: 0.1009987	total: 4.57s	remaining: 26.3s
148:	learn: 0.1008552	total: 4.6s	remaining: 26.3s
149:	learn: 0.1006744	total: 4.63s	remaining: 26.2s
150:	learn: 0.1003970	total: 4.66s	remaining: 26.2s
151:	learn: 0.1001793	total: 4.69s	remaining: 26.1s
152:	learn: 0.1000620	total: 4.71s	remaining: 26.1s
153:	learn: 0.0999009	total: 4.74s	remaining: 26s
154:	learn: 0.0996554	total: 4.77s	remaining: 26s
155:	learn: 0.0995074	total: 4.8s	remaining: 26s
156:	learn: 0.0993717	total: 4.84s	remaining: 26s
157:	learn: 0.0991892	total: 4.88s	remaining: 26s
158:	learn: 0.0990381	total: 4.91s	remaining: 25.9s
159:	learn: 0.0989183	total: 4.94s	remaining: 25.9s
160:	learn: 0.0987452	total: 4.96s	remaining: 25.9s
161:	learn: 0.0985846	total: 4.99s	remaining: 25.8s
162:	learn: 0.0984189	total: 5.02s	remaining: 25.8s
163:	learn: 0.0981745	total: 5.05s	remaining: 25.7s
164:	learn: 0.0980807	total: 5.08s	remaining: 25.7s
165:	learn: 0.0979222	total: 5.11s	remaining: 25.7s
166:	learn: 0.0976574	total: 5.14s	remaining: 25.6s
167:	learn: 0.0975084	total: 5.17s	remaining: 25.6s
168:	learn: 0.0973083	total: 5.2s	remaining: 25.6s
169:	learn: 0.0971713	total: 5.23s	remaining: 25.5s
170:	learn: 0.0970166	total: 5.26s	remaining: 25.5s
171:	learn: 0.0968881	total: 5.29s	remaining: 25.5s
172:	learn: 0.0967541	total: 5.32s	remaining: 25.4s
173:	learn: 0.0966062	total: 5.35s	remaining: 25.4s
174:	learn: 0.0963905	total: 5.38s	remaining: 25.4s
175:	learn: 0.0962434	total: 5.41s	remaining: 25.3s
176:	learn: 0.0961540	total: 5.44s	remaining: 25.3s
177:	learn: 0.0959160	total: 5.47s	remaining: 25.3s
178:	learn: 0.0957565	total: 5.5s	remaining: 25.2s
179:	learn: 0.0956124	total: 5.53s	remaining: 25.2s
180:	learn: 0.0954317	total: 5.56s	remaining: 25.2s
181:	learn: 0.0952825	total: 5.59s	remaining: 25.1s
182:	learn: 0.0951698	total: 5.62s	remaining: 25.1s
183:	learn: 0.0949772	total: 5.65s	remaining: 25.1s
184:	learn: 0.0948798	total: 5.68s	remaining: 25s
185:	learn: 0.0948162	total: 5.71s	remaining: 25s
186:	learn: 0.0945807	total: 5.74s	remaining: 24.9s
187:	learn: 0.0945505	total: 5.77s	remaining: 24.9s
188:	learn: 0.0944177	total: 5.8s	remaining: 24.9s
189:	learn: 0.0943523	total: 5.83s	remaining: 24.9s
190:	learn: 0.0943355	total: 5.85s	remaining: 24.8s
191:	learn: 0.0942367	total: 5.88s	remaining: 24.7s
192:	learn: 0.0941190	total: 5.91s	remaining: 24.7s
193:	learn: 0.0939690	total: 5.94s	remaining: 24.7s
194:	learn: 0.0938731	total: 5.97s	remaining: 24.6s
195:	learn: 0.0937854	total: 6s	remaining: 24.6s
196:	learn: 0.0936767	total: 6.04s	remaining: 24.6s
197:	learn: 0.0934584	total: 6.07s	remaining: 24.6s
198:	learn: 0.0933212	total: 6.1s	remaining: 24.5s
199:	learn: 0.0931920	total: 6.13s	remaining: 24.5s
200:	learn: 0.0931121	total: 6.15s	remaining: 24.5s
201:	learn: 0.0929785	total: 6.18s	remaining: 24.4s
202:	learn: 0.0928747	total: 6.21s	remaining: 24.4s
203:	learn: 0.0927969	total: 6.24s	remaining: 24.4s
204:	learn: 0.0927733	total: 6.27s	remaining: 24.3s
205:	learn: 0.0926654	total: 6.3s	remaining: 24.3s
206:	learn: 0.0925165	total: 6.33s	remaining: 24.3s
207:	learn: 0.0923292	total: 6.36s	remaining: 24.2s
208:	learn: 0.0921900	total: 6.39s	remaining: 24.2s
209:	learn: 0.0920724	total: 6.42s	remaining: 24.2s
210:	learn: 0.0919794	total: 6.45s	remaining: 24.1s
211:	learn: 0.0919107	total: 6.48s	remaining: 24.1s
212:	learn: 0.0917597	total: 6.51s	remaining: 24.1s
213:	learn: 0.0915899	total: 6.55s	remaining: 24s
214:	learn: 0.0915274	total: 6.58s	remaining: 24s
215:	learn: 0.0913557	total: 6.61s	remaining: 24s
216:	learn: 0.0911419	total: 6.64s	remaining: 24s
217:	learn: 0.0910805	total: 6.68s	remaining: 24s
218:	learn: 0.0909548	total: 6.71s	remaining: 23.9s
219:	learn: 0.0907402	total: 6.74s	remaining: 23.9s
220:	learn: 0.0906703	total: 6.77s	remaining: 23.9s
221:	learn: 0.0905314	total: 6.8s	remaining: 23.8s
222:	learn: 0.0904584	total: 6.84s	remaining: 23.8s
223:	learn: 0.0903121	total: 6.87s	remaining: 23.8s
224:	learn: 0.0902355	total: 6.9s	remaining: 23.8s
225:	learn: 0.0901453	total: 6.93s	remaining: 23.7s
226:	learn: 0.0899456	total: 6.96s	remaining: 23.7s
227:	learn: 0.0897262	total: 7.01s	remaining: 23.7s
228:	learn: 0.0895899	total: 7.04s	remaining: 23.7s
229:	learn: 0.0894000	total: 7.07s	remaining: 23.7s
230:	learn: 0.0892401	total: 7.1s	remaining: 23.6s
231:	learn: 0.0891608	total: 7.13s	remaining: 23.6s
232:	learn: 0.0890703	total: 7.18s	remaining: 23.6s
233:	learn: 0.0889307	total: 7.22s	remaining: 23.6s
234:	learn: 0.0888953	total: 7.25s	remaining: 23.6s
235:	learn: 0.0888597	total: 7.28s	remaining: 23.6s
236:	learn: 0.0887679	total: 7.31s	remaining: 23.5s
237:	learn: 0.0886779	total: 7.34s	remaining: 23.5s
238:	learn: 0.0884887	total: 7.37s	remaining: 23.5s
239:	learn: 0.0883914	total: 7.4s	remaining: 23.4s
240:	learn: 0.0883466	total: 7.43s	remaining: 23.4s
241:	learn: 0.0882352	total: 7.46s	remaining: 23.4s
242:	learn: 0.0880580	total: 7.49s	remaining: 23.3s
243:	learn: 0.0879473	total: 7.53s	remaining: 23.3s
244:	learn: 0.0879189	total: 7.56s	remaining: 23.3s
245:	learn: 0.0878437	total: 7.6s	remaining: 23.3s
246:	learn: 0.0877874	total: 7.62s	remaining: 23.2s
247:	learn: 0.0877011	total: 7.65s	remaining: 23.2s
248:	learn: 0.0876629	total: 7.68s	remaining: 23.2s
249:	learn: 0.0874846	total: 7.71s	remaining: 23.1s
250:	learn: 0.0873546	total: 7.74s	remaining: 23.1s
251:	learn: 0.0872146	total: 7.77s	remaining: 23.1s
252:	learn: 0.0871005	total: 7.81s	remaining: 23s
253:	learn: 0.0869423	total: 7.83s	remaining: 23s
254:	learn: 0.0868069	total: 7.86s	remaining: 23s
255:	learn: 0.0865723	total: 7.89s	remaining: 22.9s
256:	learn: 0.0863925	total: 7.92s	remaining: 22.9s
257:	learn: 0.0862815	total: 7.95s	remaining: 22.9s
258:	learn: 0.0861945	total: 7.98s	remaining: 22.8s
259:	learn: 0.0861456	total: 8.01s	remaining: 22.8s
260:	learn: 0.0860533	total: 8.04s	remaining: 22.8s
261:	learn: 0.0860225	total: 8.07s	remaining: 22.7s
262:	learn: 0.0858985	total: 8.1s	remaining: 22.7s
263:	learn: 0.0858699	total: 8.13s	remaining: 22.7s
264:	learn: 0.0858383	total: 8.16s	remaining: 22.6s
265:	learn: 0.0856867	total: 8.2s	remaining: 22.6s
266:	learn: 0.0855400	total: 8.23s	remaining: 22.6s
267:	learn: 0.0855118	total: 8.26s	remaining: 22.5s
268:	learn: 0.0854868	total: 8.29s	remaining: 22.5s
269:	learn: 0.0853301	total: 8.31s	remaining: 22.5s
270:	learn: 0.0852626	total: 8.34s	remaining: 22.4s
271:	learn: 0.0851532	total: 8.38s	remaining: 22.4s
272:	learn: 0.0850385	total: 8.41s	remaining: 22.4s
273:	learn: 0.0849815	total: 8.44s	remaining: 22.4s
274:	learn: 0.0849619	total: 8.47s	remaining: 22.3s
275:	learn: 0.0849449	total: 8.5s	remaining: 22.3s
276:	learn: 0.0848069	total: 8.53s	remaining: 22.3s
277:	learn: 0.0847237	total: 8.56s	remaining: 22.2s
278:	learn: 0.0845912	total: 8.6s	remaining: 22.2s
279:	learn: 0.0845638	total: 8.63s	remaining: 22.2s
280:	learn: 0.0844249	total: 8.66s	remaining: 22.2s
281:	learn: 0.0843449	total: 8.69s	remaining: 22.1s
282:	learn: 0.0841518	total: 8.72s	remaining: 22.1s
283:	learn: 0.0840340	total: 8.75s	remaining: 22.1s
284:	learn: 0.0840035	total: 8.78s	remaining: 22s
285:	learn: 0.0839620	total: 8.81s	remaining: 22s
286:	learn: 0.0839290	total: 8.84s	remaining: 22s
287:	learn: 0.0839024	total: 8.87s	remaining: 21.9s
288:	learn: 0.0837716	total: 8.9s	remaining: 21.9s
289:	learn: 0.0835937	total: 8.93s	remaining: 21.9s
290:	learn: 0.0834896	total: 8.96s	remaining: 21.8s
291:	learn: 0.0833651	total: 8.99s	remaining: 21.8s
292:	learn: 0.0832585	total: 9.02s	remaining: 21.8s
293:	learn: 0.0831563	total: 9.05s	remaining: 21.7s
294:	learn: 0.0830509	total: 9.08s	remaining: 21.7s
295:	learn: 0.0828939	total: 9.13s	remaining: 21.7s
296:	learn: 0.0827371	total: 9.16s	remaining: 21.7s
297:	learn: 0.0825979	total: 9.19s	remaining: 21.7s
298:	learn: 0.0825741	total: 9.22s	remaining: 21.6s
299:	learn: 0.0825320	total: 9.25s	remaining: 21.6s
300:	learn: 0.0825005	total: 9.29s	remaining: 21.6s
301:	learn: 0.0823973	total: 9.32s	remaining: 21.5s
302:	learn: 0.0822936	total: 9.35s	remaining: 21.5s
303:	learn: 0.0821868	total: 9.38s	remaining: 21.5s
304:	learn: 0.0821207	total: 9.41s	remaining: 21.4s
305:	learn: 0.0819154	total: 9.44s	remaining: 21.4s
306:	learn: 0.0816881	total: 9.47s	remaining: 21.4s
307:	learn: 0.0815833	total: 9.5s	remaining: 21.3s
308:	learn: 0.0814914	total: 9.53s	remaining: 21.3s
309:	learn: 0.0813991	total: 9.56s	remaining: 21.3s
310:	learn: 0.0813811	total: 9.59s	remaining: 21.2s
311:	learn: 0.0812577	total: 9.62s	remaining: 21.2s
312:	learn: 0.0812041	total: 9.65s	remaining: 21.2s
313:	learn: 0.0811584	total: 9.68s	remaining: 21.1s
314:	learn: 0.0810025	total: 9.71s	remaining: 21.1s
315:	learn: 0.0808968	total: 9.74s	remaining: 21.1s
316:	learn: 0.0808067	total: 9.77s	remaining: 21.1s
317:	learn: 0.0807198	total: 9.8s	remaining: 21s
318:	learn: 0.0806648	total: 9.84s	remaining: 21s
319:	learn: 0.0804805	total: 9.87s	remaining: 21s
320:	learn: 0.0803043	total: 9.9s	remaining: 20.9s
321:	learn: 0.0802315	total: 9.93s	remaining: 20.9s
322:	learn: 0.0801926	total: 9.96s	remaining: 20.9s
323:	learn: 0.0801039	total: 9.99s	remaining: 20.8s
324:	learn: 0.0800925	total: 10s	remaining: 20.8s
325:	learn: 0.0799632	total: 10s	remaining: 20.8s
326:	learn: 0.0797594	total: 10.1s	remaining: 20.7s
327:	learn: 0.0796944	total: 10.1s	remaining: 20.7s
328:	learn: 0.0795742	total: 10.1s	remaining: 20.7s
329:	learn: 0.0794563	total: 10.2s	remaining: 20.7s
330:	learn: 0.0794355	total: 10.2s	remaining: 20.6s
331:	learn: 0.0793472	total: 10.2s	remaining: 20.6s
332:	learn: 0.0793202	total: 10.3s	remaining: 20.6s
333:	learn: 0.0791715	total: 10.3s	remaining: 20.5s
334:	learn: 0.0790783	total: 10.3s	remaining: 20.5s
335:	learn: 0.0790510	total: 10.4s	remaining: 20.5s
336:	learn: 0.0790279	total: 10.4s	remaining: 20.5s
337:	learn: 0.0789397	total: 10.4s	remaining: 20.4s
338:	learn: 0.0788335	total: 10.5s	remaining: 20.4s
339:	learn: 0.0787506	total: 10.5s	remaining: 20.4s
340:	learn: 0.0786754	total: 10.5s	remaining: 20.3s
341:	learn: 0.0785782	total: 10.6s	remaining: 20.3s
342:	learn: 0.0784902	total: 10.6s	remaining: 20.3s
343:	learn: 0.0784741	total: 10.6s	remaining: 20.2s
344:	learn: 0.0783541	total: 10.6s	remaining: 20.2s
345:	learn: 0.0782982	total: 10.7s	remaining: 20.2s
346:	learn: 0.0782469	total: 10.7s	remaining: 20.1s
347:	learn: 0.0782191	total: 10.7s	remaining: 20.1s
348:	learn: 0.0781406	total: 10.8s	remaining: 20.1s
349:	learn: 0.0780154	total: 10.8s	remaining: 20s
350:	learn: 0.0779059	total: 10.8s	remaining: 20s
351:	learn: 0.0778669	total: 10.9s	remaining: 20s
352:	learn: 0.0778055	total: 10.9s	remaining: 20s
353:	learn: 0.0777451	total: 10.9s	remaining: 19.9s
354:	learn: 0.0775982	total: 10.9s	remaining: 19.9s
355:	learn: 0.0775050	total: 11s	remaining: 19.9s
356:	learn: 0.0774253	total: 11s	remaining: 19.8s
357:	learn: 0.0774006	total: 11s	remaining: 19.8s
358:	learn: 0.0772539	total: 11.1s	remaining: 19.8s
359:	learn: 0.0771778	total: 11.1s	remaining: 19.7s
360:	learn: 0.0771651	total: 11.1s	remaining: 19.7s
361:	learn: 0.0770333	total: 11.2s	remaining: 19.7s
362:	learn: 0.0769561	total: 11.2s	remaining: 19.7s
363:	learn: 0.0768963	total: 11.2s	remaining: 19.6s
364:	learn: 0.0767457	total: 11.3s	remaining: 19.6s
365:	learn: 0.0766988	total: 11.3s	remaining: 19.6s
366:	learn: 0.0766231	total: 11.3s	remaining: 19.6s
367:	learn: 0.0764785	total: 11.4s	remaining: 19.5s
368:	learn: 0.0763331	total: 11.4s	remaining: 19.5s
369:	learn: 0.0762242	total: 11.4s	remaining: 19.5s
370:	learn: 0.0761387	total: 11.5s	remaining: 19.4s
371:	learn: 0.0760064	total: 11.5s	remaining: 19.4s
372:	learn: 0.0759338	total: 11.5s	remaining: 19.4s
373:	learn: 0.0757962	total: 11.6s	remaining: 19.3s
374:	learn: 0.0757566	total: 11.6s	remaining: 19.3s
375:	learn: 0.0757480	total: 11.6s	remaining: 19.3s
376:	learn: 0.0756468	total: 11.7s	remaining: 19.3s
377:	learn: 0.0755771	total: 11.7s	remaining: 19.2s
378:	learn: 0.0754672	total: 11.7s	remaining: 19.2s
379:	learn: 0.0753960	total: 11.8s	remaining: 19.2s
380:	learn: 0.0753510	total: 11.8s	remaining: 19.2s
381:	learn: 0.0752789	total: 11.8s	remaining: 19.1s
382:	learn: 0.0752713	total: 11.9s	remaining: 19.1s
383:	learn: 0.0752142	total: 11.9s	remaining: 19.1s
384:	learn: 0.0751981	total: 11.9s	remaining: 19.1s
385:	learn: 0.0751429	total: 12s	remaining: 19s

CV folds:  88%|████████▊ | 44/50 [23:10<03:09, 31.56s/fold]

Learning rate set to 0.042738
0:	learn: 0.3864841	total: 28.2ms	remaining: 28.1s
1:	learn: 0.3760026	total: 57.7ms	remaining: 28.8s
2:	learn: 0.3658099	total: 91.6ms	remaining: 30.4s
3:	learn: 0.3562488	total: 124ms	remaining: 30.9s
4:	learn: 0.3467528	total: 153ms	remaining: 30.4s
5:	learn: 0.3377761	total: 184ms	remaining: 30.4s
6:	learn: 0.3285293	total: 215ms	remaining: 30.5s
7:	learn: 0.3204751	total: 249ms	remaining: 30.8s
8:	learn: 0.3125224	total: 282ms	remaining: 31s
9:	learn: 0.3043098	total: 313ms	remaining: 31s
10:	learn: 0.2967060	total: 343ms	remaining: 30.8s
11:	learn: 0.2897957	total: 374ms	remaining: 30.8s
12:	learn: 0.2831628	total: 403ms	remaining: 30.6s
13:	learn: 0.2760855	total: 434ms	remaining: 30.5s
14:	learn: 0.2696373	total: 465ms	remaining: 30.5s
15:	learn: 0.2632535	total: 494ms	remaining: 30.4s
16:	learn: 0.2575482	total: 524ms	remaining: 30.3s
17:	learn: 0.2514934	total: 554ms	remaining: 30.2s
18:	learn: 0.2463880	total: 583ms	remaining: 30.1s
19:	learn: 0.2409623	total: 610ms	remaining: 29.9s
20:	learn: 0.2358392	total: 640ms	remaining: 29.8s
21:	learn: 0.2313726	total: 671ms	remaining: 29.8s
22:	learn: 0.2271118	total: 703ms	remaining: 29.9s
23:	learn: 0.2227039	total: 730ms	remaining: 29.7s
24:	learn: 0.2186550	total: 758ms	remaining: 29.6s
25:	learn: 0.2145518	total: 788ms	remaining: 29.5s
26:	learn: 0.2104396	total: 819ms	remaining: 29.5s
27:	learn: 0.2068396	total: 851ms	remaining: 29.5s
28:	learn: 0.2031144	total: 880ms	remaining: 29.4s
29:	learn: 0.2000042	total: 911ms	remaining: 29.4s
30:	learn: 0.1967530	total: 938ms	remaining: 29.3s
31:	learn: 0.1935849	total: 966ms	remaining: 29.2s
32:	learn: 0.1905551	total: 1s	remaining: 29.5s
33:	learn: 0.1875648	total: 1.04s	remaining: 29.5s
34:	learn: 0.1848464	total: 1.07s	remaining: 29.4s
35:	learn: 0.1820762	total: 1.1s	remaining: 29.4s
36:	learn: 0.1797467	total: 1.13s	remaining: 29.4s
37:	learn: 0.1773369	total: 1.16s	remaining: 29.3s
38:	learn: 0.1750011	total: 1.18s	remaining: 29.2s
39:	learn: 0.1727503	total: 1.23s	remaining: 29.4s
40:	learn: 0.1703895	total: 1.26s	remaining: 29.4s
41:	learn: 0.1683665	total: 1.28s	remaining: 29.3s
42:	learn: 0.1661531	total: 1.31s	remaining: 29.3s
43:	learn: 0.1638602	total: 1.36s	remaining: 29.5s
44:	learn: 0.1619459	total: 1.39s	remaining: 29.5s
45:	learn: 0.1601941	total: 1.42s	remaining: 29.5s
46:	learn: 0.1583648	total: 1.45s	remaining: 29.4s
47:	learn: 0.1566991	total: 1.48s	remaining: 29.3s
48:	learn: 0.1551170	total: 1.51s	remaining: 29.3s
49:	learn: 0.1533388	total: 1.54s	remaining: 29.4s
50:	learn: 0.1517736	total: 1.57s	remaining: 29.3s
51:	learn: 0.1503664	total: 1.6s	remaining: 29.3s
52:	learn: 0.1488494	total: 1.64s	remaining: 29.2s
53:	learn: 0.1474962	total: 1.66s	remaining: 29.1s
54:	learn: 0.1461892	total: 1.69s	remaining: 29s
55:	learn: 0.1449523	total: 1.72s	remaining: 29s
56:	learn: 0.1436641	total: 1.75s	remaining: 28.9s
57:	learn: 0.1424772	total: 1.78s	remaining: 28.9s
58:	learn: 0.1412558	total: 1.81s	remaining: 28.9s
59:	learn: 0.1400222	total: 1.84s	remaining: 28.8s
60:	learn: 0.1390184	total: 1.86s	remaining: 28.7s
61:	learn: 0.1379592	total: 1.89s	remaining: 28.6s
62:	learn: 0.1368122	total: 1.92s	remaining: 28.6s
63:	learn: 0.1356967	total: 1.95s	remaining: 28.5s
64:	learn: 0.1347591	total: 1.98s	remaining: 28.5s
65:	learn: 0.1338878	total: 2.02s	remaining: 28.5s
66:	learn: 0.1328276	total: 2.04s	remaining: 28.5s
67:	learn: 0.1318045	total: 2.07s	remaining: 28.4s
68:	learn: 0.1309252	total: 2.1s	remaining: 28.4s
69:	learn: 0.1301071	total: 2.13s	remaining: 28.3s
70:	learn: 0.1293454	total: 2.16s	remaining: 28.3s
71:	learn: 0.1286205	total: 2.19s	remaining: 28.2s
72:	learn: 0.1280309	total: 2.22s	remaining: 28.2s
73:	learn: 0.1272862	total: 2.25s	remaining: 28.2s
74:	learn: 0.1266105	total: 2.29s	remaining: 28.2s
75:	learn: 0.1258336	total: 2.31s	remaining: 28.1s
76:	learn: 0.1250727	total: 2.34s	remaining: 28.1s
77:	learn: 0.1244052	total: 2.37s	remaining: 28.1s
78:	learn: 0.1238002	total: 2.4s	remaining: 28s
79:	learn: 0.1232532	total: 2.43s	remaining: 28s
80:	learn: 0.1225275	total: 2.46s	remaining: 28s
81:	learn: 0.1217590	total: 2.49s	remaining: 27.9s
82:	learn: 0.1212276	total: 2.52s	remaining: 27.9s
83:	learn: 0.1205723	total: 2.55s	remaining: 27.8s
84:	learn: 0.1201664	total: 2.58s	remaining: 27.8s
85:	learn: 0.1196557	total: 2.61s	remaining: 27.7s
86:	learn: 0.1190884	total: 2.64s	remaining: 27.7s
87:	learn: 0.1185351	total: 2.67s	remaining: 27.6s
88:	learn: 0.1180860	total: 2.7s	remaining: 27.6s
89:	learn: 0.1174938	total: 2.73s	remaining: 27.6s
90:	learn: 0.1170392	total: 2.75s	remaining: 27.5s
91:	learn: 0.1166166	total: 2.79s	remaining: 27.5s
92:	learn: 0.1162260	total: 2.81s	remaining: 27.5s
93:	learn: 0.1158293	total: 2.85s	remaining: 27.4s
94:	learn: 0.1153926	total: 2.87s	remaining: 27.4s
95:	learn: 0.1149184	total: 2.91s	remaining: 27.4s
96:	learn: 0.1145417	total: 2.94s	remaining: 27.3s
97:	learn: 0.1141125	total: 2.97s	remaining: 27.3s
98:	learn: 0.1137792	total: 3s	remaining: 27.3s
99:	learn: 0.1132333	total: 3.02s	remaining: 27.2s
100:	learn: 0.1127713	total: 3.05s	remaining: 27.2s
101:	learn: 0.1122013	total: 3.08s	remaining: 27.1s
102:	learn: 0.1116907	total: 3.11s	remaining: 27.1s
103:	learn: 0.1112700	total: 3.14s	remaining: 27s
104:	learn: 0.1109401	total: 3.17s	remaining: 27s
105:	learn: 0.1106102	total: 3.2s	remaining: 27s
106:	learn: 0.1101807	total: 3.23s	remaining: 26.9s
107:	learn: 0.1096815	total: 3.26s	remaining: 26.9s
108:	learn: 0.1092848	total: 3.29s	remaining: 26.9s
109:	learn: 0.1089076	total: 3.32s	remaining: 26.9s
110:	learn: 0.1084776	total: 3.35s	remaining: 26.9s
111:	learn: 0.1081865	total: 3.38s	remaining: 26.8s
112:	learn: 0.1079388	total: 3.41s	remaining: 26.8s
113:	learn: 0.1076776	total: 3.44s	remaining: 26.8s
114:	learn: 0.1072993	total: 3.48s	remaining: 26.7s
115:	learn: 0.1070604	total: 3.53s	remaining: 26.9s
116:	learn: 0.1067456	total: 3.56s	remaining: 26.9s
117:	learn: 0.1064296	total: 3.6s	remaining: 26.9s
118:	learn: 0.1060316	total: 3.62s	remaining: 26.8s
119:	learn: 0.1057190	total: 3.66s	remaining: 26.8s
120:	learn: 0.1053677	total: 3.69s	remaining: 26.8s
121:	learn: 0.1049153	total: 3.72s	remaining: 26.8s
122:	learn: 0.1046223	total: 3.76s	remaining: 26.8s
123:	learn: 0.1043466	total: 3.81s	remaining: 26.9s
124:	learn: 0.1040911	total: 3.85s	remaining: 26.9s
125:	learn: 0.1038227	total: 3.88s	remaining: 26.9s
126:	learn: 0.1035376	total: 3.91s	remaining: 26.9s
127:	learn: 0.1032658	total: 3.94s	remaining: 26.8s
128:	learn: 0.1029566	total: 3.97s	remaining: 26.8s
129:	learn: 0.1026855	total: 4s	remaining: 26.7s
130:	learn: 0.1023690	total: 4.03s	remaining: 26.7s
131:	learn: 0.1020456	total: 4.06s	remaining: 26.7s
132:	learn: 0.1017207	total: 4.09s	remaining: 26.6s
133:	learn: 0.1014570	total: 4.11s	remaining: 26.6s
134:	learn: 0.1011262	total: 4.14s	remaining: 26.6s
135:	learn: 0.1008985	total: 4.17s	remaining: 26.5s
136:	learn: 0.1007149	total: 4.2s	remaining: 26.5s
137:	learn: 0.1004884	total: 4.23s	remaining: 26.4s
138:	learn: 0.1003647	total: 4.26s	remaining: 26.4s
139:	learn: 0.1001776	total: 4.29s	remaining: 26.3s
140:	learn: 0.1000363	total: 4.32s	remaining: 26.3s
141:	learn: 0.0996963	total: 4.34s	remaining: 26.3s
142:	learn: 0.0995396	total: 4.37s	remaining: 26.2s
143:	learn: 0.0993873	total: 4.4s	remaining: 26.2s
144:	learn: 0.0992303	total: 4.43s	remaining: 26.2s
145:	learn: 0.0989498	total: 4.46s	remaining: 26.1s
146:	learn: 0.0987513	total: 4.5s	remaining: 26.1s
147:	learn: 0.0984599	total: 4.54s	remaining: 26.1s
148:	learn: 0.0982037	total: 4.57s	remaining: 26.1s
149:	learn: 0.0980632	total: 4.6s	remaining: 26.1s
150:	learn: 0.0979031	total: 4.63s	remaining: 26s
151:	learn: 0.0977141	total: 4.66s	remaining: 26s
152:	learn: 0.0975663	total: 4.69s	remaining: 25.9s
153:	learn: 0.0973725	total: 4.72s	remaining: 25.9s
154:	learn: 0.0972793	total: 4.75s	remaining: 25.9s
155:	learn: 0.0971117	total: 4.78s	remaining: 25.9s
156:	learn: 0.0968676	total: 4.83s	remaining: 25.9s
157:	learn: 0.0966517	total: 4.86s	remaining: 25.9s
158:	learn: 0.0965192	total: 4.89s	remaining: 25.9s
159:	learn: 0.0962676	total: 4.92s	remaining: 25.8s
160:	learn: 0.0961740	total: 4.95s	remaining: 25.8s
161:	learn: 0.0960475	total: 4.98s	remaining: 25.7s
162:	learn: 0.0959070	total: 5.01s	remaining: 25.7s
163:	learn: 0.0956412	total: 5.03s	remaining: 25.7s
164:	learn: 0.0953683	total: 5.06s	remaining: 25.6s
165:	learn: 0.0952189	total: 5.09s	remaining: 25.6s
166:	learn: 0.0950141	total: 5.12s	remaining: 25.5s
167:	learn: 0.0948798	total: 5.15s	remaining: 25.5s
168:	learn: 0.0947038	total: 5.18s	remaining: 25.5s
169:	learn: 0.0944165	total: 5.21s	remaining: 25.4s
170:	learn: 0.0941525	total: 5.24s	remaining: 25.4s
171:	learn: 0.0939537	total: 5.27s	remaining: 25.4s
172:	learn: 0.0938600	total: 5.29s	remaining: 25.3s
173:	learn: 0.0937386	total: 5.32s	remaining: 25.3s
174:	learn: 0.0935535	total: 5.35s	remaining: 25.2s
175:	learn: 0.0934030	total: 5.39s	remaining: 25.2s
176:	learn: 0.0932374	total: 5.42s	remaining: 25.2s
177:	learn: 0.0930740	total: 5.45s	remaining: 25.2s
178:	learn: 0.0929693	total: 5.48s	remaining: 25.1s
179:	learn: 0.0928250	total: 5.51s	remaining: 25.1s
180:	learn: 0.0925823	total: 5.54s	remaining: 25.1s
181:	learn: 0.0925103	total: 5.57s	remaining: 25.1s
182:	learn: 0.0923456	total: 5.6s	remaining: 25s
183:	learn: 0.0922721	total: 5.64s	remaining: 25s
184:	learn: 0.0920973	total: 5.68s	remaining: 25s
185:	learn: 0.0919574	total: 5.71s	remaining: 25s
186:	learn: 0.0918442	total: 5.74s	remaining: 25s
187:	learn: 0.0917665	total: 5.77s	remaining: 24.9s
188:	learn: 0.0916673	total: 5.8s	remaining: 24.9s
189:	learn: 0.0915946	total: 5.83s	remaining: 24.9s
190:	learn: 0.0915074	total: 5.87s	remaining: 24.8s
191:	learn: 0.0913004	total: 5.89s	remaining: 24.8s
192:	learn: 0.0912400	total: 5.92s	remaining: 24.8s
193:	learn: 0.0910963	total: 5.96s	remaining: 24.7s
194:	learn: 0.0910097	total: 5.99s	remaining: 24.7s
195:	learn: 0.0909528	total: 6.02s	remaining: 24.7s
196:	learn: 0.0908572	total: 6.05s	remaining: 24.6s
197:	learn: 0.0907906	total: 6.08s	remaining: 24.6s
198:	learn: 0.0905874	total: 6.11s	remaining: 24.6s
199:	learn: 0.0904094	total: 6.13s	remaining: 24.5s
200:	learn: 0.0902308	total: 6.16s	remaining: 24.5s
201:	learn: 0.0900304	total: 6.2s	remaining: 24.5s
202:	learn: 0.0899013	total: 6.23s	remaining: 24.4s
203:	learn: 0.0898141	total: 6.26s	remaining: 24.4s
204:	learn: 0.0897139	total: 6.29s	remaining: 24.4s
205:	learn: 0.0895476	total: 6.32s	remaining: 24.4s
206:	learn: 0.0894111	total: 6.35s	remaining: 24.3s
207:	learn: 0.0893657	total: 6.38s	remaining: 24.3s
208:	learn: 0.0892322	total: 6.41s	remaining: 24.2s
209:	learn: 0.0891578	total: 6.44s	remaining: 24.2s
210:	learn: 0.0891010	total: 6.47s	remaining: 24.2s
211:	learn: 0.0889711	total: 6.5s	remaining: 24.2s
212:	learn: 0.0889306	total: 6.54s	remaining: 24.1s
213:	learn: 0.0887829	total: 6.56s	remaining: 24.1s
214:	learn: 0.0886944	total: 6.59s	remaining: 24.1s
215:	learn: 0.0886379	total: 6.62s	remaining: 24s
216:	learn: 0.0885892	total: 6.66s	remaining: 24s
217:	learn: 0.0884674	total: 6.69s	remaining: 24s
218:	learn: 0.0882352	total: 6.72s	remaining: 24s
219:	learn: 0.0881743	total: 6.75s	remaining: 23.9s
220:	learn: 0.0880441	total: 6.78s	remaining: 23.9s
221:	learn: 0.0878719	total: 6.81s	remaining: 23.9s
222:	learn: 0.0878099	total: 6.84s	remaining: 23.8s
223:	learn: 0.0876727	total: 6.86s	remaining: 23.8s
224:	learn: 0.0876513	total: 6.89s	remaining: 23.7s
225:	learn: 0.0875948	total: 6.92s	remaining: 23.7s
226:	learn: 0.0875363	total: 6.95s	remaining: 23.7s
227:	learn: 0.0875071	total: 6.98s	remaining: 23.6s
228:	learn: 0.0873625	total: 7.01s	remaining: 23.6s
229:	learn: 0.0872731	total: 7.04s	remaining: 23.6s
230:	learn: 0.0871692	total: 7.07s	remaining: 23.6s
231:	learn: 0.0871191	total: 7.1s	remaining: 23.5s
232:	learn: 0.0870160	total: 7.14s	remaining: 23.5s
233:	learn: 0.0870045	total: 7.17s	remaining: 23.5s
234:	learn: 0.0869696	total: 7.2s	remaining: 23.4s
235:	learn: 0.0869307	total: 7.23s	remaining: 23.4s
236:	learn: 0.0868806	total: 7.26s	remaining: 23.4s
237:	learn: 0.0867586	total: 7.29s	remaining: 23.3s
238:	learn: 0.0866748	total: 7.32s	remaining: 23.3s
239:	learn: 0.0865411	total: 7.35s	remaining: 23.3s
240:	learn: 0.0865092	total: 7.38s	remaining: 23.3s
241:	learn: 0.0863542	total: 7.41s	remaining: 23.2s
242:	learn: 0.0862913	total: 7.45s	remaining: 23.2s
243:	learn: 0.0861579	total: 7.47s	remaining: 23.1s
244:	learn: 0.0861335	total: 7.5s	remaining: 23.1s
245:	learn: 0.0861124	total: 7.53s	remaining: 23.1s
246:	learn: 0.0860971	total: 7.56s	remaining: 23.1s
247:	learn: 0.0860658	total: 7.6s	remaining: 23s
248:	learn: 0.0858443	total: 7.62s	remaining: 23s
249:	learn: 0.0858028	total: 7.66s	remaining: 23s
250:	learn: 0.0857290	total: 7.68s	remaining: 22.9s
251:	learn: 0.0855911	total: 7.71s	remaining: 22.9s
252:	learn: 0.0855762	total: 7.75s	remaining: 22.9s
253:	learn: 0.0855400	total: 7.78s	remaining: 22.8s
254:	learn: 0.0853821	total: 7.82s	remaining: 22.9s
255:	learn: 0.0853588	total: 7.85s	remaining: 22.8s
256:	learn: 0.0853425	total: 7.89s	remaining: 22.8s
257:	learn: 0.0852938	total: 7.92s	remaining: 22.8s
258:	learn: 0.0851636	total: 7.95s	remaining: 22.7s
259:	learn: 0.0851363	total: 7.98s	remaining: 22.7s
260:	learn: 0.0850245	total: 8.03s	remaining: 22.7s
261:	learn: 0.0849875	total: 8.06s	remaining: 22.7s
262:	learn: 0.0849626	total: 8.1s	remaining: 22.7s
263:	learn: 0.0849086	total: 8.13s	remaining: 22.7s
264:	learn: 0.0848873	total: 8.16s	remaining: 22.6s
265:	learn: 0.0848146	total: 8.19s	remaining: 22.6s
266:	learn: 0.0847637	total: 8.22s	remaining: 22.6s
267:	learn: 0.0846776	total: 8.25s	remaining: 22.5s
268:	learn: 0.0846138	total: 8.28s	remaining: 22.5s
269:	learn: 0.0845888	total: 8.31s	remaining: 22.5s
270:	learn: 0.0844441	total: 8.33s	remaining: 22.4s
271:	learn: 0.0843327	total: 8.37s	remaining: 22.4s
272:	learn: 0.0842103	total: 8.4s	remaining: 22.4s
273:	learn: 0.0841231	total: 8.43s	remaining: 22.3s
274:	learn: 0.0841045	total: 8.46s	remaining: 22.3s
275:	learn: 0.0839637	total: 8.49s	remaining: 22.3s
276:	learn: 0.0839427	total: 8.52s	remaining: 22.2s
277:	learn: 0.0838487	total: 8.55s	remaining: 22.2s
278:	learn: 0.0837386	total: 8.58s	remaining: 22.2s
279:	learn: 0.0835996	total: 8.61s	remaining: 22.1s
280:	learn: 0.0834869	total: 8.64s	remaining: 22.1s
281:	learn: 0.0834342	total: 8.67s	remaining: 22.1s
282:	learn: 0.0833558	total: 8.7s	remaining: 22s
283:	learn: 0.0831676	total: 8.73s	remaining: 22s
284:	learn: 0.0831218	total: 8.76s	remaining: 22s
285:	learn: 0.0830027	total: 8.79s	remaining: 21.9s
286:	learn: 0.0828873	total: 8.81s	remaining: 21.9s
287:	learn: 0.0828372	total: 8.84s	remaining: 21.9s
288:	learn: 0.0827447	total: 8.87s	remaining: 21.8s
289:	learn: 0.0827318	total: 8.9s	remaining: 21.8s
290:	learn: 0.0826735	total: 8.93s	remaining: 21.8s
291:	learn: 0.0826383	total: 8.96s	remaining: 21.7s
292:	learn: 0.0824597	total: 8.99s	remaining: 21.7s
293:	learn: 0.0824306	total: 9.02s	remaining: 21.7s
294:	learn: 0.0822674	total: 9.05s	remaining: 21.6s
295:	learn: 0.0821655	total: 9.09s	remaining: 21.6s
296:	learn: 0.0819675	total: 9.12s	remaining: 21.6s
297:	learn: 0.0819523	total: 9.15s	remaining: 21.6s
298:	learn: 0.0817924	total: 9.18s	remaining: 21.5s
299:	learn: 0.0816541	total: 9.21s	remaining: 21.5s
300:	learn: 0.0815882	total: 9.24s	remaining: 21.5s
301:	learn: 0.0815011	total: 9.27s	remaining: 21.4s
302:	learn: 0.0813509	total: 9.3s	remaining: 21.4s
303:	learn: 0.0812102	total: 9.33s	remaining: 21.4s
304:	learn: 0.0811549	total: 9.37s	remaining: 21.3s
305:	learn: 0.0810281	total: 9.4s	remaining: 21.3s
306:	learn: 0.0809945	total: 9.43s	remaining: 21.3s
307:	learn: 0.0809533	total: 9.46s	remaining: 21.2s
308:	learn: 0.0808818	total: 9.49s	remaining: 21.2s
309:	learn: 0.0806694	total: 9.52s	remaining: 21.2s
310:	learn: 0.0806489	total: 9.55s	remaining: 21.2s
311:	learn: 0.0806318	total: 9.58s	remaining: 21.1s
312:	learn: 0.0806145	total: 9.61s	remaining: 21.1s
313:	learn: 0.0804974	total: 9.64s	remaining: 21.1s
314:	learn: 0.0803875	total: 9.66s	remaining: 21s
315:	learn: 0.0803215	total: 9.7s	remaining: 21s
316:	learn: 0.0802245	total: 9.73s	remaining: 21s
317:	learn: 0.0802099	total: 9.76s	remaining: 20.9s
318:	learn: 0.0801361	total: 9.8s	remaining: 20.9s
319:	learn: 0.0800619	total: 9.83s	remaining: 20.9s
320:	learn: 0.0799109	total: 9.86s	remaining: 20.8s
321:	learn: 0.0797713	total: 9.89s	remaining: 20.8s
322:	learn: 0.0797124	total: 9.91s	remaining: 20.8s
323:	learn: 0.0797049	total: 9.97s	remaining: 20.8s
324:	learn: 0.0796885	total: 10s	remaining: 20.8s
325:	learn: 0.0795898	total: 10s	remaining: 20.7s
326:	learn: 0.0795220	total: 10.1s	remaining: 20.7s
327:	learn: 0.0793918	total: 10.1s	remaining: 20.7s
328:	learn: 0.0792864	total: 10.1s	remaining: 20.6s
329:	learn: 0.0791553	total: 10.2s	remaining: 20.6s
330:	learn: 0.0790791	total: 10.2s	remaining: 20.6s
331:	learn: 0.0790587	total: 10.2s	remaining: 20.5s
332:	learn: 0.0789852	total: 10.2s	remaining: 20.5s
333:	learn: 0.0788354	total: 10.3s	remaining: 20.5s
334:	learn: 0.0787716	total: 10.3s	remaining: 20.5s
335:	learn: 0.0787142	total: 10.3s	remaining: 20.4s
336:	learn: 0.0786977	total: 10.4s	remaining: 20.4s
337:	learn: 0.0785853	total: 10.4s	remaining: 20.4s
338:	learn: 0.0784448	total: 10.4s	remaining: 20.3s
339:	learn: 0.0783508	total: 10.5s	remaining: 20.4s
340:	learn: 0.0783306	total: 10.5s	remaining: 20.3s
341:	learn: 0.0781721	total: 10.5s	remaining: 20.3s
342:	learn: 0.0780252	total: 10.6s	remaining: 20.3s
343:	learn: 0.0778680	total: 10.6s	remaining: 20.2s
344:	learn: 0.0776663	total: 10.6s	remaining: 20.2s
345:	learn: 0.0776340	total: 10.7s	remaining: 20.2s
346:	learn: 0.0775930	total: 10.7s	remaining: 20.1s
347:	learn: 0.0775275	total: 10.7s	remaining: 20.1s
348:	learn: 0.0774977	total: 10.8s	remaining: 20.1s
349:	learn: 0.0774257	total: 10.8s	remaining: 20.1s
350:	learn: 0.0774110	total: 10.8s	remaining: 20s
351:	learn: 0.0773781	total: 10.9s	remaining: 20s
352:	learn: 0.0771955	total: 10.9s	remaining: 19.9s
353:	learn: 0.0771222	total: 10.9s	remaining: 19.9s
354:	learn: 0.0771177	total: 10.9s	remaining: 19.9s
355:	learn: 0.0770331	total: 11s	remaining: 19.9s
356:	learn: 0.0770188	total: 11s	remaining: 19.8s
357:	learn: 0.0769250	total: 11s	remaining: 19.8s
358:	learn: 0.0768462	total: 11.1s	remaining: 19.8s
359:	learn: 0.0767029	total: 11.1s	remaining: 19.7s
360:	learn: 0.0766822	total: 11.1s	remaining: 19.7s
361:	learn: 0.0766710	total: 11.2s	remaining: 19.7s
362:	learn: 0.0765324	total: 11.2s	remaining: 19.6s
363:	learn: 0.0764204	total: 11.2s	remaining: 19.6s
364:	learn: 0.0763531	total: 11.3s	remaining: 19.6s
365:	learn: 0.0763067	total: 11.3s	remaining: 19.6s
366:	learn: 0.0762893	total: 11.3s	remaining: 19.6s
367:	learn: 0.0762644	total: 11.4s	remaining: 19.5s
368:	learn: 0.0761925	total: 11.4s	remaining: 19.5s
369:	learn: 0.0760828	total: 11.4s	remaining: 19.5s
370:	learn: 0.0760635	total: 11.5s	remaining: 19.4s
371:	learn: 0.0760388	total: 11.5s	remaining: 19.4s
372:	learn: 0.0759493	total: 11.5s	remaining: 19.4s
373:	learn: 0.0759357	total: 11.6s	remaining: 19.3s
374:	learn: 0.0758589	total: 11.6s	remaining: 19.3s
375:	learn: 0.0757209	total: 11.6s	remaining: 19.3s
376:	learn: 0.0756995	total: 11.7s	remaining: 19.3s
377:	learn: 0.0756763	total: 11.7s	remaining: 19.2s
378:	learn: 0.0754364	total: 11.7s	remaining: 19.2s
379:	learn: 0.0754220	total: 11.7s	remaining: 19.2s
380:	learn: 0.0753923	total: 11.8s	remaining: 19.1s
381:	learn: 0.0753834	total: 11.8s	remaining: 19.1s
382:	learn: 0.0753722	total: 11.8s	remaining: 19.1s
383:	learn: 0.0752852	total: 11.9s	remaining: 19s
384:	learn: 0.0752395	total: 11.9s	remaining: 19s
385:	learn: 0.0752238	total: 11.9s	remaining: 19s
386:	learn: 0.0751878	total: 12s	remaining: 18.9s
387:	learn: 0.0750648	total: 12s	remaining: 18.9s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior1st': 1 unseen categories converted to Unseen on transform.

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior2nd': 1 unseen categories converted to Unseen on transform.

CV folds:  90%|█████████ | 45/50 [23:42<02:38, 31.65s/fold]

Learning rate set to 0.042738
0:	learn: 0.3872169	total: 24.7ms	remaining: 24.6s
1:	learn: 0.3767831	total: 76ms	remaining: 37.9s
2:	learn: 0.3663200	total: 111ms	remaining: 36.9s
3:	learn: 0.3567641	total: 139ms	remaining: 34.7s
4:	learn: 0.3472018	total: 166ms	remaining: 33.1s
5:	learn: 0.3383335	total: 194ms	remaining: 32.2s
6:	learn: 0.3297726	total: 226ms	remaining: 32.1s
7:	learn: 0.3213030	total: 269ms	remaining: 33.4s
8:	learn: 0.3132425	total: 297ms	remaining: 32.7s
9:	learn: 0.3051424	total: 327ms	remaining: 32.4s
10:	learn: 0.2976948	total: 357ms	remaining: 32.1s
11:	learn: 0.2905770	total: 387ms	remaining: 31.9s
12:	learn: 0.2832028	total: 416ms	remaining: 31.6s
13:	learn: 0.2769680	total: 443ms	remaining: 31.2s
14:	learn: 0.2704372	total: 472ms	remaining: 31s
15:	learn: 0.2643834	total: 503ms	remaining: 30.9s
16:	learn: 0.2581717	total: 531ms	remaining: 30.7s
17:	learn: 0.2522535	total: 561ms	remaining: 30.6s
18:	learn: 0.2466608	total: 588ms	remaining: 30.4s
19:	learn: 0.2418103	total: 616ms	remaining: 30.2s
20:	learn: 0.2369027	total: 647ms	remaining: 30.2s
21:	learn: 0.2320663	total: 679ms	remaining: 30.2s
22:	learn: 0.2275003	total: 711ms	remaining: 30.2s
23:	learn: 0.2232762	total: 744ms	remaining: 30.2s
24:	learn: 0.2187825	total: 771ms	remaining: 30.1s
25:	learn: 0.2145392	total: 804ms	remaining: 30.1s
26:	learn: 0.2107759	total: 832ms	remaining: 30s
27:	learn: 0.2071287	total: 862ms	remaining: 29.9s
28:	learn: 0.2038085	total: 895ms	remaining: 30s
29:	learn: 0.2001330	total: 935ms	remaining: 30.2s
30:	learn: 0.1969103	total: 966ms	remaining: 30.2s
31:	learn: 0.1940406	total: 995ms	remaining: 30.1s
32:	learn: 0.1911377	total: 1.03s	remaining: 30.1s
33:	learn: 0.1880805	total: 1.06s	remaining: 30.1s
34:	learn: 0.1852774	total: 1.09s	remaining: 30s
35:	learn: 0.1825020	total: 1.12s	remaining: 30.1s
36:	learn: 0.1802011	total: 1.15s	remaining: 30s
37:	learn: 0.1777379	total: 1.19s	remaining: 30s
38:	learn: 0.1753076	total: 1.22s	remaining: 30s
39:	learn: 0.1728272	total: 1.25s	remaining: 29.9s
40:	learn: 0.1705346	total: 1.27s	remaining: 29.8s
41:	learn: 0.1683292	total: 1.3s	remaining: 29.7s
42:	learn: 0.1663697	total: 1.33s	remaining: 29.6s
43:	learn: 0.1643344	total: 1.36s	remaining: 29.5s
44:	learn: 0.1626591	total: 1.39s	remaining: 29.5s
45:	learn: 0.1609322	total: 1.42s	remaining: 29.4s
46:	learn: 0.1592035	total: 1.45s	remaining: 29.4s
47:	learn: 0.1573978	total: 1.48s	remaining: 29.3s
48:	learn: 0.1556894	total: 1.51s	remaining: 29.3s
49:	learn: 0.1540501	total: 1.54s	remaining: 29.2s
50:	learn: 0.1527008	total: 1.57s	remaining: 29.2s
51:	learn: 0.1512836	total: 1.6s	remaining: 29.1s
52:	learn: 0.1497342	total: 1.63s	remaining: 29.1s
53:	learn: 0.1482234	total: 1.66s	remaining: 29s
54:	learn: 0.1470752	total: 1.69s	remaining: 29s
55:	learn: 0.1459277	total: 1.72s	remaining: 29s
56:	learn: 0.1445891	total: 1.75s	remaining: 29s
57:	learn: 0.1433229	total: 1.78s	remaining: 28.9s
58:	learn: 0.1421268	total: 1.81s	remaining: 28.9s
59:	learn: 0.1412142	total: 1.84s	remaining: 28.8s
60:	learn: 0.1400427	total: 1.87s	remaining: 28.8s
61:	learn: 0.1389338	total: 1.9s	remaining: 28.8s
62:	learn: 0.1379903	total: 1.93s	remaining: 28.7s
63:	learn: 0.1369416	total: 1.96s	remaining: 28.6s
64:	learn: 0.1357460	total: 1.99s	remaining: 28.6s
65:	learn: 0.1348187	total: 2.02s	remaining: 28.5s
66:	learn: 0.1339259	total: 2.07s	remaining: 28.8s
67:	learn: 0.1331068	total: 2.1s	remaining: 28.7s
68:	learn: 0.1323826	total: 2.13s	remaining: 28.8s
69:	learn: 0.1316254	total: 2.16s	remaining: 28.7s
70:	learn: 0.1309349	total: 2.19s	remaining: 28.7s
71:	learn: 0.1301429	total: 2.22s	remaining: 28.6s
72:	learn: 0.1294433	total: 2.25s	remaining: 28.6s
73:	learn: 0.1287300	total: 2.28s	remaining: 28.5s
74:	learn: 0.1280072	total: 2.31s	remaining: 28.5s
75:	learn: 0.1273095	total: 2.34s	remaining: 28.4s
76:	learn: 0.1265192	total: 2.37s	remaining: 28.4s
77:	learn: 0.1258268	total: 2.39s	remaining: 28.3s
78:	learn: 0.1252207	total: 2.42s	remaining: 28.3s
79:	learn: 0.1245765	total: 2.45s	remaining: 28.2s
80:	learn: 0.1241038	total: 2.49s	remaining: 28.2s
81:	learn: 0.1233912	total: 2.52s	remaining: 28.2s
82:	learn: 0.1226889	total: 2.55s	remaining: 28.2s
83:	learn: 0.1220915	total: 2.58s	remaining: 28.2s
84:	learn: 0.1213699	total: 2.61s	remaining: 28.1s
85:	learn: 0.1207465	total: 2.64s	remaining: 28s
86:	learn: 0.1203248	total: 2.67s	remaining: 28s
87:	learn: 0.1198487	total: 2.7s	remaining: 27.9s
88:	learn: 0.1192280	total: 2.73s	remaining: 27.9s
89:	learn: 0.1187265	total: 2.76s	remaining: 27.9s
90:	learn: 0.1182609	total: 2.79s	remaining: 27.9s
91:	learn: 0.1178546	total: 2.82s	remaining: 27.9s
92:	learn: 0.1175397	total: 2.85s	remaining: 27.8s
93:	learn: 0.1171012	total: 2.88s	remaining: 27.8s
94:	learn: 0.1166511	total: 2.91s	remaining: 27.8s
95:	learn: 0.1163086	total: 2.94s	remaining: 27.7s
96:	learn: 0.1159351	total: 2.98s	remaining: 27.7s
97:	learn: 0.1154671	total: 3s	remaining: 27.6s
98:	learn: 0.1151412	total: 3.03s	remaining: 27.6s
99:	learn: 0.1148567	total: 3.06s	remaining: 27.5s
100:	learn: 0.1145586	total: 3.09s	remaining: 27.5s
101:	learn: 0.1141741	total: 3.12s	remaining: 27.4s
102:	learn: 0.1137528	total: 3.15s	remaining: 27.4s
103:	learn: 0.1135204	total: 3.17s	remaining: 27.3s
104:	learn: 0.1131749	total: 3.19s	remaining: 27.2s
105:	learn: 0.1129010	total: 3.22s	remaining: 27.2s
106:	learn: 0.1124874	total: 3.25s	remaining: 27.1s
107:	learn: 0.1121139	total: 3.28s	remaining: 27.1s
108:	learn: 0.1117423	total: 3.31s	remaining: 27.1s
109:	learn: 0.1113654	total: 3.34s	remaining: 27s
110:	learn: 0.1111407	total: 3.38s	remaining: 27s
111:	learn: 0.1107728	total: 3.4s	remaining: 27s
112:	learn: 0.1104377	total: 3.44s	remaining: 27s
113:	learn: 0.1102080	total: 3.46s	remaining: 26.9s
114:	learn: 0.1100312	total: 3.49s	remaining: 26.9s
115:	learn: 0.1096267	total: 3.52s	remaining: 26.8s
116:	learn: 0.1094439	total: 3.55s	remaining: 26.8s
117:	learn: 0.1091578	total: 3.58s	remaining: 26.7s
118:	learn: 0.1089225	total: 3.61s	remaining: 26.7s
119:	learn: 0.1086268	total: 3.66s	remaining: 26.8s
120:	learn: 0.1083422	total: 3.7s	remaining: 26.9s
121:	learn: 0.1081598	total: 3.73s	remaining: 26.8s
122:	learn: 0.1079201	total: 3.76s	remaining: 26.8s
123:	learn: 0.1076896	total: 3.79s	remaining: 26.8s
124:	learn: 0.1073884	total: 3.82s	remaining: 26.7s
125:	learn: 0.1070146	total: 3.85s	remaining: 26.7s
126:	learn: 0.1067305	total: 3.88s	remaining: 26.7s
127:	learn: 0.1065187	total: 3.91s	remaining: 26.6s
128:	learn: 0.1064155	total: 3.94s	remaining: 26.6s
129:	learn: 0.1060448	total: 3.97s	remaining: 26.6s
130:	learn: 0.1058356	total: 4s	remaining: 26.5s
131:	learn: 0.1055745	total: 4.02s	remaining: 26.4s
132:	learn: 0.1053504	total: 4.05s	remaining: 26.4s
133:	learn: 0.1051787	total: 4.08s	remaining: 26.4s
134:	learn: 0.1049899	total: 4.11s	remaining: 26.3s
135:	learn: 0.1047753	total: 4.14s	remaining: 26.3s
136:	learn: 0.1044859	total: 4.17s	remaining: 26.3s
137:	learn: 0.1043497	total: 4.21s	remaining: 26.3s
138:	learn: 0.1041022	total: 4.25s	remaining: 26.3s
139:	learn: 0.1038744	total: 4.28s	remaining: 26.3s
140:	learn: 0.1035826	total: 4.31s	remaining: 26.3s
141:	learn: 0.1033553	total: 4.35s	remaining: 26.3s
142:	learn: 0.1031092	total: 4.38s	remaining: 26.3s
143:	learn: 0.1029170	total: 4.41s	remaining: 26.2s
144:	learn: 0.1026619	total: 4.44s	remaining: 26.2s
145:	learn: 0.1023954	total: 4.47s	remaining: 26.1s
146:	learn: 0.1022707	total: 4.5s	remaining: 26.1s
147:	learn: 0.1020175	total: 4.53s	remaining: 26.1s
148:	learn: 0.1017405	total: 4.56s	remaining: 26s
149:	learn: 0.1015803	total: 4.59s	remaining: 26s
150:	learn: 0.1014195	total: 4.62s	remaining: 26s
151:	learn: 0.1012682	total: 4.65s	remaining: 25.9s
152:	learn: 0.1010928	total: 4.68s	remaining: 25.9s
153:	learn: 0.1009446	total: 4.71s	remaining: 25.9s
154:	learn: 0.1007702	total: 4.74s	remaining: 25.8s
155:	learn: 0.1004070	total: 4.77s	remaining: 25.8s
156:	learn: 0.1002963	total: 4.8s	remaining: 25.8s
157:	learn: 0.1001883	total: 4.83s	remaining: 25.8s
158:	learn: 0.1000965	total: 4.87s	remaining: 25.7s
159:	learn: 0.0999471	total: 4.91s	remaining: 25.8s
160:	learn: 0.0996949	total: 4.94s	remaining: 25.7s
161:	learn: 0.0995744	total: 4.97s	remaining: 25.7s
162:	learn: 0.0994308	total: 5s	remaining: 25.7s
163:	learn: 0.0992701	total: 5.03s	remaining: 25.6s
164:	learn: 0.0991647	total: 5.06s	remaining: 25.6s
165:	learn: 0.0989938	total: 5.09s	remaining: 25.6s
166:	learn: 0.0988292	total: 5.12s	remaining: 25.5s
167:	learn: 0.0987117	total: 5.15s	remaining: 25.5s
168:	learn: 0.0985148	total: 5.18s	remaining: 25.5s
169:	learn: 0.0983873	total: 5.21s	remaining: 25.5s
170:	learn: 0.0982028	total: 5.25s	remaining: 25.4s
171:	learn: 0.0979851	total: 5.27s	remaining: 25.4s
172:	learn: 0.0978792	total: 5.3s	remaining: 25.3s
173:	learn: 0.0976825	total: 5.33s	remaining: 25.3s
174:	learn: 0.0974814	total: 5.36s	remaining: 25.3s
175:	learn: 0.0973022	total: 5.39s	remaining: 25.2s
176:	learn: 0.0972020	total: 5.42s	remaining: 25.2s
177:	learn: 0.0970975	total: 5.45s	remaining: 25.2s
178:	learn: 0.0969459	total: 5.48s	remaining: 25.1s
179:	learn: 0.0968273	total: 5.51s	remaining: 25.1s
180:	learn: 0.0967166	total: 5.54s	remaining: 25.1s
181:	learn: 0.0965677	total: 5.57s	remaining: 25s
182:	learn: 0.0964161	total: 5.6s	remaining: 25s
183:	learn: 0.0962921	total: 5.63s	remaining: 25s
184:	learn: 0.0962239	total: 5.66s	remaining: 24.9s
185:	learn: 0.0961536	total: 5.69s	remaining: 24.9s
186:	learn: 0.0959652	total: 5.72s	remaining: 24.9s
187:	learn: 0.0958728	total: 5.76s	remaining: 24.9s
188:	learn: 0.0957770	total: 5.79s	remaining: 24.8s
189:	learn: 0.0956640	total: 5.82s	remaining: 24.8s
190:	learn: 0.0954767	total: 5.84s	remaining: 24.8s
191:	learn: 0.0953084	total: 5.87s	remaining: 24.7s
192:	learn: 0.0950785	total: 5.9s	remaining: 24.7s
193:	learn: 0.0949510	total: 5.93s	remaining: 24.6s
194:	learn: 0.0949191	total: 5.96s	remaining: 24.6s
195:	learn: 0.0947316	total: 6s	remaining: 24.6s
196:	learn: 0.0946246	total: 6.03s	remaining: 24.6s
197:	learn: 0.0943835	total: 6.06s	remaining: 24.5s
198:	learn: 0.0943054	total: 6.09s	remaining: 24.5s
199:	learn: 0.0942299	total: 6.12s	remaining: 24.5s
200:	learn: 0.0941622	total: 6.14s	remaining: 24.4s
201:	learn: 0.0940185	total: 6.18s	remaining: 24.4s
202:	learn: 0.0939483	total: 6.21s	remaining: 24.4s
203:	learn: 0.0938709	total: 6.24s	remaining: 24.3s
204:	learn: 0.0937046	total: 6.26s	remaining: 24.3s
205:	learn: 0.0935179	total: 6.29s	remaining: 24.3s
206:	learn: 0.0933274	total: 6.32s	remaining: 24.2s
207:	learn: 0.0931602	total: 6.36s	remaining: 24.2s
208:	learn: 0.0930239	total: 6.39s	remaining: 24.2s
209:	learn: 0.0929584	total: 6.42s	remaining: 24.2s
210:	learn: 0.0928485	total: 6.45s	remaining: 24.1s
211:	learn: 0.0927402	total: 6.48s	remaining: 24.1s
212:	learn: 0.0926555	total: 6.51s	remaining: 24s
213:	learn: 0.0925919	total: 6.54s	remaining: 24s
214:	learn: 0.0924687	total: 6.57s	remaining: 24s
215:	learn: 0.0922679	total: 6.59s	remaining: 23.9s
216:	learn: 0.0922088	total: 6.63s	remaining: 23.9s
217:	learn: 0.0920958	total: 6.66s	remaining: 23.9s
218:	learn: 0.0920277	total: 6.69s	remaining: 23.9s
219:	learn: 0.0919765	total: 6.72s	remaining: 23.8s
220:	learn: 0.0918824	total: 6.75s	remaining: 23.8s
221:	learn: 0.0917547	total: 6.78s	remaining: 23.7s
222:	learn: 0.0916666	total: 6.81s	remaining: 23.7s
223:	learn: 0.0915716	total: 6.84s	remaining: 23.7s
224:	learn: 0.0914488	total: 6.87s	remaining: 23.7s
225:	learn: 0.0912911	total: 6.9s	remaining: 23.6s
226:	learn: 0.0912665	total: 6.93s	remaining: 23.6s
227:	learn: 0.0911463	total: 6.96s	remaining: 23.6s
228:	learn: 0.0910751	total: 6.99s	remaining: 23.5s
229:	learn: 0.0909722	total: 7.02s	remaining: 23.5s
230:	learn: 0.0908786	total: 7.05s	remaining: 23.5s
231:	learn: 0.0908487	total: 7.08s	remaining: 23.4s
232:	learn: 0.0908362	total: 7.11s	remaining: 23.4s
233:	learn: 0.0907141	total: 7.14s	remaining: 23.4s
234:	learn: 0.0906718	total: 7.17s	remaining: 23.3s
235:	learn: 0.0906072	total: 7.2s	remaining: 23.3s
236:	learn: 0.0905395	total: 7.23s	remaining: 23.3s
237:	learn: 0.0904272	total: 7.25s	remaining: 23.2s
238:	learn: 0.0903224	total: 7.29s	remaining: 23.2s
239:	learn: 0.0902922	total: 7.32s	remaining: 23.2s
240:	learn: 0.0901747	total: 7.34s	remaining: 23.1s
241:	learn: 0.0900929	total: 7.38s	remaining: 23.1s
242:	learn: 0.0899658	total: 7.41s	remaining: 23.1s
243:	learn: 0.0899305	total: 7.44s	remaining: 23s
244:	learn: 0.0898844	total: 7.47s	remaining: 23s
245:	learn: 0.0898659	total: 7.5s	remaining: 23s
246:	learn: 0.0898148	total: 7.53s	remaining: 23s
247:	learn: 0.0897658	total: 7.56s	remaining: 22.9s
248:	learn: 0.0897418	total: 7.59s	remaining: 22.9s
249:	learn: 0.0896097	total: 7.62s	remaining: 22.9s
250:	learn: 0.0895492	total: 7.65s	remaining: 22.8s
251:	learn: 0.0894924	total: 7.68s	remaining: 22.8s
252:	learn: 0.0894070	total: 7.71s	remaining: 22.8s
253:	learn: 0.0893407	total: 7.75s	remaining: 22.8s
254:	learn: 0.0892359	total: 7.78s	remaining: 22.7s
255:	learn: 0.0890371	total: 7.8s	remaining: 22.7s
256:	learn: 0.0888629	total: 7.83s	remaining: 22.6s
257:	learn: 0.0886856	total: 7.86s	remaining: 22.6s
258:	learn: 0.0885552	total: 7.89s	remaining: 22.6s
259:	learn: 0.0884834	total: 7.92s	remaining: 22.6s
260:	learn: 0.0883403	total: 7.95s	remaining: 22.5s
261:	learn: 0.0881807	total: 7.98s	remaining: 22.5s
262:	learn: 0.0879848	total: 8.02s	remaining: 22.5s
263:	learn: 0.0879006	total: 8.05s	remaining: 22.4s
264:	learn: 0.0878722	total: 8.08s	remaining: 22.4s
265:	learn: 0.0876417	total: 8.11s	remaining: 22.4s
266:	learn: 0.0875587	total: 8.13s	remaining: 22.3s
267:	learn: 0.0874080	total: 8.16s	remaining: 22.3s
268:	learn: 0.0872434	total: 8.19s	remaining: 22.3s
269:	learn: 0.0871629	total: 8.22s	remaining: 22.2s
270:	learn: 0.0871225	total: 8.25s	remaining: 22.2s
271:	learn: 0.0870336	total: 8.29s	remaining: 22.2s
272:	learn: 0.0869895	total: 8.32s	remaining: 22.1s
273:	learn: 0.0869556	total: 8.35s	remaining: 22.1s
274:	learn: 0.0867960	total: 8.38s	remaining: 22.1s
275:	learn: 0.0867699	total: 8.41s	remaining: 22.1s
276:	learn: 0.0866504	total: 8.44s	remaining: 22s
277:	learn: 0.0865290	total: 8.47s	remaining: 22s
278:	learn: 0.0865061	total: 8.51s	remaining: 22s
279:	learn: 0.0864818	total: 8.55s	remaining: 22s
280:	learn: 0.0863904	total: 8.58s	remaining: 21.9s
281:	learn: 0.0862307	total: 8.61s	remaining: 21.9s
282:	learn: 0.0861816	total: 8.63s	remaining: 21.9s
283:	learn: 0.0861259	total: 8.66s	remaining: 21.8s
284:	learn: 0.0860447	total: 8.71s	remaining: 21.8s
285:	learn: 0.0859203	total: 8.74s	remaining: 21.8s
286:	learn: 0.0857292	total: 8.77s	remaining: 21.8s
287:	learn: 0.0855452	total: 8.8s	remaining: 21.8s
288:	learn: 0.0854618	total: 8.83s	remaining: 21.7s
289:	learn: 0.0853086	total: 8.86s	remaining: 21.7s
290:	learn: 0.0852258	total: 8.89s	remaining: 21.7s
291:	learn: 0.0851858	total: 8.92s	remaining: 21.6s
292:	learn: 0.0850200	total: 8.95s	remaining: 21.6s
293:	learn: 0.0850074	total: 8.98s	remaining: 21.6s
294:	learn: 0.0849772	total: 9.01s	remaining: 21.5s
295:	learn: 0.0849607	total: 9.03s	remaining: 21.5s
296:	learn: 0.0848271	total: 9.06s	remaining: 21.4s
297:	learn: 0.0848058	total: 9.09s	remaining: 21.4s
298:	learn: 0.0846271	total: 9.12s	remaining: 21.4s
299:	learn: 0.0844142	total: 9.15s	remaining: 21.4s
300:	learn: 0.0843192	total: 9.18s	remaining: 21.3s
301:	learn: 0.0841358	total: 9.21s	remaining: 21.3s
302:	learn: 0.0839451	total: 9.24s	remaining: 21.3s
303:	learn: 0.0838582	total: 9.27s	remaining: 21.2s
304:	learn: 0.0836845	total: 9.3s	remaining: 21.2s
305:	learn: 0.0836455	total: 9.32s	remaining: 21.1s
306:	learn: 0.0835428	total: 9.35s	remaining: 21.1s
307:	learn: 0.0832987	total: 9.38s	remaining: 21.1s
308:	learn: 0.0832554	total: 9.41s	remaining: 21.1s
309:	learn: 0.0832365	total: 9.45s	remaining: 21s
310:	learn: 0.0831827	total: 9.48s	remaining: 21s
311:	learn: 0.0831673	total: 9.51s	remaining: 21s
312:	learn: 0.0830670	total: 9.54s	remaining: 20.9s
313:	learn: 0.0829526	total: 9.57s	remaining: 20.9s
314:	learn: 0.0828206	total: 9.6s	remaining: 20.9s
315:	learn: 0.0826988	total: 9.63s	remaining: 20.8s
316:	learn: 0.0826798	total: 9.66s	remaining: 20.8s
317:	learn: 0.0825614	total: 9.69s	remaining: 20.8s
318:	learn: 0.0824623	total: 9.72s	remaining: 20.7s
319:	learn: 0.0823679	total: 9.75s	remaining: 20.7s
320:	learn: 0.0822724	total: 9.78s	remaining: 20.7s
321:	learn: 0.0821554	total: 9.81s	remaining: 20.7s
322:	learn: 0.0821113	total: 9.84s	remaining: 20.6s
323:	learn: 0.0820898	total: 9.87s	remaining: 20.6s
324:	learn: 0.0819153	total: 9.9s	remaining: 20.6s
325:	learn: 0.0818956	total: 9.93s	remaining: 20.5s
326:	learn: 0.0818712	total: 9.96s	remaining: 20.5s
327:	learn: 0.0817270	total: 9.99s	remaining: 20.5s
328:	learn: 0.0815592	total: 10s	remaining: 20.4s
329:	learn: 0.0815368	total: 10s	remaining: 20.4s
330:	learn: 0.0815160	total: 10.1s	remaining: 20.4s
331:	learn: 0.0814241	total: 10.1s	remaining: 20.3s
332:	learn: 0.0814136	total: 10.1s	remaining: 20.3s
333:	learn: 0.0812825	total: 10.2s	remaining: 20.3s
334:	learn: 0.0811078	total: 10.2s	remaining: 20.2s
335:	learn: 0.0810916	total: 10.2s	remaining: 20.2s
336:	learn: 0.0809345	total: 10.3s	remaining: 20.2s
337:	learn: 0.0808655	total: 10.3s	remaining: 20.2s
338:	learn: 0.0807199	total: 10.3s	remaining: 20.1s
339:	learn: 0.0806930	total: 10.4s	remaining: 20.1s
340:	learn: 0.0804611	total: 10.4s	remaining: 20.1s
341:	learn: 0.0803497	total: 10.4s	remaining: 20s
342:	learn: 0.0801769	total: 10.4s	remaining: 20s
343:	learn: 0.0801625	total: 10.5s	remaining: 20s
344:	learn: 0.0801366	total: 10.5s	remaining: 19.9s
345:	learn: 0.0800028	total: 10.5s	remaining: 19.9s
346:	learn: 0.0799490	total: 10.6s	remaining: 19.9s
347:	learn: 0.0799274	total: 10.6s	remaining: 19.8s
348:	learn: 0.0798603	total: 10.6s	remaining: 19.8s
349:	learn: 0.0798370	total: 10.7s	remaining: 19.8s
350:	learn: 0.0796830	total: 10.7s	remaining: 19.8s
351:	learn: 0.0795540	total: 10.7s	remaining: 19.8s
352:	learn: 0.0794662	total: 10.8s	remaining: 19.7s
353:	learn: 0.0794469	total: 10.8s	remaining: 19.7s
354:	learn: 0.0793301	total: 10.8s	remaining: 19.7s
355:	learn: 0.0792936	total: 10.9s	remaining: 19.6s
356:	learn: 0.0792112	total: 10.9s	remaining: 19.6s
357:	learn: 0.0790517	total: 10.9s	remaining: 19.6s
358:	learn: 0.0790295	total: 10.9s	remaining: 19.5s
359:	learn: 0.0789373	total: 11s	remaining: 19.5s
360:	learn: 0.0788784	total: 11s	remaining: 19.5s
361:	learn: 0.0787429	total: 11s	remaining: 19.4s
362:	learn: 0.0787170	total: 11.1s	remaining: 19.4s
363:	learn: 0.0785793	total: 11.1s	remaining: 19.4s
364:	learn: 0.0784933	total: 11.1s	remaining: 19.3s
365:	learn: 0.0783894	total: 11.2s	remaining: 19.3s
366:	learn: 0.0783176	total: 11.2s	remaining: 19.3s
367:	learn: 0.0782878	total: 11.2s	remaining: 19.3s
368:	learn: 0.0782094	total: 11.2s	remaining: 19.2s
369:	learn: 0.0781793	total: 11.3s	remaining: 19.2s
370:	learn: 0.0781595	total: 11.3s	remaining: 19.2s
371:	learn: 0.0780280	total: 11.3s	remaining: 19.1s
372:	learn: 0.0778751	total: 11.4s	remaining: 19.1s
373:	learn: 0.0777534	total: 11.4s	remaining: 19.1s
374:	learn: 0.0776889	total: 11.4s	remaining: 19s
375:	learn: 0.0776675	total: 11.5s	remaining: 19s
376:	learn: 0.0776196	total: 11.5s	remaining: 19s
377:	learn: 0.0775447	total: 11.5s	remaining: 18.9s
378:	learn: 0.0774628	total: 11.5s	remaining: 18.9s
379:	learn: 0.0773977	total: 11.6s	remaining: 18.9s
380:	learn: 0.0773116	total: 11.6s	remaining: 18.9s
381:	learn: 0.0771788	total: 11.6s	remaining: 18.8s
382:	learn: 0.0771002	total: 11.7s	remaining: 18.8s
383:	learn: 0.0770856	total: 11.7s	remaining: 18.8s
384:	learn: 0.0770595	total: 11.7s	remaining: 18.7s
385:	learn: 0.0770099	total: 11.8s	remaining: 18.7s
386:	learn: 0.0769530	total: 11.8s	remaining: 18.7s
387:	learn: 0.0767440	total: 11.8s	remaining: 18.6s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior1st': 1 unseen categories converted to Unseen on transform.

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'ExterCond': 1 unseen categories converted to Unseen on transform.

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'HeatingQC': 1 unseen categories converted to Unseen on transform.

CV folds:  92%|█████████▏| 46/50 [24:13<02:06, 31.51s/fold]

Learning rate set to 0.042738
0:	learn: 0.3889766	total: 25.2ms	remaining: 25.2s
1:	learn: 0.3785636	total: 54.3ms	remaining: 27.1s
2:	learn: 0.3681529	total: 86ms	remaining: 28.6s
3:	learn: 0.3588463	total: 115ms	remaining: 28.6s
4:	learn: 0.3495981	total: 145ms	remaining: 28.8s
5:	learn: 0.3406947	total: 171ms	remaining: 28.4s
6:	learn: 0.3321203	total: 203ms	remaining: 28.8s
7:	learn: 0.3235158	total: 233ms	remaining: 28.9s
8:	learn: 0.3154098	total: 304ms	remaining: 33.4s
9:	learn: 0.3076234	total: 329ms	remaining: 32.6s
10:	learn: 0.2998153	total: 353ms	remaining: 31.8s
11:	learn: 0.2919582	total: 378ms	remaining: 31.1s
12:	learn: 0.2852730	total: 407ms	remaining: 30.9s
13:	learn: 0.2786836	total: 436ms	remaining: 30.7s
14:	learn: 0.2721767	total: 468ms	remaining: 30.7s
15:	learn: 0.2666145	total: 507ms	remaining: 31.2s
16:	learn: 0.2608617	total: 527ms	remaining: 30.5s
17:	learn: 0.2550150	total: 559ms	remaining: 30.5s
18:	learn: 0.2494146	total: 594ms	remaining: 30.7s
19:	learn: 0.2444821	total: 624ms	remaining: 30.6s
20:	learn: 0.2396047	total: 652ms	remaining: 30.4s
21:	learn: 0.2348240	total: 679ms	remaining: 30.2s
22:	learn: 0.2302735	total: 710ms	remaining: 30.1s
23:	learn: 0.2259101	total: 742ms	remaining: 30.2s
24:	learn: 0.2214710	total: 772ms	remaining: 30.1s
25:	learn: 0.2174659	total: 798ms	remaining: 29.9s
26:	learn: 0.2133382	total: 826ms	remaining: 29.8s
27:	learn: 0.2096275	total: 858ms	remaining: 29.8s
28:	learn: 0.2063010	total: 887ms	remaining: 29.7s
29:	learn: 0.2030790	total: 917ms	remaining: 29.6s
30:	learn: 0.1996495	total: 962ms	remaining: 30.1s
31:	learn: 0.1959059	total: 992ms	remaining: 30s
32:	learn: 0.1930340	total: 1.02s	remaining: 30s
33:	learn: 0.1902919	total: 1.05s	remaining: 29.9s
34:	learn: 0.1872210	total: 1.08s	remaining: 29.8s
35:	learn: 0.1844069	total: 1.11s	remaining: 29.7s
36:	learn: 0.1816738	total: 1.14s	remaining: 29.7s
37:	learn: 0.1790402	total: 1.17s	remaining: 29.6s
38:	learn: 0.1766490	total: 1.2s	remaining: 29.5s
39:	learn: 0.1740422	total: 1.23s	remaining: 29.5s
40:	learn: 0.1718785	total: 1.27s	remaining: 29.8s
41:	learn: 0.1697497	total: 1.3s	remaining: 29.6s
42:	learn: 0.1677235	total: 1.33s	remaining: 29.6s
43:	learn: 0.1656244	total: 1.36s	remaining: 29.5s
44:	learn: 0.1635006	total: 1.39s	remaining: 29.5s
45:	learn: 0.1613453	total: 1.42s	remaining: 29.4s
46:	learn: 0.1596007	total: 1.45s	remaining: 29.3s
47:	learn: 0.1578672	total: 1.47s	remaining: 29.2s
48:	learn: 0.1562415	total: 1.5s	remaining: 29.1s
49:	learn: 0.1546477	total: 1.53s	remaining: 29.1s
50:	learn: 0.1531204	total: 1.56s	remaining: 29.1s
51:	learn: 0.1513736	total: 1.59s	remaining: 29s
52:	learn: 0.1499857	total: 1.62s	remaining: 29s
53:	learn: 0.1484884	total: 1.65s	remaining: 28.9s
54:	learn: 0.1471857	total: 1.68s	remaining: 28.9s
55:	learn: 0.1456992	total: 1.71s	remaining: 28.8s
56:	learn: 0.1444274	total: 1.74s	remaining: 28.8s
57:	learn: 0.1431456	total: 1.77s	remaining: 28.8s
58:	learn: 0.1419407	total: 1.81s	remaining: 28.8s
59:	learn: 0.1407034	total: 1.84s	remaining: 28.8s
60:	learn: 0.1396134	total: 1.87s	remaining: 28.8s
61:	learn: 0.1383824	total: 1.9s	remaining: 28.7s
62:	learn: 0.1371985	total: 1.93s	remaining: 28.7s
63:	learn: 0.1363773	total: 1.96s	remaining: 28.6s
64:	learn: 0.1354233	total: 1.99s	remaining: 28.6s
65:	learn: 0.1348346	total: 2.01s	remaining: 28.5s
66:	learn: 0.1337593	total: 2.04s	remaining: 28.5s
67:	learn: 0.1327681	total: 2.11s	remaining: 28.9s
68:	learn: 0.1316661	total: 2.14s	remaining: 28.9s
69:	learn: 0.1306834	total: 2.17s	remaining: 28.9s
70:	learn: 0.1300771	total: 2.21s	remaining: 28.9s
71:	learn: 0.1293515	total: 2.24s	remaining: 28.8s
72:	learn: 0.1286459	total: 2.27s	remaining: 28.8s
73:	learn: 0.1277736	total: 2.3s	remaining: 28.7s
74:	learn: 0.1269274	total: 2.32s	remaining: 28.7s
75:	learn: 0.1261648	total: 2.35s	remaining: 28.6s
76:	learn: 0.1254243	total: 2.38s	remaining: 28.6s
77:	learn: 0.1246845	total: 2.41s	remaining: 28.5s
78:	learn: 0.1240910	total: 2.44s	remaining: 28.5s
79:	learn: 0.1234530	total: 2.47s	remaining: 28.4s
80:	learn: 0.1228712	total: 2.51s	remaining: 28.4s
81:	learn: 0.1223067	total: 2.54s	remaining: 28.4s
82:	learn: 0.1216830	total: 2.57s	remaining: 28.4s
83:	learn: 0.1211168	total: 2.6s	remaining: 28.3s
84:	learn: 0.1205353	total: 2.63s	remaining: 28.3s
85:	learn: 0.1200288	total: 2.66s	remaining: 28.3s
86:	learn: 0.1193112	total: 2.69s	remaining: 28.2s
87:	learn: 0.1187090	total: 2.72s	remaining: 28.2s
88:	learn: 0.1181911	total: 2.75s	remaining: 28.1s
89:	learn: 0.1176722	total: 2.78s	remaining: 28.1s
90:	learn: 0.1172038	total: 2.81s	remaining: 28.1s
91:	learn: 0.1165461	total: 2.84s	remaining: 28s
92:	learn: 0.1160507	total: 2.87s	remaining: 28s
93:	learn: 0.1156973	total: 2.9s	remaining: 27.9s
94:	learn: 0.1151878	total: 2.92s	remaining: 27.8s
95:	learn: 0.1147836	total: 2.95s	remaining: 27.8s
96:	learn: 0.1142416	total: 2.98s	remaining: 27.8s
97:	learn: 0.1138658	total: 3.01s	remaining: 27.7s
98:	learn: 0.1135017	total: 3.04s	remaining: 27.6s
99:	learn: 0.1130569	total: 3.07s	remaining: 27.6s
100:	learn: 0.1127030	total: 3.1s	remaining: 27.6s
101:	learn: 0.1123439	total: 3.13s	remaining: 27.5s
102:	learn: 0.1119979	total: 3.16s	remaining: 27.5s
103:	learn: 0.1115590	total: 3.19s	remaining: 27.4s
104:	learn: 0.1111693	total: 3.21s	remaining: 27.4s
105:	learn: 0.1107606	total: 3.25s	remaining: 27.4s
106:	learn: 0.1104004	total: 3.28s	remaining: 27.3s
107:	learn: 0.1101444	total: 3.31s	remaining: 27.3s
108:	learn: 0.1098018	total: 3.34s	remaining: 27.3s
109:	learn: 0.1094690	total: 3.37s	remaining: 27.3s
110:	learn: 0.1092234	total: 3.41s	remaining: 27.3s
111:	learn: 0.1088425	total: 3.44s	remaining: 27.3s
112:	learn: 0.1085776	total: 3.47s	remaining: 27.3s
113:	learn: 0.1082882	total: 3.5s	remaining: 27.2s
114:	learn: 0.1079543	total: 3.54s	remaining: 27.2s
115:	learn: 0.1076672	total: 3.57s	remaining: 27.2s
116:	learn: 0.1074807	total: 3.6s	remaining: 27.2s
117:	learn: 0.1071613	total: 3.63s	remaining: 27.1s
118:	learn: 0.1068908	total: 3.66s	remaining: 27.1s
119:	learn: 0.1064730	total: 3.68s	remaining: 27s
120:	learn: 0.1061509	total: 3.71s	remaining: 27s
121:	learn: 0.1057777	total: 3.75s	remaining: 27s
122:	learn: 0.1055423	total: 3.78s	remaining: 26.9s
123:	learn: 0.1053456	total: 3.81s	remaining: 26.9s
124:	learn: 0.1050745	total: 3.84s	remaining: 26.9s
125:	learn: 0.1049422	total: 3.85s	remaining: 26.7s
126:	learn: 0.1046200	total: 3.88s	remaining: 26.7s
127:	learn: 0.1044137	total: 3.91s	remaining: 26.7s
128:	learn: 0.1041890	total: 3.94s	remaining: 26.6s
129:	learn: 0.1039717	total: 3.98s	remaining: 26.6s
130:	learn: 0.1037180	total: 4s	remaining: 26.6s
131:	learn: 0.1034888	total: 4.03s	remaining: 26.5s
132:	learn: 0.1032583	total: 4.06s	remaining: 26.5s
133:	learn: 0.1029704	total: 4.09s	remaining: 26.4s
134:	learn: 0.1027890	total: 4.12s	remaining: 26.4s
135:	learn: 0.1025174	total: 4.15s	remaining: 26.4s
136:	learn: 0.1023149	total: 4.18s	remaining: 26.3s
137:	learn: 0.1021475	total: 4.21s	remaining: 26.3s
138:	learn: 0.1019517	total: 4.24s	remaining: 26.3s
139:	learn: 0.1017202	total: 4.27s	remaining: 26.2s
140:	learn: 0.1016158	total: 4.29s	remaining: 26.2s
141:	learn: 0.1014390	total: 4.32s	remaining: 26.1s
142:	learn: 0.1011761	total: 4.35s	remaining: 26.1s
143:	learn: 0.1010348	total: 4.38s	remaining: 26.1s
144:	learn: 0.1008039	total: 4.42s	remaining: 26s
145:	learn: 0.1005328	total: 4.45s	remaining: 26s
146:	learn: 0.1003469	total: 4.48s	remaining: 26s
147:	learn: 0.1001634	total: 4.51s	remaining: 25.9s
148:	learn: 0.0999533	total: 4.54s	remaining: 25.9s
149:	learn: 0.0996948	total: 4.57s	remaining: 25.9s
150:	learn: 0.0994331	total: 4.6s	remaining: 25.9s
151:	learn: 0.0991959	total: 4.63s	remaining: 25.8s
152:	learn: 0.0990070	total: 4.66s	remaining: 25.8s
153:	learn: 0.0986199	total: 4.69s	remaining: 25.8s
154:	learn: 0.0984163	total: 4.73s	remaining: 25.8s
155:	learn: 0.0980787	total: 4.76s	remaining: 25.7s
156:	learn: 0.0979616	total: 4.79s	remaining: 25.7s
157:	learn: 0.0977649	total: 4.82s	remaining: 25.7s
158:	learn: 0.0975507	total: 4.84s	remaining: 25.6s
159:	learn: 0.0973946	total: 4.88s	remaining: 25.6s
160:	learn: 0.0971782	total: 4.9s	remaining: 25.6s
161:	learn: 0.0969678	total: 4.93s	remaining: 25.5s
162:	learn: 0.0967919	total: 4.96s	remaining: 25.5s
163:	learn: 0.0965796	total: 4.99s	remaining: 25.4s
164:	learn: 0.0964672	total: 5.02s	remaining: 25.4s
165:	learn: 0.0962855	total: 5.05s	remaining: 25.4s
166:	learn: 0.0960524	total: 5.08s	remaining: 25.3s
167:	learn: 0.0958979	total: 5.11s	remaining: 25.3s
168:	learn: 0.0957380	total: 5.14s	remaining: 25.3s
169:	learn: 0.0956333	total: 5.17s	remaining: 25.2s
170:	learn: 0.0955206	total: 5.2s	remaining: 25.2s
171:	learn: 0.0953345	total: 5.23s	remaining: 25.2s
172:	learn: 0.0950717	total: 5.27s	remaining: 25.2s
173:	learn: 0.0949055	total: 5.3s	remaining: 25.2s
174:	learn: 0.0947608	total: 5.33s	remaining: 25.1s
175:	learn: 0.0945863	total: 5.36s	remaining: 25.1s
176:	learn: 0.0943446	total: 5.39s	remaining: 25.1s
177:	learn: 0.0940672	total: 5.42s	remaining: 25s
178:	learn: 0.0938705	total: 5.45s	remaining: 25s
179:	learn: 0.0936735	total: 5.48s	remaining: 25s
180:	learn: 0.0935451	total: 5.51s	remaining: 24.9s
181:	learn: 0.0934967	total: 5.54s	remaining: 24.9s
182:	learn: 0.0933387	total: 5.59s	remaining: 24.9s
183:	learn: 0.0932135	total: 5.61s	remaining: 24.9s
184:	learn: 0.0929913	total: 5.64s	remaining: 24.9s
185:	learn: 0.0928250	total: 5.68s	remaining: 24.8s
186:	learn: 0.0927928	total: 5.71s	remaining: 24.8s
187:	learn: 0.0927082	total: 5.73s	remaining: 24.8s
188:	learn: 0.0925230	total: 5.76s	remaining: 24.7s
189:	learn: 0.0924211	total: 5.79s	remaining: 24.7s
190:	learn: 0.0922490	total: 5.82s	remaining: 24.7s
191:	learn: 0.0920228	total: 5.85s	remaining: 24.6s
192:	learn: 0.0918646	total: 5.88s	remaining: 24.6s
193:	learn: 0.0916741	total: 5.91s	remaining: 24.6s
194:	learn: 0.0915950	total: 5.94s	remaining: 24.5s
195:	learn: 0.0914530	total: 5.97s	remaining: 24.5s
196:	learn: 0.0913181	total: 6s	remaining: 24.5s
197:	learn: 0.0912481	total: 6.04s	remaining: 24.5s
198:	learn: 0.0911642	total: 6.07s	remaining: 24.5s
199:	learn: 0.0910678	total: 6.11s	remaining: 24.4s
200:	learn: 0.0910276	total: 6.14s	remaining: 24.4s
201:	learn: 0.0909043	total: 6.17s	remaining: 24.4s
202:	learn: 0.0908709	total: 6.2s	remaining: 24.3s
203:	learn: 0.0906250	total: 6.23s	remaining: 24.3s
204:	learn: 0.0904776	total: 6.26s	remaining: 24.3s
205:	learn: 0.0903722	total: 6.29s	remaining: 24.3s
206:	learn: 0.0901605	total: 6.32s	remaining: 24.2s
207:	learn: 0.0901005	total: 6.35s	remaining: 24.2s
208:	learn: 0.0898314	total: 6.38s	remaining: 24.1s
209:	learn: 0.0898099	total: 6.41s	remaining: 24.1s
210:	learn: 0.0896360	total: 6.44s	remaining: 24.1s
211:	learn: 0.0894293	total: 6.47s	remaining: 24s
212:	learn: 0.0893431	total: 6.5s	remaining: 24s
213:	learn: 0.0892138	total: 6.53s	remaining: 24s
214:	learn: 0.0890422	total: 6.56s	remaining: 24s
215:	learn: 0.0889558	total: 6.59s	remaining: 23.9s
216:	learn: 0.0888177	total: 6.63s	remaining: 23.9s
217:	learn: 0.0887551	total: 6.65s	remaining: 23.9s
218:	learn: 0.0887108	total: 6.68s	remaining: 23.8s
219:	learn: 0.0886034	total: 6.72s	remaining: 23.8s
220:	learn: 0.0885423	total: 6.75s	remaining: 23.8s
221:	learn: 0.0885209	total: 6.77s	remaining: 23.7s
222:	learn: 0.0884464	total: 6.81s	remaining: 23.7s
223:	learn: 0.0884113	total: 6.84s	remaining: 23.7s
224:	learn: 0.0883612	total: 6.88s	remaining: 23.7s
225:	learn: 0.0882906	total: 6.91s	remaining: 23.7s
226:	learn: 0.0882051	total: 6.95s	remaining: 23.6s
227:	learn: 0.0880452	total: 6.97s	remaining: 23.6s
228:	learn: 0.0879332	total: 7s	remaining: 23.6s
229:	learn: 0.0878782	total: 7.03s	remaining: 23.5s
230:	learn: 0.0878568	total: 7.06s	remaining: 23.5s
231:	learn: 0.0878355	total: 7.09s	remaining: 23.5s
232:	learn: 0.0877371	total: 7.12s	remaining: 23.4s
233:	learn: 0.0875948	total: 7.15s	remaining: 23.4s
234:	learn: 0.0875464	total: 7.18s	remaining: 23.4s
235:	learn: 0.0874386	total: 7.2s	remaining: 23.3s
236:	learn: 0.0874076	total: 7.24s	remaining: 23.3s
237:	learn: 0.0873027	total: 7.27s	remaining: 23.3s
238:	learn: 0.0872880	total: 7.3s	remaining: 23.2s
239:	learn: 0.0872430	total: 7.33s	remaining: 23.2s
240:	learn: 0.0871084	total: 7.36s	remaining: 23.2s
241:	learn: 0.0870398	total: 7.39s	remaining: 23.1s
242:	learn: 0.0869630	total: 7.42s	remaining: 23.1s
243:	learn: 0.0869494	total: 7.45s	remaining: 23.1s
244:	learn: 0.0867571	total: 7.48s	remaining: 23.1s
245:	learn: 0.0866456	total: 7.51s	remaining: 23s
246:	learn: 0.0865025	total: 7.55s	remaining: 23s
247:	learn: 0.0864746	total: 7.58s	remaining: 23s
248:	learn: 0.0864476	total: 7.61s	remaining: 23s
249:	learn: 0.0863698	total: 7.64s	remaining: 22.9s
250:	learn: 0.0862574	total: 7.67s	remaining: 22.9s
251:	learn: 0.0862293	total: 7.71s	remaining: 22.9s
252:	learn: 0.0861779	total: 7.76s	remaining: 22.9s
253:	learn: 0.0859418	total: 7.79s	remaining: 22.9s
254:	learn: 0.0859101	total: 7.82s	remaining: 22.8s
255:	learn: 0.0857392	total: 7.85s	remaining: 22.8s
256:	learn: 0.0855469	total: 7.88s	remaining: 22.8s
257:	learn: 0.0852996	total: 7.91s	remaining: 22.7s
258:	learn: 0.0852640	total: 7.94s	remaining: 22.7s
259:	learn: 0.0851065	total: 7.97s	remaining: 22.7s
260:	learn: 0.0849164	total: 8s	remaining: 22.6s
261:	learn: 0.0848901	total: 8.03s	remaining: 22.6s
262:	learn: 0.0847940	total: 8.06s	remaining: 22.6s
263:	learn: 0.0847775	total: 8.09s	remaining: 22.6s
264:	learn: 0.0847186	total: 8.12s	remaining: 22.5s
265:	learn: 0.0846123	total: 8.15s	remaining: 22.5s
266:	learn: 0.0845433	total: 8.18s	remaining: 22.5s
267:	learn: 0.0845244	total: 8.22s	remaining: 22.4s
268:	learn: 0.0844489	total: 8.24s	remaining: 22.4s
269:	learn: 0.0843799	total: 8.27s	remaining: 22.4s
270:	learn: 0.0843630	total: 8.3s	remaining: 22.3s
271:	learn: 0.0843268	total: 8.34s	remaining: 22.3s
272:	learn: 0.0842860	total: 8.37s	remaining: 22.3s
273:	learn: 0.0842623	total: 8.4s	remaining: 22.3s
274:	learn: 0.0842489	total: 8.43s	remaining: 22.2s
275:	learn: 0.0840253	total: 8.46s	remaining: 22.2s
276:	learn: 0.0838950	total: 8.49s	remaining: 22.2s
277:	learn: 0.0838710	total: 8.52s	remaining: 22.1s
278:	learn: 0.0838476	total: 8.55s	remaining: 22.1s
279:	learn: 0.0838200	total: 8.59s	remaining: 22.1s
280:	learn: 0.0837882	total: 8.62s	remaining: 22s
281:	learn: 0.0837583	total: 8.65s	remaining: 22s
282:	learn: 0.0836349	total: 8.68s	remaining: 22s
283:	learn: 0.0835570	total: 8.71s	remaining: 22s
284:	learn: 0.0835439	total: 8.74s	remaining: 21.9s
285:	learn: 0.0834198	total: 8.77s	remaining: 21.9s
286:	learn: 0.0832869	total: 8.81s	remaining: 21.9s
287:	learn: 0.0832067	total: 8.84s	remaining: 21.9s
288:	learn: 0.0831861	total: 8.87s	remaining: 21.8s
289:	learn: 0.0831757	total: 8.9s	remaining: 21.8s
290:	learn: 0.0829590	total: 8.93s	remaining: 21.8s
291:	learn: 0.0829439	total: 8.96s	remaining: 21.7s
292:	learn: 0.0827541	total: 8.99s	remaining: 21.7s
293:	learn: 0.0826168	total: 9.02s	remaining: 21.7s
294:	learn: 0.0825679	total: 9.05s	remaining: 21.6s
295:	learn: 0.0825427	total: 9.07s	remaining: 21.6s
296:	learn: 0.0824617	total: 9.11s	remaining: 21.6s
297:	learn: 0.0824446	total: 9.14s	remaining: 21.5s
298:	learn: 0.0822326	total: 9.17s	remaining: 21.5s
299:	learn: 0.0820899	total: 9.2s	remaining: 21.5s
300:	learn: 0.0819303	total: 9.23s	remaining: 21.4s
301:	learn: 0.0819154	total: 9.26s	remaining: 21.4s
302:	learn: 0.0817740	total: 9.29s	remaining: 21.4s
303:	learn: 0.0817542	total: 9.32s	remaining: 21.3s
304:	learn: 0.0816197	total: 9.35s	remaining: 21.3s
305:	learn: 0.0815912	total: 9.38s	remaining: 21.3s
306:	learn: 0.0815308	total: 9.42s	remaining: 21.3s
307:	learn: 0.0814174	total: 9.45s	remaining: 21.2s
308:	learn: 0.0813933	total: 9.48s	remaining: 21.2s
309:	learn: 0.0813764	total: 9.51s	remaining: 21.2s
310:	learn: 0.0813116	total: 9.54s	remaining: 21.1s
311:	learn: 0.0812975	total: 9.57s	remaining: 21.1s
312:	learn: 0.0811510	total: 9.62s	remaining: 21.1s
313:	learn: 0.0811301	total: 9.65s	remaining: 21.1s
314:	learn: 0.0810318	total: 9.68s	remaining: 21s
315:	learn: 0.0809754	total: 9.71s	remaining: 21s
316:	learn: 0.0809668	total: 9.74s	remaining: 21s
317:	learn: 0.0809526	total: 9.77s	remaining: 21s
318:	learn: 0.0808787	total: 9.8s	remaining: 20.9s
319:	learn: 0.0808310	total: 9.83s	remaining: 20.9s
320:	learn: 0.0807220	total: 9.88s	remaining: 20.9s
321:	learn: 0.0805859	total: 9.93s	remaining: 20.9s
322:	learn: 0.0805331	total: 9.96s	remaining: 20.9s
323:	learn: 0.0805177	total: 9.99s	remaining: 20.8s
324:	learn: 0.0804420	total: 10s	remaining: 20.8s
325:	learn: 0.0803158	total: 10s	remaining: 20.8s
326:	learn: 0.0801608	total: 10.1s	remaining: 20.7s
327:	learn: 0.0801418	total: 10.1s	remaining: 20.7s
328:	learn: 0.0801228	total: 10.1s	remaining: 20.7s
329:	learn: 0.0799886	total: 10.2s	remaining: 20.6s
330:	learn: 0.0798293	total: 10.2s	remaining: 20.6s
331:	learn: 0.0798135	total: 10.2s	remaining: 20.6s
332:	learn: 0.0797547	total: 10.2s	remaining: 20.5s
333:	learn: 0.0797201	total: 10.3s	remaining: 20.5s
334:	learn: 0.0797071	total: 10.3s	remaining: 20.5s
335:	learn: 0.0796206	total: 10.3s	remaining: 20.4s
336:	learn: 0.0795526	total: 10.4s	remaining: 20.4s
337:	learn: 0.0795371	total: 10.4s	remaining: 20.4s
338:	learn: 0.0793691	total: 10.4s	remaining: 20.3s
339:	learn: 0.0792989	total: 10.5s	remaining: 20.3s
340:	learn: 0.0792908	total: 10.5s	remaining: 20.3s
341:	learn: 0.0792252	total: 10.5s	remaining: 20.3s
342:	learn: 0.0791324	total: 10.6s	remaining: 20.2s
343:	learn: 0.0789507	total: 10.6s	remaining: 20.2s
344:	learn: 0.0788864	total: 10.6s	remaining: 20.2s
345:	learn: 0.0788006	total: 10.7s	remaining: 20.1s
346:	learn: 0.0786224	total: 10.7s	remaining: 20.1s
347:	learn: 0.0785766	total: 10.7s	remaining: 20.1s
348:	learn: 0.0784614	total: 10.7s	remaining: 20s
349:	learn: 0.0784323	total: 10.8s	remaining: 20s
350:	learn: 0.0783965	total: 10.8s	remaining: 20s
351:	learn: 0.0782508	total: 10.8s	remaining: 19.9s
352:	learn: 0.0782285	total: 10.9s	remaining: 19.9s
353:	learn: 0.0782130	total: 10.9s	remaining: 19.9s
354:	learn: 0.0780958	total: 10.9s	remaining: 19.8s
355:	learn: 0.0780785	total: 11s	remaining: 19.8s
356:	learn: 0.0779905	total: 11s	remaining: 19.8s
357:	learn: 0.0779438	total: 11s	remaining: 19.8s
358:	learn: 0.0779302	total: 11.1s	remaining: 19.8s
359:	learn: 0.0777716	total: 11.1s	remaining: 19.7s
360:	learn: 0.0776444	total: 11.1s	remaining: 19.7s
361:	learn: 0.0775215	total: 11.2s	remaining: 19.7s
362:	learn: 0.0774644	total: 11.2s	remaining: 19.6s
363:	learn: 0.0773659	total: 11.2s	remaining: 19.6s
364:	learn: 0.0773601	total: 11.2s	remaining: 19.6s
365:	learn: 0.0771890	total: 11.3s	remaining: 19.5s
366:	learn: 0.0771706	total: 11.3s	remaining: 19.5s
367:	learn: 0.0771634	total: 11.3s	remaining: 19.5s
368:	learn: 0.0770793	total: 11.4s	remaining: 19.4s
369:	learn: 0.0770312	total: 11.4s	remaining: 19.4s
370:	learn: 0.0769981	total: 11.4s	remaining: 19.4s
371:	learn: 0.0769868	total: 11.5s	remaining: 19.4s
372:	learn: 0.0769316	total: 11.5s	remaining: 19.3s
373:	learn: 0.0768034	total: 11.5s	remaining: 19.3s
374:	learn: 0.0767871	total: 11.6s	remaining: 19.3s
375:	learn: 0.0767035	total: 11.6s	remaining: 19.2s
376:	learn: 0.0766213	total: 11.6s	remaining: 19.2s
377:	learn: 0.0765697	total: 11.7s	remaining: 19.2s
378:	learn: 0.0765046	total: 11.7s	remaining: 19.1s
379:	learn: 0.0764389	total: 11.7s	remaining: 19.1s
380:	learn: 0.0764217	total: 11.7s	remaining: 19.1s
381:	learn: 0.0762786	total: 11.8s	remaining: 19s
382:	learn: 0.0762683	total: 11.8s	remaining: 19s
383:	learn: 0.0761267	total: 11.8s	remaining: 19s
384:	learn: 0.0761085	total: 11.9s	remaining: 18.9s
385:	learn: 0.0760945	total: 11.9s	remaining: 18.9s
386:	learn: 0.0759516	total: 11.9s	remaining: 18.9s
387:	learn: 0.0759350	total: 11.9s	remaining: 18.8s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Functional': 1 unseen categories converted to Unseen on transform.

CV folds:  94%|█████████▍| 47/50 [24:44<01:34, 31.42s/fold]

999:	learn: 0.0444003	total: 30.7s	remaining: 0us
Learning rate set to 0.042738
0:	learn: 0.3883448	total: 24.5ms	remaining: 24.5s
1:	learn: 0.3778127	total: 57.3ms	remaining: 28.6s
2:	learn: 0.3671556	total: 86.1ms	remaining: 28.6s
3:	learn: 0.3578318	total: 116ms	remaining: 29s
4:	learn: 0.3483051	total: 148ms	remaining: 29.4s
5:	learn: 0.3392391	total: 175ms	remaining: 29s
6:	learn: 0.3306326	total: 206ms	remaining: 29.2s
7:	learn: 0.3225601	total: 238ms	remaining: 29.5s
8:	learn: 0.3143022	total: 270ms	remaining: 29.7s
9:	learn: 0.3060216	total: 304ms	remaining: 30.1s
10:	learn: 0.2980589	total: 334ms	remaining: 30.1s
11:	learn: 0.2905617	total: 373ms	remaining: 30.7s
12:	learn: 0.2839391	total: 408ms	remaining: 31s
13:	learn: 0.2773013	total: 441ms	remaining: 31s
14:	learn: 0.2709875	total: 469ms	remaining: 30.8s
15:	learn: 0.2652147	total: 498ms	remaining: 30.6s
16:	learn: 0.2590740	total: 528ms	remaining: 30.5s
17:	learn: 0.2531881	total: 555ms	remaining: 30.3s
18:	learn: 0.2474517	total: 583ms	remaining: 30.1s
19:	learn: 0.2424052	total: 613ms	remaining: 30.1s
20:	learn: 0.2373282	total: 642ms	remaining: 29.9s
21:	learn: 0.2325308	total: 671ms	remaining: 29.8s
22:	learn: 0.2274706	total: 703ms	remaining: 29.9s
23:	learn: 0.2233469	total: 732ms	remaining: 29.8s
24:	learn: 0.2188967	total: 759ms	remaining: 29.6s
25:	learn: 0.2150413	total: 788ms	remaining: 29.5s
26:	learn: 0.2108254	total: 818ms	remaining: 29.5s
27:	learn: 0.2068603	total: 845ms	remaining: 29.3s
28:	learn: 0.2032420	total: 875ms	remaining: 29.3s
29:	learn: 0.1997686	total: 906ms	remaining: 29.3s
30:	learn: 0.1959868	total: 935ms	remaining: 29.2s
31:	learn: 0.1927440	total: 963ms	remaining: 29.1s
32:	learn: 0.1896866	total: 990ms	remaining: 29s
33:	learn: 0.1868542	total: 1.02s	remaining: 29s
34:	learn: 0.1837149	total: 1.04s	remaining: 28.8s
35:	learn: 0.1808177	total: 1.07s	remaining: 28.8s
36:	learn: 0.1782096	total: 1.1s	remaining: 28.8s
37:	learn: 0.1754774	total: 1.14s	remaining: 28.8s
38:	learn: 0.1729397	total: 1.17s	remaining: 28.7s
39:	learn: 0.1706459	total: 1.19s	remaining: 28.6s
40:	learn: 0.1682369	total: 1.23s	remaining: 28.7s
41:	learn: 0.1658550	total: 1.28s	remaining: 29.1s
42:	learn: 0.1637072	total: 1.3s	remaining: 29.1s
43:	learn: 0.1616389	total: 1.34s	remaining: 29.1s
44:	learn: 0.1597626	total: 1.37s	remaining: 29.1s
45:	learn: 0.1581118	total: 1.4s	remaining: 29.1s
46:	learn: 0.1560115	total: 1.43s	remaining: 29s
47:	learn: 0.1540716	total: 1.46s	remaining: 28.9s
48:	learn: 0.1523937	total: 1.49s	remaining: 28.8s
49:	learn: 0.1507732	total: 1.51s	remaining: 28.8s
50:	learn: 0.1494948	total: 1.54s	remaining: 28.8s
51:	learn: 0.1480494	total: 1.58s	remaining: 28.7s
52:	learn: 0.1467312	total: 1.6s	remaining: 28.7s
53:	learn: 0.1453517	total: 1.64s	remaining: 28.7s
54:	learn: 0.1437712	total: 1.67s	remaining: 28.6s
55:	learn: 0.1426035	total: 1.7s	remaining: 28.6s
56:	learn: 0.1412850	total: 1.73s	remaining: 28.6s
57:	learn: 0.1401588	total: 1.75s	remaining: 28.5s
58:	learn: 0.1388864	total: 1.78s	remaining: 28.4s
59:	learn: 0.1378205	total: 1.81s	remaining: 28.4s
60:	learn: 0.1367971	total: 1.84s	remaining: 28.3s
61:	learn: 0.1357450	total: 1.87s	remaining: 28.3s
62:	learn: 0.1346526	total: 1.9s	remaining: 28.3s
63:	learn: 0.1336313	total: 1.93s	remaining: 28.2s
64:	learn: 0.1326886	total: 1.95s	remaining: 28.1s
65:	learn: 0.1317675	total: 1.98s	remaining: 28.1s
66:	learn: 0.1310339	total: 2.01s	remaining: 28.1s
67:	learn: 0.1303002	total: 2.04s	remaining: 28s
68:	learn: 0.1294159	total: 2.07s	remaining: 28s
69:	learn: 0.1284609	total: 2.1s	remaining: 27.9s
70:	learn: 0.1275886	total: 2.13s	remaining: 27.9s
71:	learn: 0.1268650	total: 2.16s	remaining: 27.8s
72:	learn: 0.1262013	total: 2.19s	remaining: 27.8s
73:	learn: 0.1254432	total: 2.22s	remaining: 27.8s
74:	learn: 0.1248699	total: 2.25s	remaining: 27.8s
75:	learn: 0.1242328	total: 2.28s	remaining: 27.7s
76:	learn: 0.1236798	total: 2.31s	remaining: 27.7s
77:	learn: 0.1231084	total: 2.34s	remaining: 27.7s
78:	learn: 0.1223015	total: 2.37s	remaining: 27.7s
79:	learn: 0.1216151	total: 2.4s	remaining: 27.6s
80:	learn: 0.1211084	total: 2.43s	remaining: 27.6s
81:	learn: 0.1205664	total: 2.46s	remaining: 27.5s
82:	learn: 0.1199549	total: 2.49s	remaining: 27.5s
83:	learn: 0.1194546	total: 2.54s	remaining: 27.7s
84:	learn: 0.1189261	total: 2.57s	remaining: 27.7s
85:	learn: 0.1184501	total: 2.6s	remaining: 27.6s
86:	learn: 0.1177845	total: 2.63s	remaining: 27.6s
87:	learn: 0.1174056	total: 2.66s	remaining: 27.6s
88:	learn: 0.1168759	total: 2.69s	remaining: 27.5s
89:	learn: 0.1162999	total: 2.72s	remaining: 27.5s
90:	learn: 0.1158232	total: 2.75s	remaining: 27.5s
91:	learn: 0.1152245	total: 2.78s	remaining: 27.4s
92:	learn: 0.1146546	total: 2.81s	remaining: 27.4s
93:	learn: 0.1142219	total: 2.84s	remaining: 27.3s
94:	learn: 0.1139426	total: 2.87s	remaining: 27.3s
95:	learn: 0.1136269	total: 2.89s	remaining: 27.3s
96:	learn: 0.1131893	total: 2.92s	remaining: 27.2s
97:	learn: 0.1128023	total: 2.96s	remaining: 27.2s
98:	learn: 0.1124431	total: 2.98s	remaining: 27.2s
99:	learn: 0.1120139	total: 3.02s	remaining: 27.1s
100:	learn: 0.1117071	total: 3.04s	remaining: 27.1s
101:	learn: 0.1113260	total: 3.07s	remaining: 27.1s
102:	learn: 0.1109547	total: 3.1s	remaining: 27s
103:	learn: 0.1105919	total: 3.14s	remaining: 27s
104:	learn: 0.1100993	total: 3.17s	remaining: 27s
105:	learn: 0.1096897	total: 3.2s	remaining: 27s
106:	learn: 0.1092880	total: 3.23s	remaining: 27s
107:	learn: 0.1090135	total: 3.26s	remaining: 27s
108:	learn: 0.1087006	total: 3.31s	remaining: 27.1s
109:	learn: 0.1084194	total: 3.34s	remaining: 27s
110:	learn: 0.1081251	total: 3.37s	remaining: 27s
111:	learn: 0.1078013	total: 3.4s	remaining: 27s
112:	learn: 0.1074167	total: 3.43s	remaining: 26.9s
113:	learn: 0.1071602	total: 3.48s	remaining: 27s
114:	learn: 0.1068991	total: 3.51s	remaining: 27s
115:	learn: 0.1066329	total: 3.53s	remaining: 26.9s
116:	learn: 0.1063570	total: 3.56s	remaining: 26.9s
117:	learn: 0.1060186	total: 3.59s	remaining: 26.9s
118:	learn: 0.1056344	total: 3.62s	remaining: 26.8s
119:	learn: 0.1053501	total: 3.65s	remaining: 26.8s
120:	learn: 0.1050730	total: 3.68s	remaining: 26.8s
121:	learn: 0.1047533	total: 3.71s	remaining: 26.7s
122:	learn: 0.1044619	total: 3.74s	remaining: 26.7s
123:	learn: 0.1043059	total: 3.77s	remaining: 26.6s
124:	learn: 0.1041063	total: 3.8s	remaining: 26.6s
125:	learn: 0.1038715	total: 3.83s	remaining: 26.6s
126:	learn: 0.1036395	total: 3.86s	remaining: 26.5s
127:	learn: 0.1033760	total: 3.89s	remaining: 26.5s
128:	learn: 0.1031152	total: 3.92s	remaining: 26.5s
129:	learn: 0.1029009	total: 3.95s	remaining: 26.4s
130:	learn: 0.1026772	total: 3.98s	remaining: 26.4s
131:	learn: 0.1024567	total: 4s	remaining: 26.3s
132:	learn: 0.1021528	total: 4.03s	remaining: 26.3s
133:	learn: 0.1018969	total: 4.06s	remaining: 26.3s
134:	learn: 0.1016470	total: 4.09s	remaining: 26.2s
135:	learn: 0.1012931	total: 4.12s	remaining: 26.2s
136:	learn: 0.1011216	total: 4.16s	remaining: 26.2s
137:	learn: 0.1008647	total: 4.19s	remaining: 26.2s
138:	learn: 0.1005528	total: 4.22s	remaining: 26.1s
139:	learn: 0.1002591	total: 4.25s	remaining: 26.1s
140:	learn: 0.1001405	total: 4.28s	remaining: 26.1s
141:	learn: 0.0999806	total: 4.31s	remaining: 26s
142:	learn: 0.0997462	total: 4.34s	remaining: 26s
143:	learn: 0.0994581	total: 4.37s	remaining: 26s
144:	learn: 0.0991248	total: 4.4s	remaining: 26s
145:	learn: 0.0988903	total: 4.43s	remaining: 25.9s
146:	learn: 0.0985896	total: 4.46s	remaining: 25.9s
147:	learn: 0.0983005	total: 4.5s	remaining: 25.9s
148:	learn: 0.0980708	total: 4.53s	remaining: 25.9s
149:	learn: 0.0978598	total: 4.56s	remaining: 25.9s
150:	learn: 0.0975744	total: 4.59s	remaining: 25.8s
151:	learn: 0.0973644	total: 4.62s	remaining: 25.8s
152:	learn: 0.0971821	total: 4.65s	remaining: 25.7s
153:	learn: 0.0970026	total: 4.7s	remaining: 25.8s
154:	learn: 0.0967259	total: 4.72s	remaining: 25.8s
155:	learn: 0.0964189	total: 4.75s	remaining: 25.7s
156:	learn: 0.0962357	total: 4.78s	remaining: 25.7s
157:	learn: 0.0960921	total: 4.82s	remaining: 25.7s
158:	learn: 0.0958536	total: 4.84s	remaining: 25.6s
159:	learn: 0.0955467	total: 4.87s	remaining: 25.6s
160:	learn: 0.0953227	total: 4.9s	remaining: 25.6s
161:	learn: 0.0950842	total: 4.93s	remaining: 25.5s
162:	learn: 0.0949152	total: 4.96s	remaining: 25.5s
163:	learn: 0.0947034	total: 4.99s	remaining: 25.5s
164:	learn: 0.0944653	total: 5.02s	remaining: 25.4s
165:	learn: 0.0943140	total: 5.05s	remaining: 25.4s
166:	learn: 0.0942139	total: 5.08s	remaining: 25.4s
167:	learn: 0.0940305	total: 5.12s	remaining: 25.4s
168:	learn: 0.0937641	total: 5.15s	remaining: 25.3s
169:	learn: 0.0936675	total: 5.18s	remaining: 25.3s
170:	learn: 0.0935332	total: 5.22s	remaining: 25.3s
171:	learn: 0.0933217	total: 5.26s	remaining: 25.3s
172:	learn: 0.0931678	total: 5.29s	remaining: 25.3s
173:	learn: 0.0930441	total: 5.33s	remaining: 25.3s
174:	learn: 0.0929542	total: 5.36s	remaining: 25.3s
175:	learn: 0.0927940	total: 5.39s	remaining: 25.3s
176:	learn: 0.0926744	total: 5.43s	remaining: 25.3s
177:	learn: 0.0925628	total: 5.47s	remaining: 25.3s
178:	learn: 0.0923859	total: 5.5s	remaining: 25.2s
179:	learn: 0.0922456	total: 5.53s	remaining: 25.2s
180:	learn: 0.0919529	total: 5.56s	remaining: 25.1s
181:	learn: 0.0918020	total: 5.59s	remaining: 25.1s
182:	learn: 0.0915949	total: 5.62s	remaining: 25.1s
183:	learn: 0.0914950	total: 5.65s	remaining: 25.1s
184:	learn: 0.0913832	total: 5.68s	remaining: 25s
185:	learn: 0.0912705	total: 5.72s	remaining: 25s
186:	learn: 0.0911231	total: 5.75s	remaining: 25s
187:	learn: 0.0909570	total: 5.78s	remaining: 25s
188:	learn: 0.0907822	total: 5.81s	remaining: 24.9s
189:	learn: 0.0906133	total: 5.84s	remaining: 24.9s
190:	learn: 0.0903791	total: 5.87s	remaining: 24.9s
191:	learn: 0.0903569	total: 5.9s	remaining: 24.8s
192:	learn: 0.0902907	total: 5.93s	remaining: 24.8s
193:	learn: 0.0901186	total: 5.96s	remaining: 24.8s
194:	learn: 0.0900682	total: 5.99s	remaining: 24.7s
195:	learn: 0.0899742	total: 6.02s	remaining: 24.7s
196:	learn: 0.0899343	total: 6.05s	remaining: 24.7s
197:	learn: 0.0898290	total: 6.08s	remaining: 24.6s
198:	learn: 0.0896938	total: 6.11s	remaining: 24.6s
199:	learn: 0.0893648	total: 6.14s	remaining: 24.6s
200:	learn: 0.0892918	total: 6.17s	remaining: 24.5s
201:	learn: 0.0892036	total: 6.2s	remaining: 24.5s
202:	learn: 0.0890643	total: 6.23s	remaining: 24.5s
203:	learn: 0.0890415	total: 6.26s	remaining: 24.4s
204:	learn: 0.0888925	total: 6.3s	remaining: 24.4s
205:	learn: 0.0886623	total: 6.33s	remaining: 24.4s
206:	learn: 0.0884536	total: 6.36s	remaining: 24.4s
207:	learn: 0.0883832	total: 6.38s	remaining: 24.3s
208:	learn: 0.0881863	total: 6.41s	remaining: 24.3s
209:	learn: 0.0881448	total: 6.44s	remaining: 24.2s
210:	learn: 0.0879745	total: 6.47s	remaining: 24.2s
211:	learn: 0.0878147	total: 6.5s	remaining: 24.2s
212:	learn: 0.0875661	total: 6.53s	remaining: 24.1s
213:	learn: 0.0875158	total: 6.56s	remaining: 24.1s
214:	learn: 0.0873202	total: 6.59s	remaining: 24.1s
215:	learn: 0.0870678	total: 6.62s	remaining: 24s
216:	learn: 0.0869468	total: 6.65s	remaining: 24s
217:	learn: 0.0868235	total: 6.68s	remaining: 24s
218:	learn: 0.0866769	total: 6.71s	remaining: 23.9s
219:	learn: 0.0865694	total: 6.74s	remaining: 23.9s
220:	learn: 0.0864030	total: 6.77s	remaining: 23.9s
221:	learn: 0.0862534	total: 6.79s	remaining: 23.8s
222:	learn: 0.0861899	total: 6.84s	remaining: 23.8s
223:	learn: 0.0861641	total: 6.87s	remaining: 23.8s
224:	learn: 0.0861176	total: 6.9s	remaining: 23.8s
225:	learn: 0.0860803	total: 6.94s	remaining: 23.8s
226:	learn: 0.0858462	total: 6.96s	remaining: 23.7s
227:	learn: 0.0856892	total: 7s	remaining: 23.7s
228:	learn: 0.0856605	total: 7.03s	remaining: 23.7s
229:	learn: 0.0855940	total: 7.06s	remaining: 23.6s
230:	learn: 0.0855098	total: 7.08s	remaining: 23.6s
231:	learn: 0.0854923	total: 7.11s	remaining: 23.6s
232:	learn: 0.0853727	total: 7.14s	remaining: 23.5s
233:	learn: 0.0853148	total: 7.18s	remaining: 23.5s
234:	learn: 0.0852625	total: 7.21s	remaining: 23.5s
235:	learn: 0.0851776	total: 7.24s	remaining: 23.4s
236:	learn: 0.0851315	total: 7.27s	remaining: 23.4s
237:	learn: 0.0851107	total: 7.3s	remaining: 23.4s
238:	learn: 0.0849423	total: 7.33s	remaining: 23.3s
239:	learn: 0.0848212	total: 7.36s	remaining: 23.3s
240:	learn: 0.0847939	total: 7.39s	remaining: 23.3s
241:	learn: 0.0846958	total: 7.42s	remaining: 23.2s
242:	learn: 0.0846709	total: 7.45s	remaining: 23.2s
243:	learn: 0.0844178	total: 7.47s	remaining: 23.2s
244:	learn: 0.0843851	total: 7.51s	remaining: 23.1s
245:	learn: 0.0842369	total: 7.54s	remaining: 23.1s
246:	learn: 0.0842074	total: 7.57s	remaining: 23.1s
247:	learn: 0.0841758	total: 7.6s	remaining: 23s
248:	learn: 0.0839536	total: 7.63s	remaining: 23s
249:	learn: 0.0839333	total: 7.66s	remaining: 23s
250:	learn: 0.0838440	total: 7.69s	remaining: 22.9s
251:	learn: 0.0837401	total: 7.71s	remaining: 22.9s
252:	learn: 0.0837290	total: 7.74s	remaining: 22.9s
253:	learn: 0.0835747	total: 7.77s	remaining: 22.8s
254:	learn: 0.0834770	total: 7.8s	remaining: 22.8s
255:	learn: 0.0833397	total: 7.83s	remaining: 22.8s
256:	learn: 0.0833092	total: 7.86s	remaining: 22.7s
257:	learn: 0.0832793	total: 7.89s	remaining: 22.7s
258:	learn: 0.0832066	total: 7.92s	remaining: 22.7s
259:	learn: 0.0831651	total: 7.95s	remaining: 22.6s
260:	learn: 0.0831351	total: 7.98s	remaining: 22.6s
261:	learn: 0.0830151	total: 8.01s	remaining: 22.6s
262:	learn: 0.0829554	total: 8.04s	remaining: 22.5s
263:	learn: 0.0828650	total: 8.07s	remaining: 22.5s
264:	learn: 0.0827032	total: 8.1s	remaining: 22.5s
265:	learn: 0.0826723	total: 8.13s	remaining: 22.4s
266:	learn: 0.0825691	total: 8.16s	remaining: 22.4s
267:	learn: 0.0825130	total: 8.2s	remaining: 22.4s
268:	learn: 0.0824886	total: 8.23s	remaining: 22.4s
269:	learn: 0.0822895	total: 8.26s	remaining: 22.3s
270:	learn: 0.0821754	total: 8.29s	remaining: 22.3s
271:	learn: 0.0820089	total: 8.32s	remaining: 22.3s
272:	learn: 0.0819973	total: 8.35s	remaining: 22.2s
273:	learn: 0.0819637	total: 8.38s	remaining: 22.2s
274:	learn: 0.0818423	total: 8.41s	remaining: 22.2s
275:	learn: 0.0817423	total: 8.44s	remaining: 22.1s
276:	learn: 0.0817234	total: 8.47s	remaining: 22.1s
277:	learn: 0.0816335	total: 8.51s	remaining: 22.1s
278:	learn: 0.0815906	total: 8.54s	remaining: 22.1s
279:	learn: 0.0814634	total: 8.57s	remaining: 22s
280:	learn: 0.0814370	total: 8.6s	remaining: 22s
281:	learn: 0.0813368	total: 8.63s	remaining: 22s
282:	learn: 0.0811983	total: 8.66s	remaining: 21.9s
283:	learn: 0.0810839	total: 8.69s	remaining: 21.9s
284:	learn: 0.0809991	total: 8.72s	remaining: 21.9s
285:	learn: 0.0809769	total: 8.75s	remaining: 21.8s
286:	learn: 0.0808633	total: 8.78s	remaining: 21.8s
287:	learn: 0.0808521	total: 8.81s	remaining: 21.8s
288:	learn: 0.0807157	total: 8.84s	remaining: 21.7s
289:	learn: 0.0806152	total: 8.86s	remaining: 21.7s
290:	learn: 0.0805894	total: 8.9s	remaining: 21.7s
291:	learn: 0.0805701	total: 8.93s	remaining: 21.7s
292:	learn: 0.0805363	total: 8.96s	remaining: 21.6s
293:	learn: 0.0804686	total: 9.01s	remaining: 21.6s
294:	learn: 0.0804293	total: 9.04s	remaining: 21.6s
295:	learn: 0.0803338	total: 9.07s	remaining: 21.6s
296:	learn: 0.0802051	total: 9.1s	remaining: 21.5s
297:	learn: 0.0800275	total: 9.13s	remaining: 21.5s
298:	learn: 0.0799329	total: 9.16s	remaining: 21.5s
299:	learn: 0.0799055	total: 9.2s	remaining: 21.5s
300:	learn: 0.0798468	total: 9.23s	remaining: 21.4s
301:	learn: 0.0797448	total: 9.26s	remaining: 21.4s
302:	learn: 0.0797272	total: 9.29s	remaining: 21.4s
303:	learn: 0.0797067	total: 9.32s	remaining: 21.3s
304:	learn: 0.0796696	total: 9.35s	remaining: 21.3s
305:	learn: 0.0796248	total: 9.39s	remaining: 21.3s
306:	learn: 0.0795425	total: 9.42s	remaining: 21.3s
307:	learn: 0.0793413	total: 9.45s	remaining: 21.2s
308:	learn: 0.0792842	total: 9.48s	remaining: 21.2s
309:	learn: 0.0792219	total: 9.51s	remaining: 21.2s
310:	learn: 0.0792067	total: 9.54s	remaining: 21.1s
311:	learn: 0.0790806	total: 9.57s	remaining: 21.1s
312:	learn: 0.0789033	total: 9.6s	remaining: 21.1s
313:	learn: 0.0787515	total: 9.63s	remaining: 21.1s
314:	learn: 0.0787191	total: 9.66s	remaining: 21s
315:	learn: 0.0787078	total: 9.69s	remaining: 21s
316:	learn: 0.0786168	total: 9.72s	remaining: 20.9s
317:	learn: 0.0784615	total: 9.75s	remaining: 20.9s
318:	learn: 0.0784009	total: 9.78s	remaining: 20.9s
319:	learn: 0.0783581	total: 9.81s	remaining: 20.8s
320:	learn: 0.0783042	total: 9.84s	remaining: 20.8s
321:	learn: 0.0782143	total: 9.87s	remaining: 20.8s
322:	learn: 0.0781217	total: 9.9s	remaining: 20.7s
323:	learn: 0.0780396	total: 9.93s	remaining: 20.7s
324:	learn: 0.0779685	total: 9.96s	remaining: 20.7s
325:	learn: 0.0779072	total: 9.99s	remaining: 20.7s
326:	learn: 0.0778257	total: 10s	remaining: 20.6s
327:	learn: 0.0777862	total: 10.1s	remaining: 20.6s
328:	learn: 0.0777672	total: 10.1s	remaining: 20.6s
329:	learn: 0.0777041	total: 10.1s	remaining: 20.5s
330:	learn: 0.0776771	total: 10.1s	remaining: 20.5s
331:	learn: 0.0776356	total: 10.2s	remaining: 20.5s
332:	learn: 0.0775919	total: 10.2s	remaining: 20.4s
333:	learn: 0.0775304	total: 10.2s	remaining: 20.4s
334:	learn: 0.0774318	total: 10.3s	remaining: 20.4s
335:	learn: 0.0772843	total: 10.3s	remaining: 20.4s
336:	learn: 0.0772327	total: 10.4s	remaining: 20.4s
337:	learn: 0.0772172	total: 10.4s	remaining: 20.3s
338:	learn: 0.0771020	total: 10.4s	remaining: 20.3s
339:	learn: 0.0770511	total: 10.4s	remaining: 20.3s
340:	learn: 0.0770293	total: 10.5s	remaining: 20.2s
341:	learn: 0.0769214	total: 10.5s	remaining: 20.2s
342:	learn: 0.0768540	total: 10.5s	remaining: 20.2s
343:	learn: 0.0768054	total: 10.6s	remaining: 20.1s
344:	learn: 0.0767457	total: 10.6s	remaining: 20.1s
345:	learn: 0.0766967	total: 10.6s	remaining: 20.1s
346:	learn: 0.0766406	total: 10.7s	remaining: 20.1s
347:	learn: 0.0765752	total: 10.7s	remaining: 20s
348:	learn: 0.0765626	total: 10.7s	remaining: 20s
349:	learn: 0.0765393	total: 10.7s	remaining: 20s
350:	learn: 0.0764824	total: 10.8s	remaining: 19.9s
351:	learn: 0.0764637	total: 10.8s	remaining: 19.9s
352:	learn: 0.0764108	total: 10.8s	remaining: 19.9s
353:	learn: 0.0763266	total: 10.9s	remaining: 19.8s
354:	learn: 0.0763043	total: 10.9s	remaining: 19.8s
355:	learn: 0.0761587	total: 10.9s	remaining: 19.8s
356:	learn: 0.0761473	total: 11s	remaining: 19.8s
357:	learn: 0.0760715	total: 11s	remaining: 19.7s
358:	learn: 0.0760487	total: 11s	remaining: 19.7s
359:	learn: 0.0760067	total: 11.1s	remaining: 19.7s
360:	learn: 0.0759808	total: 11.1s	remaining: 19.6s
361:	learn: 0.0758742	total: 11.1s	remaining: 19.6s
362:	learn: 0.0758095	total: 11.2s	remaining: 19.6s
363:	learn: 0.0756805	total: 11.2s	remaining: 19.6s
364:	learn: 0.0756130	total: 11.2s	remaining: 19.5s
365:	learn: 0.0755670	total: 11.3s	remaining: 19.5s
366:	learn: 0.0754437	total: 11.3s	remaining: 19.5s
367:	learn: 0.0753655	total: 11.3s	remaining: 19.4s
368:	learn: 0.0753034	total: 11.4s	remaining: 19.4s
369:	learn: 0.0752193	total: 11.4s	remaining: 19.4s
370:	learn: 0.0750916	total: 11.4s	remaining: 19.4s
371:	learn: 0.0749205	total: 11.4s	remaining: 19.3s
372:	learn: 0.0748836	total: 11.5s	remaining: 19.3s
373:	learn: 0.0747127	total: 11.5s	remaining: 19.3s
374:	learn: 0.0746944	total: 11.5s	remaining: 19.2s
375:	learn: 0.0745895	total: 11.6s	remaining: 19.2s
376:	learn: 0.0744913	total: 11.6s	remaining: 19.2s
377:	learn: 0.0744707	total: 11.6s	remaining: 19.1s
378:	learn: 0.0744514	total: 11.7s	remaining: 19.1s
379:	learn: 0.0743165	total: 11.7s	remaining: 19.1s
380:	learn: 0.0742146	total: 11.7s	remaining: 19s
381:	learn: 0.0741025	total: 11.7s	remaining: 19s
382:	learn: 0.0740354	total: 11.8s	remaining: 19s
383:	learn: 0.0739529	total: 11.8s	remaining: 18.9s
384:	learn: 0.0739376	total: 11.8s	remaining: 18.9s
385:	learn: 0.0738275	total: 11.9s	remaining: 18.9s
386:	learn: 0.0737837	total: 11.9s	remaining: 18.8s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior1st': 3 unseen categories converted to Unseen on transform.

CV folds:  96%|█████████▌| 48/50 [25:15<01:02, 31.39s/fold]

998:	learn: 0.0436862	total: 30.8s	remaining: 30.8ms
999:	learn: 0.0436790	total: 30.8s	remaining: 0us
Learning rate set to 0.042743
0:	learn: 0.3894674	total: 25.9ms	remaining: 25.8s
1:	learn: 0.3789671	total: 57ms	remaining: 28.4s
2:	learn: 0.3679164	total: 86.3ms	remaining: 28.7s
3:	learn: 0.3579922	total: 112ms	remaining: 27.8s
4:	learn: 0.3482664	total: 140ms	remaining: 27.8s
5:	learn: 0.3387177	total: 166ms	remaining: 27.6s
6:	learn: 0.3294350	total: 193ms	remaining: 27.4s
7:	learn: 0.3216742	total: 220ms	remaining: 27.3s
8:	learn: 0.3132571	total: 248ms	remaining: 27.3s
9:	learn: 0.3058107	total: 276ms	remaining: 27.3s
10:	learn: 0.2978242	total: 305ms	remaining: 27.4s
11:	learn: 0.2906403	total: 330ms	remaining: 27.2s
12:	learn: 0.2839296	total: 358ms	remaining: 27.2s
13:	learn: 0.2771435	total: 385ms	remaining: 27.1s
14:	learn: 0.2713289	total: 412ms	remaining: 27.1s
15:	learn: 0.2649618	total: 441ms	remaining: 27.1s
16:	learn: 0.2593160	total: 473ms	remaining: 27.4s
17:	learn: 0.2531422	total: 503ms	remaining: 27.5s
18:	learn: 0.2481609	total: 531ms	remaining: 27.4s
19:	learn: 0.2428221	total: 555ms	remaining: 27.2s
20:	learn: 0.2381805	total: 577ms	remaining: 26.9s
21:	learn: 0.2339693	total: 604ms	remaining: 26.9s
22:	learn: 0.2292158	total: 633ms	remaining: 26.9s
23:	learn: 0.2251114	total: 662ms	remaining: 26.9s
24:	learn: 0.2207328	total: 694ms	remaining: 27.1s
25:	learn: 0.2168719	total: 727ms	remaining: 27.2s
26:	learn: 0.2128113	total: 757ms	remaining: 27.3s
27:	learn: 0.2091349	total: 776ms	remaining: 26.9s
28:	learn: 0.2054267	total: 805ms	remaining: 27s
29:	learn: 0.2023250	total: 833ms	remaining: 26.9s
30:	learn: 0.1990939	total: 864ms	remaining: 27s
31:	learn: 0.1956244	total: 892ms	remaining: 27s
32:	learn: 0.1922328	total: 924ms	remaining: 27.1s
33:	learn: 0.1893706	total: 952ms	remaining: 27s
34:	learn: 0.1865348	total: 981ms	remaining: 27.1s
35:	learn: 0.1839576	total: 1.01s	remaining: 27s
36:	learn: 0.1814168	total: 1.04s	remaining: 27s
37:	learn: 0.1787326	total: 1.07s	remaining: 27s
38:	learn: 0.1761699	total: 1.1s	remaining: 27s
39:	learn: 0.1737011	total: 1.13s	remaining: 27.1s
40:	learn: 0.1713937	total: 1.16s	remaining: 27.1s
41:	learn: 0.1693343	total: 1.19s	remaining: 27.1s
42:	learn: 0.1670170	total: 1.22s	remaining: 27.2s
43:	learn: 0.1651170	total: 1.25s	remaining: 27.1s
44:	learn: 0.1631195	total: 1.27s	remaining: 27s
45:	learn: 0.1613111	total: 1.3s	remaining: 27s
46:	learn: 0.1593393	total: 1.33s	remaining: 27.1s
47:	learn: 0.1574724	total: 1.36s	remaining: 27s
48:	learn: 0.1557183	total: 1.39s	remaining: 27s
49:	learn: 0.1540681	total: 1.42s	remaining: 27s
50:	learn: 0.1523648	total: 1.45s	remaining: 26.9s
51:	learn: 0.1506183	total: 1.48s	remaining: 26.9s
52:	learn: 0.1491875	total: 1.51s	remaining: 26.9s
53:	learn: 0.1477467	total: 1.54s	remaining: 26.9s
54:	learn: 0.1465551	total: 1.56s	remaining: 26.9s
55:	learn: 0.1450973	total: 1.6s	remaining: 27s
56:	learn: 0.1438567	total: 1.64s	remaining: 27.1s
57:	learn: 0.1427424	total: 1.67s	remaining: 27.1s
58:	learn: 0.1416258	total: 1.7s	remaining: 27s
59:	learn: 0.1402086	total: 1.73s	remaining: 27s
60:	learn: 0.1392106	total: 1.75s	remaining: 27s
61:	learn: 0.1380253	total: 1.78s	remaining: 27s
62:	learn: 0.1369794	total: 1.81s	remaining: 26.9s
63:	learn: 0.1360828	total: 1.84s	remaining: 27s
64:	learn: 0.1352649	total: 1.87s	remaining: 26.9s
65:	learn: 0.1342261	total: 1.9s	remaining: 26.9s
66:	learn: 0.1332675	total: 1.93s	remaining: 26.8s
67:	learn: 0.1322875	total: 1.96s	remaining: 26.8s
68:	learn: 0.1315721	total: 1.98s	remaining: 26.8s
69:	learn: 0.1306404	total: 2.01s	remaining: 26.8s
70:	learn: 0.1298224	total: 2.04s	remaining: 26.7s
71:	learn: 0.1291433	total: 2.07s	remaining: 26.7s
72:	learn: 0.1283234	total: 2.1s	remaining: 26.6s
73:	learn: 0.1274710	total: 2.13s	remaining: 26.6s
74:	learn: 0.1266531	total: 2.15s	remaining: 26.6s
75:	learn: 0.1260889	total: 2.19s	remaining: 26.6s
76:	learn: 0.1254141	total: 2.22s	remaining: 26.6s
77:	learn: 0.1245842	total: 2.25s	remaining: 26.6s
78:	learn: 0.1240076	total: 2.28s	remaining: 26.6s
79:	learn: 0.1233194	total: 2.31s	remaining: 26.5s
80:	learn: 0.1226787	total: 2.33s	remaining: 26.5s
81:	learn: 0.1221014	total: 2.36s	remaining: 26.5s
82:	learn: 0.1215085	total: 2.39s	remaining: 26.4s
83:	learn: 0.1210259	total: 2.42s	remaining: 26.4s
84:	learn: 0.1204991	total: 2.45s	remaining: 26.4s
85:	learn: 0.1199552	total: 2.48s	remaining: 26.3s
86:	learn: 0.1194984	total: 2.51s	remaining: 26.3s
87:	learn: 0.1189675	total: 2.54s	remaining: 26.3s
88:	learn: 0.1184099	total: 2.56s	remaining: 26.2s
89:	learn: 0.1177934	total: 2.59s	remaining: 26.2s
90:	learn: 0.1174923	total: 2.62s	remaining: 26.2s
91:	learn: 0.1169362	total: 2.65s	remaining: 26.2s
92:	learn: 0.1165428	total: 2.68s	remaining: 26.2s
93:	learn: 0.1161502	total: 2.72s	remaining: 26.2s
94:	learn: 0.1157779	total: 2.75s	remaining: 26.2s
95:	learn: 0.1155095	total: 2.77s	remaining: 26.1s
96:	learn: 0.1150014	total: 2.8s	remaining: 26.1s
97:	learn: 0.1145642	total: 2.83s	remaining: 26s
98:	learn: 0.1140755	total: 2.86s	remaining: 26s
99:	learn: 0.1138216	total: 2.89s	remaining: 26s
100:	learn: 0.1133957	total: 2.92s	remaining: 26s
101:	learn: 0.1130045	total: 2.94s	remaining: 25.9s
102:	learn: 0.1125668	total: 2.97s	remaining: 25.9s
103:	learn: 0.1120013	total: 3s	remaining: 25.9s
104:	learn: 0.1114634	total: 3.03s	remaining: 25.9s
105:	learn: 0.1111434	total: 3.06s	remaining: 25.9s
106:	learn: 0.1108758	total: 3.09s	remaining: 25.8s
107:	learn: 0.1104967	total: 3.12s	remaining: 25.8s
108:	learn: 0.1103282	total: 3.15s	remaining: 25.7s
109:	learn: 0.1100806	total: 3.18s	remaining: 25.7s
110:	learn: 0.1097300	total: 3.21s	remaining: 25.7s
111:	learn: 0.1094993	total: 3.23s	remaining: 25.6s
112:	learn: 0.1091236	total: 3.26s	remaining: 25.6s
113:	learn: 0.1087895	total: 3.29s	remaining: 25.6s
114:	learn: 0.1085248	total: 3.32s	remaining: 25.5s
115:	learn: 0.1082648	total: 3.35s	remaining: 25.5s
116:	learn: 0.1079991	total: 3.38s	remaining: 25.5s
117:	learn: 0.1078179	total: 3.4s	remaining: 25.4s
118:	learn: 0.1074804	total: 3.43s	remaining: 25.4s
119:	learn: 0.1072288	total: 3.46s	remaining: 25.4s
120:	learn: 0.1070176	total: 3.5s	remaining: 25.4s
121:	learn: 0.1066085	total: 3.52s	remaining: 25.3s
122:	learn: 0.1062532	total: 3.56s	remaining: 25.4s
123:	learn: 0.1059287	total: 3.59s	remaining: 25.3s
124:	learn: 0.1056952	total: 3.62s	remaining: 25.3s
125:	learn: 0.1054559	total: 3.64s	remaining: 25.3s
126:	learn: 0.1053005	total: 3.67s	remaining: 25.2s
127:	learn: 0.1051583	total: 3.7s	remaining: 25.2s
128:	learn: 0.1049952	total: 3.73s	remaining: 25.2s
129:	learn: 0.1048258	total: 3.78s	remaining: 25.3s
130:	learn: 0.1046841	total: 3.81s	remaining: 25.3s
131:	learn: 0.1044075	total: 3.84s	remaining: 25.3s
132:	learn: 0.1041632	total: 3.87s	remaining: 25.2s
133:	learn: 0.1039001	total: 3.9s	remaining: 25.2s
134:	learn: 0.1036986	total: 3.93s	remaining: 25.2s
135:	learn: 0.1034572	total: 3.96s	remaining: 25.2s
136:	learn: 0.1032922	total: 3.99s	remaining: 25.1s
137:	learn: 0.1031376	total: 4.02s	remaining: 25.1s
138:	learn: 0.1030072	total: 4.05s	remaining: 25.1s
139:	learn: 0.1029032	total: 4.08s	remaining: 25.1s
140:	learn: 0.1026393	total: 4.11s	remaining: 25.1s
141:	learn: 0.1024656	total: 4.14s	remaining: 25s
142:	learn: 0.1023228	total: 4.2s	remaining: 25.2s
143:	learn: 0.1020274	total: 4.24s	remaining: 25.2s
144:	learn: 0.1017706	total: 4.27s	remaining: 25.2s
145:	learn: 0.1015728	total: 4.32s	remaining: 25.3s
146:	learn: 0.1014465	total: 4.35s	remaining: 25.2s
147:	learn: 0.1012046	total: 4.38s	remaining: 25.2s
148:	learn: 0.1010547	total: 4.4s	remaining: 25.1s
149:	learn: 0.1008973	total: 4.43s	remaining: 25.1s
150:	learn: 0.1006751	total: 4.46s	remaining: 25.1s
151:	learn: 0.1004076	total: 4.49s	remaining: 25s
152:	learn: 0.1001555	total: 4.52s	remaining: 25s
153:	learn: 0.0999700	total: 4.55s	remaining: 25s
154:	learn: 0.0998531	total: 4.58s	remaining: 25s
155:	learn: 0.0997423	total: 4.61s	remaining: 24.9s
156:	learn: 0.0995862	total: 4.64s	remaining: 24.9s
157:	learn: 0.0994031	total: 4.68s	remaining: 25s
158:	learn: 0.0992906	total: 4.71s	remaining: 24.9s
159:	learn: 0.0991260	total: 4.74s	remaining: 24.9s
160:	learn: 0.0988846	total: 4.79s	remaining: 24.9s
161:	learn: 0.0986732	total: 4.82s	remaining: 24.9s
162:	learn: 0.0985768	total: 4.84s	remaining: 24.9s
163:	learn: 0.0984665	total: 4.87s	remaining: 24.8s
164:	learn: 0.0983366	total: 4.91s	remaining: 24.9s
165:	learn: 0.0981245	total: 4.94s	remaining: 24.8s
166:	learn: 0.0980132	total: 4.98s	remaining: 24.8s
167:	learn: 0.0978871	total: 5.02s	remaining: 24.9s
168:	learn: 0.0977644	total: 5.05s	remaining: 24.8s
169:	learn: 0.0976785	total: 5.08s	remaining: 24.8s
170:	learn: 0.0974303	total: 5.11s	remaining: 24.8s
171:	learn: 0.0972907	total: 5.14s	remaining: 24.8s
172:	learn: 0.0971177	total: 5.17s	remaining: 24.7s
173:	learn: 0.0968643	total: 5.21s	remaining: 24.7s
174:	learn: 0.0967414	total: 5.24s	remaining: 24.7s
175:	learn: 0.0966224	total: 5.27s	remaining: 24.7s
176:	learn: 0.0964026	total: 5.29s	remaining: 24.6s
177:	learn: 0.0962061	total: 5.32s	remaining: 24.6s
178:	learn: 0.0961422	total: 5.35s	remaining: 24.6s
179:	learn: 0.0959700	total: 5.38s	remaining: 24.5s
180:	learn: 0.0958843	total: 5.41s	remaining: 24.5s
181:	learn: 0.0957930	total: 5.44s	remaining: 24.5s
182:	learn: 0.0957390	total: 5.47s	remaining: 24.4s
183:	learn: 0.0955917	total: 5.5s	remaining: 24.4s
184:	learn: 0.0952900	total: 5.53s	remaining: 24.4s
185:	learn: 0.0950472	total: 5.56s	remaining: 24.3s
186:	learn: 0.0948973	total: 5.59s	remaining: 24.3s
187:	learn: 0.0947982	total: 5.62s	remaining: 24.3s
188:	learn: 0.0946866	total: 5.65s	remaining: 24.2s
189:	learn: 0.0945561	total: 5.68s	remaining: 24.2s
190:	learn: 0.0944511	total: 5.71s	remaining: 24.2s
191:	learn: 0.0943083	total: 5.73s	remaining: 24.1s
192:	learn: 0.0942046	total: 5.76s	remaining: 24.1s
193:	learn: 0.0941575	total: 5.8s	remaining: 24.1s
194:	learn: 0.0940933	total: 5.83s	remaining: 24.1s
195:	learn: 0.0939208	total: 5.86s	remaining: 24s
196:	learn: 0.0937694	total: 5.9s	remaining: 24s
197:	learn: 0.0935769	total: 5.93s	remaining: 24s
198:	learn: 0.0935048	total: 5.96s	remaining: 24s
199:	learn: 0.0934057	total: 6s	remaining: 24s
200:	learn: 0.0932766	total: 6.04s	remaining: 24s
201:	learn: 0.0932018	total: 6.07s	remaining: 24s
202:	learn: 0.0930285	total: 6.1s	remaining: 23.9s
203:	learn: 0.0928354	total: 6.12s	remaining: 23.9s
204:	learn: 0.0926150	total: 6.15s	remaining: 23.9s
205:	learn: 0.0924850	total: 6.18s	remaining: 23.8s
206:	learn: 0.0923377	total: 6.21s	remaining: 23.8s
207:	learn: 0.0922511	total: 6.24s	remaining: 23.8s
208:	learn: 0.0921344	total: 6.27s	remaining: 23.7s
209:	learn: 0.0920350	total: 6.3s	remaining: 23.7s
210:	learn: 0.0919142	total: 6.33s	remaining: 23.7s
211:	learn: 0.0918525	total: 6.36s	remaining: 23.7s
212:	learn: 0.0917873	total: 6.39s	remaining: 23.6s
213:	learn: 0.0915193	total: 6.42s	remaining: 23.6s
214:	learn: 0.0914713	total: 6.45s	remaining: 23.5s
215:	learn: 0.0914369	total: 6.48s	remaining: 23.5s
216:	learn: 0.0913280	total: 6.5s	remaining: 23.5s
217:	learn: 0.0911492	total: 6.53s	remaining: 23.4s
218:	learn: 0.0910658	total: 6.57s	remaining: 23.4s
219:	learn: 0.0909774	total: 6.6s	remaining: 23.4s
220:	learn: 0.0907392	total: 6.63s	remaining: 23.4s
221:	learn: 0.0906465	total: 6.66s	remaining: 23.3s
222:	learn: 0.0906080	total: 6.68s	remaining: 23.3s
223:	learn: 0.0905537	total: 6.71s	remaining: 23.3s
224:	learn: 0.0903313	total: 6.75s	remaining: 23.2s
225:	learn: 0.0901180	total: 6.77s	remaining: 23.2s
226:	learn: 0.0900235	total: 6.8s	remaining: 23.2s
227:	learn: 0.0899372	total: 6.83s	remaining: 23.1s
228:	learn: 0.0897786	total: 6.86s	remaining: 23.1s
229:	learn: 0.0896334	total: 6.89s	remaining: 23.1s
230:	learn: 0.0895941	total: 6.92s	remaining: 23s
231:	learn: 0.0894365	total: 6.95s	remaining: 23s
232:	learn: 0.0893548	total: 6.98s	remaining: 23s
233:	learn: 0.0892535	total: 7.01s	remaining: 23s
234:	learn: 0.0890427	total: 7.04s	remaining: 22.9s
235:	learn: 0.0888904	total: 7.07s	remaining: 22.9s
236:	learn: 0.0887210	total: 7.11s	remaining: 22.9s
237:	learn: 0.0885975	total: 7.13s	remaining: 22.8s
238:	learn: 0.0884273	total: 7.16s	remaining: 22.8s
239:	learn: 0.0883044	total: 7.19s	remaining: 22.8s
240:	learn: 0.0882456	total: 7.22s	remaining: 22.7s
241:	learn: 0.0880626	total: 7.25s	remaining: 22.7s
242:	learn: 0.0878974	total: 7.28s	remaining: 22.7s
243:	learn: 0.0876674	total: 7.31s	remaining: 22.7s
244:	learn: 0.0876278	total: 7.34s	remaining: 22.6s
245:	learn: 0.0875346	total: 7.37s	remaining: 22.6s
246:	learn: 0.0875147	total: 7.39s	remaining: 22.5s
247:	learn: 0.0873487	total: 7.43s	remaining: 22.5s
248:	learn: 0.0873170	total: 7.46s	remaining: 22.5s
249:	learn: 0.0871705	total: 7.48s	remaining: 22.5s
250:	learn: 0.0870317	total: 7.51s	remaining: 22.4s
251:	learn: 0.0870084	total: 7.54s	remaining: 22.4s
252:	learn: 0.0869034	total: 7.57s	remaining: 22.4s
253:	learn: 0.0867393	total: 7.6s	remaining: 22.3s
254:	learn: 0.0865758	total: 7.63s	remaining: 22.3s
255:	learn: 0.0863675	total: 7.66s	remaining: 22.3s
256:	learn: 0.0862332	total: 7.69s	remaining: 22.2s
257:	learn: 0.0861293	total: 7.72s	remaining: 22.2s
258:	learn: 0.0858686	total: 7.75s	remaining: 22.2s
259:	learn: 0.0858524	total: 7.78s	remaining: 22.1s
260:	learn: 0.0857221	total: 7.8s	remaining: 22.1s
261:	learn: 0.0856169	total: 7.84s	remaining: 22.1s
262:	learn: 0.0854211	total: 7.87s	remaining: 22.1s
263:	learn: 0.0852496	total: 7.9s	remaining: 22s
264:	learn: 0.0851265	total: 7.93s	remaining: 22s
265:	learn: 0.0850519	total: 7.96s	remaining: 22s
266:	learn: 0.0848861	total: 7.99s	remaining: 21.9s
267:	learn: 0.0847606	total: 8.02s	remaining: 21.9s
268:	learn: 0.0847265	total: 8.06s	remaining: 21.9s
269:	learn: 0.0845222	total: 8.09s	remaining: 21.9s
270:	learn: 0.0843834	total: 8.12s	remaining: 21.8s
271:	learn: 0.0842795	total: 8.15s	remaining: 21.8s
272:	learn: 0.0842525	total: 8.18s	remaining: 21.8s
273:	learn: 0.0841525	total: 8.21s	remaining: 21.7s
274:	learn: 0.0840773	total: 8.24s	remaining: 21.7s
275:	learn: 0.0839410	total: 8.27s	remaining: 21.7s
276:	learn: 0.0839167	total: 8.29s	remaining: 21.6s
277:	learn: 0.0838740	total: 8.32s	remaining: 21.6s
278:	learn: 0.0837819	total: 8.35s	remaining: 21.6s
279:	learn: 0.0837513	total: 8.38s	remaining: 21.6s
280:	learn: 0.0836182	total: 8.41s	remaining: 21.5s
281:	learn: 0.0835146	total: 8.44s	remaining: 21.5s
282:	learn: 0.0833209	total: 8.47s	remaining: 21.5s
283:	learn: 0.0832114	total: 8.5s	remaining: 21.4s
284:	learn: 0.0831876	total: 8.53s	remaining: 21.4s
285:	learn: 0.0830999	total: 8.56s	remaining: 21.4s
286:	learn: 0.0830566	total: 8.59s	remaining: 21.3s
287:	learn: 0.0829740	total: 8.62s	remaining: 21.3s
288:	learn: 0.0828895	total: 8.65s	remaining: 21.3s
289:	learn: 0.0828650	total: 8.68s	remaining: 21.3s
290:	learn: 0.0828457	total: 8.71s	remaining: 21.2s
291:	learn: 0.0828186	total: 8.74s	remaining: 21.2s
292:	learn: 0.0826540	total: 8.79s	remaining: 21.2s
293:	learn: 0.0825813	total: 8.82s	remaining: 21.2s
294:	learn: 0.0825180	total: 8.85s	remaining: 21.1s
295:	learn: 0.0825010	total: 8.88s	remaining: 21.1s
296:	learn: 0.0823786	total: 8.91s	remaining: 21.1s
297:	learn: 0.0822155	total: 8.94s	remaining: 21s
298:	learn: 0.0820960	total: 8.97s	remaining: 21s
299:	learn: 0.0820204	total: 9s	remaining: 21s
300:	learn: 0.0818524	total: 9.03s	remaining: 21s
301:	learn: 0.0817712	total: 9.06s	remaining: 20.9s
302:	learn: 0.0816637	total: 9.08s	remaining: 20.9s
303:	learn: 0.0814636	total: 9.11s	remaining: 20.9s
304:	learn: 0.0813610	total: 9.14s	remaining: 20.8s
305:	learn: 0.0812361	total: 9.18s	remaining: 20.8s
306:	learn: 0.0812208	total: 9.21s	remaining: 20.8s
307:	learn: 0.0812031	total: 9.23s	remaining: 20.8s
308:	learn: 0.0809128	total: 9.26s	remaining: 20.7s
309:	learn: 0.0808900	total: 9.29s	remaining: 20.7s
310:	learn: 0.0807445	total: 9.32s	remaining: 20.7s
311:	learn: 0.0807299	total: 9.36s	remaining: 20.6s
312:	learn: 0.0806360	total: 9.38s	remaining: 20.6s
313:	learn: 0.0804835	total: 9.41s	remaining: 20.6s
314:	learn: 0.0803203	total: 9.44s	remaining: 20.5s
315:	learn: 0.0802037	total: 9.47s	remaining: 20.5s
316:	learn: 0.0801054	total: 9.5s	remaining: 20.5s
317:	learn: 0.0800620	total: 9.53s	remaining: 20.4s
318:	learn: 0.0798036	total: 9.56s	remaining: 20.4s
319:	learn: 0.0797777	total: 9.59s	remaining: 20.4s
320:	learn: 0.0797740	total: 9.62s	remaining: 20.3s
321:	learn: 0.0797602	total: 9.67s	remaining: 20.4s
322:	learn: 0.0797468	total: 9.7s	remaining: 20.3s
323:	learn: 0.0797339	total: 9.72s	remaining: 20.3s
324:	learn: 0.0795694	total: 9.75s	remaining: 20.3s
325:	learn: 0.0795569	total: 9.78s	remaining: 20.2s
326:	learn: 0.0795448	total: 9.81s	remaining: 20.2s
327:	learn: 0.0795352	total: 9.84s	remaining: 20.2s
328:	learn: 0.0795175	total: 9.88s	remaining: 20.1s
329:	learn: 0.0795081	total: 9.9s	remaining: 20.1s
330:	learn: 0.0794094	total: 9.93s	remaining: 20.1s
331:	learn: 0.0792307	total: 9.96s	remaining: 20s
332:	learn: 0.0791918	total: 9.99s	remaining: 20s
333:	learn: 0.0791473	total: 10s	remaining: 20s
334:	learn: 0.0789756	total: 10s	remaining: 19.9s
335:	learn: 0.0788442	total: 10.1s	remaining: 19.9s
336:	learn: 0.0787530	total: 10.1s	remaining: 19.9s
337:	learn: 0.0785869	total: 10.1s	remaining: 19.9s
338:	learn: 0.0785722	total: 10.2s	remaining: 19.8s
339:	learn: 0.0784965	total: 10.2s	remaining: 19.8s
340:	learn: 0.0784196	total: 10.2s	remaining: 19.8s
341:	learn: 0.0783945	total: 10.3s	remaining: 19.8s
342:	learn: 0.0782668	total: 10.3s	remaining: 19.7s
343:	learn: 0.0782011	total: 10.3s	remaining: 19.7s
344:	learn: 0.0781678	total: 10.4s	remaining: 19.7s
345:	learn: 0.0779760	total: 10.4s	remaining: 19.6s
346:	learn: 0.0779653	total: 10.4s	remaining: 19.6s
347:	learn: 0.0778275	total: 10.4s	remaining: 19.6s
348:	learn: 0.0776864	total: 10.5s	remaining: 19.5s
349:	learn: 0.0774433	total: 10.5s	remaining: 19.5s
350:	learn: 0.0773431	total: 10.5s	remaining: 19.5s
351:	learn: 0.0772696	total: 10.6s	remaining: 19.4s
352:	learn: 0.0771639	total: 10.6s	remaining: 19.4s
353:	learn: 0.0771369	total: 10.6s	remaining: 19.4s
354:	learn: 0.0769631	total: 10.6s	remaining: 19.3s
355:	learn: 0.0768665	total: 10.7s	remaining: 19.3s
356:	learn: 0.0768565	total: 10.7s	remaining: 19.3s
357:	learn: 0.0768484	total: 10.7s	remaining: 19.2s
358:	learn: 0.0768228	total: 10.8s	remaining: 19.2s
359:	learn: 0.0768142	total: 10.8s	remaining: 19.2s
360:	learn: 0.0767139	total: 10.8s	remaining: 19.1s
361:	learn: 0.0765952	total: 10.8s	remaining: 19.1s
362:	learn: 0.0764614	total: 10.9s	remaining: 19.1s
363:	learn: 0.0763969	total: 10.9s	remaining: 19s
364:	learn: 0.0763486	total: 10.9s	remaining: 19s
365:	learn: 0.0761997	total: 11s	remaining: 19s
366:	learn: 0.0761950	total: 11s	remaining: 19s
367:	learn: 0.0760614	total: 11s	remaining: 18.9s
368:	learn: 0.0760512	total: 11.1s	remaining: 18.9s
369:	learn: 0.0759870	total: 11.1s	remaining: 18.9s
370:	learn: 0.0759351	total: 11.1s	remaining: 18.8s
371:	learn: 0.0758982	total: 11.1s	remaining: 18.8s
372:	learn: 0.0758886	total: 11.2s	remaining: 18.8s
373:	learn: 0.0758382	total: 11.2s	remaining: 18.8s
374:	learn: 0.0757203	total: 11.2s	remaining: 18.7s
375:	learn: 0.0756086	total: 11.3s	remaining: 18.7s
376:	learn: 0.0755610	total: 11.3s	remaining: 18.7s
377:	learn: 0.0755516	total: 11.3s	remaining: 18.6s
378:	learn: 0.0753981	total: 11.4s	remaining: 18.6s
379:	learn: 0.0753767	total: 11.4s	remaining: 18.6s
380:	learn: 0.0753676	total: 11.4s	remaining: 18.6s
381:	learn: 0.0752992	total: 11.4s	remaining: 18.5s
382:	learn: 0.0750885	total: 11.5s	remaining: 18.5s
383:	learn: 0.0750758	total: 11.5s	remaining: 18.5s
384:	learn: 0.0750006	total: 11.5s	remaining: 18.4s
385:	learn: 0.0748706	total: 11.6s	remaining: 18.4s
386:	learn: 0.0748299	total: 11.6s	remaining: 18.4s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Exterior2nd': 1 unseen categories converted to Unseen on transform.

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'Electrical': 1 unseen categories converted to Unseen on transform.

CV folds:  98%|█████████▊| 49/50 [25:46<00:31, 31.21s/fold]

Learning rate set to 0.042743
0:	learn: 0.3885175	total: 24.7ms	remaining: 24.7s
1:	learn: 0.3780591	total: 54.6ms	remaining: 27.3s
2:	learn: 0.3675865	total: 84.9ms	remaining: 28.2s
3:	learn: 0.3581650	total: 113ms	remaining: 28.2s
4:	learn: 0.3488432	total: 140ms	remaining: 27.9s
5:	learn: 0.3398063	total: 166ms	remaining: 27.5s
6:	learn: 0.3312130	total: 192ms	remaining: 27.3s
7:	learn: 0.3229641	total: 224ms	remaining: 27.8s
8:	learn: 0.3144882	total: 266ms	remaining: 29.3s
9:	learn: 0.3065310	total: 298ms	remaining: 29.5s
10:	learn: 0.2992427	total: 324ms	remaining: 29.1s
11:	learn: 0.2923287	total: 351ms	remaining: 28.9s
12:	learn: 0.2852628	total: 377ms	remaining: 28.6s
13:	learn: 0.2786314	total: 405ms	remaining: 28.5s
14:	learn: 0.2720618	total: 432ms	remaining: 28.4s
15:	learn: 0.2658464	total: 463ms	remaining: 28.5s
16:	learn: 0.2602328	total: 491ms	remaining: 28.4s
17:	learn: 0.2545301	total: 522ms	remaining: 28.5s
18:	learn: 0.2491095	total: 550ms	remaining: 28.4s
19:	learn: 0.2442985	total: 580ms	remaining: 28.4s
20:	learn: 0.2396419	total: 608ms	remaining: 28.3s
21:	learn: 0.2345735	total: 635ms	remaining: 28.2s
22:	learn: 0.2299199	total: 665ms	remaining: 28.2s
23:	learn: 0.2255943	total: 692ms	remaining: 28.1s
24:	learn: 0.2214963	total: 721ms	remaining: 28.1s
25:	learn: 0.2171296	total: 749ms	remaining: 28.1s
26:	learn: 0.2136016	total: 780ms	remaining: 28.1s
27:	learn: 0.2101987	total: 808ms	remaining: 28s
28:	learn: 0.2062884	total: 836ms	remaining: 28s
29:	learn: 0.2028473	total: 866ms	remaining: 28s
30:	learn: 0.1997168	total: 898ms	remaining: 28.1s
31:	learn: 0.1964929	total: 938ms	remaining: 28.4s
32:	learn: 0.1932171	total: 971ms	remaining: 28.4s
33:	learn: 0.1900611	total: 997ms	remaining: 28.3s
34:	learn: 0.1872107	total: 1.02s	remaining: 28.2s
35:	learn: 0.1844327	total: 1.05s	remaining: 28.1s
36:	learn: 0.1816246	total: 1.08s	remaining: 28s
37:	learn: 0.1789563	total: 1.1s	remaining: 28s
38:	learn: 0.1763156	total: 1.13s	remaining: 27.9s
39:	learn: 0.1740622	total: 1.17s	remaining: 28s
40:	learn: 0.1718639	total: 1.2s	remaining: 28.1s
41:	learn: 0.1696440	total: 1.23s	remaining: 28s
42:	learn: 0.1674432	total: 1.26s	remaining: 28s
43:	learn: 0.1654530	total: 1.28s	remaining: 27.9s
44:	learn: 0.1634588	total: 1.32s	remaining: 27.9s
45:	learn: 0.1613273	total: 1.34s	remaining: 27.9s
46:	learn: 0.1595206	total: 1.37s	remaining: 27.8s
47:	learn: 0.1575558	total: 1.4s	remaining: 27.8s
48:	learn: 0.1558346	total: 1.43s	remaining: 27.8s
49:	learn: 0.1540299	total: 1.46s	remaining: 27.8s
50:	learn: 0.1525922	total: 1.49s	remaining: 27.7s
51:	learn: 0.1510691	total: 1.52s	remaining: 27.7s
52:	learn: 0.1496424	total: 1.55s	remaining: 27.6s
53:	learn: 0.1481665	total: 1.57s	remaining: 27.6s
54:	learn: 0.1469730	total: 1.6s	remaining: 27.5s
55:	learn: 0.1457966	total: 1.63s	remaining: 27.5s
56:	learn: 0.1445678	total: 1.66s	remaining: 27.5s
57:	learn: 0.1432425	total: 1.69s	remaining: 27.4s
58:	learn: 0.1421224	total: 1.72s	remaining: 27.4s
59:	learn: 0.1409002	total: 1.75s	remaining: 27.4s
60:	learn: 0.1396750	total: 1.78s	remaining: 27.3s
61:	learn: 0.1386740	total: 1.8s	remaining: 27.3s
62:	learn: 0.1377085	total: 1.83s	remaining: 27.2s
63:	learn: 0.1367498	total: 1.86s	remaining: 27.2s
64:	learn: 0.1358967	total: 1.89s	remaining: 27.2s
65:	learn: 0.1350094	total: 1.92s	remaining: 27.2s
66:	learn: 0.1342058	total: 1.95s	remaining: 27.1s
67:	learn: 0.1334288	total: 1.98s	remaining: 27.1s
68:	learn: 0.1326125	total: 2s	remaining: 27.1s
69:	learn: 0.1317176	total: 2.04s	remaining: 27s
70:	learn: 0.1310039	total: 2.06s	remaining: 27s
71:	learn: 0.1302079	total: 2.1s	remaining: 27s
72:	learn: 0.1294342	total: 2.12s	remaining: 26.9s
73:	learn: 0.1286407	total: 2.15s	remaining: 26.9s
74:	learn: 0.1278872	total: 2.18s	remaining: 26.9s
75:	learn: 0.1272885	total: 2.21s	remaining: 26.9s
76:	learn: 0.1267088	total: 2.23s	remaining: 26.8s
77:	learn: 0.1259608	total: 2.27s	remaining: 26.8s
78:	learn: 0.1253242	total: 2.29s	remaining: 26.8s
79:	learn: 0.1248221	total: 2.33s	remaining: 26.7s
80:	learn: 0.1242520	total: 2.35s	remaining: 26.7s
81:	learn: 0.1235879	total: 2.39s	remaining: 26.7s
82:	learn: 0.1230072	total: 2.42s	remaining: 26.7s
83:	learn: 0.1224691	total: 2.45s	remaining: 26.7s
84:	learn: 0.1219801	total: 2.47s	remaining: 26.6s
85:	learn: 0.1213393	total: 2.5s	remaining: 26.6s
86:	learn: 0.1206622	total: 2.53s	remaining: 26.6s
87:	learn: 0.1202204	total: 2.58s	remaining: 26.7s
88:	learn: 0.1195277	total: 2.62s	remaining: 26.8s
89:	learn: 0.1188520	total: 2.65s	remaining: 26.8s
90:	learn: 0.1184078	total: 2.68s	remaining: 26.8s
91:	learn: 0.1177651	total: 2.71s	remaining: 26.8s
92:	learn: 0.1170994	total: 2.74s	remaining: 26.8s
93:	learn: 0.1163907	total: 2.77s	remaining: 26.7s
94:	learn: 0.1157541	total: 2.81s	remaining: 26.8s
95:	learn: 0.1153420	total: 2.84s	remaining: 26.7s
96:	learn: 0.1150126	total: 2.87s	remaining: 26.7s
97:	learn: 0.1145750	total: 2.9s	remaining: 26.7s
98:	learn: 0.1141778	total: 2.93s	remaining: 26.7s
99:	learn: 0.1138133	total: 2.96s	remaining: 26.6s
100:	learn: 0.1134781	total: 2.98s	remaining: 26.6s
101:	learn: 0.1131385	total: 3.01s	remaining: 26.5s
102:	learn: 0.1128442	total: 3.05s	remaining: 26.5s
103:	learn: 0.1124752	total: 3.08s	remaining: 26.5s
104:	learn: 0.1121133	total: 3.11s	remaining: 26.5s
105:	learn: 0.1118436	total: 3.14s	remaining: 26.5s
106:	learn: 0.1115624	total: 3.17s	remaining: 26.4s
107:	learn: 0.1113232	total: 3.19s	remaining: 26.4s
108:	learn: 0.1111214	total: 3.22s	remaining: 26.4s
109:	learn: 0.1107853	total: 3.25s	remaining: 26.3s
110:	learn: 0.1104812	total: 3.28s	remaining: 26.3s
111:	learn: 0.1101459	total: 3.32s	remaining: 26.3s
112:	learn: 0.1098562	total: 3.36s	remaining: 26.4s
113:	learn: 0.1095505	total: 3.39s	remaining: 26.3s
114:	learn: 0.1091894	total: 3.42s	remaining: 26.3s
115:	learn: 0.1089434	total: 3.44s	remaining: 26.3s
116:	learn: 0.1086945	total: 3.48s	remaining: 26.2s
117:	learn: 0.1084498	total: 3.5s	remaining: 26.2s
118:	learn: 0.1084498	total: 3.51s	remaining: 26s
119:	learn: 0.1081925	total: 3.54s	remaining: 26s
120:	learn: 0.1079243	total: 3.57s	remaining: 26s
121:	learn: 0.1076623	total: 3.6s	remaining: 25.9s
122:	learn: 0.1073783	total: 3.63s	remaining: 25.9s
123:	learn: 0.1070367	total: 3.66s	remaining: 25.8s
124:	learn: 0.1068523	total: 3.69s	remaining: 25.8s
125:	learn: 0.1067274	total: 3.71s	remaining: 25.8s
126:	learn: 0.1066502	total: 3.74s	remaining: 25.7s
127:	learn: 0.1064083	total: 3.76s	remaining: 25.6s
128:	learn: 0.1062291	total: 3.79s	remaining: 25.6s
129:	learn: 0.1057646	total: 3.82s	remaining: 25.6s
130:	learn: 0.1055547	total: 3.85s	remaining: 25.6s
131:	learn: 0.1053197	total: 3.88s	remaining: 25.5s
132:	learn: 0.1051154	total: 3.91s	remaining: 25.5s
133:	learn: 0.1049633	total: 3.94s	remaining: 25.5s
134:	learn: 0.1047871	total: 3.97s	remaining: 25.4s
135:	learn: 0.1045707	total: 4s	remaining: 25.4s
136:	learn: 0.1044097	total: 4.03s	remaining: 25.4s
137:	learn: 0.1042096	total: 4.06s	remaining: 25.4s
138:	learn: 0.1040211	total: 4.09s	remaining: 25.3s
139:	learn: 0.1038087	total: 4.12s	remaining: 25.3s
140:	learn: 0.1035625	total: 4.16s	remaining: 25.3s
141:	learn: 0.1035219	total: 4.19s	remaining: 25.3s
142:	learn: 0.1032663	total: 4.22s	remaining: 25.3s
143:	learn: 0.1029837	total: 4.25s	remaining: 25.3s
144:	learn: 0.1027926	total: 4.28s	remaining: 25.2s
145:	learn: 0.1026722	total: 4.31s	remaining: 25.2s
146:	learn: 0.1024812	total: 4.34s	remaining: 25.2s
147:	learn: 0.1023693	total: 4.37s	remaining: 25.2s
148:	learn: 0.1020911	total: 4.4s	remaining: 25.1s
149:	learn: 0.1019333	total: 4.43s	remaining: 25.1s
150:	learn: 0.1017933	total: 4.46s	remaining: 25.1s
151:	learn: 0.1015716	total: 4.49s	remaining: 25s
152:	learn: 0.1013523	total: 4.51s	remaining: 25s
153:	learn: 0.1011542	total: 4.54s	remaining: 25s
154:	learn: 0.1010045	total: 4.58s	remaining: 24.9s
155:	learn: 0.1009726	total: 4.61s	remaining: 24.9s
156:	learn: 0.1008812	total: 4.64s	remaining: 24.9s
157:	learn: 0.1008812	total: 4.65s	remaining: 24.8s
158:	learn: 0.1007699	total: 4.68s	remaining: 24.7s
159:	learn: 0.1006986	total: 4.71s	remaining: 24.7s
160:	learn: 0.1004228	total: 4.74s	remaining: 24.7s
161:	learn: 0.1002166	total: 4.76s	remaining: 24.6s
162:	learn: 0.0999981	total: 4.79s	remaining: 24.6s
163:	learn: 0.0998213	total: 4.83s	remaining: 24.6s
164:	learn: 0.0998213	total: 4.84s	remaining: 24.5s
165:	learn: 0.0998213	total: 4.84s	remaining: 24.3s
166:	learn: 0.0997172	total: 4.86s	remaining: 24.2s
167:	learn: 0.0996817	total: 4.89s	remaining: 24.2s
168:	learn: 0.0994181	total: 4.92s	remaining: 24.2s
169:	learn: 0.0992643	total: 4.95s	remaining: 24.1s
170:	learn: 0.0990851	total: 4.97s	remaining: 24.1s
171:	learn: 0.0989272	total: 5.01s	remaining: 24.1s
172:	learn: 0.0988216	total: 5.04s	remaining: 24.1s
173:	learn: 0.0985307	total: 5.07s	remaining: 24.1s
174:	learn: 0.0984528	total: 5.1s	remaining: 24s
175:	learn: 0.0981784	total: 5.13s	remaining: 24s
176:	learn: 0.0981666	total: 5.15s	remaining: 23.9s
177:	learn: 0.0981666	total: 5.16s	remaining: 23.8s
178:	learn: 0.0981018	total: 5.19s	remaining: 23.8s
179:	learn: 0.0979459	total: 5.22s	remaining: 23.8s
180:	learn: 0.0978006	total: 5.25s	remaining: 23.8s
181:	learn: 0.0977646	total: 5.28s	remaining: 23.7s
182:	learn: 0.0977154	total: 5.31s	remaining: 23.7s
183:	learn: 0.0976101	total: 5.34s	remaining: 23.7s
184:	learn: 0.0974904	total: 5.37s	remaining: 23.7s
185:	learn: 0.0972506	total: 5.4s	remaining: 23.6s
186:	learn: 0.0971303	total: 5.43s	remaining: 23.6s
187:	learn: 0.0971008	total: 5.47s	remaining: 23.6s
188:	learn: 0.0968186	total: 5.51s	remaining: 23.7s
189:	learn: 0.0967478	total: 5.54s	remaining: 23.6s
190:	learn: 0.0966397	total: 5.57s	remaining: 23.6s
191:	learn: 0.0964675	total: 5.6s	remaining: 23.6s
192:	learn: 0.0964610	total: 5.62s	remaining: 23.5s
193:	learn: 0.0962788	total: 5.64s	remaining: 23.4s
194:	learn: 0.0962320	total: 5.68s	remaining: 23.4s
195:	learn: 0.0961229	total: 5.71s	remaining: 23.4s
196:	learn: 0.0959190	total: 5.74s	remaining: 23.4s
197:	learn: 0.0957934	total: 5.76s	remaining: 23.3s
198:	learn: 0.0957548	total: 5.79s	remaining: 23.3s
199:	learn: 0.0956808	total: 5.82s	remaining: 23.3s
200:	learn: 0.0954099	total: 5.85s	remaining: 23.3s
201:	learn: 0.0953121	total: 5.88s	remaining: 23.2s
202:	learn: 0.0950557	total: 5.91s	remaining: 23.2s
203:	learn: 0.0949461	total: 5.94s	remaining: 23.2s
204:	learn: 0.0947934	total: 5.97s	remaining: 23.1s
205:	learn: 0.0946531	total: 6s	remaining: 23.1s
206:	learn: 0.0946424	total: 6.03s	remaining: 23.1s
207:	learn: 0.0944352	total: 6.06s	remaining: 23.1s
208:	learn: 0.0942541	total: 6.09s	remaining: 23s
209:	learn: 0.0942024	total: 6.12s	remaining: 23s
210:	learn: 0.0940522	total: 6.15s	remaining: 23s
211:	learn: 0.0938670	total: 6.17s	remaining: 22.9s
212:	learn: 0.0936836	total: 6.2s	remaining: 22.9s
213:	learn: 0.0934976	total: 6.23s	remaining: 22.9s
214:	learn: 0.0933286	total: 6.26s	remaining: 22.9s
215:	learn: 0.0931271	total: 6.29s	remaining: 22.8s
216:	learn: 0.0930419	total: 6.32s	remaining: 22.8s
217:	learn: 0.0928815	total: 6.35s	remaining: 22.8s
218:	learn: 0.0928580	total: 6.38s	remaining: 22.7s
219:	learn: 0.0927760	total: 6.41s	remaining: 22.7s
220:	learn: 0.0927480	total: 6.44s	remaining: 22.7s
221:	learn: 0.0926198	total: 6.46s	remaining: 22.7s
222:	learn: 0.0925919	total: 6.49s	remaining: 22.6s
223:	learn: 0.0923659	total: 6.52s	remaining: 22.6s
224:	learn: 0.0923131	total: 6.55s	remaining: 22.6s
225:	learn: 0.0921890	total: 6.61s	remaining: 22.6s
226:	learn: 0.0920310	total: 6.64s	remaining: 22.6s
227:	learn: 0.0919025	total: 6.67s	remaining: 22.6s
228:	learn: 0.0918450	total: 6.7s	remaining: 22.6s
229:	learn: 0.0916966	total: 6.73s	remaining: 22.5s
230:	learn: 0.0916023	total: 6.77s	remaining: 22.5s
231:	learn: 0.0915608	total: 6.8s	remaining: 22.5s
232:	learn: 0.0914931	total: 6.84s	remaining: 22.5s
233:	learn: 0.0913828	total: 6.88s	remaining: 22.5s
234:	learn: 0.0912972	total: 6.9s	remaining: 22.5s
235:	learn: 0.0912644	total: 6.93s	remaining: 22.4s
236:	learn: 0.0911410	total: 6.96s	remaining: 22.4s
237:	learn: 0.0911033	total: 7s	remaining: 22.4s
238:	learn: 0.0909389	total: 7.03s	remaining: 22.4s
239:	learn: 0.0906671	total: 7.06s	remaining: 22.3s
240:	learn: 0.0906173	total: 7.09s	remaining: 22.3s
241:	learn: 0.0905083	total: 7.12s	remaining: 22.3s
242:	learn: 0.0904894	total: 7.15s	remaining: 22.3s
243:	learn: 0.0904404	total: 7.18s	remaining: 22.3s
244:	learn: 0.0903026	total: 7.22s	remaining: 22.2s
245:	learn: 0.0902112	total: 7.26s	remaining: 22.2s
246:	learn: 0.0901826	total: 7.29s	remaining: 22.2s
247:	learn: 0.0901583	total: 7.32s	remaining: 22.2s
248:	learn: 0.0901070	total: 7.35s	remaining: 22.2s
249:	learn: 0.0899299	total: 7.38s	remaining: 22.1s
250:	learn: 0.0897707	total: 7.41s	remaining: 22.1s
251:	learn: 0.0895871	total: 7.44s	remaining: 22.1s
252:	learn: 0.0894517	total: 7.47s	remaining: 22.1s
253:	learn: 0.0893100	total: 7.5s	remaining: 22s
254:	learn: 0.0892497	total: 7.53s	remaining: 22s
255:	learn: 0.0892041	total: 7.56s	remaining: 22s
256:	learn: 0.0890445	total: 7.59s	remaining: 21.9s
257:	learn: 0.0889962	total: 7.63s	remaining: 21.9s
258:	learn: 0.0889623	total: 7.66s	remaining: 21.9s
259:	learn: 0.0889473	total: 7.7s	remaining: 21.9s
260:	learn: 0.0889371	total: 7.72s	remaining: 21.9s
261:	learn: 0.0888180	total: 7.76s	remaining: 21.9s
262:	learn: 0.0886592	total: 7.79s	remaining: 21.8s
263:	learn: 0.0885971	total: 7.82s	remaining: 21.8s
264:	learn: 0.0885762	total: 7.85s	remaining: 21.8s
265:	learn: 0.0885600	total: 7.88s	remaining: 21.7s
266:	learn: 0.0884021	total: 7.91s	remaining: 21.7s
267:	learn: 0.0883236	total: 7.94s	remaining: 21.7s
268:	learn: 0.0881681	total: 7.96s	remaining: 21.6s
269:	learn: 0.0881536	total: 8s	remaining: 21.6s
270:	learn: 0.0880882	total: 8.02s	remaining: 21.6s
271:	learn: 0.0880070	total: 8.05s	remaining: 21.6s
272:	learn: 0.0879898	total: 8.09s	remaining: 21.5s
273:	learn: 0.0879297	total: 8.12s	remaining: 21.5s
274:	learn: 0.0878010	total: 8.15s	remaining: 21.5s
275:	learn: 0.0877770	total: 8.18s	remaining: 21.5s
276:	learn: 0.0875992	total: 8.21s	remaining: 21.4s
277:	learn: 0.0875786	total: 8.23s	remaining: 21.4s
278:	learn: 0.0875386	total: 8.26s	remaining: 21.4s
279:	learn: 0.0875176	total: 8.29s	remaining: 21.3s
280:	learn: 0.0873555	total: 8.32s	remaining: 21.3s
281:	learn: 0.0873093	total: 8.35s	remaining: 21.3s
282:	learn: 0.0872951	total: 8.39s	remaining: 21.2s
283:	learn: 0.0870758	total: 8.42s	remaining: 21.2s
284:	learn: 0.0870523	total: 8.45s	remaining: 21.2s
285:	learn: 0.0870250	total: 8.48s	remaining: 21.2s
286:	learn: 0.0869988	total: 8.51s	remaining: 21.1s
287:	learn: 0.0869432	total: 8.54s	remaining: 21.1s
288:	learn: 0.0869208	total: 8.57s	remaining: 21.1s
289:	learn: 0.0868681	total: 8.6s	remaining: 21.1s
290:	learn: 0.0868508	total: 8.63s	remaining: 21s
291:	learn: 0.0868215	total: 8.66s	remaining: 21s
292:	learn: 0.0868054	total: 8.7s	remaining: 21s
293:	learn: 0.0866760	total: 8.72s	remaining: 20.9s
294:	learn: 0.0865485	total: 8.75s	remaining: 20.9s
295:	learn: 0.0864923	total: 8.78s	remaining: 20.9s
296:	learn: 0.0863735	total: 8.81s	remaining: 20.9s
297:	learn: 0.0863373	total: 8.85s	remaining: 20.8s
298:	learn: 0.0862127	total: 8.87s	remaining: 20.8s
299:	learn: 0.0860647	total: 8.91s	remaining: 20.8s
300:	learn: 0.0860137	total: 8.94s	remaining: 20.8s
301:	learn: 0.0858505	total: 8.97s	remaining: 20.7s
302:	learn: 0.0857290	total: 9s	remaining: 20.7s
303:	learn: 0.0856192	total: 9.03s	remaining: 20.7s
304:	learn: 0.0854903	total: 9.06s	remaining: 20.6s
305:	learn: 0.0853251	total: 9.09s	remaining: 20.6s
306:	learn: 0.0853085	total: 9.12s	remaining: 20.6s
307:	learn: 0.0851352	total: 9.15s	remaining: 20.6s
308:	learn: 0.0849428	total: 9.18s	remaining: 20.5s
309:	learn: 0.0848362	total: 9.21s	remaining: 20.5s
310:	learn: 0.0848267	total: 9.24s	remaining: 20.5s
311:	learn: 0.0848027	total: 9.27s	remaining: 20.4s
312:	learn: 0.0847253	total: 9.3s	remaining: 20.4s
313:	learn: 0.0846271	total: 9.33s	remaining: 20.4s
314:	learn: 0.0845845	total: 9.36s	remaining: 20.4s
315:	learn: 0.0844561	total: 9.4s	remaining: 20.3s
316:	learn: 0.0843142	total: 9.43s	remaining: 20.3s
317:	learn: 0.0843033	total: 9.46s	remaining: 20.3s
318:	learn: 0.0842325	total: 9.49s	remaining: 20.3s
319:	learn: 0.0842233	total: 9.52s	remaining: 20.2s
320:	learn: 0.0840890	total: 9.55s	remaining: 20.2s
321:	learn: 0.0840365	total: 9.58s	remaining: 20.2s
322:	learn: 0.0839049	total: 9.62s	remaining: 20.2s
323:	learn: 0.0838321	total: 9.65s	remaining: 20.1s
324:	learn: 0.0838135	total: 9.68s	remaining: 20.1s
325:	learn: 0.0836748	total: 9.71s	remaining: 20.1s
326:	learn: 0.0836673	total: 9.74s	remaining: 20s
327:	learn: 0.0836194	total: 9.78s	remaining: 20s
328:	learn: 0.0834835	total: 9.82s	remaining: 20s
329:	learn: 0.0833834	total: 9.85s	remaining: 20s
330:	learn: 0.0833186	total: 9.88s	remaining: 20s
331:	learn: 0.0831862	total: 9.91s	remaining: 19.9s
332:	learn: 0.0830944	total: 9.94s	remaining: 19.9s
333:	learn: 0.0830325	total: 9.97s	remaining: 19.9s
334:	learn: 0.0829735	total: 9.99s	remaining: 19.8s
335:	learn: 0.0829157	total: 10s	remaining: 19.8s
336:	learn: 0.0828927	total: 10.1s	remaining: 19.8s
337:	learn: 0.0827362	total: 10.1s	remaining: 19.7s
338:	learn: 0.0827149	total: 10.1s	remaining: 19.7s
339:	learn: 0.0826762	total: 10.1s	remaining: 19.7s
340:	learn: 0.0826147	total: 10.2s	remaining: 19.7s
341:	learn: 0.0824911	total: 10.2s	remaining: 19.6s
342:	learn: 0.0824397	total: 10.2s	remaining: 19.6s
343:	learn: 0.0823384	total: 10.3s	remaining: 19.6s
344:	learn: 0.0822864	total: 10.3s	remaining: 19.5s
345:	learn: 0.0821973	total: 10.3s	remaining: 19.5s
346:	learn: 0.0821842	total: 10.4s	remaining: 19.5s
347:	learn: 0.0820943	total: 10.4s	remaining: 19.5s
348:	learn: 0.0819830	total: 10.4s	remaining: 19.4s
349:	learn: 0.0818909	total: 10.4s	remaining: 19.4s
350:	learn: 0.0817665	total: 10.5s	remaining: 19.4s
351:	learn: 0.0817502	total: 10.5s	remaining: 19.3s
352:	learn: 0.0815930	total: 10.5s	remaining: 19.3s
353:	learn: 0.0815623	total: 10.6s	remaining: 19.3s
354:	learn: 0.0815537	total: 10.6s	remaining: 19.3s
355:	learn: 0.0814934	total: 10.6s	remaining: 19.2s
356:	learn: 0.0814548	total: 10.7s	remaining: 19.2s
357:	learn: 0.0813510	total: 10.7s	remaining: 19.2s
358:	learn: 0.0813019	total: 10.7s	remaining: 19.2s
359:	learn: 0.0812619	total: 10.8s	remaining: 19.1s
360:	learn: 0.0812441	total: 10.8s	remaining: 19.1s
361:	learn: 0.0811901	total: 10.8s	remaining: 19.1s
362:	learn: 0.0811719	total: 10.8s	remaining: 19s
363:	learn: 0.0809800	total: 10.9s	remaining: 19s
364:	learn: 0.0807979	total: 10.9s	remaining: 19s
365:	learn: 0.0806989	total: 10.9s	remaining: 18.9s
366:	learn: 0.0806311	total: 11s	remaining: 18.9s
367:	learn: 0.0805252	total: 11s	remaining: 18.9s
368:	learn: 0.0805115	total: 11s	remaining: 18.9s
369:	learn: 0.0804707	total: 11.1s	remaining: 18.9s
370:	learn: 0.0804421	total: 11.1s	remaining: 18.8s
371:	learn: 0.0804171	total: 11.1s	remaining: 18.8s
372:	learn: 0.0803293	total: 11.2s	remaining: 18.8s
373:	learn: 0.0803081	total: 11.2s	remaining: 18.7s
374:	learn: 0.0802167	total: 11.2s	remaining: 18.7s
375:	learn: 0.0802064	total: 11.3s	remaining: 18.7s
376:	learn: 0.0800345	total: 11.3s	remaining: 18.7s
377:	learn: 0.0800123	total: 11.3s	remaining: 18.6s
378:	learn: 0.0799188	total: 11.3s	remaining: 18.6s
379:	learn: 0.0799003	total: 11.4s	remaining: 18.6s
380:	learn: 0.0797905	total: 11.4s	remaining: 18.5s
381:	learn: 0.0796283	total: 11.4s	remaining: 18.5s
382:	learn: 0.0795263	total: 11.5s	remaining: 18.5s
383:	learn: 0.0795029	total: 11.5s	remaining: 18.4s
384:	learn: 0.0794455	total: 11.5s	remaining: 18.4s
385:	learn: 0.0793712	total: 11.5s	remaining: 18.4s
386:	learn: 0.0793057	total: 11.6s	remaining: 18.3s
387:	learn: 0.0792970	total: 11.6s	remaining: 18.3s

d:\vs_projects\fp_houses\src\processing.py:179: UserWarning: Column 'MiscFeature': 2 unseen categories converted to Unseen on transform.

,model,TRAIN_rmsle_MEAN,TRAIN_rmsle_STD,VAL_rmsle_MEAN,VAL_rmsle_STD,OOF_rmsle
0,None,0.051251,0.001906,0.113443,0.013345,0.11239

### tuning

* elastic net
* lgbm
* catboost

In [10]:
from sklearn.base import clone
from sklearn.metrics import root_mean_squared_error
import optuna

In [11]:
def run_one_fold(
    pipe,
    build_model_fn,
    params,
    X_tr,
    y_tr,
    X_val,
    y_val,
    fit_extra_fn=None,
    early_stopping=True,
):

    prep = clone(pipe)
    X_tr_t = prep.fit_transform(X_tr)
    X_val_t = prep.transform(X_val)

    model = build_model_fn(params)
    fit_kwargs = dict(fit_extra_fn(params) if fit_extra_fn else {})
    if early_stopping:
        fit_kwargs["eval_set"] = [(X_val_t, y_val)]

    model.fit(X_tr_t, y_tr, **fit_kwargs)

    rmse = root_mean_squared_error(y_val, model.predict(X_val_t))
    fitted_pipe = Pipeline([("preprocessor", prep), ("model", model)])
    return rmse, fitted_pipe

In [12]:
from tqdm.auto import tqdm

In [13]:
def make_objective(
    sample_params_fn,
    build_model_fn,
    pipe,
    X,
    y,
    y_binned,
    cv,
    fit_extra_fn=None,
    early_stopping=True,
):
    def objective(trial):
        params = sample_params_fn(trial)
        fold_rmses = []
        fold_iter = enumerate(cv.split(X, y_binned))
        for step, (tr_idx, val_idx) in tqdm(
            fold_iter,
            total=cv.get_n_splits(),
            desc=f"trial {trial.number}",
            leave=False,
        ):
            X_tr, X_val = X.iloc[tr_idx], X.iloc[val_idx]
            y_tr, y_val = y.iloc[tr_idx], y.iloc[val_idx]

            rmse, _ = run_one_fold(
                pipe,
                build_model_fn,
                params,
                X_tr,
                y_tr,
                X_val,
                y_val,
                fit_extra_fn=fit_extra_fn,
                early_stopping=early_stopping,
            )
            fold_rmses.append(rmse)

            trial.report(float(np.mean(fold_rmses)), step=step)
            if trial.should_prune():
                raise optuna.TrialPruned()

        trial.set_user_attr("fold_std", float(np.std(fold_rmses)))
        return float(np.mean(fold_rmses))

    return objective

In [14]:
def run_confirm_cv(
    pipe,
    build_model_fn,
    params,
    X,
    y,
    y_binned,
    cv,
    fit_extra_fn=None,
    early_stopping=True,
):
    fold_rmses, fitted_pipes = [], []
    for tr_idx, val_idx in tqdm(
        cv.split(X, y_binned), total=cv.get_n_splits(), desc="confirm cv"
    ):
        X_tr, X_val = X.iloc[tr_idx], X.iloc[val_idx]
        y_tr, y_val = y.iloc[tr_idx], y.iloc[val_idx]
        rmse, fitted_pipe = run_one_fold(
            pipe,
            build_model_fn,
            params,
            X_tr,
            y_tr,
            X_val,
            y_val,
            fit_extra_fn=fit_extra_fn,
            early_stopping=early_stopping,
        )
        fold_rmses.append(rmse)
        fitted_pipes.append(fitted_pipe)
    return fold_rmses, fitted_pipes

In [15]:
from sklearn.model_selection import train_test_split, RepeatedStratifiedKFold

X_opt, X_hold, y_opt, y_hold, yb_opt, yb_hold = train_test_split(
    X_train,
    y_train,
    y_binned,
    test_size=0.15,
    stratify=y_binned,
    random_state=gseed,
)

yb_opt = pd.qcut(y_opt, q=10, labels=False)

rskf_search = RepeatedStratifiedKFold(n_splits=5, n_repeats=2, random_state=gseed)
rskf_confirm = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=gseed)

In [16]:
import lightgbm as lgb


def sample_params_en(trial):
    return {
        "alpha": trial.suggest_float("alpha", 1e-4, 10.0, log=True),
        "l1_ratio": trial.suggest_float("l1_ratio", 0.0, 1.0),
    }


def build_en(params):
    return ElasticNet(random_state=gseed, max_iter=20000, **params)


def sample_params_lgbm(trial):
    return {
        "num_leaves": trial.suggest_int("num_leaves", 7, 255, log=True),
        "max_depth": trial.suggest_int("max_depth", 3, 12),
        "learning_rate": trial.suggest_float("learning_rate", 5e-3, 0.2, log=True),
        "min_child_samples": trial.suggest_int("min_child_samples", 5, 100),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "subsample_freq": trial.suggest_int("subsample_freq", 0, 7),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.4, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True),
    }


def build_lgbm(params):
    return LGBMRegressor(random_state=gseed, verbosity=-1, n_estimators=5000, **params)


def lgbm_fit_extra(params=None):
    return {"callbacks": [lgb.early_stopping(100, verbose=False)]}


def sample_params_cb(trial):
    return {
        "depth": trial.suggest_int("depth", 3, 10),
        "learning_rate": trial.suggest_float("learning_rate", 1e-2, 0.3, log=True),
        "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 1.0, 30.0, log=True),
        "random_strength": trial.suggest_float("random_strength", 1e-3, 10.0, log=True),
        "bagging_temperature": trial.suggest_float("bagging_temperature", 0.0, 1.0),
        "border_count": trial.suggest_int("border_count", 32, 255),
    }


def build_cb(params):
    return CatBoostRegressor(
        random_state=gseed,
        loss_function="RMSE",
        iterations=5000,
        thread_count=1,
        **params,
    )


def cb_fit_extra(params=None):
    return {
        "cat_features": list(ohe_columns),
        "early_stopping_rounds": 100,
        "use_best_model": True,
        "verbose": False,
    }

In [ ]:
import os
import optuna

output_dir = "optuna_results"
os.makedirs(output_dir, exist_ok=True)

storage = f"sqlite:///{output_dir}/optuna_studies.db"


sampler_en = optuna.samplers.TPESampler(seed=gseed, multivariate=True)
sampler_lgbm = optuna.samplers.TPESampler(seed=gseed, multivariate=True)
sampler_cb = optuna.samplers.TPESampler(seed=gseed, multivariate=True)

pruner_lgbm = optuna.pruners.MedianPruner(
    n_startup_trials=10, n_warmup_steps=3, interval_steps=1
)
pruner_cb = optuna.pruners.MedianPruner(
    n_startup_trials=10, n_warmup_steps=3, interval_steps=1
)

study_en = optuna.create_study(
    study_name="elastic_net",
    direction="minimize",
    sampler=sampler_en,
    storage=storage,
    load_if_exists=True,
)
study_lgbm = optuna.create_study(
    study_name="lightgbm",
    direction="minimize",
    sampler=sampler_lgbm,
    pruner=pruner_lgbm,
    storage=storage,
    load_if_exists=True,
)
study_cb = optuna.create_study(
    study_name="catboost",
    direction="minimize",
    sampler=sampler_cb,
    pruner=pruner_cb,
    storage=storage,
    load_if_exists=True,
)

[I 2026-09-14 01:01:35,694] Using an existing study with `study_name='elastic_net'` instead of creating a new one.
[I 2026-09-14 01:01:35,727] Using an existing study with `study_name='lightgbm'` instead of creating a new one.
[I 2026-09-14 01:01:35,756] Using an existing study with `study_name='catboost'` instead of creating a new one.

In [21]:
study_en.optimize(
    make_objective(
        sample_params_en,
        build_en,
        lin_pipe,
        X_opt,
        y_opt,
        yb_opt,
        rskf_confirm,
        early_stopping=False,
    ),
    n_trials=200,
    n_jobs=4,
)

study_lgbm.optimize(
    make_objective(
        sample_params_lgbm,
        build_lgbm,
        tree_pipe,
        X_opt,
        y_opt,
        yb_opt,
        rskf_search,
        fit_extra_fn=lgbm_fit_extra,
    ),
    n_trials=80,
    n_jobs=1,
)

study_cb.optimize(
    make_objective(
        sample_params_cb,
        build_cb,
        tree_pipe,
        X_opt,
        y_opt,
        yb_opt,
        rskf_search,
        fit_extra_fn=cb_fit_extra,
    ),
    n_trials=60,
    n_jobs=1,
)

d:\vs_projects\fp_houses\.venv\Lib\site-packages\sqlalchemy\orm\state.py:204: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x000001604B1B4400>
  self.obj = weakref.ref(obj, self._cleanup)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
d:\vs_projects\fp_houses\.venv\Lib\site-packages\sqlalchemy\orm\state.py:204: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x000001604B1B62F0>
  self.obj = weakref.ref(obj, self._cleanup)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
d:\vs_projects\fp_houses\.venv\Lib\site-packages\sqlalchemy\orm\state.py:204: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x000001604B0B45E0>
  self.obj = weakref.ref(obj, self._cleanup)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
d:\vs_projects\fp_houses\.venv\Lib\site-packages\sqlalchemy\orm\state.py:204: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x000001604B1048B0>
  self.obj = weakref.ref(obj, self._cleanup)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
d:\vs_projects\fp_houses\.venv\Lib\site-packages\sqlalchemy\orm\state.py:204: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x000001604B003880>
  self.obj = weakref.ref(obj, self._cleanup)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
d:\vs_projects\fp_houses\.venv\Lib\site-packages\sqlalchemy\orm\state.py:204: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x000001604B0B4F40>
  self.obj = weakref.ref(obj, self._cleanup)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
d:\vs_projects\fp_houses\.venv\Lib\site-packages\sqlalchemy\orm\state.py:204: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x000001604B0B4D60>
  self.obj = weakref.ref(obj, self._cleanup)
ResourceWarning: Enable tracemalloc to get the object allocation traceback

trial 476:   0%|          | 0/50 [00:00<?, ?it/s]

trial 478:   0%|          | 0/50 [00:00<?, ?it/s]

trial 479:   0%|          | 0/50 [00:00<?, ?it/s]

trial 477:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:01:40,299] Trial 476 pruned.
[I 2026-09-14 01:01:40,444] Trial 478 pruned.
[I 2026-09-14 01:01:40,452] Trial 477 pruned.
[I 2026-09-14 01:01:40,481] Trial 479 pruned.

trial 480:   0%|          | 0/50 [00:00<?, ?it/s]

trial 482:   0%|          | 0/50 [00:00<?, ?it/s]

trial 481:   0%|          | 0/50 [00:00<?, ?it/s]

trial 483:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:01:42,080] Trial 482 pruned.
[I 2026-09-14 01:01:42,099] Trial 483 pruned.
[I 2026-09-14 01:01:42,116] Trial 481 pruned.

trial 485:   0%|          | 0/50 [00:00<?, ?it/s]

trial 484:   0%|          | 0/50 [00:00<?, ?it/s]

trial 486:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:01:43,451] Trial 485 pruned.
[I 2026-09-14 01:01:43,714] Trial 484 pruned.
[I 2026-09-14 01:01:43,784] Trial 486 pruned.

trial 487:   0%|          | 0/50 [00:00<?, ?it/s]

trial 488:   0%|          | 0/50 [00:00<?, ?it/s]

trial 489:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:01:45,299] Trial 487 pruned.
[I 2026-09-14 01:01:45,754] Trial 489 pruned.

trial 490:   0%|          | 0/50 [00:00<?, ?it/s]

trial 491:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:01:47,374] Trial 491 pruned.

trial 492:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:01:49,819] Trial 492 pruned.

trial 493:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:01:52,143] Trial 493 pruned.

trial 494:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:01:54,680] Trial 494 pruned.

trial 495:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:01:57,166] Trial 495 pruned.

trial 496:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:02:00,165] Trial 496 pruned.

trial 497:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:02:39,389] Trial 480 finished with value: 0.10849051158853489 and parameters: {'alpha': 0.0011368351689816868, 'l1_ratio': 0.552814373960963}. Best is trial 145 with value: 0.10822154579479654.

trial 498:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:03:03,494] Trial 488 finished with value: 0.10918533658325492 and parameters: {'alpha': 0.0011532389061909554, 'l1_ratio': 0.8235428725302478}. Best is trial 145 with value: 0.10822154579479654.

trial 499:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:03:09,986] Trial 490 finished with value: 0.10871339023599597 and parameters: {'alpha': 0.0012025026667636912, 'l1_ratio': 0.6215205240830027}. Best is trial 145 with value: 0.10822154579479654.

trial 500:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:03:12,391] Trial 500 pruned.

trial 501:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:03:15,540] Trial 501 pruned.

trial 502:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:03:18,522] Trial 502 pruned.

trial 503:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:03:20,821] Trial 503 pruned.

trial 504:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:03:23,912] Trial 504 pruned.
[I 2026-09-14 01:03:24,976] Trial 497 finished with value: 0.10877095423594006 and parameters: {'alpha': 0.001481570473199672, 'l1_ratio': 0.5063413893618354}. Best is trial 145 with value: 0.10822154579479654.

trial 505:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:03:26,300] Trial 505 pruned.

trial 506:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:03:27,112] Trial 506 pruned.

trial 507:   0%|          | 0/50 [00:00<?, ?it/s]

trial 508:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:03:29,425] Trial 508 pruned.

trial 509:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:03:33,047] Trial 509 pruned.

trial 510:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:03:35,627] Trial 510 pruned.

trial 511:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:03:37,818] Trial 498 finished with value: 0.10905856932367268 and parameters: {'alpha': 0.001185211584802281, 'l1_ratio': 0.7641237827444233}. Best is trial 145 with value: 0.10822154579479654.

trial 512:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:03:40,738] Trial 512 pruned.

trial 513:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:03:45,622] Trial 499 finished with value: 0.10883770268416212 and parameters: {'alpha': 0.0013868145176181928, 'l1_ratio': 0.5735764047929629}. Best is trial 145 with value: 0.10822154579479654.

trial 514:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:03:53,572] Trial 514 pruned.

trial 515:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:03:57,440] Trial 515 pruned.

trial 516:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:04:00,167] Trial 516 pruned.

trial 517:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:04:16,088] Trial 517 pruned.

trial 518:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:04:18,453] Trial 518 pruned.

trial 519:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:04:26,560] Trial 507 finished with value: 0.10941390152621039 and parameters: {'alpha': 0.0010375932920988278, 'l1_ratio': 0.9869469828336617}. Best is trial 145 with value: 0.10822154579479654.

trial 520:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:04:36,448] Trial 511 finished with value: 0.10908409592862765 and parameters: {'alpha': 0.001625081019088114, 'l1_ratio': 0.5422721594234311}. Best is trial 145 with value: 0.10822154579479654.

trial 521:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:04:38,732] Trial 521 pruned.

trial 522:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:04:40,998] Trial 522 pruned.
[I 2026-09-14 01:04:42,620] Trial 513 finished with value: 0.10908768058079132 and parameters: {'alpha': 0.0018091893371698765, 'l1_ratio': 0.478737192017194}. Best is trial 145 with value: 0.10822154579479654.

trial 523:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:04:43,169] Trial 523 pruned.

trial 524:   0%|          | 0/50 [00:00<?, ?it/s]

trial 525:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:04:45,037] Trial 524 pruned.
[I 2026-09-14 01:04:45,086] Trial 525 pruned.

trial 527:   0%|          | 0/50 [00:00<?, ?it/s]

trial 526:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:04:47,106] Trial 526 pruned.
[I 2026-09-14 01:04:47,111] Trial 527 pruned.

trial 528:   0%|          | 0/50 [00:00<?, ?it/s]

trial 529:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:04:49,252] Trial 528 pruned.
[I 2026-09-14 01:04:49,257] Trial 529 pruned.

trial 530:   0%|          | 0/50 [00:00<?, ?it/s]

trial 531:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:04:50,736] Trial 530 pruned.
[I 2026-09-14 01:04:51,337] Trial 531 pruned.

trial 532:   0%|          | 0/50 [00:00<?, ?it/s]

trial 533:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:04:53,004] Trial 532 pruned.
[I 2026-09-14 01:04:53,504] Trial 533 pruned.

trial 534:   0%|          | 0/50 [00:00<?, ?it/s]

trial 535:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:04:54,707] Trial 534 pruned.
[I 2026-09-14 01:04:55,671] Trial 535 pruned.

trial 536:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:04:56,827] Trial 536 pruned.
[I 2026-09-14 01:04:56,975] Trial 519 finished with value: 0.10867054201218557 and parameters: {'alpha': 0.0010603271702134284, 'l1_ratio': 0.6947988064755967}. Best is trial 145 with value: 0.10822154579479654.

trial 537:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:04:57,554] Trial 537 pruned.

trial 538:   0%|          | 0/50 [00:00<?, ?it/s]

trial 539:   0%|          | 0/50 [00:00<?, ?it/s]

trial 540:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:04:58,812] Trial 539 pruned.
[I 2026-09-14 01:04:59,628] Trial 540 pruned.

trial 541:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:00,331] Trial 541 pruned.

trial 542:   0%|          | 0/50 [00:00<?, ?it/s]

trial 543:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:02,260] Trial 542 pruned.
[I 2026-09-14 01:05:02,285] Trial 543 pruned.
[I 2026-09-14 01:05:02,991] Trial 520 finished with value: 0.10944801287781321 and parameters: {'alpha': 0.001898910815030746, 'l1_ratio': 0.5179493432734478}. Best is trial 145 with value: 0.10822154579479654.

trial 544:   0%|          | 0/50 [00:00<?, ?it/s]

trial 545:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:03,948] Trial 544 pruned.
[I 2026-09-14 01:05:04,026] Trial 545 pruned.

trial 546:   0%|          | 0/50 [00:00<?, ?it/s]

trial 547:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:04,715] Trial 546 pruned.

trial 548:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:05,431] Trial 547 pruned.
[I 2026-09-14 01:05:05,437] Trial 548 pruned.

trial 549:   0%|          | 0/50 [00:00<?, ?it/s]

trial 550:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:06,227] Trial 549 pruned.

trial 551:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:07,287] Trial 550 pruned.

trial 552:   0%|          | 0/50 [00:00<?, ?it/s]

trial 553:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:08,571] Trial 552 pruned.
[I 2026-09-14 01:05:09,234] Trial 553 pruned.

trial 554:   0%|          | 0/50 [00:00<?, ?it/s]

trial 555:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:11,102] Trial 554 pruned.
[I 2026-09-14 01:05:11,269] Trial 555 pruned.

trial 556:   0%|          | 0/50 [00:00<?, ?it/s]

trial 557:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:12,558] Trial 556 pruned.
[I 2026-09-14 01:05:13,321] Trial 557 pruned.

trial 558:   0%|          | 0/50 [00:00<?, ?it/s]

trial 559:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:15,319] Trial 558 pruned.
[I 2026-09-14 01:05:15,369] Trial 559 pruned.

trial 560:   0%|          | 0/50 [00:00<?, ?it/s]

trial 561:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:17,869] Trial 561 pruned.

trial 562:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:20,255] Trial 562 pruned.

trial 563:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:22,810] Trial 563 pruned.

trial 564:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:25,300] Trial 564 pruned.

trial 565:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:27,827] Trial 565 pruned.

trial 566:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:30,001] Trial 566 pruned.
[I 2026-09-14 01:05:30,375] Trial 538 finished with value: 0.1087110012255722 and parameters: {'alpha': 0.001321917920377353, 'l1_ratio': 0.5558845150278545}. Best is trial 145 with value: 0.10822154579479654.

trial 568:   0%|          | 0/50 [00:00<?, ?it/s]

trial 567:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:32,353] Trial 567 pruned.
[I 2026-09-14 01:05:32,402] Trial 568 pruned.

trial 569:   0%|          | 0/50 [00:00<?, ?it/s]

trial 570:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:34,069] Trial 570 pruned.
[I 2026-09-14 01:05:34,085] Trial 569 pruned.

trial 572:   0%|          | 0/50 [00:00<?, ?it/s]

trial 571:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:36,646] Trial 571 pruned.

trial 573:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:39,118] Trial 573 pruned.

trial 574:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:41,009] Trial 574 pruned.
[I 2026-09-14 01:05:41,376] Trial 551 finished with value: 0.10959183914632822 and parameters: {'alpha': 0.0016921041633437492, 'l1_ratio': 0.6150809141049076}. Best is trial 145 with value: 0.10822154579479654.

trial 575:   0%|          | 0/50 [00:00<?, ?it/s]

trial 576:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:43,213] Trial 575 pruned.
[I 2026-09-14 01:05:43,227] Trial 576 pruned.

trial 577:   0%|          | 0/50 [00:00<?, ?it/s]

trial 578:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:45,346] Trial 577 pruned.

trial 579:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:47,538] Trial 579 pruned.

trial 580:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:52,775] Trial 560 finished with value: 0.10855593117821534 and parameters: {'alpha': 0.0013616103002042459, 'l1_ratio': 0.474265418864343}. Best is trial 145 with value: 0.10822154579479654.

trial 581:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:55,706] Trial 581 pruned.

trial 582:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:05:57,895] Trial 582 pruned.

trial 583:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:06:00,297] Trial 583 pruned.

trial 584:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:06:02,703] Trial 584 pruned.

trial 585:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:06:15,567] Trial 572 finished with value: 0.1088219438105326 and parameters: {'alpha': 0.0011215878483569585, 'l1_ratio': 0.7237595904913318}. Best is trial 145 with value: 0.10822154579479654.

trial 586:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:06:23,684] Trial 578 finished with value: 0.10885309790978233 and parameters: {'alpha': 0.0013360506556620753, 'l1_ratio': 0.6047345152126699}. Best is trial 145 with value: 0.10822154579479654.

trial 587:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:06:32,413] Trial 580 finished with value: 0.10866429434291991 and parameters: {'alpha': 0.0013444685293186012, 'l1_ratio': 0.5272939353534281}. Best is trial 145 with value: 0.10822154579479654.

trial 588:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:06:34,979] Trial 588 pruned.

trial 589:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:06:37,699] Trial 589 pruned.

trial 590:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:06:40,551] Trial 590 pruned.

trial 591:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:06:42,933] Trial 591 pruned.
[I 2026-09-14 01:06:43,862] Trial 585 finished with value: 0.10855792866287965 and parameters: {'alpha': 0.0010299728381994067, 'l1_ratio': 0.6586540994514437}. Best is trial 145 with value: 0.10822154579479654.

trial 592:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:06:44,833] Trial 592 pruned.

trial 593:   0%|          | 0/50 [00:00<?, ?it/s]

trial 594:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:06:46,915] Trial 594 pruned.

trial 595:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:06:48,843] Trial 595 pruned.

trial 596:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:06:51,896] Trial 596 pruned.

trial 597:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:06:54,725] Trial 597 pruned.

trial 598:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:06:56,607] Trial 586 finished with value: 0.10871898262911352 and parameters: {'alpha': 0.0017081572449902228, 'l1_ratio': 0.4101662323542765}. Best is trial 145 with value: 0.10822154579479654.
[I 2026-09-14 01:06:57,234] Trial 598 pruned.

trial 599:   0%|          | 0/50 [00:00<?, ?it/s]

trial 600:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:06:59,104] Trial 599 pruned.
[I 2026-09-14 01:06:59,448] Trial 600 pruned.

trial 601:   0%|          | 0/50 [00:00<?, ?it/s]

trial 602:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:01,130] Trial 601 pruned.
[I 2026-09-14 01:07:01,448] Trial 602 pruned.
[I 2026-09-14 01:07:01,553] Trial 587 finished with value: 0.10885484465060324 and parameters: {'alpha': 0.0010581749525550813, 'l1_ratio': 0.7863256135766119}. Best is trial 145 with value: 0.10822154579479654.

trial 603:   0%|          | 0/50 [00:00<?, ?it/s]

trial 604:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:02,499] Trial 603 pruned.

trial 605:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:03,189] Trial 604 pruned.
[I 2026-09-14 01:07:03,315] Trial 605 pruned.

trial 606:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:03,851] Trial 606 pruned.

trial 607:   0%|          | 0/50 [00:00<?, ?it/s]

trial 608:   0%|          | 0/50 [00:00<?, ?it/s]

trial 609:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:04,645] Trial 607 pruned.
[I 2026-09-14 01:07:05,214] Trial 609 pruned.

trial 610:   0%|          | 0/50 [00:00<?, ?it/s]

trial 611:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:06,860] Trial 610 pruned.
[I 2026-09-14 01:07:07,532] Trial 611 pruned.

trial 612:   0%|          | 0/50 [00:00<?, ?it/s]

trial 613:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:09,110] Trial 612 pruned.
[I 2026-09-14 01:07:09,117] Trial 613 pruned.

trial 614:   0%|          | 0/50 [00:00<?, ?it/s]

trial 615:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:11,551] Trial 614 pruned.
[I 2026-09-14 01:07:11,581] Trial 615 pruned.

trial 616:   0%|          | 0/50 [00:00<?, ?it/s]

trial 617:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:12,902] Trial 616 pruned.
[I 2026-09-14 01:07:13,708] Trial 617 pruned.

trial 618:   0%|          | 0/50 [00:00<?, ?it/s]

trial 619:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:15,847] Trial 619 pruned.
[I 2026-09-14 01:07:16,844] Trial 593 finished with value: 0.10910281722438019 and parameters: {'alpha': 0.0015672286950471842, 'l1_ratio': 0.5699635595053341}. Best is trial 145 with value: 0.10822154579479654.

trial 620:   0%|          | 0/50 [00:00<?, ?it/s]

trial 621:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:19,058] Trial 621 pruned.

trial 622:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:20,838] Trial 622 pruned.

trial 623:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:24,342] Trial 623 pruned.

trial 624:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:26,293] Trial 624 pruned.

trial 625:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:28,716] Trial 625 pruned.

trial 626:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:31,171] Trial 626 pruned.

trial 627:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:41,017] Trial 608 finished with value: 0.10861875126684213 and parameters: {'alpha': 0.0011877663292396167, 'l1_ratio': 0.5887659380417898}. Best is trial 145 with value: 0.10822154579479654.

trial 628:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:43,886] Trial 628 pruned.

trial 629:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:46,089] Trial 629 pruned.

trial 630:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:48,583] Trial 630 pruned.

trial 631:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:51,563] Trial 631 pruned.

trial 632:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:53,937] Trial 618 finished with value: 0.1085936439540961 and parameters: {'alpha': 0.0012124989754947186, 'l1_ratio': 0.5635041169663155}. Best is trial 145 with value: 0.10822154579479654.

trial 633:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:56,354] Trial 633 pruned.
[I 2026-09-14 01:07:56,722] Trial 620 finished with value: 0.10893002102458933 and parameters: {'alpha': 0.001624447033650322, 'l1_ratio': 0.5024662289685349}. Best is trial 145 with value: 0.10822154579479654.

trial 635:   0%|          | 0/50 [00:00<?, ?it/s]

trial 634:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:07:58,555] Trial 634 pruned.
[I 2026-09-14 01:07:58,826] Trial 635 pruned.

trial 636:   0%|          | 0/50 [00:00<?, ?it/s]

trial 637:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:00,964] Trial 637 pruned.
[I 2026-09-14 01:08:00,994] Trial 636 pruned.

trial 638:   0%|          | 0/50 [00:00<?, ?it/s]

trial 639:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:02,618] Trial 638 pruned.
[I 2026-09-14 01:08:03,393] Trial 639 pruned.

trial 640:   0%|          | 0/50 [00:00<?, ?it/s]

trial 641:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:04,958] Trial 640 pruned.
[I 2026-09-14 01:08:05,911] Trial 641 pruned.

trial 642:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:07,205] Trial 642 pruned.

trial 643:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:08,458] Trial 643 pruned.

trial 644:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:09,131] Trial 644 pruned.
[I 2026-09-14 01:08:09,358] Trial 627 finished with value: 0.10854292871114399 and parameters: {'alpha': 0.0010723456775979694, 'l1_ratio': 0.6212560220218881}. Best is trial 145 with value: 0.10822154579479654.

trial 645:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:10,173] Trial 645 pruned.

trial 647:   0%|          | 0/50 [00:00<?, ?it/s]

trial 646:   0%|          | 0/50 [00:00<?, ?it/s]

trial 648:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:11,823] Trial 648 pruned.

trial 649:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:14,284] Trial 649 pruned.

trial 650:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:16,624] Trial 650 pruned.

trial 651:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:19,903] Trial 651 pruned.

trial 652:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:30,576] Trial 632 finished with value: 0.10903664448623024 and parameters: {'alpha': 0.0015756611546351008, 'l1_ratio': 0.5501254595677658}. Best is trial 145 with value: 0.10822154579479654.

trial 653:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:32,933] Trial 653 pruned.

trial 654:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:35,287] Trial 654 pruned.

trial 655:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:37,814] Trial 655 pruned.

trial 656:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:40,435] Trial 656 pruned.

trial 657:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:43,112] Trial 657 pruned.

trial 658:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:45,771] Trial 658 pruned.

trial 659:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:48,278] Trial 659 pruned.
[I 2026-09-14 01:08:49,207] Trial 647 finished with value: 0.10860552396498871 and parameters: {'alpha': 0.001449012126829995, 'l1_ratio': 0.4600370352469135}. Best is trial 145 with value: 0.10822154579479654.

trial 660:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:49,894] Trial 646 finished with value: 0.10867248235202764 and parameters: {'alpha': 0.0013625441315992814, 'l1_ratio': 0.5220823863553496}. Best is trial 145 with value: 0.10822154579479654.

trial 661:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:50,138] Trial 660 pruned.
[I 2026-09-14 01:08:50,648] Trial 661 pruned.

trial 662:   0%|          | 0/50 [00:00<?, ?it/s]

trial 663:   0%|          | 0/50 [00:00<?, ?it/s]

trial 664:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:52,493] Trial 663 pruned.

trial 665:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:55,196] Trial 665 pruned.

trial 666:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:57,728] Trial 666 pruned.

trial 667:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:08:59,404] Trial 667 pruned.
[I 2026-09-14 01:09:00,760] Trial 652 finished with value: 0.11015925985846016 and parameters: {'alpha': 0.007968905815331988, 'l1_ratio': 0.10442291788583469}. Best is trial 145 with value: 0.10822154579479654.

trial 668:   0%|          | 0/50 [00:00<?, ?it/s]

trial 669:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:09:03,094] Trial 669 pruned.

trial 670:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:09:06,111] Trial 670 pruned.

trial 671:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:09:08,091] Trial 671 pruned.

trial 672:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:09:10,479] Trial 672 pruned.

trial 673:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:09:12,996] Trial 673 pruned.

trial 674:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:09:15,529] Trial 674 pruned.

trial 675:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-09-14 01:09:30,600] Trial 662 finished with value: 0.10863213474123333 and parameters: {'alpha': 0.0008772921606908323, 'l1_ratio': 0.83038178104139}. Best is trial 145 with value: 0.10822154579479654.
[I 2026-09-14 01:09:31,998] Trial 664 finished with value: 0.1090380283559309 and parameters: {'alpha': 0.001947152817934102, 'l1_ratio': 0.4270376538605576}. Best is trial 145 with value: 0.10822154579479654.
[I 2026-09-14 01:09:36,490] Trial 668 finished with value: 0.10914855285946955 and parameters: {'alpha': 0.0015500207960085534, 'l1_ratio': 0.5877762485540646}. Best is trial 145 with value: 0.10822154579479654.
[I 2026-09-14 01:09:40,332] Trial 675 finished with value: 0.10876000259422909 and parameters: {'alpha': 0.001382056682625172, 'l1_ratio': 0.5461359489258205}. Best is trial 145 with value: 0.10822154579479654.

trial 2:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:09:55,165] Trial 2 finished with value: 0.11974234799468302 and parameters: {'num_leaves': 43, 'max_depth': 8, 'learning_rate': 0.005553764029861861, 'min_child_samples': 21, 'subsample': 0.8426384908486563, 'subsample_freq': 6, 'colsample_bytree': 0.5841797318033427, 'reg_alpha': 1.1028532241013205, 'reg_lambda': 0.03118133864355715}. Best is trial 2 with value: 0.11974234799468302.

trial 3:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:10:00,585] Trial 3 finished with value: 0.11728842065465508 and parameters: {'num_leaves': 13, 'max_depth': 8, 'learning_rate': 0.018327638898495667, 'min_child_samples': 22, 'subsample': 0.8928008809321795, 'subsample_freq': 7, 'colsample_bytree': 0.5394121970888565, 'reg_alpha': 5.650057960050972e-08, 'reg_lambda': 0.0027035586822681547}. Best is trial 3 with value: 0.11728842065465508.

trial 4:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:10:08,214] Trial 4 finished with value: 0.15334301262822153 and parameters: {'num_leaves': 94, 'max_depth': 5, 'learning_rate': 0.0626429000963665, 'min_child_samples': 54, 'subsample': 0.5242422687132002, 'subsample_freq': 1, 'colsample_bytree': 0.5121804556827526, 'reg_alpha': 8.889167922254462, 'reg_lambda': 0.0004852757284257302}. Best is trial 3 with value: 0.11728842065465508.

trial 5:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:10:12,721] Trial 5 finished with value: 0.13348294678228623 and parameters: {'num_leaves': 54, 'max_depth': 10, 'learning_rate': 0.03691690436166197, 'min_child_samples': 92, 'subsample': 0.9039600754939585, 'subsample_freq': 3, 'colsample_bytree': 0.6143346056924728, 'reg_alpha': 3.7660877284938508, 'reg_lambda': 1.237896118074375e-05}. Best is trial 3 with value: 0.11728842065465508.

trial 6:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:10:16,865] Trial 6 finished with value: 0.1295707348215474 and parameters: {'num_leaves': 156, 'max_depth': 11, 'learning_rate': 0.0364029794953107, 'min_child_samples': 93, 'subsample': 0.5485732398825078, 'subsample_freq': 0, 'colsample_bytree': 0.8209043774174954, 'reg_alpha': 1.033519849907543, 'reg_lambda': 2.7292461609423586e-07}. Best is trial 3 with value: 0.11728842065465508.

trial 7:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:10:24,341] Trial 7 finished with value: 0.12592831962860762 and parameters: {'num_leaves': 18, 'max_depth': 9, 'learning_rate': 0.009166287310865457, 'min_child_samples': 72, 'subsample': 0.743817611102864, 'subsample_freq': 5, 'colsample_bytree': 0.7129289153955156, 'reg_alpha': 2.4579341856167136e-08, 'reg_lambda': 1.0361662241687912e-06}. Best is trial 3 with value: 0.11728842065465508.

trial 8:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:10:28,454] Trial 8 finished with value: 0.11864642085564717 and parameters: {'num_leaves': 54, 'max_depth': 4, 'learning_rate': 0.03163639450260956, 'min_child_samples': 18, 'subsample': 0.5264042005446331, 'subsample_freq': 1, 'colsample_bytree': 0.6654208789076469, 'reg_alpha': 0.7911993497243279, 'reg_lambda': 3.4944365633452965}. Best is trial 3 with value: 0.11728842065465508.

trial 9:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:10:32,135] Trial 9 finished with value: 0.122914896775456 and parameters: {'num_leaves': 38, 'max_depth': 7, 'learning_rate': 0.05247413204861301, 'min_child_samples': 36, 'subsample': 0.5587890465139971, 'subsample_freq': 0, 'colsample_bytree': 0.7825951916906952, 'reg_alpha': 0.20435866371403186, 'reg_lambda': 0.010773176696694801}. Best is trial 3 with value: 0.11728842065465508.

trial 10:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:10:35,711] Trial 10 finished with value: 0.12156136598191458 and parameters: {'num_leaves': 71, 'max_depth': 7, 'learning_rate': 0.05634756107386424, 'min_child_samples': 25, 'subsample': 0.8299622594335837, 'subsample_freq': 4, 'colsample_bytree': 0.8491122219102955, 'reg_alpha': 6.979297368822564e-08, 'reg_lambda': 0.11499968474000738}. Best is trial 3 with value: 0.11728842065465508.

trial 11:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:10:40,182] Trial 11 finished with value: 0.13116764292930802 and parameters: {'num_leaves': 81, 'max_depth': 9, 'learning_rate': 0.03125935239386002, 'min_child_samples': 98, 'subsample': 0.6017638103007605, 'subsample_freq': 2, 'colsample_bytree': 0.5365935356765159, 'reg_alpha': 2.7134384139169515e-08, 'reg_lambda': 1.3669172276235095}. Best is trial 3 with value: 0.11728842065465508.

trial 12:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:10:46,776] Trial 12 pruned.

trial 13:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:10:50,769] Trial 13 finished with value: 0.11569581737803518 and parameters: {'num_leaves': 7, 'max_depth': 6, 'learning_rate': 0.030972914799167067, 'min_child_samples': 11, 'subsample': 0.9622020176355737, 'subsample_freq': 6, 'colsample_bytree': 0.49376646066203883, 'reg_alpha': 0.0008020020059636961, 'reg_lambda': 0.07932146316672259}. Best is trial 13 with value: 0.11569581737803518.

trial 14:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:10:53,657] Trial 14 finished with value: 0.11743234435049507 and parameters: {'num_leaves': 12, 'max_depth': 3, 'learning_rate': 0.09514016685268215, 'min_child_samples': 14, 'subsample': 0.9340969261601128, 'subsample_freq': 6, 'colsample_bytree': 0.4222122206386368, 'reg_alpha': 0.0004495975100621287, 'reg_lambda': 0.00416218826905454}. Best is trial 13 with value: 0.11569581737803518.

trial 15:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:10:58,261] Trial 15 finished with value: 0.11775110479039404 and parameters: {'num_leaves': 7, 'max_depth': 4, 'learning_rate': 0.022577113494418394, 'min_child_samples': 21, 'subsample': 0.9981655070161961, 'subsample_freq': 6, 'colsample_bytree': 0.40770320648919106, 'reg_alpha': 9.342026266624081e-07, 'reg_lambda': 5.507434291854446}. Best is trial 13 with value: 0.11569581737803518.

trial 16:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:11:03,553] Trial 16 finished with value: 0.11579772637414505 and parameters: {'num_leaves': 7, 'max_depth': 9, 'learning_rate': 0.017037503191797084, 'min_child_samples': 20, 'subsample': 0.9811538218156688, 'subsample_freq': 6, 'colsample_bytree': 0.46274749737889564, 'reg_alpha': 0.001776373823308131, 'reg_lambda': 4.554210211320963e-05}. Best is trial 13 with value: 0.11569581737803518.

trial 17:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:11:07,745] Trial 17 finished with value: 0.11473952124357903 and parameters: {'num_leaves': 13, 'max_depth': 5, 'learning_rate': 0.03280156747732789, 'min_child_samples': 9, 'subsample': 0.8754915269993226, 'subsample_freq': 7, 'colsample_bytree': 0.5401154770752743, 'reg_alpha': 0.006204630885821621, 'reg_lambda': 1.4397331959056827}. Best is trial 17 with value: 0.11473952124357903.

trial 18:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:11:11,493] Trial 18 finished with value: 0.11529439223259481 and parameters: {'num_leaves': 9, 'max_depth': 8, 'learning_rate': 0.04182565155043087, 'min_child_samples': 10, 'subsample': 0.9102016057336159, 'subsample_freq': 6, 'colsample_bytree': 0.6220431656447531, 'reg_alpha': 0.15769939580928402, 'reg_lambda': 0.527284648379596}. Best is trial 17 with value: 0.11473952124357903.

trial 19:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:11:16,168] Trial 19 finished with value: 0.11759793030599575 and parameters: {'num_leaves': 7, 'max_depth': 8, 'learning_rate': 0.024498007545009932, 'min_child_samples': 15, 'subsample': 0.840767425399559, 'subsample_freq': 7, 'colsample_bytree': 0.6322419737394109, 'reg_alpha': 0.5909003788137724, 'reg_lambda': 4.394173030419707}. Best is trial 17 with value: 0.11473952124357903.

trial 20:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:11:19,502] Trial 20 pruned.

trial 21:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:11:22,317] Trial 21 finished with value: 0.11802552016565812 and parameters: {'num_leaves': 7, 'max_depth': 5, 'learning_rate': 0.1376540171443672, 'min_child_samples': 12, 'subsample': 0.8689521773946689, 'subsample_freq': 6, 'colsample_bytree': 0.7215623107952239, 'reg_alpha': 0.04036450487342145, 'reg_lambda': 1.4454463299671372}. Best is trial 17 with value: 0.11473952124357903.

trial 22:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:11:27,135] Trial 22 finished with value: 0.11580003811580135 and parameters: {'num_leaves': 18, 'max_depth': 5, 'learning_rate': 0.029324316325948716, 'min_child_samples': 7, 'subsample': 0.9438023393371844, 'subsample_freq': 5, 'colsample_bytree': 0.5291958893030166, 'reg_alpha': 0.0012295797973309408, 'reg_lambda': 0.624316309569271}. Best is trial 17 with value: 0.11473952124357903.

trial 23:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:11:31,888] Trial 23 finished with value: 0.11694041583712711 and parameters: {'num_leaves': 19, 'max_depth': 7, 'learning_rate': 0.027911010551781197, 'min_child_samples': 12, 'subsample': 0.9694834150908574, 'subsample_freq': 7, 'colsample_bytree': 0.5286127160053329, 'reg_alpha': 0.02222622336967997, 'reg_lambda': 0.005485553408958008}. Best is trial 17 with value: 0.11473952124357903.

trial 24:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:11:34,108] Trial 24 pruned.

trial 25:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:11:38,603] Trial 25 finished with value: 0.11463615472949462 and parameters: {'num_leaves': 7, 'max_depth': 4, 'learning_rate': 0.015959148548699613, 'min_child_samples': 13, 'subsample': 0.7980978086005135, 'subsample_freq': 5, 'colsample_bytree': 0.5346582508194228, 'reg_alpha': 0.0001373043235617372, 'reg_lambda': 0.24291809495579064}. Best is trial 25 with value: 0.11463615472949462.

trial 26:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:11:43,827] Trial 26 finished with value: 0.11678509258569858 and parameters: {'num_leaves': 19, 'max_depth': 7, 'learning_rate': 0.038560139990370224, 'min_child_samples': 7, 'subsample': 0.8764403692461601, 'subsample_freq': 5, 'colsample_bytree': 0.6575768475960283, 'reg_alpha': 0.0020509355561358074, 'reg_lambda': 5.238533322796196}. Best is trial 25 with value: 0.11463615472949462.

trial 27:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:11:48,436] Trial 27 pruned.

trial 28:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:11:54,710] Trial 28 finished with value: 0.11253918950532307 and parameters: {'num_leaves': 10, 'max_depth': 3, 'learning_rate': 0.009698503372179305, 'min_child_samples': 7, 'subsample': 0.7387318057364348, 'subsample_freq': 6, 'colsample_bytree': 0.42125338229870696, 'reg_alpha': 0.00030477278332171205, 'reg_lambda': 0.7590152102666399}. Best is trial 28 with value: 0.11253918950532307.

trial 29:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:11:58,860] Trial 29 finished with value: 0.11633875687380466 and parameters: {'num_leaves': 8, 'max_depth': 4, 'learning_rate': 0.02384581328203134, 'min_child_samples': 20, 'subsample': 0.7277829375486026, 'subsample_freq': 5, 'colsample_bytree': 0.47432195030140056, 'reg_alpha': 0.00011284430198791345, 'reg_lambda': 0.2881091320110088}. Best is trial 28 with value: 0.11253918950532307.

trial 30:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:12:02,743] Trial 30 finished with value: 0.11505793079313813 and parameters: {'num_leaves': 7, 'max_depth': 5, 'learning_rate': 0.030821061588667802, 'min_child_samples': 6, 'subsample': 0.9588076892738131, 'subsample_freq': 7, 'colsample_bytree': 0.5126695181263361, 'reg_alpha': 0.12229458053691089, 'reg_lambda': 0.7660406116748745}. Best is trial 28 with value: 0.11253918950532307.

trial 31:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:12:10,436] Trial 31 finished with value: 0.1129787616837478 and parameters: {'num_leaves': 9, 'max_depth': 3, 'learning_rate': 0.006447373440782586, 'min_child_samples': 5, 'subsample': 0.7334332850097467, 'subsample_freq': 6, 'colsample_bytree': 0.5314455664797202, 'reg_alpha': 0.00020937858199415036, 'reg_lambda': 1.416561025664698}. Best is trial 28 with value: 0.11253918950532307.

trial 32:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:12:17,363] Trial 32 finished with value: 0.1151475978342555 and parameters: {'num_leaves': 9, 'max_depth': 4, 'learning_rate': 0.009944354413217858, 'min_child_samples': 14, 'subsample': 0.7721183514304915, 'subsample_freq': 5, 'colsample_bytree': 0.4540137165615613, 'reg_alpha': 2.2086391137285407e-05, 'reg_lambda': 7.991853262233886}. Best is trial 28 with value: 0.11253918950532307.

trial 33:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:12:24,386] Trial 33 finished with value: 0.11469864081164068 and parameters: {'num_leaves': 11, 'max_depth': 6, 'learning_rate': 0.007757149886226675, 'min_child_samples': 13, 'subsample': 0.6459471662908631, 'subsample_freq': 7, 'colsample_bytree': 0.5385141428023431, 'reg_alpha': 1.3680614172948689e-05, 'reg_lambda': 0.7387576290820056}. Best is trial 28 with value: 0.11253918950532307.

trial 34:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:12:29,740] Trial 34 finished with value: 0.11454578418200376 and parameters: {'num_leaves': 7, 'max_depth': 4, 'learning_rate': 0.010874201198290818, 'min_child_samples': 9, 'subsample': 0.749884064264223, 'subsample_freq': 6, 'colsample_bytree': 0.633587966254205, 'reg_alpha': 4.768254803106961e-05, 'reg_lambda': 0.8347512409938751}. Best is trial 28 with value: 0.11253918950532307.

trial 35:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:12:34,428] Trial 35 finished with value: 0.11672681846491188 and parameters: {'num_leaves': 10, 'max_depth': 3, 'learning_rate': 0.013258600880537876, 'min_child_samples': 27, 'subsample': 0.8140199914714741, 'subsample_freq': 6, 'colsample_bytree': 0.48764359143356445, 'reg_alpha': 0.004727595327123917, 'reg_lambda': 0.18160962443683884}. Best is trial 28 with value: 0.11253918950532307.

trial 36:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:12:40,394] Trial 36 finished with value: 0.11324203639545138 and parameters: {'num_leaves': 7, 'max_depth': 3, 'learning_rate': 0.008825640679874088, 'min_child_samples': 7, 'subsample': 0.7493654676494326, 'subsample_freq': 5, 'colsample_bytree': 0.5582325282285904, 'reg_alpha': 0.0011205630263550338, 'reg_lambda': 0.16501291165052143}. Best is trial 28 with value: 0.11253918950532307.

trial 37:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:12:45,847] Trial 37 finished with value: 0.11279470270068086 and parameters: {'num_leaves': 8, 'max_depth': 3, 'learning_rate': 0.010982478394949705, 'min_child_samples': 7, 'subsample': 0.8124185070668898, 'subsample_freq': 7, 'colsample_bytree': 0.4505890439824186, 'reg_alpha': 0.0003417772149062413, 'reg_lambda': 0.048035287341513896}. Best is trial 28 with value: 0.11253918950532307.

trial 38:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:12:50,619] Trial 38 finished with value: 0.11609047445320797 and parameters: {'num_leaves': 14, 'max_depth': 3, 'learning_rate': 0.014851445576885244, 'min_child_samples': 25, 'subsample': 0.7671294998674729, 'subsample_freq': 7, 'colsample_bytree': 0.4059631767522822, 'reg_alpha': 0.000890287378896096, 'reg_lambda': 2.1299949887441905}. Best is trial 28 with value: 0.11253918950532307.

trial 39:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:12:54,716] Trial 39 finished with value: 0.11344262504117683 and parameters: {'num_leaves': 10, 'max_depth': 3, 'learning_rate': 0.017735952476544407, 'min_child_samples': 5, 'subsample': 0.7204747312959651, 'subsample_freq': 6, 'colsample_bytree': 0.4878056447642262, 'reg_alpha': 6.552371454273179e-05, 'reg_lambda': 0.36648215465242134}. Best is trial 28 with value: 0.11253918950532307.

trial 40:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:13:01,549] Trial 40 finished with value: 0.11369452533936367 and parameters: {'num_leaves': 8, 'max_depth': 4, 'learning_rate': 0.008409440252230465, 'min_child_samples': 10, 'subsample': 0.7514333807104725, 'subsample_freq': 5, 'colsample_bytree': 0.44780913631984104, 'reg_alpha': 0.009641584988630837, 'reg_lambda': 0.9340521683215695}. Best is trial 28 with value: 0.11253918950532307.

trial 41:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:13:07,050] Trial 41 finished with value: 0.11485525453875922 and parameters: {'num_leaves': 9, 'max_depth': 3, 'learning_rate': 0.011068601765617825, 'min_child_samples': 18, 'subsample': 0.8551280558458343, 'subsample_freq': 7, 'colsample_bytree': 0.5582072616443288, 'reg_alpha': 3.596557365067787e-05, 'reg_lambda': 0.20998977673237465}. Best is trial 28 with value: 0.11253918950532307.

trial 42:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:13:12,321] Trial 42 finished with value: 0.11459244671963312 and parameters: {'num_leaves': 13, 'max_depth': 3, 'learning_rate': 0.009422861043814129, 'min_child_samples': 15, 'subsample': 0.648947173547182, 'subsample_freq': 5, 'colsample_bytree': 0.543029039942994, 'reg_alpha': 6.593619161128408e-05, 'reg_lambda': 0.8363309800122978}. Best is trial 28 with value: 0.11253918950532307.

trial 43:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:13:21,063] Trial 43 finished with value: 0.11334863947491862 and parameters: {'num_leaves': 13, 'max_depth': 4, 'learning_rate': 0.005983092763179366, 'min_child_samples': 5, 'subsample': 0.7396159968981171, 'subsample_freq': 6, 'colsample_bytree': 0.4215151972627699, 'reg_alpha': 0.00011567913356507719, 'reg_lambda': 1.1450178658420955}. Best is trial 28 with value: 0.11253918950532307.

trial 44:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:13:27,733] Trial 44 finished with value: 0.11502481765153769 and parameters: {'num_leaves': 7, 'max_depth': 4, 'learning_rate': 0.009746417325590886, 'min_child_samples': 20, 'subsample': 0.8389134898649782, 'subsample_freq': 5, 'colsample_bytree': 0.4328324882585964, 'reg_alpha': 0.004837209244704729, 'reg_lambda': 0.04927974292896395}. Best is trial 28 with value: 0.11253918950532307.

trial 45:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:13:30,240] Trial 45 pruned.

trial 46:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:13:37,164] Trial 46 finished with value: 0.1139119768193246 and parameters: {'num_leaves': 7, 'max_depth': 3, 'learning_rate': 0.006409910655462146, 'min_child_samples': 14, 'subsample': 0.6682880763319073, 'subsample_freq': 5, 'colsample_bytree': 0.5221909617243667, 'reg_alpha': 0.0002010503128212477, 'reg_lambda': 0.2527435074436803}. Best is trial 28 with value: 0.11253918950532307.

trial 47:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:13:42,356] Trial 47 finished with value: 0.1135290578819719 and parameters: {'num_leaves': 9, 'max_depth': 3, 'learning_rate': 0.012058353371019175, 'min_child_samples': 12, 'subsample': 0.7285146899361534, 'subsample_freq': 7, 'colsample_bytree': 0.4483332412033114, 'reg_alpha': 0.0016507973833564027, 'reg_lambda': 0.3795442732050207}. Best is trial 28 with value: 0.11253918950532307.

trial 48:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:13:49,155] Trial 48 finished with value: 0.1133885404908113 and parameters: {'num_leaves': 12, 'max_depth': 4, 'learning_rate': 0.01045793873973, 'min_child_samples': 5, 'subsample': 0.8154982149782435, 'subsample_freq': 6, 'colsample_bytree': 0.45799630758955406, 'reg_alpha': 0.00138225254379659, 'reg_lambda': 0.7664859286130542}. Best is trial 28 with value: 0.11253918950532307.

trial 49:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:13:57,910] Trial 49 finished with value: 0.11350601505624036 and parameters: {'num_leaves': 11, 'max_depth': 5, 'learning_rate': 0.006077746414594975, 'min_child_samples': 8, 'subsample': 0.7270374486542142, 'subsample_freq': 5, 'colsample_bytree': 0.5092519859393071, 'reg_alpha': 3.163189379533507e-05, 'reg_lambda': 1.5108020598821714}. Best is trial 28 with value: 0.11253918950532307.

trial 50:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:14:07,702] Trial 50 finished with value: 0.11462097410719499 and parameters: {'num_leaves': 9, 'max_depth': 3, 'learning_rate': 0.005034286478943552, 'min_child_samples': 12, 'subsample': 0.7647918191774742, 'subsample_freq': 6, 'colsample_bytree': 0.4938445124400519, 'reg_alpha': 0.001031545647940551, 'reg_lambda': 5.904064542870312}. Best is trial 28 with value: 0.11253918950532307.

trial 51:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:14:16,087] Trial 51 finished with value: 0.11457794954969754 and parameters: {'num_leaves': 15, 'max_depth': 3, 'learning_rate': 0.006854757910717058, 'min_child_samples': 11, 'subsample': 0.770846733884508, 'subsample_freq': 5, 'colsample_bytree': 0.4919171620975541, 'reg_alpha': 1.9584386659390443e-05, 'reg_lambda': 6.396482095629476}. Best is trial 28 with value: 0.11253918950532307.

trial 52:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:14:24,362] Trial 52 finished with value: 0.11290308573247354 and parameters: {'num_leaves': 9, 'max_depth': 4, 'learning_rate': 0.006505764594231333, 'min_child_samples': 9, 'subsample': 0.7501794178083931, 'subsample_freq': 7, 'colsample_bytree': 0.4212342182210988, 'reg_alpha': 0.00014205694138637385, 'reg_lambda': 0.06418132640280336}. Best is trial 28 with value: 0.11253918950532307.

trial 53:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:14:32,846] Trial 53 finished with value: 0.11365201637827346 and parameters: {'num_leaves': 7, 'max_depth': 4, 'learning_rate': 0.005167010298711078, 'min_child_samples': 8, 'subsample': 0.746178371180501, 'subsample_freq': 6, 'colsample_bytree': 0.43558290043307163, 'reg_alpha': 2.6763828630307583e-05, 'reg_lambda': 0.7795658092527055}. Best is trial 28 with value: 0.11253918950532307.

trial 54:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:14:41,768] Trial 54 finished with value: 0.11347475959669143 and parameters: {'num_leaves': 11, 'max_depth': 5, 'learning_rate': 0.005371661590047032, 'min_child_samples': 11, 'subsample': 0.6868143139940859, 'subsample_freq': 7, 'colsample_bytree': 0.4588829137274818, 'reg_alpha': 0.0007552125196316138, 'reg_lambda': 0.08697392673862991}. Best is trial 28 with value: 0.11253918950532307.

trial 55:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:14:47,865] Trial 55 finished with value: 0.11259360992524343 and parameters: {'num_leaves': 13, 'max_depth': 3, 'learning_rate': 0.00846183676245209, 'min_child_samples': 7, 'subsample': 0.776965646016535, 'subsample_freq': 7, 'colsample_bytree': 0.4343931031908952, 'reg_alpha': 3.515961382690258e-05, 'reg_lambda': 0.300364382975131}. Best is trial 28 with value: 0.11253918950532307.

trial 56:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:14:54,065] Trial 56 finished with value: 0.11295383119495006 and parameters: {'num_leaves': 12, 'max_depth': 3, 'learning_rate': 0.010836242138261072, 'min_child_samples': 7, 'subsample': 0.7815192124183116, 'subsample_freq': 6, 'colsample_bytree': 0.5011183110526842, 'reg_alpha': 0.00018410638023334016, 'reg_lambda': 0.019176933304252006}. Best is trial 28 with value: 0.11253918950532307.

trial 57:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:14:59,342] Trial 57 finished with value: 0.11333790816305392 and parameters: {'num_leaves': 14, 'max_depth': 3, 'learning_rate': 0.011687441470432144, 'min_child_samples': 7, 'subsample': 0.8283702943758384, 'subsample_freq': 7, 'colsample_bytree': 0.45494567118532664, 'reg_alpha': 1.3608149405464541e-05, 'reg_lambda': 0.07059491839516294}. Best is trial 28 with value: 0.11253918950532307.

trial 58:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:15:05,967] Trial 58 finished with value: 0.11356020222817904 and parameters: {'num_leaves': 13, 'max_depth': 4, 'learning_rate': 0.010167687602105412, 'min_child_samples': 8, 'subsample': 0.7122884149846489, 'subsample_freq': 6, 'colsample_bytree': 0.4929442407427918, 'reg_alpha': 8.365381514151934e-05, 'reg_lambda': 2.7552100124284364}. Best is trial 28 with value: 0.11253918950532307.

trial 59:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:15:12,283] Trial 59 finished with value: 0.11352782588973831 and parameters: {'num_leaves': 8, 'max_depth': 4, 'learning_rate': 0.008957359215801285, 'min_child_samples': 9, 'subsample': 0.8458374056812394, 'subsample_freq': 7, 'colsample_bytree': 0.5001945171029011, 'reg_alpha': 0.0001064198042407368, 'reg_lambda': 0.011828418686496363}. Best is trial 28 with value: 0.11253918950532307.

trial 60:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:15:15,455] Trial 60 pruned.

trial 61:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:15:23,110] Trial 61 finished with value: 0.11375337474090126 and parameters: {'num_leaves': 9, 'max_depth': 3, 'learning_rate': 0.005185518498884153, 'min_child_samples': 13, 'subsample': 0.7294083314250848, 'subsample_freq': 7, 'colsample_bytree': 0.5006149060178028, 'reg_alpha': 8.876694356523753e-06, 'reg_lambda': 0.1232330729334693}. Best is trial 28 with value: 0.11253918950532307.

trial 62:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:15:28,483] Trial 62 finished with value: 0.11255716183416223 and parameters: {'num_leaves': 12, 'max_depth': 3, 'learning_rate': 0.01051450001232099, 'min_child_samples': 6, 'subsample': 0.7660387946727393, 'subsample_freq': 6, 'colsample_bytree': 0.4044963452206561, 'reg_alpha': 0.0027078550142703803, 'reg_lambda': 1.13656798087829}. Best is trial 28 with value: 0.11253918950532307.

trial 63:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:15:35,045] Trial 63 finished with value: 0.11392903203734146 and parameters: {'num_leaves': 10, 'max_depth': 4, 'learning_rate': 0.008508780273493298, 'min_child_samples': 15, 'subsample': 0.8000475206274332, 'subsample_freq': 6, 'colsample_bytree': 0.4168006814374803, 'reg_alpha': 0.00012460358166029644, 'reg_lambda': 0.7415934375190252}. Best is trial 28 with value: 0.11253918950532307.

trial 64:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:15:40,705] Trial 64 finished with value: 0.11254054064259147 and parameters: {'num_leaves': 9, 'max_depth': 3, 'learning_rate': 0.009427858384509883, 'min_child_samples': 8, 'subsample': 0.7694558230056232, 'subsample_freq': 6, 'colsample_bytree': 0.4278770797019547, 'reg_alpha': 0.00041182056611174567, 'reg_lambda': 0.014768979043342635}. Best is trial 28 with value: 0.11253918950532307.

trial 65:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:15:46,284] Trial 65 pruned.

trial 66:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:15:53,526] Trial 66 pruned.

trial 67:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:16:00,647] Trial 67 finished with value: 0.11293321209545422 and parameters: {'num_leaves': 7, 'max_depth': 3, 'learning_rate': 0.0067788629315453115, 'min_child_samples': 7, 'subsample': 0.7348542944472017, 'subsample_freq': 6, 'colsample_bytree': 0.43793826246034634, 'reg_alpha': 0.0005679966853782531, 'reg_lambda': 0.0438693735998662}. Best is trial 28 with value: 0.11253918950532307.

trial 68:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:16:07,370] Trial 68 finished with value: 0.11320187540152049 and parameters: {'num_leaves': 9, 'max_depth': 4, 'learning_rate': 0.008831841476391144, 'min_child_samples': 8, 'subsample': 0.8019576719994015, 'subsample_freq': 6, 'colsample_bytree': 0.46769696009147965, 'reg_alpha': 0.0003298156839026004, 'reg_lambda': 0.03309673144564635}. Best is trial 28 with value: 0.11253918950532307.

trial 69:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:16:10,740] Trial 69 pruned.

trial 70:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:16:15,406] Trial 70 finished with value: 0.11429059741973495 and parameters: {'num_leaves': 8, 'max_depth': 3, 'learning_rate': 0.013248075362421207, 'min_child_samples': 17, 'subsample': 0.7831506521690812, 'subsample_freq': 6, 'colsample_bytree': 0.4311537497118655, 'reg_alpha': 0.00020376755736193435, 'reg_lambda': 0.09980097152650587}. Best is trial 28 with value: 0.11253918950532307.

trial 71:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:16:21,665] Trial 71 finished with value: 0.11335187292296647 and parameters: {'num_leaves': 11, 'max_depth': 3, 'learning_rate': 0.008172112708423664, 'min_child_samples': 14, 'subsample': 0.7704441574738169, 'subsample_freq': 7, 'colsample_bytree': 0.43657907041987176, 'reg_alpha': 0.0007848722579904886, 'reg_lambda': 0.4886913857913433}. Best is trial 28 with value: 0.11253918950532307.

trial 72:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:16:28,540] Trial 72 finished with value: 0.1128024187450912 and parameters: {'num_leaves': 9, 'max_depth': 4, 'learning_rate': 0.007737032634177886, 'min_child_samples': 8, 'subsample': 0.770663916238211, 'subsample_freq': 6, 'colsample_bytree': 0.41088079344165807, 'reg_alpha': 8.711875108155015e-05, 'reg_lambda': 0.13633224395375673}. Best is trial 28 with value: 0.11253918950532307.

trial 73:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:16:34,075] Trial 73 finished with value: 0.11347189396616468 and parameters: {'num_leaves': 11, 'max_depth': 4, 'learning_rate': 0.010718864268457902, 'min_child_samples': 13, 'subsample': 0.7671674491016335, 'subsample_freq': 6, 'colsample_bytree': 0.4268807106247271, 'reg_alpha': 0.001866952216509946, 'reg_lambda': 0.10219398572290743}. Best is trial 28 with value: 0.11253918950532307.

trial 74:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:16:40,906] Trial 74 finished with value: 0.11311982522541171 and parameters: {'num_leaves': 11, 'max_depth': 3, 'learning_rate': 0.007291213272142006, 'min_child_samples': 7, 'subsample': 0.8292363619740171, 'subsample_freq': 7, 'colsample_bytree': 0.428038110241429, 'reg_alpha': 7.501253311778614e-05, 'reg_lambda': 0.14577382566815936}. Best is trial 28 with value: 0.11253918950532307.

trial 75:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:16:49,311] Trial 75 finished with value: 0.11321103660865266 and parameters: {'num_leaves': 10, 'max_depth': 3, 'learning_rate': 0.005148243030000968, 'min_child_samples': 9, 'subsample': 0.8039335436279503, 'subsample_freq': 7, 'colsample_bytree': 0.46324760579605184, 'reg_alpha': 0.000587731941354087, 'reg_lambda': 0.06850055687174324}. Best is trial 28 with value: 0.11253918950532307.

trial 76:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:16:56,164] Trial 76 finished with value: 0.11349622383034438 and parameters: {'num_leaves': 13, 'max_depth': 3, 'learning_rate': 0.006746286815232292, 'min_child_samples': 11, 'subsample': 0.7487257571342358, 'subsample_freq': 7, 'colsample_bytree': 0.46617077484261116, 'reg_alpha': 4.360782849670609e-05, 'reg_lambda': 0.3622012027024152}. Best is trial 28 with value: 0.11253918950532307.

trial 77:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:17:02,128] Trial 77 finished with value: 0.11415985010672558 and parameters: {'num_leaves': 9, 'max_depth': 4, 'learning_rate': 0.010937431376222061, 'min_child_samples': 12, 'subsample': 0.7798412888558967, 'subsample_freq': 6, 'colsample_bytree': 0.4448835651907254, 'reg_alpha': 0.0006512030203664008, 'reg_lambda': 2.134146536487598}. Best is trial 28 with value: 0.11253918950532307.

trial 78:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:17:08,406] Trial 78 finished with value: 0.11294811865209713 and parameters: {'num_leaves': 9, 'max_depth': 4, 'learning_rate': 0.009746332939407088, 'min_child_samples': 8, 'subsample': 0.7377773538785721, 'subsample_freq': 7, 'colsample_bytree': 0.435803124517228, 'reg_alpha': 3.126219765332917e-05, 'reg_lambda': 0.12641312662135462}. Best is trial 28 with value: 0.11253918950532307.

trial 79:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:17:16,001] Trial 79 finished with value: 0.11355304087040659 and parameters: {'num_leaves': 9, 'max_depth': 4, 'learning_rate': 0.006348186898202969, 'min_child_samples': 12, 'subsample': 0.7628192337127242, 'subsample_freq': 7, 'colsample_bytree': 0.4082012849043035, 'reg_alpha': 0.00024220273759096276, 'reg_lambda': 0.10584708634971675}. Best is trial 28 with value: 0.11253918950532307.

trial 80:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:17:22,575] Trial 80 finished with value: 0.11279282237392547 and parameters: {'num_leaves': 10, 'max_depth': 3, 'learning_rate': 0.008397922286684813, 'min_child_samples': 7, 'subsample': 0.7863009751150261, 'subsample_freq': 7, 'colsample_bytree': 0.429676594310754, 'reg_alpha': 0.00019367465441490341, 'reg_lambda': 0.47466864704737727}. Best is trial 28 with value: 0.11253918950532307.

trial 81:   0%|          | 0/10 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
[I 2026-09-14 01:17:30,571] Trial 81 finished with value: 0.11245714481885252 and parameters: {'num_leaves': 12, 'max_depth': 4, 'learning_rate': 0.006343873628352569, 'min_child_samples': 8, 'subsample': 0.7740606115988959, 'subsample_freq': 7, 'colsample_bytree': 0.40305278091678737, 'reg_alpha': 0.0001114933842526271, 'reg_lambda': 0.013407726240487437}. Best is trial 81 with value: 0.11245714481885252.

trial 0:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 01:22:55,863] Trial 0 finished with value: 0.11721924430319983 and parameters: {'depth': 7, 'learning_rate': 0.06965386533564681, 'l2_leaf_reg': 1.1016912119705573, 'random_strength': 0.004853853060450191, 'bagging_temperature': 0.6852769816973125, 'border_count': 218}. Best is trial 0 with value: 0.11721924430319983.

trial 1:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 01:25:28,850] Trial 1 finished with value: 0.11841383301554072 and parameters: {'depth': 5, 'learning_rate': 0.20891752562136418, 'l2_leaf_reg': 11.636108829315083, 'random_strength': 0.00575116485703084, 'bagging_temperature': 0.5542275911247871, 'border_count': 110}. Best is trial 0 with value: 0.11721924430319983.

trial 2:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 01:27:52,174] Trial 2 finished with value: 0.11711230608083012 and parameters: {'depth': 4, 'learning_rate': 0.1446868495147813, 'l2_leaf_reg': 26.6769262958003, 'random_strength': 0.008499916262600599, 'bagging_temperature': 0.08356143366334368, 'border_count': 167}. Best is trial 2 with value: 0.11711230608083012.

trial 3:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 01:55:14,400] Trial 3 finished with value: 0.1180490881928052 and parameters: {'depth': 8, 'learning_rate': 0.025588112116740704, 'l2_leaf_reg': 10.286805875183488, 'random_strength': 0.11788808060448733, 'bagging_temperature': 0.048484537426400576, 'border_count': 62}. Best is trial 2 with value: 0.11711230608083012.

trial 4:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 01:56:09,863] Trial 4 finished with value: 0.11836378175173276 and parameters: {'depth': 4, 'learning_rate': 0.294257882709626, 'l2_leaf_reg': 5.876055972782478, 'random_strength': 0.20661323703419787, 'bagging_temperature': 0.7348190582693819, 'border_count': 153}. Best is trial 2 with value: 0.11711230608083012.

trial 5:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 02:06:16,750] Trial 5 finished with value: 0.12846013759819547 and parameters: {'depth': 10, 'learning_rate': 0.15609752858268236, 'l2_leaf_reg': 3.938008609872663, 'random_strength': 0.026847099432508792, 'bagging_temperature': 0.9528767147108732, 'border_count': 108}. Best is trial 2 with value: 0.11711230608083012.

trial 6:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 02:17:22,217] Trial 6 finished with value: 0.12763550058006318 and parameters: {'depth': 9, 'learning_rate': 0.16843054580954112, 'l2_leaf_reg': 6.236339003766467, 'random_strength': 4.896406775966569, 'bagging_temperature': 0.09714647976501556, 'border_count': 55}. Best is trial 2 with value: 0.11711230608083012.

trial 7:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 02:20:44,537] Trial 7 finished with value: 0.12406666567409794 and parameters: {'depth': 8, 'learning_rate': 0.20670298179484656, 'l2_leaf_reg': 1.7206395921963602, 'random_strength': 0.01265581680126259, 'bagging_temperature': 0.6724915296568056, 'border_count': 68}. Best is trial 2 with value: 0.11711230608083012.

trial 8:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 02:37:53,453] Trial 8 finished with value: 0.11830863487089657 and parameters: {'depth': 8, 'learning_rate': 0.05251656974363662, 'l2_leaf_reg': 10.126132340893838, 'random_strength': 0.1219530789163864, 'bagging_temperature': 0.04339669443408434, 'border_count': 82}. Best is trial 2 with value: 0.11711230608083012.

trial 9:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 03:00:01,308] Trial 9 finished with value: 0.11751912313657613 and parameters: {'depth': 7, 'learning_rate': 0.015062432689334037, 'l2_leaf_reg': 5.479400282683755, 'random_strength': 0.0035648254775139474, 'bagging_temperature': 0.05280840108926621, 'border_count': 71}. Best is trial 2 with value: 0.11711230608083012.

trial 10:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 03:02:04,357] Trial 10 finished with value: 0.11701654176131933 and parameters: {'depth': 3, 'learning_rate': 0.07901053585857475, 'l2_leaf_reg': 12.417233699081484, 'random_strength': 0.07247616808693265, 'bagging_temperature': 0.0843973039690165, 'border_count': 142}. Best is trial 10 with value: 0.11701654176131933.

trial 11:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 03:06:26,354] Trial 11 finished with value: 0.11570319812024499 and parameters: {'depth': 4, 'learning_rate': 0.060702274884729616, 'l2_leaf_reg': 17.800058602061913, 'random_strength': 0.1622538397553613, 'bagging_temperature': 0.21549872538678505, 'border_count': 159}. Best is trial 11 with value: 0.11570319812024499.

trial 12:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 03:10:18,179] Trial 12 finished with value: 0.11622176013480323 and parameters: {'depth': 3, 'learning_rate': 0.046778433947855275, 'l2_leaf_reg': 10.064494382221433, 'random_strength': 0.14899610551444137, 'bagging_temperature': 0.058291631063264376, 'border_count': 176}. Best is trial 11 with value: 0.11570319812024499.

trial 13:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 03:13:50,660] Trial 13 finished with value: 0.11442725281384765 and parameters: {'depth': 3, 'learning_rate': 0.04065774041803912, 'l2_leaf_reg': 5.431137178081272, 'random_strength': 1.171412588799379, 'bagging_temperature': 0.03999430861417083, 'border_count': 222}. Best is trial 13 with value: 0.11442725281384765.

trial 14:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 03:16:56,774] Trial 14 finished with value: 0.1138407864779631 and parameters: {'depth': 3, 'learning_rate': 0.05893499448936648, 'l2_leaf_reg': 5.904359435244335, 'random_strength': 4.518934195521256, 'bagging_temperature': 0.13718054099871674, 'border_count': 209}. Best is trial 14 with value: 0.1138407864779631.

trial 15:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 03:18:24,990] Trial 15 finished with value: 0.11540018156792398 and parameters: {'depth': 3, 'learning_rate': 0.09872558357242542, 'l2_leaf_reg': 2.8004984054125566, 'random_strength': 0.8949001937417556, 'bagging_temperature': 0.024123812683063423, 'border_count': 231}. Best is trial 14 with value: 0.1138407864779631.

trial 16:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 03:24:27,938] Trial 16 finished with value: 0.11199472295327603 and parameters: {'depth': 4, 'learning_rate': 0.027380287153561927, 'l2_leaf_reg': 3.490909874831599, 'random_strength': 2.0640546856006625, 'bagging_temperature': 0.11621152647716818, 'border_count': 203}. Best is trial 16 with value: 0.11199472295327603.

trial 17:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 03:36:21,760] Trial 17 finished with value: 0.11159041611488114 and parameters: {'depth': 5, 'learning_rate': 0.014615500304705794, 'l2_leaf_reg': 2.698048510238601, 'random_strength': 1.2062499257433672, 'bagging_temperature': 0.003868299450135629, 'border_count': 189}. Best is trial 17 with value: 0.11159041611488114.

trial 18:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 03:48:41,793] Trial 18 finished with value: 0.11308409319639515 and parameters: {'depth': 5, 'learning_rate': 0.012692364048870036, 'l2_leaf_reg': 1.2975149761203324, 'random_strength': 0.48965057342294344, 'bagging_temperature': 0.07171247064747772, 'border_count': 146}. Best is trial 17 with value: 0.11159041611488114.

trial 19:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 03:59:43,639] Trial 19 finished with value: 0.11358126199909328 and parameters: {'depth': 6, 'learning_rate': 0.03655216132801585, 'l2_leaf_reg': 4.8778050998479285, 'random_strength': 3.581819638457284, 'bagging_temperature': 0.16340707788475328, 'border_count': 187}. Best is trial 17 with value: 0.11159041611488114.

trial 20:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 04:10:53,580] Trial 20 finished with value: 0.11208429961688297 and parameters: {'depth': 5, 'learning_rate': 0.01778521587655763, 'l2_leaf_reg': 2.17219788761274, 'random_strength': 2.6553014655792513, 'bagging_temperature': 0.14992311248977153, 'border_count': 253}. Best is trial 17 with value: 0.11159041611488114.

trial 21:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 04:31:00,879] Trial 21 finished with value: 0.1114898185799739 and parameters: {'depth': 5, 'learning_rate': 0.010697824794897698, 'l2_leaf_reg': 3.1264778595427596, 'random_strength': 9.241430733095818, 'bagging_temperature': 0.0010230992182795051, 'border_count': 232}. Best is trial 21 with value: 0.1114898185799739.

trial 22:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 04:47:44,054] Trial 22 finished with value: 0.11233374740653693 and parameters: {'depth': 5, 'learning_rate': 0.01104274293086562, 'l2_leaf_reg': 5.139989120655503, 'random_strength': 5.386732413244941, 'bagging_temperature': 0.3741575496221682, 'border_count': 234}. Best is trial 21 with value: 0.1114898185799739.

trial 23:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 04:54:14,628] Trial 23 finished with value: 0.11211128928900545 and parameters: {'depth': 3, 'learning_rate': 0.01658812500272126, 'l2_leaf_reg': 1.374349045185233, 'random_strength': 7.149941340243451, 'bagging_temperature': 0.08995271884481201, 'border_count': 253}. Best is trial 21 with value: 0.1114898185799739.

trial 24:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 05:05:20,761] Trial 24 finished with value: 0.11250469898984036 and parameters: {'depth': 5, 'learning_rate': 0.019365956149157763, 'l2_leaf_reg': 5.981227897411774, 'random_strength': 0.9093039907112249, 'bagging_temperature': 0.3131597449025818, 'border_count': 200}. Best is trial 21 with value: 0.1114898185799739.

trial 25:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 05:23:54,377] Trial 25 finished with value: 0.11411392058436627 and parameters: {'depth': 6, 'learning_rate': 0.012544314095373718, 'l2_leaf_reg': 3.26276726199325, 'random_strength': 0.22854517318722853, 'bagging_temperature': 0.05619314456105742, 'border_count': 232}. Best is trial 21 with value: 0.1114898185799739.

trial 26:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 05:30:02,327] Trial 26 finished with value: 0.11195642621376108 and parameters: {'depth': 5, 'learning_rate': 0.03449261232155887, 'l2_leaf_reg': 2.8449295810671633, 'random_strength': 0.9489190670121966, 'bagging_temperature': 0.02792010106595713, 'border_count': 154}. Best is trial 21 with value: 0.1114898185799739.

trial 27:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 05:36:28,587] Trial 27 finished with value: 0.11356504932849772 and parameters: {'depth': 5, 'learning_rate': 0.028683961115234816, 'l2_leaf_reg': 2.791447910075527, 'random_strength': 0.3551423995070692, 'bagging_temperature': 0.18860369970261082, 'border_count': 139}. Best is trial 21 with value: 0.1114898185799739.

trial 28:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 05:46:21,382] Trial 28 finished with value: 0.1111781323724644 and parameters: {'depth': 4, 'learning_rate': 0.015493876135308561, 'l2_leaf_reg': 2.2857825383077843, 'random_strength': 7.932624765679261, 'bagging_temperature': 0.010875787124807464, 'border_count': 190}. Best is trial 28 with value: 0.1111781323724644.

trial 29:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 06:00:21,842] Trial 29 finished with value: 0.11167124785852892 and parameters: {'depth': 5, 'learning_rate': 0.018853817003575038, 'l2_leaf_reg': 4.978784225071902, 'random_strength': 8.54656185995546, 'bagging_temperature': 0.0004378030205081044, 'border_count': 249}. Best is trial 28 with value: 0.1111781323724644.

trial 30:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 06:11:35,534] Trial 30 finished with value: 0.111155043463527 and parameters: {'depth': 5, 'learning_rate': 0.017677532894539993, 'l2_leaf_reg': 3.380065401193799, 'random_strength': 2.3578969587999103, 'bagging_temperature': 0.04034081621492492, 'border_count': 219}. Best is trial 30 with value: 0.111155043463527.

trial 31:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 06:25:09,589] Trial 31 finished with value: 0.11258255089113586 and parameters: {'depth': 5, 'learning_rate': 0.01593630151592992, 'l2_leaf_reg': 3.6941363454460685, 'random_strength': 6.733203877663122, 'bagging_temperature': 0.1746543726821887, 'border_count': 191}. Best is trial 30 with value: 0.111155043463527.

trial 32:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 06:39:47,445] Trial 32 finished with value: 0.11194269075185677 and parameters: {'depth': 5, 'learning_rate': 0.011539393957498156, 'l2_leaf_reg': 2.7588271005560525, 'random_strength': 2.994505418034857, 'bagging_temperature': 0.023793848972570805, 'border_count': 245}. Best is trial 30 with value: 0.111155043463527.

trial 33:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 06:52:05,168] Trial 33 finished with value: 0.11206211064266451 and parameters: {'depth': 4, 'learning_rate': 0.01099945206350092, 'l2_leaf_reg': 2.4308854958578316, 'random_strength': 5.918922826796789, 'bagging_temperature': 0.2579607644489916, 'border_count': 247}. Best is trial 30 with value: 0.111155043463527.

trial 34:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 06:59:44,184] Trial 34 finished with value: 0.11125542439987406 and parameters: {'depth': 4, 'learning_rate': 0.021927651502780417, 'l2_leaf_reg': 2.1669734164357326, 'random_strength': 6.221866354141101, 'bagging_temperature': 0.004433737315156861, 'border_count': 197}. Best is trial 30 with value: 0.111155043463527.

trial 35:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 07:04:32,258] Trial 35 finished with value: 0.11290521659498398 and parameters: {'depth': 3, 'learning_rate': 0.019578145970580694, 'l2_leaf_reg': 1.5336262339690196, 'random_strength': 4.581554821299428, 'bagging_temperature': 0.13466058957779656, 'border_count': 208}. Best is trial 30 with value: 0.111155043463527.

trial 36:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 07:12:12,532] Trial 36 pruned.

trial 37:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 07:22:11,334] Trial 37 finished with value: 0.1119587281089803 and parameters: {'depth': 4, 'learning_rate': 0.014234918908395944, 'l2_leaf_reg': 1.8880916903403853, 'random_strength': 5.262276115615511, 'bagging_temperature': 0.01976677092208701, 'border_count': 166}. Best is trial 30 with value: 0.111155043463527.

trial 38:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 07:44:21,781] Trial 38 finished with value: 0.1126322763445498 and parameters: {'depth': 6, 'learning_rate': 0.011171133128636889, 'l2_leaf_reg': 3.7553342701677206, 'random_strength': 3.990315474690785, 'bagging_temperature': 0.026264540927616167, 'border_count': 192}. Best is trial 30 with value: 0.111155043463527.

trial 39:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 07:51:09,865] Trial 39 pruned.

trial 40:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 07:58:52,743] Trial 40 finished with value: 0.11261154499169805 and parameters: {'depth': 4, 'learning_rate': 0.018512191331773738, 'l2_leaf_reg': 2.1480038246221924, 'random_strength': 1.0541995345045903, 'bagging_temperature': 0.014710694247440198, 'border_count': 236}. Best is trial 30 with value: 0.111155043463527.

trial 41:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 08:21:46,992] Trial 41 finished with value: 0.11248848093726085 and parameters: {'depth': 6, 'learning_rate': 0.014886745713343523, 'l2_leaf_reg': 3.2731347570025346, 'random_strength': 7.066024314197652, 'bagging_temperature': 0.026926307678241307, 'border_count': 228}. Best is trial 30 with value: 0.111155043463527.

trial 42:   0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-09-14 08:28:21,797] Trial 42 finished with value: 0.11260360067115201 and parameters: {'depth': 4, 'learning_rate': 0.01966356272888405, 'l2_leaf_reg': 2.362625214598672, 'random_strength': 2.0165371906675125, 'bagging_temperature': 0.09359726747002999, 'border_count': 213}. Best is trial 30 with value: 0.111155043463527.

trial 43:   0%|          | 0/10 [00:00<?, ?it/s]

[W 2026-09-14 08:32:10,273] Trial 43 failed with parameters: {'depth': 4, 'learning_rate': 0.012150474034779785, 'l2_leaf_reg': 5.407177857765772, 'random_strength': 0.8468801316196507, 'bagging_temperature': 0.0718088737238704, 'border_count': 223} because of the following error: KeyboardInterrupt('').
Traceback (most recent call last):
  File "d:\vs_projects\fp_houses\.venv\Lib\site-packages\optuna\study\_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\kochn\AppData\Local\Temp\ipykernel_24964\1285715589.py", line 25, in objective
    rmse, _ = run_one_fold(
              ~~~~~~~~~~~~^
        pipe,
        ^^^^^
    ...<7 lines>...
        early_stopping=early_stopping,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\kochn\AppData\Local\Temp\ipykernel_24964\2880402208.py", line 22, in run_one_fold
    model.fit(X_tr_t, y_tr, **fit_kwargs)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\vs_projects\fp_houses\.venv\Lib\site-packages\catboost\core.py", line 6178, in fit
    return self._fit(X, y, cat_features, text_features, embedding_features, None, graph, sample_weight, None, None, None, None, baseline,
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     use_best_model, eval_set, verbose, logging_level, plot, plot_file, column_description,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     verbose_eval, metric_period, silent, early_stopping_rounds,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\vs_projects\fp_houses\.venv\Lib\site-packages\catboost\core.py", line 2716, in _fit
    self._train(
    ~~~~~~~~~~~^
        train_pool,
        ^^^^^^^^^^^
    ...<3 lines>...
        train_params["init_model"]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\vs_projects\fp_houses\.venv\Lib\site-packages\catboost\core.py", line 1824, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_catboost.pyx", line 5430, in _catboost._CatBoost._train
  File "_catboost.pyx", line 5479, in _catboost._CatBoost._train
KeyboardInterrupt
[W 2026-09-14 08:32:10,289] Trial 43 failed with value None.

KeyboardInterrupt:

In [22]:
best_params = study_lgbm.best_params
rmses, fitted_pipes = run_confirm_cv(
    tree_pipe,
    build_lgbm,
    best_params,
    X_opt,
    y_opt,
    yb_opt,
    rskf_confirm,
    fit_extra_fn=lgbm_fit_extra,
)

hold_pred = np.mean([p.predict(X_hold) for p in fitted_pipes], axis=0)
hold_rmse = root_mean_squared_error(y_hold, hold_pred)
print(f"CV: {np.mean(rmses):.4f} ± {np.std(rmses):.4f}   Holdout: {hold_rmse:.4f}")

confirm cv:   0%|          | 0/50 [00:00<?, ?it/s]

d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\pandas\core\generic.py:6215: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x000001604B0B6020>
  object.__setattr__(self, name, value)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
d:\vs_projects\fp_houses\.venv\Lib\site-packages\pandas\core\generic.py:6215: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x000001604B104040>
  object.__setattr__(self, name, value)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
d:\vs_projects\fp_houses\.venv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

CV: 0.1122 ± 0.0154   Holdout: 0.1257

In [ ]:
# слишком долго, лучше провернуть трюк с одной моделью
best_params = study_cb.best_params
rmses, fitted_pipes = run_confirm_cv(
    tree_pipe,
    build_cb,
    best_params,
    X_opt,
    y_opt,
    yb_opt,
    rskf_confirm,
    fit_extra_fn=cb_fit_extra,
)

hold_pred = np.mean([p.predict(X_hold) for p in fitted_pipes], axis=0)
hold_rmse = root_mean_squared_error(y_hold, hold_pred)
print(f"CV: {np.mean(rmses):.4f} ± {np.std(rmses):.4f}   Holdout: {hold_rmse:.4f}")

confirm cv:   0%|          | 0/50 [00:00<?, ?it/s]

KeyboardInterrupt:

In [24]:
best_params = study_en.best_params
rmses, fitted_pipes = run_confirm_cv(
    lin_pipe,
    build_en,
    best_params,
    X_opt,
    y_opt,
    yb_opt,
    rskf_confirm,
    early_stopping=False,
)

hold_pred = np.mean([p.predict(X_hold) for p in fitted_pipes], axis=0)
hold_rmse = root_mean_squared_error(y_hold, hold_pred)
print(f"CV: {np.mean(rmses):.4f} ± {np.std(rmses):.4f}   Holdout: {hold_rmse:.4f}")

confirm cv:   0%|          | 0/50 [00:00<?, ?it/s]

CV: 0.1082 ± 0.0123   Holdout: 0.1127